### ISSUE TITLE
Error: starting container ... setting up Pasta: pasta failed with exit code 1

### ISSUE THREAD

**Issue by paulrenn67** [containers/podman#22015] opened 2024-03-11 20:46 UTC
### Issue Description

Hi,

I'm new to Podman, and trying to setup a new server with only a basic Debian 12 install.  I spent a while configuring the server, trying to load all the dependencies needed for Podman, upgraded Go, and Podman should be the latest:

```
Client:       Podman Engine
Version:      5.0.0-dev
API Version:  5.0.0-dev
Go Version:   go1.22.1
Git Commit:   38e22d443cc4ba0300712fa6532c79730b829f21
Built:        Mon Mar 11 19:39:45 2024
OS/Arch:      linux/amd64
```

I'm attempting to install a rootless user, and I'm finally at a place where I can actually create and attempt to start a pod.

```
podman network create test-network
podman pod create --name psp-pod --network test-network 
```

However, Pasta networking fails at startup, here is output from `podman pod start psp-pod --log-level=debug`

```
INFO[0000] podman filtering at log level debug
DEBU[0000] Called start.PersistentPreRunE(podman pod start psp-pod --log-level=debug)
DEBU[0000] Using conmon: "/usr/bin/conmon"
INFO[0000] Using sqlite as database backend
DEBU[0000] systemd-logind: Unknown object '/'.
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/psp/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/psp/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/psp/.local/share/containers/storage/volumes
DEBU[0000] Using transient store: false
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that metacopy is not being used
DEBU[0000] Cached value indicated that native-diff is usable
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false
DEBU[0000] Initializing event backend journald
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument
DEBU[0000] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument
DEBU[0000] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument
DEBU[0000] Configured OCI runtime crun-vm initialization failed: no valid executable found for OCI runtime crun-vm: invalid argument
DEBU[0000] Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument
DEBU[0000] Using OCI runtime "/usr/bin/crun"
INFO[0000] Setting parallel job count to 49
DEBU[0000] Strongconnecting node 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964
DEBU[0000] Pushed 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964 onto stack
DEBU[0000] Finishing node 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964. Popped 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964 off stack
DEBU[0000] Cached value indicated that idmapped mounts for overlay are not supported
DEBU[0000] Made network namespace at /run/user/1000/netns/netns-8238d692-8b38-1c9b-7cae-83eb84bc3852 for container 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964
DEBU[0000] Check for idmapped mounts support
DEBU[0000] overlay: mount_data=lowerdir=/home/psp/.local/share/containers/storage/overlay/l/BK6K7MHETGSAMGGN5DHK5PRYGQ,upperdir=/home/psp/.local/share/containers/storage/overlay/f4267117530de68e42c6edef8bb7a81a5662f3f0cb708f39ca2baa1b61f95efb/diff,workdir=/home/psp/.local/share/containers/storage/overlay/f4267117530de68e42c6edef8bb7a81a5662f3f0cb708f39ca2baa1b61f95efb/work,userxattr
DEBU[0000] Mounted container "2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964" at "/home/psp/.local/share/containers/storage/overlay/f4267117530de68e42c6edef8bb7a81a5662f3f0cb708f39ca2baa1b61f95efb/merged"
DEBU[0000] Successfully loaded network test-network: &{test-network 0932e8bed08d20d078792b39e9dbad47d1e1ba5de0482b12a5eabf71ccd371e0 bridge podman1 2024-03-11 20:17:16.380692008 +0100 CET [{{{10.89.0.0 ffffff00}} 10.89.0.1 <nil>}] [] false false true [] map[] map[] map[driver:host-local]}
DEBU[0000] Successfully loaded 2 networks
DEBU[0000] Created root filesystem for container 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964 at /home/psp/.local/share/containers/storage/overlay/f4267117530de68e42c6edef8bb7a81a5662f3f0cb708f39ca2baa1b61f95efb/merged
DEBU[0000] Creating rootless network namespace at "/run/user/1000/containers/networks/rootless-netns/rootless-netns"
DEBU[0000] pasta arguments: --config-net --pid /run/user/1000/containers/networks/rootless-netns/rootless-netns-conn.pid -t none -u none -T none -U none --no-map-gw --dns none --quiet --netns /run/user/1000/containers/networks/rootless-netns/rootless-netns
DEBU[0000] Unmounted container "2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964"
DEBU[0000] Network is already cleaned up, skipping...
DEBU[0000] Cleaning up container 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964
DEBU[0000] Network is already cleaned up, skipping...
DEBU[0000] Container 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964 storage is already unmounted, skipping...
Error: starting container 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964: setting up Pasta: pasta failed with exit code 1:
Couldn't open network namespace /run/user/1000/containers/networks/rootless-netns/rootless-netns
```

Checking the rootless-netns file, it is empty:

```
psp@primary:~$ ls -l /run/user/1000/containers/networks/rootless-netns/rootless-netns
-rw------- 1 psp psp 0 Mar 11 21:08 /run/user/1000/containers/networks/rootless-netns/rootless-netns
```

Not sure how to continue further, does anybody have any clues?  Happy to assist and provide any further information if required!

Thanks in advance,
Paul

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install clean version of Debian 12
2. Install a ton of packages required by Podman (mostly 
3. Upgrade to latest version of Go
4. Compiled Podman from source (mostly followed instructions here https://podman.io/docs/installation)
5. Attempt to start a pod
6. Tear out last remaining hair

### Describe the results you received

Error: starting container 2ba3568f71cfd3779ebfbc53ccfeb084e539605c2f3299ef4630f9ba8a743964: setting up Pasta: pasta failed with exit code 1:
Couldn't open network namespace /run/user/1000/containers/networks/rootless-netns/rootless-netns

### Describe the results you expected

Pod should start cleanly

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.35.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.6+ds1-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: unknown'
  cpuUtilization:
    idlePercent: 99.95
    systemPercent: 0.03
    userPercent: 0.02
  cpus: 16
  databaseBackend: sqlite
  distribution:
    codename: bookworm
    distribution: debian
    version: "12"
  eventLogger: journald
  freeLocks: 2046
  hostname: primary.my-hostname.io
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.1.0-18-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 133924184064
  memTotal: 134750760960
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns_1.4.0-3_amd64
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.4.0
    package: netavark_1.4.0-3_amd64
    path: /usr/lib/podman/netavark
    version: netavark 1.4.0
  ociRuntime:
    name: crun
    package: crun_1.8.1-1+deb12u1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt_0.0~git20230309.7c7625d-1_amd64
    version: |
      pasta unknown version
      Copyright Red Hat
      GNU Affero GPL version 3 or later <https://www.gnu.org/licenses/agpl-3.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4289720320
  swapTotal: 4289720320
  uptime: 1h 41m 1.00s (Approximately 0.04 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/psp/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/psp/.local/share/containers/storage
  graphRootAllocated: 229732732928
  graphRootUsed: 5696118784
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/psp/.local/share/containers/storage/volumes
version:
  APIVersion: 5.0.0-dev
  Built: 1710182385
  BuiltTime: Mon Mar 11 19:39:45 2024
  GitCommit: 38e22d443cc4ba0300712fa6532c79730b829f21
  GoVersion: go1.22.1
  Os: linux
  OsArch: linux/amd64
  Version: 5.0.0-dev
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment] 2024-03-12 10:41
Yes I think the old pasta version is the problem, we test with debian sid in CI so this should work fine with the lastest passt version.

**Comment by afbjorklund** [comment] 2024-03-12 14:22
Pasta doesn't seem to be documented _anywhere_ under https://podman.io/docs/installation#building-from-source

```yaml
  pasta:
    executable: ""
    package: ""
    version: ""
```

**Comment by paulrenn67** [comment] 2024-03-12 15:15
Sorry guys, wasn't able to continue with this.  I downgraded podman first to 4.9.3 and then to 4.1.0 (which matches another server we use) finally I was able to get the server running.  Unfortunately my woes continue, not able to connect to the machine from my Mac, I have configured networks thus:
```
Name                         URI                                                         Identity                                    Default
my_podman_server             ssh://psp@XX.XX.XX.XX:22/run/podman/podman.sock           /Users/me/.ssh/id_ed25519     false
podman-machine-default       ssh://core@127.0.0.1:49764/run/user/503/podman/podman.sock  /Users/canapay/.ssh/podman-machine-default  true
podman-machine-default-root  ssh://root@127.0.0.1:49764/run/podman/podman.sock           /Users/canapay/.ssh/podman-machine-default  false
```

I am able to ssh into `my_podman_server` directly without password having added the key to the remote machine and to my Mac's ssh agent.  However, any attempt to upload an image to the server always fails as follows (and adding `my_podman_server` to my `etc/hosts` did not help):
```
podman --ssh=native image scp localhost/whatever/psp:prod my_podman_server:22:: --log-level=debug
INFO[0000] podman filtering at log level debug
DEBU[0000] Called scp.PersistentPreRunE(podman --ssh=native image scp localhost/whatever/psp:prod my_podman_server:22:: --log-level=debug)
DEBU[0000] SSH Ident Key "/Users/me/.ssh/podman-machine-default" SHA256:my-key ssh-ed25519
DEBU[0000] DoRequest Method: GET URI: http://d/v4.9.3/libpod/_ping
DEBU[0000] DoRequest Method: POST URI: http://d/v4.9.3/libpod/images/scp/localhost/whatever/psp:prod
Error: failed to connect: dial tcp: lookup my_podman_server: no such host
DEBU[0004] Shutting down engines
```

Incidentally, if I don't supply the :22 port number on the image scp command, I get the following, which I thought I read was fixed a while back (I have podman 4.9.3 on my Mac):
```
Error: strconv.Atoi: parsing "": invalid syntax
```

If I can't get this to work today then going to resort to old fashioned scp'ing and bash scripts :/

**Comment by Luap99** [comment] 2024-03-12 15:42
@afbjorklund Well updates to the docs are always welcome as you know. Feel free to report that on podman.io repo, the install instructions haven't been updated in a while.

**Comment by Luap99** [comment] 2024-03-12 15:45
@paulrenn67 I am going to close this one then assuming it will work with the lastest pasta version.

If you have other problems please make sure to file separate issues. The port thing was fixed in https://github.com/containers/podman/pull/21583 AFAIK and should be fixed in 5.0 and was backported to 4.9, it will in a future 4.9.4.

**Closed by Luap99** 2024-03-12 15:45 UTC
Labels: kind/bug, network, pasta

**Comment by sbrivio-rh** [comment] 2024-03-12 16:28
> I downgraded podman first to 4.9.3 and then to 4.1.0 (which matches another server we use) finally I was able to get the server running

By the way, there isn't really a need to downgrade anything. To install a single Debian package from testing or unstable there are a number of established ways, but given that passt has no dependencies, you could keep it quick and just `dpkg -i` a package you would download from https://packages.debian.org/trixie/amd64/passt/download.

**Comment by afbjorklund** [comment] 2024-03-12 17:36
As usual, the package versions vary a bit between the distribution and releases.

* https://packages.ubuntu.com/passt (not in 20.04, not in 22.04, but in 24.04)

* https://packages.debian.org/passt

Well, once you find out that 1) you need `pasta` and 2) it is in the `passt`package

**Comment by sbrivio-rh** [comment] 2024-03-12 17:48
> As usual, the package versions vary a bit between the distribution and releases.
> 
>  * https://packages.ubuntu.com/passt (not in 20.04, not in 22.04, but in 24.04)

Yes, I just maintain the Debian package, and rely on automatic Ubuntu imports which happen before every import freeze (https://wiki.ubuntu.com/DebianImportFreeze). The first Ubuntu version where this happened was 23.04.

> * https://packages.debian.org/passt
> 
> 
> Well, once you find out that 1) you need `pasta` and 2) it is in the `passt`package

Point 1) is a distribution matter I think -- I wouldn't know how to improve on it. On Debian, for example, Podman recommends the passt package.

About 2):

```
$ apt-cache search pasta | grep passt
passt - user-mode networking daemons for virtual machines and namespaces
```

...how bad can it be?

**Comment by sbrivio-rh** [comment] 2024-03-12 19:23
> It could still be worth a line in the install documentation.

Absolutely, I'm grateful you reported https://github.com/containers/podman.io/issues/285 and I think that should be fixed. I'm just not sure we can improve much on those two points you raised above (outside of the documentation, I mean).

**Comment by afbjorklund** [comment] 2024-03-12 19:38
They are not too bad to install from source, don't even need to venture into Cargo Hell and set up rustc and so on :-D

**Comment by sbrivio-rh** [comment] 2024-03-12 19:53
```git clone git://passt.top/passt && sudo make -C passt install``` should do it. :)

**Comment by Luap99** [comment] 2024-03-12 20:00
Isn't there a way to setup an alias for package names? So that a dnf install pasta would install passt. I think for rpm setting a `Provides: pasta` might do it. Not sure if there is a option for deb packages.

The podman error message could also say `could not find pasta (package passt)...` if others think that helps. But yeah in general a user will install podman and passt should be installed as dep, we were just talking today that passt needs to be a requirement for podman given it is now the default with 5.0.

That said of course our install instructions need to mention it.

**Comment by afbjorklund** [comment] 2024-03-12 20:15
I think it wasn't a requirement previously, because you could (in theory) run everything with `--network=none`.

**Comment by afbjorklund** [comment] 2024-03-12 20:17
The main issue here is the version breakage, which means it will need to get dumped into `libexec/podman`

**Comment by Luap99** [comment] 2024-03-12 20:34
> I think it wasn't a requirement previously, because you could (in theory) run everything with --network=none.

And this is what we discussed and decided that it should be a requires because by default podman run wouldn't work.

> The main issue here is the version breakage, which means it will need to get dumped into libexec/podman

What breakage? We need a recent passt and that is to be expected. I do not see anything wrong with that or what we would gain by moving it into a different location (and yes we already check libexec/podman for pasta).
Bugs happen and are only fix by updating to newer versions. If a stable disto chooses to never update this is not something upstream can help with.

**Comment by afbjorklund** [comment] 2024-03-12 21:02
Just saying that it would be nice if it was possible to check the "API" versions of the dependencies, that's all.

**Comment by sbrivio-rh** [comment] 2024-03-12 21:40
> Just saying that it would be nice if it was possible to check the "API" versions of the dependencies, that's all.

But the issue at hand was really an issue in pasta -- not an intended behaviour or an API change. We're being really careful with functional changes and so far I think we avoided to introduce any (deliberate) breakage.

> Then again passt doesn't even seem to have any versions. The tags seems to be mostly based on date/commit.

Those are the actual versions: passt doesn't use semantic versioning. You have the ISO-8601 date so you know (approximately) when the release was made, and 7 digits of git SHA you can use to quickly navigate the code from a given release. I personally find that more meaningful than "passt 3.11" or suchlike.

**Comment by sbrivio-rh** [comment] 2024-03-12 21:54
> Isn't there a way to setup an alias for package names? So that a dnf install pasta would install passt. I think for rpm setting a `Provides: pasta` might do it. Not sure if there is a option for deb packages.

I have to look into this. On Debian there are virtual packages (https://www.debian.org/doc/debian-policy/ch-relationships.html#s-virtual), but they're mostly used to represent possible alternatives providing similar functionality, and especially satisfying a dependency. On RPM-based distributions, `Provides:` might do the trick, but I have to test it.

**Comment by alexanderadam** [comment] 2024-06-07 19:42
What's the solution for installing podman in `brew`?

Previously I could install Podman 4.x on Ubuntu without any issues.
However, since [the recent Podman updates](https://github.com/Homebrew/homebrew-core/pull/173714) I'm also running into the issue that [Podman requires `pasta`](https://bugzilla.redhat.com/show_bug.cgi?id=2269148) which doesn't seem to come with [the installation](https://formulae.brew.sh/formula/podman) and it [doesn't seem to be available either](https://duckduckgo.com/?t=h_&q=%2B%22pasta%22+site%3Ahttps%3A%2F%2Fformulae.brew.sh).

**Comment by sbrivio-rh** [comment] 2024-06-07 19:57
> Previously I could install Podman 4.x on Ubuntu without any issues. However, since [the recent Podman updates](https://github.com/Homebrew/homebrew-core/pull/173714) I'm also running into the issue that [Podman requires `pasta`](https://bugzilla.redhat.com/show_bug.cgi?id=2269148)

Can't you install pasta using the official Ubuntu [package](https://launchpad.net/ubuntu/+source/passt)?

**Comment by alexanderadam** [comment] 2024-06-07 20:59
It doesn't look like I could:

![vagrant@vagrantvm:~$ sudo apt show passt N: Unable to locate package passt N: Unable to locate package passt E: No packages found](https://github.com/containers/podman/assets/372620/5dc097a9-005a-4635-be26-ce48d4b682d6)

**Comment by sbrivio-rh** [comment] 2024-06-07 21:17
> It doesn't look like I could:
> 
> ![vagrant@vagrantvm:~$ sudo apt show passt N: Unable to locate package passt N: Unable to locate package passt E: No packages found](https://private-user-images.githubusercontent.com/372620/337790944-5dc097a9-005a-4635-be26-ce48d4b682d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTUyODgsIm5iZiI6MTcxNzc5NDk4OCwicGF0aCI6Ii8zNzI2MjAvMzM3NzkwOTQ0LTVkYzA5N2E5LTAwNWEtNDYzNS1iZTI2LWNlNDhkNGI2ODJkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QyMTE2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjg0MTE0M2MyNmYzZjA5MjEwNjk2MzljODIwNmFiNjdmOTRkMzY3ODkxN2RhYTFjMTk0NDAwNWZkZGFkNDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QloFy5bXh8PriKdPD7YvThCvRD0NWj_R0hMAelMQ7RI)

I guess your Ubuntu version is too old to contain any version? In that case, I guess you can install a single package from a newer Ubuntu version.

**Comment by alexanderadam** [comment] 2024-06-07 21:49
I think getting recent packages of the Podman ecosystem is generally difficult since there aren't any stable and new ones any more as far as I know.

And I think it's even more difficult for pasta.
Furthermore `brew` isn't only available on Ubuntu but pretty much every OS/X and ever Linux.
And right now `brew` delivers a Podman version that requires `pasta` without giving a possibilty to install it.
So this might be a default configuration or dependency bug, or am I missing a bit here?

Apart from that mixing package sources might lead to further problems as well.

But I don't have a strong Podman background so I might misunderstand the constraints here. :wink: 

**PS:** thank you for your quick answer by the way! I really appreciate this!

**Comment by sbrivio-rh** [comment] 2024-06-08 11:01
> I think getting recent packages of the Podman ecosystem is generally difficult since there aren't any stable and new ones any more as far as I know.
> 
> And I think it's even more difficult for pasta.

It shouldn't be, it's a much smaller/simpler beast with fewer interactions, and zero dependencies other than a standard C library. There are updated [packages](https://repology.org/project/passt/packages) for many distributions.

> Furthermore `brew` isn't only available on Ubuntu but pretty much every OS/X and ever Linux.

Sure, it would be nice to have a Homebrew package as well, but I already maintain passt/pasta packages for a few distributions, including the one for Debian (which periodically gets synchronised with Ubuntu), so I guess you would have to find somebody interested in maintaining that. I hope you have more luck on https://github.com/Homebrew/homebrew-core/pull/173714.

> And right now `brew` delivers a Podman version that requires `pasta` without giving a possibilty to install it. So this might be a default configuration or dependency bug, or am I missing a bit here?

I don't think that Homebrew ships every single dependency of Podman. For example, I'm fairly sure you can't run Podman on Linux without Bash, but Bash isn't taken care of in Podman's Homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/5bdbd2bdad83fae5a9390f3a92dc6613cc87158a/Formula/p/podman.rb).

Some things are just system dependencies (pasta could be one of them as well) and maybe there is a way to list them as such (`depends_on` without `=> :build`?). Perhaps Podman 5.1.1 shipped by Homebrew should require a minimum Ubuntu version, too? I'm not sure.

**Comment by YevheniiPokhvalii** [comment] 2024-07-07 20:10
https://github.com/Homebrew/homebrew-core/issues/173699
