### ISSUE TITLE
Unable to connect to Podman socket

### ISSUE THREAD

**Issue by pironev** [containers/podman#24753] opened 2024-12-04 07:38 UTC
### Issue Description

I am using podman on MacOS Sequoia 15.1.1 Apple M1 Max.
OS: darwin/arm64
provider: applehv
version: 5.3.0

Running  `podman compose up` I receive this error message:
```
Cannot connect to Podman. Please verify your connection to the Linux system using 
`podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to read identity "~/.ssh/id_rsa_pv2": open ~/.ssh/id_rsa_pv2: no such file or directory
```
I remove and recreate podman-machine-default - the same result.
This file ~/.ssh/id_rsa_pv2  exists and can be read, but Podman reporting it doesn't.

Thank you

**Comment by Luap99** [comment] 2024-12-04 10:47
Duplicate of #24567

**Closed by Luap99** 2024-12-04 10:47 UTC
Labels: kind/bug
