### ISSUE TITLE
Aardvark Test 2: Two containers, same subnet

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14173] opened 2022-05-09 21:18 UTC
```
Aardvark Test 2: Two containers, same subnet
...

Expected
               <[]string | len:0, cap:0>: nil
           to have length 2
         
           /var/tmp/go/src/github.com[/containers/podman/test/e2e/run_aardvark_test.go:105](https://github.com/containers/podman/blob/bb8f53a727aeebb49873b2f4c9c12d6f1d0ce1d3/test/e2e/run_aardvark_test.go#L105)
```
### Podman run networking [It] Aardvark Test 2: Two containers, same subnet 
* fedora-35 : Netavark int podman root
  * PR #13744
    * [04-01 05:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4916207047409664/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [04-01 05:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4916207047409664/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
    * [04-01 05:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4916207047409664/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--3)
  * PR #13662
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--3)
  * PR #13575
    * [03-21 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4749337602293760/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [03-21 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4749337602293760/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
* fedora-36 : int podman fedora-36 root container
  * PR #14152
    * [05-08 12:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5421609321234432/html/int-podman-fedora-36-root-container.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
* fedora-36 : int podman fedora-36 root host
  * PR #14040
    * [04-28 08:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5047243462934528/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [04-28 08:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5047243462934528/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)

**Comment by vrothberg** [comment] 2022-05-18 10:23
@flouthoc @Luap99 in case you have/find time.

**Comment by flouthoc** [comment] 2022-05-20 10:13
I am unable to reproduce this flake on host not entirely sure but I think know why this happens on CI.

One root cause could be that  `netavark` spawns `aardvark-dns` using `Command::spawn()` and never waits for it especially in case of `systemd-run`. Usually it does not makes any difference since by the time podman actually runs command on container , `aardvark-dns` should be ready but on CI env on certain runs we are surpassing this window.

I think adding a backoff on netavark end should help here. Something like this: https://github.com/containers/podman/issues/14173

**Comment by flouthoc** [comment] 2022-05-20 10:28
PS: Also while running tests on host I am only running `test/e2e/run_networking_test.go test/e2e/run_aardvark_test.go` with commons assuming that tests are isolated with each other they share nothing.

**Comment by edsantiago** [comment] 2022-06-13 21:19
### Podman run networking [It] Aardvark Test 2: Two containers, same subnet 
* fedora-36 : int podman fedora-36 root host
  * PR #14533
    * [06-09 10:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5797344032587776/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [06-09 10:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5797344032587776/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
    * [06-09 10:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5797344032587776/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--3)
  * PR #14478
    * [06-03 10:40](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5342622389633024/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [06-03 10:40](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5342622389633024/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
  * PR #14477
    * [06-03 09:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6481516686475264/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
  * PR #14344
    * [06-01 13:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4833114949156864/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [06-01 13:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4833114949156864/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
    * [06-01 13:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4833114949156864/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--3)
  * PR #14329
    * [05-25 14:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4505005989298176/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [05-25 14:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4505005989298176/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
    * [05-25 14:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4505005989298176/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--3)
  * PR #14256
    * [05-16 12:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4750591279759360/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [05-16 12:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4750591279759360/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14455
    * [06-02 09:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4795978581540864/html/int-remote-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [06-02 09:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4795978581540864/html/int-remote-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
    * [06-02 09:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4795978581540864/html/int-remote-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--3)

**Comment by flouthoc** [comment] 2022-06-14 09:52
There is a bigger design change under discussion which should help in this as well as some other issue, please track it here. However it will take some time to get merged: https://github.com/containers/aardvark-dns/pull/148

**Comment by Luap99** [comment] 2022-07-04 14:11
The netavark/aardvark changes are fine but I don't think it is required to fix this flake in CI. The test already "tries" to implement a back off logic:
https://github.com/containers/podman/blob/6dffa453a4c62a183526e22ac5c099f02b6c6f0e/test/e2e/common_test.go#L1045-L1062

This does not work because dig always returns exit code 0 even when there is no match.

**Closed** 2022-07-04 16:50 UTC
Labels: flakes

**Comment by edsantiago** [comment] 2022-07-07 12:25
I'm still seeing flakes on this test, and I'm somewhat sure that it's after the "fix" merged. Error message seems different:
```
dns is not responding
```
Shall I file a new issue?

### Podman run networking [It] Aardvark Test 2: Two containers, same subnet 
* fedora-36 : int podman fedora-36 root host
  * PR #14841
    * [07-06 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6095397528535040/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--1)
    * [07-06 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6095397528535040/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--2)
    * [07-06 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6095397528535040/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-2--Two-containers--same-subnet--3)

**Comment by edsantiago** [comment] 2022-07-14 16:36
New set of symptoms in [remote f36 root](https://api.cirrus-ci.com/v1/artifact/task/6300287030788096/html/int-remote-fedora-36-root-host.log.html):
```
Execing /usr/sbin/ip netns add XVlBzgbaiCMR

Cannot create namespace file "/var/run/netns/XVlBzgbaiCMR": File exists
```
The surprising thing about this is that a *lot* of tests fail, and all of them have the same presumably-random string. I would expect each test to have a unique string. Whoever groks the random-netns-name code, that might be a good starting place to look.

**Comment by edsantiago** [comment] 2022-07-14 16:37
Renaming & repurposing this issue as a general place to log \*vark flakes

**Comment by Luap99** [comment] 2022-07-14 16:41
> New set of symptoms in [remote f36 root](https://api.cirrus-ci.com/v1/artifact/task/6300287030788096/html/int-remote-fedora-36-root-host.log.html):
> 
> ```
> Execing /usr/sbin/ip netns add XVlBzgbaiCMR
> 
> Cannot create namespace file "/var/run/netns/XVlBzgbaiCMR": File exists
> ```
> 
> The surprising thing about this is that a _lot_ of tests fail, and all of them have the same presumably-random string. I would expect each test to have a unique string. Whoever groks the random-netns-name code, that might be a good starting place to look.

This should not effect netavark/aardvark at all, using a custom net namespace will never call into the network backend.

**Comment by edsantiago** [comment] 2022-07-18 22:27
Another one, this time [podman (non-remote) f36 root](https://api.cirrus-ci.com/v1/artifact/task/5684895023366144/html/int-podman-fedora-36-root-host.log.html), same "file exists" symptom
