### ISSUE TITLE
No limitations when starting multiple machines with WSL

### ISSUE THREAD

**Issue by lstocchi** [containers/podman#18415] opened 2023-05-02 12:09 UTC
### Issue Description

Not sure if it's a bug or something that should work this way.
In Podman Desktop we noticed that Mac users can only start one machine while on Windows there is no limitations. 
is it done on purpose?

### Steps to reproduce the issue

Steps to reproduce the issue
1. start two or more machines on Windows
2. no error displayed

### Describe the results you received

N/A

### Describe the results you expected

I would expect to see an error message when starting a machine if another one is already running

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.85
    systemPercent: 0.09
    userPercent: 0.06
  cpus: 12
  databaseBackend: ""
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: journald
  hostname: LucaW11
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 15704739840
  memTotal: 16646250496
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.3-2.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 0h 10m 21.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 0
    stopped: 10
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269427478528
  graphRootUsed: 7028027392
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 11
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.4
  Built: 1680521485
  BuiltTime: Mon Apr  3 13:31:25 2023
  GitCommit: ""
  GoVersion: go1.19.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment] 2023-05-02 12:39
I don't see a reason why you shouldn't be allowed to run more than one VM at the same time. I am not sure why it is limited on macos.
@baude @ashley-cui PTAL

**Comment by ashley-cui** [comment] 2023-05-02 12:41
That's by design, it doesn't make sense to run more than one VM at a time since you would have to either specify the connection every time you run a podman command or constantly change connections. At that point, it's probably easier to just boot up the correct machine. I think windows should be fixed to only allow one VM, as that's what happens on Mac and Linux

**Comment by Luap99** [comment] 2023-05-02 12:49
But what is that problem with specifying the connection every time? I see no problem with allowing this as a use case. Consider something like one machine per project you are working on. I could easily set the connection env var in my shell and then have two windows for both projects were you could work in parallel.

General speaking changing this now for windows is a breaking change as existing users relying on multiple VMs at once will be broken if you start blocking this.

**Comment by rhatdan** [comment] 2023-05-02 20:38
I think we should allow multiple machines as well, especially as we move towards supporting multiple Arches.
On a M2 MAC, I could have a machine running Arm and another running X86, then I would want to build an image for both arches without using qemu-user-static.

**Comment by baude** [comment] 2023-05-17 14:51
we cannot allow multiple machines without retooling a number of things, some of which we do not own.  if we need to do this, then we need create an epic and get all the things gathered up to do so.

**Comment by ashley-cui** [comment] 2023-05-17 14:54
I'll fix up windows to match Mac/Linux behavior for consistency (I'd argue this is a bug) and if we want, we can change this later as an epic.

**Comment by ashley-cui** [comment] 2023-05-17 17:27
It's in our docs, so I'd still see it as a bugfix: https://github.com/containers/podman/blob/2c6c5d4becfb049c6acf11f5aa0cbe69581539ae/docs/source/markdown/podman-machine-start.1.md?plain=1#L23

**Comment by Luap99** [comment] 2023-05-17 18:09
But what is the bug? Taking away functionality for no benefit doesn't sound like a good idea to me. Just because it is documented doesn't mean changing it will not break people.

**Comment by rhatdan** [comment] 2023-05-18 21:05
Why not change the documentation to say that podman on Window WSL2 can support multiple machines.

**Comment by rhatdan** [comment] 2023-06-20 20:52
Someone interested in opening a Docs PR?

**Comment by vrothberg** [comment] 2023-08-01 13:09
It's definitely something to think about.  The upcoming `podman buildfarm` command would benefit a lot if the limitation of 1 running machine would be dropped.

**Comment by baude** [comment] 2023-08-29 13:42
i think this must be for WSL?  For hyperv, you cannot start more than one:

```
PS C:\Users\baude\go\src\github.com\containers\podman> .\bin\windows\podman.exe machine start foobar
Error: cannot start VM foobar. VM podman-machine-default is currently running or starting: only one VM can be active at a time
```

I'll keep digging for wsl

**Closed as completed** 2023-08-29 15:15 UTC
Labels: kind/bug, documentation, remote, machine, podman-desktop, locked - please file new issue/PR
