### ISSUE TITLE
Podman hangs on build

### ISSUE THREAD

**Issue by CoenraadS** [containers/podman#24427] opened 2024-10-31 03:28 UTC
Dupe of https://github.com/containers/podman/issues/17628 which is closed without resolution.

Dockerfile
```Dockerfile
# Start from the latest Ubuntu image
FROM ubuntu:latest

# Install required dependencies and .NET SDK
RUN apt-get update && apt-get install -y dotnet-sdk-8.0
RUN dotnet tool install --global dotnet-dump
```

`podman build --log-level debug -t example .`
```
time="2024-10-31T14:19:31+11:00" level=info msg="podman filtering at log level debug"
time="2024-10-31T14:19:31+11:00" level=debug msg="Called build.PersistentPreRunE(podman build --log-level debug -t example .)"
time="2024-10-31T14:19:31+11:00" level=debug msg="SSH Ident Key \"C:\\\\Users\\\\coenraad.stijne\\\\.local\\\\share\\\\containers\\\\podman\\\\machine\\\\machine\" SHA256:V80r6QgNxmafGHg9JINaP+Ww53MH8ac7f58JNPzQ/nA ssh-ed25519"
time="2024-10-31T14:19:31+11:00" level=debug msg="DoRequest Method: GET URI: http://d/v5.2.5/libpod/_ping"
time="2024-10-31T14:19:31+11:00" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
time="2024-10-31T14:19:31+11:00" level=debug msg="DoRequest Method: POST URI: http://d/v5.2.5/libpod/build"
```

podman info
```
host:
  arch: amd64
  buildahVersion: 1.37.2
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.10-1.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 98.88
    systemPercent: 0.49
    userPercent: 0.63
  cpus: 4
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: container
    version: "40"
  eventLogger: journald
  freeLocks: 2045
  hostname: ir-n-coenraad
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 5.15.153.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 5355347968
  memTotal: 6218977280
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.1-1.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.1
    package: netavark-1.12.1-1.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.1
  ociRuntime:
    name: crun
    package: crun-1.15-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.15
      commit: e6eacaf4034e84185fd8780ac9262bbf57082278
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240821.g1d6142f-1.fc40.x86_64
    version: |
      pasta 0^20240821.g1d6142f-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 0h 10m 30.00s
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 4008087552
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 12
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.2
  Built: 1724198400
  BuiltTime: Wed Aug 21 10:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.6
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.2
```

**Comment by Luap99** [comment] 2024-11-01 10:43
> Dupe of https://github.com/containers/podman/issues/17628 which is closed without resolution.

Did you read the issue? This is caused by a big context directory that must be copied into the VM. So if you change to a different small directory it should work nuch faster unless there is actual hang somewhere?
Also https://github.com/containers/podman/issues/21627 so closing this as dup

**Closed by Luap99** 2024-11-01 10:43 UTC
Labels: remote
