### ISSUE TITLE
No Podman 4 binaries attached to Github releases or available on Kubic repositories

### ISSUE THREAD

**Issue by fjorgemota** [containers/podman#13349] opened 2022-02-25 11:12 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

There are no binaries or packages available to use/test Podman 4. Podman Remote isn't available anymore on [Github Releases page](https://github.com/containers/podman/releases), for instance, neither from the [Kubic project](https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/podman).

**Steps to reproduce the issue:**

1. Visit [Github Release page](https://github.com/containers/podman/releases);

2. Observe that there are no ready-to-download binaries to test on 4.0.0 release and newer;

**Describe the results you received:**

No binary is available to download.

**Describe the results you expected:**

At least Podman Remote binaries are available to download, or maybe updated repositories to use on Ubuntu.

----- 

Ignored the rest of the template given that it's redundant (as the problem isn't only local). Feel free to ask for it if you want and I'll offer all the details. =) 

I also tried looking out for open issues related to this, but I haven't found anything. Sorry if this is a duplicate.

**Comment by Luap99** [comment] 2022-02-25 12:12
Duplicate of #13298
For kubic see https://github.com/containers/podman/issues/13302

**Closed by Luap99** 2022-02-25 12:12 UTC
Labels: kind/bug
