### ISSUE TITLE
 podman generate kube writes the container CMD as a command parameter to YAML file.

### ISSUE THREAD

**Issue by kaiyasuda** [containers/podman#7019] opened 2020-07-20 04:53 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

related issue
https://github.com/containers/podman/issues/6995

The command parameter of kubernetes yaml is equivalent to the entrypoint of image. and similarly, args is equivalent to cmd.
but podman generate kube writes container's CMD as a command parameter to YAML file.

**Steps to reproduce the issue:**

1.  make pod with `play kube`

```
podman play kube ipc.yml
```

```ipc.yml
apiVersion: v1
kind: Pod
metadata:
  name: mc2
spec:
  containers:
  - name: producer
    image: allingeek/ch6_ipc
    command: ["./ipc","-producer"]
  - name: consumer
    image: allingeek/ch6_ipc
    command: ["./ipc","-consumer"]
  restartPolicy: Never
```

2. check container CMD and Entrypoint.

```
# podman container ls -a --no-trunc --format="{{.Names}} {{.Command}}"
NAMES                      COMMAND
mc2-consumer          ./ipc ./ipc -consumer
fdce7aa7e7bb-infra
mc2-producer           ./ipc ./ipc -producer

# podman container inspect mc2-producer | grep Entrypoint
            "Entrypoint": "./ipc",
# podman container inspect mc2-producer | grep Cmd -A4
            "Cmd": [
                "./ipc",
                "./ipc",
                "-producer"
            ],
```

3. reconvert to kubernetes yaml.

```
# podman generate mc2 > ipc2.yml 
```

**Describe the results you received:**

podman generate kube writes container's CMD as a command parameter to YAML file.

```ipc2.yml
# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.0.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-07-20T03:00:09Z"
  labels:
    app: mc2
  name: mc2
spec:
  containers:
  - command:
    - ./ipc
    - ./ipc
    - -consumer
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: mc2
    image: allingeek/ch6_ipc
    name: mc2-consumer
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /work/ipc
  - command:
    - ./ipc
    - ./ipc
    - -producer
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: mc2
    image: allingeek/ch6_ipc
    name: mc2-producer
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /work/ipc
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}
```

**Describe the results you expected:**

podman should recognize Entrypoint as command parameter, and generate like this.

```
  - command:
    - ./ipc
    - -consumer
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:      2.0.2
API Version:  1
Go Version:   go1.13.4
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
podman info --debug
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.19-1.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 4726cba6f219c7479c28f0687868bd2ffe894869'
  cpus: 2
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: ycentos8.example.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-147.el8.x86_64
  linkmode: dynamic
  memFree: 5467197440
  memTotal: 8191717376
  ociRuntime:
    name: runc
    package: runc-1.0.0-60.rc8.module_el8.1.0+237+63e26edc.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 6874460160
  swapTotal: 6874460160
  uptime: 123h 6m 21.33s (Approximately 5.12 days)
registries:
  search:
  - registry.redhat.io
  - registry.access.redhat.com
  - quay.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 11
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.13.4
  OsArch: linux/amd64
  Version: 2.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-2.0.2-2.el8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware

**Comment by vrothberg** [comment] 2020-07-20 09:23
Thanks for opening the issue, @kaiyasuda! Are you interested in opening a pull request and fix it?

**Comment by zhangguanzhang** [comment] 2020-07-20 17:52
Podman generate is generated from the container, so this issue is caused by the same reason as https://github.com/containers/podman/issues/6995
https://github.com/containers/podman/pull/7002 fix this

**Comment by zhangguanzhang** [comment] 2020-07-27 11:12
Can you use the latest version of podman to test whether the created pod and `generate kube` work normally, if there is no problem, please close this issue

**Comment by rhatdan** [comment] 2020-07-27 13:14
I prefer to reverse the logic.
If the latest version does not fix this issue, then reopen it.
Thanks @zhangguanzhang

**Closed by rhatdan** 2020-07-27 13:14 UTC
Labels: kind/bug
