### ISSUE TITLE
The unlinkat/EBUSY flake is back

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11594] opened 2021-09-15 17:13 UTC
Background: we thought this had been fixed in https://github.com/containers/storage/pull/926 . Further background: #7139, #10454.

Symptom [[source](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4640376129585152/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-play-kube-with-image-data--1)]:
```
Running: podman [options] pod rm -fa
Error: error removing container SHA root filesystem: 2 errors occurred:
	* unlinkat /tmp/podman_test184319701/crio/vfs-containers/SHA/userdata/shm: device or resource busy
	* unlinkat /tmp/podman_test184319701/crio/vfs-containers/SHA/userdata/shm: device or resource busy
```
Most often seen in "`podman play kube with image data`" test, with "`podman pod rm -fa`", but also seen in "`podman create container with --uidmap and conmon PidFile accessible`" test (with `podman rm`, not `podman pod rm`, and with one unlinkat line, not two).  Happening on ubuntu and fedora.

Flakes began on 2021-08-31 and continue through today. The multiarch folks are [also seeing it](https://gitlab.com/cki-project/kernel-tests/-/issues/739).

These flakes do not appear in my flake logs because they seem to be happening in `common_test.go:Cleanup()`, which (sigh) does not do exit-status checks.

Log links available if absolutely necessary, but please don't ask unless absolutely necessary: my flake checker doesn't catch these (see immediately above), so finding logs requires tedious manual effort.

What happened on August 30/31?

**Comment by giuseppe** [comment] 2021-09-16 11:09
this looks like a new issue not related to the previous one we had in c/storage.

It looks like a race when cleaning up `/dev/shm` shared among the containers in the pod

**Comment by giuseppe** [comment] 2021-09-16 11:21
> Flakes began on 2021-08-31 and continue through today. The multiarch folks are [also seeing it](https://gitlab.com/cki-project/kernel-tests/-/issues/739).

this one instead looks like the one we had in storage :/  It could be an issue specific to ppc64le

**Comment by edsantiago** [comment] 2021-11-09 17:01
Still happening:
* 10-26 [int remote f33 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5848798850187264/html/int-remote-fedora-33-root-host.log.html#t--podman-play-kube-with-image-data--1)
* 10-27 [int podman ubuntu-2104 rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4746606357512192/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-play-kube-with-image-data--1)
* 11-04 [int podman ubuntu-2104-rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6296467519307776/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-play-kube-with-image-data--1)
* 11-08 [int podman f33 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4680072280932352/html/int-podman-fedora-33-root-container.log.html#t--podman-play-kube-with-image-data--1)
* 11-09 [int podman f34 rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--podman-play-kube-with-image-data--1)

So: both root and rootless. Fedora and Ubuntu. Local and remote. Always in `podman play kube with image data` test.

**Comment by edsantiago** [comment] 2021-11-16 18:12
Hmmm, I just managed to accidentally reproduce this on my laptop. I ^C'ed a while-forever loop that was doing `podman run`. This left a container in state `Created`, which I then tried to rm:
```console
$ bin/podman ps -a
CONTAINER ID  IMAGE                            COMMAND     CREATED        STATUS      PORTS       NAMES
99cc76cd2fe8  docker.io/library/fedora:latest  true        2 seconds ago  Created                 charming_dirac
$ bin/podman rm -f -a      <--- This paused for about 10s.
Error: error removing container 99cc76cd2fe854a86529081a519a90510243ab4681e3a79e1b7899e53827fb96 root filesystem: 2 errors occurred:
        * unlinkat /home/esm/.local/share/containers/storage/overlay-containers/99cc76cd2fe854a86529081a519a90510243ab4681e3a79e1b7899e53827fb96/userdata/shm: device or resource busy
        * unlinkat /home/esm/.local/share/containers/storage/overlay-containers/99cc76cd2fe854a86529081a519a90510243ab4681e3a79e1b7899e53827fb96/userdata/shm: device or resource busy


```
(Yes, two blank lines afterward).

The pause surprised me: I did not expect to need `-t 0` on a `Created` container.

**Comment by edsantiago** [comment] 2022-01-05 14:32
Just reproduced it again on my laptop, again unintentionally via ^C:
```console
...
^C
$ bin/podman rm foo
Error: error removing container f512e6e9274b8ccb8d4b2715c482308a00c404b553ae81611146f339df107ba7 root filesystem: 2 errors occurred:
        * unlinkat /home/esm/.local/share/containers/storage/overlay-containers/f512e6e9274b8ccb8d4b2715c482308a00c404b553ae81611146f339df107ba7/userdata/shm: device or resource busy
        * unlinkat /home/esm/.local/share/containers/storage/overlay-containers/f512e6e9274b8ccb8d4b2715c482308a00c404b553ae81611146f339df107ba7/userdata/shm: device or resource busy
```
Based on the output of the loop, I'm pretty sure the ^C interrupted this command:
```
bin/podman run -d --name foo $IMAGE sh -c 'printenv NOTIFY_SOCKET;echo READY;while ! test -f /stop;do sleep 0.1;done'
```

**Comment by jnovy** [comment] 2022-01-13 13:02
Reproduced this again in RHEL8 gating tests:

`Error: error removing container 033f3b8a1eec95570e68aacc12035c56113d9e180eb3e83bbe6a48ee05f7ce71 root filesystem: 1 error occurred:
	* unlinkat /var/lib/containers/storage/overlay/240447b311711770c5d6a17a15f9cc6ec7284a98d05dccce841abec60bbdb7ab/merged: device or resource busy
[ rc=125 (** EXPECTED 0 **) ]
`

**Comment by edsantiago** [comment] 2022-02-14 13:39
Still.
* 02-09 [int podman f34 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6697518636466176/html/int-podman-fedora-34-root-host.log.html#t--podman-play-kube-with-image-data--1)
* 02-09 [ditto, meaning, again in the same run](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6697518636466176/html/int-podman-fedora-34-root-host.log.html#t--podman-play-kube-should-not-rename-pod-if-container-in-pod-has-same-name--1)
* 02-11 [netavark int rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5253070870282240/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--podman-pod-inspect--CreateCommand---1) (this one also has over three hundred `unlinkat /tmp/.../catatonit: EPERM` errors which I'm just not going to worry about right now)
* 02-11 [again netavark, but in a completely different PR](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5406823686602752/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--podman-play-kube-with-image-data--1) (and ditto the catatonit thing)

Please don't make me cite more examples: these are not easily captured by my flake logger, and it is super tedious for me to manually find and link to each one.

**Comment by edsantiago** [comment] 2022-04-19 13:51
Haven't seen this in, oh, [five days](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5566482477219840/html/int-podman-fedora-35-root-container.log.html#t--podman-play-kube-replace--1). (Plus lots more in April and March and February; but like I said above, it's tedious to gather these).

**Comment by edsantiago** [comment] 2022-05-24 18:39
Seen today [f36 remote rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4974853869535232/html/sys-remote-fedora-36-rootless-host.log.html#t--00345):
```
[+1790s] not ok 345 podman play --annotation
...
         # $ podman-remote --url unix:/tmp/podman_tmp_1ytS stop -a -t 0
         # 7a31b6a381e43f0ddb956072018fa33037657c471ff8a9250206fc5eb00b65dc
         # 35a84ff304a006de59c19941cad812fe5417345aa64ded5073a2837ed98b81c3
         # $ podman-remote --url unix:/tmp/podman_tmp_1ytS pod rm -t 0 -f test_pod
         # Error: error removing container 35a84ff304a006de59c19941cad812fe5417345aa64ded5073a2837ed98b81c3 root filesystem: 1 error occurred:
         # 	* unlinkat /home/some5835dude/.local/share/containers/storage/overlay/4c6ba48ec95c425623b4e8964b3fc07ee6f96d78dd9147e56535cdbff09ac39e/merged: device or resource busy
```

**Comment by Eugeny** [comment] 2022-06-30 10:33
still happening on root containers with podman 4.1.0:

```
WARN[0025] Found incomplete layer "831b9ae6149f440fe45423384f7ba5ca916a92ee23c8401e855a8a609127af24", deleting it 
Error: error mounting storage for container e84b32d982c7a4fb56ddf3db1a2d75351cc02934c1e7fda25f8a2d7888d47aa8: unlinkat /var/lib/containers/storage/overlay/831b9ae6149f440fe45423384f7ba5ca916a92ee23c8401e855a8a609127af24/merged: device or resource busy```

**Comment by edsantiago** [comment] 2022-07-07 14:50
Seen just now, [ubuntu 2110 remote root](https://api.cirrus-ci.com/v1/artifact/build/5742372758749184/sys%20remote%20ubuntu-2110%20root%20host/html/sys-remote-ubuntu-2110-root-host.log.html):
```
[+0654s] not ok 255 podman pod create --share
         # (from function `die' in file test/system/[helpers.bash, line 555](https://github.com/containers/podman/blob/cd16c6a6a7d153b18a7f25a5728a44d0acf64b3f/test/system/helpers.bash#L555),
         #  from function `run_podman' in file test/system/[helpers.bash, line 219](https://github.com/containers/podman/blob/cd16c6a6a7d153b18a7f25a5728a44d0acf64b3f/test/system/helpers.bash#L219),
         #  in test file test/system/[200-pod.bats, line 342](https://github.com/containers/podman/blob/cd16c6a6a7d153b18a7f25a5728a44d0acf64b3f/test/system/200-pod.bats#L342))
         #   `run_podman pod create --share +pid --replace --name $pod_name' failed with status 125
         # # podman-remote --url unix:/tmp/podman_tmp_orNk rm -t 0 --all --force --ignore
         # # podman-remote --url unix:/tmp/podman_tmp_orNk ps --all --external --format {{.ID}} {{.Names}}
         # # podman-remote --url unix:/tmp/podman_tmp_orNk images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
         # quay.io/libpod/testimage:20220615 f26aa69bb3f3
         # # podman-remote --url unix:/tmp/podman_tmp_orNk pod create --share bogus --name dd1keqxlvx
         # Error: failed to make pod: Invalid kernel namespace to share: bogus. Options are: cgroup, ipc, net, pid, uts or none
         # [ rc=125 (expected) ]
         # # podman-remote --url unix:/tmp/podman_tmp_orNk pod create --share ipc --name dd1keqxlvx
         # 21ac2d3fe9939e699a6d1f4da0adf5cbed36a6e27c4b455b6f865ba832f7258c
         # # podman-remote --url unix:/tmp/podman_tmp_orNk pod inspect dd1keqxlvx --format {{.SharedNamespaces}}
         # [ipc]
         # # podman-remote --url unix:/tmp/podman_tmp_orNk run --rm --pod dd1keqxlvx --hostname foobar quay.io/libpod/testimage:20220615 hostname
         # foobar
         # # podman-remote --url unix:/tmp/podman_tmp_orNk pod create --share +pid --replace --name dd1keqxlvx
         # Error: error removing container 14a06e3b746c083e938bad3dfbbcd4869effcd5013df1e49ec3e39837edcfadf root filesystem: 1 error occurred:
         # 	* unlinkat /var/lib/containers/storage/overlay/08c4e1dad9a8889447368484b7ceadbb5551e171c5917a00d38c2f2db4049b40/merged: device or resource busy
```
This then caused a cascade of failures, where every test after that failed:
```         # # podman-remote --url unix:/tmp/podman_tmp_orNk images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
         # Error: error retrieving parent of image "f26aa69bb3f3de470d358b6c4e7f9de8ca165ef7f1689af1cdd446902dc27928": you may need to remove the image to resolve the error: unlinkat /var/lib/containers/storage/overlay/08c4e1dad9a8889447368484b7ceadbb5551e171c5917a00d38c2f2db4049b40/merged: device or resource busy
```

**Comment by Eugeny** [comment] 2022-07-07 15:26
Seems to be much easier to trigger when running on the 3.10 kernel

**Comment by edsantiago** [comment] 2022-07-07 15:48
Okay, we've got a problem. This is blowing up today. New one, [f36 remote rootless](https://api.cirrus-ci.com/v1/artifact/build/5539940548214784/sys%20remote%20fedora-36%20rootless%20host/html/sys-remote-fedora-36-rootless-host.log.html)

**Comment by edsantiago** [comment] 2022-07-07 16:36
And another one. Now [f36 remote root](https://api.cirrus-ci.com/v1/artifact/build/6040624804659200/sys%20remote%20fedora-36%20root%20host/html/sys-remote-fedora-36-root-host.log.html).

**Comment by edsantiago** [comment] 2022-07-08 00:53
And yet another one, [sys remote fedora-36 rootless](https://api.cirrus-ci.com/v1/task/5112750148943872/logs/main.log).

@containers/podman-maintainers PTAL this one is getting ugly really fast.

**Comment by vrothberg** [comment] 2022-07-08 08:08
@giuseppe, if you find time, could you take a look?

**Comment by edsantiago** [comment] 2022-07-12 12:04
Another one: [sys remote ubuntu root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4602887803240448/html/sys-remote-ubuntu-2110-root-host.log.html)

**Comment by edsantiago** [comment] 2022-08-17 19:03
Another recent one: [sys remote f36 rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5555957253013504/html/sys-remote-fedora-36-rootless-host.log.html#t--00364) on August 8

**Comment by edsantiago** [comment] 2022-08-22 20:36
In this one [remote ubuntu root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6169165353451520/html/sys-remote-ubuntu-2204-root-host.log.html#t--00270), the unlinkat/EBUSY flake triggers the error-freeing error which renders the system unusable (#15367)

**Comment by vrothberg** [comment] 2022-08-26 11:36
@giuseppe if you find time, could you take a look? It seems related to https://github.com/containers/podman/issues/15367.

**Comment by rhatdan** [comment] 2022-09-30 14:22
Reminder @giuseppe @vrothberg

**Comment by edsantiago** [comment] 2022-10-12 16:00
This one could be the same one, or could be the rm-hose issue (#15367), I can't tell. [podman ubuntu rootless](https://api.cirrus-ci.com/v1/artifact/task/6119046214057984/html/sys-podman-ubuntu-2204-rootless-host.log.html#t--00392), in `kube down`:
```console
$ podman kube down /tmp/podman_bats.pH6C43/testpod.yaml
Pods stopped:
3cb812278cf782c71fb501a171658fac32c9fdbbba3055ec9d2a6ccbd003a2f8
Pods removed:
Error: 1 error occurred:
	* removing container 10413d40f879e63f9d5802f8dc26343b8b6267020014e1ae0491b26c8eea33cc from pod 3cb812278cf782c71fb501a171658fac32c9fdbbba3055ec9d2a6ccbd003a2f8: removing container 10413d40f879e63f9d5802f8dc26343b8b6267020014e1ae0491b26c8eea33cc root filesystem: 1 error occurred:
	* unlinkat /home/some25997dude/.local/share/containers/storage/overlay-containers/10413d40f879e63f9d5802f8dc26343b8b6267020014e1ae0491b26c8eea33cc/userdata/shm: device or resource busy
[ rc=125 (** EXPECTED 0 **) ]
```

**Comment by vrothberg** [comment] 2022-12-15 12:21
Since https://github.com/containers/podman/pull/16159 merged, I am going to close it.  Please reopen if I am mistaken.

**Closed by vrothberg** 2022-12-15 12:21 UTC
Labels: flakes
