### ISSUE TITLE
Add possibility to completely disable cgroup management

### ISSUE THREAD

**Issue by zv0n** [containers/podman#8060] opened 2020-10-19 13:08 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Our organization has a use-case for podman where we need it to not manage cgroups. Podman switches cgroup when it's setting up rootless environment, so setting `--cgroups disabled` doesn't prevent this as it is a command flag (and rootless env is being set up in the root part of program). So we'd like an option that completely disables any and all cgroup management that podman does. This issue has been discussed in this PR - https://github.com/containers/podman/pull/7721 and we've come to the conclusion that the best/cleanest approach to solve this would probably be to add `disabled` option to `--cgroup-manager` which would automatically also set `--cgroups disabled` for all commands.

**Comment by rhatdan** [comment] 2020-11-23 12:12
@giuseppe WDYT?

**Comment by giuseppe** [comment] 2020-11-23 12:57
I think that the approach could solve the issue.

@mheon are you fine with it?

**Comment by mheon** [comment] 2020-11-23 16:15
I'm perfectly fine with this - makes sense from my perspective.

**Comment by rhatdan** [comment] 2020-12-24 11:51
@giuseppe could you create a PR to make this happen?

**Comment by rhatdan** [comment] 2021-01-25 14:09
@giuseppe Did you ever get a chance to look at this?

**Comment by giuseppe** [comment] 2021-01-26 13:47
not yet.

@zv0n would accepting the cgroup manager through an environment variable work for you (e.g. `CGROUP_MANAGER=disabled`)?

**Comment by zv0n** [comment] 2021-01-26 14:09
@giuseppe sure, that would work great!

**Comment by rhatdan** [comment] 2021-02-11 11:24
@giuseppe any progress?

**Comment by giuseppe** [comment] 2021-02-11 13:07
I had a look and I am not happy with all the plumbing needed.

If the issue is only in SetupRootless, maybe we can find another way to address it.

@zv0n would something like setting `DBUS_SESSION_BUS_ADDRESS=unix:path=/dev/zero` and using `--cgroups=disabled` work with you?

**Comment by zv0n** [comment] 2021-03-03 08:12
@giuseppe We've done some testing and it seems that `DBUS_SESSION_BUS_ADDRESS=unix:path=/dev/zero` works, thanks for the idea!

**Comment by rhatdan** [comment] 2021-04-05 18:17
@giuseppe @zv0n is this still something we need  to fix.

**Comment by giuseppe** [comment] 2021-04-06 07:42
The plumbing is not trivial and there is a workaround.

Let's close it.

**Closed by giuseppe** 2021-04-06 07:42 UTC
Labels: kind/feature
