### ISSUE TITLE
Feature: journalctl support for podman generate systemd

### ISSUE THREAD

**Issue by daniel-wtd** [containers/podman#8841] opened 2020-12-27 17:57 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It would be awesome to change the generated systemd from "podman generate systemd" to support `--attach stdout`.
This will allow to have the logs from `podman logs` directly visible in `journalctl`.

**Steps to reproduce the issue:**

1. `podman run -dt --name web01 httpd`
2. `podman generate systemd --name --new web01`

**Describe the results you received:**

The generated file will have the `-dt` flag in `ExecStart`.
Logs from `podman logs web01` are not visible in `systemctl status container-web01` or `journalctl`.

**Describe the results you expected:**

The generated file does not use shorthand arguments and replaces `--detach` to `--attach stdout`.
Logs from `podman logs web01` are visible in `systemctl status container-web01` or `journalctl`.

**Output of `podman version`:**

```
podman version 2.2.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Minor additions:**

- Systemd expects to have processes running in foreground, same for containers
- Additional tools like fail2ban/elastic/collectd can use the logs directly from journald/systemd

**Comment by Luap99** [comment] 2020-12-27 19:05
There exists `--log-driver journald` for `podman create/run`. With that option conmon will write the container output to journald.

**Comment by daniel-wtd** [comment] 2020-12-28 14:22
Hmmm, could you please elaborate how I can view/use these logs afterwards? I cannot even see something in `journalctl -f`

**Comment by Luap99** [comment] 2020-12-28 15:09
You should definitely see something with `journalctl -f`. Notice the the logs are written by the conmon process not podman. 
You can query by the full container id like this: `journalctl -f CONTAINER_ID_FULL=b422fcc881fd457034d65cd6138a6ca2625463c43ba273dcc42d44bcc29af1f2`

No they are not linked to the unit so your feature request is still valid. I just wanted to point out that this option exists.

**Comment by Luap99** [comment] 2020-12-28 15:20
I thinks this requires 3 things:
1. change the unit type to simple
2. don't add --detach if the --new option is used; if --new is not used add --attach to podman start
3. remove the pidfile references

Also I think if someone wants this they would want both stdout and stderr to be logged. I don't see a benefit to only log stdout.

**Comment by daniel-wtd** [comment] 2020-12-28 15:40
Hi,

I am doing the below at the moment.

```
[Unit]
Description=Podman Gitea DB

Wants=network.target
After=network-online.target

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Type=forking

PIDFile=%t/container-gitea-db.pid

KillMode=none
Restart=always

ExecStartPre=/bin/rm -f %t/container-gitea-db.pid %t/container-gitea-db.ctr-id

ExecStart=/usr/bin/podman run \
          --conmon-pidfile %t/container-gitea-db.pid \
          --cidfile %t/container-gitea-db.ctr-id \
          --replace \
          --attach stdout \
          --tty \
          --rm \
          --env MYSQL_USER=gitea \
          --env MYSQL_PASSWORD=password \
          --env MYSQL_RANDOM_ROOT_PASSWORD=true \
          --env MYSQL_DATABASE=gitea \
          --volume gitea-db:/var/lib/mysql:Z \
          --name gitea-db \
          --label io.containers.autoupdate=image \
          docker.io/library/mariadb:10

ExecStop=/usr/bin/podman stop \
          --ignore \
          --cidfile %t/container-gitea-db.ctr-id

ExecStopPost=/usr/bin/podman rm \
          --ignore \
          --force \
          --cidfile %t/container-gitea-db.ctr-id


[Install]
WantedBy=multi-user.target default.target
```

This way, I can simply run `systemctl status container-gitea-db` or `journalctl -u container-gitea-db`.

I have chosen to use stdout, because all container processes should run in foreground anyway. But using all output would be absolutely ok for me, too.

As a template, I have used: `podman generate systemd --name --new`

**Comment by daniel-wtd** [comment] 2020-12-28 15:46
Little addition: This feature is not specific for me, but everybody who is expecting that a defined service writes properly to the journal. I know how to tweak the output already ^^

**Comment by Luap99** [comment] 2020-12-28 16:06
If just adding --attach works I think adding this flag to `podman generate systemd` is easy.
Interested in opening a PR?

**Comment by daniel-wtd** [comment] 2020-12-28 16:07
Sure, I can have a look. But it will take some time. Currently developing a bunch of example roles for the podman collection.

**Comment by daniel-wtd** [comment] 2021-01-29 11:56
During testing the funtionality with different scenarios I came to issues like systemctl start is stuck foreground. Currently, checking where this is coming from, since (to my understanding) systemd recommends having processes running in foreground :/

**Comment by Luap99** [comment] 2021-01-29 12:45
@daniel-wtd You have to change the unit type from forking to simple I believe

**Comment by daniel-wtd** [comment] 2021-01-29 12:53
Ah, right :) Thanks.

**Comment by rhatdan** [comment] 2021-02-11 11:12
@daniel-wtd @Luap99 is this still an issue or should it be closed?

**Comment by daniel-wtd** [comment] 2021-02-11 11:28
@rhatdan Not an issue for me, since I can tweak the systemd unit files to my needs.

Since there is some development for sdnotify, I will come back to it and either:

- open a PR for some additonal option for `podman generate systemd`
- write an article for podman.io / docs.podman.io to document a way of systemd integrated logging

If it's not a problem, it would be awesome to have a look after 3.0 again. Otherwise, feel free to close it, I am having it on my personal agenda :)

**Comment by Luap99** [comment] 2021-02-11 11:37
Lets keep it open. It is not that difficult to implement. I added the Good Fist Issue label if someone wants to work on it.

In order to make it work three things are required:
* change the unit type to simple
* don't add --detach if the --new option is used; if --new is not used add --attach to podman start
* add a new cli flag (--attach) to podman generate systemd for this

**Comment by huww98** [comment] 2021-02-24 14:22
I propose another approach:
* enable `Delegate=yes` in unit file
* add `--log-driver=journald`
* add `--cgroups=split` (or disabled)

This approach enables the logs to be linked to the unit via cgroups. And they do appear in `systemctl status xxx.service`. Also, I think this is more efficient, as we don't need the extra podman process, and logs are directly transferred to journald.

In addition, this approach allows us to use unit file to setup resource control for processes in container.

However, this may not work for cgroups v1 and user unit. As stated in [the doc](https://systemd.io/CGROUP_DELEGATION/):
> Delegation to less privileges processes is not safe in cgroup v1 (as a limitation of the kernel), hence systemd won’t facilitate access to it."

What do you think?

**Comment by daniel-wtd** [comment] 2021-02-24 15:14
@huww98 This sound pretty awesome. I will give it a try this week. I assume cgroupsv1 support is not a major feature(?) with a lot of attention.

**Comment by daniel-wtd** [comment] 2021-03-01 20:51
I just added

```
Delegate=yes
```
and
```
--log-driver=journald
```

All logs from podman and the service in podman are in the logs/journal.

**Comment by vrothberg** [comment] 2021-03-02 08:41
@daniel-wtd, awesome!

@ashley-cui did some great work on polishing the journald driver recently, so I expect things to work smoothly.

**Comment by huww98** [comment] 2021-03-02 08:44
Just note I'm facing containers/conmon#242 when using this method.

**Comment by rhatdan** [comment] 2021-04-05 16:54
I believe this is fixed in the main branch and in podman 3.1

**Comment by vrothberg** [comment] 2021-04-06 06:31
Not yet fixed.  The units had to be generated with `--log-driver=journald` which is not yet done.

**Comment by giggls** [comment] 2021-05-06 09:49
Hello,

I add this comment here because I think `--log-driver=journald` might be not enough in cases where it is required that a service is ready to serve after startup meaning a unit of `Type=notify` is needed.

This will basically need a setup where stdout/stderr of the podman processs will end up exactly at stdin of  the following process and not anywhere strange.

I am currently trying to port a setup from docker-ce which works fine there.

It looks like this:

Systemd-service:
```
[Unit]
Description=Startup container and wait until ready to serve
After=docker.service
Requires=docker.service

[Service]
Type=notify
ExecStart=/path/to/my/startup-wrapper.sh
ExecStop=docker exec -it  mycontainer /path/to/service-shutdown.sh
```
Startup-wrapper:
```sh
#!/bin/sh
# startup by wrapper script to notify systemd
# after startup has completed

/usr/bin/docker start -a mycontainer 2>&1 | \
while read l
do
  echo $l
  # process listening on port 8080 is ready to serve
  if [ -z "${l##*0.0.0.0:8080*}" ] ;then
    systemd-notify --ready --status="mycontainer started."
  fi
done
```

**Comment by banool** [comment] 2021-08-28 06:41
For anyone reading this now, here's how I fixed it. Previously I had it that I wouldn't detach (with `-d`), but `podman generate systemd` recommends it. But if you do so, you lose your logs in journalctl ("yes I know that's why I'm here!"). To deal with this, you need to tell podman to log to journalctl instead. To do so, you do add `--log-driver=journald`, which should look like this in the end:
```
ExecStart=/usr/bin/podman run \
  --conmon-pidfile %t/%n.pid \
  --cidfile %t/%n.ctr-id \
  --cgroups no-conmon \
  -d \
  --log-driver=journald \
  --replace \
  -a stdout \
  -a stderr \
  --name <name> <image>
```

I did not have to add `Delegate=yes` for this to work like one of the earlier answers suggests (though I'm not sure which is best).

**Comment by huww98** [comment] 2021-08-28 06:50
I think `Delegate=yes` is only needed if you use `podman run --cgroups=split`. Otherwise, you should not add it.

**Comment by vrothberg** [comment] 2021-09-23 12:09
`journalctl` is now the default log driver and the logs show up in `systemctl` and `journalctl`. Thanks everybody!

**Closed by vrothberg** 2021-09-23 12:09 UTC
Labels: Good First Issue, kind/feature

**Comment by Luap99** [comment] 2021-09-23 12:11
@vrothberg I think `Delegate=yes` is still needed, no?

**Comment by vrothberg** [comment] 2021-09-23 12:14
@Luap99 it wasn't required in my tests which aligns with the comments above.

**Comment by haarts** [comment] 2022-10-03 15:20
I still face this issue with podman 4.1.1.

I've generated a unit with with `podman generate systemd` and got this file:

```
# container-0fb53a71d4ceaf1d49c762fc51d4f3859a39ef365351c1b486f2251feab710ba.service
# autogenerated by Podman 4.1.1
# Mon Oct  3 13:56:31 UTC 2022

[Unit]
Description=Podman container-0fb53a71d4ceaf1d49c762fc51d4f3859a39ef365351c1b486f2251feab710ba.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=/run/user/1000/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podman start 0fb53a71d4ceaf1d49c762fc51d4f3859a39ef365351c1b486f2251feab710ba
ExecStop=/usr/bin/podman stop -t 10 0fb53a71d4ceaf1d49c762fc51d4f3859a39ef365351c1b486f2251feab710ba
ExecStopPost=/usr/bin/podman stop -t 10 0fb53a71d4ceaf1d49c762fc51d4f3859a39ef365351c1b486f2251feab710ba
PIDFile=/run/user/1000/containers/overlay-containers/0fb53a71d4ceaf1d49c762fc51d4f3859a39ef365351c1b486f2251feab710ba/userdata/conmon.pid
Type=forking

[Install]
WantedBy=default.target
```

The container was initially run with the `--log-driver=journald` and I can confirm that is what it uses with `podman container inspect`. 

I copied the unit file to `$HOME/.config/systemd/user` and successfully ran it with `systemctl start ...`. The logs remain empty though (`journalctl --user -f`).

The container in question runs this: `ruby -e 'i=0; while true; sleep 1; pp i+=1; $stdout.flush; end;'` and it does so correctly when started by `podman run`.

I'm a bit at a loss.

**Comment by porjo** [comment] 2023-06-14 22:41
I came here with the same problem. The solution for me was as described in this [post](https://serverfault.com/a/1068267/169220):
```
sudo mkdir /var/log/journal
sudo reboot
```
(I'm running Podman on Rocky Linux 9.2)
