### ISSUE TITLE
When running with docker-compose, DNS doesn't work.

### ISSUE THREAD

**Issue by fugkco** [containers/podman#10146] opened 2021-04-27 11:26 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
It seems that when I try to run a very simple docker-compose file, the network that then gets configured (which I've specified in the compose file) seems to provide a different DNS setting for `/etc/resolv.conf` which doesn't allow for DNS resolution. This is likely my naivety on container network but when I run it without a network configuration, it works fine.

**Steps to reproduce the issue:**

1. run docker-compose up using this compose file:
   ```
   version: '3.7'
   
   services:
     testing:
       image: docker.io/library/alpine:3.13
       entrypoint: sh
       command:
         - -xc
         - "wget -S -O/dev/null https://www.google.com/ 2>&1 | head -n2; wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46  2>&1 | head -n2"
   ```
   Notice that this is able to connect to google on both occasions:
   ```
   $ docker-compose -f docker-compose.test.yaml up
   Recreating bug_testing_1 ... done
   Attaching to bug_testing_1
   testing_1  | + wget -S -O/dev/null https://www.google.com/
   testing_1  | + head -n2
   testing_1  | Connecting to www.google.com (172.217.169.4:443)
   testing_1  |   HTTP/1.1 200 OK
   testing_1  | + wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46
   testing_1  | + head -n2
   testing_1  |   HTTP/1.1 200 OK
   testing_1  |   Date: Tue, 27 Apr 2021 11:05:40 GMT
   ```
2. Now try compose up with the following docker-compose file:
   ```
   version: '3.7'
   
   services:
     testing:
       image: docker.io/library/alpine:3.13
       entrypoint: sh
       command:
         - -xc
         - "wget -S -O/dev/null https://www.google.com/ 2>&1 | head -n2; wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46  2>&1 | head -n2"
       networks:
         - main
   
   networks:
     main:
   ```
   Notice the when wget has to do dns resolution, it complains that www.google.com is a bad address, and subsequently notice that Google's IP are accessible when bypassing DNS resolution.
   ```
   $ docker-compose -f docker-compose.test.yaml up
   Creating network "bug_main" with the default driver
   Creating bug_testing_1 ... done
   Attaching to bug_testing_1
   testing_1  | + wget -S -O/dev/null https://www.google.com/
   testing_1  | + head -n2
   testing_1  | wget: bad address 'www.google.com'
   testing_1  | + wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46
   testing_1  | + head -n2
   testing_1  |   HTTP/1.1 200 OK
   testing_1  |   Date: Tue, 27 Apr 2021 11:08:18 GMT
   ```
3. After further investigation it seems that `/etc/resolv.conf` gets populated with a different IP address than what the host knows. I'm not sure what it is supposed to be pointing to.
   ```
   7ab875ecc459:/# cat /etc/resolv.conf
   search dns.podman
   nameserver 10.89.1.1
   ```
   Contrary to the one in step one which has the nameserver configured as per the host.

**Describe the results you received:**
When defining a network, DNS resolution does not work.

**Describe the results you expected:**
When defining a network, DNS resolution should work.

**Additional information you deem important (e.g. issue happens only occasionally):** Note, this is all running using root-full containers. 

**Output of `podman version`:**

```
podman version 3.1.2
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 8
  distribution:
    distribution: pop
    version: "20.10"
  eventLogger: journald
  hostname: pop-os
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.11.0-7612-generic
  linkmode: dynamic
  memFree: 625520640
  memTotal: 16492675072
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1.3-9b83-dirty
      commit: 33851ada2cc9bf3945915565bf3c2df97facb92c
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 62767104
  swapTotal: 4294434816
  uptime: 240h 48m 7.81s (Approximately 10.00 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 10
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 3.1.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/unknown,now 100:3.1.2-1 amd64 [installed]
podman/unknown 100:3.1.2-1 arm64
podman/unknown 100:3.1.2-1 armhf
podman/unknown 100:3.1.2-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by mheon** [comment] 2021-04-27 16:36
Are you running Compose against rootless Podman? This isn't presently a supported configuration (we should start supporting it in Podman 3.2.x, releasing sometime in mid-late May)

**Comment by baude** [comment] 2021-04-27 20:55
when you add the network bits, does your container end up with one or two networks?

**Comment by fugkco** [comment] 2021-04-28 08:19
@mheon I am using rootfull. I look forward to using rootless podman with compose!

@baude Ah, it slipped my mind to post that. It looks like it ends up with a single NIC:

```
7ab875ecc459:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if171: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether c6:76:81:61:7c:5c brd ff:ff:ff:ff:ff:ff
    inet 10.89.1.51/24 brd 10.89.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::c476:81ff:fe61:7c5c/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by Luap99** [comment] 2021-04-28 18:39
@fugkco I cannot reproduce this with your compose file. What is in `/etc/resolv.conf` on your host? Can you do `podman network inspect <NETNAME>` for both networks to check if there are any differences.

**Comment by fugkco** [comment] 2021-04-29 07:20
```
$ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.1.3
```

> I cannot reproduce this with your compose file.

That's very interesting, I moved the docker-compose file to a different, empty directory, and it works. Running the same one in my project's directory, and it fails again. After a little bit more investigation and comparing with my real project's docker-compose file, it looks like adding network aliases causes the issue.
```
$ pwd
/tmp/testing

$ cat docker-compose.yaml
version: '3.7'

services:
  testing:
    image: docker.io/library/alpine:3.13
    entrypoint: sh
    command:
      - -xc
      - "wget -S -O/dev/null https://www.google.com/ 2>&1 | head -n2; wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46  2>&1 | head -n2; tail -f /dev/null"
    networks:
      main:
        aliases:
          - testing

networks:
  main:

$ sudo -E docker-compose up -d
Creating network "testing_main" with the default driver
Creating testing_testing_1 ... done

$ sudo -E docker-compose logs testing
Attaching to testing_testing_1
testing_1  | + wget -S -O/dev/null https://www.google.com/
testing_1  | + head -n2
testing_1  | wget: bad address 'www.google.com'
testing_1  | + wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46
testing_1  | + head -n2
testing_1  |   HTTP/1.1 200 OK
testing_1  |   Date: Thu, 29 Apr 2021 06:25:48 GMT
testing_1  | + tail -f /dev/null

$ sudo podman network ls
NETWORK ID    NAME                       VERSION  PLUGINS
2f259bab93aa  podman                     0.4.0    bridge,portmap,firewall,tuning
35dcfa866dbd  testing_main               0.4.0    bridge,portmap,firewall,tuning,dnsname

$ sudo podman network inspect testing_main
[
    {
        "args": {
            "podman_labels": {
                "com.docker.compose.network": "main",
                "com.docker.compose.project": "testing",
                "com.docker.compose.version": "1.25.0"
            }
        },
        "cniVersion": "0.4.0",
        "name": "testing_main",
        "plugins": [
            {
                "bridge": "cni-podman2",
                "hairpinMode": true,
                "ipMasq": true,
                "ipam": {
                    "ranges": [
                        [
                            {
                                "gateway": "10.89.1.1",
                                "subnet": "10.89.1.0/24"
                            }
                        ]
                    ],
                    "routes": [
                        {
                            "dst": "0.0.0.0/0"
                        }
                    ],
                    "type": "host-local"
                },
                "isGateway": true,
                "type": "bridge"
            },
            {
                "capabilities": {
                    "portMappings": true
                },
                "type": "portmap"
            },
            {
                "backend": "",
                "type": "firewall"
            },
            {
                "type": "tuning"
            },
            {
                "capabilities": {
                    "aliases": true
                },
                "domainName": "dns.podman",
                "type": "dnsname"
            }
        ]
    }
]

```

So I found it weird that the previous compose file I posted didn't work in my real project's directory, it turns out, when you add aliases, do a compose up, then down (as above in this current comment), then remove the aliases, and do a compose up, you get the same issue. Observe below:

```
$ pwd
/tmp/testing2

$ cat docker-compose.yaml
version: '3.7'

services:
  testing:
    image: docker.io/library/alpine:3.13
    entrypoint: sh
    command:
      - -xc
      - "wget -S -O/dev/null https://www.google.com/ 2>&1 | head -n2; wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46  2>&1 | head -n2; tail -f /dev/null"
    networks:
      - main

networks:
  main:

$ sudo -E docker-compose up -d
Creating network "testing2_main" with the default driver
Creating testing2_testing_1 ... done

$ sudo -E docker-compose logs testing
Attaching to testing2_testing_1
testing_1  | + wget -S -O/dev/null https://www.google.com/
testing_1  | + head -n2
testing_1  | Connecting to www.google.com (216.58.213.4:443)
testing_1  |   HTTP/1.1 200 OK
testing_1  | + wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46
testing_1  | + head -n2
testing_1  |   HTTP/1.1 200 OK
testing_1  |   Date: Thu, 29 Apr 2021 06:30:17 GMT
testing_1  | + tail -f /dev/null

$ sudo podman network ls
NETWORK ID    NAME                       VERSION  PLUGINS
2f259bab93aa  podman                     0.4.0    bridge,portmap,firewall,tuning
75092cb37eb4  testing2_main              0.4.0    bridge,portmap,firewall,tuning,dnsname

$ sudo podman network inspect testing2_main
[
    {
        "args": {
            "podman_labels": {
                "com.docker.compose.network": "main",
                "com.docker.compose.project": "testing2",
                "com.docker.compose.version": "1.25.0"
            }
        },
        "cniVersion": "0.4.0",
        "name": "testing2_main",
        "plugins": [
            {
                "bridge": "cni-podman2",
                "hairpinMode": true,
                "ipMasq": true,
                "ipam": {
                    "ranges": [
                        [
                            {
                                "gateway": "10.89.1.1",
                                "subnet": "10.89.1.0/24"
                            }
                        ]
                    ],
                    "routes": [
                        {
                            "dst": "0.0.0.0/0"
                        }
                    ],
                    "type": "host-local"
                },
                "isGateway": true,
                "type": "bridge"
            },
            {
                "capabilities": {
                    "portMappings": true
                },
                "type": "portmap"
            },
            {
                "backend": "",
                "type": "firewall"
            },
            {
                "type": "tuning"
            },
            {
                "capabilities": {
                    "aliases": true
                },
                "domainName": "dns.podman",
                "type": "dnsname"
            }
        ]
    }
]

$ sudo -E docker-compose down
Stopping testing2_testing_1 ... done
Removing testing2_testing_1 ... done
Removing network testing2_main

$ sudo podman network ls
NETWORK ID    NAME                       VERSION  PLUGINS
2f259bab93aa  podman                     0.4.0    bridge,portmap,firewall,tuning

$ sed -i 's/- main/main:\n        aliases:\n          - testing/' docker-compose.yaml

$ cat docker-compose.yaml
version: '3.7'

services:
  testing:
    image: docker.io/library/alpine:3.13
    entrypoint: sh
    command:
      - -xc
      - "wget -S -O/dev/null https://www.google.com/ 2>&1 | head -n2; wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46  2>&1 | head -n2; tail -f /dev/null"
    networks:
      main:
        aliases:
          - testing

networks:
  main:

$ sudo -E docker-compose up
Starting testing2_testing_1 ... done
Attaching to testing2_testing_1
testing_1  | + wget -S -O/dev/null https://www.google.com/
testing_1  | + head -n2
testing_1  | wget: bad address 'www.google.com'
testing_1  | + wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46
testing_1  | + head -n2
testing_1  |   HTTP/1.1 200 OK
testing_1  |   Date: Thu, 29 Apr 2021 06:55:41 GMT
testing_1  | + tail -f /dev/null
^CGracefully stopping... (press Ctrl+C again to force)
Stopping testing2_testing_1 ... done

$ sudo -E docker-compose down
Removing testing2_testing_1 ... done
Removing network testing2_main

$ sudo podman network ls
NETWORK ID    NAME                       VERSION  PLUGINS
2f259bab93aa  podman                     0.4.0    bridge,portmap,firewall,tuning

$ sed -i -e '/        aliases:/d' -e '/          - testing/d' -e '0,/main:$/s//- main/' docker-compose.yaml

$ cat docker-compose.yaml
version: '3.7'

services:
  testing:
    image: docker.io/library/alpine:3.13
    entrypoint: sh
    command:
      - -xc
      - "wget -S -O/dev/null https://www.google.com/ 2>&1 | head -n2; wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46  2>&1 | head -n2; tail -f /dev/null"
    networks:
      - main

networks:
  main:

$ sudo -E docker-compose up
Creating network "testing2_main" with the default driver
Creating testing2_testing_1 ... done
Attaching to testing2_testing_1
testing_1  | + wget -S -O/dev/null https://www.google.com/
testing_1  | + head -n2
testing_1  | wget: bad address 'www.google.com'
testing_1  | + + head -n2
testing_1  | wget -q -S -O/dev/null --header 'Host: www.google.com' 142.250.200.46
testing_1  |   HTTP/1.1 200 OK
testing_1  |   Date: Thu, 29 Apr 2021 07:03:55 GMT
testing_1  | + tail -f /dev/null
^CGracefully stopping... (press Ctrl+C again to force)
Stopping testing2_testing_1 ...

$ sudo podman network ls
NETWORK ID    NAME                       VERSION  PLUGINS
2f259bab93aa  podman                     0.4.0    bridge,portmap,firewall,tuning
75092cb37eb4  testing2_main              0.4.0    bridge,portmap,firewall,tuning,dnsname
```

Anyway, diff between the network of when it works and when it doesn't work, doesn't produce anything fruitful. See the diff for above two JSONs:
```
$ git diff --no-index /tmp/testing/inspect-network.json /tmp/testing2/inspect-network.json
diff --git 1/tmp/testing/inspect-network.json 2/tmp/testing2/inspect-network.json
index 392d07e..4b39c80 100644
--- 1/tmp/testing/inspect-network.json
+++ 2/tmp/testing2/inspect-network.json
@@ -3,12 +3,12 @@
     "args": {
       "podman_labels": {
         "com.docker.compose.network": "main",
-        "com.docker.compose.project": "testing",
+        "com.docker.compose.project": "testing2",
         "com.docker.compose.version": "1.25.0"
       }
     },
     "cniVersion": "0.4.0",
-    "name": "testing_main",
+    "name": "testing2_main",
     "plugins": [
       {
         "bridge": "cni-podman2",
```

Hope this all make sense. If not, I'm happy to try and provide more info.

**Comment by Luap99** [comment] 2021-04-29 08:32
It still doesn't reproduce for me. On your host check the content in `/run/containers/cni/dnsname/testing_main/addnhosts` when the container is running and try to do `nslookup testing 10.89.1.1` and `nslookup www.google.com 10.89.1.1`. Also can you check the dnsmasq logs with `sudo journalctl | grep dnsmasq`.

**Comment by fugkco** [comment] 2021-04-29 10:41
```
$ sudo cat /run/containers/cni/dnsname/testing_main/addnhosts
10.89.0.2       testing_testing_1       5edee655a11b    testing

$ sudo -E docker-compose exec testing sh -l
5edee655a11b:/# nslookup www.google.com 10.89.1.1
;; connection timed out; no servers could be reached

5edee655a11b:/# nslookup testing 10.89.1.1
;; connection timed out; no servers could be reached
```

dnsmasq logs contained a lot so just outputting recent events that started after I did compose up.
```
$ sudo journalctl --follow | grep dnsmasq
Apr 29 11:26:00 pop-os dnsmasq[3956712]: started, version 2.82 cachesize 150
Apr 29 11:26:00 pop-os dnsmasq[3956712]: compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset auth nettlehash DNSSEC loop-detect inotify dumpfile
Apr 29 11:26:00 pop-os dnsmasq[3956712]: warning: interface cni-podman4 does not currently exist
Apr 29 11:26:00 pop-os dnsmasq[3956712]: using only locally-known addresses for domain dns.podman
Apr 29 11:26:00 pop-os dnsmasq[3956712]: reading /etc/resolv.conf
Apr 29 11:26:00 pop-os dnsmasq[3956712]: using only locally-known addresses for domain dns.podman
Apr 29 11:26:00 pop-os dnsmasq[3956712]: using nameserver 192.168.1.3#53
Apr 29 11:26:00 pop-os dnsmasq[3956712]: read /run/containers/cni/dnsname/testing_main/addnhosts - 1 addresses
Apr 29 11:26:06 pop-os systemd[1]: podman.service: Unit process 3956712 (dnsmasq) remains running after unit stopped.
Apr 29 11:26:39 pop-os systemd[1]: podman.service: Found left-over process 3956712 (dnsmasq) in control group while starting unit. Ignoring.
```

Another thing I noticed is that despite the networks not existing (after doing compose down), there are some lingering files in `/var/lib/cni` and `/run/containers/cni/dnsname`. Could this have some effect on things? Are the ones in `/var/lib/cni` safe to clear (I assume the ones in `/run/containers/cni/dnsname` are)? I've also done several `sudo podman system reset` on different occasions, including one before my last reply, but they don't seem to get cleared.
```
$ sudo ls -la /var/lib/cni/networks/
total 36
drwxr-xr-x 9 root root 4096 Apr 29 07:30 .
drwx------ 4 root root 4096 Jun  1  2020 ..
drwxr-xr-x 2 root root 4096 Apr 25 09:23 project1
drwxr-xr-x 2 root root 4096 Apr 25 08:58 project1_default
drwxr-xr-x 2 root root 4096 Apr 25 23:28 podman
drwxr-xr-x 2 root root 4096 Apr 29 07:07 otherproject_default
drwxr-xr-x 2 root root 4096 Apr 29 07:22 otherproject_main
drwxr-xr-x 2 root root 4096 Apr 29 08:08 testing2_main
drwxr-xr-x 2 root root 4096 Apr 29 11:30 testing_main

$ sudo ls -la /run/containers/cni/dnsname
total 0
drwx------ 8 root root 160 Apr 29 07:30 .
drwx------ 3 root root  60 Apr 20 05:49 ..
drwx------ 2 root root 120 Apr 25 09:23 project1
drwx------ 2 root root 120 Apr 25 08:58 project1_default
drwx------ 2 root root 120 Apr 29 07:07 otherproject_default
drwx------ 2 root root 120 Apr 29 07:22 otherproject_main
drwx------ 2 root root 120 Apr 29 08:08 testing2_main
drwx------ 2 root root 120 Apr 29 11:30 testing_main

$ sudo podman network ls
NETWORK ID    NAME          VERSION  PLUGINS
2f259bab93aa  podman        0.4.0    bridge,portmap,firewall,tuning
35dcfa866dbd  testing_main  0.4.0    bridge,portmap,firewall,tuning,dnsname
```

**Comment by Luap99** [comment] 2021-04-30 16:23
> `dnsmasq[3961791]: warning: interface cni-podman4 does not currently exist`

I think this is the issue. Somehow the interface is wrong in the dnsmasq config. If you have no containers running remove  `/var/lib/cni/networks/` and `/run/containers/cni/dnsname` and try again.

**Comment by fugkco** [comment] 2021-05-03 07:56
Thanks. Removing those directories fixed it. I've not tried re-adding the aliases, and unless you would like me to further help with figuring out why adding aliases won't work, I'm not going to bother. Also, is there a reason those files are lingering despite the networks being deleted?

**Comment by Luap99** [comment] 2021-05-03 09:21
I don't think aliases have to do anything with this. The problem is the dangling config file in `/run/containers/cni/dnsname`.

steps to reproduce:
```
$ sudo podman network create net1
/etc/cni/net.d/net1.conflist
$ sudo podman run --rm --network net1  alpine nslookup google.de
Server:		10.89.8.1
Address:	10.89.8.1:53

Non-authoritative answer:
Name:	google.de
Address: 2a00:1450:4001:810::2003

Non-authoritative answer:
Name:	google.de
Address: 142.250.185.67

$ sudo podman network rm net1
net1
$ sudo podman network create net2
/etc/cni/net.d/net2.conflist
$ sudo podman network create net1
/etc/cni/net.d/net1.conflist
$ sudo podman run --rm --network net1  alpine nslookup google.de
nslookup: write to '10.89.9.1': Connection refused
;; connection timed out; no servers could be reached
```

I think this should be fixed in the dnsname plugin.

**Comment by Luap99** [comment] 2021-05-03 10:02
This should be fixed by https://github.com/containers/dnsname/pull/65

**Closed** 2021-05-03 13:22 UTC
Labels: kind/bug

**Comment by fugkco** [comment] 2021-05-03 13:25
Thank you @Luap99. Much appreciated.
