### ISSUE TITLE
Compatibility: Add filters for listing networks

### ISSUE THREAD

**Issue by minioin** [containers/podman#7462] opened 2020-08-26 15:46 UTC
I tried to run k3d with podman system service but k3d returned error with ``filters for listing networks is not implemented ``. As I looked at docker [api](https://docs.docker.com/engine/api/v1.40/#operation/NetworkList), it lists filters as an option.

This features is one of the first thing I encountered while running [k3d under podman ](https://github.com/rancher/k3d/issues/84).

**Comment by Luap99** [comment] 2020-08-26 19:28
The problem is that podman handles networking differently from docker. The podman backend only supports `name` and `plugin` as valid filter keys for networks. I guess that's the reason why the api don't allow filters.

**Comment by minioin** [comment] 2020-08-27 04:59
Considering that we already need a system service for docker compatibility, how is it difficult to maintain a list of networks to implement this feature? What is blocking this api exactly?

**Comment by Luap99** [comment] 2020-08-27 07:53
@mheon stated that he is looking to improve this in the future https://github.com/containers/podman/issues/7080#issuecomment-664021523

@minioin Do you know what filter k3d is using? I think we can at least implement the name filter for now.

**Comment by rhatdan** [comment] 2020-08-27 10:40
@minioin Time is the only thing blocking us.  Getting community to help build it is always helpful.

**Comment by iwilltry42** [comment] 2020-09-02 12:28
@Luap99 , in k3d we're only filtering by name: https://github.com/rancher/k3d/blob/main/pkg/runtimes/docker/network.go#L47-L54
```Go
        // (1) configure list filters
	args := filters.NewArgs()
	args.Add("name", name)

	// (2) get filtered list of networks
	networkList, err := docker.NetworkList(ctx, types.NetworkListOptions{
		Filters: args,
	})
```

**Comment by rhatdan** [comment] 2020-09-10 20:35
@iwilltry42 @minioin  @Luap99 Can we close this issue now since your PR has been merged?

**Comment by mheon** [comment] 2020-09-11 19:28
I'm going to go ahead and close this. We're not 100% there yet, but we can open separate, more specific issues for any remaining missing filters.

**Closed** 2020-09-11 19:27 UTC
Labels: kind/feature
