### ISSUE TITLE
Mounted file changes are not detected  by Rails or NPM inside the containers

### ISSUE THREAD

**Issue by AshDevFr** [containers/podman#24453] opened 2024-11-02 20:03 UTC
### Issue Description

We have found an issue when migrating from Docker to Podman that we have not been able to fix yet.

When we mount files to the container on our local setup, neither Rails nor Gulp.js are picking the changes to the files made from the host.
When we look inside the container, the files are correctly changed.

I have not tried many tools but `Rails` server is not picking up the changes, neither `Gulp.js` and `Vite.js`. 
With `vite.js` I was able to make it work by adding `usePolling: true` in the configuration, but for the other we don't have a fix. 

I created a [repository](https://github.com/AshDevFr/podman-fs-events-test) with an example to see the difference between Docker and Podman behavior.

---

When editing a mounted file directly from within the container instead of from the host, the change is detected. 

---

I have tried to play with `--userns=keep-id`but it did not fix the behavior.

I also tried the following that I found [here](https://github.com/containers/podman-compose/issues/654#issuecomment-2135644779)

```yaml
    environment:
      PODMAN_USERNS: "keep-id:uid=${MY_UID}:1000,gid=${MY_GID}:1000" # Define in .env
```

The issue persist. 

---

```bash
podman version 5.2.5
Running on MacOS (Arm64)
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Clone the repository [https://github.com/AshDevFr/podman-fs-events-test](https://github.com/AshDevFr/podman-fs-events-test)
2. Use the `podman` or `podman compose` commands from the README
3. Change a JS file and see that the change is not picked up by `vite.js`

### Describe the results you received

When using podman, the file changes are not detected by our tools running in the container.

### Describe the results you expected

It should work like Docker and our tools should be able to detect the changes

### podman info output

host:
  arch: arm64
  buildahVersion: 1.37.5
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-2.fc40.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 99.55
    systemPercent: 0.21
    userPercent: 0.24
  cpus: 4
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "40"
  eventLogger: journald
  freeLocks: 2047
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.11.3-200.fc40.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 15052582912
  memTotal: 16723427328
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.2-2.fc40.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.2
    package: netavark-1.12.2-1.fc40.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: crun
    package: crun-1.17-1.fc40.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.17
      commit: 000fa0d4eeed8938301f3bcf8206405315bc1017
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240906.g6b38f07-1.fc40.aarch64
    version: |
      pasta 0^20240906.g6b38f07-1.fc40.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-2.fc40.aarch64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 0
  swapTotal: 0
  uptime: 0h 39m 9.00s
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 20869787648
  graphRootUsed: 4103110656
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 10
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.5
  Built: 1729209600
  BuiltTime: Thu Oct 17 17:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.7
  Os: linux
  OsArch: linux/arm64
  Version: 5.2.5

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by Luap99** [comment] 2024-11-04 14:51
Duplicate of #22343

**Closed by Luap99** 2024-11-04 14:51 UTC
Labels: kind/bug, remote
