### ISSUE TITLE
podman-mac-helper is not managing docker.sock correctly

### ISSUE THREAD

**Issue by rgov** [containers/podman#18784] opened 2023-06-02 18:23 UTC
### Issue Description

I have been running Podman 4.5.1 on macOS, with `podman-mac-helper` to redirect `/var/run/docker.sock` to Podman.

I needed to run Docker Desktop, so I shut down Podman with:

    podman machine stop
    sudo podman-mac-helper uninstall

However this did not remove the symlink for `/var/run/docker.sock`:

    % ls -l /var/run/docker.sock
    lrwxr-xr-x  1 root  daemon  61 May 20 23:30 /var/run/docker.sock -> ~/.local/share/containers/podman/machine/podman.sock

When Docker Desktop starts, the `docker` command line tools cannot communicate with Docker Engine. It seems that `docker` will try to communicate over `/var/run/docker.sock` if it exists, but if not it uses `~/.docker/run/docker.sock`.

After shutting down Docker Desktop I then tried running `sudo podman-mac-helper install`, which succeeded but did not create `/var/run/docker.sock`.

### Steps to reproduce the issue

1. `sudo podman-mac-helper install` and check if `/var/run/docker.sock` was created.
2. `sudo podman-mac-helper uninstall` and check if `/var/run/docker.sock` was deleted.

### Describe the results you received

`podman-mac-helper` is not modifying the symlink.

### Describe the results you expected

`podman-mac-helper` manages the symlink properly.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

**Comment by rgov** [comment] 2023-06-02 18:48
The `podman-mac-helper install` command doesn't manipulate `/var/run/docker.sock` directly but installs a launchd service that can be inspected with:

```
sudo launchctl print system/com.github.containers.podman.helper-$USER
```

That service listens on its own socket, `/private/var/run/podman-helper-$USER.socket`, which creates the `docker.sock` symlink if you do:

```
echo "GO" | socat - UNIX-CONNECT:/private/var/run/podman-helper-$USER.socket
```

1. It doesn't look like it's designed to clean up after itself when you stop or uninstall the service.

2. While the use of a launchd service allows Podman to claim `docker.sock` automatically at startup, which is useful, it's not clear why this `podman-helper-$USER.socket` and `GO` signal exist. Why doesn't the launchd service just create the symlink directly, without installing a helper tool?

3. Why not redirect `~/.docker/run/docker.sock` which would not require privileges unless the user really needs to use `sudo docker` on macOS?

**Comment by Luap99** [comment] 2023-06-06 10:13
@n1hility PTAL

**Comment by n1hility** [comment] 2023-06-06 17:35
test:


> podman machine stop
> sudo podman-mac-helper uninstall
> ```
> 
> However this did not remove the symlink for `/var/run/docker.sock`:

Yes this is expected. The helper agent  is installed to assist podman so that it can create the appropriate link when its needed. It is not intended to be uninstalled when stopping, only to remove the capability entirely. Uninstall could clean up the link, but it is fairly common practice not to since these are replaced and are on temporary volumes.

> When Docker Desktop starts, the `docker` command line tools cannot communicate with Docker Engine. It seems that `docker` will try to communicate over `/var/run/docker.sock` if it exists, but if not it uses `~/.docker/run/docker.sock`.

That's not the behavior I see:

docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

If the docker commands are using ~/.docker/run/docker.sock it is because you have a context set (see ~/.docker/config.json && docker context ls)

Although even if it did fail over it still wouldn't work with many container tools, since the docker APIs in every language expect/var/run/docker.sock to point to the correct location.

Docker used to reclaim the socket on start, but in recent versions this changed, and now it only reclaims on system startup. This is probably a bug that Docker Desktop that it no longer checks on App Start (previous versions used to alert and reauth).

There are three ways you can get the link back

1. Reboot
2. Go into Docker's system prefs -> advanced -> then disable and reenable the checkbox
3. in a terminal run `sudo rm /var/run/docker.sock; sudo launchctil start com.docker.socket` 



> 
> After shutting down Docker Desktop I then tried running `sudo podman-mac-helper install`, which succeeded but did not create `/var/run/docker.sock`.

Right, it's not supposed to, it is created on demand by podman when needed using the agent/daemon. You should never need to reinstall

>  1. It doesn't look like it's designed to clean up after itself when you stop or uninstall the service.

Correct 

> 2. While the use of a launchd service allows Podman to claim `docker.sock` automatically at startup, which is useful, it's not clear why this `podman-helper-$USER.socket` and `GO` signal exist. Why doesn't the launchd service just create the symlink directly, without installing a helper tool?

There are a few reasons for this approach:

1. Something, e.g. Docker Desktop may reclaim /var/run/docker.sock after the agent was launched, which is a perfectly valid scenario (the user may want to switch between tools and shouldnt need to restart an internal system process/daemon when they want it to point to podman again. All that should be requires is podman machine start (with the noted exception that podman aims to be nice here and will back off if the socket is active)
2. Similar to 1) A competing agent claims /var/run/docker.sock on boot 
3. Multiple users on the same system use podman machine (switching back and forth), or switch between other container providers

> 3. Why not redirect `~/.docker/run/docker.sock` which would persist without the need for a service, and would not require privileges? (Unless the user _really_ needs to use `docker` as the root user on macOS.)

As mentioned above, the Docker CLI client won't actually use it if it was configured in the default settings (and the user has not explicitly set a different context - or they picked non-default settings in a previous install which would have set a custom context).

Also, many container tools and APIs that expect /var/run/docker.sock would fail since it would no longer be redirected.

**Comment by n1hility** [comment] 2023-06-06 19:17
Closing for now, since this is operating as intended, but feel free to propose further enhancements or feature requests

**Closed by n1hility** 2023-06-06 19:17 UTC
Labels: kind/bug, podman machine

**Comment by rgov** [comment] 2023-06-06 20:55
Thanks @n1hility.

First, is there agreement that there is a reasonable need to be able to switch between Podman and Docker? For example, for developers to check compatibility with both, or to file bugs? (In my case I was doing something like exporting an image from Docker to run it under Podman.)

Having to *reboot* all because of a broken symlink seems extreme. The user is very unlikely to find one of the other workarounds.

It sounds like it would be low effort, high reward to solve this issue on the part of `podman-mac-helper`, just an `os.Remove()` call in `uninstall.go` right? (*Ideally* the socket wouldn't exist when nothing is listening to it, but `uninstall` could effectively solve the problem without significant changes to the service.)

> Uninstall could clean up the link, but it is fairly common practice not to since these are replaced and are on temporary volumes.

Most of the time being a little messy with temporary files is harmless for the reasons you mention but in this case the leftover symlink is causing a problem.

Maybe it's common practice but it doesn't seem like a good one worth aspiring to. Dynamically allocated memory is also reclaimed when a process exits but of course it would be bad practice to never free memory. The same should apply to any resource including temporary files written to disk.

> Docker used to reclaim the socket on start, but in recent versions this changed, and now it only reclaims on system startup.

I can't blame Docker's new behavior here on causing a regression. It sounds like a well-behaved citizen: it sees an existing file so it doesn't overwrite it.

---

> If the docker commands are using `~/.docker/run/docker.sock` it is because you have a context set

I *do* have a context set according to your commands, but this was done implicitly and I don't know why or by what. So maybe other users end up in this configuration?
