### ISSUE TITLE
:bug: internal libpod error when attempting to read large text file output (stdout)

### ISSUE THREAD

**Issue by thiago-scherrer** [containers/podman#18650] opened 2023-05-22 12:19 UTC
### Issue Description

When attempting to read a text, log, etc. via stdout with at least 8000 lines, the following error occurs:

```sh
Error: Timed out waiting for file 
/home/<my_user_here>/.local/share/containers/storage/overlay-containers/xx/userdata/xx/exit/xx: 
Internal libpod error
```

### Steps to reproduce the issue

Steps to reproduce the issue
1.
```sh
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 9999
```

### Describe the results you received

Describe the results you received
```sh
...
Yqww1YN3xXAaGIF6QzSM
LFkdyz8nU2ha2fL16JBX
3ku5GuKz0EsDrd3G8LbD
Q6YhndX1vcY2l9Ld8QD1
M7ZohpICbwbhDlpQJPu0
Rf9kd9VxeiYCzMGXekjx
BOcUZdGVmnhU8x0BToPu
Error: timed out waiting for file /home/<my_user_here>/.local/share/containers/storage/overlay-containers/xxxxx/userdata/xxxxx/exit/xxxxxx: internal libpod error
[~]$ (Here, I am dropped from inside the container to the terminal of my machine.)
```

### Describe the results you expected

Describe the results you expected

Outputting all 9999 lines without dropping me from inside the container.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.


$ podman version
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec 31 21:00:00 1969
OS/Arch:      linux/amd64


```sh
$ podman info
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 8
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: 8X3N2L3
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.19.0-41-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 242397184
  memTotal: 16501121024
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 1159106560
  swapTotal: 2147479552
  uptime: 95h 47m 42.5s (Approximately 3.96 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/<my_user>/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/<my_user>/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 25
  runRoot: /run/user/1001/containers
  volumePath: /home/<my_user>/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 21:00:00 1969
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

I am running the latest version of Ubuntu, 22.04.2 LTS:
 
```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```
```sh
$ dpkg -l podman
||/ Nome           Versão             Arquitectura Descrição
+++-==============-==================-============-==========================================
ii  podman         3.4.4+ds1-1ubuntu1 amd64        engine to run OCI-based containers in Pods
```

**Comment by Luap99** [comment] 2023-05-22 12:50
Try running with `--log-driver k8s-file` or `--log-driver none`

Duplicate of #13779

**Closed by Luap99** 2023-05-22 12:50 UTC
Labels: kind/bug
