### ISSUE TITLE
Error: writing blob: storing blob to file: unexpected EOF

### ISSUE THREAD

**Issue by dpnishant** [containers/podman#18142] opened 2023-04-11 07:27 UTC
### Issue Description

This is in continuation to https://github.com/containers/podman/issues/12962, https://github.com/containers/podman/issues/17545. The issue still persists even after upgrading podman client to 4.4.4 and podman server to 4.4.2 on macOS Ventura (13.2.1) on M1 Max.

**Client Logs**
```sh
➜  ~ podman --version
podman version 4.4.4
➜  ~ podman pull --platform linux/amd64 hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612
Trying to pull hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612...
Getting image source signatures
Copying blob sha256:3d51a39ba405fc1b46007633c09b5388246bde32fdc9e224fd1d46e15f8cab4f
Copying blob sha256:391aa60d798921957837d6d49b2c8ec1d40090acdb93e7b63e2b10311de10bb1
Copying blob sha256:7608715873ec5c02d370e963aa9b19a149023ce218887221d93fe671b3abbf58
Copying blob sha256:efd2628a9d8be4265cd14a2270cb994333917832af3dab6ba06f14b3f8ea673f
Copying blob sha256:6d87af36c87a2afe3797ea76c0f29e630ce254a41e3183e7c75da10c3afd73ea
Copying blob sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec
Copying blob sha256:b8bade255407e5aae315a50508ee20045f1bf60870d23a8f2171ffcaacbe3604
Copying blob sha256:580263e2d3156c888372e0695254fcf0c80518e6efcacc524e70afe323928f6e
Copying blob sha256:6068cad611ea0100a9f89066da5246eade076e24a12c48989b51ed63fba8ec22
Copying blob sha256:3cfc1b709af2ad4de3724b037345ef34da299623103202f9d30f7373271b851e
Error: writing blob: storing blob to file "/var/tmp/storage3331955061/6": happened during read: (heuristic tuning data: last retry 56506494, current offset 56571510; 258707.443 ms total, 252.803 ms since progress): unexpected EOF
➜  ~
```

**Server Logs**
```sh
[core@localhost ~]$ systemctl status podman
○ podman.service - Podman API Service
     Loaded: loaded (/usr/lib/systemd/system/podman.service; disabled; preset: disabled)
     Active: inactive (dead) since Tue 2023-04-11 11:56:54 IST; 9min ago
   Duration: 5.082s
TriggeredBy: ● podman.socket
       Docs: man:podman-system-service(1)
    Process: 1600 ExecStart=/usr/bin/podman $LOGGING system service (code=exited, status=0/SUCCESS)
   Main PID: 1600 (code=exited, status=0/SUCCESS)
        CPU: 77ms

Apr 11 11:56:49 localhost.localdomain systemd[1]: Starting podman.service - Podman API Service...
Apr 11 11:56:49 localhost.localdomain systemd[1]: Started podman.service - Podman API Service.
Apr 11 11:56:49 localhost.localdomain podman[1600]: time="2023-04-11T11:56:49+05:30" level=info msg="/usr/bin/podman filtering at log level info"
Apr 11 11:56:49 localhost.localdomain podman[1600]: time="2023-04-11T11:56:49+05:30" level=info msg="Not using native diff for overlay, this may c>
Apr 11 11:56:49 localhost.localdomain podman[1600]: 2023-04-11 11:56:49.808309953 +0530 IST m=+0.055997311 system refresh
Apr 11 11:56:49 localhost.localdomain podman[1600]: time="2023-04-11T11:56:49+05:30" level=info msg="Setting parallel job count to 19"
Apr 11 11:56:49 localhost.localdomain podman[1600]: time="2023-04-11T11:56:49+05:30" level=info msg="Using systemd socket activation to determine >
Apr 11 11:56:49 localhost.localdomain podman[1600]: time="2023-04-11T11:56:49+05:30" level=info msg="API service listening on \"/run/podman/podman>
Apr 11 11:56:54 localhost.localdomain systemd[1]: podman.service: Deactivated successfully.
[core@localhost ~]$
[core@localhost ~]$
[core@localhost ~]$ podman --version
podman version 4.4.2
[core@localhost ~]$
[core@localhost ~]$
[core@localhost ~]$ podman --log-level debug system service -t 0
INFO[0000] podman filtering at log level debug
DEBU[0000] Called service.PersistentPreRunE(podman --log-level debug system service -t 0)
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /var/home/core/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] systemd-logind: Unknown object '/'.
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /var/home/core/.local/share/containers/storage
DEBU[0000] Using run root /run/user/502/containers
DEBU[0000] Using static dir /var/home/core/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/502/libpod/tmp
DEBU[0000] Using volume path /var/home/core/.local/share/containers/storage/volumes
DEBU[0000] Using transient store: false
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that metacopy is not being used
DEBU[0000] Cached value indicated that native-diff is usable
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false
DEBU[0000] Initializing event backend journald
DEBU[0000] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument
DEBU[0000] Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument
DEBU[0000] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument
DEBU[0000] Using OCI runtime "/usr/bin/crun"
INFO[0000] Setting parallel job count to 19
DEBU[0000] registered SIGHUP watcher for config
INFO[0000] API service listening on "/run/user/502/podman/podman.sock". URI: "unix:/run/user/502/podman/podman.sock"
DEBU[0000] CORS Headers were not set
DEBU[0000] waiting for SIGHUP to reload configuration
DEBU[0000] API service(s) shutting down, idle for 0s
DEBU[0000] API service shutdown request ignored as timeout Duration is UnlimitedService
DEBU[0003] IdleTracker:new 0m+0h/0t connection(s)        X-Reference-Id=0x40006ee008
DEBU[0003] IdleTracker:active 0m+0h/1t connection(s)     X-Reference-Id=0x40006ee008
@ - - [11/Apr/2023:12:07:08 +0530] "GET /v4.4.4/libpod/_ping HTTP/1.1" 200 2 "" "Go-http-client/1.1"
DEBU[0003] IdleTracker:idle 1m+0h/1t connection(s)       X-Reference-Id=0x40006ee008
DEBU[0003] IdleTracker:closed 1m+0h/1t connection(s)     X-Reference-Id=0x40006ee008
DEBU[0003] IdleTracker:new 0m+0h/1t connection(s)        X-Reference-Id=0x40006ee010
DEBU[0003] IdleTracker:active 0m+0h/2t connection(s)     X-Reference-Id=0x40006ee010
DEBU[0003] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0003] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0003] Loading registries configuration "/etc/containers/registries.conf.d/999-podman-machine.conf"
DEBU[0003] Stored credentials for hub.foobar.com in credential helper containers-auth.json
DEBU[0003] Pulling image hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612 (policy: always)
DEBU[0003] Looking up image "hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612" in local containers storage
DEBU[0003] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0003] Trying "hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612" ...
DEBU[0003] Trying "hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612" ...
DEBU[0003] Trying "hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612" ...
DEBU[0003] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0003] Attempting to pull candidate hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612 for hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612
DEBU[0003] parsed reference into "[overlay@/var/home/core/.local/share/containers/storage+/run/user/502/containers]hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612"
DEBU[0003] Copying source image //hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612 to destination image [overlay@/var/home/core/.local/share/containers/storage+/run/user/502/containers]hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612
DEBU[0003] Using registries.d directory /etc/containers/registries.d
DEBU[0003] Trying to access "hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612"
DEBU[0003] Found credentials for hub.foobar.com/apps/nginx in credential helper containers-auth.json in file /var/tmp/auth.json.512814193
DEBU[0003]  No signature storage configuration found for hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612, using built-in default file:///var/home/core/.local/share/containers/sigstore
DEBU[0003] Looking for TLS certificates and private keys in /etc/docker/certs.d/hub.foobar.com
DEBU[0003] GET https://hub.foobar.com/v2/
DEBU[0005] Ping https://hub.foobar.com/v2/ status 401
DEBU[0005] GET https://hub.foobar.com/v2/auth?account=johndoe&scope=repository%3Aapps%2Fnginx%3Apull&service=hub.foobar.com
DEBU[0007] Increasing token expiration to: 60 seconds
DEBU[0007] GET https://hub.foobar.com/v2/apps/nginx/manifests/1.0.3_RELEASE_20230308210704612
DEBU[0009] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.v2+json"
DEBU[0009] Using blob info cache at /var/home/core/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0009] IsRunningImageAllowed for image docker:hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612
DEBU[0009]  Using default policy section
DEBU[0009]  Requirement 0: allowed
DEBU[0009] Overall: allowed
DEBU[0009] Downloading /v2/apps/nginx/blobs/sha256:cf5492592b3e75afe4c0b110df61994272b9065975bb1211fb880504f8b2768c
DEBU[0009] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:cf5492592b3e75afe4c0b110df61994272b9065975bb1211fb880504f8b2768c
DEBU[0012] Reading /var/home/core/.local/share/containers/sigstore/apps/nginx@sha256=147dee945dc0cfd4aa38efb6a421d1f3f7fd38379d49f8dce5aab595755c2034/signature-1
DEBU[0012] Not looking for sigstore attachments: disabled by configuration
DEBU[0012] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json]
DEBU[0012] ... will first try using the original manifest unmodified
DEBU[0012] Checking if we can reuse blob sha256:3d51a39ba405fc1b46007633c09b5388246bde32fdc9e224fd1d46e15f8cab4f: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0012] Checking if we can reuse blob sha256:391aa60d798921957837d6d49b2c8ec1d40090acdb93e7b63e2b10311de10bb1: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0012] Checking if we can reuse blob sha256:7608715873ec5c02d370e963aa9b19a149023ce218887221d93fe671b3abbf58: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0012] Checking if we can reuse blob sha256:efd2628a9d8be4265cd14a2270cb994333917832af3dab6ba06f14b3f8ea673f: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0012] Checking if we can reuse blob sha256:6d87af36c87a2afe3797ea76c0f29e630ce254a41e3183e7c75da10c3afd73ea: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0012] Checking if we can reuse blob sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0012] Failed to retrieve partial blob: blob type not supported for partial retrieval
DEBU[0012] Skipping blob sha256:391aa60d798921957837d6d49b2c8ec1d40090acdb93e7b63e2b10311de10bb1 (already present):
DEBU[0012] Skipping blob sha256:7608715873ec5c02d370e963aa9b19a149023ce218887221d93fe671b3abbf58 (already present):
DEBU[0012] Downloading /v2/apps/nginx/blobs/sha256:3d51a39ba405fc1b46007633c09b5388246bde32fdc9e224fd1d46e15f8cab4f
DEBU[0012] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:3d51a39ba405fc1b46007633c09b5388246bde32fdc9e224fd1d46e15f8cab4f
DEBU[0012] Failed to retrieve partial blob: blob type not supported for partial retrieval
DEBU[0012] Downloading /v2/apps/nginx/blobs/sha256:efd2628a9d8be4265cd14a2270cb994333917832af3dab6ba06f14b3f8ea673f
DEBU[0012] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:efd2628a9d8be4265cd14a2270cb994333917832af3dab6ba06f14b3f8ea673f
DEBU[0012] Checking if we can reuse blob sha256:b8bade255407e5aae315a50508ee20045f1bf60870d23a8f2171ffcaacbe3604: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0012] Checking if we can reuse blob sha256:580263e2d3156c888372e0695254fcf0c80518e6efcacc524e70afe323928f6e: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0012] Failed to retrieve partial blob: blob type not supported for partial retrieval
DEBU[0012] Downloading /v2/apps/nginx/blobs/sha256:6d87af36c87a2afe3797ea76c0f29e630ce254a41e3183e7c75da10c3afd73ea
DEBU[0012] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:6d87af36c87a2afe3797ea76c0f29e630ce254a41e3183e7c75da10c3afd73ea
DEBU[0012] Failed to retrieve partial blob: blob type not supported for partial retrieval
DEBU[0012] Downloading /v2/apps/nginx/blobs/sha256:580263e2d3156c888372e0695254fcf0c80518e6efcacc524e70afe323928f6e
DEBU[0012] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:580263e2d3156c888372e0695254fcf0c80518e6efcacc524e70afe323928f6e
DEBU[0012] Failed to retrieve partial blob: blob type not supported for partial retrieval
DEBU[0012] Downloading /v2/apps/nginx/blobs/sha256:b8bade255407e5aae315a50508ee20045f1bf60870d23a8f2171ffcaacbe3604
DEBU[0012] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:b8bade255407e5aae315a50508ee20045f1bf60870d23a8f2171ffcaacbe3604
DEBU[0012] Failed to retrieve partial blob: blob type not supported for partial retrieval
DEBU[0012] Downloading /v2/apps/nginx/blobs/sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec
DEBU[0012] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec
DEBU[0015] Detected compression format gzip
DEBU[0015] Using original blob without modification
DEBU[0015] Checking if we can reuse blob sha256:6068cad611ea0100a9f89066da5246eade076e24a12c48989b51ed63fba8ec22: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0015] Failed to retrieve partial blob: blob type not supported for partial retrieval
DEBU[0015] Downloading /v2/apps/nginx/blobs/sha256:6068cad611ea0100a9f89066da5246eade076e24a12c48989b51ed63fba8ec22
DEBU[0015] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:6068cad611ea0100a9f89066da5246eade076e24a12c48989b51ed63fba8ec22
DEBU[0015] Detected compression format gzip
DEBU[0015] Using original blob without modification
DEBU[0015] Checking if we can reuse blob sha256:3cfc1b709af2ad4de3724b037345ef34da299623103202f9d30f7373271b851e: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true
DEBU[0015] Failed to retrieve partial blob: blob type not supported for partial retrieval
DEBU[0015] Downloading /v2/apps/nginx/blobs/sha256:3cfc1b709af2ad4de3724b037345ef34da299623103202f9d30f7373271b851e
DEBU[0015] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:3cfc1b709af2ad4de3724b037345ef34da299623103202f9d30f7373271b851e
DEBU[0015] Detected compression format gzip
DEBU[0015] Using original blob without modification
DEBU[0015] Detected compression format gzip
DEBU[0015] Using original blob without modification
DEBU[0015] Detected compression format gzip
DEBU[0015] Using original blob without modification
DEBU[0015] Detected compression format gzip
DEBU[0015] Using original blob without modification
DEBU[0016] Reading blob body from https://hub.foobar.com/v2/apps/nginx/blobs/sha256:efd2628a9d8be4265cd14a2270cb994333917832af3dab6ba06f14b3f8ea673f failed (&errors.errorString{s:"unexpected EOF"}), decision inputs: lastRetryOffset 0, offset 65079, 811.584 ms since first connection, 1.597 ms since last progress
DEBU[0016] Not reconnecting to https://hub.foobar.com/v2/apps/nginx/blobs/sha256:efd2628a9d8be4265cd14a2270cb994333917832af3dab6ba06f14b3f8ea673f because only 65079 bytes progress made
DEBU[0016] Reading blob body from https://hub.foobar.com/v2/apps/nginx/blobs/sha256:3d51a39ba405fc1b46007633c09b5388246bde32fdc9e224fd1d46e15f8cab4f failed (&errors.errorString{s:"unexpected EOF"}), decision inputs: lastRetryOffset 0, offset 65079, 1099.203 ms since first connection, 275.780 ms since last progress
DEBU[0016] Not reconnecting to https://hub.foobar.com/v2/apps/nginx/blobs/sha256:3d51a39ba405fc1b46007633c09b5388246bde32fdc9e224fd1d46e15f8cab4f because only 65079 bytes progress made
DEBU[0017] Detected compression format gzip
DEBU[0017] Using original blob without modification
DEBU[0018] Detected compression format gzip
DEBU[0018] Using original blob without modification
DEBU[0263] Reading blob body from https://hub.foobar.com/v2/apps/nginx/blobs/sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec failed (&errors.errorString{s:"unexpected EOF"}), decision inputs: lastRetryOffset 0, offset 56506494, 248252.428 ms since first connection, 7.868 ms since last progress
INFO[0263] Reading blob body from https://hub.foobar.com/v2/apps/nginx/blobs/sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec failed (unexpected EOF), reconnecting…
DEBU[0264] GET https://hub.foobar.com/v2/auth?account=johndoe&scope=repository%3Aapps%2Fnginx%3Apull&service=hub.foobar.com
DEBU[0267] Increasing token expiration to: 60 seconds
DEBU[0267] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec
DEBU[0272] Succesfully reconnected to https://hub.foobar.com/v2/apps/nginx/blobs/sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec
DEBU[0274] Reading blob body from https://hub.foobar.com/v2/apps/nginx/blobs/sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec failed (&errors.errorString{s:"unexpected EOF"}), decision inputs: lastRetryOffset 56506494, offset 56571510, 258707.443 ms since first connection, 252.803 ms since last progress
DEBU[0274] Not reconnecting to https://hub.foobar.com/v2/apps/nginx/blobs/sha256:18e855ea6c2e5aea18b9594ecf1324124c242798b9cf7bd33a3c0175d0ee1aec because only 65016 bytes progress made
DEBU[1029] Reading blob body from https://hub.foobar.com/v2/apps/nginx/blobs/sha256:6d87af36c87a2afe3797ea76c0f29e630ce254a41e3183e7c75da10c3afd73ea failed (&errors.errorString{s:"unexpected EOF"}), decision inputs: lastRetryOffset 0, offset 228587645, 1014300.379 ms since first connection, 2.298 ms since last progress
INFO[1029] Reading blob body from https://hub.foobar.com/v2/apps/nginx/blobs/sha256:6d87af36c87a2afe3797ea76c0f29e630ce254a41e3183e7c75da10c3afd73ea failed (unexpected EOF), reconnecting…
DEBU[1030] GET https://hub.foobar.com/v2/auth?account=johndoe&scope=repository%3Aapps%2Fnginx%3Apull&service=hub.foobar.com
DEBU[1033] Increasing token expiration to: 60 seconds
DEBU[1033] GET https://hub.foobar.com/v2/apps/nginx/blobs/sha256:6d87af36c87a2afe3797ea76c0f29e630ce254a41e3183e7c75da10c3afd73ea
DEBU[1037] Succesfully reconnected to https://hub.foobar.com/v2/apps/nginx/blobs/sha256:6d87af36c87a2afe3797ea76c0f29e630ce254a41e3183e7c75da10c3afd73ea
DEBU[1039] Error pulling candidate hub.foobar.com/apps/nginx:1.0.3_RELEASE_20230308210704612: writing blob: storing blob to file "/var/tmp/storage3331955061/6": happened during read: (heuristic tuning data: last retry 56506494, current offset 56571510; 258707.443 ms total, 252.803 ms since progress): unexpected EOF
@ - - [11/Apr/2023:12:07:08 +0530] "POST /v4.4.4/libpod/images/pull?alltags=false&arch=amd64&authfile=&os=linux&password=&policy=always&quiet=false&reference=hub.foobar.com%2Fapps%2Fnginx%3A1.0.3_RELEASE_20230308210704612&username=&variant= HTTP/1.1" 200 1389 "" "Go-http-client/1.1"
DEBU[1039] IdleTracker:idle 1m+0h/2t connection(s)       X-Reference-Id=0x40006ee010
DEBU[1039] IdleTracker:closed 1m+0h/2t connection(s)     X-Reference-Id=0x40006ee010
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Same as: 
2. https://github.com/containers/podman/issues/12962 
3. https://github.com/containers/podman/issues/17545

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc37.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.71
    systemPercent: 0.16
    userPercent: 0.13
  cpus: 6
  distribution:
    distribution: fedora
    variant: coreos
    version: "37"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 502
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.2.8-200.fc37.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 7787401216
  memTotal: 8300191744
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.3-2.fc37.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/502/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: unix:/run/user/502/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.aarch64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 58m 20.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 2577489920
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/502/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.2
  Built: 1677669759
  BuiltTime: Wed Mar  1 16:52:39 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/arm64
  Version: 4.4.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

**Comment by Luap99** [comment] 2023-04-12 10:47
@mtrmac PTAL

**Comment by mtrmac** [comment] 2023-04-12 19:28
Look at all the log lines with `decision inputs`: that’s quite a few “unexpected EOF” errors. We do retry failed requests, but the retries do need to stop _eventually_. There’s probably no universally-right threshold for that, but this does seem rather far in direction of “too many”, especially in how they seem to come in bursts. (For retrying, we require either some time between retries, or some progress being made; here we see failures within a few seconds, and at around 60 kB of data.)

In this case, the copy has failed for _three_ separate reasons!

So I’d rather suggest that this might be best improved by understanding the root cause of the failures, instead of papering them over with retries. Especially it’s rather suggestive that two blobs fail with exactly the same 65079 offset, and one other failure is at offset 56571510-56506494=65016 . That seems very non-random (TCP slow start might be involved, but still…); wildly guessing, is there something in the network limiting the number of concurrent connections? Some kind of connection-tracking firewall with full state tables? I don’t have any expertise in this area or in debugging that…

---

Focusing only on the heuristics, that was further relaxed in https://github.com/containers/image/pull/1847 / https://github.com/containers/image/pull/1859 , which is not yet included in Podman 4.4.2. That might have made a difference for two of the failures, but not for the last one (were a retried connection also fails within about 65 kB ).

**Comment by dpnishant** [comment] 2023-04-13 04:07
@mtrmac I too can't guess the root cause but I can tell for sure that pulling the same image or any other image on the same network fails everytime with Podman but works successfully with Docker CLI (Docker Desktop) every single time on the same network.

**Comment by pccowboy** [comment] 2023-04-20 19:43
FWIW, I ran into this today when using the SHA URL.  If I use a URL like `ghcr.io/pccowboy/postscript_test_project:main`, my pull succeeds.  HTH

**Comment by vrothberg** [comment] 2023-05-15 14:34
@dpnishant @pccowboy are you running behind a proxy?  (misconfigured) Proxies have turned out be causing quite a lot of unexpected EOFs inthe past.

**Comment by dpnishant** [comment] 2023-05-17 18:19
@vrothberg Not proxy but behind corporate VPN gateway and CASB. I reported the same issue to the folks from my corporate vpn gateway and the issue seems to have gone away for now, by enabling "Always connect using SSL" in the VPN client.

**Comment by vrothberg** [comment] 2023-06-13 14:20
Thanks, @dpnishant.

I think we can close the issue then.

**Closed by vrothberg** 2023-06-13 14:20 UTC
Labels: kind/bug, remote
