### ISSUE TITLE
Can't use kubernetes secret as env var

### ISSUE THREAD

**Issue by odra** [containers/podman#16623] opened 2022-11-25 11:45 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am unable to use a kubernetes secret as an environment variable in a Pod when using `podman play kube pod.yaml`.

**Steps to reproduce the issue:**

1. Create a kubernetes secret yaml file and store it as a podman secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  foo: YmFy
```

3.  Create a pod.yaml file:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: app
      image: fedora
      command: ["/usr/bin/sleep", "infinity"]
      volumeMounts:
        - name: mysecret
          mountPath: "/etc/mysecret"
          readOnly: true
            # envFrom:
            # - secretRef:
            # name: mysecret
      env:
        - name: FOO
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: foo
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret
        optional: false
```

5. Run `podman play kube --replace pod.yaml`.

**Describe the results you received:**

```
$ podman play kube --replace pod.yaml 
Pods stopped:
7bcc03dcd28a8b558c080f263ad880ac572633bdb9f3604f323c23d508ac4a42
Pods removed:
7bcc03dcd28a8b558c080f263ad880ac572633bdb9f3604f323c23d508ac4a42
Error: cannot set env FOO: secret mysecret is not valid JSON: invalid character 'a' looking for beginning of value
```

**Describe the results you expected:**

I would expect the secret key value (foo) to available as a env var "FOO".

Also, the commented section which that uses "envFrom", which should  mount the whole secret content as env key -> value, is totally ignored.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.7
Built:        Fri Nov 11 12:24:13 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 98.63
    systemPercent: 0.3
    userPercent: 1.07
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: 192.168.1.16
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.0.9-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 19659972608
  memTotal: 33395277824
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.7-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7
      commit: 40d996ea8a827981895ce22886a9bac367f87264
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 19327344640
  swapTotal: 19327344640
  uptime: 19h 43m 14.00s (Approximately 0.79 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/lrossett/.config/containers/storage.conf
  containerStore:
    number: 13
    paused: 0
    running: 0
    stopped: 13
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/lrossett/.local/share/containers/storage
  graphRootAllocated: 417295147008
  graphRootUsed: 208372506624
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 34
  runRoot: /run/user/1000/containers
  volumePath: /home/lrossett/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668180253
  BuiltTime: Fri Nov 11 12:24:13 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/am
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman-4.3.1-1.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, I also tested it with the "latest podman" by building it myself from the main branch.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Nothing special, just running it from my local development machine.

**Comment by Luap99** [comment] 2022-11-25 13:32
Duplicate of https://github.com/containers/podman/issues/16269

**Closed by Luap99** 2022-11-25 13:32 UTC
Labels: kind/bug
