### ISSUE TITLE
Feature: support uidmap with `podman play kube`

### ISSUE THREAD

**Issue by akvadrako** [containers/podman#7504] opened 2020-08-30 10:55 UTC
/kind feature

I would like to use pod.yaml as a rootless alternative to docker-compose. In a pod I'm working on, some containers expect to run as root and some expect to run as a non-root user. I would like all of them to map to my current user in the host's namespace.

For this I need some way to pass the **uidmap** option using a pod.yaml file. Something like:

```
spec:
  containers:
  - name: as1000
    securityContext:
      UIDMap: 300:0:1
      GIDMap: 300:0:1
```

Related: https://github.com/moby/moby/issues/28593 https://github.com/kubernetes/enhancements/issues/127 https://github.com/containers/podman/issues/6123

**Comment by rhatdan** [comment] 2020-09-10 21:05
Is this syntax valid for Kubernetes?

**Comment by rhatdan** [comment] 2020-09-10 21:05
@haircommander @giuseppe WDYT?

**Comment by haircommander** [comment] 2020-09-10 21:26
hey @Akasurde upstream still seems to be figuring out how the support for usernamespaces will land. right now, it's added as an annotation, and only processed by the cri implementation. I would rather not handle this until there is clarity with the upstream on what the approach will be

**Comment by Akasurde** [comment] 2020-09-11 05:13
@haircommander I think you meant @akvadrako

**Comment by haircommander** [comment] 2020-09-11 13:30
oops, sorry for the noise, yes I did mean @akvadrako

**Comment by haircommander** [comment] 2020-09-11 13:32
@akvadrako does the https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#securitycontext-v1-core `runAsUser` field fit your needs? I'm not sure we support it right now, but if you need a container to run as a certain user on the host, I do not think you need usernamespaces for that

**Comment by akvadrako** [comment] 2020-09-11 13:46
`runAsUser` is supported, but it's not enough. For example, given this pod:
```yaml
apiVersion: v1
kind: Pod
metadata: { name: demo }
spec:
  containers:
  - name: as1000
    image: docker.io/alpine
    command: [ "sh", "-c", "touch /tmp/abc-1000" ]
    securityContext:
      runAsUser: 1000
    volumeMounts:
    - { mountPath: /tmp, name: tmp }
  - name: asroot
    image: docker.io/alpine
    command: [ "sh", "-c", "touch /tmp/abc-root" ]
    securityContext:
      runAsUser: 0
    volumeMounts:
    - { mountPath: /tmp, name: tmp }
  volumes:
  - name: tmp
    hostPath: { path: /tmp }
```
one finds that:
- /tmp/abc-root is owned by my current user
- /tmp/abc-1000 is owned by 100999 (due to my /etc/subuid file)
but I want that both files are owned by my current user.

**Comment by dtitov** [comment] 2020-09-16 16:52
If I understand this request correctly, it's about the possibility to achieve Podman's `--userns=keep-id` with `podman play kube`, which is currently not supported by this command (AFAIK). If it's the case, then +1 to the issue, it would be a very useful feature, IMHO.

**Comment by akvadrako** [comment] 2020-09-17 09:14
According to the `keep-id` docs, that's not quite enough. It says it's only maps the current UID to the same UID in the container. But my containers are running with (A) user=0 and (B) user=123 (for example), while my UID is 1000. What I want is for container (A), 0 is mapped to 1000, while for container (B), 123 is mapped to 1000.

**Comment by dtitov** [comment] 2020-09-17 09:27
Ah, I see, so you need a more comprehensive kind of mapping... 

Well, for my personal use-case it's good enough to just get `--userns=keep-id` implemented in `podman play kube` context. Not use if I need to create a separate request for this, so I'm looking forward to the feedback from devs.

**Comment by rhatdan** [comment] 2020-11-23 12:25
I like the idea of podman play kube --userns=keep-id

**Comment by rhatdan** [comment] 2020-12-24 12:06
This is a duplicate of #8269

**Comment by akvadrako** [comment] 2020-12-24 12:17
How is this a duplicate? #8269 doesn't seem to mention specifying uidmap for containers.

**Comment by rhatdan** [comment] 2020-12-26 10:05
Sorry I misread the description.

**Comment by rhatdan** [comment] 2020-12-26 10:06
Sorry I misread this issue.

I don't see a way for us to change the pod yaml spec until it gets changed in upstream Kubernetes, which I believe is being worked on.  Podman should only work with the same yaml files that kubernetes supports.

**Comment by akvadrako** [comment] 2020-12-26 10:42
A reasonable position. The linked issue seems stalled for years but does it looks like they'll implement it eventually. https://github.com/kubernetes/enhancements/issues/127

**Comment by rhatdan** [comment] 2020-12-26 11:37
There has been a decent amount of movement and discussion on user namespace support in k8s, over the last few weeks in this issue:

https://github.com/kubernetes/enhancements/pull/2101

**Comment by rhatdan** [comment] 2021-01-26 15:57
Kunernetes discussions continue.

**Comment by rhatdan** [comment] 2021-02-26 09:59
No progress.

**Comment by rhatdan** [comment] 2022-02-17 14:21
SGTM.  I think adding that flag to podman play kube makes sense.

**Comment by rhatdan** [comment] 2022-05-06 14:23
@giuseppe Could you add --userns=auto to podman play kube?

**Comment by giuseppe** [comment] 2022-05-06 16:22
at this point I suggest we just wait for the feature to land in Kubernetes (phase 1 should not be too far)

**Comment by giuseppe** [comment] 2022-05-06 16:24
more details about phase 1 and what it means: https://github.com/kubernetes/enhancements/pull/3065

**Comment by rhatdan** [comment] 2022-05-06 17:52
But why not also support --auto, for the case where I just want to run within a unigue user namespace.  We can follow the yaml file if it has rules, but allow us to run in random seems like a nice feature.

**Comment by giuseppe** [comment] 2022-05-06 20:02
PR here: https://github.com/containers/podman/pull/14140

**Closed** 2022-05-10 17:28 UTC
Labels: kind/feature
