### ISSUE TITLE
--replace should work with dependent containers.

### ISSUE THREAD

**Issue by EvanCarroll** [containers/podman#18575] opened 2023-05-15 18:02 UTC
### Issue Description

I would think if container `foo` depends on container `bar`. You should still be able to `--replace` on `foo`. However, currently you can't.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman run --name foo alpine:3 /bin/sleep 180`
2. `podman run --name bar --requires foo alpine:3 /bin/sleep 180`
3. `podman run --name foo --replace alpine:3 /bin/sleep 180`

### Describe the results you received

> Error: container 7f607050acca1a64e5a87315fb808723b1d51f73ee5a48b4c028d743f479fc5c has dependent containers which must be removed before it: 5d3bae2f570a6a34e4bdedd71e7540ab9dbf4a22ecacd7f273c4c672b2a0fb3a: container already exists

### Describe the results you expected

it to work.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

podman version 4.3.1

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment] 2023-05-16 06:55
Thanks for taking the time to reach out, @EvanCarroll !

I like the idea.  @Luap99 @mheon WDYT?

**Comment by Luap99** [comment] 2023-05-16 08:35
> Describe the results you expected
> it to work.

What does to work here mean? Should it remove the dependency container as well or atomically replace the container while keeping the dependencies?
The former could lead to unexpected container deletion and the second one seems impossible to implement (considering the container may be running).

**Comment by EvanCarroll** [comment] 2023-05-16 17:21
In my opinion, in the above, it should mean "atomically replace the container while keeping the dependencies". As in given

```
podman run --name foo alpine:3 /bin/sleep 180
podman run --name bar --requires foo alpine:3 /bin/sleep 180
podman run --name foo --replace alpine:3 /bin/sleep 180
```

Foo would be seamlessly replaced. If bar has to be restarted to accomplish that would be acceptable to me too. So long as that can be done with a flag something like `--restart-deps`

**Comment by vrothberg** [comment] 2023-05-17 07:36
Ah, I thought that `--replace` would start removing dependent containers as well.  An in-place replacement while keeping dependencies sounds quite challenging and may even break the workloads.

@EvanCarroll, depending on your use case, did you consider moving the containers into a Pod?

**Comment by Luap99** [comment] 2023-05-17 08:21
> Ah, I thought that --replace would start removing dependent containers as well. An in-place replacement while keeping dependencies sounds quite challenging and may even break the workloads.

I agree enabling something like this is very tricky, we would need a way to atomically replace the container in the db otherwise we could corrupt the dependency chain. And then we still have the problem with running containers being in the wrong namespace.

Overall I think it is best to keep --replace as simple as possible. It should be treated as `podman rm <name> && podman run --name <name> ... `. If the new container specification is not valid the old container is removed but no new one created.

I changed it to a feature as I think the current behaviour is fine and not a bug.

**Comment by EvanCarroll** [comment] 2023-05-17 15:03
@vrothberg they're already in a pod. i'm developing mailman to launch with podman in a pod. i have a container in that pod called mailman-core which hosts the REST api. I need to update that with a new image, you can see it here. I'm testing a new image.

https://github.com/maxking/docker-mailman/pull/617/commits/82e6bc15bb6a7694b1c83b982d21ccd78fe2aa4f#diff-cf59feb0a11b2f24b23d39c055b50ef5bf0713b5abd0e9c2496548e55a8c7237R23

However, [mailman-web requires mailman-core](https://github.com/maxking/docker-mailman/pull/617/commits/82e6bc15bb6a7694b1c83b982d21ccd78fe2aa4f#diff-cf59feb0a11b2f24b23d39c055b50ef5bf0713b5abd0e9c2496548e55a8c7237R54) and because of this I can not run mailman-core on a new image without first removing mailman-web.

**Comment by EvanCarroll** [comment] 2023-05-23 13:17
@vrothberg Not yet on this project. But I have to support substantially older podman for the work I'm doing currently.

**Comment by EvanCarroll** [comment] 2023-06-23 05:05
The issue hasn't been solved.

**Comment by rhatdan** [comment] 2023-06-23 10:16
@mheon PTAL

**Comment by mheon** [comment] 2023-06-23 13:09
This definitely requires database work (we'd need a dedicated ReplaceContainer API or similar, to allow for a container to be updated to a new config without first removing and re-adding its dependencies).

**Comment by Luap99** [comment] 2023-06-23 13:27
Yes exactly this would need to be atomically. But I really see this as way to complicated/out of scope, we cannot make the dependency containers attach to the new namespace of the recreated container so this would break things until all dependencies containers are restarted.

I like to repeat myself:
Overall I think it is best to keep --replace as simple as possible. It should be treated as podman rm <name> && podman run --name <name> ... . If the new container specification is not valid the old container is removed but no new one created.

**Comment by rhatdan** [comment] 2023-06-23 13:33
Ok lets document that the --replace does not work with dependent containers and explain what the user needs to do.  I agree that this is getting real complicated for a corner case.

**Comment by EvanCarroll** [comment] 2023-06-28 06:31
I don't think there is anything wrong with removing and re-adding the dependencies. With something like `--restart-deps`, as mentioned earlier. I also don't think anything is wrong just adding a force flag and pretending like the dependency isn't there at all for the action. Just something that let's me develop that maintains the relationship that I'm deploying with.

**Comment by rhatdan** [comment] 2023-07-31 14:43
Feel free to open a PR to implement such a change.

**Comment by Luap99** [comment] 2024-04-04 11:10
I am going to close this as I do not think it is a good idea long term as the complexity is to high.

**Closed** 2024-06-15 19:08 UTC
Labels: kind/feature, jetsam
