### ISSUE TITLE
Cannot use podman auto-update against a container that was created through podman play kube

### ISSUE THREAD

**Issue by spirit-team** [containers/podman#14671] opened 2022-06-20 19:00 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Create a new Pod with at least 1 container configured to use auto-update and 1 container that doesnt use auto-update

2. podman generate systemd --files --name --new newapp

3. systemctl --user enable ....    (for all systemd files) 

4. Setup and Test auto-update feature

5. podman generate kube newapp > kube.yml

6. Modify image version for container that doesnt use auto-update in kube.yml

7. podman play kube --replace kube.yml

8. Need regenerate the systemd files using podman generate systemd --files --name podman_drpinfo    (cannot use --new on pod created from Kube file)

9. Restart containers using systemd files

10. podman auto-update 

**Describe the results you received:**

Error: registry auto-updating container "2508498e4eda910598580d2e0d93d4a095a34f0fed897081da32d5a7854f2f9a": raw-image name is empty

**Describe the results you expected:**
UNIT                    CONTAINER            IMAGE                                     POLICY      UPDATED
container-newapp.service  2508498e4eda  docker.io/newapp:dev  registry    false

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Apr 19 06:16:32 2022
OS/Arch:    linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 87b7a9037cbd1d81288bdf2d6705dfda889f7cf9'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: stha2n40220
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 1541792
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 7073
      size: 1
    - container_id: 1
      host_id: 1541792
      size: 65536
  kernel: 4.18.0-372.9.1.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 9830215680
  memTotal: 16595566592
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-2.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/7073/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.module+el8.6.0+14877+f643d2d6.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 12457074688
  swapTotal: 12457074688
  uptime: 137h 57m 20.55s (Approximately 5.71 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/istoolin/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/istoolin/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/user/7073/containers
  volumePath: /home/istoolin/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1650363392
  BuiltTime: Tue Apr 19 06:16:32 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**kube.yml**

```
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.0.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/proxy/nginx.reverseproxy.conf: Z
    bind-mount-options:/certs: Z
    bind-mount-options:/volumes/newapp: Z
    bind-mount-options:/volumes/mongodb/dump: Z
    io.containers.autoupdate.authfile/newapp: /run/user/7073/containers/auth.json
    io.containers.autoupdate/newapp: registry
  creationTimestamp: "2022-06-17T15:34:54Z"
  labels:
    app: podmannewapp
  name: podman_newapp
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: USER
      value: 7073:3661
    - name: NGINX_PORT
      value: "8080"
    image: docker.io/nginx:1.21.6
    name: nginx
    ports:
    - containerPort: 4443
      hostPort: 4443
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 27017
      hostPort: 27017
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /etc/nginx/certs/
      name: certs-host-0
    - mountPath: /etc/nginx/conf.d/default.conf
      name: apps-proxy-nginx.reverseproxy.conf-host-1
  - args:
    - mongod
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: MONGO_PWD
    image: docker.io/mongo:4.4.14
    name: mongodb
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /data/dump
      name: volumes-mongodb-dump-host-0
    - mountPath: /data/db
      name: volumes-newapp-host-1
    - mountPath: /data/configdb
      name: ad36729e8889a30f821720653d39be4134d731dc0821b5fd8e94d0768c589511-pvc
  - args:
    - node_modules/.bin/next
    - start
    env:
    - name: PORT
      value: "3000"
    - name: HOST
      value: APPNAME
    - name: NET
      value: '"HOST"'
    image: localhost/newapp:dev
    name: newapp
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    tty: true
  restartPolicy: Never
  volumes:
  - name: ad36729e8889a30f821720653d39be4134d731dc0821b5fd8e94d0768c589511-pvc
    persistentVolumeClaim:
      claimName: ad36729e8889a30f821720653d39be4134d731dc0821b5fd8e94d0768c589511
  - hostPath:
      path: /certs
      type: Directory
    name: certs-host-0
  - hostPath:
      path: /apps/proxy/nginx.reverseproxy.conf
      type: File
    name: apps-proxy-nginx.reverseproxy.conf-host-1
  - hostPath:
      path: /volumes/mongodb/dump
      type: Directory
    name: volumes-mongodb-dump-host-0
  - hostPath:
      path: /volumes/newapp
      type: Directory
    name: volumes-newapp-host-1
status: {}

``` 

Basicly the goal here was to have the auto-update feature be executed from a pipeline whenever a new image was built from our code because the image name and tag never change and to use the kube deployment feature to update nginx and mongodb when we are ready to, by updating the YML and running a pipeline

**Comment by cdoern** [comment] 2022-06-21 12:55
this might just need generate to set use the `WithRootFSFromImage` function. I will take a look at this,

**Comment by Luap99** [comment] 2022-06-21 13:02
Auto update is only supported with units generated with `--new`, so this will not even if this problem is fixed.

@vrothberg has done some improvements for systemd with play kube, maybe he can take a look when he is back.

**Comment by Luap99** [comment] 2022-06-21 14:32
Yes but as long as units are not created with `--new` auto-update will not work for them.

**Comment by rhatdan** [comment] 2022-06-27 12:47
Do we record the path to the YAML file somewhere.  Could we at least give the users some indicator on how to launch a YAML file with podman generate systemd ?

**Comment by vrothberg** [comment] 2022-06-27 12:50
> Do we record the path to the YAML file somewhere. Could we at least give the users some indicator on how to launch a YAML file with podman generate systemd ?

That's a different request.  I need to go back to the "play-kube in systemd" and write docs and a blog on it.

It remains unclear at the moment how auto-updates can be used in conjunction with play-kube-in-systemd

**Comment by cdoern** [comment] 2022-07-11 13:17
@vrothberg can we close this as it seems this is expected behavior or do you want to take it?

**Comment by vrothberg** [comment] 2022-07-11 14:43
I think we need to keep this open.  Auto updates still don't work with `play kube`.  But, we have the groundwork done with the systemd integration of play-kube.  What it will probably break down to is that entire service will be restarted if one container has a new image.

**Comment by rhatdan** [comment] 2022-09-04 10:22
@vrothberg this is moving forward correct?

**Comment by MartinX3** [comment] 2022-11-08 19:03
I can confirm that it is still broken in 4.3.0 with yaml pods created with the systemd service `podman-kube@`.

**Comment by vrothberg** [comment] 2022-11-09 08:46
Thanks for coming back to the issue.  I forgot to drop that this is actually working since Podman v4.3, see commit https://github.com/containers/podman/commit/274d34a25a3ed7b69a6e4caec07e845157048c96.

Please open a new issue if it does not work as expected.

**Closed by vrothberg** 2022-11-09 08:46 UTC
Labels: kind/feature, kube
