### ISSUE TITLE
Support `.subPath`  for host volumes as well

### ISSUE THREAD

**Issue by gsalvatella** [containers/podman#16838] opened 2022-12-14 18:03 UTC
While https://github.com/containers/podman/issues/12929 has added support for `VolumeMounts.subPath` in named volumes (thank you big time @cdoern !), the same is still needed for host volumes to complete the feature. Since I cannot reopen the issue, I'm opening a new one so it does not fall into oblivion.

**Comment by Luap99** [comment] 2022-12-15 15:00
Duplicate of #16828

**Closed by Luap99** 2022-12-15 15:00 UTC
