### ISSUE TITLE
podman + docker-compose: DNS does not resolve other containers

### ISSUE THREAD

**Issue by WhyNotHugo** [containers/podman#15848] opened 2022-09-17 23:46 UTC
/kind bug

**Description**

When using podman with docker-compose, containers don't resolve each others DNS name.

**Steps to reproduce the issue:**

1. Use this docker-compose file:

```yaml
services:
  postgres:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_PASSWORD: password
  another:
    image: alpine
    command: "sh -c 'apk add netcat-openbsd && nc postgres 5432'"
```

2. Run `docker-compose up postgres`.

3. Run` docker-compose up another` in a separate terminal.

**Describe the results you received:**

    nc: getaddrinfo: Name does not resolve

**Describe the results you expected:**

DNS should resolve and this should work.

**Additional information you deem important (e.g. issue happens only occasionally):**

- I'm using rootless containers.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.19
Git Commit:   62b324ddf718411b1d4d0ba8117c632f7f984a38-dirty
Built:        Thu Sep  8 08:52:54 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.4-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: bd1459a3ffbb13eb552cc9af213e1f56f31ba2ee'
  cpuUtilization:
    idlePercent: 97.22
    systemPercent: 0.84
    userPercent: 1.94
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: victory
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65537
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65537
  kernel: 5.19.9-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 626294784
  memTotal: 16460664832
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.6-1
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 31368552448
  swapTotal: 34343288832
  uptime: 38h 43m 33.00s (Approximately 1.58 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/hugo/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/hugo/.local/share/containers/storage
  graphRootAllocated: 972831813632
  graphRootUsed: 859737743360
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 9
  runRoot: /run/user/1000/containers
  volumePath: /home/hugo/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 1662619974
  BuiltTime: Thu Sep  8 08:52:54 2022
  GitCommit: 62b324ddf718411b1d4d0ba8117c632f7f984a38-dirty
  GoVersion: go1.19
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Installed [arch] packages:

```
podman 4.2.1-1
podman-dnsname 1.3.1-2
podman-docker 4.2.1-1
cni-plugins 1.1.1-2
slirp4netns 1.2.0-1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, and I also checked https://wiki.archlinux.org/title/Podman#Troubleshooting

**Additional environment details (AWS, VirtualBox, physical, etc.):**

    export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"

**Comment by fabian-marquardt** [comment] 2022-09-19 12:53
I recently had the same issue, and after some confusion I found the root cause of the problem when I manually tried to attach a container to the network:
```
WARN[0000] aardvark-dns binary not found, container dns will not be enabled
```
The problem was that Arch Linux/Manjaro does not have a forced dependency to install the `aardvark-dns` package if you install podman. Manually executing `sudo pacman -S aardvark-dns` fixed the problem for me.

**Comment by rhatdan** [comment] 2022-10-27 11:43
@Luap99 @mheon @flouthoc Is this a packaging issue or a real bug?  Can we close this issue?

**Comment by mheon** [comment] 2022-10-27 12:21
Seemingly a packaging issue, yes. Make sure aardvark-dns is installed, and DNS should work. If there is a similar bug where aardvark *is* installed, please open a fresh issue.

**Closed by mheon** 2022-10-27 12:21 UTC
Labels: kind/bug

**Comment by cdpb** [comment] 2022-10-28 21:39
I have the same problem as OP. I checked my logs, no missing aardvark-dns is thrown.
aardvark-dns is installed.
podman version 4.2.1

on Fedora 36 Desktop, bare metal.

**Comment by mheon** [comment] 2022-10-29 02:29
As said earlier, please open a fresh issue and complete the full issue template
