### ISSUE TITLE
Incorrect download link on podman.io for Windows

### ISSUE THREAD

**Issue by m-czernek** [containers/podman#13947] opened 2022-04-21 09:17 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When visiting https://podman.io/getting-started/installation#windows, the latest remote client link points to https://github.com/containers/podman/releases/latest/download/podman-remote-release-windows_amd64.zip

However, the latest releases in https://github.com/containers/podman/releases/ are CVEs that do not contain any windows release.
This means Windows users might be under the impression that you cannot install podman on Windows, since the link 404s.

**Steps to reproduce the issue:**

1. Visit https://podman.io/getting-started/installation#windows

2. Try downloading the "latest remote client" 

**Describe the results you received:**

File not found

**Describe the results you expected:**

File is downloaded

**Comment by Luap99** [comment] 2022-04-21 09:34
Oh good, github for some reason always uses the date to check what the latest release is instead of semver. So all latest links are redirected to v3.4.7 currently. This is very bad since we use the latest link in several places.

Even worse there is no way to manually overwrite the latest release in github, according to https://stackoverflow.com/questions/22822586/swap-latest-release-on-github you need to change your commit date on the tag which sounds like a bad idea to me.


@mheon @containers/podman-maintainers PTAL

**Comment by mheon** [comment] 2022-04-21 15:08
Well damn.

We can't actually alter tags once they're created because they are signed. Our only potential option would be to tag a new release from the latest release branch?

**Comment by Luap99** [comment] 2022-04-21 15:14
I don't think this is the solution. It will happen again every time we have to do a release from an old branch.
I wonder if it would make more sense to hardcode the links to the actual latest version and have a script which can update it for each new release with some form of CI check to ensure it is up to date.

**Comment by mheon** [comment] 2022-04-21 15:17
I'm fine with that, as it shifts the solution away from me and to other folks :smile: 

Given this - should we move the issue to the podman.io repo?

**Comment by Luap99** [comment] 2022-04-21 15:18
No this also applies to podman, for example the link in our Readme also points to latest

**Comment by mheon** [comment] 2022-04-21 15:20
Naturally, because nothing can ever be simple.

That can probably be done manually as part of the release process. Podman.io seems scriptable, though.

**Comment by Luap99** [comment] 2022-04-21 15:22
Manually == it will be forgotten, as least that is my experience.

**Comment by mheon** [comment] 2022-04-21 15:25
Fair. I wonder if we could GH actions this - on new tag, check semantic version versus readme latest, update if newer?

**Comment by Luap99** [comment] 2022-04-22 08:56
`git ls-remote --tags --refs --sort="v:refname" https://github.com/containers/podman.git | sed 's/.*\///' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | tail -n1`
This command should be able to get the latest version from anywhere.

**Comment by rhatdan** [comment] 2022-04-23 10:33
The link is now fixed. We can carry on the conversation here on how to make this human proof.

**Closed by rhatdan** 2022-04-23 10:33 UTC
Labels: kind/bug, documentation

**Comment by edsantiago** [comment] 2022-11-10 14:56
Hi! This has been on my backburner for months. I have a script intended to take care of this, and as of a few minutes ago I confirmed that it handles the v4.3.0 -> .1 transition. However: there is no "msi" for v4.3.0. How do msi files get created? Is that a manual process? Will there be one for v4.3.1? My script fails if it doesn't find the corresponding msi file.

**Comment by edsantiago** [comment] 2022-11-10 15:03
Oh I don't care! I've never used Windows and am unlikely ever to. I just want our documentation and links to be accurate.

**Comment by Luap99** [comment] 2022-11-10 15:08
The windows install section on podman.io no longer directly links to the binaries, just to the tutorial which links to the the github release page so this is not really a problem any more.

**Comment by edsantiago** [comment] 2022-11-10 15:13
Uh, well, except that the tutorials say:
> The Windows installer file is named `podman-v.#.#.#.msi`, where the `#` symbols represent the version number of Podman

And one of them also says:
>At the time of this writing, the file name is `podman-v3.4.4.msi`   <---- just dead text, not a hyperlink

I find that offensive.

It's very easy (in fact, it's done except for review and merge) to automate this, add a link of the form:
```markdown
As of YYYY-MM-DD the latest version is [vX.Y.Z](https://link/to/that/exe-or-msi-or-whatever)
```

So: (1) should I fix the tutorials to say "exe" instead of "msi"? And (2) should I continue with this work?

**Comment by mheon** [comment] 2022-11-10 15:15
RE 1, definitely - the MSI is now legacy.

RE 2, IMO we could just as easily point to the Github releases page and say grab the link from the latest release... But that's also not perfect (releases are chronological, so if we were to do a 3.4.8 right now it would show as latest until we cut 4.3.2), so I won't object to doing this the right way.
