### ISSUE TITLE
podman-restart.service Does Not Restart "unless-stopped" Containers

### ISSUE THREAD

**Issue by arazilsongweaver** [containers/podman#17851] opened 2023-03-19 19:24 UTC
### Issue Description

The podman-restart.service daemon only restarts services that are in an "always" restart state. This is inconsistent with the behavior of Docker which will restart all running "unless-stopped" containers after a system-wide restart.

### Steps to reproduce the issue

1. Use docker-compose (or similar tool) to start a few containers with "restart: unless-stopped" configuration.
2. Reboot the system with the podman-restart.service daemon enabled.

### Describe the results you received

All containers with the "unless-stopped" configuration are not restarted by podman-restart.service.

### Describe the results you expected

All running containers with a "unless-stopped" configuration get restarted by podman-restart.service upon system boot.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 56561007b6a59ea175ee9a67384639721499e160'
  cpuUtilization:
    idlePercent: 95.37
    systemPercent: 1.34
    userPercent: 3.29
  cpus: 6
  distribution:
    distribution: '"rhel"'
    version: "9.1"
  eventLogger: journald
  hostname: [hostname]
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-162.18.1.el9_1.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 5564882944
  memTotal: 16726843392
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 8588881920
  swapTotal: 8588881920
  uptime: 0h 19m 10.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 37
    paused: 0
    running: 36
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 265084731392
  graphRootUsed: 19616268288
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 30
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1675767401
  BuiltTime: Tue Feb  7 04:56:41 2023
  GitCommit: ""
  GoVersion: go1.18.9
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

RHEL 9.1 running on Proxmox 7.3-6

### Additional information

Containers were created using docker-compose 2.16.0. Docker's restart policy documentation is available at: https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by JCBird1012** [comment] 2023-03-23 22:53
This is a duplicate of #17580.

**Comment by rhatdan** [comment] 2023-03-25 11:29
Looks like this is fixed in the main branch. And will be delivered in podman 4.4 (RHEL9.2)

**Closed by rhatdan** 2023-03-25 11:29 UTC
Labels: kind/bug
