### ISSUE TITLE
run with `--arch` or `--platform` do not search local images unless some `unqualified-search-registries` is set

### ISSUE THREAD

**Issue by martinetd** [containers/podman#12707] opened 2021-12-27 06:23 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to run a local image with its short name works iff some unqualified-search-registries is set in the config.

**Steps to reproduce the issue:**

1. setup qemu user emulation (here at least aarch64) + `podman pull docker.io/arm64v8/alpine && podman image tag docker.io/arm64v8/alpine test`

2. `CONTAINERS_REGISTRIES_CONF=/dev/null podman run --rm  --platform linux/aarch64 test uname -m` -> fails with `Error: short-name "test" did not resolve to an alias and no unqualified-search registries are defined in "/dev/null"`

3. `echo 'unqualified-search-registries = ["docker.io"]' > test-registries.conf; CONTAINERS_REGISTRIES_CONF=$PWD/test-registries.conf podman run --rm  --platform linux/aarch64 test uname -m` -> works, prints `aarch64` as expected

**Describe the results you received:**

image was not found.

**Describe the results you expected:**

My understanding is that since `localhost/` is automatically prepended, it should also always be searched and image should be found - it should not depend on having something in unqualified-search-registries

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.4
Git Commit:   72df58eb05290e506c96069e0c5c8d0afab3041f
Built:        Sat Dec 11 22:04:57 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: 2182230f3227b0b417fd6c5c62ea2b9c714a9b1e-dirty'
  cpus: 4
  distribution:
    distribution: alpine
    version: 3.15.0
  eventLogger: file
  hostname: alpine
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.11-0-virt
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 549425152
  memTotal: 1030807552
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 268431360
  swapTotal: 268431360
  uptime: 6h 1m 16.73s (Approximately 0.25 days)
plugins:
  log:
  - k8s-file
  - none
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 0
    stopped: 6
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 5
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1639227897
  BuiltTime: Sat Dec 11 22:04:57 2021
  GitCommit: 72df58eb05290e506c96069e0c5c8d0afab3041f
  GoVersion: go1.17.4
  OsArch: linux/amd64
  Version: 3.4.4

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes and yes, also tried master branch from a couple of weeks ago (91ef5fb85e29b70c4b0f6c0fadadce37474b5dc0)

**Comment by mheon** [comment] 2022-01-05 21:43
@vrothberg PTAL

**Comment by vrothberg** [comment] 2022-01-10 10:20
Thanks for reaching out and for providing the reproducer.  I agree with your assessment that this should work and will provide a fix shortly.

**Comment by vrothberg** [comment] 2022-01-10 14:58
Opened a fix here: https://github.com/containers/common/pull/880

**Comment by rhatdan** [comment] 2022-01-10 19:13
Since this got merged into common and common got merged here, I am closing.

**Closed by rhatdan** 2022-01-10 19:13 UTC
Labels: kind/bug

**Comment by vrothberg** [comment] 2022-01-10 19:16
Thanks, @rhatdan !

**Comment by martinetd** [comment] 2022-01-11 00:04
@vrothberg thanks!
I'm not sure the fix works for the example I described however -- if it was a pull problem, having a search registry would make no difference as the image doesn't exist on the registry anyway? I think it's stuck in another part that disable inexact match depending on the unqualified-search-registries setting.

I've just recompiled the tip of main branch right now and can still reproduce:
```
$ ./podman pull docker.io/arm64v8/alpine && ./podman image tag docker.io/arm64v8/alpine test
Trying to pull docker.io/arm64v8/alpine:latest...
Getting image source signatures
Copying blob 9b3977197b4f skipped: already exists  
Copying config 8e1d7573f4 done  
Writing manifest to image destination
Storing signatures
8e1d7573f448dc8d0ca13293b1768959a2528ff04be704f1f3d35fd3dbf6da3d

$ echo 'unqualified-search-registries = ["docker.io"]' > test-registries.conf; CONTAINERS_REGISTRIES_CONF=$PWD/test-registries.conf podman run --rm --platform linux/aarch64 test uname -m
aarch64

$ CONTAINERS_REGISTRIES_CONF=/dev/null ./podman run --rm --platform linux/aarch64 test uname -m
Error: short-name "test" did not resolve to an alias and no unqualified-search registries are defined in "/dev/null"

$ ./podman info | grep -i GitCommit
  GitCommit: ed9ef59e7ea439b670875863132b68fd094501c7

$ git log --oneline -1
ed9ef59e7ea4 (HEAD, origin/main) Merge pull request #12780 from rhatdan/pod
```

Would you be able to confirm that works for you?

(timezone differences make this a bit annoying as I'm usually asleep while you're at work, but hopefully we can get this right :))

**Comment by vrothberg** [comment] 2022-01-11 08:02
Thanks for coming back, @martinetd!

The fixes for this specific issue are not yet vendored into Podman it seems. Try the following to reproduce:
* `go get github.com/containers/common@main`
* `make vendor; make podman`
* Re-run reproducer

It will work now. The fix for the issue was to massage the pull-policy enforcement. Previously, the policy was enforced to _always_ in the presence of a custom platform to pull. Now the policy is enforced to _newer_ which has a slightly different behavior in that it attempts to pull a "newer" image (i.e., one with a different digest) but errors during pull are non-fatal. This way, the local image will be returned and the error from the registries is non-fatal.

**Comment by martinetd** [comment] 2022-01-11 08:08
It looks like I had misunderstood @rhatdan 's "common got merged here" as vendoring in podman, doing it manually works :) (I'm in no particular hurry so that'll get done when it gets done, no worry, was just a misunderstanding)

Thanks for the fix and the explanation!
