### ISSUE TITLE
play kube: invalid character 'N' looking for beginning of value

### ISSUE THREAD

**Issue by 1player** [containers/podman#15071] opened 2022-07-26 11:12 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`play kube` error in latest HEAD

**Steps to reproduce the issue:**

```
cat <<EOF >manifest.yml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
EOF
```

1. `podman play kube ./manifest.yml`

**Describe the results you received:**

```
Error: ./manifest.yml: invalid character 'N' looking for beginning of value
```

**Additional information you deem important (e.g. issue happens only occasionally):**

On stable version (tested tag `v4.1.1`) I get this error instead: 

```
Error: ./manifest.yml: error playing YAML file: short-name resolution enforced but cannot prompt without a TTY
```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0-dev
API Version:  4.2.0-dev
Go Version:   go1.18.4
Git Commit:   a298909decc9091da8cc134e6eb2f38a70635a30
Built:        Tue Jul 26 12:08:11 2022
OS/Arch:      linux/amd64

Server:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 22 17:17:44 2022
OS/Arch:      linux/amd64
```

**Comment by zhangguanzhang** [comment] 2022-07-26 11:22
```
cat -A manifest.yml
```

**Comment by 1player** [comment] 2022-07-26 11:25
```
apiVersion: v1$
kind: Pod$
metadata:$
  name: nginx$
spec:$
  containers:$
  - name: nginx$
    image: nginx:1.14.2$
    ports:$
    - containerPort: 80$
```

**Comment by vrothberg** [comment] 2022-07-26 11:34
I can reproduce.

**Comment by vrothberg** [comment] 2022-07-26 11:36
The issue occurs when a new client talks to an older server.  I think I know what's going on.

@nicrowe00, I fear we need to let the remote client to use the `play/kube` endpoint.  Otherwise, we run into this issue.  Would you open a PR to fix it?

**Comment by vrothberg** [comment] 2022-07-26 11:36
Nice catch, @1player! Thanks for the report.

**Comment by nicrowe00** [comment] 2022-07-26 12:03
@vrothberg Will do.

**Comment by vrothberg** [comment] 2022-07-26 12:05
Thanks, @nicrowe00!

**Comment by vrothberg** [comment] 2022-07-27 09:40
@mheon @jwhonce @Luap99 how have we historically dealt with such issues.  Assuming we add an entirely new command, how do newer clients negotiate with older server of the same major version, for instance, a v4.2 client with a v4.1 server?

Did we just hope for the best?

**Comment by vrothberg** [comment] 2022-07-27 09:41
Just to make sure I don't ask @nicrowe00 to do some Yoga we usually did not do.

**Comment by Luap99** [comment] 2022-07-27 11:06
Yes, the client should use the old endpoint for backwards compat. Although I am confused about the current error message I would expect a 404 not found when calling non exiting endpoints.
Alternatively you could make a version check in the bindings but since this is the same endpoint just with different paths there is really no reason to do so.

**Comment by vrothberg** [comment] 2022-08-02 08:57
Fixed by https://github.com/containers/podman/pull/15119

**Closed by vrothberg** 2022-08-02 08:57 UTC
Labels: kind/bug
