### ISSUE TITLE
podman login leaves password in clear

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#4119] opened 2019-09-26 17:03 UTC
I just used the most recent Docker for the first time in a long time and when doing `docker login` I get:

```
# docker login quay.io
Username: tomsweeneyredhat
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

In the most up to date podman, 1.6-dev we don't do a similar warning for `podman login` and probably should.  We'll also need to make sure `podman login` works with a credential helper too.  Probably the same story in `buildah login` too.

**Comment by TomSweeneyRedHat** [comment] 2019-09-26 17:03
@QiWang19 PTAL

**Comment by QiWang19** [comment] 2019-09-26 19:51
support the `"credsStore"` has been working on https://github.com/containers/image/pull/656

c/image and podman already support `"credHelpers"`, but only works for config in `/run/user/0/auth.json`  and `sudo podman login`

 with config in `/run/user/1000/auth.json` and podman login got error

```
{
        "credHelpers": {
                "docker.io": "secretservice"
        }
}

Error: error reading auth file: error getting credentials - err: exit status 1, out: `Exhausted all available authentication mechanisms (tried: EXTERNAL) (available: EXTERNAL)`
```
I think this should be fixed before podman login return `credentials-store WARNING`.....
#4123

**Comment by vrothberg** [comment] 2019-10-30 08:46
Throwing a warning can be done independently of the ongoing work for credStores but it must be done in c/image. @TomSweeneyRedHat, are you interested in opening a PR for c/image? I guess we could do a `fmt.Fprintf(os.Stderr, "$WARNING")` when using an authfile while storing credentials.

**Comment by TomSweeneyRedHat** [comment] 2019-10-30 11:36
I'll work with @QiWang19 to make this happen

**Comment by rhatdan** [comment] 2020-02-17 20:09
@QiWang19 @TomSweeneyRedHat What should we do with this one?

**Comment by TomSweeneyRedHat** [comment] 2020-02-17 22:49
We should keep it.  It got lost in the weeds, but is needed.

**Comment by rhatdan** [comment] 2020-06-09 16:49
@QiWang19 Could you look into fixing this and adding the warning?

**Comment by QiWang19** [comment] 2020-06-16 16:56
Will fix on adding the warning after the credential helper can be used as default.

> @QiWang19 Could you look into fixing this and adding the warning?

**Comment by rugk** [comment] 2020-08-07 17:04
Accidentally opened https://github.com/containers/podman/issues/7254 as a duplicate.
So I'd very much like to see libsecret support, at least, so passwords are saved in the credential store on Linux desktops.

**Comment by rhatdan** [comment] 2020-09-11 11:25
@QiWang19 What is the latest on this?

**Comment by rhatdan** [comment] 2020-12-24 12:42
@QiWang19 Any progress?

**Comment by QiWang19** [comment] 2021-01-04 19:21
If https://github.com/containers/image/pull/971could finally merged, this can be issue closed by using credential helpers. But I haven't been working on this for a while. And I have no idea why the upstream fix https://github.com/docker/docker-credential-helpers/pull/191 failed the CI.

**Comment by vrothberg** [comment] 2021-05-04 11:27
What is the scope of the issue?  I think there is a number of mentioned topics which makes it hard to know when can close.  Is it credhelpers, is it a warning?

Throwing a warning for the _default_ setup may raise the question why it is the default.

**Comment by rhatdan** [comment] 2021-05-04 19:13
Once we have changed the credhelper to something other the auth.json file, we can close this.  For rootless users we should default to gnome-secrets.

**Comment by rugk** [comment] 2021-05-04 20:29
> For rootless users we should default to gnome-secrets.

Yes! Respectively to [some XDG standard](https://unix.stackexchange.com/q/457799/146739) of that… 

E.g. this [`libsecret` thing git uses](https://discussion.fedoraproject.org/t/attention-git-credential-libsecret-for-storing-git-passwords-in-the-gnome-keyring-is-now-an-extra-package/18275?u=rugk)…

**Comment by rhatdan** [comment] 2021-05-04 21:13
Yes that looks perfect.

**Comment by rugk** [comment] 2021-08-11 18:14
shh #badbot :no_bell::robot::no_bell:

…that does still not mean the issue is magically solved.

**Comment by rhatdan** [comment] 2021-08-11 20:17
@cdoern PTAL

**Comment by TomSweeneyRedHat** [comment] 2021-08-13 22:10
Just noting that https://github.com/containers/image/pull/1193 supplied the credential helpers bit of this along with this issue: https://github.com/containers/podman/issues/4123

**Comment by umohnani8** [comment] 2021-09-29 20:36
This looks like it might be done based on @TomSweeneyRedHat's comment above. Is there anything else left to do here @rhatdan @vrothberg @QiWang19?

**Comment by rhatdan** [comment] 2021-09-29 21:28
Yes I believe this is complete.  Reopen if I am mistaken.

**Closed by rhatdan** 2021-09-29 21:28 UTC
Labels: kind/bug
