### ISSUE TITLE
`image is in use` on `podman system reset`

### ISSUE THREAD

**Issue by jpalus** [containers/podman#20856] opened 2023-11-30 17:41 UTC
### Issue Description

`podman 4.8.0` with sqlite database backend (affected by #20809) failed on `system reset` with:
```
ERRO[0014] image used by 929b991f97c04ce7d5a203abb206626c2285e63fe45e9b690a44fce236006417: image is in use by a container: consider listing external containers and force-removing image 
```

Three different containers based on three different images were running at the time.

### Steps to reproduce the issue

Note that issue seems to be racey and there are no steps to reproduce that would always work. In my case it was:
1. Create 3 (running) containers
2. Perform `podman system reset`

### Describe the results you received

Error occurred.

### Describe the results you expected

No Error.

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.33.2
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: 9aa8067313b1282097df84ab1a218149999397e4'
  cpuUtilization:
    idlePercent: 98.59
    systemPercent: 1.11
    userPercent: 0.3
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: pld
    version: "3.0"
  eventLogger: journald
  freeLocks: 2048
  hostname: rock
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.110-8-rockchip
  linkmode: dynamic
  logDriver: journald
  memFree: 11045920768
  memTotal: 16487534592
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.9.0
    package: Unknown
    path: /usr/libexec/podman/netavark
    version: netavark 1.9.0
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 1.12
      commit: ce429cb2e277d001c2179df1ac66a470f00802ae
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: false
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 8144547840
  swapTotal: 8242851840
  uptime: 1337h 37m 14.00s (Approximately 55.71 days)
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/users/jan/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /mnt/build-storage/jan/containers
  graphRootAllocated: 274877906944
  graphRootUsed: 1612390400
  graphStatus:
    Build Version: Btrfs v6.6.2
    Library Version: "102"
  imageCopyTmpDir: /home/users/jan/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /mnt/build-storage/jan/containers/volumes
version:
  APIVersion: 4.8.0
  Built: 1701166825
  BuiltTime: Tue Nov 28 11:20:25 2023
  GitCommit: bf038720ca8b9301a3aa80966759567c41199dd0
  GoVersion: go1.21.4
  Os: linux
  OsArch: linux/arm64
  Version: 4.8.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by Luap99** [comment] 2023-11-30 17:55
If you try to reproduce please add `--log-level=debug` to the command, that should give some insight.

**Comment by baude** [comment] 2023-11-30 21:19
also, if you can reproduce, more information about the exact reproducer would be great ... like ... are all the running continers using the same image or ?

**Comment by jpalus** [comment] 2023-12-01 00:02
Doing my best with reproduction attempt but this one is tough. Although I did get a database locked that was logged only with debug level:
```
DEBU[0007] Removing all exec sessions for container 9d731e64218818614e7c47a83327e6c241947b3a4b361b5b274c2d037e5c7f8b 
DEBU[0007] Container 9d731e64218818614e7c47a83327e6c241947b3a4b361b5b274c2d037e5c7f8b storage is already unmounted, skipping... 
DEBU[0008] Container "1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72" state changed from "stopping" to "stopped" while waiting for it to be stopped: discontinuing stop procedure as another process interfered 
DEBU[0008] Cleaning up container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72 
DEBU[0008] Tearing down network namespace at /run/user/1000/netns/netns-015c455e-e875-5e88-f339-f40cd679d0f8 for container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72 
DEBU[0009] Successfully cleaned up container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72 
DEBU[0010] Container "3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97" state changed from "stopping" to "stopped" while waiting for it to be stopped: discontinuing stop procedure as another process interfered 
DEBU[0010] Cleaning up container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97 
DEBU[0010] Tearing down network namespace at /run/user/1000/netns/netns-17edb1cf-3973-5987-baec-727ea20cf537 for container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97 
DEBU[0011] Successfully cleaned up container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97 
DEBU[0192] Unmounted container "1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72" 
DEBU[0192] Unmounted container "3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97" 
DEBU[0197] Removing all exec sessions for container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97 
DEBU[0197] Container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97 storage is already unmounted, skipping... 
DEBU[0197] [graphdriver] trying provided driver "btrfs" 
DEBU[0197] Removing all exec sessions for container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72 
DEBU[0198] Container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72 storage is already unmounted, skipping... 
DEBU[0210] Failed to remove container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97: cleaning up container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97: unmounting container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97 storage: unmounting container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97: saving container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97 state: beginning container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97 save transaction: database is locked 
DEBU[0225] Failed to remove container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72: cleaning up container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72: unmounting container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72 storage: unmounting container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72: saving container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72 state: beginning container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72 save transaction: database is locked 
DEBU[0225] Multiple results for container 3630b4e970215bc293a16db76ddec4afe32fa788cbcb8c704608d1d52fa6ad97 - attempted multiple removals? 
DEBU[0225] Multiple results for container 1599acdbb0de935cd00ad69312ba90cc0ef77ebf6140a07aed283f5f659a9e72 - attempted multiple removals? 
DEBU[0225] Multiple results for container 9d731e64218818614e7c47a83327e6c241947b3a4b361b5b274c2d037e5c7f8b - attempted multiple removals?
```
didn't result in `image is in use` though.

> are all the running continers using the same image or ?

this one time that it happened each of 3 containers was based on independent image without any common layers.

**Comment by jpalus** [comment] 2023-12-01 01:05
Got another error instance with debug logging enabled. Same situation as before -- 3 running containers based on 3 independent images (full log: [system-reset-debug.txt](https://github.com/containers/podman/files/13519334/system-reset-debug.txt)):

```console
ERRO[0013] image used by 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562: image is in use by a container: consider listing external containers and force-removing image
```

With the culprit likely being:

```console
DEBU[0009] Failed to remove container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562: cannot remove container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 as it could not be stopped: unmarshalling container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 state JSON: readObjectStart: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...
```

The error is interesting in two ways:
1. It's actually the only container out of 3 that didn't get `database locked` during setup.
2. Follow up `podman system reset` does not see any problem:
```console
DEBU[0001] Starting parallel job on container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 
DEBU[0001] Removing container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 
DEBU[0001] Cleaning up container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 
DEBU[0001] Tearing down network namespace at /run/user/1000/netns/netns-dfcd647f-2307-0db1-2b94-f1a1cf81a2ab for container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 
ERRO[0001] Unable to clean up network for container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562: "unmounting network namespace for container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562: failed to unmount NS: at /run/user/1000/netns/netns-dfcd647f-2307-0db1-2b94-f1a1cf81a2ab: invalid argument" 
DEBU[0002] Successfully cleaned up container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 
DEBU[0002] Container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 failed to unmount /mnt/build-storage/jan/containers/btrfs-containers/111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562/userdata/shm : invalid argument 
DEBU[0002] Unmounted container "111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562" 
DEBU[0002] Removing all exec sessions for container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 
DEBU[0003] Container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 storage is already unmounted, skipping... 
DEBU[0005] Multiple results for container 111c8776b2ad752b724a7fc3a559b14ee5df9702f23b0577ec73db537cbb9562 - attempted multiple removals? 
DEBU[0005] Using conmon: "/usr/bin/conmon"              
INFO[0005] Using sqlite as database backend             
DEBU[0005] Using graph driver btrfs                     
DEBU[0005] Using graph root /mnt/build-storage/jan/containers 
DEBU[0005] Using run root /run/user/1000/containers     
DEBU[0005] Using static dir /mnt/build-storage/jan/containers/libpod 
DEBU[0005] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0005] Using volume path /mnt/build-storage/jan/containers/volumes 
DEBU[0005] Using transient store: false                 
DEBU[0005] Initializing event backend journald          
DEBU[0005] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0005] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0005] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument 
DEBU[0005] Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument 
DEBU[0005] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0005] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0005] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument 
DEBU[0005] Using OCI runtime "/usr/bin/crun"            
DEBU[0005] Removing image 5fc6b74e0da894b4b3703bfcd6286d76ed6f3b7dee4344868a81f79d12c2801c 
DEBU[0005] [graphdriver] trying provided driver "btrfs" 
DEBU[0005] parsed reference into "[btrfs@/mnt/build-storage/jan/containers+/run/user/1000/containers]@5fc6b74e0da894b4b3703bfcd6286d76ed6f3b7dee4344868a81f79d12c2801c" 
DEBU[0005] exporting opaque data as blob "sha256:5fc6b74e0da894b4b3703bfcd6286d76ed6f3b7dee4344868a81f79d12c2801c" 
DEBU[0005] exporting opaque data as blob "sha256:5fc6b74e0da894b4b3703bfcd6286d76ed6f3b7dee4344868a81f79d12c2801c" 
DEBU[0005] Successfully loaded 1 networks
```

**Comment by jpalus** [comment] 2023-12-15 13:07
Similar issue just reoccurred but:
- x86_64
- kernel 6.6.6
- podman 4.8.1
- boltdb
- conmon 2.1.8

I know the command has invalid argument placement but it didn'tfail on wrong executable but instead with:
```
$ podman run --rm -i -t docker.io/alpine --arch i386 bash
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob 661ff4d9561e done   | 
Copying config f8c20f8bbc done   | 
Writing manifest to image destination
Error: container create failed (no logs from conmon): conmon bytes "": readObjectStart: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...
```

**Comment by romanlytovchenko** [comment] 2023-12-26 20:18
maybe you faced an external containers?
`podman ps -a --external`

**Comment by giuseppe** [comment] 2024-01-17 09:49
closing the issue since https://github.com/containers/podman/pull/21226 was merged

**Closed by giuseppe** 2024-01-17 09:49 UTC
Labels: kind/bug
