### ISSUE TITLE
--name is updating /etc/hosts on container with name &  IP address Why?

### ISSUE THREAD

**Issue by jbhrfx9280** [containers/podman#16108] opened 2022-10-10 17:31 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug
bug

/kind feature
bug

**Description**
When using podman run with the --name option it updates the /etc/host file in the container with name and container ip.

**Steps to reproduce the issue:**

1.REHL 9 / Rocky 9 Linux stand alone server

2.PODMAN 4.1.1 installed
podman network create django-net
pull down image   "docker.io/library/mariadb"
podman volume create django-db

3.
podman run -d \
--env MYSQL_DATABASE=django_db \
--env MYSQL_USER=django_user \
--env MYSQL_PASSWORD=####### \
--env MYSQL_ROOT_PASSWORD=####### \
--volume django-db:/var/lib/mysql \
--network django-net \
--ip=10.89.1.5 \
--publish 127.0.0.1:3306:3306/tcp \
--hostname=mariadb_node1 \
--add-host=mariadb_node1:10.89.1.5 \
--add-host=mariadb_node2:10.89.1.10 \
--restart on-failure \
--name django-db_1 docker.io/library/mariadb

**Describe the results you received:**
Podman creates and run's the container just fine.  Except for /etc/hosts entry with --name and IP. Do the following.
Now log into container
podman exec -it container ID /bin/bash
once inside the container:
cat /etc/hosts
10.89.1.5       mariadb_node1
10.89.1.10      mariadb_node2
127.0.0.1       localhost localhost.localdomain localhost4 localhost4.localdomain4 example.com example.net
::1     localhost localhost.localdomain localhost6 localhost6.localdomain6 example.com example.net
10.89.1.1       host.containers.internal
10.89.1.5       django-db_1

**Describe the results you expected:**
Why is it adding the --name django-db_1 option into the hosts file with IP address ? This should not happen. It should not be adding 10.89.1.5       django-db_1 to /etc/hosts file.

I only have 2 directives for this. These 2 are supposed to add the entries to hosts file and it does.
--add-host=mariadb_node1:10.89.1.5 \
--add-host=mariadb_node2:10.89.1.10 \

If you look at podmans help --name is NOT supposed to do this.
**Additional information you deem important (e.g. issue happens only occasionally):**
Happens everytime.

**Output of `podman version`:**
4.1.1
```
(paste your output here)
podman version 4.1.1

**Output of `podman info`:**

```
(paste your output here)
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.2-2.el9_0.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: c22a156d8b67bfc2959fafd1ae718134423045ab'
  cpuUtilization:
    idlePercent: 99.91
    systemPercent: 0.03
    userPercent: 0.05
  cpus: 8
  distribution:
    distribution: '"rocky"'
    version: "9.0"
  eventLogger: journald
  hostname: dpai16r9.001
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-70.26.1.el9_0.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 31568904192
  memTotal: 33152749568
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-2.el9_0.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 8321495040
  swapTotal: 8321495040
  uptime: 1h 36m 11.4s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 2
    stopped: 5
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 75125227520
  graphRootUsed: 11795226624
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1660063436
  BuiltTime: Tue Aug  9 12:43:56 2022
  GitCommit: ""
  GoVersion: go1.17.12
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by mheon** [comment] 2022-10-10 17:35
Why is this a problem? Adding the container's name to /etc/hosts for easy resolution without hitting the DNS server seems like a positive for usability.

**Comment by jbhrfx9280** [comment] 2022-10-10 18:12
What? the --name directive is not supposed to do this anyways.
The --add-host is for this.
Ok 1st of all /etc/hosts file is the last name in DNS resolution unless
stack order is changed (/etc/nsswitch.conf). If you make an entry into
/etc/hosts file with an ip address and a host name on another line use the
same IP address and a different host name it will only use the last entry.
i.e.:
10.89.1.5   some host name
10.89.1.5   another host name

with the example above the 2nd entry will override the first entry. Try it.
Also your podman help does not say this will happen. For me to make this
work I have to edit the /etc/hosts file. With this container only having
MariaDB there is no text editor like VI, VIM or nano installed. You cannot
install it because there is no systemd as well. Would be bad practice to
enable systemd anyways. I have to copy a prepared hosts file on my host
server and copy it into the container using :
podman container cp hosts container ID:/etc/hosts.
This would be stupid. --name directive seems to have a bug.
Please advise...
Thank you
John

**Comment by Luap99** [comment] 2022-10-10 18:30
This is the expect behaviour and not a bug.

> Ok 1st of all /etc/hosts file is the last name in DNS resolution unless
stack order is changed (/etc/nsswitch.conf). 

In my experience /etc/host is first before anything else:
```
$ podman run ubi9 cat /etc/nsswitch.conf | grep hosts
# Valid databases are: aliases, ethers, group, gshadow, hosts,
hosts:      files dns myhostname
```


> If you make an entry into /etc/hosts file with an ip address and a host name on another line use the same IP address and a different host name it will only use the last entry. i.e.: 10.89.1.5 some host name 10.89.1.5 another host name

That does not seem to be the case either:

```
$ podman run --add-host host1:127.0.0.1 --add-host host2:127.0.0.1  alpine sh -c "ping -c 1 host1; ping -c 1 host2"
PING host1 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=42 time=0.031 ms

--- host1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.031/0.031/0.031 ms
PING host2 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=42 time=0.014 ms

--- host2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.014/0.014/0.014 ms
```

Just because some things are not documented does not mean it is a bug, it is briefly mentioned here: https://docs.podman.io/en/latest/markdown/podman-create.1.html#no-hosts
The docs can/should be improved, I agree. PRs are always welcome.

**Comment by jbhrfx9280** [comment] 2022-10-10 20:34
Thank you for your reply. I appreciate your time.

Not sure what to do now?
Here is a copy of my /etc/hosts file on my MariaDB container that was
created by Podman run ... you already have the code.
# cat /etc/hosts
10.89.1.5       mariadb_node1
10.89.1.10      mariadb_node2
127.0.0.1       localhost localhost.localdomain localhost4
localhost4.localdomain4 example.com example.net
::1     localhost localhost.localdomain localhost6 localhost6.localdomain6
example.com example.net
10.89.1.1       host.containers.internal
10.89.1.5       django-db_1

When I try to ping this server from my rhel 9 container using "10.89.1.5"
works well. When I try to ping using "mariadb_node1" it fails. When I try
to ping using "django-db_1" it works well. So as you can see it ignores
"mariadb_node1". I need it to work using "mariadb_node1". I cannot edit the
/etc/hosts file because there is no systemd or any text editors in the
mariadb container as designed. Nor would you open this container up to
that. Bad practice. The only way I see to do this is create a host file
outside of the container and copy into the container then bounce the
container. You can review the Podman info below. "--add-host" adds an entry
into /etc/hosts as stated it would. "--name"  Assign a name to the
container, not the host name. "--no-hosts" would not apply and would be in
conflict.  BTW Docker run does not have this issue.
Please advise.... Thank you so much.

As per your help docs online:
*--add-host*=*host:ip*¶
<https://docs.podman.io/en/latest/markdown/podman-run.1.html#add-host-host-ip>

Add a custom host-to-IP mapping (host:ip)

Add a line to /etc/hosts. The format is hostname:ip. The *--add-host* option
can be set multiple times. Conflicts with the *--no-hosts* option.
*--name*=*name*
Assign a name to the container.

The operator can identify a container in three ways:

   -

   UUID long identifier
   (“f78375b1c487e03c9438c729345e54db9d20cfa2ac1fc3494b6eb60872e74778”);
   -

   UUID short identifier (“f78375b1c487”);
   -

   Name (“jonah”).

Podman generates a UUID for each container, and if a name is not assigned
to the container with *--name* then it will generate a random string name.
The name is useful any place you need to identify a container. This works
for both background and foreground containers.


*--no-hosts*

Do not create */etc/hosts* for the container. By default, Podman will
manage */etc/hosts*, adding the container’s own IP address and any hosts
from *--add-host*. *--no-hosts* disables this, and the image’s
*/etc/hosts* will
be preserved unmodified.

**Comment by baude** [comment] 2022-10-10 21:59
what does your host's /etc/hosts look like?

**Comment by jbhrfx9280** [comment] 2022-10-10 22:33
Um..it's in the email I sent you under /etc/hosts. Here it is again.
etc/hosts
10.89.1.5       mariadb_node1
10.89.1.10      mariadb_node2
127.0.0.1       localhost localhost.localdomain localhost4
localhost4.localdomain4 example.com example.net
::1     localhost localhost.localdomain localhost6 localhost6.localdomain6
example.com example.net
10.89.1.1       host.containers.internal
10.89.1.5       django-db_1

Thank you

**Comment by rhatdan** [comment] 2022-11-11 12:42
@jbhrfx9280 @Luap99 @baude What is the scoop on this issue?  At this point is it a discussion?  @Luap99 says Podman is working properly, should I close the issue or move to a discussion?

**Comment by jbhrfx9280** [comment] 2022-11-11 15:06
I have figured these issues out using buildah and other methods, script
etc. You can close this ticket. Amazing no answers/replies from anyone.
Anyways thank you.

**Closed** 2022-11-11 20:37 UTC
Labels: kind/feature
