### ISSUE TITLE
Podman 4.0.2 System Service and Docker Compose unexpected EOF with JournalD

### ISSUE THREAD

**Issue by pclass-sensonix** [containers/podman#13778] opened 2022-04-05 13:10 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am running podman 4.0.2 with docker-compose v2.2.3 on a custom ARMv7 Linux 5.10 machine with SystemD 249.7+. I have a simple docker-compose.yml file with 1 container running a very noisy 'lumberjack.py' Python script.

The script runs for ~10 hours just fine with journalctl displaying the extremely verbose logs. This initial time to failure seems to depend on the amount of verbosity that the script dumps to the journald log. After that time, docker-compose stops suddenly within several minutes with **EOF** and is continually restarted with SystemD over and over again. The podman system service exits with several errors show below.  Each failure from docker-compose's perspective is this unexpected EOF. Each error from the podman system service's perspective is this error 'broken pipe'. Restarting the podman system service does not fix it and running docker-compose manually does not fix it. When I turn on debugging in the podman system service, the error seems to be related to journald with **failed to get cursor: cannot assign requested address:**

Podman system service debug output:

```
DEBU[0406] Read fd(2) 4096/8193 bytes for container ba9a6ab1e45940a3fb67995358fd7812eee0ed81782cdbf0921a860ff5e2ae59 
DEBU[0406] Read fd(2) 4096/8193 bytes for container ba9a6ab1e45940a3fb67995358fd7812eee0ed81782cdbf0921a860ff5e2ae59 
INFO[0408] Request Failed(Internal Server Error): failed to get journal cursor: failed to get cursor: cannot assign requested address 
http: superfluous response.WriteHeader call from github.com/gorilla/handlers.(*responseLogger).WriteHeader (handlers.go:61)
@ - - [05/Apr/2022:12:56:16 +0000] "GET /v1.40/events?filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Ddocker-compose%22%3Atrue%7D%7D HTTP/1.1" 500 1224 "" "Docker-Client/unknown-version (linux)"
DEBU[0408] IdleTracker:idle 1m+1h/3t connection(s)       X-Reference-Id=0x40848a0
DEBU[0408] STDOUT/ERR copy completed                    
ERRO[0408] Writing error to container ba9a6ab1e45940a3fb67995358fd7812eee0ed81782cdbf0921a860ff5e2ae59 HTTP attach connection: write unix /run/podman/podman.sock->@: write: broken pipe 
DEBU[0408] STDIN copy completed                         
ERRO[0408] Flushing HTTP buffer for container ba9a6ab1e45940a3fb67995358fd7812eee0ed81782cdbf0921a860ff5e2ae59 HTTP attach connection: write unix /run/podman/podman.sock->@: write: broken pipe 
ERRO[0408] error attaching to container ba9a6ab1e45940a3fb67995358fd7812eee0ed81782cdbf0921a860ff5e2ae59: write unix /run/podman/podman.sock->@: write: broken pipe 
DEBU[0408] Attach for container ba9a6ab1e45940a3fb67995358fd7812eee0ed81782cdbf0921a860ff5e2ae59 completed successfully 
DEBU[0408] IdleTracker:closed 1m+1h/3t connection(s)     X-Reference-Id="%!p(<nil>)"
@ - - [05/Apr/2022:12:56:05 +0000] "POST /v1.40/containers/ba9a6ab1e45940a3fb67995358fd7812eee0ed81782cdbf0921a860ff5e2ae59/attach?stderr=1&stdin=1&stdout=1&stream=1 HTTP/1.1" 200 0 "" "Docker-Client/unknown-version (linux)"
DEBU[0408] IdleTracker:closed 1m+0h/3t connection(s)     X-Reference-Id=0x40848a0
DEBU[0469] API service(s) shutting down, idle for 60s   
DEBU[0469] API service shutdown, 0/3 connection(s)      
DEBU[0469] API service forced shutdown, ignoring timeout Duration 
DEBU[0469] Called service.PersistentPostRunE(/usr/bin/podman --log-level=debug system service --time=60) 
```

Container journald log output form docker-compose:
```
tckrxgoBsyUjVduYFeipzYhdhqFYwmvTgTssqbLYlsFPJdKoEEmmmsgXQoAhDRKWfKkrwdFKKFZKvQckadOGdnoKfFpFuxKYTuANZYJFpDuGCxdDdEDdWDXzgmwZintdlvwpcNmncmZhDYlmmlsIAcBlTXtafKeiHGIshiTIOcSidgjJykKpDjxfkOuVWbQgikbBdMXzsTkEfMkKjuqeeCtEVMTCllsdENiyHboNKFOBnSKrsMvteMludVHhIJpPYcwuuEpQGnqlPvQvRqhbSIqmTuvFyAZWFTyRIcNgXPqRJuQBacPEkGOGAjaqBuwGUnKQddYPXjFKyXOmnMaMiejZvMrkKRcysVZGDutbIExnDJcisIPbZYrH
Apr 05 11:42:53 device sh[18873]: lumberjack  | 2022-04-05 11:42:53,071 - 1439627, thflXUhSJwgqhkNjrxCpgNqmOAgRVzAZxWRhdReAbANKLFMOKIxxvZEoVcJpdyDrjzQxFpFYNPCdhiUdCbqSnxWbUOMlkYqufRKyyUaqEdgRaFSCZqIdgptTxUAckzckFwmfdzGmjjpfsFMHdeiiFlpSIxyZOaqyDsRQzPtonULUdlKhAuVhAjAiyPSmIsaSEtACAMDTHcyrFWLCstmMJJCLMuGkTQdcMkeCvaHVTRfXdNvNfxbRCyMeVALEnujVHDrXgxpOygqKOXVTOgCinFoRIYoJOGZSxRRaRLwweNgVhWQVZYUqsbFQJkLEtyyoXptqTFIqDLpDHXrxZQclfslLSFchJLJUFQESlUlzFsHivjbxYyHOUUHtVOEIvbPIEbiroygjYzechpiTAfsViGlLmDWuIscbZbiwlzQHPCUvysRYhcXejXYZoANfdoTKxFiELDWALfJBoOwrdRCgmMcZSmYWgnfkmzqtxsmiOpbGgAgBBVdbadSWbDvfUPZd
Apr 05 11:42:53 device sh[18873]: EOF
Apr 05 11:42:53 device systemd[1]: device-docker-compose.service: Main process exited, code=exited, status=1/FAILURE
...
Apr 05 11:44:54 device sh[19376]: lumberjack  | 2022-04-05 11:44:52,349 - 1443314, KEduSNXdPRgYXSbQCoLjmwLuDkMdgSMwdSzrxxDJeOKfnuiXoYKrimDWNnyWIMMcIXctBmLATCuurJHfBdbqYPYpFUjvMWATVqvMyvgyPkGDnnfAVydiCvFGQnWmityvdoEbjekgjcwjdRlFtkgjumqCdtYubywWVcSVsoHNpfkYpfNdLZwvevLmVJcHuuKoAOElbDKHAIXXNRyWGwjjoyGfZpLDqWSDYUDlgECXorjQOKRcSbJIxIKxIiMIbcLYsieRmmpemvsUgRtWEzuvovPTceuRdmoLFEdPUwHFHwzIumcpmoMvFEcCpHfRhXlsVXzaUHqnyHMyKcvcYbQdoPPqfcoiuaKwhlFcLociNXkkhvyDiNfQCFIWYqnWRWUFTZQXFjBUxOfpZQcNRyzvzPNYtCQrXejHimMrbFMQkqmTmyrHiDuXdHisVpnbVHbEsisKDIPumhSXCbfpnuUPbCAKZcrrAXHQMdJpLkkgbPkMWYpBhgjZrvAiyUNIwRQS
Apr 05 11:44:54 device sh[19376]: lumberjack  | 2022-04-05 11:44:52,385 - 1443315, CWhhngwshCRtITZhOgPIAknqxcScPyLtWEwPznlEcwgPWmMykSbMJnHToppMfKOvjFDtHjuosdOOEijlLgpZDlbdNgZybqSatWGhwGekCodkXrWRoaaQEmTLseLQVBOOjdnjLGPTgIiLBVhEzHXOiQXoSpugdwCddomRSyONFAJETQDeZFXKOYUfJgpbfhTkeoAjPIKdJYJgbeJwLqPJlzcQPaqJvjyMVjhYtVEeVmOyvNTVfdIycNGfEFJAPmfdzBBeEaUOXFfbNhRzUfVdUScYkmpnvgOwnyDlFjskIfdqwtnhJOgIquDRRrSJqEAMQcQWiNIURKbxueGQiElHoOWahRTjXtmOOkZBqPNqApxYRcdSfmsbMlmClpSGQFNFQxelSeJIVvhwXisDjoaAbWZfdUSNyCmIvtxRlBbuiDcejYpqerwEYzUWTIRFAnVuHBHVgzPlnMUyYzvFDpcELuwpyMxieGRBtXkeBHWFdPabAMHOCjHrXnrFLmDMgBkC
Apr 05 11:44:54 device sh[19376]: EOF
```

**Steps to reproduce the issue:**

1.)  Create a docker-compose.yml file with these contents:

```
version: "2.4"
services:
  app1:
    container_name: "lumberjack"
    hostname: "lumberjack"
    image: "localhost/device-base:1.4"
    init: true
    security_opt:
      - "seccomp=unconfined"
    tty: true
    restart: "always"
    mem_limit: "35m"
    cpus: 0.95
    volumes:
      - "./app1:/app"
      - "./shared_data:/shared_data"
    networks:
      device_internal_net:
        ipv4_address: "10.89.0.2"
    entrypoint:
      - "python3"
      - "/app/lumberjack.py"
    environment: {}
volumes:
  shared_data: null
networks:
  device_internal_net:
    driver: "bridge"
```

2.) Create a **lumberjack.py** script with the following contents:

```
import time
import string
import random
import logging

logging.basicConfig(format='%(asctime)s - %(message).2048s', level=logging.INFO)
log = logging.getLogger(__name__)

count = 0
letters = string.ascii_letters
while True:
    log.info(f"{count}, {''.join(random.choice(letters) for i in range(512))}")
    count += 1
    #time.sleep(random.uniform(0.01, 0.2))
```

3.) Start the docker-compose environment and wait.

**Describe the results you received:**

podman and docker-compose will run my noisy container indefinitely.

**Describe the results you expected:**

podman container started by docker-compose and podman system service fails unexpectedly with **EOF**.

**Additional information you deem important (e.g. issue happens only occasionally):**

After a fresh boot, this takes many hours to hit this bug. After the bug is hit once, it seems to happen over and over in a short amount of time ( minutes ).

**Output of `podman version`:**

```
root@device:~# podman --version
podman version 4.0.2

root@device:~# docker-compose --version
Docker Compose version v2.2.3

root@device:~# systemctl --version
systemd 249 (249.7+)
+PAM -AUDIT -SELINUX -APPARMOR +IMA -SMACK -SECCOMP -GCRYPT -GNUTLS -OPENSSL -ACL +BLKID +CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY +P11KIT -QRENCODE -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=hybrid

```

**Output of `podman info --debug`:**

```
root@device:~# podman info
host:
  arch: arm
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 7e6de6678f6ed8a18661e1d5721b81ccee293b9b-dirty'
  cpus: 1
  distribution:
    distribution: unknown
    version: unknown
  eventLogger: journald
  hostname: device
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.50-linux4sam-2021.04
  linkmode: dynamic
  logDriver: journald
  memFree: 64966656
  memTotal: 253423616
  networkBackend: cni
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 0.4.1
      commit: unknown
  swapFree: 182710272
  swapTotal: 251654144
  uptime: 15h 5m 35.5s (Approximately 0.62 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /container-storage/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /container-storage/downloaded
  imageStore:
    number: 7
  runRoot: /container-storage/containers/storage
  volumePath: /container-storage/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1646322037
  BuiltTime: Thu Mar  3 15:40:37 2022
  GitCommit: ""
  GoVersion: go1.16.5
  OsArch: linux/arm
  Version: 4.0.2

version: "2.4"
services:
  app1:
    container_name: "lumberjack"
    hostname: "lumberjack"
    image: "localhost/device-base:1.4"
    init: true
    security_opt:
      - "seccomp=unconfined"
    tty: true
    restart: "always"
    mem_limit: "35m"
    cpus: 0.95
    volumes:
      - "./app1:/app"
      - "./shared_data:/shared_data"
      - "/persistent-storage/aws-creds:/aws-creds"
      - "/persistent-storage/azure-creds:/azure-creds"
      - "/persistent-storage/ibm-creds:/ibm-creds"
      - "/persistent-storage/generic-creds:/generic-creds"
    networks:
      device_internal_net:
        ipv4_address: "10.89.0.2"
    entrypoint:
      - "python3"
      - "/app/lumberjack.py"
    environment: {}
volumes:
  shared_data: null
networks:
  device_internal_net:
    driver: "bridge"
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Yocto build
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by pclass-sensonix** [comment] 2022-04-06 12:09
This also happens with "k8s-file" in the containers.conf file.

**log_driver = "k8s-file"
events_logger = "k8s-file"**

```
Apr 06 12:06:43 device sh[8626]: lumberjack1  | 2022-04-06 12:06:42,226 - 248196, HPmcxZTtfinVJKTjWeBYbkmjYCzSzdqcDUfeUyRTBxxINGuuBpNGFwnHuDsrUmRHMNIganoXKhWDlNWDoABEElAAeAAhZAAUXoSplsRPfnWYDCjuwVUOeymLZttnUzHiRGtSgNlsvWgvAXEsroxQrDvimRdUauvKthUGvmDJWuklPrSyIescyFWzVhymZkeVObHlbNTyZULZyfCbEadgadhaQPMLwXQytXwsQYOWwdVHswZvBFKTdhZsyaANGJRFImvFBQfmZZIdNwcMWuhKiNiPLXurYRiuuCrzNJSvqXDdjpPYxjIGZkZOKQFAGyOkPFuGPlhXbULOlhXMKXvKbLRKKZqIYqiowJqgGzRicnERPQNUXZGErgvjfstmlpHnhHpwYFUfeYicsvPAEdlyTACGvRSoIHMyvgwsMgjuiBOWtWtzsPTbuhaEdrgQlIWYpJwyJzXPsXxFZciVtYTvNcucRqZnZjnEkKXQwHjkRsPFEWQgMXOuXKJyVDNJYZMLfClzNOyhAnjWOuIkbsbKJCItzwdCkhItNSKXXsfqMiAPMgnHhWCXlkABazWyEBscFUDroMHSthfpJAdDOvXiYvlIpSmOmgsjNYshomrIWbGpfyJOxfwuTLvbCDCXIXpwPmQDYfgZmSMsJGquOKgXWqkIXAtqtmuqvLGHNFCXslcGWdbLbrReksWEXLlGcnHAxVdwdgIJPCpqlMnQgfliqnlNWFhXgzLWdcSAlpuzEZRNvZmqQqSvovIcZaMSzqCIemlKWMZLOAwcVLZaqydPqDedFidScSABfcyeOfrZkzpsDTpXQvEhgFmNKefPCJWmjSijHEOOtaXjKmLiTlOKzhnjsLxgmBDmMBbMyfvupJDgprfZZeycvIqPKValekUsrxPMGAXCHYzYjEoUKKAygNCRnrUVLUFxKqmSzxYTGKPwkDnpWLwaFUtMkRfYkTJHnsHXkoiaZcVDPguabABFymjkYGFMSdDxnqzvwuOzaUxTsPlVoowFJOOzvVwGEdYG
Apr 06 12:06:43 banner-fusion-gateway sh[8626]: EOF
```

**Comment by pclass-sensonix** [comment] 2022-04-06 17:27
It doesn't seem to have to do with journals log rotation either. I've been sporadically manually running 'journalctl --rotate' and it seems to keep logging correctly.

**Comment by rhatdan** [comment] 2022-05-07 09:53
@nalind PTAL

**Comment by pclass-sensonix** [comment] 2022-06-01 18:08
Hi - this is still happening. Do you have any suggestions I can try? Thank you.

**Comment by rhatdan** [comment] 2022-07-02 10:53
@mheon PTAL

**Comment by pclass-sensonix** [comment] 2022-07-04 14:37
Hi - I tried the latest common ( v2.1.2  ) and it is still failing. If there is substantial container output, eventually the EOF will occur.

**Comment by mheon** [comment] 2022-07-05 16:09
Core error seems to be the journal. I'd imagine it's getting angry about the amount of content we're dumping into it? We've had similar issues elsewhere.

**Comment by pclass-sensonix** [comment] 2022-08-31 13:04
> Core error seems to be the journal. I'd imagine it's getting angry about the amount of content we're dumping into it? We've had similar issues elsewhere.

I hit this condition again with Podman 4.2.0. This time I squelched all output from my container processes. I hit the condition within 1.5 hours of starting my applications, and since then it has been running ~12 hours without the issue.

```
Aug 08 09:10:23 system systemd[1]: Company Docker-Compose Environment was skipped because of a failed condition check (ConditionPathExists=/storage/docker-compose/docker-compose.yml).
Aug 30 22:27:31 system systemd[1]: Started Company Docker-Compose Environment.
Aug 30 22:27:40 system sh[2338]: Network company-internal-net  Creating
Aug 30 22:27:41 system sh[2338]: Network company-internal-net  Created
Aug 30 22:27:41 system sh[2338]: Container data_collector  Creating
Aug 30 22:27:47 system sh[2338]: Container data_collector  Created
Aug 30 22:27:47 system sh[2338]: Container mqtt_client  Creating
Aug 30 22:27:49 system sh[2338]: Container mqtt_client  Created
Aug 30 22:27:49 system sh[2338]: Attaching to data_collector, mqtt_client
Aug 30 23:59:08 system sh[2338]: EOF
Aug 30 23:59:08 system systemd[1]: company-docker-compose.service: Main process exited, code=exited, status=1/FAILURE
Aug 30 23:59:08 system systemd[1]: company-docker-compose.service: Failed with result 'exit-code'.
Aug 30 23:59:08 system systemd[1]: company-docker-compose.service: Consumed 4.880s CPU time.
Aug 30 23:59:08 system systemd[1]: company-docker-compose.service: Scheduled restart job, restart counter is at 1.
Aug 30 23:59:09 system systemd[1]: Stopped Company Docker-Compose Environment.
Aug 30 23:59:09 system systemd[1]: company-docker-compose.service: Consumed 4.880s CPU time.
Aug 30 23:59:09 system systemd[1]: Started Company Docker-Compose Environment.
Aug 30 23:59:25 system sh[9719]: Container data_collector  Running
Aug 30 23:59:25 system sh[9719]: Container mqtt_client  Running
Aug 30 23:59:26 system sh[9719]: Attaching to data_collector, mqtt_client
```

**Comment by pclass-sensonix** [comment] 2022-08-31 13:05
So perhaps the frequency of output aggravates the issue but does not cause it 100% of the time?

**Comment by pclass-sensonix** [comment] 2022-08-31 16:35
I bumped docker-compose and conmon to the latest versions and am still seeing this issue:

1.) conmon version 2.1.4
2.) docker-compose v2.10.2

**Comment by rhatdan** [comment] 2022-09-01 11:52
Have you tried to change the logdriver to file?

**Comment by pclass-sensonix** [comment] 2022-09-01 12:55
@rhatdan - yes I have tried changing both of the following to 'file' and 'none'. Unfortunately I still eventually get the EOFs.

```
log_driver = "none"
events_logger = "none"
```

Here is my entire containers.conf file:

```
**[containers]
default_capabilities = [
  "CHOWN",
  "DAC_OVERRIDE",
  "FOWNER",
  "FSETID",
  "KILL",
  "NET_BIND_SERVICE",
  "SETFCAP",
  "SETGID",
  "SETPCAP",
  "SETUID",
  "SYS_CHROOT"
]
default_sysctls = [
  "net.ipv4.ping_group_range=0 0",
]
#devices = []
init = true
init_path = "/usr/bin/docker-init"
log_driver = "none"
events_logger = "none"
log_size_max=10485760
log_global_size_max=10485760
[network]
cni_plugin_dirs = ["/usr/libexec/cni"]
default_network = "podman"
default_subnet = "10.88.0.0/16"
network_config_dir = "/etc/cni/net.d/"
[engine]
env = ["TMPDIR=/container-storage/downloaded"]
cgroup_manager = "cgroupfs"
runtime = "crun"
static_dir = "/container-storage/containers/storage/libpod"
stop_timeout = 3
volume_path = "/container-storage/containers/storage/volumes"**
```

**Comment by pclass-sensonix** [comment] 2022-09-01 13:00
Another interesting bit of information I found was that if I start the podman system service and then my docker-compose environment, I can always trigger the EOF by restarting the podman system service. I am not sure if that is the same issue ( and maybe a guaranteed way to cause the issue for debugging ). I thought perhaps that if the podman system service goes away, docker-compose would handle that a bit more gracefully since the containers are started and running.

**Comment by rhatdan** [comment] 2022-09-06 18:41
@baude PTAL

**Comment by pclass-sensonix** [comment] 2022-09-08 12:11
Yesterday I changed my SystemD service file to run docker-compose in 'detached' mode:

`ExecStartPre=/bin/sh -c "/usr/bin/docker-compose --ansi never -f ./docker-compose.yml up -d --remove-orphans"`

I still wanted to see the output from each container so I added a 'podman attach' command to the service file as well:

`ExecStartPre=/bin/bash -c "/usr/bin/docker-compose ps | grep -v NAME | tr -s \" \" | cut -d \" \" -f 1 | while read line ; do ( podman attach --no-stdin \"$line\" & ); done"`

Since doing this, it has been running for 17 hours without any EOFs - and journalctl shows my container output.

Without running in detached mode, I would encounter the EOF far before 17 hours. Perhaps the issue is with running docker compose without detached mode against the podman system service for long periods of time.

**Comment by rhatdan** [comment] 2022-09-08 12:25
That is interesting, since the issue could be a resource leak.  If the service stays up for a long period of time, then it becomes more of a daemon, and we could be seeing a conflict happening.

**Comment by 0fbcb238c0** [comment] 2022-11-13 20:31
I also had this issue. I started a number of [Archive Warriors](https://wiki.archiveteam.org/index.php?title=Warrior) on two machines. One running a current Fedora with up-to-date packages and a RHEL 9.0 machine. Both systems experienced the error.
I'm currently testing with fewer containers, but will increase the number to try and reproduce the issue.
I have not yet tried to set "eventLogger" to "file" or something else

**Comment by ssbarnea** [comment] 2022-11-25 10:58
I am seeing the same error even with latest podman 4.3.0 on fedora 37:
```
Error: attaching to container fff6dd3fb8c095592bc206c376bd808c5298e3b98eb59961ec0bfc647f43abb0: write /dev/stdout: broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
```

**Comment by Luap99** [comment] 2024-04-04 12:03
I assume this is fixed in the latest version

**Closed by Luap99** 2024-04-04 12:03 UTC
Labels: kind/bug
