### ISSUE TITLE
Unable to use the events streaming endpoint as when using docker engine

### ISSUE THREAD

**Issue by iongion** [containers/podman#24185] opened 2024-10-07 10:27 UTC
### Issue Description

I am unable to consume events using the `/events` endpoint.

Sample code to reproduce it

Sample `package.json` - note, using axios 1.7.7 as it supports streaming out of the box using http agent.

```json
{
  "name": "podman-events-streaming-test",
  "description": "",
  "main": "test.mjs",
  "homepage": "./",
  "type": "module",
  "scripts": {
    "node": "node"
  },
  "private": true,
  "dependencies": {
    "axios": "^1.7.7"
  }
}
```

The example `test.mjs`

```javascript
import axios from "axios";
import httpAdapter from "axios/lib/adapters/http.js";
import http from "http";

export function createApiDriver() {
  const httpAgent = new http.Agent({
    keepAlive: true,
    keepAliveMsecs: 10,
    timeout: 30000
  });
  const driver = axios.create({
    adapter: httpAdapter,
    httpAgent,
    baseURL: "http://d",
    // socketPath: "\\\\.\\pipe\\podman-machine-default"
    socketPath: "/run/user/1002/podman/podman.sock"
    // socketPath: "/var/run/docker.sock"
  });
  return driver;
}

const driver = createApiDriver();
console.debug(">> PING");
let response = await driver.get("/_ping");
console.debug("<< PING", response.data);
console.debug(">> EVENTS STREAM");
response = await driver.get("/events", { responseType: "stream" });
// response.data.pipe(process.stdout);
console.debug("<< EVENTS STREAM (waiting for events)");
```

To test

```
npm install
node test.mjs
```

### Steps to reproduce the issue

Steps to reproduce the issue

1. Use example client code to reproduce the issue

### Describe the results you received

Describe the results you received

Upon running the example, although the response type is `stream`, the request never finishes

```
>> PING
<< PING OK
>> EVENTS STREAM
```

Interception of events is not possible because the request never finishes.

### Describe the results you expected

Describe the results you expected

When switching to docker socket (docker engine), the output looks like this, which is expected:

```
>> PING
<< PING OK
>> EVENTS STREAM
<< EVENTS STREAM (waiting for events)
```

And one can now intercept events and use them

### podman info output

It happened on any podman version I've tried - current version I am using is `5.2.3` with cgroup v2 enabled, WSL Ubuntu 24.04

```yaml
host:
  arch: amd64
  buildahVersion: 1.37.3
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon_100:2.1.12-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: e21e7c85b7637e622f21c57675bf1154fc8b1866'
  cpuUtilization:
    idlePercent: 99.91
    systemPercent: 0.04
    userPercent: 0.04
  cpus: 32
  databaseBackend: sqlite
  distribution:
    codename: noble
    distribution: ubuntu
    version: "24.04"
  eventLogger: file
  freeLocks: 2047
  hostname: HomePCI7
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.146.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 9250353152
  memTotal: 16768786432
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns_1.4.0-5_amd64
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.4.0
    package: netavark_1.4.0-4_amd64
    path: /usr/lib/podman/netavark
    version: netavark 1.4.0
  ociRuntime:
    name: crun
    package: crun_100:1.17-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.17
      commit: 000fa0d4eeed8938301f3bcf8206405315bc1017
      rundir: /run/user/1002/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt_100:0.0+20240906.6b38f072-1_amd64
    version: |
      pasta 0.0+20240906.6b38f072
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1002/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_100:1.3.1-1_amd64
    version: |-
      slirp4netns version 1.3.1
      commit: unknown
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 5h 5m 48.00s (Approximately 0.21 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/istoica/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/istoica/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 235468357632
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1002/containers
  transientStore: false
  volumePath: /home/istoica/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.3
  Built: 1728141165
  BuiltTime: Sat Oct  5 17:12:45 2024
  GitCommit: d3629e043110829451b0de76a9d2b15931b5cc88
  GoVersion: go1.22.2
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.3
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

I've tried podman on linux natively, on macos and lima, all behave the same.

### Additional information

The issue happens in any os

**Comment by Luap99** [comment] 2024-10-07 10:58
This sounds like a duplicate of https://github.com/containers/podman/issues/23712

**Comment by Luap99** [comment] 2024-10-29 16:25
Closing this as dup, PR https://github.com/containers/podman/pull/24406 contains the fix so feel free to test it.

**Closed by Luap99** 2024-10-29 16:25 UTC
Labels: kind/bug
