### ISSUE TITLE
unable to start a container

### ISSUE THREAD

**Issue by JimitSoni18** [containers/podman#24792] opened 2024-12-07 13:55 UTC
### Issue Description

when staring a podman container using podman-compose up -d, i get the following error:

Error: unable to start container "1658c6e0bc891751926b1f968abb67ff5963c37dc4454e361de1409dadc06aa6": rootless netns: mount "/tmp/containers/networks/rootless-netns/run" to "/run": no such file or directory

i remove the container+pod, make the directory /tmp/containers/networks/rootless-netns/run, and then run it again. it fails again with the same error message, and the directory that i just created is gone!

here is my podman-compose file:
```yml
version: "3"
services:
  garage:
    image: docker.io/dxflrs/garage:v1.0.0
    restart: unless-stopped
    volumes:
      - /etc/garage.toml:/etc/garage.toml
      - /var/lib/garage/meta:/var/lib/garage/meta
      - /var/lib/garage/data:/var/lib/garage/data
    ports:
      - 3901:3901
```

here is the output of `podmancompose up -d`:
```
WARN[0000] Using cgroups-v1 which is deprecated in favor of cgroups-v2 with Podman v5 and will be removed in a future version. Set environment vari
able `PODMAN_IGNORE_CGROUPSV1_WARNING` to hide this warning.
051312a300621494cd49d2c617c3f0a7e9adb955678c01d91f3031379ef9912c
WARN[0000] Using cgroups-v1 which is deprecated in favor of cgroups-v2 with Podman v5 and will be removed in a future version. Set environment vari
able `PODMAN_IGNORE_CGROUPSV1_WARNING` to hide this warning.
WARN[0000] aardvark-dns binary not found, container dns will not be enabled
c79d146680fe19b950fa461e312b2d0c0eac5a3b8c235d19bb42450dad84b32b
WARN[0000] Using cgroups-v1 which is deprecated in favor of cgroups-v2 with Podman v5 and will be removed in a future version. Set environment vari
able `PODMAN_IGNORE_CGROUPSV1_WARNING` to hide this warning.
WARN[0001] aardvark-dns binary not found, container dns will not be enabled
Error: unable to start container "c79d146680fe19b950fa461e312b2d0c0eac5a3b8c235d19bb42450dad84b32b": rootless netns: mount "/tmp/containers/network
s/rootless-netns/run" to "/run": no such file or directory
```

i do not know much about network namespaces.

i did not invoke podman/podman-compose with sudo.

i am using void linux glibc

### Steps to reproduce the issue

Steps to reproduce the issue
1. copy this podman compose file
2. run podman-compose -d up
3. it does create a container, but fails to run giving the aforementioned output

### Describe the results you received

container fails to run giving the aforementioned output

### Describe the results you expected

container should be created and process should be running

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.36.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.10, commit: unknown'
  cpuUtilization:
    idlePercent: 86.97
    systemPercent: 2.78
    userPercent: 10.25
  cpus: 4
  databaseBackend: sqlite
  distribution:
    distribution: void
    version: unknown
  eventLogger: file
  freeLocks: 2037
  hostname: void
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.6.60_1
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 662310912
  memTotal: 8000667648
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
    package: Unknown
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.1.13
      spec: 1.0.2-dev
      go: go1.23.0
      libseccomp: 2.5.5
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: Unknown
    version: |
      pasta unknown version
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /tmp/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 17118953472
  swapTotal: 17179865088
  uptime: 9h 36m 35.00s (Approximately 0.38 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/jimit/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/jimit/.local/share/containers/storage
  graphRootAllocated: 83955703808
  graphRootUsed: 67461001216
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /tmp/containers
  transientStore: false
  volumePath: /home/jimit/.local/share/containers/storage/volumes
version:
  APIVersion: 5.1.2
  Built: 0
  BuiltTime: Thu Jan  1 05:30:00 1970
  GitCommit: ""
  GoVersion: go1.23.0
  Os: linux
  OsArch: linux/amd64
  Version: 5.1.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details: None

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

ocassionally panics on null dereference, forgot to get the log output, but it was some function with a name similar to `getHost`

**Comment by Luap99** [comment] 2024-12-10 12:08
Duplicate of #24777

**Closed by Luap99** 2024-12-10 12:08 UTC
Labels: kind/bug
