### ISSUE TITLE
Run rootful container with userns=auto fails due to "wrong" file ownership

### ISSUE THREAD

**Issue by florentulve** [containers/podman#24037] opened 2024-09-23 06:12 UTC
### Discussed in https://github.com/containers/podman/discussions/24033

<div type='discussions-op-text'>

<sup>Originally posted by **florentulve** September 22, 2024</sup>
Hi,

I am confronted to an issue with podman rootfull dans userns=auto and the redis image from the docker library : https://hub.docker.com/_/redis

Its entrypoint check the ownership of the current directory and chown if needed.

`#### allow the container to be started with `--user`

if [ "$1" = 'redis-server' -a "$(id -u)" = '0' ]; then
	find . \! -user redis -exec chown redis '{}' +
	exec gosu redis "$0" "$@"
fi`

source: https://github.com/redis/docker-library-redis/blob/master/docker-entrypoint.sh

It fails with **userns=auto** because the working directory ownership is not the redis 999 user as shown below:

![image](https://github.com/user-attachments/assets/c7bcda86-43d1-4551-acbf-27bb8df461b4)

My subuid and subgid contains

`
containers:2147483647:2147483648
`

If i check the underlying filesystem:

`ls -alnZ /var/lib/containers/storage/overlay/85fa5b943e569816e1fb2627827e35c06f166e0079d6fa153c4d2d58273eed73/merged

lrwxrwxrwx. 1 2147583647 2147583647 system_u:object_r:container_file_t:s0:c655,c984  7 Sep  4 11:00 bin -> usr/bin/
drwxr-xr-x. 1 2147583647 2147583647 system_u:object_r:container_file_t:s0:c655,c984  0 Aug 14 18:10 boot/
drwxr-xr-x. 1 2147584646 2147584646 system_u:object_r:container_file_t:s0:c655,c984  0 Sep  5 01:09 data/
drwxr-xr-x. 1 2147583647 2147583647 system_u:object_r:container_file_t:s0:c655,c984  0 Sep  4 11:00 dev/`

2147583647 -> 0
2147584646 -> 2147583647 + 999(redis user)

I realy don't understand why inside the container the 2147584646 user is reported as 65534 noboby as shown in the screen above.

Podman version affected 5.2.2
This works with podman 4.3.1

</div>

**Comment by giuseppe** [comment] 2024-09-23 06:54
it is a duplicate of https://github.com/containers/podman/issues/23347

that was fixed recently by https://github.com/containers/podman/pull/23977

**Closed by giuseppe** 2024-09-23 06:54 UTC
