### ISSUE TITLE
Installing podman on ubuntu gets old version

### ISSUE THREAD

**Issue by crfrolik** [containers/podman#15028] opened 2022-07-21 14:59 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On Ubuntu 22.04, installing podman via `apt` gets version 3.4.2, even though the latest is 4.1.1.

**Steps to reproduce the issue:**

1. `sudo apt update`
2. `sudo apt install podman`
3. `podman --version`

**Describe the results you received:**

`podman version 3.4.2`

**Describe the results you expected:**

`podman version 4.1.1`

**Comment by mheon** [comment] 2022-07-21 15:01
@lsm5 This is expected, right?

**Comment by Luap99** [comment] 2022-07-21 15:15
This is just the official package in ubuntu/debian. We (upstream) have no control about that. You should reach out to the packager.
Duplicate of #14065

**Closed by Luap99** 2022-07-21 15:15 UTC
Labels: kind/bug

**Comment by lsm5** [comment] 2022-07-22 14:29
Yes, that's what you would see on the official ubuntu repos. I think debian experimental has a newer version.

Anyway, @crfrolik please see https://github.com/containers/podman/issues/14302#issuecomment-1192617223 for info about an unstable kubic repo you could try for non-production use.
