### ISSUE TITLE
[Question] Anywhere we can download old podman versions?

### ISSUE THREAD

**Issue by tetchel** [containers/podman#10148] opened 2021-04-27 13:19 UTC
Hi,

Is there anywhere we can download older versions of podman?

It looks like the versions in the distro repositories, and in the Kubic project repository, are all kept at latest. And there are no binaries attached to the GitHub releases.

In the past, we have wanted to see if an issue is due to a change between podman versions. But we don't have a way to get old binaries for testing, or for reverting our environments if the issue was with podman.

Thank you

**Comment by rhatdan** [comment] 2021-04-27 14:30
We do not keep older versions in Kubic project, since I believe this has proven to be difficult.  @lsm5 would know more.
We would prefer distributions to provide Podman, so we can get out of the shipping business.

**Comment by tetchel** [comment] 2021-04-27 14:48
Is there a reason (historical, legal, etc) why release binaries are not attached to the GitHub releases?

**Comment by rhatdan** [comment] 2021-04-27 14:53
For which distribution?  Podman is not an all inclusive binary, it depends on OCI Runtimes, Specific versions of conmon, specific versions of container-selinux, fuse-overlayfs, slirp4netns, CNI Plugins, crun, runc, containers-common.

**Comment by tetchel** [comment] 2021-04-27 14:57
Right, ok. That makes sense.

Because of the number of dependencies it would be great to have multiple versions in the distro repositories and/or the kubic project, so users can revert to a previous, working version if they have an issue.

**Comment by rhatdan** [comment] 2021-04-27 15:02
Sure, but I believe we need to leave this to volunteers. Bottom line @lsm5 does not have time to maintain them.

**Comment by afbjorklund** [comment] 2021-04-27 15:33
We have talked about this before (#3924 #9358), but so far no takers. You will have to rebuild from source.

**Comment by rhatdan** [comment] 2021-04-27 15:44
Closed as a duplicate of #3924

**Closed by rhatdan** 2021-04-27 15:44 UTC
