### ISSUE TITLE
[root] podman events --events-backend=file now hanging forever

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15703] opened 2022-09-08 18:07 UTC
I seem to have managed to get my laptop in a state where this hangs forever (as in, over 8 minutes):
```console
# podman --log-level=trace events --stream=false --events-backend=file 
....
DEBU[0000] Using OCI runtime "/usr/bin/crun"
INFO[0000] Setting parallel job count to 37
DEBU[0000] Initializing event backend file
```
It might've been while playing with #15698, but I've `rm`'ed the dotfile.

`lsof` on the process shows nothing useful, nor does `strace`. `/run/libpod/events` is empty. There is a `/run/libpod/alive.lck`, but `rm`'ing it has no effect, it just shows up again later. Only happens with `--events-backend=file`, `journald` or default are fine.

Is there a way to find out what podman is waiting for? Seems like an important missing log message.

**Comment by Luap99** [comment] 2022-09-08 18:45
Duplicate of https://github.com/containers/podman/issues/15688? I found this while running your new --format test.
Basically if the file does not exists it just hangs until the file is created.

**Comment by edsantiago** [comment] 2022-09-08 19:10
Nice. Yes, that's very clearly the same bug. Thank you!

**Closed** 2022-09-08 19:12 UTC
