### ISSUE TITLE
`podman manifest add` unable to set os.version

### ISSUE THREAD

**Issue by snay2** [containers/podman#12774] opened 2022-01-07 22:10 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When trying to create or modify a manifest that includes a Windows image, I am unable to set the `os.version` value in the manifest via `podman manifest add ... --os-version`.

**Steps to reproduce the issue:**

1. Run the following commands:
   1. `podman manifest create public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1`
   1. `podman manifest add public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1 public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1-windows-amd64 --arch amd64 --os windows`
1. At this point, run `podman manifest inspect public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1` and note that, as expected, there is no `os.version` value under `platform` for the image.
1. Now try to add the image to the manifest with an `os.version`:
   1. `podman manifest add public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1 public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1-windows-amd64 --arch amd64 --os windows --os-version 10.0.17763.1282`
1. Now run `podman manifest inspect public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1` again. Note that there is still no `os.version` value under `platform` for the image. This is incorrect.

**Describe the results you received:**
Output of `podman manifest inspect`:

```
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 1752,
            "digest": "sha256:2a72849bcd7c46518523072f8ad3453c451030a1ddfd2dd9c95bdae3ffdfdc8e",
            "platform": {
                "architecture": "amd64",
                "os": "windows"
            }
        }
    ]
}
```

**Describe the results you expected:**
Output of `podman manifest inspect`:

```
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 1752,
            "digest": "sha256:2a72849bcd7c46518523072f8ad3453c451030a1ddfd2dd9c95bdae3ffdfdc8e",
            "platform": {
                "architecture": "amd64",
                "os": "windows",
                "os.version": "10.0.17763.1282"
            }
        }
    ]
}
```

**Additional information you deem important (e.g. issue happens only occasionally):**
I also tried a few other syntax variations, but none of them worked either:

* `--os-version=10.0.17763.1282`
* `--os-version "10.0.17763.1282"`
* `--os-version="10.0.17763.1282"`

**Output of `podman version`:**

```
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec  8 12:41:11 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 15:45:07 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.12-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1617551360
  memTotal: 2061381632
  ociRuntime:
    name: crun
    package: crun-1.4-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4
      commit: 3daded072ef008ef0840e8eccb0b52a7efbd165d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 5h 42m 30.71s (Approximately 0.21 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1638999907
  BuiltTime: Wed Dec  8 21:45:07 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ brew list podman
/usr/local/Cellar/podman/3.4.4/bin/podman
/usr/local/Cellar/podman/3.4.4/bin/podman-remote
/usr/local/Cellar/podman/3.4.4/etc/bash_completion.d/podman
/usr/local/Cellar/podman/3.4.4/libexec/gvproxy
/usr/local/Cellar/podman/3.4.4/share/fish/vendor_completions.d/podman.fish
/usr/local/Cellar/podman/3.4.4/share/man/ (160 files)
/usr/local/Cellar/podman/3.4.4/share/zsh/site-functions/_podman
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on a MacBook with Big Sur 11.6.2

**Comment by rhatdan** [comment] 2022-01-08 11:32
```
$ podman manifest create public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1
0e17655a7e8dddb7d49e6610d62d6be1af20fea3fd44c08c6000f058f216a796
$ podman manifest add public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1 public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1-windows-amd64 --arch amd64 --os windows
0e17655a7e8dddb7d49e6610d62d6be1af20fea3fd44c08c6000f058f216a796
$ podman manifest inspect public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 1752,
            "digest": "sha256:2a72849bcd7c46518523072f8ad3453c451030a1ddfd2dd9c95bdae3ffdfdc8e",
            "platform": {
                "architecture": "amd64",
                "os": "windows"
            }
        }
    ]
}
$ podman manifest add public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1 public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1-windows-amd64 --arch amd64 --os windows --os-version 10.0.17763.1282
0e17655a7e8dddb7d49e6610d62d6be1af20fea3fd44c08c6000f058f216a796
podman (pause) $ podman manifest inspect public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 1752,
            "digest": "sha256:2a72849bcd7c46518523072f8ad3453c451030a1ddfd2dd9c95bdae3ffdfdc8e",
            "platform": {
                "architecture": "amd64",
                "os": "windows",
                "os.version": "10.0.17763.1282"
            }
        }
    ]
}
```
This looks like it worked for me?
```
$ podman -v
podman version 3.4.4
$ rpm -q podman
podman-3.4.4-1.fc35.x86_64
```

**Comment by snay2** [comment] 2022-01-10 21:55
I tried it on a linux machine with podman version 3.0.1 and it worked, like you described.

However, when I run these commands on a Mac, it doesn't work. Are there other things I should try to get that environment to work?

**Comment by rhatdan** [comment] 2022-01-10 22:23
Can you get newer versions on the MAC, this could be a remote API problem.

**Comment by snay2** [comment] 2022-01-10 22:44
I’m running 3.4.4 on the Mac (both client and server), which is the latest release if I understand correctly.

**Comment by rhatdan** [comment] 2022-01-11 10:51
I just ran podman 3.4.4 against this script, with a reset storage and it works for me.
```
#!/usr/bin/bash -x
/bin/podman --remote manifest create public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1
/bin/podman --remote manifest add public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1 public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1-windows-amd64 --arch amd64 --os windows
/bin/podman --remote manifest inspect public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1
```

```
 $ /tmp/t.sh
+ /bin/podman --remote manifest create public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1
92937daf269f6e066a5b73f0d299e7b7af81468e4ff6070081030a7c7339ed4a
+ /bin/podman --remote manifest add public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1 public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1-windows-amd64 --arch amd64 --os windows
92937daf269f6e066a5b73f0d299e7b7af81468e4ff6070081030a7c7339ed4a
+ /bin/podman --remote manifest inspect public.ecr.aws/u0c8p9d8/nth-test-public:v1.6.1
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 1752,
            "digest": "sha256:2a72849bcd7c46518523072f8ad3453c451030a1ddfd2dd9c95bdae3ffdfdc8e",
            "platform": {
                "architecture": "amd64",
                "os": "windows",
                "os.version": "10.0.17763.1282"
            }
        }
    ]
}
```

**Comment by vrothberg** [comment] 2022-01-17 10:59
@ashley-cui could you have a look and try to reproduce on mac?

**Comment by snay2** [comment] 2022-01-18 22:43
Update from me: I tried using `--remote` and it behaved the same; still unable to set `os.version` on a Mac.

I've gone back to using `docker manifest annotate` commands instead of `podman manifest`, so this is not a pressing issue for me, but it does still seem like a bug.

**Comment by rhatdan** [comment] 2022-02-21 14:00
@flouthoc PTAL. I think this could be a podman-remote issue, could you see if this has been fixed?

**Comment by flouthoc** [comment] 2022-02-28 12:34
Ackd, I can reproduce this bug exists on `podman-remote` side. I'll check this thanks.

**Comment by flouthoc** [comment] 2022-03-01 09:43
@snay2 Thanks, above PR should close this issue and will be present in newer versions of podman.

**Comment by flouthoc** [comment] 2022-04-01 06:40
The PR linked to this issue is yet to be reviewed by @jwhonce

**Comment by rhatdan** [comment] 2022-05-02 20:49
@flouthoc @jwhonce State of this issue?

**Comment by flouthoc** [comment] 2022-06-02 04:55
Not stale and needs to be visited again, discussion on the linked PR expected this to be fixed upstream but issue still persists. Please  follow linked PR for updates.

**Closed** 2022-06-21 20:18 UTC
Labels: kind/bug
