### ISSUE TITLE
WSL2: can't start containers

### ISSUE THREAD

**Issue by c-goes** [containers/podman#8578] opened 2020-12-03 14:54 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After 2.2 Update no containers can be started on WSL2 using Ubuntu 20.04 distro (rootless and rootful)

**Steps to reproduce the issue:**

Rootless

1. podman run -it  busybox sh

Rootful

1. podman run -it busybox sh

**Describe the results you received:**

Rootless

```
error creating temporary file: No such file or directory
Error: error setting up the process: open /tmp/podman-run-1000/libpod/pause.pid: no such file or directory
```

Rootful

```
# podman run -it busybox sh
Completed short name "busybox" with unqualified-search registries (origin: /etc/containers/registries.conf)
Trying to pull docker.io/library/busybox:latest...
Getting image source signatures
Copying blob 5f5dd3e95e9f done
Copying config dc3bacd8b5 done
Writing manifest to image destination
Storing signatures
ERRO[0004] unable to write pod event: "write unixgram @00006->/run/systemd/journal/socket: sendmsg: no such file or directory"
Error: OCI runtime error: systemd cgroup flag passed, but systemd support for managing cgroups is not available
```

**Describe the results you expected:**

Shell prompt

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

rootfull

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: wslhost
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.128-microsoft-standard
  linkmode: dynamic
  memFree: 6375514112
  memTotal: 8345993216
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 6h 28m 8.57s (Approximately 0.25 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 20
    paused: 0
    running: 0
    stopped: 20
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 23
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.0
```

rootless:

command doesn't work

```
error creating temporary file: No such file or directory
Error: error setting up the process: open /tmp/podman-run-1000/libpod/pause.pid: no such file or directory
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.2.0~2 amd64 [installed]
podman/unknown 2.2.0~2 arm64
podman/unknown 2.2.0~2 armhf
podman/unknown 2.2.0~2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

WSL2

**Comment by mheon** [comment] 2020-12-03 14:58
Dupe of https://github.com/containers/podman/issues/8539 - see that for a workaround.

**Closed by mheon** 2020-12-03 14:58 UTC
Labels: kind/bug
