### ISSUE TITLE
Internet / DNS not working when using custom network

### ISSUE THREAD

**Issue by olee** [containers/podman#19590] opened 2023-08-10 20:41 UTC
### Issue Description

When I run a container with the default network, dns works just fine:
```
> podman run --rm -it alpine nslookup google.com
Server:         172.29.64.1
Address:        172.29.64.1:53

Non-authoritative answer:
Name:   google.com
Address: 142.250.186.174

Non-authoritative answer:
Name:   google.com
Address: 2a00:1450:4001:802::200e
```

However, as soon as I use a custom network, dns fails on me:
```
> podman network create --driver bridge test
> podman run --rm --network test -it alpine nslookup google.com
;; connection timed out; no servers could be reached
```

A container created with the default network has this in `/etc/resolv.conf`:
```
nameserver 10.0.2.3
nameserver 172.29.64.1
```

When I create a container with a custom network instead, it looks like this:
```
search dns.podman
nameserver 10.89.1.1
```

If I now enter the container and replace nameserver with eg. `8.8.8.8` everything works again.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman network create --driver bridge test`
2. `podman run --rm --network test -it alpine nslookup google.com`

### Describe the results you received

No dns / internet when using a custom network

### Describe the results you expected

Working dns resolution

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.46
    systemPercent: 0.18
    userPercent: 0.35
  cpus: 32
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: journald
  hostname: #######
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 12685119488
  memTotal: 16720412672
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.4-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 32h 37m 33.00s (Approximately 1.33 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 9685991424
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 15
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681486976
  BuiltTime: Fri Apr 14 17:42:56 2023
  GitCommit: ""
  GoVersion: go1.19.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```

### Podman in a container
No

### Privileged Or Rootless
None

### Upstream Latest Release
Yes

### Additional environment details
Running on windows 10

**Comment by Luap99** [comment] 2023-08-11 08:29
Duplicate of #18530

**Closed by Luap99** 2023-08-11 08:29 UTC
Labels: kind/bug, remote
