### ISSUE TITLE
Failed config validation with custom CNI plugins

### ISSUE THREAD

**Issue by kbknapp** [containers/podman#14363] opened 2022-05-25 14:56 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Adding a custom CNI plugin fails configuration validation

**Steps to reproduce the issue:**

1. Add a file `/etc/cni/net.d/10-demo-custom-cni.conflist` with the contents (contents are valid for the `custom-cni` plugin:

```
{
  "cniVersion": "0.4.0",
  "name": "demo",
  "plugins": [{
    "type": "custom-cni",
    "arg": "value"
  }]
}
```

3. Place `custom-cni` binary in `/usr/local/lib/cni/` (which is listed in `/etc/containers/libpod.conf` under `cni_plugin_dir`) (also safe to assume `custom-cni` is functioning properly)

**Describe the results you received:**

Running `podman network ls` lists the `demo` network, but also shows a warning message:

```
WARN[0000] Error validating CNI config file /etc/cni/net.d/10-demo-custom-cni.conflist: [netplugin failed: "Error: missing field `name` at line 1 column 22\n"]
NETWORK ID    NAME        VERSION     PLUGINS
2f259bab93aa  podman      0.4.0       bridge,portmap,firewall,tuning
3ecee7bc9885  demo          0.4.0       custom-cni
```

Trying to run a container with that network also fails, as it appears that warning turns into a hard error.

```
 podman run --net=demo --rm -d docker.io/nginxdemos/hello:latest
WARN[0000] Error validating CNI config file /etc/cni/net.d/10-demo-custom-cni.conflist: [netplugin failed: "Error: missing field `name` at line 1 column 22\n"]
WARN[0000] Error validating CNI config file /etc/cni/net.d/10-demo-custom-cni.conflist: [netplugin failed: "Error: missing field `name` at line 1 column 22\n"]
ERRO[0000] error loading cached network config: network "demo" not found in CNI cache
WARN[0000] falling back to loading from existing plugins on disk
WARN[0000] Error validating CNI config file /etc/cni/net.d/10-demo-custom-cni.conflist: [netplugin failed: "Error: missing field `name` at line 1 column 22\n"]
ERRO[0000] Error tearing down partially created network namespace for container 76f09c099080ff4870cb95c8019e1751fc38688f4e39d70607c38b88317f1bb3: CNI network "demo" not found
Error: error configuring network namespace for container 76f09c099080ff4870cb95c8019e1751fc38688f4e39d70607c38b88317f1bb3: CNI network "demo" not found
```

**Describe the results you expected:**

The network is created, and control is handed to `custom-cni` to set up the namespace and interfaces for the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```
**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 1
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: vm4
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-30-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 267186176
  memTotal: 1013338112
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 19h 52m 42.6s (Approximately 0.79 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Troubleshooting yes, Podman 4.x no as our system at work uses official repositories which don't have that version yet.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The example above is running inside a LXD VM, but that seems unrelated to the problem at hand.

**Comment by mheon** [comment] 2022-05-25 14:59
Please try 4.0 - we did a full rewrite of our network stack in 4.x, which may have resolved the problem.

**Comment by kbknapp** [comment] 2022-05-25 15:31
The reason I think it's not that and that it's coming from somewhere in Podman (or related libs) is running the plugin manually works (i.e. if do `podman run --net=none ...` and then `cat /etc/cni/net.d/10-demo-custom-cni.conflist | CNI_COMMAND=ADD CNI_ARGS=... CNI_NETNS=... CNI_IFNAME=... /usr/local/lib/custom-cni`).

**Comment by Luap99** [comment] 2022-05-25 15:36
Also I do not think that using the full conflist for the plugin is correct, the cni lib will send a different config to the plugin not the original, check https://github.com/containernetworking/cni/blob/main/SPEC.md

I am closing this since the issue is not related to podman but fell free to continue the conversation.

**Closed by Luap99** 2022-05-25 15:36 UTC
Labels: kind/bug

**Comment by kbknapp** [comment] 2022-05-26 02:10
Just to close the loop it turned out it was the plugin expecting a field that shouldn't have been there. My test didn't catch it cause I was manually writing what I *thought* Podman was sending, not what it was actually sending. A quick `strace` to see what Podman was sending cleared it up.

I appreciate all those that took time out of their day to assist and make suggetions!
