### ISSUE TITLE
DNS: no servers could be reached in `rootless` network on WSL2

### ISSUE THREAD

**Issue by klesh** [containers/podman#18530] opened 2023-05-10 06:34 UTC
### Issue Description

I tried both `Podman Desktop for Window` and `Podman4.5 in WSL2`  in `rootless`  mode, the DNS just didn't seem to be working.
```
> podman network create hello
hello
> podman network inspect hello
[
     {
          "name": "hello",
          "id": "998d23d8b357df4017297226e458e56f57f36f5c8a53ac37552a157ffcef6338",
          "driver": "bridge",
          "network_interface": "podman2",
          "created": "2023-05-10T12:48:20.796574327+08:00",
          "subnets": [
               {
                    "subnet": "10.89.1.0/24",
                    "gateway": "10.89.1.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
> podman run --rm --network=hello busybox nslookup baidu.com
;; connection timed out; no servers could be reached
```

However, it seems find under `rootful` mode:
```
[klesh@klesh-laptop] /e/apt> sudo podman network inspect hello
[
     {
          "name": "hello",
          "id": "3edf7f49c8f5da8bf24b65ea53cdc768013d5eaf1bca366daa8c4c7af2eed6bf",
          "driver": "bridge",
          "network_interface": "podman1",
          "created": "2023-05-09T23:56:41.968028336+08:00",
          "subnets": [
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
[klesh@klesh-laptop] /e/apt> sudo podman run --rm --network=hello -it busybox nslookup baidu.com
Server:         10.89.0.1
Address:        10.89.0.1:53

Non-authoritative answer:

Non-authoritative answer:
Name:   baidu.com
Address: 39.156.66.10
Name:   baidu.com
Address: 110.242.68.66

[klesh@klesh-laptop] /e/apt>  
```

Am I missing sth?

### Steps to reproduce the issue

Steps to reproduce the issue
1. create network in `rootless` mode: `podman network create hello`
2. run `nslookup` for a valid domain: `podman run --rm --network=hello -it busybox nslookup baidu.com`

### Describe the results you received

 see error : `;; connection timed out; no servers could be reached`

### Describe the results you expected

recieve ip adddress of the given domain

### podman info output

```yaml
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.2
Git Commit:   75e3c12579d391b81d871fd1cded6cf0d043550a
Built:        Fri Apr 14 23:21:09 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.19.7
Built:        Fri Apr 14 23:42:56 2023
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment] 2023-05-10 09:29
Does rootless dns work when you run without a special network, i.e. use the default `--network slirp4netns`?

Could you also provide the output of `cat /etc/resolv.conf`, `podman unshare --rootless-netns  cat /etc/resolv.conf` and `podman run --rm --network=hello -it busybox cat /etc/resolv.conf`?

It would also help if you could try `podman unshare --rootless-netns nslookup ...`

**Comment by Luap99** [comment] 2023-05-10 10:45
Can you run `podman unshare --rootless-netns ip addr`, to me this sounds like the slirp4netns process died?
You could check `ps auxww | grep slirp4netns`. If that is the case I assume a reboot should fix it, `podman machine stop && podman machine start`

**Comment by klesh** [comment] 2023-05-10 13:32
I don't think so, the DNS in the rootless network never works, how can it be fixed by reboot?
```
[klesh@klesh-laptop] ~/P/m/lake (cloud|✔ )> podman unshare --rootless-netns ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tap0: <BROADCAST,UP,LOWER_UP> mtu 65520 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 3e:a1:17:d9:74:38 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.100/24 brd 10.0.2.255 scope global tap0
       valid_lft forever preferred_lft forever
    inet6 fd00::3ca1:17ff:fed9:7438/64 scope global dynamic mngtmpaddr
       valid_lft 86160sec preferred_lft 14160sec
    inet6 fe80::3ca1:17ff:fed9:7438/64 scope link
       valid_lft forever preferred_lft forever
3: podman4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 16:9b:f0:3b:29:bd brd ff:ff:ff:ff:ff:ff
    inet 10.89.3.1/24 brd 10.89.3.255 scope global podman4
       valid_lft forever preferred_lft forever
    inet6 fe80::60cb:aff:fe82:7e3f/64 scope link
       valid_lft forever preferred_lft forever
4: veth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master podman4 state UP group default qlen 1000
    link/ether 16:9b:f0:3b:29:bd brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::149b:f0ff:fe3b:29bd/64 scope link
       valid_lft forever preferred_lft forever
6: podman1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c6:b3:04:f8:ad:ef brd ff:ff:ff:ff:ff:ff
    inet 10.89.0.1/24 brd 10.89.0.255 scope global podman1
       valid_lft forever preferred_lft forever
    inet6 fe80::182f:5bff:fe32:ee94/64 scope link
       valid_lft forever preferred_lft forever
7: veth1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master podman1 state UP group default qlen 1000
    link/ether c6:b3:04:f8:ad:ef brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::c4b3:4ff:fef8:adef/64 scope link
       valid_lft forever preferred_lft forever
[klesh@klesh-laptop] ~/P/m/lake (cloud|✔ )> ps auxww | grep slirp4netns                                                                                            0.413s
klesh      767  0.0  0.0   6224  3288 ?        S    13:14   0:00 /usr/bin/slirp4netns --disable-host-loopback --mtu=65520 --enable-sandbox --enable-seccomp --enable-ipv6 -c -r 3 --netns-type=path /mnt/wslg/runtime-dir/netns/rootless-netns-402b7e8cbfdd4a658644 tap0
[klesh@klesh-laptop] ~/P/m/lake (cloud|✔ )>
```

**Comment by klesh** [comment] 2023-05-10 13:48
Looks like it is working, not sure though 😂
```
[klesh@klesh-laptop] ~/P/m/lake (cloud|✔ )> podman unshare --rootless-netns
Now using Node v16.19.0 (npm 8.19.3) ~/.local/nvm/v16.19.0/bin/node
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
[root@klesh-laptop] ~/P/m/lake (cloud|✔ )# nslookup baidu.com 172.31.144.1
Server:         172.31.144.1
Address:        172.31.144.1#53

Non-authoritative answer:
Name:   baidu.com
Address: 110.242.68.66
Name:   baidu.com
Address: 39.156.66.10
```

**Comment by klesh** [comment] 2023-05-10 13:51
Maybe it is conflicting with my other network? `10.0.2.3` is my `printer` ...

**Comment by klesh** [comment] 2023-05-10 16:04
I installed the latest `archlinux` with podman 4.5, same result:
```
[root@arch pacman.d]# podman run --rm busybox nslookup baidu.com
Server:         10.0.4.1
Address:        10.0.4.1:53

Non-authoritative answer:
Name:   baidu.com
Address: 39.156.66.10
Name:   baidu.com
Address: 110.242.68.66

Non-authoritative answer:

[root@arch pacman.d]# podman network create hello
hello
[root@arch pacman.d]# podman run --rm --network=hello busybox nslookup baidu.com
WARN[0001] aardvark-dns binary not found, container dns will not be enabled
;; connection timed out; no servers could be reached

nslookup: write to '10.89.0.1': Connection refused
```

**Comment by fuomag9** [comment] 2023-05-12 07:29
If this can be of help, `podman-2:4.4.1-3.el9.x86_64` is the packet that started giving me issues and I can’t resolve host names on the same network when using docker compose with podman. Downgrading the package resolved the issue

**Comment by Luap99** [comment] 2023-05-15 09:38
> If this can be of help, `podman-2:4.4.1-3.el9.x86_64` is the packet that started giving me issues and I can’t resolve host names on the same network when using docker compose with podman. Downgrading the package resolved the issue

This may or may not be related. I would need more info to tell. It sounds like https://github.com/containers/podman/issues/17499 and https://github.com/containers/podman/issues/17731 which is already fixed in v4.4.3.

**Comment by Timost** [comment] 2023-05-17 16:39
I'm hitting the same issue as @fuomag9  with the same use case (docker-compose with podman on ubuntu 22.04 in WSL2).

If it can help, I see the following logs on the podman service logs: `netavark: IO error: aardvark pid not found` (might be another issue with packaging)

**Comment by Timost** [comment] 2023-05-25 11:53
For anyone interested, I have been able to get podman rootless working with wsl2 using https://github.com/arkane-systems/bottle-imp on Ubuntu 22.04.

I tested this on a `docker-compose` + `podman` project with several services talking to each other within the same podman network. DNS resolution using container names also works.

I think this issue is linked to WSL2's rootless systemd setup being incomplete/imperfect (missing /run/user/.../bus among other things).

**Comment by klesh** [comment] 2023-06-25 04:12
> For anyone interested, I have been able to get podman rootless working with wsl2 using https://github.com/arkane-systems/bottle-imp on Ubuntu 22.04.
> 
> I tested this on a `docker-compose` + `podman` project with several services talking to each other within the same podman network. DNS resolution using container names also works.
> 
> I think this issue is linked to WSL2's rootless systemd setup being incomplete/imperfect (missing /run/user/.../bus among other things).

It would be great if anyone of the maintainers can take a look and comment 😊

**Comment by rhatdan** [comment] 2023-06-25 10:41
@n1hility PTAL

**Comment by sighoya** [comment] 2023-07-09 17:14
I have the same issue in rootless podman wsl2 mode.

I'm using nat bridging however and I'm in VPN.

cat /etc/resolv.conf in container yields:
```
search dns.podman
nameserver 10.89.0.1
```

sudo apt update or pinging archive.ubuntu.org yields timeouts.

However, changing the dns section to 8.8.8.8 make everything works as expected.
So the problem lies probably in the podman dns service itself.

**Comment by n1hility** [comment] 2023-07-13 04:05
@sighoya  WSL has known interoperability issues with VPN, since VPNs typically drop traffic from VM interfaces (which WSL uses) unless specially configured to allow it. Podman 4.6 has a user-mode networking feature that can be used to workaround these scenarios.  Allowing traffic to route extenrally and on the VPN. Changing the DNS manually to a public server will also work without this feature, as you did, in cases where the VPN does split routing. Although in the manual DNS fix case, it will likely still drop traffic destined to anything on the VPN.

**Comment by sighoya** [comment] 2023-07-13 17:01
@n1hility,

I wasn't aware of that and it is probably an issue but it seems docker on WSL on VPN doesn't have it. It's not that data packages are missing in general just that it takes too long to resolve the hostnames to ips and sometimes even result in a connection timeout but only for this kind of communication and not for general data transfer over VPN.

The workaround is unfortunately a bit rocky because it doesn't resolve internal ips anymore when disabling dns which is sad, I can't even add two dns entries as it seem to just be ignored.  

>Podman 4.6 has a user-mode networking feature that can be used to workaround these scenarios

Did you have a link how to use it, or is it the default now for podman 4.6?

**Comment by sighoya** [comment] 2023-07-13 18:03
Ah, I see: https://github.com/containers/podman/blob/v4.6/RELEASE_NOTES.md:

>The podman machine init and podman machine set commands now support a new option, --user-mode-networking, which improves interops with VPN configs that drop traffic from WSL networking, on Windows.

**Comment by sighoya** [comment] 2023-07-15 11:56
@n1hility,

I've tested it with podman 4.6 rc1 and it didn't solve anything using user networking just to say ( I even believe there are problems with port forarwding now).

Overwriting dns https://github.com/containers/podman/issues/17499 seems not possible anymore though you can add a second dns in a docker file.

Adding a second dns has the problem that first try to resolve an address is made by podman dns which takes 5s to switch to the latter dns which is a bottleneck regarding multiple tcp requests.
Changing the order of dns entries makes communication among the containers a bottleneck.
I mean we can shrink the timeout but that will inroduce new problems for ouside servers with bad response time.

So I think I will now use static ips for all containers and include a hosts file for all of them to be reachable by container names.

I would be very glad if you could fix the dns problem for the future. If it's a wsl problem, maybe reporting a bug there though I haven't any tools to proove that myself.

**Comment by Timost** [comment] 2023-07-18 09:23
Hi,

Dropping by, for an update since my [comment](https://github.com/containers/podman/issues/18530#issuecomment-1562771912) a few months ago. I've had no issue with podman on WSL.

I also have to use a corporate VPN which is broken by default on WSL.

My full setup is:
- WSL 2 with ubuntu 22.04 and systemd enabled
- [`bottle-imp` ](https://github.com/arkane-systems/bottle-imp) to have a proper rootless systemd in WSL
- [`wsl-vpnkit`] https://github.com/sakai135/wsl-vpnkit to have a working network on wsl when using the VPN
- podman 4.5.1

**Comment by n1hility** [comment] 2023-07-24 19:26
> @n1hility,
> 
> I've tested it with podman 4.6 rc1 and it didn't solve anything using user networking just to say ( I even believe there are problems with port forarwding now).

FYI, for those that are interested, 4.6.0 is now out. 

> 
> Overwriting dns #17499 seems not possible anymore though you can add a second dns in a docker file.

It sounded like you were having a general networking issue but perhaps this issue you are hitting is specific to an explicit container network.

Does the following work for you in rootless (no network specified) [with and without the user-mode networking machine]

```
podman run fedora curl www.google.com 
```

**Comment by n1hility** [comment] 2023-07-24 20:13
> Hi,
> 
> Dropping by for an update since my [comment](https://github.com/containers/podman/issues/18530#issuecomment-1562771912) a few months ago. I've had no issue with podman on WSL.
> 
> I also have to use a corporate VPN which is broken by default on WSL.
> 
> My full setup is:
> 
> * WSL 2 with ubuntu 22.04 and systemd enabled
> * [`bottle-imp` ](https://github.com/arkane-systems/bottle-imp) to have a proper rootless systemd in WSL
> * [`wsl-vpnkit`](https://github.com/sakai135/wsl-vpnkit) to have a working network on wsl when using the VPN
> * podman 4.5.1

You can certainly do a manual setup like this for podman customizing your own distro, but keep in mind that you wont get interop with Windows applications / CLI in this sort of setup, which for those that do everyhting on the WSL prompt this could be fine.

When you install stock podman on Windows, and use podman machine,  it sets up something very similar. It create a WSL instance with its own bootstrap of systemd (does not use the newer wsl2 native systemd). For the VPN capability 4.6  you can do `podman machine init --user-mode-networking` and it will create a machine instance that internally operates similar to wsl-vpnkit. You can also manually run wsl-vpkit as well if you prefer.

**Comment by yosiasz** [comment] 2023-08-10 17:09
any news on this, how does one resolve this? I am hitting a wall with this for nginx proxy/grafana pod
https://github.com/containers/podman/discussions/19569#discussioncomment-6693457

**Comment by reo-1963** [comment] 2023-08-10 22:05
Is it considered "cheating" if you pass the IPv4 of your Windows PC's DNS Server to the "podman run"?

In Windows CMD:
```
> nslookup baidu.com
Server:  hq-dc-1.canfield.hq
Address:  172.16.200.95

Non-authoritative answer:
Name:    baidu.com
Addresses:  110.242.68.66
          39.156.66.10
```
          
Which is all well and good on Windows. But it gives a clue as to the IPv4 of my nearest DNS Server.
Create a "podman network" with
`> podman network create hello`
and then run
```
> podman run --network hello --dns 172.16.200.95 -it busybox nslookup baidu.com

Server:         10.89.0.1
Address:        10.89.0.1:53

Non-authoritative answer:

Non-authoritative answer:
Name:   baidu.com
Address: 39.156.66.10
Name:   baidu.com
Address: 110.242.68.66
```

And I am running rootless. Or was that "cheating"?

**Comment by olee** [comment] 2023-08-11 13:26
> Is it considered "cheating" if you pass the IPv4 of your Windows PC's DNS Server to the "podman run"?

Thanks! That's actually the first working and also easy solution to this problem I found here!
With this I can at least continue development on my application until a proper solution is found.

**Comment by reo-1963** [comment] 2023-08-11 13:51
I may be newer to this community than you.
But a serious clue may be found in:
`podman network inspect podman`
It shows an entry in "network_dns_server" for me. So:
`podman network create --dns XX.YY.ZZ.AA hello`
(where you substitute XX.YY.ZZ.AA with whatever appears for the "network_dns_server" entry) may be the easiest "work around".

**Comment by n1hility** [comment] 2023-08-17 09:14
The underlying issue for this is caused by an incompatibility in slirp4netns with the resolv.conf symlinking approach in recent WSL versions.

I'm working on a proposed fix here:
https://github.com/rootless-containers/slirp4netns/pull/318

**Comment by Luap99** [comment] 2023-08-17 09:43
Thanks for taking a look @n1hility.

**Comment by n1hility** [comment] 2023-08-21 17:17
@Luap99 your welcome!

**Comment by n1hility** [comment] 2023-08-21 17:25
1.2.1 of slirp4netns was just release which includes this fix. 

Until this update lands in Fedora update streams you can manually install it doing the following:

1. podman machine ssh
2. sudo dnf remove slirp4netns
3. cd /usr/local/bin;  curl -o slirp4netns --fail -L https://github.com/rootless-containers/slirp4netns/releases/download/v1.2.1/slirp4netns-$(uname -m)
4. chmod +x /usr/local/bin/slirp4netns

Once it is available, you will be able to flip back by removing this executable and reinstalling the package. Alternatively you can re-create the machine instance at that time: `podman machine rm; podman machine init`

Other workarounds:

- As mentioned earlier in the thread you can explicitly set the dns when creating the network 
- You can also create the machine with user-mode-networking enabled, which is not affected by this issue

**Closed by n1hility** 2023-08-21 17:25 UTC
Labels: kind/bug, network, windows

**Comment by klesh** [comment] 2023-08-22 08:17
@n1hility Thank you so much for fixing the problem, it is working flawlessly on my local machine.
