### ISSUE TITLE
Configuration to reduce process clutter using podman remote

### ISSUE THREAD

**Issue by gmarcy** [containers/podman#13222] opened 2022-02-12 15:10 UTC
/kind feature

**Description**

I have been taking great advantage of the podman remote capability, and corresponding podman socket/service, using the podman connector for ansible.  This is much nicer than running remote ssh commands manually.  Many thanks for the work that has been done for this.

What I have noticed is that after my playbook has finished there can be in some cases hundreds of sleeping processes on the remote system whose child processes are long gone having only existed for a moment.  This appears to be done in the name of Docker compatibility.

The following code can be found in [pkg/api/handlers/compat/exec.go](https://github.com/containers/podman/blob/main/pkg/api/handlers/compat/exec.go#L74-L76)
```
        // Run the exit command after 5 minutes, to mimic Docker's exec cleanup
        // behavior.
        libpodConfig.ExitCommandDelay = 5 * 60
```

This is implemented in conmon [src/ctr_exit.c](https://github.com/containers/conmon/blob/main/src/ctr_exit.c#L201-L204) as
```
        if (opt_exit_delay) {
                ndebugf("Sleeping for %d seconds before executing exit command", opt_exit_delay);
                sleep(opt_exit_delay);
        }
```

I would like to request a feature to add some configuration to override the hard-wired code so that I could set a shorter delay in my podman systemd units, or in some similarly reasonable manner.  I am also wondering if this is even a behavior we want to mimic in this fashion.  Do we really need to do nothing for all that time?  Could we break out of the sleep when all the child processes are gone, poll in a loop with shorter sleeps, etc?

Thank you for your consideration of this request.

**Comment by rvandernoort** [comment] 2022-02-22 16:21
Hi there, this seems like a pretty good first issue to pick up, could we (student team) try to tackle this?

**Comment by mheon** [comment] 2022-02-22 16:26
Sure, feel free.

Modifications to containers.conf must begin in https://github.com/containers/common/tree/main/pkg/config - once that's done, wiring the change into the compat API endpoint shouldn't be that bad.

**Comment by rvandernoort** [comment] 2022-02-23 17:13
Thanks, so I started there and created the configuration knob. Now I face the next step changing exec to use the config like this
```
libpodConfig.ExitCommandDelay = runtimeConfig.Engine.ExitCommandDelay
```
but this gives me a error in make saying ExitCommandDelay is undefined. I tried to locally make common which is in the same rootdirectory as podman, but I'm guessing I'm missing some linking step. Do you perhaps have any suggestions?

**Comment by mheon** [comment] 2022-02-23 18:28
You'll need to update the vendor of c/common - once the change is committed to the containers/common repo, you can use `go get github.com/containers/common@<COMMIT HASH>` and then `make vendor-in-container` to finalize the vendoring and get the updated c/common into Podman.

**Comment by rvandernoort** [comment] 2022-03-02 11:47
Thanks for the clarification. The common updates seem to have merged already now and it now builds using the configuration, however I can't reproduce the behaviour of the changed value yet. I have added the configuration into `containers.conf` file in `/usr/share/containers` for both the client and server but that does not seem to work. Does the locally build version use another file perhaps?

**Comment by mheon** [comment] 2022-03-02 21:49
They should all use the same config files. I would recommend adding some debug prints to the c/common code in your local copy to see if the variable in the config file is being read in properly.

**Comment by rvandernoort** [comment] 2022-03-03 00:13
Alright, I will investigate more then

**Comment by rvandernoort** [comment] 2022-03-03 13:01
I managed to get it working now, don't really know what was going wrong, but when I debugged it it suddenly worked! Anyway PR is open and ready to close this issue.

**Closed** 2022-03-07 18:32 UTC
Labels: kind/feature, HTTP API
