### ISSUE TITLE
[Bug]: Failing to pull `ubuntu` (a manifast issue)

### ISSUE THREAD

**Issue by nadav-dav** [containers/podman#17312] opened 2023-02-01 15:35 UTC
### Issue Description

When calling `podman pull ubuntu` it fails for `Error: copying system image from manifest list: parsing image configuration: unsupported image-specific operation on artifact with type "application/vnd.docker.container.image.v1+json"`

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman pull ubuntu

### Describe the results you received

Error: copying system image from manifest list: parsing image configuration: unsupported image-specific operation on artifact with type "application/vnd.docker.container.image.v1+json"

### Describe the results you expected

For it to pull the image

### podman info output

```shell
host:
  arch: arm64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc37.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 99.65
    systemPercent: 0.23
    userPercent: 0.12
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "37"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.1.6-200.fc37.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1292746752
  memTotal: 2050191360
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-3.fc37.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.aarch64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 2h 34m 26.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 2269999104
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178831
  BuiltTime: Fri Nov 11 17:00:31 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/arm64
  Version: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Running on OSX

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by thestr4ng3r** [comment] 2023-02-01 15:39
Also reproduced here: https://builds.sr.ht/~thestr4ng3r/job/932446#task-appimage

**Comment by nadav-dav** [comment] 2023-02-01 15:46
More info
* On `Jan 31, 2023 at 7:27 pm` new ubuntu images were pushed to [dockerhub](https://hub.docker.com/_/ubuntu/tags) 
* `docker pull unbuntu:latest` works fine, but `podman pull unbuntu:latest` fails
* `podman pull unbuntu:14.04` works fine (updated 3 month ago)

**Comment by flouthoc** [comment] 2023-02-01 15:48
Please see: https://github.com/containers/buildah/issues/4551 , I am closing this since this is already discussed :)

**Closed by flouthoc** 2023-02-01 15:48 UTC
Labels: kind/bug, remote

**Comment by nadav-dav** [comment] 2023-02-01 15:52
@flouthoc Thank you :) I see that it was an issue specifically with ubuntu, [see reply here](https://github.com/docker-library/official-images/pull/13950#issuecomment-1411728853)
