### ISSUE TITLE
[ci]: ERROR: Releases must never contain '-dev' in output of 'podman info'  (contrib/cirrus/runner.sh:203 in _run_release())

### ISSUE THREAD

**Issue by zhangguanzhang** [containers/podman#8802] opened 2020-12-22 08:00 UTC
https://cirrus-ci.com/task/5650026892361728
https://github.com/containers/podman/pull/8793/checks?check_run_id=1592712174
@edsantiago PTAL

**Comment by edsantiago** [comment] 2021-01-07 13:07
Sorry for the delay, I was on PTO. I can't figure out what this is referring to? It seems like that PR is merged, so you must've figured out the cause?

**Comment by zhangguanzhang** [comment] 2021-01-08 01:13
> Sorry for the delay, I was on PTO. I can't figure out what this is referring to? It seems like that PR is merged, so you must've figured out the cause?

Before that, almost every step in pr will report an error, you can check the related issue of the link

**Comment by zhangguanzhang** [comment] 2021-01-13 02:11
related https://github.com/containers/podman/pull/8951

**Closed** 2021-01-13 13:02 UTC
