### ISSUE TITLE
/bin/sh: line 1: systemctl: command not found

### ISSUE THREAD

**Issue by quantum77** [containers/podman#20105] opened 2023-09-22 16:48 UTC
### Issue Description

$ podman image build -f plexmediaserver.imgbuild -t plex .
... fails with the above.  podman supports systemd but does not have systemctl.

### Steps to reproduce the issue

Steps to reproduce the issue
1. $ podman image build -f plexmediaserver.imgbuild -t plex .
STEP 1/9: FROM registry.opensuse.org/opensuse/tumbleweed
STEP 2/9: RUN echo && echo "**** Install extras ****"   && zypper in -y                 lsof            mawk            nano   && ln -s /usr/bin/mawk /usr/bin/awk
--> Using cache f1f5c5d9220f114fe5982d10bcb2d344caaf388fae877de8c8e680d0cd534e84
--> f1f5c5d9220f
STEP 3/9: COPY /plex.repo /etc/zypp/repos.d/
--> Using cache 513b559cc9f2e4f34c63fe36fdc215699b99e184cfc5a0c666898a0067db5de8
--> 513b559cc9f2
STEP 4/9: RUN   echo "systemd" > /proc/1/comm   && echo && echo "**** Install Plex repo ****"   && zypper --gpg-auto-import-keys ref    && zypper in -y                 plexmediaserver         && sed -i 's/User=plex//g' /usr/lib/systemd/system/plexmediaserver.service      && sed -i 's/Group=plex//g' /usr/lib/systemd/system/plexmediaserver.service
--> Using cache b1ced7e6e36e81ced3c6a57f14a2d72b7438377b556f166146771822ce046185
--> b1ced7e6e36e
STEP 5/9: RUN   systemctl daemon-reload
/bin/sh: line 1: systemctl: command not found
Error: building at STEP "RUN systemctl daemon-reload": while running runtime: exit status 127

2. $ cat plex.imgbuild
FROM registry.opensuse.org/opensuse/tumbleweed

RUN echo && echo "**** Install extras ****" \
        && zypper in -y \
                lsof \
                mawk \
                nano \
        && ln -s /usr/bin/mawk /usr/bin/awk

COPY /plex.repo /etc/zypp/repos.d/

        # Fake out the PMS install script to make it think systemd:
RUN     echo "systemd" > /proc/1/comm \

        && echo && echo "**** Install Plex repo ****" \

        && zypper --gpg-auto-import-keys ref \
        && zypper in -y \
                plexmediaserver \

        # Remove 'plex' user:group so Plex runs as root (bill) to get all dirs
        && sed -i 's/User=plex//g' /usr/lib/systemd/system/plexmediaserver.service \
        && sed -i 's/Group=plex//g' /usr/lib/systemd/system/plexmediaserver.service

RUN     systemctl daemon-reload
RUN systemctl enable plexmediaserver.service

RUN   echo && echo "**** Cleanup ****" \
  && rm -rf \
        $HOME/.cache \
        /tmp/* \
        /var/tmp/* \

  && echo && echo "**** Expose Port ****"
# 32400/tcp PM Server, 1900/udp/32469/tcp Plex DLNA Server, 32410/32412/32413/32414/udp GDM network discovery
EXPOSE 32400/tcp

CMD [ "/usr/lib/systemd/systemd" ]

### Describe the results you received

build crashes with "/bin/sh: line 1: systemctl: command not found"

I've asked on IRC but nobody's there.

### Describe the results you expected

Expected the image to build properly.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.3
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: 3c1e4548e778d692b2b7c2848d83708223a148b9'
  cpuUtilization:
    idlePercent: 90.04
    systemPercent: 1.59
    userPercent: 8.37
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: '"centos"'
    version: "9"
  eventLogger: file
  freeLocks: 2011
  hostname: aquarius.darkmtter.org
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-331.el9.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 2771017728
  memTotal: 16504016896
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.5.0-2.el9.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.5.0
    package: netavark-1.5.0-2.el9.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.5.0
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-3.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 2202005504
  swapTotal: 2202005504
  uptime: 67h 26m 42.00s (Approximately 2.79 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  127.0.0.1:5000:
    Blocked: false
    Insecure: true
    Location: 127.0.0.1:5000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: 127.0.0.1:5000
    PullFromMirror: ""
  search:
  - registry.opensuse.org
  - registry.suse.com
  - docker.io
store:
  configFile: /home/carl/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/carl/.local/share/containers/storage
  graphRootAllocated: 50382532608
  graphRootUsed: 12322877440
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 14
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/carl/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.1
  Built: 1692961071
  BuiltTime: Fri Aug 25 03:57:51 2023
  GitCommit: ""
  GoVersion: go1.20.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

**Comment by nalind** [comment] 2023-09-22 18:17
It's not finding the binary of `systemctl` to run.  Near as I can tell, the base image doesn't include that command, because it doesn't have systemd installed in it.

**Comment by quantum77** [comment] 2023-09-22 18:36
Understand, but podman is supposed to have systemd support, meaning it adds the binaries on-the-fly.  As I can not get an image built nor a container started, I can't check for this.

podman should automatically add systemctl since it's advertised to have systemd support and since I call for it in CMD..

**Comment by nalind** [comment] 2023-09-22 19:30
That is not what supporting systemd means.  Running systemd in a container requires that the process of starting a container at run time be done a bit differently from how it would otherwise be done.
The build process for images does not add content to them as a side-effect of a CMD instruction.

**Comment by quantum77** [comment] 2023-09-22 19:34
So you're saying that built-in support of systemd is no good if you need to start a service within the container with systemd.

I don't understand what then was the rationale for adding -any- systemd...  if in fact it was added?

**Comment by nalind** [comment] 2023-09-22 19:49
Certain things need to be done differently if the main process for the container is an init system, such as systemd, which will itself be starting and managing multiple services within that container.

When booting in a VM or on bare metal, systemd expects to be mounting filesystems and doing mundane things like seeding the system random number generator, and the correct thing to do when any of that fails (as it would in a container which doesn't allow any of that) is to either fail completely or drop to a recovery shell.  When it's running in a container, it depends on the engine that started the container to take care of certain things on its behalf, and it, in turn, needs to be given some indication that it can and should skip these things.  That is what part of what it means for podman to support running systemd in a container.

Getting the systemd binaries into a container image while it's being built, in particular binaries that are built for the right architecture and linked against the shared libraries that are also going to be in that image, along with their dependencies, is something that has to be done using ADD, COPY, or RUN.

**Comment by quantum77** [comment] 2023-09-22 19:59
Ok so systemd support in podman does not actually include the binaries necessary to start services within the container.

So assuming that adding the systemd package to the image, tis will -not- interfere with whatever mechanisms of systemd are built into podman.   So my new imgbuild is as so:
FROM registry.opensuse.org/opensuse/tumbleweed

RUN echo && echo "**** Install extras ****" \
        && zypper in -y \
#               iptables-backend-nft \
                lsof \
                mawk \
                nano \
                systemd \
        && ln -s /usr/bin/mawk /usr/bin/awk

COPY /plex.repo /etc/zypp/repos.d/

        # Fake out the PMS install script to make it think systemd:
RUN     echo "systemd" > /proc/1/comm \

        && echo && echo "**** Install Plex repo ****" \

        && zypper --gpg-auto-import-keys ref \
        && zypper in -y \
                plexmediaserver \

        # Remove 'plex' user:group so Plex runs as root (bill) to get all dirs
        && sed -i 's/User=plex//g' /usr/lib/systemd/system/plexmediaserver.service \
        && sed -i 's/Group=plex//g' /usr/lib/systemd/system/plexmediaserver.service


RUN     systemctl daemon-reload
RUN systemctl enable plexmediaserver.service

RUN   echo && echo "**** Cleanup ****" \
  && rm -rf \
        $HOME/.cache \
        /tmp/* \
        /var/tmp/* \

  && echo && echo "**** Expose Port ****"
# 32400/tcp PM Server, 1900/udp/32469/tcp Plex DLNA Server, 32410/32412/32413/32414/udp GDM network discovery
EXPOSE 32400/tcp

#RUN echo && echo "**** Set volume ****"
#VOLUME /var/lib/plexmediaserver/
# /srv/cygnus/ /srv/vela/complete/

#RUN echo "" && echo "**** force library dependencies ****" && \
#export LD_LIBRARY_PATH=/lib #required to use /lib/ld-musl.x86_64.so instead of Plex's version && \
#export LD_PRELOAD=/usr/lib/libva.so.2:/usr/lib/plexmediaserver/lib/libssl.so.3:/usr/lib/plexmediaserver/lib/libcrypto.so.3 #us>

CMD [ "/usr/lib/systemd/systemd" ]
======================================================
$ podman image build -f plexmediaserver.imgbuild -t plex .
STEP 1/9: FROM registry.opensuse.org/opensuse/tumbleweed
STEP 2/9: RUN echo && echo "**** Install extras ****"   && zypper in -y                 lsof            mawk            nano   systemd  && ln -s /usr/bin/mawk /usr/bin/awk
--> Using cache 7f419035e458bd3a22ed7b0b5a246247be3857c6766b8a616e9a76925e0e41e9
--> 7f419035e458
STEP 3/9: COPY /plex.repo /etc/zypp/repos.d/
--> Using cache af9bac09d2e81391f01d52a7a399b45f75dabc7f9098f009a0fe4390442f32ef
--> af9bac09d2e8
STEP 4/9: RUN   echo "systemd" > /proc/1/comm   && echo && echo "**** Install Plex repo ****"   && zypper --gpg-auto-import-keys ref    && zypper in -y                 plexmediaserver         && sed -i 's/User=plex//g' /usr/lib/systemd/system/plexmediaserver.service      && sed -i 's/Group=plex//g' /usr/lib/systemd/system/plexmediaserver.service
--> Using cache af0f965a44406894ffc8423171e7687d5f2afe9e2367ac65e19b7f94a0de82e4
--> af0f965a4440
STEP 5/9: RUN   systemctl daemon-reload
error running container: from /usr/bin/crun creating container for [/bin/sh -c systemctl daemon-reload]: sd-bus call: Process org.freedesktop.systemd1 exited with status 1: Input/output error
: exit status 1
ERRO[0000] did not get container create message from subprocess: EOF 
Error: building at STEP "RUN systemctl daemon-reload": while running runtime: exit status 1

**Comment by quantum77** [comment] 2023-09-22 20:01
Oh what a mess this forum makes of code...

**Comment by nalind** [comment] 2023-09-22 20:17
Changing the recorded command which was used to launch the shell for a RUN instruction is not a substitute for having an init system.  But then if there isn't an init system running (and running processes don't persist across instructions during a build), it doesn't need to be told to reload its configuration when the files which contain that configuration are modified.

**Comment by quantum77** [comment] 2023-09-22 21:45
Huh?

**Comment by rhatdan** [comment] 2023-09-23 14:17
First you need to install into the container systemd and its tools, podman does not automatically add them to containers, it only executes code installed into the container.  The `podman run` command when seeing a CMD of systemd, will configure the container environment in a way that systemd likes.

You are doing  a podman build not a podman run. In the Build steps each command is a separate container only running that command.  Systemd would not be running inside of the RUN container, so `systemctl daemon-reload` will fail. However this line is not even needed, since when systemd starts it automatically does a daemon reload.

**Comment by quantum77** [comment] 2023-09-23 15:36
Maybe these are things that should be mentioned in the docs.  It may be self-evident to devs, but is a knowledge-gap and show-stopper for others.

**Comment by baude** [comment] 2023-09-24 15:06
would you care to create a PR?

**Comment by quantum77** [comment] 2023-09-24 18:21
Github is one of those things I've sworn I will never learn...  like fixing automatic transmissions.

I am preparing to start a wiki though with all the painful struggles I've had and lessons learned in the Black Arts of cantankerous podman.

**Comment by rhatdan** [comment] 2023-09-24 23:10
Well you are welcome to try your luck with other container technology like Docker, but you are going to find the same issues.  Since this is not a bug I am going to close it.

**Closed by rhatdan** 2023-09-24 23:10 UTC
Labels: kind/bug

**Comment by quantum77** [comment] 2023-09-24 23:28
I see.  So this is your attitude.

Well in that case it's not worth it to set up a wiki on podman explaining all the gaps in knowledge and filling them in.  I have better things to do.
