### ISSUE TITLE
podman-remote: Cannot build if context directory is symlink

### ISSUE THREAD

**Issue by tnk4on** [containers/podman#12409] opened 2021-11-24 20:52 UTC
**Description**

When building with podman-remote, an error occurs if the context directory is symlink.

**Steps to reproduce the issue:**

If the context directory is symlink.
```
# tree
.
├── test
│   └── Containerfile
└── test2 -> test/

2 directories, 1 file

# cd test2; pwd
/root/build-test/test2
# podman -r build -t test2 .
Error: stat /var/tmp/libpod_builder630693276/build/root/build-test/test2/Containerfile: no such file or directory
```

If the context directory is a real directory.
```
# cd ../test; pwd
/root/build-test/test
# podman -r build -t test .
STEP 1/2: FROM registry.access.redhat.com/ubi8/ubi
STEP 2/2: RUN uname -a
Linux b20a3e8238f9 5.14.18-300.fc35.x86_64 containers/buildah#1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
COMMIT test
--> 88f8a6e2a4a
Successfully tagged localhost/test:latest
88f8a6e2a4ad0b6f24db25431dffb828a8c1c5fa81ac5aa760e1ce4d3e58b176
```
Additional notes:
I reproduced the same error on macOS remote client(v3.4.2 and latest main branch).
This error will block the execution of "[Clone Repository in Container Volume](https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume)" in VS Code on macOS. It works fine when using Docker.

**Output of `podman version` if reporting a `podman build` issue:**
```
# podman -r version
Client:
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.16.8
Git Commit:   93138541f3119b81c170e5ce904a8c4e6cece842
Built:        Thu Nov 25 03:56:42 2021
OS/Arch:      linux/amd64

Server:
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.16.8
Git Commit:   93138541f3119b81c170e5ce904a8c4e6cece842
Built:        Thu Nov 25 03:56:42 2021
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**
```
# cat /etc/*release
Fedora release 35 (Thirty Five)
NAME="Fedora Linux"
VERSION="35 (Server Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
Fedora release 35 (Thirty Five)
Fedora release 35 (Thirty Five)
```

**Output of `uname -a`:**
```
# uname -a
Linux fedora-1 5.14.18-300.fc35.x86_64 containers/buildah#1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
```
# cat /etc/containers/storage.conf
# This file is is the configuration file for all tools
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

# Storage path for rootless users
#
# rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to the UIDs/GIDs as they should appear outside of the container,
# and the length of the range of UIDs/GIDs.  Additional mapped sets can be
# listed and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and then a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped in-container ID,
# until all of the entries have been used for maps.
#
# remap-user = "containers"
# remap-group = "containers"

# Root-auto-userns-user is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid and /etc/subgid file.  These ranges will be partitioned
# to containers configured to create automatically a user namespace.  Containers
# configured to automatically create a user namespace can still overlap with containers
# having an explicit mapping set.
# This setting is ignored when running as rootless.
# root-auto-userns-user = "storage"
#
# Auto-userns-min-size is the minimum size for a user namespace created automatically.
# auto-userns-min-size=1024
#
# Auto-userns-max-size is the minimum size for a user namespace created automatically.
# auto-userns-max-size=65536

[storage.options.overlay]
# ignore_chown_errors can be set to allow a non privileged user running with
# a single UID within a user namespace to run containers. The user can pull
# and use any image even those with multiple uids.  Note multiple UIDs will be
# squashed down to the default uid in the container.  These images will have no
# separation between the users in the container. Only supported for the overlay
# and vfs drivers.
#ignore_chown_errors = "false"

# Inodes is used to set a maximum inodes of the container image.
# inodes = ""

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
#mount_program = "/usr/bin/fuse-overlayfs"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev,metacopy=on"

# Set to skip a PRIVATE bind mount on the storage home directory.
# skip_mount_home = "false"

# Size is used to set a maximum size of the container image.
# size = ""

# ForceMask specifies the permissions mask that is used for new files and
# directories.
#
# The values "shared" and "private" are accepted.
# Octal permission masks are also accepted.
#
#  "": No value specified.
#     All files/directories, get set with the permissions identified within the
#     image.
#  "private": it is equivalent to 0700.
#     All files/directories get set with 0700 permissions.  The owner has rwx
#     access to the files. No other users on the system can access the files.
#     This setting could be used with networked based homedirs.
#  "shared": it is equivalent to 0755.
#     The owner has rwx access to the files and everyone else can read, access
#     and execute them. This setting is useful for sharing containers storage
#     with other users.  For instance have a storage owned by root but shared
#     to rootless users as an additional store.
#     NOTE:  All files within the image are made readable and executable by any
#     user on the system. Even /etc/shadow within your image is now readable by
#     any user.
#
#   OCTAL: Users can experiment with other OCTAL Permissions.
#
#  Note: The force_mask Flag is an experimental feature, it could change in the
#  future.  When "force_mask" is set the original permission mask is stored in
#  the "user.containers.override_stat" xattr and the "mount_program" option must
#  be specified. Mount programs like "/usr/bin/fuse-overlayfs" present the
#  extended attribute permissions to processes within containers rather then the
#  "force_mask"  permissions.
#
# force_mask = ""

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# metadata_size is used to set the `pvcreate --metadatasize` options when
# creating thin devices. Default is 128k
# metadata_size = ""

# Size is used to set a maximum size of the container image.
# size = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

**Comment by flouthoc** [comment] 2021-11-25 09:27
@tnk4on I don't think this a buildah issue it seems to be failing at very early level hence moving it to podman. I don't have a `remote` setup but sharing `--log-level=debug` could be helpful.

**Comment by Luap99** [comment] 2021-11-25 09:44
I think this already fixed in the main branch, see https://github.com/containers/podman/issues/11732

**Comment by tnk4on** [comment] 2021-11-25 17:28
@flouthoc Thank you for moving the issue!
The debug log is below.
```
$ podman --log-level debug -r build -t test2 .
INFO[0000] podman filtering at log level debug
DEBU[0000] Called build.PersistentPreRunE(podman --log-level debug -r build -t test2 .)
DEBU[0000] SSH Ident Key "/root/.ssh/id_ecdsa" SHA256:7DMAeeupk5yNBFP/DOVVtKFKn21/uJwLBTZht9JjWz4 ecdsa-sha2-nistp256
DEBU[0000] DoRequest Method: GET URI: http://d/v4.0.0/libpod/_ping
DEBU[0000] SSH Ident Key "/root/.ssh/id_ecdsa" SHA256:7DMAeeupk5yNBFP/DOVVtKFKn21/uJwLBTZht9JjWz4 ecdsa-sha2-nistp256
DEBU[0000] DoRequest Method: GET URI: http://d/v4.0.0/libpod/_ping
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0000] DoRequest Method: POST URI: http://d/v4.0.0/libpod/build
Error: stat /var/tmp/libpod_builder150168969/build/root/build-test/test2/Containerfile: no such file or directory
```

**Comment by tnk4on** [comment] 2021-11-25 17:58
@Luap99 Thanks for the information on the related issue.
As far as I've tried on my macOS, this issue doesn't seem to be fixed...

**Comment by Luap99** [comment] 2021-11-25 18:04
The path is slightly different between your error and the old one:
`/var/tmp/libpod_builder150168969/build/root/build-test/test2/Containerfile` while the old one was `/var/tmp/libpod_builder324688225/build/Dockerfile`. I guess the problem is the extra `root/build-test/test2` in the path.

**Comment by tnk4on** [comment] 2021-11-25 18:10
Sorry for the confusion. 
The debug log was re-fetched from the newly created Podman environment. It is reproducible.

**Comment by Luap99** [comment] 2021-11-25 18:16
No I am saying your path is different from the one in the old issue #11732, you have a extra `root/build-test/test2` in there

Can you try with the full path to the directory, e.g. `podman -r build -t test2 /path/to/link`

**Comment by tnk4on** [comment] 2021-11-25 18:44
OK, I understand. I was able to build it by specifying the path.
```
# podman -r build -t test2 /root/build-test/test2
STEP 1/2: FROM registry.access.redhat.com/ubi8/ubi
STEP 2/2: RUN uname -a
Linux b20a3e8238f9 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
COMMIT test2
--> a27bd92387e
Successfully tagged localhost/test2:latest
a27bd92387e278cbf840d9c7c3e4af69eda5cca00573c9d1e49441d50e12d83c
```
The Linux version of podman-remote seems to be fine.

**Comment by tnk4on** [comment] 2021-11-25 19:12
On macOS, the error continues.
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.6.1
BuildVersion:	20G224

$ ls -l /tmp
lrwxr-xr-x@ 1 root  wheel  11  1  1  2020 /tmp -> private/tmp
$ tree /tmp/test
/tmp/test
└── Containerfile

0 directories, 1 file

$ podman version
Client:
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.2
Git Commit:   ed83ef2517ba4d6a0c7659206fe3a2faa0bdf547
Built:        Tue Nov 23 04:29:35 2021
OS/Arch:      darwin/amd64

Server:
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.16.8
Git Commit:   7324d94648a9987b0de2dc95cf1b6fbc20592532
Built:        Fri Nov 26 02:13:03 2021
OS/Arch:      linux/amd64

$ podman build -t from-mac /tmp/test/
Error: stat /var/tmp/libpod_builder009900604/build/tmp/test/Containerfile: no such file or directory

$ podman build -t from-mac /private/tmp/test/
STEP 1/2: FROM registry.access.redhat.com/ubi8/ubi
STEP 2/2: RUN uname -a
Linux b20a3e8238f9 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
COMMIT from-mac
--> 5b99ea27313
Successfully tagged localhost/from-mac:latest
5b99ea27313b9ab2f8af67e89e5a4cb482114dcced6df6b15c33b463ecf63e7c
```

**Comment by tnk4on** [comment] 2021-11-26 21:56
The following code solved the problem. This works not only for macOS, but also for podman-remote on Linux
```
$ git diff pkg/bindings/images/build.go
diff --git a/pkg/bindings/images/build.go b/pkg/bindings/images/build.go
index 3b0bebe9f..6e636aa7c 100644
--- a/pkg/bindings/images/build.go
+++ b/pkg/bindings/images/build.go
@@ -345,6 +345,13 @@ func Build(ctx context.Context, containerFiles []string, options entities.BuildO
                        }
                        c = tmpFile.Name()
                }
+
+               cfDir := filepath.Dir(c)
+               if absDir, err := filepath.EvalSymlinks(cfDir); err == nil {
+                       name := filepath.ToSlash(strings.TrimPrefix(c, cfDir+string(filepath.Separator)))
+                       c = filepath.Join(absDir,name)
+               }
+
                containerfile, err := filepath.Abs(c)
                if err != nil {
                        logrus.Errorf("Cannot find absolute path of %v: %v", c, err)
```

**Closed** 2021-12-02 09:30 UTC
Labels: kind/bug, remote
