### ISSUE TITLE
Explicit --build-arg causing all stages to ignore cache

### ISSUE THREAD

**Issue by agoose77** [containers/podman#9636] opened 2021-03-05 09:39 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When building a large Dockerfile, I noticed that `podman build` was failing to cache earlier layers. In this reproducer, passing `--build-arg` with the default value causes all of the build stages to be re-run.

However, it does *not seem* that the cache is invalidated; subsequent layers state that the cache was used.

**Steps to reproduce the issue:**
1. Run `podman build . --build-arg="PYTHON_VERSION=3.8.5"` with this Dockerfile:
    ```
    FROM centos:centos7 as builder
    
    RUN echo "i am a no op $(date -u)"
    RUN echo "i am also a no op $(date -u)"
  	    
    ARG PYTHON_VERSION=3.8.5
    RUN echo "I have been executed with [${PYTHON_VERSION}]"
    RUN echo "i am still a no op $(date -u)"

    ```

2. Run  `podman build . --build-arg="PYTHON_VERSION=3.8.5"` again

**Describe the results you received:**
The first build produces the following output: 
[out-0.txt](https://github.com/containers/buildah/files/6090290/out-0.txt)

The subsequent build produces this output instead: 
[out-1.txt](https://github.com/containers/buildah/files/6090291/out-1.txt)

**Describe the results you expected:**
In `out-1.txt`, I expected to see only cache messages. Instead the newly executed RUN command outputs are visible, with different date-times to the original build.

**Additional information you deem important (e.g. issue happens only occasionally):**
* I'm using the Ubuntu 20.04 `.deb` from https://build.opensuse.org/package/live_build_log/devel:kubic:libcontainers:stable/podman/xUbuntu_20.04/x86_64
* This doesn't happen when using `buildah bud --layers`.

**Output of `podman version`:**

```
podman version 3.0.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.26, commit: '
  cpus: 12
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: angus-desktop
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.0-44-generic
  linkmode: dynamic
  memFree: 679563264
  memTotal: 16710430720
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.18.1-7931a-dirty
      commit: 7931a1eab0590eff4041c1f74e2844b297c31cea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 29599461376
  swapTotal: 30516703232
  uptime: 25h 5m 34.86s (Approximately 1.04 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/angus/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/angus/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 216
  runRoot: /run/user/1000/containers
  volumePath: /home/angus/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.0.1-2 amd64 [installed]
podman/unknown 100:3.0.1-2 arm64
podman/unknown 100:3.0.1-2 armhf
podman/unknown 100:3.0.1-2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by TomSweeneyRedHat** [comment] 2021-03-06 00:34
@umohnani8 could you take a peak?

**Comment by AnsgarKlein** [comment] 2021-03-15 20:38
@agoose77 Are you sure `--build-arg` is even necessary to trigger this bug?

Testing with the following Dockerfile:
```
FROM ubuntu:18.04
ARG EXAMPLE=yesplease
RUN echo "Not using cache..."
```

for me `buildah bud --layers -f - < Dockerfile` will use caching as expected but `podman build --layers -f - < Dockerfile` will **always** execute the RUN command.

I'm running podman 3.0.1 and buildah 1.19.6 (Fedora 33) and I am quite sure that this behaviour is new and layer caching with ARG worked for me not too long ago.

**Comment by agoose77** [comment] 2021-03-16 07:49
I have since found that the build arg flag isn't required to trigger this bug.

**Comment by umohnani8** [comment] 2021-03-16 15:14
This was a regression in buildah 1.19.4 and has since been fixed in buildah 1.19.6. Can you please try again with podman v3.1.0-rc1, which has the fixed buildah.

**Comment by rhatdan** [comment] 2021-03-17 14:30
Since we believe this is fixed in the main branch, I am closing.

**Closed by rhatdan** 2021-03-17 14:30 UTC
Labels: kind/bug

**Comment by agoose77** [comment] 2021-03-17 15:02
Thanks for the efforts everyone. I'm waiting on the suse repository for a pre-built package and then I can confirm, but it makes sense that this would be fixed - I hadn't realised that podman vendored (?) an older buildah.

**Comment by socketpair** [comment] 2021-04-01 10:41
@agoose77 please rename the issue to something like `Podman does not use cache`

**Comment by samskiter** [comment] 2022-09-28 15:22
I believe this issue may have regressed. I have been finding a lot of issues with caching in https://github.com/containers/podman/issues/15887

**Comment by sanmai-NL** [comment] 2022-11-23 18:30
@rhatdan: [here](https://gitlab.com/han-aim/lern/-/jobs/3370942280#L48)'s a trace where the remote cache is somehow missed once `ARG` comes into play, even with a constant and default value across build runs.

**Comment by rhatdan** [comment] 2022-11-28 21:53
@flouthoc PTAL

**Comment by yellowhat** [comment] 2023-03-06 11:00
I am having a similar problem, seems that I solved using the `--cache-to` and `--cache-from` argument.

For example

```
$ cat Dockerfile
FROM registry.fedoraproject.org/fedora:37

ARG BASH_COMPLETION_VER='2.11'

RUN dnf install -y "bash-completion-$BASH_COMPLETION_VER"

CMD ["/bin/bash"]

HEALTHCHECK --interval=30s --timeout=30s --retries=3 CMD pgrep bash
```

Gitlab CI pipeline

```yaml
---
stages:
  - publish

publish:
  stage: publish
  image:
    name: quay.io/podman/stable:v4.4.2
    entrypoint: [""]
  before_script:
    - podman login
          --username "$CI_REGISTRY_USER"
          --password "$CI_REGISTRY_PASSWORD"
          "$CI_REGISTRY"
  script:
    - podman build
          --layers
          --cache-to "$CI_REGISTRY_IMAGE"
          --cache-from "$CI_REGISTRY_IMAGE"
          --file "Dockerfile"
          --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
          --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
          --tag "${CI_REGISTRY_IMAGE}:latest"
          .
    - podman push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
    - podman push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    - podman push "${CI_REGISTRY_IMAGE}:latest"
```
