### ISSUE TITLE
podman pull 403 forbiden with region blocked ip

### ISSUE THREAD

**Issue by jgato** [containers/podman#12395] opened 2021-11-23 11:43 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I was having problems pulling a docker image, and the only info I get was:

```
 podman  pull --all-tags --authfile pull-secret.json quay.io/openshift-release-dev/ocp-release:4.9.8-aarch64
Getting image source signatures
Error: reading blob sha256:aeb7866.....b3bf7: Error fetching blob: invalid status code from registry 403 (Forbidden)
```

**Describe the results you received:**

This only happens from my laptop (home network). But I could pull other images from other registries. It is not a real authentication problem, I have checked it well. The same pull with the same auth works in other hosts. So, it was a problem in my netowrk
After several tries I tried the same using docker and I discovered more information about the error:
```
Not continuing with pull after error: error pulling image configuration: denied: The region from which you are pulling has been geo-ip blocked. Please contact the namespace owner. 
```

**Describe the results you expected:**
Maybe podman would also give more details. Because it is not just a 403 error, it is a problem with my network ip and my ISP. The error from docker command is much more clear and it can help you to solve your connectivity problem.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "34"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.14-200.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 475824128
  memTotal: 33399881728
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 3639468032
  swapTotal: 8589930496
  uptime: 21h 50m 31.49s (Approximately 0.88 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/jgato/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/jgato/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/jgato/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.1
  Built: 1634740528
  BuiltTime: Wed Oct 20 16:35:28 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.1-1.fc34.x86_64

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment] 2021-11-25 14:54
@vrothberg @mtrmac PTAL I assume this must be fixed in c/image.

**Comment by mtrmac** [comment] 2021-11-25 15:03
Note to self: Looks like `GetBlob` should call `registryHTTPResponseToError`, not just `httpResponseToError`.

**Comment by jgato** [comment] 2021-11-26 09:38
@mtrmac how do I test that change?

**Comment by jgato** [comment] 2021-11-26 15:17
Maybe this would help. I took the blob image from podman output and tried to download just with Firefox.

```
HTTP Response headers
HTTP/2 403 Forbidden
server: nginx/1.12.1
date: Fri, 26 Nov 2021 15:09:47 GMT
content-type: application/json
content-length: 154
vary: Cookie
set-cookie: session=.eJxtkg.YaD4uw.vC1XHikoJ82E1F6kT2iyzNURfKM; Expires=Mon, 27-Dec-2021 15:09:47 GMT; Secure; HttpOnly; Path=/; SameSite=Lax
X-Firefox-Spdy: h2
```

```
HTTP Request headers
GET /v2/openshift-release-dev/ocp-release/blobs/sha256:40c264676.....103aeac4b HTTP/2
Host: quay.io
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: session=.eJx.......wo; quay.loggedin=true; quay.credentialsTab=cred-secret; quay.namespace=jgato
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
DNT: 1
Sec-GPC: 1
Cache-Control: max-age=0
TE: trailers
```

**Comment by jgato** [comment] 2022-01-11 16:10
I can confirm the real problem was an IP Region Ban. The Docker command info was very precise.

After checking with quay.io team, I have solved the issue of my ip region ban because of an outdated DDBB. But I still think that podman returned error would be more clear. Forbidden 403 make you think on accessing a privated repo, or credentials... But the real problem is a region ban problem. Docker command returns a more clear error, which what it helped me to solve the problem .

**Comment by rhatdan** [comment] 2022-02-14 18:26
@mtrmac was this ever fixed?

**Comment by mtrmac** [comment] 2022-02-14 19:25
See the state of the linked PR.

**Comment by flavianmissi** [comment] 2022-04-20 09:24
we're seeing this on [quay](https://issues.redhat.com/browse/PROJQUAY-3590) as well - let me know if I can help with testing.

**Comment by mtrmac** [comment] 2022-10-12 21:55
It’s fairly likely that #15662 will fix this, but I don’t have a way to test that.

Can someone who is experiencing this try Podman with that PR, please?

And for our test suite, it would be useful to have a capture of the failing request (headers at least, make sure to drop any credentials) and the failing response (_both_ headers and body).

**Comment by flavianmissi** [comment] 2023-06-19 14:21
I'm not longer working closely with the Quay team, but I pinged their QE about this @vrothberg. Will let you know what they find.

**Comment by vrothberg** [comment] 2023-06-20 06:25
That's very kind. Thank you, @flavianmissi !

**Comment by flavianmissi** [comment] 2023-06-20 07:49
Got [a reply from QE](https://issues.redhat.com/browse/PROJQUAY-3590?focusedId=22485034&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22485034)
Looks like they can no longer reproduce the issue.

**Closed** 2023-06-20 07:53 UTC
Labels: kind/bug
