### ISSUE TITLE
Directory structure of the podman-remote linux tarball is not consistent in 4.4.x releases

### ISSUE THREAD

**Issue by cfergeau** [containers/podman#18434] opened 2023-05-03 08:40 UTC
### Issue Description

Directory structure of the podman-remote linux tarball (https://github.com/containers/podman/releases/download/v4.4.4/podman-remote-static-linux_amd64.tar.gz) changed several times during the 4.4.x cycle. Sometimes the tarball contains a `bin/podman-remote` binary, sometimes the `bin/` directory is not there.
This makes it inconvenient to consume from crc: https://github.com/crc-org/snc/issues/707

### Steps to reproduce the issue

Steps to reproduce the issue
1. Download https://github.com/containers/podman/releases/download/v4.4.4/podman-remote-static-linux_amd64.tar.gz
2. Check the archive content
3. Compare with 1. Download https://github.com/containers/podman/releases/download/v4.4.3/podman-remote-static-linux_amd64.tar.gz

### Describe the results you received

Different directory structure between the 2 tarballs

### Describe the results you expected

Same directory structure.

### podman info output

```yaml
-
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment] 2023-05-03 08:46
Duplicate of #18215
This should be fixed going forward (https://github.com/containers/podman/pull/18238).

**Closed by Luap99** 2023-05-03 08:46 UTC
Labels: kind/bug
