### ISSUE TITLE
Multiple networks with static ip addresses

### ISSUE THREAD

**Issue by pjannesen** [containers/podman#12200] opened 2021-11-07 16:43 UTC
/kind feature

I need to link a pod/container to multiple physical NICs with a static ip addresses. The current syntax only allow to specify an ip address when there is only 1 network. A workaround (with macvlan) is to create of networks per ip address and use a /32 ip-range. It would be a lot simpler and nicer if there is the possibility to give parameters to a network such as a static ip-address.

It would be nice to defines networks like: --net=netX,ip= A.B.C.D,mac-address=xx:xx:xx:xx:xx:xx
And allow multiple –net arguments to define multiple networks

**Comment by Luap99** [comment] 2021-11-07 19:31
This is planned for podman 4.0.
I close this as duplicate of https://github.com/containers/podman/issues/9883.

**Closed by Luap99** 2021-11-07 19:31 UTC
Labels: kind/feature
