### ISSUE TITLE
Flake: CI Validation: Golangci-lint v1.54.2: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by cevich** [containers/podman#19752] opened 2023-08-25 15:28 UTC
### Issue Description

While running the `Validate fedora-38 Build` CI job in an image-update PR (`c20230824t202814z-f38f37d13`) golangci-lint is barfing with [a huge traceback (log)](https://cirrus-ci.com/task/5676357686919168?logs=main#L38).

### Steps to reproduce the issue

Steps to reproduce the issue
1. Open a PR (with the CI VM image suffix mentioned above)
2. Run CI

### Describe the results you received

`Validate fedora-38 Build` job fails, but passes on re-run.

### Describe the results you expected

CI should always pass

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

N/A

**Comment by cevich** [comment] 2023-08-25 15:29
cc @edsantiago - I didn't see this on your flake list.  Just FYI.  Also, renovate is already configured to update golangci-lint, there's no update available ATM.

**Comment by Luap99** [comment] 2023-08-25 15:36
I recommend you file this against golgangci-lint, this error is pretty much always a logic bug in the code, parallel map access is not allowed in go and must be guarded with a mutex.

**Comment by cevich** [comment] 2023-08-25 20:49
Yeah that's probably a good idea, though being a flake it's probably hard to reproduce :disappointed: In anycase I wanted to report it here in case anybody else hits it and as a reminder that we probably need to update golangci-lint when one is available.

**Comment by Luap99** [comment] 2023-09-11 08:27
A reproducer is helpful but not necessary because you captured the full stack trace we can see where the concurrent write happens so it should be easy enough for upstream developers to understand and fix IMO.

Looking at the upstream repo I see https://gitlab.com/bosi/decorder/-/merge_requests/91 and https://github.com/golangci/golangci-lint/pull/4056 so I expect the fix for this to be included in the next golangci-lint version.

**Closed** 2024-04-04 10:46 UTC
Labels: flakes, kind/bug
