### ISSUE TITLE
keep-id and ping

### ISSUE THREAD

**Issue by crepererum** [containers/podman#18023] opened 2023-04-03 13:32 UTC
### Issue Description

It seems that `--userns=keep-id` and ping interact in a somewhat weird way and ping isn't allowed for the group that is identical to the user group (see example below).

### Steps to reproduce the issue

Steps to reproduce the issue (this assumes that your rootless user and group ID is 1000:1000)
1. Add this to `/etc/containers/containers.conf`:
   ```text
   default_sysctls = [
       "net.ipv4.ping_group_range=0 65536",
   ]
   ```
3. `podman run -it --rm --userns=keep-id -u1000:1000 alpine ping -c1 8.8.8.8`

### Describe the results you received

```text
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: permission denied (are you root?)
```

### Describe the results you expected

Ping is working.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 95.59
    systemPercent: 1.19
    userPercent: 3.21
  cpus: 16
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: mneumann-x1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.1.12-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 9012674560
  memTotal: 67122044928
  networkBackend: cni
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.8.3-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 137438949376
  swapTotal: 137438949376
  uptime: 5h 13m 23.00s (Approximately 0.21 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/mneumann/.config/containers/storage.conf
  containerStore:
    number: 34
    paused: 0
    running: 1
    stopped: 33
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/mneumann/.local/share/containers/storage
  graphRootAllocated: 870622851072
  graphRootUsed: 700134436864
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 256
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/mneumann/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.4
  Built: 1680009696
  BuiltTime: Tue Mar 28 15:21:36 2023
  GitCommit: c8223435f49a860c8ac4281a85db39232745a7cb-dirty
  GoVersion: go1.20.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

# User and Group IDs

```console
$ id -u
1000
$ id -g
1000
```

### Additional information

# Test w/ `keep-id`
This is the scenario described in this bug that doesn't work:

```console
$ podman run -it --rm --userns=keep-id -u1000:1000 alpine id
uid=1000(mneumann) gid=1000(mneumann) groups=1000(mneumann)
$ podman run -it --rm --userns=keep-id -u1000:1000 alpine ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: permission denied (are you root?)
```

# Test w/o `keep-id`
If we don't use `keep-id`, it works:

```console
$ podman run -it --rm -u1000:1000 alpine id
uid=1000(mneumann) gid=1000(1000) groups=1000(1000)
$ podman run -it --rm -u1000:1000 alpine ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=42 time=17.119 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 17.119/17.119/17.119 ms
```

# Test w/ different user/group
If we use a different user/group, it also works:

```console
$ podman run -it --rm --userns=keep-id -u999:999 alpine id
uid=999(999) gid=999(ping) groups=1000(mneumann),999(ping)
$ podman run -it --rm --userns=keep-id -u999:999 alpine ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=42 time=14.373 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 14.373/14.373/14.373 ms
```

```console
$ podman run -it --rm --userns=keep-id -u1001:1001 alpine id
uid=1001(1001) gid=1001(1001) groups=1000(mneumann),1001(1001)
$ podman run -it --rm --userns=keep-id -u1001:1001 alpine ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=42 time=17.239 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 17.239/17.239/17.239 ms
```

This can also be reproduced when you only change the group:

```console
$ podman run -it --rm --userns=keep-id -u1000:999 alpine id
uid=1000(mneumann) gid=999(ping) groups=1000(mneumann),999(ping)
$ podman run -it --rm --userns=keep-id -u1000:999 alpine ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=42 time=14.890 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 14.890/14.890/14.890 ms
```

```console
$ podman run -it --rm --userns=keep-id -u1000:1001 alpine id
uid=1000(mneumann) gid=1001(1001) groups=1000(mneumann),1001(1001)
$ podman run -it --rm --userns=keep-id -u1000:1001 alpine ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=42 time=19.639 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 19.639/19.639/19.639 ms
```

**Comment by giuseppe** [comment] 2023-04-11 20:16
this smells like the kernel is converting the specified limits to `ping_group_range` from the user namespace to the kernel gids.

```
default_sysctls = [
    "net.ipv4.ping_group_range=0 65536",
]
```

In the example above, 0 is in reality a high ID with keep-id (since it is mapped to the first additional ID), so they are converted like: 0 -> 100000 and 65536 -> 165535.

So when you try to create an ICMP socket with your gid=1000, the kernel will reject it since 1000 is not included in 100000-165535.

To get the expected behavior, you'll need to specify something like: `--sysctl='net.ipv4.ping_group_range=1000 1000'`.

I am closing the issue because this is not something Podman can fix (except getting into the semantic of the specific sysctl), and it is a kernel behavior but feel free to comment further

**Closed by giuseppe** 2023-04-11 20:16 UTC
Labels: kind/bug
