### ISSUE TITLE
How to connect to pod started from deployment definition

### ISSUE THREAD

**Issue by bluebrown** [containers/podman#7738] opened 2020-09-22 23:05 UTC
/kind Question

Hi,

I am trying out the new feature of running a deployment definition. Before when I was using a created pod, I could assign an IP address to this pod. `podman pod create --name my-pod -p 8080:80`. 

The pods from the deployment file don't seem to expose a port and I can't find any documentation on this. 
In Kubernetes, it looks like it is usually paired with a top level service definition that exposes the port. [See here](https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/).

I am trying something like this but it doesn't work. I can't access the container.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - port: 8080
        - targetPort: 8080
        - containerPort: 80
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
````
These are the running containers.

```shell
CONTAINER ID  IMAGE                 COMMAND               CREATED         STATUS             PORTS   NAMES
0551ed5f7ce0  tomcat                catalina.sh run       20 seconds ago  Up 19 seconds ago          nginx-deployment-pod-0-tomcat
677383fe7b7f  k8s.gcr.io/pause:3.2                        20 seconds ago  Up 20 seconds ago          319739a24dbe-infra
6eb7b7cfa335  nginx                 /docker-entrypoin...  20 seconds ago  Up 19 seconds ago          nginx-deployment-pod-0-nginx
```

**Comment by zhangguanzhang** [comment] 2020-09-23 01:15
could you paste the output of `podman version`?

**Comment by zhangguanzhang** [comment] 2020-09-23 05:34
you could use the hostPort
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - port: 8080
        - hostPort: 81
        - targetPort: 8080
        - containerPort: 80
```

**Comment by bluebrown** [comment] 2020-09-23 15:40
@zhangguanzhang, thanks that was the missing piece. 

If there needs to be some documentation written on this, I would be happy to contribute.

**Comment by zhangguanzhang** [comment] 2020-09-24 01:01
I think you shuold configure the nginx to proxy the tomcat

**Comment by bluebrown** [comment] 2020-09-24 06:14
No, it's not that. When I only start nginx, I don't see anything. The reason why this happens is that tomcats default port is 8080 and the pod is mapping this and not port 80 to 8080 from the nginx container.  In a more complex setup I have the proxy configured but I wanted to keep it simple for this exercise.

**Comment by rhatdan** [comment] 2020-10-05 18:40
@bluebrown @zhangguanzhang @haircommander @ashley-cui Any progress?

**Comment by bluebrown** [comment] 2020-10-05 19:54
@rhatdan I gave it up at some stage and moved to k3s for that matter. There typically a deployment would also not even mix tomcat and nginx.

So not sure. I think the way that was shown can be used if you really use one image per deployment. If you want to use it in docker-compose fashion, I think it's not that useful as long as we don't have a way to use only one image on the pod as external service.

**Comment by zhangguanzhang** [comment] 2020-10-06 04:07
could use the containers' IP in local, if externalTraffic , must use port mapping

**Comment by rhatdan** [comment] 2020-10-07 17:29
@bluebrown @zhangguanzhang Should we close this issue?  Or is this a bug?

**Comment by bluebrown** [comment] 2020-10-07 19:56
@rhatdan I don't know if this is a bug. How did you intend the deployment to be used?

**Comment by zhangguanzhang** [comment] 2020-10-08 06:10
> @rhatdan I don't know if this is a bug. How did you intend the deployment to be used?

I think you should use `hostNetwork` or `hostPort`, and I think this is not a bug, because k8s has overlay net and svc

**Closed** 2020-10-11 16:22 UTC
Labels: Question
