### ISSUE TITLE
Parsing of IMAGE in runlabel command changed behavior in 4d4baba

### ISSUE THREAD

**Issue by KKoukiou** [containers/podman#10192] opened 2021-05-03 10:11 UTC
/kind bug

**Description**

runlabel behavior changed in podman version 3.1.1.

**Steps to reproduce the issue:**

1.
```
podman container runlabel INSTALL cockpit/ws
Error: repository name must be lowercase
Error: `/proc/self/exe run --rm --privileged -v /:/host IMAGE /container/atomic-install IMAGE` failed: exit status 125
```

Dockerfile:
```
FROM registry.fedoraproject.org/fedora:33
LABEL maintainer="cockpit-devel@lists.fedorahosted.org"
LABEL VERSION=243

ARG VERSION=243

ADD . /container

RUN echo -e '[group_cockpit-cockpit-preview]\nname=Copr repo for cockpit-preview owned by @cockpit\nbaseurl=https://copr-be.cloud.fedoraproject.org/results/@cockpit/cockpit-preview/fedora-$releasever-$basearch/\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://copr-be.cloud.fedoraproject.org/results/@cockpit/cockpit-preview/pubkey.gpg\nrepo_gpgcheck=0\nenabled=1\nenabled_metadata=1' > /etc/yum.repos.d/cockpit.repo

# Again see above ... we do our branching in shell script
RUN /container/install-package.sh && /container/prep-container.sh

LABEL INSTALL="/usr/bin/docker run --rm --privileged -v /:/host IMAGE /container/atomic-install IMAGE"
LABEL UNINSTALL="/usr/bin/docker run --rm --privileged -v /:/host IMAGE /container/atomic-uninstall"
LABEL RUN="/usr/bin/docker run -d --name NAME --privileged --pid=host -v /:/host IMAGE /container/atomic-run --local-ssh"

# Look ma, no EXPOSE

CMD ["/container/atomic-run"]
```

Commit which changed behavior:

```
commit 4d4babac7615ac832edaa8d405b507e5264a2122 (refs/bisect/bad)
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Mon Apr 5 18:12:50 2021 -0400

    Fix handling of $NAME and $IMAGE in runlabel
    
    Fixes: https://github.com/containers/podman/issues/9405
    
    Add system runlabel tests.
    
    Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
```

**Describe the results you received:**
Error: repository name must be lowercase

**Describe the results you expected:**
No error :)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
 3.1.1
```

**Comment by KKoukiou** [comment] 2021-05-03 10:12
So the question is, is that an expected change? Should we use IMAGE like \$IMAGE ?

**Comment by martinpitt** [comment] 2021-05-03 11:18
It's been `IMAGE` for years in docker and atomic, so this smells like a plain regression?

**Comment by rhatdan** [comment] 2021-05-03 11:59
Yes we should use IMAGE like $IMAGE, since we did this way back in Atomic.

**Comment by vrothberg** [comment] 2021-05-03 12:06
@rhatdan before fixing, let's wait until https://github.com/containers/podman/pull/10147 is merged.

**Comment by rhatdan** [comment] 2021-05-03 12:34
Should not be effected by this.

**Closed** 2021-05-05 20:47 UTC
Labels: kind/bug
