### ISSUE TITLE
How to escape command in kube

### ISSUE THREAD

**Issue by DaniBet** [containers/podman#9655] opened 2021-03-07 19:39 UTC
Hello,

I am using podman v3.0, this issue was not present in v1.6.

```
command: ['-f', '/opt/mongod.conf']
```

It seems that '-f' doesn't work anymore and it is considered a directory/file. My error:
```
container_linux.go:367: starting container process caused: exec: "-f": executable file not found in $PATH: OCI not found
```

**Comment by mheon** [comment] 2021-03-07 19:41
Can you provide further details? What image are you using. are you setting entrypoint as well? Full Kube YAML that reproduces would be ideal.

**Comment by DaniBet** [comment] 2021-03-07 19:47
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flowmanager
  name: flowmanager_pod
spec:
  containers:
    - image: mongo:3.6
      name: mongodb
      ports:
        - name: mongoport
          hostPort: 27017
          containerPort: 27017
          protocol: tcp
      command: ['-f', '/opt/mongod.conf']
      env:
        - name: MONGO_INTERNAL_PORT
          value: "27017"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "rootpassword"
        - name: MONGO_APP_DATABASE
          value: "umcft"
        - name: MONGO_APP_USER
          value: "flowmanager_user"
        - name: MONGO_APP_PASS
          value: "flowmanager_pass"
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: scripts
        - mountPath: /opt
          name: config
        - mountPath: /data/db
          name: data
  volumes:
    - hostPath:
        path: ./files/mongo/scripts
        type: Directory
      name: scripts
    - hostPath:
        path: ./files/mongo/config
        type: Directory
      name: config
    - hostPath:
        path: ./mongodb_data_container
        type: Directory
      name: data
```

**Comment by DaniBet** [comment] 2021-03-08 09:05
@mheon

Does it also replicate to you?

Thanks

**Comment by mheon** [comment] 2021-03-08 16:10
Concur, this does replicate.

**Comment by mheon** [comment] 2021-03-08 16:11
Looks like ENTRYPOINT from the mongo:3.6 image is being ignored.

**Comment by DaniBet** [comment] 2021-03-08 23:03
Do you think that this is a bug? If not, how can I fix that?

**Comment by DaniBet** [comment] 2021-03-08 23:09
The problem is not replicating in Podman v1.6. The problem is present in 3+.

**Comment by mheon** [comment] 2021-03-09 01:18
Yes, this definitely seems like a bug. I'll see if I can take a look tomorrow.

**Comment by zhangguanzhang** [comment] 2021-03-09 01:22
> The problem is not replicating in Podman v1.6. The problem is present in 3+.

command in pod's yaml is equal Image's entrypoint, should change the `command` to `args` in the yaml file and try again

**Comment by mheon** [comment] 2021-03-09 14:18
Alright, that makes sense. This would be classified as a bugfix, then.

**Comment by mheon** [comment] 2021-03-17 20:30
I'm going to close this - the old behavior was incorrect.

**Closed by mheon** 2021-03-17 20:30 UTC
Labels: kind/bug
