### ISSUE TITLE
podman machine init for HyperV provider fails on non English Windows

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman#20571] opened 2023-11-02 15:00 UTC
### Issue Description

When running podman machine init with HyperV on my French Windows, I have this:
```

Downloading VM image: fedora-coreos-38.20231027.2.0-hyperv.x86_64.vhdx.zip: done
Extracting compressed file: test_fedora-coreos-38.20231027.2.0-hyperv.x86_64.vhdx: done
Error: could not find virtual machine "test"
```

Although the HyperV machine has been created:

![image](https://github.com/containers/podman/assets/695993/5e72a503-3fdb-4986-a154-ba955fe1f90b)

### Steps to reproduce the issue

Steps to reproduce the issue
1. set CONTAINERS_MACHINE_PROVIDER=hyperv
2. podman machine init
3.

### Describe the results you received

Error returned while the machine has been created

### Describe the results you expected

Machine should be created

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.32.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.48
    systemPercent: 0.36
    userPercent: 0.15
  cpus: 12
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "38"
  eventLogger: journald
  freeLocks: 2048
  hostname: DESKTOP-JEFF
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 16047583232
  memTotal: 16646250496
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.8.0-1.fc38.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.8.0
    package: netavark-1.8.0-2.fc38.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.8.0
  ociRuntime:
    name: crun
    package: crun-1.10-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.10
      commit: c053c83c57551bca13ead8600237341818975974
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231004.gf851084-1.fc38.x86_64
    version: |
      pasta 0^20231004.gf851084-1.fc38.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc38.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 0h 1m 45.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 1125453824
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.7.0
  Built: 1695839078
  BuiltTime: Wed Sep 27 20:24:38 2023
  GitCommit: ""
  GoVersion: go1.20.8
  Os: linux
  OsArch: linux/amd64
  Version: 4.7.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Seems to be related to the underlying libhvee (I18N)

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment] 2023-11-02 15:31
@baude @mheon @ashley-cui PTAL

**Comment by baude** [comment] 2023-11-02 21:16
you are, for certain, running this with from a shell with administrative privileges?

**Comment by baude** [comment] 2023-11-02 21:18
also, please provide the full invocation ?

**Comment by jeffmaury** [comment] 2023-11-03 10:39
> you are, for certain, running this with from a shell with administrative privileges?

I have not but then switched to an admin shell and got the same error

**Comment by jeffmaury** [comment] 2023-11-03 10:40
> > you are, for certain, running this with from a shell with administrative privileges?
> 
> I have not but then switched to an admin shell and got the same error



> also, please provide the full invocation ?

podman machine init testhyperv

**Comment by ashley-cui** [comment] 2023-11-06 14:19
I switched my windows language to French and wasn't able to reproduce this.

Can you see if translating `Microsoft Virtual Machine` to 
`Machine virtuelle Microsoft` (or something like that) here fixes anything for you? 

https://github.com/containers/libhvee/blob/ec235380978ccf81dd6af42696c92a16bc5fe61f/pkg/hypervctl/vmm.go#L27

**Comment by jeffmaury** [comment] 2023-11-06 16:20
> I switched my windows language to French and wasn't able to reproduce this.
> 
> Can you see if translating `Microsoft Virtual Machine` to `Machine virtuelle Microsoft` (or something like that) here fixes anything for you?
> 
> https://github.com/containers/libhvee/blob/ec235380978ccf81dd6af42696c92a16bc5fe61f/pkg/hypervctl/vmm.go#L27

Changing the WQL query from:
`Select * From Msvm_ComputerSystem Where Description = 'Microsoft Virtual Machine'`
to
`Select * From Msvm_ComputerSystem Where Description = 'Ordinateur virtuel Microsoft'`

causes the dumpvms tools to return the list of Hyper-V VMs instead of `null`

**Comment by n1hility** [comment] 2023-11-06 19:27
@ashley-cui 

> Oh this might be interesting. @baude @n1hility it looks like the query changes depending on the system install language. Any ideas on how to fix this? Is there a hyperV config for language?

This is what the locale connection info in https://github.com/containers/libhvee/pull/33 was intended to resolve (fixed issues reported previously). Not sure why it's not working int his case, I'll see if I can reproduce somehow (Perhaps fallback to system default if the 409 locale isn't present?)

**Comment by ashley-cui** [comment] 2023-11-06 19:54
Just a thought - I wonder if it has to do with having the english locale existing on the system too - I was unable to reproduce on my system which has english installed.

**Comment by n1hility** [comment] 2023-11-06 21:40
@ashley-cui yeah thats exactly what i was thinking it might be that it would ignore and fallback to the system default without an error. I was able to get it to happen but i had to remove all traces of the english language pack, and then reboot (otherwise it gets cached)

@jeffmaury could you going into windows settings, languages and adding the english language pack and doing a full OS reboot?. You shouldn't have to switch your display language or anything like that, Get-InstalledLanguage should show an en language pack afterwords and it should start working.

**Comment by ashley-cui** [comment] 2023-11-06 21:44
Thanks for reproducing! I suppose the thing to do here is document this behavior, as I guess the fix is to download the language pack in Windows settings. 

cc @baude

**Comment by n1hility** [comment] 2023-11-06 23:37
yeah we could detect it isnt available and throw a friendlier error with instructions. alternatively it might be possible to do some specialized queries that better adapt to arbitrary locales in the future (e.g. via indirect querying, possibly some locale tables). Before going with the latter it needs some research to verify we dont end up with something too brittle to maintain.

**Comment by jeffmaury** [comment] 2023-11-07 08:27
> @ashley-cui yeah thats exactly what i was thinking it might be that it would ignore and fallback to the system default without an error. I was able to get it to happen but i had to remove all traces of the english language pack, and then reboot (otherwise it gets cached)
> 
> @jeffmaury could you going into windows settings, languages and adding the english language pack and doing a full OS reboot?. You shouldn't have to switch your display language or anything like that, Get-InstalledLanguage should show an en language pack afterwords and it should start working.

Once I added the English US language pack, then dumpvms now works ok

**Comment by jeffmaury** [comment] 2023-11-07 08:33
> yeah we could detect it isnt available and throw a friendlier error with instructions. alternatively it might be possible to do some specialized queries that better adapt to arbitrary locales in the future (e.g. via indirect querying, or possibly some synced locale keyword table). Before going with the latter it needs some research to verify we dont end up with something too brittle to maintain.

I'm afraid that will be too complex for users to handle and not sure it would be supported in enterprise environments. Does the Hyper-V Host Compute System API has the same limitations ?

**Comment by n1hility** [comment] 2023-11-07 16:57
> > @ashley-cui yeah thats exactly what i was thinking it might be that it would ignore and fallback to the system default without an error. I was able to get it to happen but i had to remove all traces of the english language pack, and then reboot (otherwise it gets cached)
> > @jeffmaury could you going into windows settings, languages and adding the english language pack and doing a full OS reboot?. You shouldn't have to switch your display language or anything like that, Get-InstalledLanguage should show an en language pack afterwords and it should start working.
> 
> Once I added the English US language pack, then dumpvms now works ok

Awesome. Thanks for confirming

> I'm afraid that will be too complex for users to handle 

Yeah I agree ideally we would automate it if its required but first going to try an approach I have in mind where it wouldn't matter.

> and not sure it would be supported in enterprise environments. 

It would really just be a dependent package if going this route (similar overhead would apply to distributing podman for example). Although I agree even better if it's avoided. 

> Does the Hyper-V Host Compute System API has the same limitations ?

I think it's immune to this one via the JSON schema but  it does trade other problems. Will get back soon on a possible solution once I escape some meetings :)

**Comment by n1hility** [comment] 2023-11-09 21:29
FYI a fix is advancing through to podman:
https://github.com/containers/libhvee/pull/62

**Comment by jeffmaury** [comment] 2023-11-10 11:25
Scary because the path works for me but the old code also (0.4.0) so it seems if you install and remove a language pack some files are kept

**Comment by ashley-cui** [comment] 2023-11-14 19:33
closed via https://github.com/containers/libhvee/pull/62

**Closed as completed by ashley-cui** 2023-11-14 19:33 UTC
Labels: kind/bug, remote, machine, windows, locked - please file new issue/PR
