### ISSUE TITLE
Error: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall bdflush: permission denied: OCI permission denied

### ISSUE THREAD

**Issue by jxs** [containers/podman#10735] opened 2021-06-20 11:51 UTC
Hi, I am getting this error with latest `podman` my podman info is:
```bash
~ sudo podman info                     
host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers:
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.29-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 7e6de6678f6ed8a18661e1d5721b81ccee293b9b'
  cpus: 12
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: ophion
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.45-1-lts
  linkmode: dynamic
  memFree: 7517126656
  memTotal: 8102539264
  ociRuntime:
    name: runc
    package: /usr/bin/runc is owned by runc 1.0.0rc95-1
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc95
      commit: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
      spec: 1.0.2-dev
      go: go1.16.4
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 7999582208
  swapTotal: 7999582208
  uptime: 9m 24.03s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 15
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.1
  Built: 1623927305
  BuiltTime: Thu Jun 17 11:55:05 2021
  GitCommit: 152952fe6b18581615c3efd1fafef2d8142738e8
  GoVersion: go1.16.5
  OsArch: linux/amd64
  Version: 3.2.1
  ```
downgrading [containers-common](https://archlinux.org/packages/community/any/containers-common/) from `0.40.0-1` to `0.39.0-3` fixes the issue 

thanks

**Comment by mheon** [comment] 2021-06-20 13:49
@cevich Well, we have a report of this in the wild now.

@jxs Workaround for now is to use `crun` instead of `runc` as your OCI runtime. We're seeing this in our CI and are trying to chase down the exact cause.

**Comment by cevich** [comment] 2021-06-21 14:36
> Well, we have a report of this in the wild now.

Aye, s'pose it was eventually inevitable.  For reference, this is being [tracked in a containers-common issue](https://github.com/containers/common/issues/631) (but affects both podman and buildah bud).

**Comment by captn3m0** [comment] 2021-06-22 07:53
Thanks @mheon.

`podman --runtime /usr/bin/crun run` worked for me (after installing [crun](https://github.com/containers/crun))

**Comment by rhatdan** [comment] 2021-06-22 18:47
You can change this by default in /etc/containers/containers.conf

**Comment by Foxboron** [comment] 2021-06-23 10:08
Arch maintainer here. Feel free to poke me to test patches and/or if we should add some workarounds.

Are we better off swapping runc for crun in our `podman` package going forward?

**Comment by rhatdan** [comment] 2021-06-23 13:41
That is what we are doing in Fedora land.  We think in the long run having a lighter weight OCI Runtime is a good thing.  Also we hope to get newer "plugin" runtimes that use crun as a front end in the future. libkrun for example.

**Comment by kallisti5** [comment] 2021-06-26 13:15
Just saw this on ArchLinux
```
docker build -t docker.io/haikuporter/haikuporter:1.2.5 .
STEP 1: FROM ubuntu:bionic
STEP 2: RUN ...
level=error msg="container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall bdflush: permission denied"
: exit status 1
Error: error building at STEP "RUN ...": error while running runtime: exit status 1
```

podman version 3.2.1

**Comment by kallisti5** [comment] 2021-06-26 13:17
switching to crun fixes it.  To have a workaround documented in this ticket, how do you change the default runtime of podman to crun?

**Comment by jxs** [comment] 2021-06-26 13:21
@kallisti5 :
>You can change this by default in /etc/containers/containers.conf

[see here](https://github.com/containers/common/blob/main/pkg/config/containers.conf#L404-L406)

**Comment by cevich** [comment] 2021-06-28 16:14
Closing this as the [root cause issue](https://github.com/containers/common/issues/631) has also been closed.  To be clear, the fix is podman 2.3.1 (or later) plus either:

* Use crun
* Use runc 1.0.0 (released 23rd June)

**Closed by cevich** 2021-06-28 16:14 UTC

**Comment by tsjk** [comment] 2021-10-03 09:17
> Closing this as the [root cause issue](https://github.com/containers/common/issues/631) has also been closed. To be clear, the fix is podman 2.3.1 (or later) plus either:
> 
> * Use crun
> * Use runc 1.0.0 (released 23rd June)

I run podman 3.3.1 on Gentoo, and with runc 1.0.0 I stumbled on this same error. I unstalled crun 0.19.1 (latest in Gentoo), and the problem "went away".

**Comment by ghenry** [comment] 2021-12-23 16:56
> Thanks @mheon.
> 
> `podman --runtime /usr/bin/crun run` worked for me (after installing [crun](https://github.com/containers/crun))

@captn3m0 I can this on Fedora 35:

```
sudo podman --runtime /usr/bin/crun run
Error: requires at least 1 arg(s), only received 0
```

What typo have I done?

**Comment by rhatdan** [comment] 2021-12-23 17:21
You have to specify an image.

**Comment by ghenry** [comment] 2021-12-23 17:23
Ah, I'm trying to build one from a Dockerfile.

**Comment by yiya1989** [comment] 2021-12-30 07:28
I use the lastst version of crun and podman, but i still raise errors.

[lch@n131-251-011 ~]$ podman run --userns=/usr/bin/runc --userns=keep-id -it docker.io/library/ubuntu:14.04 bash
Error: executable file `bash` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
[lch@n131-251-011 ~]$ podman run --runtime /usr/local/bin/crun --userns=keep-id -it docker.io/library/ubuntu:14.04 bash
Error: executable file `bash` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found

`podman info
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/local/bin/conmon
    version: 'conmon version 2.0.32-dev, commit: dc197c93e6095e40484a5fefa3932bdf69461852'
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "7"
  eventLogger: file
  hostname: n131-251-011.byted.org
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 3.10.0-1160.49.1.el7.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 5864042496
  memTotal: 16655921152
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/local/bin/crun
    version: |-
      crun version 1.4.16-fafb
      commit: fafb556f09e6ffd4690c452ff51856b880c089f1
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1002/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-0.4.3-4.el7_8.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.3.3
  swapFree: 0
  swapTotal: 0
  uptime: 27h 16m 49.73s (Approximately 1.12 days)
plugins:
  log:
  - k8s-file
  - none
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  example.com/foo:
    Blocked: false
    Insecure: false
    Location: internal-registry-for-example.com/bar
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: example.com/foo
  search:
  - docker.io
  - registry.aliyuncs.com
store:
  configFile: /home/lch/.config/containers/storage.conf
  containerStore:
    number: 18
    paused: 0
    running: 0
    stopped: 18
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/local/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
  graphRoot: /home/lch/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /tmp/podman-run-1002/containers
  volumePath: /home/lch/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1640010710
  BuiltTime: Mon Dec 20 22:31:50 2021
  GitCommit: f6526ada1025c2e3f88745ba83b8b461ca659933
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 3.4.4`

**Comment by mheon** [comment] 2021-12-30 23:48
That is a separate error, please file a new issue.
