### ISSUE TITLE
log-driver=passthrough issue with /dev/stderr

### ISSUE THREAD

**Issue by djarbz** [containers/podman#15759] opened 2022-09-12 21:33 UTC
```
ansible@chuwi:~$ podman version
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.19
Built:        Wed Dec 31 18:00:00 1969
OS/Arch:      linux/amd64
```
/kind bug

**Description**

I have been migrating my SystemD unit files to reference the new `--log-driver=passthrough` option.
It has been working rather well, except for this one container that logs to `/dev/stderr`.
I receive the following error when it attempts to write to the error log which is in turn symlinked to stderr.
```
(6)No such device or address: AH00091: apache2: could not open error log file /var/log/apache2/error.log.
AH00015: Unable to open logs
```

**Steps to reproduce the issue:**

This is my unit file and I have tested without the security options at the end.
```
## ANSIBLE MANAGED
[Unit]
Description=Podman librespeed.service
Documentation=man:podman-run(1)
Documentation=https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/assembly_porting-containers-to-systemd-using-podman_building-running-and-managing-containers
Wants=network-online.target
After=network-online.target
RequiresMountsFor=%t/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
ExecStartPre=-/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
ExecStartPre=-/bin/rm -f %t/%n.ctr-id
ExecStartPre=-/bin/rm -f %t/%n.pid
ExecStart=/usr/bin/podman run \
    --name librespeed \
    -d \
    --cidfile=%t/%n.ctr-id --sdnotify=conmon --cgroups=no-conmon \
    --conmon-pidfile=%t/%n.pid \
    --network slirp4netns:allow_host_loopback=true,enable_ipv6=true \
    --restart no \
    --replace \
    --rm \
    --stop-timeout 60 \
    --env "MODE=standalone" \
    --env "TITLE=Speedtest" \
    --env "TELEMETRY=True" \
    --env "REDACT_IP_ADDRESS=False" \
    --env "PASSWORD=admin" \
    --env "EMAIL=root@localhost" \
    --env "DISTANCE=mi" \
    --env "WEBPORT=8080" \
    -p 8001:8080 \
    -v /etc/localtime:/etc/localtime:ro \
    -v %E/librespeed/:/database/:rw \
    -l=diun.enable \
    --cap-drop=all \
    --security-opt=no-new-privileges \
    --cap-add=chown \
    docker.io/adolfintel/speedtest:latest
ExecReload=-/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecReload=-/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
Type=notify
NotifyAccess=all
KillMode=mixed
PIDFile=%t/%n.pid
Restart=on-failure
SyslogIdentifier=%N

[Install]
WantedBy=multi-user.target
WantedBy=default.target
```

**Describe the results you received:**
Apache could not log to stderr.

**Describe the results you expected:**
Apache should be able to log to stderr.

I am using the Alvistack Podman Repo to get the latest builds on Debian.

**Output of `podman info`:**
<details>
```
ansible@chuwi:~$ podman info
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon_100:2.1.4-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: bd1459a3ffbb13eb552cc9af213e1f56f31ba2ee'
  cpuUtilization:
    idlePercent: 86.8
    systemPercent: 5.09
    userPercent: 8.11
  cpus: 4
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: file
  hostname: chuwi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.0-13-amd64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 164151296
  memTotal: 8157216768
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun_100:1.6-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_100:1.2.0-1_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: unknown
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 1583607808
  swapTotal: 2147479552
  uptime: 147h 51m 14.00s (Approximately 6.12 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: registry.<REDACTED>.net
      PullFromMirror: ""
    - Insecure: false
      Location: mirror.gcr.io
      PullFromMirror: ""
    Prefix: docker.io
    PullFromMirror: ""
  search:
  - docker.io
store:
  configFile: /home/ansible/.config/containers/storage.conf
  containerStore:
    number: 23
    paused: 0
    running: 23
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ansible/.local/share/containers/storage
  graphRootAllocated: 471384244224
  graphRootUsed: 72845111296
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 53
  runRoot: /run/user/1000/containers
  volumePath: /home/ansible/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 0
  BuiltTime: Wed Dec 31 18:00:00 1969
  GitCommit: ""
  GoVersion: go1.19
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.1
```
</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
ansible@chuwi:~$ apt list podman
Listing... Done
podman/unknown,now 100:4.2.1-1 amd64 [installed]
N: There are 4 additional versions. Please use the '-a' switch to see them.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Debian 11 Bullseye

**Comment by giuseppe** [comment] 2022-09-13 11:54
To sure of what is failing, you could try to `strace` the container process and see what syscall is failing.  I think it is  attempting to open the `/dev/stderr` file and that fails because stderr is a socket under systemd.

I am closing the issue as I don't think there is anything doable in Podman, since it is an error caused by the interaction of the container payload with systemd, but feel free to comment further.

**Closed by giuseppe** 2022-09-13 11:54 UTC
Labels: kind/bug
