### ISSUE TITLE
Rest endpoint `/events` is cutting messages after 2048 chars while it should not

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15037] opened 2022-07-22 08:36 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

We can track podman events from clients by listening to `/events`
https://docs.podman.io/en/latest/_static/api.html?version=v4.1#operation/SystemEvents

The problem is that sometimes the events are cut, thus the client is only receiving a chunk of the full message, leading to invalid JSON content

**Steps to reproduce the issue:**

1. I've tried with a simple nodejs client.

Basically it connects to `/events` and wait that it receive contents before displaying

If I use Podman as backend I receive the following data when running a container from `quay.io/openshift/origin-hello-openshift` 

```
{"status":"create","id":"8e62a37e1f0562645905a7ae0def90f7d594f80b62bf393d97018ad0a64f02a5","from":"quay.io/openshift/origin-hello-openshift:latest","Type":"container","Action":"create","Actor":{"ID":"8e62a37e1f0562645905a7ae0def90f7d594f80b62bf393d97018ad0a64f02a5","Attributes":{"License":"GPLv2+","architecture":"x86_64","build-date":"2022-07-07T09:43:46.691337","com.redhat.build-host":"cpt-1008.osbs.prod.upshift.rdu2.redhat.com","com.redhat.component":"openshift-enterprise-base-container","com.redhat.license_terms":"https://www.redhat.com/agreements","containerExitCode":"0","description":"This is the base image from which all OpenShift Container Platform images inherit.","distribution-scope":"public","image":"quay.io/openshift/origin-hello-openshift:latest","io.buildah.version":"1.24.2","io.k8s.description":"ART equivalent image openshift-4.12-openshift-enterprise-base - rhel-8/base-repos","io.k8s.display-name":"4.12-base","io.openshift.build.commit.author":"","io.openshift.build.commit.date":"","io.openshift.build.commit.id":"6af294513f4fd83df5c821ec402fde182b3c390d","io.openshift.build.commit.message":"","io.openshift.build.commit.ref":"master","io.openshift.build.commit.url":"https://github.com/openshift/images/commit/50d342b487ce0f8a89046ddc1d93f390e4334b11","io.openshift.build.name":"","io.openshift.build.namespace":"","io.openshift.build.source-context-dir":"","io.openshift.build.source-location":"https://github.com/openshift/origin","io.openshift.ci.from.base":"sha256:1f7de7b0e1140b38ca08dcd402c2a88e91d438f080566781be3ab6b19bef3ba9","io.openshift.expose-services":"","io.openshift.maintainer.component":"Release","io.openshift.maintainer.product":"OpenShift Container Platform","io.openshift.tags":"openshift,base","maintainer":"Red Hat, Inc.","name":"unruffled_margulis","release":"202207070855.p0.g50d342b.assembly.stream","summary":"Provides the latest release of Red Hat Universal Base Image 8.","url":"https://access.redhat.com/containers/#/registry.access.redhat.com/openshift/ose-base/images/v4.12.0-2022070
```

and then
```
70855.p0.g50d342b.assembly.stream","vcs-ref":"6af294513f4fd83df5c821ec402fde182b3c390d","vcs-type":"git","vcs-url":"https://github.com/openshift/origin","vendor":"Red Hat, Inc.","version":"v4.12.0"}},"scope":"local","time":1658478438,"timeNano":1658478438576208167}
```

so we can see that data has been cut after exactly 2048 characters !

**Describe the results you received:**

messages are cut after 2048 characters

**Describe the results you expected:**

messages are not cut

I've tried with Docker as backend
and here is the result:
```
receiving data chunk: {"status":"create","id":"db1e1cca9322e71d6c8d99433b94879030742b24afcea20f6a5a1350a64d7e01","from":"quay.io/openshift/origin-hello-openshift","Type":"container","Action":"create","Actor":{"ID":"db1e1cca9322e71d6c8d99433b94879030742b24afcea20f6a5a1350a64d7e01","Attributes":{"License":"GPLv2+","architecture":"x86_64","build-date":"2022-07-07T09:43:46.691337","com.redhat.build-host":"cpt-1008.osbs.prod.upshift.rdu2.redhat.com","com.redhat.component":"openshift-enterprise-base-container","com.redhat.license_terms":"https://www.redhat.com/agreements","description":"This is the base image from which all OpenShift Container Platform images inherit.","distribution-scope":"public","image":"quay.io/openshift/origin-hello-openshift","io.buildah.version":"1.24.2","io.k8s.description":"ART equivalent image openshift-4.12-openshift-enterprise-base - rhel-8/base-repos","io.k8s.display-name":"4.12-base","io.openshift.build.commit.author":"","io.openshift.build.commit.date":"","io.openshift.build.commit.id":"6af294513f4fd83df5c821ec402fde182b3c390d","io.openshift.build.commit.message":"","io.openshift.build.commit.ref":"master","io.openshift.build.commit.url":"https://github.com/openshift/images/commit/50d342b487ce0f8a89046ddc1d93f390e4334b11","io.openshift.build.name":"","io.openshift.build.namespace":"","io.openshift.build.source-context-dir":"","io.openshift.build.source-location":"https://github.com/openshift/origin","io.openshift.ci.from.base":"sha256:1f7de7b0e1140b38ca08dcd402c2a88e91d438f080566781be3ab6b19bef3ba9","io.openshift.expose-services":"","io.openshift.maintainer.component":"Release","io.openshift.maintainer.product":"OpenShift Container Platform","io.openshift.tags":"openshift,base","maintainer":"Red Hat, Inc.","name":"trusting_ardinghelli","release":"202207070855.p0.g50d342b.assembly.stream","summary":"Provides the latest release of Red Hat Universal Base Image 8.","url":"https://access.redhat.com/containers/#/registry.access.redhat.com/openshift/ose-base/images/v4.12.0-202207070855.p0.g50d342b.assembly.stream","vcs-ref":"6af294513f4fd83df5c821ec402fde182b3c390d","vcs-type":"git","vcs-url":"https://github.com/openshift/origin","vendor":"Red Hat, Inc.","version":"v4.12.0"}},"scope":"local","time":1658478727,"timeNano":1658478727409980525}
```

So we can clearly see that message is 2277 characters long as expected

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
current main branch
```

**Output of `podman info --debug`:**

```
current main branch
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
build from source
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

here is the client I wrote to reproduce the issue

you need to change socketPath to try either on podman or docker

to test:
1. launch this client: `node <name-of-this-file.js>`
when you see `Ready to receive events..`, you can continue
2. launch this container: 
`podman run --rm quay.io/openshift/origin-hello-openshift` to try with Podman
`docker run --rm quay.io/openshift/origin-hello-openshift` to try with Docker

```js
const http = require("http");

// uncomment the lines to use either podman or docker socket

const socketPath = '/Users/benoitf/.local/share/containers/podman/machine/podman-machine-default/podman.sock'
//const socketPath = "/var/run/docker.sock";
const path = "/v1.41/events";

const req = http.request({ method: "GET", socketPath, path }, (res) => {
  console.log("Ready to receive events...");

  res.on("data", (chunk) => {
    console.log("receiving data chunk:", chunk.toString());
    try {
      JSON.parse(chunk.toString());
      console.log("Valid-JSON");
    } catch (error) {
      console.log("Invalid JSON", error);
    }
  });

  res.on("end", () => {
    console.log("ending with status", res.statusCode);
  });
});
req.end();

req.once("error", (err) => {
  console.log("receive error", err);
});

```

**Comment by Luap99** [comment] 2022-07-22 09:12
You are not reading events correctly. There is no guarantee that one write on the server equals one read on the client, especially not when this proxied to the mac. You have to continue reading until the end of the json message.

**Comment by benoitf** [comment] 2022-07-22 09:17
@Luap99 on Docker this is not cutting after 2048

**Comment by Luap99** [comment] 2022-07-22 09:27
Do you see the rest of the message on the next read?

Because if you do then you are not parsing the message correctly. It doesn't matter if docker truncates or not. The point is that you cannot expect a single read to contain the full message. AFAIK we proxy the socket via ssh which is send via TCP and there is a limited package size. This is a stream socket and there is no concept of packages when you read from the stream. Read will succeed as soon as some data arrives.

I don't know how it works in JS but in go we can parse JSON directly from the stream:
https://github.com/containers/podman/blob/ee937c518e7efb9c47d21a4e1050b966ca02d005/pkg/bindings/system/system.go#L44-L50

**Comment by benoitf** [comment] 2022-07-22 09:31
if you proxy it, then proxy should deliver the correct message.

Clients like [Dockerode](https://github.com/apocas/dockerode) provides the message directly. All people that will use compat mode of Podman will have this issue

**Comment by Luap99** [comment] 2022-07-22 09:42
AGAIN there is no such thing as a message on a stream socket, you read a stream of bytes. So you have to continue reading until the end of the json message.

If you expose the docker socket via TCP on a different PC on your network you will have the same problem.

**Comment by benoitf** [comment] 2022-07-22 09:45
@Luap99 I'm on macOS so docker is running in a VM so it's exposed by TCP

**Comment by Luap99** [comment] 2022-07-22 10:45
It doesn't matter if it works for you with docker, they might have a high enough MTU on the VM interface.

You are relying on undefined behaviour. Look at socket(2):
> Sockets of type SOCK_STREAM are full-duplex byte streams.  They do not preserve record boundaries.

See also https://stackoverflow.com/a/9563694 for a example what that means.

Your liked lib also has this issue: https://github.com/apocas/dockerode/issues/363, although this is the other way around 2 messages retuned at once.

The end of the event message is marked with a newline so you would have to read until you find a newline before parsing the message.

**Comment by vrothberg** [comment] 2022-07-22 10:47
@Luap99 I prefer to keep it open an investigate why Podman doesn't use a 8192 buffer as Docker does.  I agree that it's not a Podman bug per-se but if it breaks a popular JS library, we should check whether we can behave as Docker.

**Comment by vrothberg** [comment] 2022-07-22 10:51
I _think_ the difference comes from docker using `"golang.org/x/net/http2"` which is not chunking at 2038 as the standard library does.

**Comment by vrothberg** [comment] 2022-07-22 11:30
Since we cannot [change the buffer size](https://github.com/golang/go/issues/7467) of the standard library  I think we have three options:
1) Use `http2` for the server as well
2) Add a writer-wrapper to the server to increase the buffer size
3) No code change but document the issue

My order of preference is 2), 1), 3). @jwhonce @rhatdan @mheon WDYT?

**Comment by benoitf** [comment] 2022-07-22 16:50
@n1hility I understand what is said but to be more compliant it should at least use the same buffer size by default so clients don't need to be changed.
If you don't set same default then it's not mapping the same default behaviour so it is not what I called 'compat'

**Comment by n1hility** [comment] 2022-07-22 22:08
@benoitf I sent in a PR for one approach of a solution (and comment on an alternative if you guys like that one better):
https://github.com/containers/podman-desktop/pull/344

What I meant in my earlier reply is that even if we change the buffer, the client will still break. Perhaps slightly less often.

**Comment by vrothberg** [comment] 2022-07-23 10:02
> @vrothberg @benoitf What @Luap99 is pointing out is that this is something that can't be fixed on the server side, it can only be corrected on the client. Even if you change the buffer amounts, there is no gaurantee they will be respected. 

Yes, I understand (and agree).

> A workaround you can potentially do (before dockerode is fixed) is if they provide a way for you to intercept their stream you can wrap it with a buffered implementation that reads up to record boundaries.

I see two things that are worth addressing:
1) Fix podman-desktop and dockerode.  Thanks for the PR, @n1hility!
2) Use the same buffer size as Docker.  There's no guarantee that proxies wouldn't change the behavior or that the buffer-size in the Go packages will remain the same (it has changed in the Go stdlib over time alrady) _BUT_ older versions of dockerode etc. would work.  There may be other tools and libraries having the same issue.

The diplomat that I am wants to make everybody happy :angel:

**Comment by Luap99** [comment] 2022-07-23 10:35
I am totally fine with option 2 if this is a simple fix. I assume other streaming endpoints (attach/logs, or there more?) could have similar problems.

**Comment by n1hility** [comment] 2022-07-23 19:57
> > @vrothberg @benoitf What @Luap99 is pointing out is that this is something that can't be fixed on the server side, it can only be corrected on the client. Even if you change the buffer amounts, there is no gaurantee they will be respected.
> 
> Yes, I understand (and agree).
> 
> > A workaround you can potentially do (before dockerode is fixed) is if they provide a way for you to intercept their stream you can wrap it with a buffered implementation that reads up to record boundaries.
> 
> I see two things that are worth addressing:
> 
> 1. Fix podman-desktop and dockerode.  Thanks for the PR, @n1hility!

The good news there is it looks like we don't need to patch dockerode, in this case dockerode passes the body stream back to the client, and the client is responsible for processing the stream (client receives a callback per IO read() result and needs to assemble into a JSON stream)

> 2. Use the same buffer size as Docker.  There's no guarantee that proxies wouldn't change the behavior or that the buffer-size in the Go packages will remain the same (it has changed in the Go stdlib over time alrady) _BUT_ older versions of dockerode etc. would work.  There may be other tools and libraries having the same issue.

This won't really help with compatibility (better perf perhaps). Any client that was written to expect a json payload fitting inside the result of a single read call is fundamentally broken, and will fail, _**even when talking to Docker**_. Since, the contract of read() is that an arbitrary number of bytes from zero to an implementation-defined max, and since a JSON streaming payload is made up of records of arbitrary size, clients must pre-assemble or lazy parse. Otherwise, the event stream will quickly become indecipherable, and events will be lost. 

The buffer size on the server is only one of several environmental factors that may influence the result of those read() calls. The path from podman-desktop to podman looks like:

podman-desktop -> nodejs http stack framing -> node i/o stack -> read kernel syscall -> unix socket stack -> go based ssh proxy -> ssh nested tunnel over ssh framing -> gvproxy or wsl forwarder -> gvisor vrtual network framing over vsock -> qemu | hyper-v vm -> virtio-net driver ->  kernel tcp stack -> openssh ssh server (deframing tunneling) -> unix socket stack -> systemd socket activation -> go http and io -> podman service.

All of these things impact the amount of data available to read at any given moment, and that is based on live dynamic conditions. As an example, @Luap99 earlier mentioned tcp windows. When a receiver can't keep up with a sender the sender is throttled and sends less data, which means less returned on that read() call. The linux kernel also will throttle buffers based on system resources; if memory is under pressure, for example, buffer sizes drop. Then you have framing behavior. HTTP headers have arbitrary size and value and are part of the TCP payload. One slightly longer header could mean the body is divided differently. SSH traffic includes control traffic and encryption (including padding), which can also vary and competes for space in the TCP buffer for the connection. Then there is the JSON payload itself, one event may have more data than another (as the original description in this lays out).

> 
> The diplomat that I am wants to make everybody happy 👼

Completely agree on improving the experience however possible. To be clear, I am not even against raising the buffer, I am just trying to help prevent the wrong expectations being formed, and any disappointing experience that might come from that (hard to debug problems, hangs, data loss etc).

**Comment by vrothberg** [comment] 2022-07-25 07:38
> The good news there is it looks like we don't need to patch dockerode, in this case dockerode passes the body stream back to the client, and the client is responsible for processing the stream (client receives a callback per IO read() result and needs to assemble into a JSON stream)

That indeed is good news, thanks for sharing.

**Comment by vrothberg** [comment] 2022-07-25 07:39
Since dockerode is passing the stream to the client, I feel less inclined to change the buffer size and am OK with closing the issue.

**Closed by vrothberg** 2022-07-25 07:39 UTC
Labels: kind/bug

**Comment by benoitf** [comment] 2022-07-25 07:50
I've looked at all github clients using Dockerode and they're mostly all parsing the message as it is so most of clients will still break. At leat you're informed that default behaviour (no proxy, no remote, etc) is not the same.

**Comment by deboer-tim** [comment] 2022-07-25 12:02
The post from @n1hility above was spot on - Podman is not broken and ultimately no server-side change can fix bad client parsing. Now that we're aware of the issue we can point any broken client here for a thorough explanation of the problem and why the client has to fix it.

IMHO the question then becomes whether we're ok with the current buffer size and the fact that clients are more likely to hit this problem and break with Podman vs Docker. IMHO it's in an awkward size where clients don't often hit it but definitely will at some point, and hence their first assumption is that something is wrong in Podman. We could leave as-is, make the buffer smaller to essentially force all clients to fix the problem up-front to work with Podman, or raise it to match Docker and fail later.

As much as there is delayed damage in raising it, personally I think it's better to match Docker both for compatibility reasons and having more clients work by default.

**Comment by rhatdan** [comment] 2022-07-25 20:24
I tend to agree.  Do not need more This works on Docker but not on Podman...

**Comment by vrothberg** [comment] 2022-07-26 09:00
> I tend to agree. Do not need more This works on Docker but not on Podman...

@rhatdan what's you preferred solution?  Quick and easy is to use the `http2` for the server.

@jwhonce ^ WDYT?

**Comment by n1hility** [comment] 2022-07-26 13:42
http2 wont help though if the clients are using http 1 (and don't support upgrading). we could just wrap with a larger buffer i have a small patch for this i just need to test it.

**Comment by vrothberg** [comment] 2022-07-26 13:49
@n1hility, I am referring to the gopackage Docker uses which is chunking differently, see https://github.com/containers/podman/issues/15037#issuecomment-1192446325.

**Comment by n1hility** [comment] 2022-07-26 13:55
ah gotcha!

**Comment by n1hility** [comment] 2022-07-27 07:00
hi @vrothberg  Just for discussion, I posted up the small patch I referred to as a draft in case it's useful for this discussion. I tried it out tonight and it works with the examples of the issue. 

I took a look at the docker api server impl, and it is using net.http for h1 clients (like the node sample), with the same chunking and buffer limits (confirmed at runtime as well). The only other differences that stood out were flushing on every write and a lot more use of locking scattered about.

**Comment by vrothberg** [comment] 2022-07-27 07:41
Thanks for digging into it, @n1hility. I'll comment over in the PR :+1:

**Comment by n1hility** [comment] 2022-07-29 15:01
As an update, #15086 was merged: the docker API compatibility end-points that offer API streaming, we now buffer up to 8k. I tested the provided example which does work for me.

**Comment by benoitf** [comment] 2022-07-29 15:07
nice improvement 👍
