### ISSUE TITLE
podman secret create --replace=true unexpectedly fails to create secret when replacement isn't needed

### ISSUE THREAD

**Issue by cgigun** [containers/podman#22000] opened 2024-03-08 23:46 UTC
### Feature request description

I expected  podman secret create --replace=true to  create a secret, even if that requires replacing the existing one.

Instead the current behavior is to refuse to create a secret unless a pre-existing secret with the same name is found.

### Suggest potential solution

I'd like  --replace=true to _allow_ replacement, not require it

### Have you considered any alternatives?

The alternative I'm using  is to not use the --replace flag at all.  My script for updating my passwords has to manually remove every secret and then create them again.

**Comment by Luap99** [comment] 2024-03-11 13:51
Duplicate of #21952

**Closed** 2024-03-11 13:52 UTC
Labels: kind/feature
