### ISSUE TITLE
[documentation] example image `libpod/banner` used in `basic_networking.md` does not serve the website it should

### ISSUE THREAD

**Issue by vrms** [containers/podman#14305] opened 2022-05-20 09:00 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

in the [Podman Basic Networking Guide]( https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md) (basic_networking.md) there is an example to curl a website served by a container based on a `quay.io/libpod/banner` image. It should look like
```
   ___           __
  / _ \___  ___/ /_ _  ___ ____
 / ___/ _ \/ _  /  ' \/ _ `/ _ \
/_/   \___/\_,_/_/_/_/\_,_/_//_/
```
however the actual outcome is 
```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Steps to reproduce the issue:**

1. `podman run -dt --name webserver -p 8881:80 quay.io/libpod/banner`

2. ` curl localhost:8081`

**Describe the results you expected/received:**
- see description

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18.1
Git Commit:   e4b03902052294d4f342a185bb54702ed5bed8b1
Built:        Fri May  6 20:18:30 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.0-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: bdb4f6e56cd193d40b75ffc9725d4b74a18cb33c'
  cpuUtilization:
    idlePercent: 49.08
    systemPercent: 15.51
    userPercent: 35.4
  cpus: 4
  distribution:
    distribution: manjaro
    version: unknown
  eventLogger: journald
  hostname: manj-laptop
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 65536
      size: 34465
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 65536
      size: 34465
  kernel: 5.10.114-1-MANJARO
  linkmode: dynamic
  logDriver: journald
  memFree: 712433664
  memTotal: 12454653952
  networkBackend: cni
  ociRuntime:
    name: runc
    package: /usr/bin/runc is owned by runc 1.1.1-2
    path: /usr/bin/runc
    version: |-
      runc version 1.1.1
      spec: 1.0.2-dev
      go: go1.18.1
      libseccomp: 2.5.4
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 24061947904
  swapTotal: 24889536512
  uptime: 3h 7m 53.69s (Approximately 0.12 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/manolo/.config/containers/storage.conf
  containerStore:
    number: 19
    paused: 0
    running: 2
    stopped: 17
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/manolo/.local/share/containers/storage
  graphRootAllocated: 475004928000
  graphRootUsed: 447898779648
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 48
  runRoot: /run/user/1000/containers
  volumePath: /home/manolo/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.0
  Built: 1651861110
  BuiltTime: Fri May  6 20:18:30 2022
  GitCommit: e4b03902052294d4f342a185bb54702ed5bed8b1
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ pacman -Qi podman
Name            : podman
Version         : 4.1.0-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/podman
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : conmon  containers-common  crun  iptables  libdevmapper.so=1.02-64  libgpgme.so=11-64  libseccomp.so=2-64  slirp4netns
Optional Deps   : apparmor: for AppArmor support [installed]
                  btrfs-progs: support btrfs backend devices [installed]
                  netavark: for a new container-network-stack implementation [installed]
                  podman-compose: for docker-compose compatibility [installed]
                  podman-docker: for Docker-compatible CLI
Required By     : podman-compose
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 63,26 MiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Fr 06 Mai 2022 20:18:30 CEST
Install Date    : Fr 13 Mai 2022 08:02:57 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

issue is not related to podman version

**Comment by Luap99** [comment] 2022-05-23 18:15
Duplicate of #13685

**Closed by Luap99** 2022-05-23 18:15 UTC
Labels: kind/bug
