### ISSUE TITLE
podman search fails on azure registry

### ISSUE THREAD

**Issue by masarlabs** [containers/podman#10251] opened 2021-05-06 16:22 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
podman search on Azure registry fails for some search with "denied: requested access to the resource is denied"

**Steps to reproduce the issue:**

1. podman search wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner --list-tags
2. podman search wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner
3. podman search wfprshrdkrreg01cr.azurecr.io/

**Describe the results you received:**
I got error for 2 and 3, but 1 works as expected   

**Describe the results you expected:**
I would like to find the container images

**Additional information you deem important (e.g. issue happens only occasionally):**
I did the same commands with --log-level debug.

This works as expected
```
podman search wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner --list-tags --log-level debug

INFO[0000] podman filtering at log level debug
...
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/v2/ 
DEBU[0000] Ping https://wfprshrdkrreg01cr.azurecr.io/v2/ status 401 
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/oauth2/token?account=wfprshrdkrreg01cr&scope=repository%3Acdt%2Fminiwaf-banner%3Apull&service=wfprshrdkrreg01cr.azurecr.io 
DEBU[0000] Increasing token expiration to: 60 seconds   
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/v2/cdt/miniwaf-banner/tags/list 
NAME                                             TAG
wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner  0.0.3-0.20210506.125359
wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner  prd
DEBU[0000] Called search.PersistentPostRunE(podman search wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner --list-tags --log-level debug) 
```

This gives error:
```
podman search wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner --log-level debug

INFO[0000] podman filtering at log level debug
...
DEBU[0000] trying to talk to v1 search endpoint         
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/v2/ 
DEBU[0000] Ping https://wfprshrdkrreg01cr.azurecr.io/v2/ status 401 
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/v1/search?n=25&q=cdt%2Fminiwaf-banner 
DEBU[0000] error getting search results from v1 endpoint "wfprshrdkrreg01cr.azurecr.io": invalid status code from registry 404 (Not Found) 
DEBU[0000] trying to talk to v2 search endpoint         
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/oauth2/token?account=wfprshrdkrreg01cr&service=wfprshrdkrreg01cr.azurecr.io 
DEBU[0000] Increasing token expiration to: 60 seconds   
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/v2/_catalog 
ERRO[0000] error getting search results from v2 endpoint "wfprshrdkrreg01cr.azurecr.io": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information. 
DEBU[0000] Called search.PersistentPostRunE(podman search wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner --log-level debug) 
```

This gives error:
```
podman search wfprshrdkrreg01cr.azurecr.io/ --log-level debug

INFO[0000] podman filtering at log level debug
...
DEBU[0000] trying to talk to v2 search endpoint         
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/v2/ 
DEBU[0000] Ping https://wfprshrdkrreg01cr.azurecr.io/v2/ status 401 
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/oauth2/token?account=wfprshrdkrreg01cr&service=wfprshrdkrreg01cr.azurecr.io 
DEBU[0000] Increasing token expiration to: 60 seconds   
DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/v2/_catalog 
ERRO[0000] error getting search results from v2 endpoint "wfprshrdkrreg01cr.azurecr.io": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information. 
DEBU[0000] Called search.PersistentPostRunE(podman search wfprshrdkrreg01cr.azurecr.io/ --log-level debug) 
```

It seams that it does call the oauth2 authentication or that it does not use the auth token.

**Output of `podman version`:**
```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.9
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**
```
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 8
  distribution:
    distribution: debian
    version: unknown
  eventLogger: journald
  hostname: masar
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100001
      size: 655350
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100001
      size: 655350
  kernel: 5.10.0-6-amd64
  linkmode: dynamic
  memFree: 1946333184
  memTotal: 8228171776
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.4.0
  swapFree: 8988651520
  swapTotal: 8998875136
  uptime: 10h 24m 27.09s (Approximately 0.42 days)
registries:
  localhost:
    Blocked: true
    Insecure: false
    Location: localhost
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost
  search:
  - docker.io
  - quay.io
  - wfprshrdkrreg01cr.azurecr.io
store:
  configFile: /srv/masar/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /srv/masar/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 15
  runRoot: /run/user/1000/containers
  volumePath: /srv/masar/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.9
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
podman/testing,now 3.0.1+dfsg1-2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment] 2021-05-07 10:10
Can you search for this image using docker?

**Comment by masarlabs** [comment] 2021-05-16 08:42
I cannot test it with docker, but I tried to call the registry API with a simple curl using basic authentication and it works:

curl --user xxx:zzz https://wfprshrdkrreg01cr.azurecr.io/v2/
   HTTP/1.1 200 OK
   {}

curl --user xxx:zzz https://wfprshrdkrreg01cr.azurecr.io/v2/_catalog
   HTTP/1.1 200 OK
   {"repositories":[ ...,"cdt/miniwaf-banner",...]}

curl --user xxx:zzz https://wfprshrdkrreg01cr.azurecr.io/v2/cdt/miniwaf-banner/tags/list
   HTTP/1.1 200 OK
   {"name":"cdt/miniwaf-banner","tags":["prd"]}
   
I think that the problem is that podman tries to use OAuth2 authentication for the "_catalog" query instead of basic auth and Azure Registry seams not support it.

podman login wfprshrdkrreg01cr.azurecr.io
   Authenticating with existing credentials...
   Existing credentials are valid. Already logged in to wfprshrdkrreg01cr.azurecr.io

podman search miniwaf-banner --log-level debug
   DEBU[0000] trying to talk to v1 search endpoint         
   DEBU[0000] Ping https://wfprshrdkrreg01cr.azurecr.io/v2/ status 401 
   DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/v1/search?n=25&q=miniwaf-banner
   DEBU[0000] error getting search results from v1 endpoint "wfprshrdkrreg01cr.azurecr.io": invalid status code from registry 404 (Not Found) 
   DEBU[0000] trying to talk to v2 search endpoint         
   DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/oauth2/token?account=wfprshrdkrreg01cr&service=wfprshrdkrreg01cr.azurecr.io 
   DEBU[0000] Increasing token expiration to: 60 seconds   
   DEBU[0000] GET https://wfprshrdkrreg01cr.azurecr.io/v2/_catalog 
   ERRO[0000] error getting search results from v2 endpoint "wfprshrdkrreg01cr.azurecr.io": unable to retrieve auth token: invalid username/password: errors:
   denied: requested access to the resource is denied
   unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information. 
   DEBU[0001] Called search.PersistentPostRunE(podman search miniwaf-banner --log-level debug) 

podman search miniwaf-banner
   ERRO[0000] error getting search results from v2 endpoint "wfprshrdkrreg01cr.azurecr.io": unable to retrieve auth token: invalid username/password: errors:
   denied: requested access to the resource is denied
   unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information. 

podman search wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner 
   ERRO[0000] error getting search results from v2 endpoint "wfprshrdkrreg01cr.azurecr.io": unable to retrieve auth token: invalid    username/password: errors:
   denied: requested access to the resource is denied
   unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information. 

podman search wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner --list-tags
   NAME                                             TAG
   wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner  0.0.3-0.20210506.125359
   wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner  0.9.0-0.20210510.160336
   wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner  0.9.1-0.20210510.180050
   wfprshrdkrreg01cr.azurecr.io/cdt/miniwaf-banner  prd

Only the last podman search works!!!

**Comment by rhatdan** [comment] 2021-07-09 20:34
@mtrmac @vrothberg PTAL

**Comment by mtrmac** [comment] 2021-07-09 20:50
Well, `--list-tags` is not a search at all, so it’s not all that relevant that that one doesn’t fail.

WRT accepting basic auth but not a token, that’s surprising but I guess possible.
- Is there any official documentation to the effect that this is intentional and not just a (temporary?) bug? It wouldn’t be nice to send basic auth credentials to a registry when the whole point of dealing with tokens OAuth2 is not to do that. It’s also quite possible that the registry does support OAuth2 for this, but expects some specific scope request which we are not asking for.
- Either way, can we automatically recognize the relevant server implementation and adjust? Making this an end-user option would be pretty bad.

**Comment by mtrmac** [comment] 2021-07-12 22:37
Testing this,
```console
$ curl -iL 'https://wfprshrdkrreg01cr.azurecr.io/v2/_catalog'
…
Www-Authenticate: Bearer realm="https://wfprshrdkrreg01cr.azurecr.io/oauth2/token",service="wfprshrdkrreg01cr.azurecr.io",scope="registry:catalog:*"
…
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information.","detail":[{"Type":"registry","Name":"catalog","Action":"*"}]}]}
```

so it does seem that it would be possible for OAuth2 to work, with an appropriate scope. And that would be a duplicate of https://github.com/containers/image/issues/1225 .

**Comment by vrothberg** [comment] 2021-07-16 12:52
Closing as a duplicate of containers/image#1225

**Closed by vrothberg** 2021-07-16 12:52 UTC
Labels: kind/bug
