### ISSUE TITLE
support CLI plugins

### ISSUE THREAD

**Issue by muayyad-alsadi** [containers/podman#13461] opened 2022-03-08 19:35 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
as discussed [here](https://github.com/containers/podman/issues/11780#issuecomment-1061133562)
it's good to have a `podman <COMMAND>`  by running executable named `podman-<COMMAND>`
found in `/usr/libexec/podman/cli-plugins/` or `~/.podman/cli-plugins`

**Comment by rhatdan** [comment] 2022-03-08 19:56
If you have plugins in both directories, we execute the local ones?

~/.config/containers/cli-plugins?
~/.local/share/containers/cli-plugins?

**Comment by rhatdan** [comment] 2022-03-08 21:53
Ok I guess your suggested directories work, since this would be specific to Podman as well.

**Comment by vrothberg** [comment] 2022-03-11 12:51
How should the API of such plugins look like?

**Comment by Luap99** [comment] 2022-03-11 17:14
Also see https://github.com/containers/podman/issues/5802

**Comment by vrothberg** [comment] 2022-03-14 09:49
> I think we should match the docker cli API. This would allow people to use docker cli plugins as well.

Is it documented somewhere?

**Comment by muayyad-alsadi** [comment] 2022-03-14 10:49
here

https://github.com/docker/cli/issues/1534

**Comment by vrothberg** [comment] 2022-03-14 10:58
Thanks!

I just briefly skimmed the plugins code and am not entirely convinced that's something Podman should support. The documentation/specification really is in the code which is completely outside of our control. I am mostly afraid of a potential whack-a-mole and the maintenance burden.

@muayyad-alsadi, can you elaborate on a use case?  Podman supports [OCI hooks](https://manpages.debian.org/unstable/podman/oci-hooks.5.en.html) which may meet your requirements already.

**Comment by muayyad-alsadi** [comment] 2022-03-14 11:16
> says it is deprecated. However it seems that docker still uses for many tools, e.g. docker-compose v2.

yes, the old docker-compose was not a cli plugin, the new v2 is a cli plugin
so is scan plugin
so is buildx

https://github.com/docker/scan-cli-plugin/

> can you elaborate on a use case?

podman-compose and maybe scan ...etc.

> OCI hooks are different than a generic cli plugin. Hooks can only be used for a container lifecycle. For a tool like compose you cannot use hooks, you want the user to type a specific command.

exactly

> I never understand why someone would need a plugin in the first place, what is the problem with typing podman-foo or just foo vs podman foo.

so users can find help in one place

```
# docker --help

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  app*        Docker App (Docker Inc., v0.9.1-beta3)
  builder     Manage builds
  buildx*     Docker Buildx (Docker Inc., v0.7.1-docker)
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  demo*       Demo docker command (Muayyad Alsadi, v0.0.1) <----------------------- this is my above bash script
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  scan*       Docker Scan (Docker Inc., v0.12.0)
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

**Comment by vrothberg** [comment] 2022-03-17 10:27
@containers/podman-maintainers PTAL

**Comment by mheon** [comment] 2022-03-17 14:23
The question for me is, will the Docker Compose v2.x tool remain a CLI plugin?

If so, that's a pretty significant incentive for us to support the Docker plugin model, even if it is official deprecrated and mostly undocumented. With a few simple steps, a user can have Docker Compose, or Podman Compose, or both, directly integrated into the Podman CLI, and that's a very powerful argument.

Unfortunately, I don't really have an answer here. The Docker folks say they're looking into integrating compose v2.0 more directly, which would presumably not involve CLI plugins, but we don't know if that is going to happen or when.

**Comment by rhatdan** [comment] 2022-03-22 21:00
If we could do this simply, IE if an executable is in a directory, then we can show it in the help, and execute the commands, then I am fine with it.  If it involves huge engineering, then I agree it is not worth it.

**Comment by muayyad-alsadi** [comment] 2022-03-22 21:07
>  if an executable is in a directory, then we can show it in the help, and execute the commands

This is exactly this is what I want. Just execute the binary and display help.

**Comment by rhatdan** [comment] 2022-03-22 21:12
PRs welcome.  :^)

**Comment by ashley-cui** [comment] 2022-05-26 19:14
@karthikelango137

**Comment by karthikelango137** [comment] 2022-05-26 19:15
git it

**Comment by Luap99** [comment] 2022-05-30 12:44
Before there is to much work done on this we should agree on a design first.

cc @containers/podman-maintainers

**Comment by vrothberg** [comment] 2022-05-30 12:59
> Before there is to much work done on this we should agree on a design first.

https://github.com/docker/cli/issues/1534 should summarize the design quite well.  Certainly, we need to support the Docker-specific paths and also look up plugins with `s/docker/podman` in the paths.

**Comment by rhatdan** [comment] 2022-07-01 11:32
@karthikelango137 Any progress or should I assign this to someone else?

**Comment by karthikelango137** [comment] 2022-07-01 12:25
> @karthikelango137 Any progress or should I assign this to someone else?

I plan to begin next week. Do you think 4-5 weeks is enough time for this? I want to do it, but don't want to hold the team back.

**Comment by rhatdan** [comment] 2022-07-02 11:19
Start it and then we can follow up.  See if you can get small chunks in and we can have people help you out.

**Comment by rhatdan** [comment] 2022-08-02 10:18
@karthikelango137 did you make any progress?

**Comment by karthikelango137** [comment] 2022-08-02 12:21
> @karthikelango137 did you make any progress?

No, I haven't started it. Is this the route we are taking to support third party commands? I'm not sure if we confirmed this or not.

**Comment by cdoern** [comment] 2022-09-14 00:40
@rhatdan would this be something good for me to do? or is it low priority

**Comment by rhatdan** [comment] 2022-09-14 18:44
Sure as long as you keep it simple.

**Comment by vrothberg** [comment] 2023-10-18 14:28
I think we've discussed this idea in detail last year and concluded to not pursue it, so I am closing the issue as not planned.  Please reopen or speak up if I am mistaken.

**Closed by vrothberg** 2023-10-18 14:28 UTC
Labels: kind/feature
