### ISSUE TITLE
[Bug]:  Can't initialize iptables table NAT on MacOS

### ISSUE THREAD

**Issue by qoomon** [containers/podman#17285] opened 2023-01-30 16:54 UTC
### Issue Description

If I run `iptables --list -t nat` command with `docker` it works just fine, however it breaks with `podman`. 
What I am missing?

### Steps to reproduce the issue

Run`podman run -it --rm --cap-add=NET_ADMIN --cap-add=NET_RAW alpine`

**Run Commands in Container**
```shell
apk add iptables
iptables --list -t nat
```

### Describe the results you received

```
iptables v1.8.8 (legacy): can't initialize iptables table `nat': Permission denied
Perhaps iptables or your kernel needs to be upgraded.
```

### Describe the results you expected

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```

### podman info output

```shell
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 98.6
    systemPercent: 0.94
    userPercent: 0.47
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "37"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.1.6-200.fc37.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1193459712
  memTotal: 2065825792
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-3.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 7m 22.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 2359435264
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178887
  BuiltTime: Fri Nov 11 16:01:27 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

`Darwin Kernel Version 22.2.0`

### Additional information

I am the author of https://github.com/qoomon/docker-host and want to support podman as well.

**Comment by MR-KO** [comment] 2023-01-30 17:20
> ### Privileged Or Rootless
> None

Are you running podman rootful (aka privileged / root user), and if so, does the issue still occur if you run podman with `sudo`?

**Comment by MR-KO** [comment] 2023-01-30 17:41
It does work for me (output is as expected), even though your setup is practically identical to mine, with 2 exceptions. I am using ext4 instead of xfs (highly unlikely that's the culprit though), and you are using SELinux, I am not. However, I remember now running into this issue a long time ago as well. It may seem silly, but have you rebooted your machine? I seem to remember that that's what fixed my problem after some googling around, due to some kernel module (it might have been `iptable_nat`) not being loaded or something, and `insmod iptable_nat` not making the error go away.

**Comment by Luap99** [comment] 2023-01-30 17:47
Yes this look like the kernel module is not loaded. As root iptables will just load the module for you. However since you run podman rootless that is impossible.
The easy fix is to load the modules as root before you execute podman, alternatively you can run podman as root.
see https://github.com/containers/podman/blob/main/contrib/modules-load.d/podman-iptables.conf

Or you use iptables-nft this doesn't require root to load the modules AFAIK.

I am closing this because it is not a bug but feel free to continue the discussion.

**Closed by Luap99** 2023-01-30 17:47 UTC
Labels: kind/bug, remote, network

**Comment by Luap99** [comment] 2023-01-30 17:52
I just realized you are using podman machine, can you check if `/usr/lib/modules-load.d/podman-iptables.conf` is present in the VM? You can access the VM with `podman machine ssh`.

**Comment by qoomon** [comment] 2023-01-31 07:54
@Luap99 yes it is present with following content
```
# On fedora 36 ip_tables is no longer auto loaded and rootless user have no permsissions to load it.
# When we have actual nftables support in the future we might want to revisit this.
# If you use iptables-nft this is not needed.
ip_tables
ip6_tables
```

**Comment by qoomon** [comment] 2023-01-31 08:26
Strange It works on my machine as well after I added `nf_nat`kernel module to podman machine
```
podman machine ssh

modprobe nf_nat
```
This strange because I am only using `iptables` commands see https://github.com/qoomon/docker-host/blob/master/entrypoint.sh

**Comment by MR-KO** [comment] 2023-02-01 15:41
Strange, but maybe not unexpected if you check out [this page](https://www.kernelconfig.io/config_ip_nf_nat):

> iptables NAT support
modulename: iptable_nat.ko
configname: CONFIG_IP_NF_NAT
Linux Kernel Configuration
└─> Networking support
└─> Networking options
└─> Network packet filtering framework (Netfilter)
└─> IP: Netfilter Configuration
└─> iptables NAT support
> 
> This enables the `nat' table in iptables. This allows masquerading,
port forwarding and other forms of full Network Address Port
Translation. 

But glad that it now works for you! :)
