### ISSUE TITLE
After podman machine start, periodic "connect: operation timed out" messages appear in the executing window.

### ISSUE THREAD

**Issue by ekinano** [containers/podman#12132] opened 2021-10-28 22:01 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When I do

```
podman machine init
podman machine start
```

Everything works fine. However in the window where I executed those commands, I periodically get messages of the form `ERRO[0168] net.Dial() = dial tcp 140.211.169.196:443: connect: operation timed out`. These messages do not affect Podmans' normal operation, but they do seem weird enough that I don't know if they may indicate an underlying bug.

**Steps to reproduce the issue:**

In a terminal window:

1. `podman machine init`

2. `podman machine start`

Then wait for a minute or two for the first message to start appearing.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.4.1
```

**Output of `podman info --debug`:**

einan-mac:ocean-developer-tools einan$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "34"
  eventLogger: journald
  hostname: localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.11-200.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 2783457280
  memTotal: 4104060928
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 12m 42.18s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030821
  BuiltTime: Thu Sep 30 19:40:21 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.0

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
einan-mac:ocean-developer-tools einan$ brew info podman
podman: stable 3.4.1 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/3.4.1 (170 files, 39.5MB) *
  Poured from bottle on 2021-10-28 at 10:00:50
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✘, go-md2man ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Analytics
install: 16,611 (30 days), 31,175 (90 days), 58,729 (365 days)
install-on-request: 16,614 (30 days), 31,178 (90 days), 58,652 (365 days)
build-error: 0 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am on Mac OS Big Sur.

**Comment by ekinano** [comment] 2021-11-03 17:52
Any updates on this issue's status?

**Comment by kishorekkota** [comment] 2021-11-10 16:09
I have the same issue as well.

**Comment by rhatdan** [comment] 2021-12-18 11:45
@jwhonce @baude Thoughts on this.

**Comment by baude** [comment] 2022-01-13 19:32
Any chance the operation system went to "sleep" with the vm running prior to the error?

**Comment by e1m1** [comment] 2022-01-20 21:16
I experience the same behavior as well. On MacOS Big Sur. OS is not asleep prior to when I get the messages

**Comment by rhatdan** [comment] 2022-02-21 20:09
@baude didn't you say that you saw this happen?

**Comment by baude** [comment] 2022-02-21 20:14
i think they are a result of port mappings coming and going ?

**Comment by Robert-J-Slover** [comment] 2022-02-24 21:33
@baude, I see your question above:

> Any chance the operation system went to "sleep" with the vm running prior to the error?

I have a colleague who experienced this issue today and verifies that he accidentally put his MacBook to sleep when he went to lunch, instead of locking the screen. I don't believe he's otherwise seen this issue.

**Comment by jeffreybreen** [comment] 2022-03-06 15:46
I am also seeing these errors on my Mac laptop after podman's vm has been running for a long time (such as overnight), so the speculation around sleep or other power saving-related state changes makes sense.

My question -- and pardon my ignorance -- is more basic: what are these connection attempts? These do not look like local IP addresses. Is this some sort of dial-home functionality I am not aware of?

```
ERRO[2669] net.Dial() = dial tcp 67.219.144.68:443: connect: operation timed out 
ERRO[9706] net.Dial() = dial tcp 67.219.144.68:443: connect: operation timed out 
[...]
ERRO[26367] net.Dial() = dial tcp 67.219.144.68:443: connect: operation timed out 
ERRO[27394] net.Dial() = dial tcp 67.219.144.68:443: connect: operation timed out 
```

**Comment by jeffreybreen** [comment] 2022-03-06 15:54
Answering my own question...of course. Podman's machine is running CoreOS, so Zincati is probably just doing its normal auto-update thing....

```
[root@localhost config.d]# cat /usr/lib/zincati/config.d/10-auto-updates.toml 

# Enable auto-updates.
[updates]

# Boolean to enable auto-update logic.
# There is almost no case where disabling this is a good idea.
enabled = true

# Boolean to allow downgrading via updates logic.
# This provides an additional safety net against rogue servers,
# and allowing downgrades via Zincati is generally not recommended.
allow_downgrade = false
```

**Comment by habib** [comment] 2022-03-17 03:49
I see this behavior on the terminal even when my Mac laptop is actively being used. I'm on podman version 4.0.2 on an M1 Mac. 

`ERRO[27617] net.Dial() = dial tcp 140.211.169.206:443: connect: operation timed out` is the error message in the terminal.

**Comment by rhatdan** [comment] 2022-04-19 18:28
@baude @Luap99 any idea what is causing this?

**Comment by Luap99** [comment] 2022-04-20 09:03
gvproxy logs this error, no idea why. I think they should be ignored and not logged.
Also why do we keep gvproxy stdout/err open? This can cause a sigpipe when writing to the output and it is closed, which will kill the process if not handled correctly (at least on linux, no idea if macos has the same problem).

**Comment by geekykant** [comment] 2022-05-10 12:09
Any updates on this issue? The issue is when the podman machine is running. 
(podman Version: 3.4.4, Device MBP 2020)

<img width="968" alt="Screenshot 2022-05-10 at 5 37 31 PM" src="https://user-images.githubusercontent.com/27401142/167624677-3ac7a1ac-b5fa-41ed-8d36-96f08a37dc64.png">

**Comment by Luap99** [comment] 2022-05-10 12:25
Update to v4.1, I think this was fixed in https://github.com/containers/podman/pull/13942. stdin/stdout/stderr from gvproxy is redirected to /dev/null so it will no longer display these useless errors.

**Closed by Luap99** 2022-05-10 12:25 UTC
Labels: kind/bug, podman machine
