### ISSUE TITLE
 Rootless podman not working on latest CentOS8 Stream with cgroupsv2 enabled

### ISSUE THREAD

**Issue by MatMaul** [containers/podman#7768] opened 2020-09-24 21:31 UTC
**Steps to reproduce the issue:**

1. `podman run -it caddy`

It gives me this error:

`Error: writing file /sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/cgroup.subtree_control: No such file or directory: OCI runtime command not found error`

**Additional information you deem important (e.g. issue happens only occasionally):**

`crun` is installed and correctly reported when doing `podman info`.

When comparing `cgroup.subtree_control` values between my well behaving Fedora and this system I can see that any cgroup under `/sys/fs/cgroup/user.slice` has it empty, while my Fedora has `memory pids`.

After doing:
`echo "+pids +memory" >/sys/fs/cgroup/user.slice/cgroup.subtree_control`
`echo "+pids +memory" >/sys/fs/cgroup/user.slice/user-1001.slice/cgroup.subtree_control`

It works fine.

I am now pretty certain this is not a bug in podman/crun but some misconfiguration of systemd with cgroupv2 on CentOS 8 Stream, but I can't find the culprit myself and I would be really happy to have a working rootless cgroupv2 by default on the soon to be released CentOS/RHEL 8.3 :-)

Thanks in advance for your help.

**Output of `podman version`:**

```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Mon Sep 14 17:09:56 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.20-2.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 1019ecdeda3936be22162bb1cca308192145de53'
  cpus: 2
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: mymachine
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 4.18.0-236.el8.x86_64
  linkmode: dynamic
  memFree: 3486142464
  memTotal: 4018786304
  ociRuntime:
    name: crun
    package: crun-0.14.1-2.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.module_el8.3.0+475+c50ce30b.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 0
  swapTotal: 0
  uptime: 46m 57.76s
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/centos/.config/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 0
    stopped: 10
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-2.module_el8.3.0+475+c50ce30b.x86_64
      Version: |-
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/centos/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1001/containers
  volumePath: /home/centos/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600096196
  BuiltTime: Mon Sep 14 17:09:56 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.5-4.module_el8.3.0+491+298e1ad1.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Comment by xordspar0** [comment] 2020-09-24 21:40
Is this a duplicate of https://github.com/containers/podman/issues/7765?

**Comment by MatMaul** [comment] 2020-09-24 22:01
Not really, because mine happens even if we don't use any cpu limit like `--cpu 1`.
Also the `Delegate` fix mentioned there by Giuseppe is not working, there is something else missing.

This RedHat bug however seems to be about that (just found it):
https://bugzilla.redhat.com/show_bug.cgi?id=1732957

=> using `--cgroups=disabled` workaround is working.

Feel free to close this bug since it is properly tracked as a RHEL bug, I was a bit to quick to open it here.

**Closed** 2020-09-25 12:28 UTC
