### ISSUE TITLE
Rootless exec fails, unable to write to cgroup.procs

### ISSUE THREAD

**Issue by KenMacD** [containers/podman#14851] opened 2022-07-07 13:31 UTC
/kind bug

**Description**

When running a rootless container I'm unable to `podman exec` in to that container.

For example:

```
$ podman  run --rm  -it docker.io/ubuntu bash
root@e37dd236bf3a:/#
```

then in another terminal:

```
$ podman exec e37dd236bf3a id
Error: crun: writing file `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-e37dd236bf3ad816e50f82c8fa6204b18322aa924e3e46e590154abd69fc8adb.scope/container/cgroup.procs`: Permission denied: OCI permission denied
```

It does work though if I do:

```
$ systemd-run --user --scope podman exec e37dd236bf3a id
Running scope as unit: run-ra349205238984ea59d71e8f96729ede2.scope
uid=0(root) gid=0(root) groups=0(root)
```

Looking at the cgroup info I find:

```
$ cat /proc/self/cgroup
0::/user.slice/user-1000.slice/session-1.scope

$ cat /proc/BASH-PID/cgroup
0::/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-e37dd236bf3ad816e50f82c8fa6204b18322aa924e3e46e590154abd69fc8adb.scope/container
```

If I look in `/sys/fs/cgroup/user.slice/user-1000.slice` for `cgroup.procs` files I see that root owns the one in that directory, but the ones under libpod and my session are owned by me.

Looking at an `strace` for the read:

```
236520 openat(AT_FDCWD, "/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-e37dd236bf3ad816e50f82c8fa6204b18322aa924e3e46e590154abd69fc8adb.scope/container/cgroup.procs", O_WRONLY|O_CREAT|O_TRUNC, 0700) = 8
236520 write(8, "236524", 6)            = -1 EACCES (Permission denied)
```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.11
Built:        Mon Dec 31 20:00:00 1979
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /nix/store/4q9ypwjb817kgxz9hggy79l82vmxq5z6-conmon-2.1.2/bin/conmon
    version: 'conmon version 2.1.2, commit: '
  cpuUtilization:
    idlePercent: 97.73
    systemPercent: 0.79
    userPercent: 1.48
  cpus: 8
  distribution:
    codename: raccoon
    distribution: nixos
    version: "22.11"
  eventLogger: journald
  hostname: dn
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.18.7-zen1
  linkmode: dynamic
  logDriver: journald
  memFree: 12505907200
  memTotal: 33387560960
  networkBackend: cni
  ociRuntime:
    name: crun
    package: Unknown
    path: /nix/store/ghcin8ngpvj802xcsaivy94qbwgh9wix-crun-1.4.5/bin/crun
    version: |-
      crun version 1.4.5
      commit: 1.4.5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /nix/store/sxlh4dd2yf3gc2y5drflg1bs5ab7496p-slirp4netns-1.2.0/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 16693776384
  swapTotal: 16693776384
  uptime: 13h 48m 2.79s (Approximately 0.54 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/kenny/.config/containers/storage.conf
  containerStore:
    number: 20
    paused: 0
    running: 1
    stopped: 19
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /home/kenny/.local/share/containers/storage
  graphRootAllocated: 644245094400
  graphRootUsed: 538751905792
  graphStatus:
    Build Version: Btrfs v5.18.1
    Library Version: "102"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 262
  runRoot: /run/user/1000/containers
  volumePath: /home/kenny/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 315532800
  BuiltTime: Mon Dec 31 20:00:00 1979
  GitCommit: ""
  GoVersion: go1.17.11
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

NixOS, physical

**Comment by cdoern** [comment] 2022-07-07 13:36
this exact process works for me. I have recently rehauled cgroup handling in podman, some of which might be in 4.1.1 and some of which is not. Can you try running this off of the main branch and see if the issue goes away?

**Comment by edsantiago** [comment] 2022-07-07 20:08
I tried to reproduce on f35, no luck. I have no access to Nix, or even any idea what Nix is.

**Comment by KenMacD** [comment] 2022-07-07 21:42
Okay, so for some testing I started an f36 vm. It also doesn't happen by default so I started comparing differences. It looks like it happens if I set the owner on the session scope:

`chown kenny:kenny /sys/fs/cgroup/user.slice/user-1000.slice/session-1.scope`

Now sure why they're different though, or why it matters.

**Comment by giuseppe** [comment] 2022-07-07 21:57
what is the current cgroup (`cat /proc/self/cgroup`)?

If it is not owned by your user, then the kernel blocks moving the process out of it

**Comment by giuseppe** [comment] 2022-07-08 09:19
but what is the cgroup in the "normal host shell"?  Does it work better if you do something like `systemd-run --scope --user podman exec e37dd236bf3a id` ?

**Comment by giuseppe** [comment] 2022-07-08 21:30
isn't `/sys/fs/cgroup/user.slice/user-1000.slice/session-1.scope` owned by root?  At least on my system it is:

```
$ ls -ld /sys/fs/cgroup/user.slice/user-1000.slice/session-*.scope
drwxr-xr-x. 2 root root 0 Jun 23 15:17 /sys/fs/cgroup/user.slice/user-1000.slice/session-3.scope
```

**Comment by KenMacD** [comment] 2022-07-10 16:06
@giuseppe Nope, that's part of the issue. On Fedora it's owned by root, on NixOS (at least mine) it's owned by the user.

`$ ls /sys/fs/cgroup/user.slice/user-1000.slice/session-1.scope -al`
```ls
drwxr-xr-x kenny users 0  Fri Jul  8 14:48:10 2022 .
drwxr-xr-x root  root  0  Fri Jul  8 14:47:50 2022 ..
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cgroup.controllers
.r--r--r-- root  root  0  Fri Jul  8 14:47:50 2022 cgroup.events
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cgroup.freeze
.-w------- root  root  0  Fri Jul  8 14:59:02 2022 cgroup.kill
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cgroup.max.depth
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cgroup.max.descendants
.rw-r--r-- kenny users 0  Fri Jul  8 14:49:13 2022 cgroup.procs
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cgroup.stat
.rw-r--r-- kenny users 0  Fri Jul  8 14:47:50 2022 cgroup.subtree_control
.rw-r--r-- kenny users 0  Fri Jul  8 14:47:50 2022 cgroup.threads
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cgroup.type
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cpu.idle
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 cpu.max
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cpu.max.burst
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cpu.pressure
.r--r--r-- root  root  0  Fri Jul  8 14:47:50 2022 cpu.stat
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 cpu.weight
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cpu.weight.nice
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 cpuset.cpus
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cpuset.cpus.effective
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cpuset.cpus.partition
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 cpuset.mems
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 cpuset.mems.effective
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 io.latency
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 io.max
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 io.pressure
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 io.prio.class
.r--r--r-- root  root  0  Fri Jul  8 14:47:50 2022 io.stat
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 io.weight
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 memory.current
.r--r--r-- root  root  0  Fri Jul  8 14:47:50 2022 memory.events
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 memory.events.local
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 memory.high
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 memory.low
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 memory.max
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 memory.min
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 memory.numa_stat
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 memory.oom.group
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 memory.pressure
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 memory.stat
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 memory.swap.current
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 memory.swap.events
.rw-r--r-- root  root  0  Fri Jul  8 14:59:02 2022 memory.swap.high
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 memory.swap.max
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 pids.current
.r--r--r-- root  root  0  Fri Jul  8 14:59:02 2022 pids.events
.rw-r--r-- root  root  0  Fri Jul  8 14:47:50 2022 pids.max
drwxr-xr-x root  root  0  Fri Jul  8 14:48:10 2022 user
```

**Comment by giuseppe** [comment] 2022-07-10 18:34
From the `cgroups(7)` man page:
```
      Some delegation containment rules ensure that the delegatee can move processes between cgroups within the delegated subtree, but can't move processes from outside the delegated subtree into  the  sub‐
       tree or vice versa.  A nonprivileged process (i.e., the delegatee) can write the PID of a "target" process into a cgroup.procs file only if all of the following are true:

       *  The writer has write permission on the cgroup.procs file in the destination cgroup.

       *  The  writer  has  write  permission  on  the cgroup.procs file in the nearest common ancestor of the source and destination cgroups.  Note that in some cases, the nearest common ancestor may be the
          source or destination cgroup itself.  This requirement is not enforced for cgroups v1 hierarchies, with the consequence that containment in v1 is less strict than in v2.  (For example,  in  cgroups
          v1 the user that owns two distinct delegated subhierarchies can move a process between the hierarchies.)

       *  If the cgroup v2 filesystem was mounted with the nsdelegate option, the writer must be able to see the source and destination cgroups from its cgroup namespace.

       *  In  cgroups  v1:  the effective UID of the writer (i.e., the delegatee) matches the real user ID or the saved set-user-ID of the target process.  Before Linux 4.11, this requirement also applied in
          cgroups v2 (This was a historical requirement inherited from cgroups v1 that was later deemed unnecessary, since the other rules suffice for containment in cgroups v2.)
```

I think your configuration doesn't still honor the second rule for moving a process to a different cgroup as you'd have to own the `user-1000.slice` cgroup.

I am closing the issue but please keep adding more comments.  Also reopen if I am wrong and you still think it is an issue in Podman itself :-)

**Closed by giuseppe** 2022-07-10 18:34 UTC
Labels: kind/bug

**Comment by KenMacD** [comment] 2022-07-11 02:04
Thanks @giuseppe! I did some more digging in to permissions and the like. I found that if I have `lxcfs` installed I no longer end up with the `nsdelegate` option on the `cgroup2` mount. Removing `lxcfs` (I wasn't actually using it currently) makes everything work as expected.

Hopefully this helps others. It sounds like it's not a Podman bug, but maybe it's worth including the `nsdelegate` requirement in the rootless docs? (or the mount options in the `podman info --debug` output?)

**Comment by edgex004** [comment] 2022-10-17 01:52
I seem to be running into the same issue on Fedora 36 with podman 4.2.0. I can reproduce in the same manner as listed on this ticket. `podman  run --rm  -it docker.io/ubuntu bash` followed by `podman exec 36fd7d5165cc id` in another terminal leads to:
```
Error: crun: writing file `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-36fd7d5165cc2cba2b9fcddc37ae9f60d2e75424315ce8b1f007d10dc0ca890a.scope/container/cgroup.procs`: Permission denied: OCI permission denied
```

I checked that session is owned by root:
```
$ ls -ld /sys/fs/cgroup/user.slice/user-1000.slice/session-*.scope
drwxr-xr-x. 2 root root 0 Oct 16 17:41 /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope
```
And that `nsdelegate` is enabled for `cgroup2`:
```
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate,memory_recursiveprot)
```

@giuseppe you mentioned that you thought the kernel would block if the cgroup is not owned by the user. You also mentioned that root owns the cgroup on your system (just like mine). Any ideas of what I might be doing wrong?

**Comment by giuseppe** [comment] 2022-10-17 07:46
what is the current cgroup where podman is running in?  You can check it with `cat /proc/self/cgroup`

**Comment by edgex004** [comment] 2022-10-19 00:38
@giuseppe 
```
$ cat /proc/self/cgroup
0::/user.slice/user-1000.slice/session-2.scope
```

**Comment by grzs** [comment] 2022-12-06 13:46
If someone else still suffers from this issue: the solution for me (Debian 10) was to install dbus-user-session.

**Comment by ssbarnea** [comment] 2022-12-16 13:29
@grzs We get the same error with github runners (ubuntu) where dbus-user-session is already installed. If anyone has other ideas... 


Podman reports 3.4.4
