### ISSUE TITLE
macOS `podman machine` mounts are lost if VM is rebooted

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#18592] opened 2023-05-16 16:30 UTC
### Issue Description

If the `podman machine` VM is restarted by a reboot/shutdown command run from within the VM (such as after installing `qemu-user-static` for additional platform support), then when the VM restarts the host mounts (such as `/Users`) are no longer present, and difficult to diagnose errors stating that stat() is failing on files are thrown when data mounted from the host is accessed.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman machine ssh "sudo systemctl reboot";
2. Wait for VM to restart;
3. Try to run a container with a volume from the host on macOS.

### Describe the results you received

```
Error: statfs /Users/<user>/<path>/<file>: no such file or directory
```

… when the specified file clearly exists (on the host).

### Describe the results you expected

Mounts should be restored when the `podman machine` VM reboots, so that volumes defined on the host work transparently.

It would also be beneficial to allow podman on macOS to indicate what's happening if a file or directory can't be found on the `podman machine` VM, but does exist for the host OS.

### podman info output

```yaml
% podman info
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 86.96
    systemPercent: 1.69
    userPercent: 11.34
  cpus: 1
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.2.13-300.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 951304192
  memTotal: 2048839680
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.4-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 12h 11m 20.00s (Approximately 0.50 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 8120274944
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 47
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681486942
  BuiltTime: Fri Apr 14 16:42:22 2023
  GitCommit: ""
  GoVersion: go1.20.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0

```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

macOS 13.3.1 (a), Intel Core i5.

### Additional information

`podman machine stop && podman machine start` does resolve this issue, but it was very non-obvious to diagnose :(

**Comment by Luap99** [comment] 2023-05-16 16:33
Duplicate of #15976

**Closed by Luap99** 2023-05-16 16:33 UTC
Labels: kind/bug, remote
