### ISSUE TITLE
--uidmap fails with `EOF: OCI runtime error`

### ISSUE THREAD

**Issue by awerlang** [containers/podman#8182] opened 2020-10-29 14:22 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running a container with `--uidmap 0:0:1001` fails. Possibly because the range overlaps with more than one uidmap on the system.

**Steps to reproduce the issue:**

1. `podman run --rm --uidmap=0:0:1001 -u 1000 debian id -u`

**Describe the results you received:**

`Error: container_linux.go:370: starting container process caused: process_linux.go:338: getting the final child's pid from pipe caused: EOF: OCI runtime error`

**Describe the results you expected:**

`1000`

Or, at least a better error message.

**Additional information you deem important (e.g. issue happens only occasionally):**

This works:

```
$ podman run --rm --uidmap=0:0:1 --uidmap=1000:1000:1 -u 1000 debian id -u
1000
```

My goal is to emulate `--userns=keep-id`, which is failing with the nvidia-container hook.

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.13.15
Built:        Tue Sep 29 21:00:00 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-1.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: unknown'
  cpus: 8
  distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20201025"
  eventLogger: journald
  hostname: host
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.15-1-default
  linkmode: dynamic
  memFree: 8953794560
  memTotal: 16674750464
  ociRuntime:
    name: runc
    package: runc-1.0.0~rc92-1.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.0-1.3.x86_64
    version: |-
      slirp4netns version 1.0.0
      commit: unknown
      libslirp: 4.3.1
  swapFree: 10737414144
  swapTotal: 10737414144
  uptime: 1h 17m 10.75s (Approximately 0.04 days)
registries:
  search:
  - registry.opensuse.org
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 0
    stopped: 8
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-2.1.x86_64
      Version: |-
        fusermount3 version: 3.10.0
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.10.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/user/local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 180
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601424000
  BuiltTime: Tue Sep 29 21:00:00 2020
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-1.1.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by rhatdan** [comment] 2020-10-29 21:22
@giuseppe PTAL

**Comment by giuseppe** [comment] 2020-10-30 07:03
You are right, the issue is that the specified new mappings overlap on two mappings in the current user namespace.  That error is coming directly from the kernel.

Not sure why it is done this way in the kernel, probably to simplify the implementation

**Comment by rhatdan** [comment] 2020-10-31 10:24
Does this mean this is unfixable, other then to improve the error message?

**Comment by giuseppe** [comment] 2020-10-31 18:36
> Does this mean this is unfixable, other then to improve the error message?

we could fix it if we take care of splitting the specified mappings, possibly in the OCI runtime, but I think it is better to try to fix it in the kernel first.  @ebiederm what do you think?

The error message above is generated by runc.  With crun it is:

```
$ podman run --rm --uidmap=0:0:1001 fedora true
Error: writing file `/proc/553298/gid_map`: Operation not permitted: OCI permission denied
```

**Comment by giuseppe** [comment] 2020-12-01 10:35
I've proposed a patch for the kernel: https://lkml.kernel.org/lkml/20201126100839.381415-1-gscrivan@redhat.com/

**Comment by rhatdan** [comment] 2020-12-24 11:08
@giuseppe isn't the PR that you just opened to related to this?

**Comment by rhatdan** [comment] 2021-01-25 14:08
@giuseppe Any progress?

**Comment by giuseppe** [comment] 2021-01-26 13:44
the kernel patch is stuck on review, but it is fixed now in Podman so we can close the issue here

**Closed by giuseppe** 2021-01-26 13:44 UTC
Labels: kind/bug
