### ISSUE TITLE
podman remote: build with `--from oci-archive:./image.ociarchive` should copy the image to the remote

### ISSUE THREAD

**Issue by dustymabe** [containers/podman#15804] opened 2022-09-14 15:19 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

I left it as a bug, but this could very well be a feature request.

**Description**

Note: I would have opened this issue against buildah, since it is build related, but the relationship with `podman --remote` made me open it here instead. If this should be a `buildah` bug please transfer it to that repo.

It would be nice if someone has an environment set up to use `podman --remote` that if they provided a local path to an ociarchive to `podman build --from` that the image get properly copied/imported/used on the remote for the build.  

**Steps to reproduce the issue:**

1. export CONTAINER_HOST=foo ; export CONTAINER_SSHKEY=bar

2. curl -O http://example.com/image.ociarchive 

3. podman build --from oci-archive:./image.ociarchive

**Describe the results you received:**

The path to the image is attempted to be found on the remote and fails:

```
2022-09-13 19:23:19,203 INFO - Running command: ['podman', 'build', '--cache-ttl=0.1s', '--tag=localhost:x86_64-c940faa', '/tmp/tmpf85qmpcc/', "--label=build.commit.id='c940faad56002dc881ee5a707de42ba4951d4ba6'", "--label=build.commit.re
f='main'", "--label=build.commit.url='https://github.com/dustymabe/dustymabe.com.git'", "--label=build.commit.author=''Dusty Mabe <dusty@dustymabe.com>'", "--label=build.commit.date='Fri Nov 5 15:19:18 2021 -0400'", "--label=build.commit
.message='Some more updates for the 2021-11-02 post''", '--from=oci-archive://f37.ociarchive']                                                                                                                                               
STEP 1/23: FROM oci-archive://f37.ociarchive                                                                                                                                                                                                 
Error: error creating build container: creating temp directory: open /f37.ociarchive: no such file or directory
```

**Describe the results you expected:**

Argument to `--from` to be copied/used on the remote.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[coreos-assembler]$ podman version
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 14:42:17 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

<details>

```
[coreos-assembler]$ podman info
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 90.39
    systemPercent: 1.73
    userPercent: 7.88
  cpus: 12
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: file
  hostname: dc453b08cad1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 1
      size: 999
    - container_id: 1000
      host_id: 1001
      size: 64535
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 1
      size: 999
    - container_id: 1000
      host_id: 1001
      size: 64535
  kernel: 5.18.17-100.fc35.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 476622848
  memTotal: 67364122624
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 10570690560
  swapTotal: 12884893696
  uptime: 737h 23m 24.00s (Approximately 30.71 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/builder/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/builder/.local/share/containers/storage
  graphRootAllocated: 607574138880
  graphRootUsed: 534589915136
  graphStatus:
    Backing Filesystem: overlayfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/builder/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228937
  BuiltTime: Thu Aug 11 14:42:17 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0


```

</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ rpm -q podman
podman-4.2.0-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment] 2022-09-14 16:10
Duplicate of https://github.com/containers/podman/issues/15141?

**Comment by dustymabe** [comment] 2022-09-14 18:28
yes perhaps it is a duplicate of #15141. IIUC making this work wouldn't be too hard (just copying over a file to the remote and making it available), correct? It's just if it's worth it or not to support it.

**Comment by rhatdan** [comment] 2022-09-14 19:22
Please continue the conversation on #15141

**Closed** 2022-09-14 19:21 UTC
Labels: kind/bug
