### ISSUE TITLE
NameRegex used for network does not match docker

### ISSUE THREAD

**Issue by jjwatt** [containers/podman#18263] opened 2023-04-18 19:42 UTC
### Issue Description

podman with `docker-compose` does not behave as expected when run from directories named with an initial underscore (e.g., `_sources` or `_hello`). `docker` will create the network, but podman won't.

It might be worth pointing out that one `NameRegex` seems to be used for nearly everything: volumes, networks, etc.

`docker` actually does not seem to care much about what you name networks. I've done `docker network create '&'` etc.

### Background
The ansible AWX team uses ansible playbooks to generate configuration files and container scripts as well as `docker-compose` into a hard-coded `_sources` directory. I don't want to put docker on my laptop, so I've been trying to get the dev environment to work with `podman` driving the `docker-compose` dev build. I hit this issue pretty early on. I'm fixing the dev build to allow for changing the build output directory here: https://github.com/ansible/awx/pull/13682, but I am betting other people have run into this, too. I probably wouldn't have even opened this, but on a re-read of the Podman in Action book, I found this:

> The Podman team treats any problem concerning a
> difference with the Docker API as a bug. If the API works against the Docker 
> daemon, it must work against the Podman service.

And, it seems like this fits that criteria.

Because of the way `docker-compose` works, a user does not have to explicitly pick a network name to fail, either. If the user's `docker-compose.yml` file is in a directory named  `_name`, `docker-compose` will try to create a default network named `_name_default`. 

### Steps to reproduce the issue

Steps to reproduce the issue

## Simple
1. `podman network create _sources`

## Original Reproducer
1. `export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock`
2. Have a `docker-compose.yml` in a directory named `_sources` and call `docker-compose` on it with podman posing as docker.

### Describe the results you received

```Error: network name _sources_default invalid: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*: invalid argument```

### Describe the results you expected

The expected results are for `docker-compose` to create the network named `_sources` with podman in the same way it does with docker.

### podman info output

```yaml
I don't think it's needed. Will provide out of band over chat or email if it is. So far, see it in
- RHEL8
- Fedora 37
- CentOS 9 stream
And on freshly built podman `main` on CentOS 9 stream
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional information

A [search of the podman repo](https://github.com/containers/podman/issues?q=NameRegex) finds some related issues and PRs that I used for reference. It's outside of the scope of this issue, but I don't think our validation of volume and container names matches Docker, either.
- #4184 podman network create should validate
- #2793 Alter container/pod/volume name regexp to match Docker
- #4188 podman network create: validate user input

**Comment by Luap99** [comment] 2023-04-19 08:16
Duplicate of #17746

**Closed by Luap99** 2023-04-19 08:16 UTC
Labels: kind/bug
