### ISSUE TITLE
error running container: from /usr/bin/crun creating container for [/bin/sh -c mkdir -p /config]: mount `/home/user/.local/share/containers/storage/overlay-containers/d67e7e4f18895db83e729e8321e0c9f791f5c1407495c8c8dc5e494da5997798/userdata/overlay/3392401135/merge` to `/tmp`: Operation not permitted[Bug]: 

### ISSUE THREAD

**Issue by ssyedabthahir** [containers/podman#17346] opened 2023-02-03 03:15 UTC
### Issue Description

Team,

I have below issue when i try to create the image with podman (version 4.3.1) and any help is appreciated.

Dockerfile:

FROM docker.io/openjdk:17-jdk-alpine
VOLUME /tmp
EXPOSE 9440
RUN mkdir -p /config
ADD keystore.jks /config/keystore.jks
ADD target/SampleWebService-0.1.jar SampleWebService-0.1.jar
ENTRYPOINT ["sh", "-c", "java -jar SampleWebService-0.1.jar"]

Error:
error running container: from /usr/bin/crun creating container for [/bin/sh -c mkdir -p /config]: mount `/home/user/.local/share/containers/storage/overlay-containers/d67e7e4f18895db83e729e8321e0c9f791f5c1407495c8c8dc5e494da5997798/userdata/overlay/3392401135/merge` to `/tmp`: Operation not permitted

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman -t samplewebserice:1.0 .
2.
3.

### Describe the results you received

Describe the results you received

STEP 1/7: FROM docker.io/openjdk:17-jdk-alpine
STEP 2/7: VOLUME /tmp
--> Using cache 0501cef2a945febf31e82f0578d35332918868a05c91d51ae46729b3b8d1ba13
--> 0501cef2a94
STEP 3/7: EXPOSE 9440
--> Using cache 60f2f069be6c56516f2446d0e13c36589921cfeb642df3800304e472649f61eb
--> 60f2f069be6
STEP 4/7: RUN mkdir -p /config
error running container: from /usr/bin/crun creating container for [/bin/sh -c mkdir -p /config]: mount `/home/user/.local/share/containers/storage/overlay-containers/d67e7e4f18895db83e729e8321e0c9f791f5c1407495c8c8dc5e494da5997798/userdata/overlay/3392401135/merge` to `/tmp`: Operation not permitted
: exit status 1
Error: building at STEP "RUN mkdir -p /config": while running runtime: exit status 1

### Describe the results you expected

Creating imaged successfully

### podman info output

```shell
podman Desktop 4.3.1 running in windows 10
```

### Podman in a container

Yes

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by ssyedabthahir** [comment] 2023-02-03 21:03
Team - Any update?

**Comment by mheon** [comment] 2023-02-03 21:07
@flouthoc PTAL

**Comment by amanfangeria980** [comment] 2023-02-06 06:14
can anyone assign this issue to me. I wanna work upon this...

**Comment by Luap99** [comment] 2023-02-06 16:57
@amanfangeria980 sure

**Comment by ssyedabthahir** [comment] 2023-02-06 17:38
Hello Team,

I had resolved the issue by uninstalling podman 4.3.1 and installing 4.1.0 version and now it is working as expected.

Now i tried with simple DB connect bean in Java and build an image.. 

C:\Users\ssamsudeen2>podman run -p 8080:8080 -d dbconnect:1.0
cfbc0c8fbe263d3ff35786c4b55968eb9b90f68ca75f8d6555e3adf580c2d586

Log:
C:\Users\ssamsudeen2>podman logs cfbc0c8fbe263d3ff35786c4b55968eb9b90f68ca75f8d6555e3adf580c2d586
Feb 06, 2023 5:32:29 PM com.gxo.podman.db.connect.ConnectDB main
INFO: Getting connection...
Feb 06, 2023 5:32:35 PM com.gxo.podman.db.connect.ConnectDB main
INFO: Unable to process java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection

Docker file:
FROM docker.io/openjdk:17-jdk-alpine
VOLUME /tmp
EXPOSE 8080
ADD DBConnectivity.jar DBConnectivity.jar
ENTRYPOINT ["sh", "-c", "java -jar DBConnectivity.jar"]

I am calling DB through VPN and not sure if we need to add any other steps to make this DB successful from podman desktop to external DB connection.

Code:
public class ConnectDB {

	private static final Logger logger = Logger.getLogger(ConnectDB.class.getName());  
	public static void main(String[] args) {
		Connection conn = null;
		try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (ClassNotFoundException e) {
            logger.info("Where is your Oracle JDBC Driver?" + e.getMessage());
            e.printStackTrace();
            return;
        }
		
		try {
			logger.info("Getting connection...");
			String url = "jdbc:oracle:thin:@*******:****:****";
			Properties props = new Properties();
			props.put("user", "*******");
			props.put("password", "********");
			props.put("SetBigStringTryClob", "true");
			conn = DriverManager.getConnection(url, props);
			conn.setAutoCommit(true);
			logger.info("Got connection!" + conn);
		} catch (Exception e) {
			logger.info("Unable to process "  + e);
		}
	}
}

**Comment by amanfangeria980** [comment] 2023-02-08 10:56
Hey @Luap99, I think the issue is resolved the user itself, so you can close this PR :)

**Closed** 2023-02-08 11:39 UTC
Labels: kind/bug
