### ISSUE TITLE
Rootless networking backend info w/ podman info

### ISSUE THREAD

**Issue by danishprakash** [containers/podman#22356] opened 2024-04-12 06:58 UTC
### Feature request description

We currently show networking backend information for rootful containers but not for rootless containers, though we show information about both pasta and slirp4netns. But since we're in a middle of a transition w/ the rootless networking backends, it'd be helpful to show rootless networking backend as part of `podman info`. 

I'll raise a PR if the idea sounds good.

### Suggest potential solution

`NetworkBackendInfo` could show information for both rootless and rootfull containers.

**Comment by Luap99** [comment] 2024-04-12 09:49
Duplicate of #22172

**Closed by Luap99** 2024-04-12 09:49 UTC
Labels: kind/feature, network
