### ISSUE TITLE
Setting existing applehv machine to rootful prevents machine restart

### ISSUE THREAD

**Issue by jfrantzius** [containers/podman#21442] opened 2024-01-30 17:51 UTC
### Issue Description

When an already initialized `applehv` machine is made rootful, it cannot be restarted anymore

### Steps to reproduce the issue

In Mac shell:
```
export CONTAINERS_MACHINE_PROVIDER=applehv
podman machine init
podman machine start

podman machine stop
podman machine set --rootful
podman system connection default podman-machine-default-root
podman machine start

podman machine stop
podman --debug machine start
```

### Describe the results you received

Machine refuses to start with same error message as in https://github.com/containers/podman/issues/21288#issuecomment-1916557530 :
```
❯
podman --debug machine start
INFO[0000] podman filtering at log level debug
DEBU[0000] Using Podman machine with `applehv` virtualization provider
DEBU[0000] connection refused: http://localhost:50478/vm/state
Starting machine "podman-machine-default"
DEBU[0000] connection refused: http://localhost:50478/vm/state
DEBU[0000] creating runtimeDir: /var/folders/04/bfd6wk9n385174twdm8hx_dc0000gp/T/podman
DEBU[0000] gvproxy binary being used: /opt/homebrew/Cellar/podman/HEAD-2ba3605/libexec/podman/gvproxy
DEBU[0000] [-debug -mtu 1500 -ssh-port 50479 -listen-vfkit unixgram:///var/folders/04/bfd6wk9n385174twdm8hx_dc0000gp/T/podman/gvproxy.sock -forward-user root -forward-identity /Users/joerg.frantzius/.local/share/containers/podman/machine/machine -forward-sock /Users/joerg.frantzius/.local/share/containers/podman/machine/applehv/podman.sock -forward-dest /run/podman/podman.sock -pid-file /var/folders/04/bfd6wk9n385174twdm8hx_dc0000gp/T/podman/gvproxy.pid]
DEBU[0000] gvproxy unixgram socket "/var/folders/04/bfd6wk9n385174twdm8hx_dc0000gp/T/podman/gvproxy.sock" not found: stat /var/folders/04/bfd6wk9n385174twdm8hx_dc0000gp/T/podman/gvproxy.sock: no such file or directory
Error: gvproxy exited unexpectedly with exit code 0
DEBU[0000] Shutting down engines
```

### Describe the results you expected

Machine should start up

### podman info output

```yaml
podman version
Client:       Podman Engine
Version:      5.0.0-dev
API Version:  5.0.0-dev
Go Version:   go1.21.6
Git Commit:   7ed4478c087303b58c082188088a03e2c533d796
Built:        Tue Jan 30 01:06:53 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.8.3
API Version:  4.8.3
Go Version:   go1.21.5
Built:        Wed Jan  3 15:10:40 2024
OS/Arch:      linux/arm64

podman info
host:
  arch: arm64
  buildahVersion: 1.33.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.8-2.fc39.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 86.67
    systemPercent: 2.64
    userPercent: 10.68
  cpus: 4
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "39"
  eventLogger: journald
  freeLocks: 2040
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.6.9-200.fc39.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 65806336
  memTotal: 1982877696
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.9.0-1.fc39.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.9.0
    package: netavark-1.9.0-1.fc39.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.9.0
  ociRuntime:
    name: crun
    package: crun-1.12-1.fc39.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.12
      commit: ce429cb2e277d001c2179df1ac66a470f00802ae
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231204.gb86afe3-1.fc39.aarch64
    version: |
      pasta 0^20231204.gb86afe3-1.fc39.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc39.aarch64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 5m 28.00s
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  insecure-registry.net:
    Blocked: false
    Insecure: true
    Location: insecure-registry.net
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: insecure-registry.net
    PullFromMirror: ""
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 3
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 4823834624
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 20
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.8.3
  Built: 1704291040
  BuiltTime: Wed Jan  3 15:10:40 2024
  GitCommit: ""
  GoVersion: go1.21.5
  Os: linux
  OsArch: linux/arm64
  Version: 4.8.3
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

podman installed with `brew install podman --HEAD`

### Additional information

**The workaround** is to use `podman machine init --rootful` when creating the machine, avoiding the use of `podman machine set --rootful`. At least the machine survived a number of restarts, also after restarting the host (laptop).

The error message is the same as in https://github.com/containers/podman/issues/21288

**Comment by mheon** [comment] 2024-01-31 20:33
@baude PTAL

**Comment by jakecorrenti** [comment] 2024-03-19 13:08
I am unable to reproduce this on the current `main` branch

**Comment by baude** [comment] 2024-06-25 18:08
Closing as fixed.

**Closed by baude** 2024-06-25 18:08 UTC
Labels: kind/bug, remote, macos, machine
