### ISSUE TITLE
podman run --ip6 support

### ISSUE THREAD

**Issue by vikas-goel** [containers/podman#10373] opened 2021-05-18 03:13 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Is there a timeline for supporting `podman run --ip6` option? The podman manual says the option is not implemented. We are using IPv6 with Docker in RHEL7.9 and planning to move to RHEL 8+ with podman.

**Comment by aojea** [comment] 2021-05-24 21:21
podman supports ipv6 and dual-stack since https://github.com/containers/podman/pull/8143 that is 2.2.0 IIRC

**Comment by vikas-goel** [comment] 2021-05-25 01:09
Hello @aojea, @rhatdan,
Is it possible to update podman-run manual to state this? It still says IPv6 not implemented.

**Comment by mheon** [comment] 2021-05-25 02:18
I don't believe the `--ipv6` flag for static v6 addresses is implemented yet.

**Comment by rugk** [comment] 2021-07-09 11:54
Duplicate of https://github.com/containers/podman/issues/7511 (?)

**Comment by rhatdan** [comment] 2021-11-29 21:48
This is being worked on and can be followed in github.com/containers/netavark.

**Comment by Luap99** [comment] 2021-12-15 15:43
Lets close this as dup of #7511.

**Closed by Luap99** 2021-12-15 15:43 UTC
Labels: kind/feature, network, 4.0
