### ISSUE TITLE
Building of Podman 2.0.x packages fails in Kubic Project  due to Go < 1.13 on Ubuntu 18.04  

### ISSUE THREAD

**Issue by alitvak69** [containers/podman#6875] opened 2020-07-07 03:40 UTC
/kind bug

**Description**

I wonder if Go can be bumped to 1.13 in packages on the Open Build service for 
18.04 <= ubuntu < 20.04 and possible Debian.  It seems that recent changes are preventing podman 2.0 from being built with the earlier versions of Go.  I was able to build podman 2.0.1 using Go 1.13 from custom ppa on my box, but developers here use and test with your repo.

**Comment by afbjorklund** [comment] 2020-07-07 06:40
Same story for CRI-O, guess you just have to use the older packages

**Comment by rhatdan** [comment] 2020-07-07 10:48
The issue is that newer versions of Kubernetes are being vendored in that require newer compilers.

**Comment by alitvak69** [comment] 2020-07-07 11:55
I don't disagree with this notion but can the current Kubic Project maintainers start using newer Go for building latest packages?  Or does it mean, for example, Ubuntu Bionic will not be supported for version 2.0 and above?  That would be pity as one doesn't need to upgrade go or install go for runtime.

**Comment by vrothberg** [comment] 2020-07-07 12:06
@lsm5 PTAL

The go world and the "traditional" world of Linux distributions are quite different. Go is rolling fast and with it the entire ecosystem around it, including most container tools as most are built on top of go.

We tried to defer the requirement on go 1.13+ as much as possible but our hands are tied to a certain degree as too many dependencies jumped on go 1.13 which introduced some nice new APIs for error handling.

Not being able to update beyond Podman 2.0 is not really acceptable, so we need to find a solution. Let's figure out the options we have.

I have high hopes that the Podman package for Debian will eventually bubble up in Ubuntu. This will make our lifes much easier and the Ubuntu/Debian community has full control over what's happening when.

**Comment by lsm5** [comment] 2020-07-07 12:10
@alitvak69 I just learned from the OBS guys how to add the backports repos to Debian 10. I should be able to fix Debian today, I'll look into the older Ubuntus as well.

**Comment by vrothberg** [comment] 2020-07-07 12:14
Awesome, thanks a ton @lsm5 !!!

**Comment by alitvak69** [comment] 2020-07-07 12:15
@lsm5 and @vrothberg Thank you for your ongoing support and attention to this matter.

**Comment by afbjorklund** [comment] 2020-07-07 15:43
> The go world and the "traditional" world of Linux distributions are quite different. Go is rolling fast and with it the entire ecosystem around it, including most container tools as most are built on top of go.

Eventually even the enterprise linux world catches up to the fact that tools evolve faster than systems, and we get things like "application streams" to allow multiple versions of for instance the `go` compiler.

**Comment by vrothberg** [comment] 2020-07-07 15:49
I think the enterprise world does that already, at least we (Red Hat) do. I guess more distributions will follow but it will take time.

**Comment by afbjorklund** [comment] 2020-07-07 16:26
In the old days, we just did hacks like "go1.13-1.13.9" or something. But then you get to also backport all the required tools first.

If you don't care so much, you can just use the network and do `go get golang.org/dl/go1.13.9` as per vendor documentation.

https://golang.org/doc/install#extra_versions

But I think the OpenSUSE build system _does_ care...

So it would be much better with a proper deb package.

BTW; I think they upgraded to 1.14 for 1.19 ;-)

**Comment by lsm5** [comment] 2020-07-07 17:46
@alitvak69 I was able to build for Debian 10 x86_64, but I can't seem to find anything newer than golang 1.10 in Ubuntu versions older than 20.04. So, I can either request ubuntu people to backport it or build it myself on OBS. Might be worth doing both, but may take a few days unless I can reuse current packaging sources without any change.

**Comment by afbjorklund** [comment] 2020-07-07 17:53
@lsm5:
I reused your packaging for podman 1.9.3, in order to fix the podman-remote issues

Good that it works both ways

**Comment by lsm5** [comment] 2020-07-07 17:55
> @lsm5:
> I reused your packaging for podman 1.9.3, in order to fix the podman-remote issues
> 
> Good that it works both ways

@afbjorklund sorry, reused where exactly? are you building it separately somewhere?

**Comment by afbjorklund** [comment] 2020-07-07 18:01
I just used “pbuilder”

**Comment by alitvak69** [comment] 2020-07-07 19:31
would adding custom ppa I used help you  at least in short term?

**Comment by lsm5** [comment] 2020-07-07 19:58
> would adding custom ppa I used help you at least in short term?

Na, OBS guys aren't gonna agree to it. And, AIUI, there's no way for me to simply add some PPA. I'll look into adding the golang package myself.

**Comment by lsm5** [comment] 2020-07-08 14:41
@alitvak69 @afbjorklund dear valued members of the podman community, ask and ye shall receive :)
https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman

Enjoy :)

**Comment by lsm5** [comment] 2020-07-08 15:08
Closing, I guess all distros and arches are happy now except Debian Unstable ppc64le, which is an OBS problem that I nag them often about.

**Closed by lsm5** 2020-07-08 15:08 UTC
Labels: Packaging, debian, kind/bug, obs, ubuntu

**Comment by alitvak69** [comment] 2020-07-09 06:47
Thank you for the amazing turn around!
