### ISSUE TITLE
Pod Containers Cannot Reach Internet

### ISSUE THREAD

**Issue by quantum77** [containers/podman#9805] opened 2021-03-24 16:20 UTC
/kind bug

I've pulled secns/unbound and put the unbound container into an unbound pod.  I start the pod rootlessly with:
`# unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.service
# autogenerated by Podman 3.0.1
# Mon Mar 22 10:49:50 PDT 2021

[Unit]
Description=Podman unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.service
Documentation=man:podman-generate-systemd(1)
Wants=network.target
After=network-online.target
Requires=container-a4a46146b158101f3932e9cca6d205182f43acddd3afee3daee9d5168e1bb275.service
Before=container-a4a46146b158101f3932e9cca6d205182f43acddd3afee3daee9d5168e1bb275.service

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStartPre=/bin/rm -f %t/unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.pid %t/unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.pod-id
ExecStartPre=/usr/bin/podman pod create --infra-conmon-pidfile %t/unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.pid --pod-id-file %t/unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.pod-id --name=unbound --publish 127.0.0.1:1153:53/udp --publish 127.0.0.1:1153:53 --replace
ExecStart=/usr/bin/podman pod start --pod-id-file %t/unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.pod-id
ExecStop=/usr/bin/podman pod stop --ignore --pod-id-file %t/unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.pod-id -t 10
ExecStopPost=/usr/bin/podman pod rm --ignore -f --pod-id-file %t/unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.pod-id
PIDFile=%t/unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.pid
Type=forking

[Install]
WantedBy=multi-user.target default.target`

It runs fine and listens on the host's 1153/udp.  I have an nft table for dnat and masquerade of 53/1153.

But unbound, being in a pod, has no way to reach out to the internet to get the IP for unknown URLs.

I've asked politely several times in IRC, but bbaude has ordered everyone to not respond to my questions, so there is no input.  At least he didn't ban me this time like he did before, even as I was just as polite.  I've read docs for hours and found plenty of guidance on the simple things, over and over, but nothing relating to this issue. 

Sometimes a server has to reach out, rather than just listening.

**Comment by baude** [comment] 2021-03-24 21:11
I have not ordered everyone to not respond to you ... and I have never banned you.  That is a blatant lie.

Moreover, I was not on IRC today.  The fact that you didn't get answer today or any other day suggests to me that people are busy, in meetings, or don't have an answer for you.

**Comment by baude** [comment] 2021-03-24 21:13
First question I would ask you is if this pod setup works outside the confirms of systemd?

**Comment by rhatdan** [comment] 2021-03-24 21:44
@quantum77 Please rewrite this issue, without attacking any engineers.  Let's take the high road.  There is no guarantee to get any response on IRC. Engineers do this in the spear time.  If you have an issue, you should have opened an issue, if no one was able help you.

**Comment by TomSweeneyRedHat** [comment] 2021-03-25 00:28
Honestly @quantum77 @rhatdan "spear time" was a  typo for "spare time"!  :^)

Just for a bit more background, @baude has never encouraged anyone on the Red Hat team to avoid or ignore a user, including you.  I find him to be very customer-focused and concerned about their needs, I'm sorry that's not been your experience.  

As far as the IRC response goes, we do try to monitor that closely,  but mostly during Eastern time working hours (9a.m. to 5pm UTC-4).  After that, it's spare time but many of us are still there.  Also at the moment, several of the maintainers work for Red Hat.  We are currently in a real balancing act in the past several weeks as we just ran a conference for the first time, we attend to the needs of our upstream community, and have not one, not two, but three different releases of RHEL and one release of OpenShift that we are all heavily involved in with looming deadlines for all.  It's fun, but we've been scrambling as of late and not as responsive as we would like.

As far as your issue goes, I, unfortunately, don't have the underlying network knowledge necessary to help.  Hopefully, someone will be able to chime in and it looks like @baude has left a question that might lead down the trail to a solution for you.

**Comment by quantum77** [comment] 2021-03-25 15:55
bbaude, Ok, technically you didn't technically 'ban' me in the IRC sense, but you did set me to +q (quiet) so I could not post...  and added a string so I couldn't post under any alias, according to #freenode staff.  Plus you blocked my account on freenode so I could not even log in until they kindly freed it up for me.  I was not rude in the channel or in violation of rules.  I was just posting questions you didn't understand.

And Tuesday if you weren't there, somebody hacked into your account and was posting under your nick.  At 08:26:59 PDT I posted the question: 

> "I'm clear that I can set a pod to listen on a given host's port.  But I'm trying to set up an unbound server (DNS).  The unbound container in the unbound pod will need to send (forward) requests of unknown URLs to an outside authoritative server, yet it's confined to the pod.  How do I make this connexion?"

... and hours went by, with hundreds in the channel.  During this time other knowledgeable members were posting like apollo13.  At 10:11:33 I re-posted the same question and patiently waited.  At 11:01:06 you began a dialog with mheon, acui, and jhonce.  All the top ppl were there and all were active in channel, but there was zero effort to address my earnest, polite, and on-topic question.

I finally gave up at 11:27:43 deciding that either I was being shut out, or that nobody knows and this is a bug.  So I posted this bug.  Hours went by on IRC.  I realize that bugs are a nuisance, and those who post them are apparently annoying and insolent, and are to be ignored.  I also realize how important you all are and how valuable your time is, and that I am just a user and not a member of the Inner Circle.

But I do not know how I am supposed to move forward with this showstopper.  bbaude do you seriously mean to suggest that secns/unbound is defective and non-functional?  Really?

**Comment by vrothberg** [comment] 2021-03-26 08:47
@quantum77, I have empathy for your frustration, especially when being stuck and seeking help.

I cannot fulfill the expectation to reply to all questions in IRC. On some days, that would be a full-time job. Oftentimes, community members are able to answer questions that I wouldn't be able to. Opening an issue, in many cases, is a better option as it allows for asynchronous communication. Simple issues are easily answered in IRC but yours seem rather complex, especially as it may be unrelated to Podman; I have no expertise at all in nftables or networking.

Talking about your issue.  Please follow the required issue template which asks for a reproducer along with providing the environment data of `podman info`. Without that, it'll be hard to know what's going on.

**Comment by quantum77** [comment] 2021-03-26 14:17
Understand vrothberg.  I didn't take the time to use the template as the problem seems like it should be very evident to those who know a pod's networking mechanics.  Containers in the pod have access to the pod's internal lo, but nothing else unless a listening function is opened up on creation of the pod, and that is in only.  bbaude knows, but isn't speaking to me evidently.

I'm not picking on bbaude.  But these issues are in his wheelhouse.  When we are given or take on significant responsibility, we can grow into the role, if we can stifle our intimidation long enough.  You and the others have done great things with podman, things which have never been done or even thought of before, and I am grateful for that.  But I also have production to implement, and I am giving honest feedback on my experiences, from the outside.

I can take care of nft and networking functions which are available.  But the ability of a container in a pod to be able to send out packets and get responses on a given port or to/from a given IP or interface, as is needed by unbound's calls to an authoratative server... does not exist.

I want unbound in a pod rather than just a container for specific security reasons.  Surely there's some workaround because mailu/postfix has done it, but I've had to abandon that for now due to https://github.com/containers/podman/issues/9694 and I'm not smart enough to get in and analyze its structure yet.

Here's the template vrothberg:
/kind bug

**Description**
unbound, being in a pod, has no way to reach out to the internet to get the IP for unknown URLs, as when it's reaching out to an authoritative DNS server.

Sometimes a server has to reach out, rather than just listening.


**Steps to reproduce the issue:**

$ mkdir /home/bill/unbound
$ podman pull docker.io/secns/unbound
$ podman pod create --name=unbound --publish 127.0.0.1:1153:53/udp  --publish 127.0.0.1:1153:53

View the newly created pod:
$ podman pod list
	POD ID        NAME    STATUS   CREATED         INFRA ID      # OF CONTAINERS
	d0c941a570fb  unbound  Created  23 seconds ago  4636b702c8b9  1

View the individual containers within a pod:
$ podman ps -a --pod
	CONTAINER ID  IMAGE                 COMMAND  CREATED             STATUS   PORTS   NAMES               POD ID        PODNAME
	4636b702c8b9  k8s.gcr.io/pause:3.2           42 seconds ago  Created  127.0.0.1:1153->53/udp  d0c941a570fb-infra  d0c941a570fb  unbound

$ podman run -dt --pod unbound --restart=always --tz=local --label "io.containers.autoupdate=image" --env DO_IPV6="no" --env HIDE_IDENTITY="yes" --env HIDE_VERSION="yes" docker.io/secns/unbound

To use auto-updates, containers must be run with --label="io.containers.autoupdate=image"
		in a systemd unit generated by podman generate systemd --new.
		--label "io.containers.autoupdate=image"

Make systemd:
	$ mkdir -p /home/carl/.config/systemd/user/
	$ cd /home/carl/.config/systemd/user/
	$ podman generate systemd --new --pod-prefix unbound --files unbound
	$ systemctl start --user unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.service
	$ systemctl status --user unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.service
	$ systemctl enable --user unbound-1bda22c3a60cf41c20f5539828724dde0cfb21e759ec83f16a2cf4d01166873f.service
	Don't worry about the "container" container.

List port mappings:
	$ podman port -a

Wire nft to forward incoming 53 requests to port 1153.

**Describe the results you received:**

There is no pod networking interface from which I can nft wire outgoing requests from the pod's unbound container to outside random authoritative A DNS servers. 

**Describe the results you expected:**

Some means for unbound in a pod to be able to reach outside random authoritative A DNS servers, no matter the mechanism.

**Output of `podman version`:**

# podman -v
podman version 3.0.1

**Output of `podman info --debug`:**

# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-1.2.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: unknown'
  cpus: 1
  distribution:
    distribution: '"opensuse-microos"'
    version: "20210321"
  eventLogger: journald
  hostname: zeta.darkmatter.org
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.11.6-1-default
  linkmode: dynamic
  memFree: 605081600
  memTotal: 2067439616
  ociRuntime:
    name: runc
    package: runc-1.0.0~rc93-2.2.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
      spec: 1.0.2-dev
      go: go1.13.15
      libseccomp: 2.5.0
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 20h 25m 5.74s (Approximately 0.83 days)
registries:
  search:
  - registry.opensuse.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Build Version: 'Btrfs v5.9 '
    Library Version: "102"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1614124800
  BuiltTime: Tue Feb 23 16:00:00 2021
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 3.0.1


**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

# rpm -q podman
podman-3.0.1-1.2.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

MicroOS immutable OS running in a KVM VM, intended to be Wireguard server.

**Comment by quantum77** [comment] 2021-03-26 18:05
Same problem running Wireguard in a pod in client mode.  It can't get out.

**Comment by vrothberg** [comment] 2021-04-01 17:31
Closing as requested in another issue.

**Closed by vrothberg** 2021-04-01 17:31 UTC
Labels: kind/bug
