### ISSUE TITLE
podman 5.0.3 fails now with message pasta failed with exit code 1: couldn't set IPv6 route(s) in guest: no route to host

### ISSUE THREAD

**Issue by cbdejavu** [containers/podman#22824] opened 2024-05-28 03:57 UTC
### Issue Description

This seems very similar to the closed issue from a couple months ago #22192.

My configuration was bit more complex as I'm running a few containers in a pod.  The workaround from that was to use --net=pasta:-4 argument and that works for the containers that are not in the pod however, it doesn't work for the containers I try to run in a pod.

To simplify things I tried just doing the basics from that issue #22192.

So if I do
podman run --rm fedora:latest

The error is:
Error: pasta failed with exit code 1:
Couldn't set IPv6 route(s) in guest: No route to host

If I do:
podman run --net=pasta:-4 --rm fedora:latest

Then it works as expected.  I'm having issues because this workaround doesn't work for running containers inside pods apparently but as I started troubleshooting since I can't run a simple container I figured it was easiest to troubleshoot that problem and fixing that will probably fix the container inside of a pod issue.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Running up to date version of Manjaro
2. installed podman v5.0.3
3. installed passt v 2024-05-23-765eb0b-1
4. Run the following command - podman run --rm fedora:latest

### Describe the results you received

The container doesn't run and I receive the following error message:

Error: pasta failed with exit code 1:
Couldn't set IPv6 route(s) in guest: No route to host

### Describe the results you expected

The expected result is for the container to run without any errors

### podman info output

```yaml
podman info --debug

host:
  arch: amd64
  buildahVersion: 1.35.4
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.11-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: e21e7c85b7637e622f21c57675bf1154fc8b1866'
  cpuUtilization:
    idlePercent: 94.88
    systemPercent: 0.61
    userPercent: 4.5
  cpus: 20
  databaseBackend: boltdb
  distribution:
    distribution: manjaro
    version: unknown
  eventLogger: journald
  freeLocks: 2045
  hostname: DejaRaptor
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.8.9-3-MANJARO
  linkmode: dynamic
  logDriver: journald
  memFree: 2297589760
  memTotal: 67126120448
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
    package: /usr/lib/podman/netavark is owned by netavark 1.10.3-1
    path: /usr/lib/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.15-1
    path: /usr/bin/crun
    version: |-
      crun version 1.15
      commit: e6eacaf4034e84185fd8780ac9262bbf57082278
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: /usr/bin/pasta is owned by passt 2024_05_23.765eb0b-1
    version: |
      pasta 2024_05_23.765eb0b
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.3.0-1
    version: |-
      slirp4netns version 1.3.0
      commit: 8a4d4391842f00b9c940bb8f067964427eb0c964
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 0
  swapTotal: 0
  uptime: 46h 23m 59.00s (Approximately 1.92 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/craig/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/craig/.local/share/containers/storage
  graphRootAllocated: 2014790946816
  graphRootUsed: 722278821888
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 66
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/craig/.local/share/containers/storage/volumes
version:
  APIVersion: 5.0.3
  Built: 1715595915
  BuiltTime: Mon May 13 03:25:15 2024
  GitCommit: d08315df35cb6e95f65bf3935f529295c6e54742-dirty
  GoVersion: go1.22.3
  Os: linux
  OsArch: linux/amd64
  Version: 5.0.3
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Manjaro 24.0.0 with all updates up to 2024-5-18 update installed

Everything was working prior to this update using podman v5.0.2 and passt v2024-04-26 along with various older versions (I've been running this particular set of containers and pods for almost 2 years now).

pacman -Qii podman

Name            : podman
Version         : 5.0.3-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/podman
Licenses        : Apache-2.0
Groups          : None
Provides        : None
Depends On      : catatonit  conmon  containers-common  crun  gcc-libs  glibc  iptables  device-mapper  libdevmapper.so=1.02-64  gpgme  libgpgme.so=11-64
                  libseccomp  libseccomp.so=2-64  passt
Optional Deps   : apparmor: for AppArmor support [installed]
                  btrfs-progs: support btrfs backend devices [installed]
                  cni-plugins: for an alternative container-network-stack implementation
                  fuse-overlayfs: for storage driver in rootless environment
                  slirp4netns: for alternative rootless network support [installed]
                  podman-compose: for docker-compose compatibility
                  podman-docker: for Docker-compatible CLI
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 76.95 MiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Mon 13 May 2024 03:25:15 AM PDT
Install Date    : Sat 25 May 2024 09:18:35 PM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
Backup Files    : None
Extended Data   : pkgtype=split

pacman -Qii passt

Name            : passt
Version         : 2024_05_23.765eb0b-1
Description     : Plug A Simple Socket Transport
Architecture    : x86_64
URL             : https://passt.top/passt/about/
Licenses        : BSD-3-Clause  GPL-2.0-or-later
Groups          : None
Provides        : None
Depends On      : glibc
Optional Deps   : sh: for demo script [installed]
Required By     : podman
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 425.72 KiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Thu 23 May 2024 02:32:01 PM PDT
Install Date    : Sat 25 May 2024 09:18:16 PM PDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
Backup Files    : None
Extended Data   : pkgtype=pkg

### Additional information

Just let me know if I can provide any other details.  I don't really work with containers daily and I set all of this up almost 2 years ago and it has worked flawlessly until now.  So I'm having to refresh myself on things but I do have the original commands I used to create the pods, containers and then the systemd .service files I use to currently launch everything.  For right now I can only run the containers that are no inside of a pod by adding the --net=pasta:-4 argument to them.  Adding that argument to containers that are trying to start inside a pod just fails with 

ERRO[0000] Starting some container dependencies         
ERRO[0000] "pasta failed with exit code 1:\nCouldn't set IPv6 route(s) in guest: No route to host\n" 

That is the same error message with or without the --net=pasta:-4 argument

**Comment by Luap99** [comment] 2024-05-28 08:01
> I'm having issues because this workaround doesn't work for running containers inside pods apparently but as I started troubleshooting since I can't run a simple container I figured it was easiest to troubleshoot that problem and fixing that will probably fix the container inside of a pod issue.

You have to set the network option on the pod not the container when using pods in general unless you explicitly do not want to share the network namespace.

**Comment by Luap99** [comment] 2024-05-28 08:03
Can you share your ipv6 routes? You can hide the real addresses but subnet and interface information is likely needed to reproduce.

cc @sbrivio-rh @dgibson

**Comment by cbdejavu** [comment] 2024-05-28 19:26
Thank you for the super fast response @Luap99 .  First off while I thought I had properly passed the --net=pasta:-4 argument to my pod I clearly didn't (or typo'd it when I had tried because I just tested it again and that "fixed my pod" so my containers are working again.  Since they don't need ipv6 to function it is a perfectly fine workaround however, to further assist troubleshooting the cause of this because I can no longer run containers on my system without forcing ipv4 only.

I did a bit more digging and I'm thinking this issue is related to #22320 as I'm connected to a VPN.

My physical network configuration is a wireless connection to my router, and I'm also running a VPN  (ProtonVPN)

Here are my ipv6 routes

::/3 via fd54:20a4:d33b:b10c:e07:0:60:1 dev proton0 proto static metric 50 pref medium
2604:xxxx:31fe:xxxx::8c7 dev wlo1 proto kernel metric 600 pref medium
2604:xxxx:31fe:xxxx::/64 dev wlo1 proto ra metric 600 pref medium
2604:xxxx:31fe:xxxx::/56 via fe80::d276:8fff:fe4a:d995 dev wlo1 proto ra metric 600 pref medium
2000::/4 via fd54:20a4:d33b:b10c:e07:0:60:1 dev proton0 proto static metric 50 pref medium
3000::/4 via fd54:20a4:d33b:b10c:e07:0:60:1 dev proton0 proto static metric 50 pref medium
fd54:20a4:d33b:b10c:e07:0:60:0/112 dev proton0 proto kernel metric 50 pref medium
fd61:8b53:3f61::/64 via fe80::1c58:adc:4cb4:f788 dev wlo1 proto ra metric 600 pref medium
fdeb:446c:912d:8da::/64 dev ipv6leakintrf0 proto kernel metric 95 pref medium
fdeb:446c:912d:8da::/64 dev pvpnksintrf0 proto kernel metric 98 pref medium
fc00::/7 via fd54:20a4:d33b:b10c:e07:0:60:1 dev proton0 proto static metric 50 pref medium
fe80::/64 dev proton0 proto kernel metric 256 pref medium
fe80::/64 dev wlo1 proto kernel metric 1024 pref medium
fe80::/64 dev ipv6leakintrf0 proto kernel metric 1024 pref medium
fe80::/64 dev pvpnksintrf0 proto kernel metric 1024 pref medium
default dev proton0 proto static metric 50 pref medium
default via fdeb:446c:912d:8da::1 dev ipv6leakintrf0 proto static metric 95 pref medium
default via fdeb:446c:912d:8da::1 dev pvpnksintrf0 proto static metric 98 pref medium
default via fe80::d276:8fff:fe4a:d995 dev wlo1 proto ra metric 600 pref medium

I'll tag the people you cc'd above.
cc @sbrivio-rh @dgibson

**Comment by sbrivio-rh** [comment] 2024-06-04 21:08
The issue here is rather clear. While we copy routes from host upstream interface to the container, there might be dependencies between routes, so, to keep things simple, we just retry to copy routes n times, with n number of routes. While doing this, we [don't consider `ENETUNREACH` and `EEXIST` as errors](https://passt.top/passt/tree/netlink.c?id=765eb0bf1651d20ca319eeb8b41ff35f52f2a29c#n658), because we might be trying inserting a route that we already added successfully, or one that doesn't have its route dependency satisfied yet. `ENETUNREACH` isn't enough, though: we also need to ignore `EHOSTUNREACH` ("no route to host"), because we might not have, at some point, a route to reach a given gateway.

However, just to be sure that's your case: could you please try to build passt (it's simple: `git clone git://passt.top; make -C passt`) with the patch below (hacky and very lightly tested):

```
diff --git a/netlink.c b/netlink.c
index d3bea68..0465f1a 100644
--- a/netlink.c
+++ b/netlink.c
@@ -344,6 +344,27 @@ unsigned int nl_get_ext_if(int s, sa_family_t af)
 	return 0;
 }
 
+static void nl_route_print(struct nlmsghdr *nh, char *buf, size_t len)
+{
+	struct rtmsg *rtm = (struct rtmsg *)NLMSG_DATA(nh);
+	struct rtattr *rta;
+	size_t na, n;
+
+	for (rta = RTM_RTA(rtm), na = RTM_PAYLOAD(nh); RTA_OK(rta, na);
+	     rta = RTA_NEXT(rta, na)) {
+		char addrbuf[INET6_ADDRSTRLEN];
+
+		if (rta->rta_type == RTA_DST || rta->rta_type == RTA_GATEWAY) {
+			n = snprintf(buf, len, "%s: %s ",
+				     rta->rta_type == RTA_DST ? "dst" : "gw",
+				     inet_ntop(rtm->rtm_family, RTA_DATA(rta),
+					       addrbuf, sizeof(addrbuf)));
+			buf += n;
+			len -= n;
+		}
+	}
+}
+
 /**
  * nl_route_get_def_multipath() - Get lowest-weight route from nexthop list
  * @rta:	Routing netlink attribute with type RTA_MULTIPATH
@@ -655,8 +676,13 @@ int nl_route_dup(int s_src, unsigned int ifi_src,
 			rc = nl_do(s_dst, nh, RTM_NEWROUTE,
 				   (flags & ~NLM_F_DUMP_FILTERED) | NLM_F_CREATE,
 				   nh->nlmsg_len);
-			if (rc < 0 && rc != -ENETUNREACH && rc != -EEXIST)
+			if (rc < 0 && rc != -ENETUNREACH && rc != -EEXIST) {
+				char buf[BUFSIZ];
+
+				nl_route_print(nh, buf, BUFSIZ);
+				err("Failed to copy route, %s", buf);
 				return rc;
+			}
 		}
 	}

```

then start pasta stand-alone on your system (`./pasta --config-net`) and see what route it actually fails to copy to the container? Thanks.

**Comment by luckylinux** [comment] 2024-06-13 16:30
I had a bit of a rought Ride as well with Podman 5.1.0 on Fedora AMD64.

```
host:
  arch: amd64
  buildahVersion: 1.36.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 99.11
    systemPercent: 0.49
    userPercent: 0.4
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: server
    version: "40"
  eventLogger: journald
  freeLocks: 2032
  hostname: MYHOST.MYDOMAIN.TLD
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 655360
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 655360
      size: 65536
  kernel: 6.8.11-300.fc40.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1083744256
  memTotal: 8171499520
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-1.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark-1.10.3-3.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun-1.15-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.15
      commit: e6eacaf4034e84185fd8780ac9262bbf57082278
      rundir: /run/user/1002/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240510.g7288448-1.fc40.x86_64
    version: |
      pasta 0^20240510.g7288448-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1002/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-2.fc40.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 10733215744
  swapTotal: 10733215744
  uptime: 2h 57m 5.00s (Approximately 0.08 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: localhost:5000
    PullFromMirror: ""
  search:
  - docker.MYDOMAIN.TLD
  - docker.io
  - ghcr.io
store:
  configFile: /home/podman/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 5
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.13-1.fc40.x86_64
      Version: |-
        fusermount3 version: 3.16.2
        fuse-overlayfs: version 1.13-dev
        FUSE library version 3.16.2
        using FUSE kernel interface version 7.38
    overlay.mountopt: nodev
  graphRoot: /zdata/PODMAN/STORAGE
  graphRootAllocated: 298635362304
  graphRootUsed: 3273916416
  graphStatus:
    Backing Filesystem: zfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /home/podman/containers/tmp
  imageStore:
    number: 207
  runRoot: /run/user/1002
  transientStore: false
  volumePath: /zdata/PODMAN/VOLUMES
version:
  APIVersion: 5.1.0
  Built: 1716940800
  BuiltTime: Wed May 29 02:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.3
  Os: linux
  OsArch: linux/amd64
  Version: 5.1.0
```

The Proposed Fix by @sbrivio-rh **almost** works.

Procedure:
```
# Change to Sources Folder
root@MYHOST# cd /usr/src

# Clone Repository
root@MYHOST# git clone https://passt.top/passt

# Change Folder
root@MYHOST# cd passt/

# Copy the Patch outlined by @sbrivio-rh into netlink.patch
root@MYHOST# nano netlink.patch
(paste the contents here)

# Apply Patch
# In my case I need to install patch first
root@MYHOST# dnf install patch
root@MYHOST# patch -p1 < netlink.patch

# Build - First Attempt
root@MYHOST# make

# Test (as USER)
podman@MYHOST$ /usr/src/passt/pasta --config-net --debug

# It will fail, in my case on the nat46 route for snid
# Failed to copy route, dst: 64:ff9b:1::1:0:0 gw: 2XXX:XXXX:XXXX:0001::1:66

# Mark patch as already applied
root@MYHOST# mv netlink.patch netlink.patch.already_applied

# Replace this line: if (rc < 0 && rc != -ENETUNREACH && rc != -EEXIST) {
# With this line: if (rc < 0 && rc != -ENETUNREACH && rc != -EHOSTUNREACH && rc != -EEXIST) {

# Build - Second Attempt
root@MYHOST# make

# Test as USER
# Now no Errors (without --debug NOTHING is displayed)
podman@MYHOST$ /usr/src/passt/pasta --config-net --debug
```

Main IPv6 Interface address is: `2XXX:XXXX:XXXX:0001::8:15`
User-Configurable Local IPv6 Addresses are: `2XXX:XXXX:XXXX:0001::ff15:0/112` (`2XXX:XXXX:XXXX:0001::ff15:0000` ... `2XXX:XXXX:XXXX:0001::ff15:ffff`)

WITHOUT PATCHING + ONE-LINER:
```
# Run pasta debug
podman@MYHOST$ pasta --config-net --debug

# Host LOCAL Routes (IPv6)
podman@MYHOST$ ip -6 route show table local
local ::1 dev lo proto kernel metric 0 pref medium
local 64:ff9b:1::9999:0:0/96 dev lo metric 1024 pref medium
local 2XXX:XXXX:XXXX:0001::8:15 dev ens18 proto kernel metric 0 pref medium
local 2XXX:XXXX:XXXX:0001::ff15:0/112 dev lo metric 1024 pref medium
local 2XXX:XXXX:XXXX:0001:1234:1234:1234:1234 dev ens18 proto kernel metric 0 pref medium
local fe80::XXXX:XXXX:XXXX:XXXX dev ens18 proto kernel metric 0 pref medium
multicast ff00::/8 dev ens18 proto kernel metric 256 pref medium

# Host REMOTE Routes (IPv6)
podman@MYHOST$ ip -6 route show
64:ff9b:1::1:0:0/96 via 2XXX:XXXX:XXXX:0001::1:66 dev ens18 metric 1024 pref medium
64:ff9b:1::2:0:0/96 via 2XXX:XXXX:XXXX:0001::1:67 dev ens18 metric 1024 pref medium
2XXX:XXXX:XXXX:0001::/64 dev ens18 proto ra metric 1002 mtu 1500 pref medium
fe80::/64 dev ens18 proto kernel metric 256 pref medium
default via fe80::192:168:1:1 dev ens18 proto ra metric 1002 mtu 1500 pref medium

podman@MYHOST$ podman-compose down
podman@MYHOST$ podman-compose up
[whoami-application] | time="2024-06-13T18:16:30+02:00" level=error msg="Starting some container dependencies"
[whoami-application] | time="2024-06-13T18:16:30+02:00" level=error msg="\"pasta failed with exit code 1:\\nCouldn't get any nameserver address\\nCouldn't set IPv6 route(s) in guest: No route to host\\n\""
[whoami-application] | Error: unable to start container 4c28b8281f329e8e9e078727c36e5253fe4e5c259bfde0f22c95df6fbc518f61: starting some containers: internal libpod error
[whoami-caddy]       | Error: unable to start container 870e45e905be8db65525fa040744784930533322add0e07812254be64858a036: pasta failed with exit code 1:
[whoami-caddy]       | Couldn't get any nameserver address
[whoami-caddy]       | Couldn't set IPv6 route(s) in guest: No route to host
[whoami-caddy]       | 

```

WITH PATCHING + ONE-LINER:
```
# Host LOCAL Routes (IPv6)
podman@MYHOST$ ip -6 route show table local
local ::1 dev lo proto kernel metric 0 pref medium
local 64:ff9b:1::9999:0:0/96 dev lo metric 1024 pref medium
local 2XXX:XXXX:XXXX:0001::8:15 dev ens18 proto kernel metric 0 pref medium
local 2XXX:XXXX:XXXX:0001::ff15:0/112 dev lo metric 1024 pref medium
local 2XXX:XXXX:XXXX:0001:1234:1234:1234:1234 dev ens18 proto kernel metric 0 pref medium
local fe80::XXXX:XXXX:XXXX:XXXX dev ens18 proto kernel metric 0 pref medium
multicast ff00::/8 dev ens18 proto kernel metric 256 pref medium

podman@MYHOST$ podman-compose down
podman@MYHOST$ CONTAINERS_HELPER_BINARY_DIR="/usr/src/passt" podman-compose up
(working Caddy Proxy Logs)

# Host REMOTE Routes (IPv6)
podman@MYHOST$ ip -6 route show
64:ff9b:1::1:0:0/96 via 2XXX:XXXX:XXXX:0001::1:66 dev ens18 metric 1024 pref medium
64:ff9b:1::2:0:0/96 via 2XXX:XXXX:XXXX:0001::1:67 dev ens18 metric 1024 pref medium
2XXX:XXXX:XXXX:0001::/64 dev ens18 proto ra metric 1002 mtu 1500 pref medium
fe80::/64 dev ens18 proto kernel metric 256 pref medium
default via fe80::192:168:1:1 dev ens18 proto ra metric 1002 mtu 1500 pref medium
```

From INSIDE the Container when running with the Patcheed + one-liner `passt` Version:
```
# Container LOCAL Routes (IPv6)
/srv # ip -6 route show table local
local ::1 dev lo  metric 0 
local 2XXX:XXXX:XXXX:0001::8:15 dev ens18  metric 0 
local 2XXX:XXXX:XXXX:0001:1234:1234:1234:1234 dev ens18  metric 0 
local fe80::XXXX:XXXX:XXXX:XXXX dev ens18  metric 0 


# Container REMOTE Routes (IPv6)
/srv # ip -6 route show
64:ff9b:1::1:0:0/96 via 2XXX:XXXX:XXXX:0001::1:66 dev ens18  metric 1024 
64:ff9b:1::2:0:0/96 via 2XXX:XXXX:XXXX:0001::1:67 dev ens18  metric 1024 
2XXX:XXXX:XXXX:0001::/64 dev ens18  metric 1002 
fe80::/64 dev ens18  metric 256 
default via fe80::192:168:1:1 dev ens18  metric 1002 
multicast ff00::/8 dev ens18  metric 256 
```

**Comment by sbrivio-rh** [comment] 2024-06-24 19:19
Fixed in [2024_06_24.1ee2eca](https://archives.passt.top/passt-user/20240624210651.61ce77af@elisabeth/), and matching Fedora 40 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2024-4632bfa865). Updated Arch Linux package should follow soon.

**Closed** 2024-06-25 15:28 UTC
Labels: kind/bug, network, pasta
