### ISSUE TITLE
virtiofsd not in path breaks podman start

### ISSUE THREAD

**Issue by baude** [containers/podman#23127] opened 2024-06-27 19:20 UTC
### Issue Description

It seems like the recent addition of virtiofsd broke podman start on fedora.  The virtiofsd executable sits in /usr/libexec and is not present in path.

```
[baude@baudework ~]$ podman machine start
Starting machine "podman-machine-default"
ERRO[0000] process 6160 has not ended                   
Error: failed to find virtiofsd: exec: "virtiofsd": executable file not found in $PATH

```

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment] 2024-06-28 08:33
https://github.com/containers/podman/pull/22920#discussion_r1630919819

In general if you want to hard code paths you can add this back but this is horrible as it doesn't scale across distros.

One thing that we should change though is not to lookup in $PATH. This doesn't make sense and the returned error to users is confusing.

**Comment by afbjorklund** [comment] 2024-06-29 16:39
Seems to be missing from the build-from-source documentation, but then again so is gvproxy etc.

* https://github.com/containers/podman.io/issues/285

**Comment by afbjorklund** [comment] 2024-08-04 16:12
Still happens with 5.2.0, workaround is to install `virtiofsd` in `/usr/local/bin`.

https://gitlab.com/virtio-fs/virtiofsd#ci-built-binaries

**Comment by afbjorklund** [comment] 2024-08-04 16:22
With v5.2.0, it will now find `/usr/local/libexec/podman/virtiofsd`

**Comment by rhatdan** [comment] 2024-08-05 10:41
Should this issue be closed?

**Comment by afbjorklund** [comment] 2024-08-05 10:47
The current hack will work for latest Fedora (40) and latest Ubuntu (24.04). Others will have to work around the issue with symlinks from the helper dir...

**Comment by afbjorklund** [comment] 2024-08-05 11:18
Upstream has a JSON file, where the path is defined.

**Comment by afbjorklund** [comment] 2024-08-05 12:09
> They are not needed when running podman locally, only podman machine.
> 
> But it could be a point to build them with podman anyway, "just in case".

If I understand packaging rules, it's supposed to go in a subpackage since fc40:

* https://github.com/containers/podman/pull/23095

https://packages.fedoraproject.org/pkgs/podman/podman-machine/

So "podman-machine" is where gvproxy/virtiofsd and even the new qemu lives.

**Comment by mryo0826** [comment] 2024-08-14 05:51
The version of podman managed by Fedora 40's dnf has been updated to v5.2.0. It probably happened today (2024/08/12).
This version causes the bug in this issue.
The problem did not occur with v5.1.2 until yesterday.
It seems to be happening because qume installed with dnf dependencies is 8.2.2.
I specified podman v5.0.0 in dnf and installed it, but since qume is still 8.2.2, this problem occurs.

**Comment by afbjorklund** [comment] 2024-08-14 06:00
You need to install the "podman-machine" package, once it is available in Fedora.

https://packages.fedoraproject.org/pkgs/podman/podman-machine/

**Comment by mryo0826** [comment] 2024-08-14 07:21
> You need to install the "podman-machine" package, once it is available in Fedora:

Sorry I don't understand what you posted before.
I installed the  "podman-machine" package.

But now I'm getting another error.

```
$ podman machine start
Starting machine "podman-machine-default"
Error: qemu exited unexpectedly with exit code 1, stderr: Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: -accel kvm: failed to initialize kvm: No such file or directory
```

I have confirmed that "qemu-kvm" is installed in my environment.

Are there still other required modules that have different paths that are causing the error?

**Comment by afbjorklund** [comment] 2024-08-14 08:31
There might be other steps needed too, to set up KVM

Ubuntu has a script called `kvm-ok`, to check setup

**Comment by cgwalters** [comment] 2024-08-20 23:57
I think we need a public service announcement of the form:

"Are you using podman-machine on Linux (e.g. Fedora?); then `dnf -y install podman-machine` or equivalent"

Hmm...you know while I tend to agree with Paul about not hardcoding file paths, on the flip side it would be *very* practical to add a downstream patch (or maybe an upstream variant) that basically checks on `podman machine start` if `/usr/libexec/podman/virtiofsd` exists, and if it doesn't tells you to install that package.

@baude I am going to go ahead and proactively close this issue as "fixed" with the resolution "please install podman-machine", but of course feel free to reopen if you disagree!

**Closed by cgwalters** 2024-08-20 23:57 UTC
Labels: kind/bug, machine

**Comment by afbjorklund** [comment] 2024-08-21 05:23
The same issue already existed for gvproxy, but better documentation or error messages could help...

**Comment by cgwalters** [comment] 2024-08-21 12:39
(OK I know this is a closed issue, but we can gather some quick consensus here before making a new one (or straight to a PR))

How about this: podman-machine on Linux *requires* `/usr/libexec/podman/machine` to exist (as a symlink to `../../bin/podman`) - and the presence of that file signals that all dependencies of podman-machine are installed. If not, podman has a generic message that tells you to go install it using your OS/distro tooling. We could add a build tag that allows customizing the error message.

**Comment by cgwalters** [comment] 2024-08-21 17:56
cc @baude for opinions on :arrow_up

**Comment by Luap99** [comment] 2024-08-22 09:22
>  podman-machine on Linux requires /usr/libexec/podman/machine 

That sounds like extra work for no benefit. And AFAIK other distros do not use a libexec dir at all so hard coding this does not work for them. Neither will it work for users installing binaries in their home dir.  IMO if we do not find qemu/gvproxy/virtiofsd,etc.. we should just throw better errors in general and simply document what packages are required on what distros.

**Comment by germag** [comment] 2024-08-22 11:43
Sorry, I'm late to this

Since `/usr/libexec` is not in the `PATH` it will fail even if `virtiofsd` is installed, adding `HELPER_BINARIES_DIR="/usr/libexec"` in the build step of the rpm spec (it will be added to `additionalHelperBinariesDir` at link time) will fix the issue, without interfering with other distributions

**Comment by Luap99** [comment] 2024-08-22 12:05
> Since /usr/libexec is not in the PATH it will fail even if virtiofsd is installed, adding HELPER_BINARIES_DIR="/usr/libexec" in the build step of the rpm spec (it will be added to additionalHelperBinariesDir at link time) will fix the issue, without interfering with other distributions

You should install `podman-machine` which adds a symlink from the podman default helper dir to virtiofsd.

**Comment by germag** [comment] 2024-08-22 12:45
> > Since /usr/libexec is not in the PATH it will fail even if virtiofsd is installed, adding HELPER_BINARIES_DIR="/usr/libexec" in the build step of the rpm spec (it will be added to additionalHelperBinariesDir at link time) will fix the issue, without interfering with other distributions
> 
> You should install `podman-machine` which adds a symlink from the podman default helper dir to virtiofsd.

then I'll add `podman-machine` as dependency in the podman-bootc rpm spec, thanks!
