### ISSUE TITLE
Unattended Image signing

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [containers/podman#7705] opened 2020-09-21 11:23 UTC
/kind feature

**Description**

I would like to be able to do unattended image signing with podman - getting the signature passphrase from file/fd.

With gpg I can do something like this:

```console
$ gpg --pinentry-mode loopback --passphrase-file /secrets/SIGNATURE_ID_PASSWORD -s -u SIGNATURE_ID ...
```

to sign something (unattended) using secrets from the filesystem.

It would be nice with something similar for podman (or buildah/skopeo).

**Comment by jskovjyskebankdk** [comment] 2020-09-21 11:45
Maybe people just make signatures without password?

That seems to allow unattended signing.

**Comment by rhatdan** [comment] 2020-09-21 19:11
@QiWang19 @mtrmac PTAL

**Comment by mtrmac** [comment] 2020-10-02 17:47
Thanks for your report. This was historically not easily possible because RHEL 7’s GPGme does not expose the loopback option (and IIRC neither does the underlying GPG); and the Go build system makes it rather difficult for libraries to opt in/out of features based on the build environment — essentially the top-level software has to deal with all the complexity.

If we can drop drop support for RHEL 7, adding the loopback option + a way to supply a passphrase seems reasonable, based on reading the documentation (not having a prototype).

---

One way that would work right now is to use a GPG agent, and to unlock the private key by using `gpg --sign` to sign something inconsequential. That’s horribly ugly, of course, and having those “inconsequential” signatures around introduces extra risk.

**Comment by rhatdan** [comment] 2020-10-05 18:39
I have no problem ignoring RHEL7 going forward. We should pay attention to RHEL8 and above at this point.  If someone backports this functionality to RHEL7 and it blows up we can just close it as not supported.

**Comment by mtrmac** [comment] 2020-10-06 12:50
It’s not so much a backport concern, or a feature blowing up if used — just _building_ any version of Podman / … that adds the loopback option will be simply impossible on RHEL 7 and earlier; anyone trying would have to actively patch out the loopback uses.

(I’m fine with that consequence, I just want to make it very explicit.)

**Comment by rhatdan** [comment] 2020-10-10 10:55
Sure, we are already beginning to do this.  With certain features (cgroupsV2).  But I don't want a 8 year old OS holding us back,especially when we have no intention os shipping a new supported version of a container engine on it. podman 1.6 was the end of the line for supported RHEL 7.

**Comment by SirNiggo** [comment] 2020-10-27 13:52
I do also have a need for such a feature for unattended CI Pipelines. Helm (which is probably often used together with Podman in such pipelines) has recently (re)introduced arguments for passphrases with PR https://github.com/helm/helm/pull/8394.
Having the additional layer of security by using a passphrase on a GPG key is necessary for me.

**Comment by rhatdan** [comment] 2020-12-04 22:32
@mtrmac WDYT with us dumping RHEL7, should we pursue this?

**Comment by mtrmac** [comment] 2020-12-07 15:04
It does make sense to do. I don’t have a strong opinion on priority/timing.

**Comment by rhatdan** [comment] 2020-12-23 20:30
@QiWang19 PTAL

**Comment by QiWang19** [comment] 2020-12-23 21:02
duplicate of BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1892722,  @umohnani8 are you working on this?

**Comment by umohnani8** [comment] 2021-01-11 18:09
Yup, will work on this.

**Comment by rhatdan** [comment] 2021-01-11 19:43
Awesome.

**Comment by rheinzma** [comment] 2021-02-19 21:03
Will this fix only address podman or also skopeo / podman ?

**Comment by rhatdan** [comment] 2021-12-26 11:55
@umohnani8 did you ever make any progress on this?

**Comment by mtrmac** [comment] 2022-01-26 12:14
After https://github.com/containers/image/pull/1446, this is now possible. Probably needs to be exposed in c/common/libimage first.

**Comment by vrothberg** [comment] 2022-01-26 12:19
> After [containers/image#1446](https://github.com/containers/image/pull/1446), this is now possible. Probably needs to be exposed in c/common/libimage first.

Good call!  Yes, we need to add a Passphrase field to `libimage.CopyOptions` and do the plumbing in Podman's CLI as we did in https://github.com/containers/skopeo/pull/1540 for Skopeo.

**Comment by rhatdan** [comment] 2022-01-26 14:12
Awesome.

**Comment by rhatdan** [comment] 2022-05-06 14:22
@umohnani8 Do you have time to work on this?

**Comment by vrothberg** [comment] 2022-07-13 09:29
Probably a nice work item for interns.

https://github.com/containers/skopeo/pull/1540 should serve as a good example of how to use the c/image API.  `podman image sign` should be able to use it directly. `podman push` needs to do some wiring in [libimage's](https://github.com/containers/common/tree/main/libimage) CopyOptions.

**Comment by mtrmac** [comment] 2022-08-23 16:55
As of https://github.com/containers/podman/pull/15108 included in Podman 4.2, `podman push` and `podman manifest push` have a `--sign-passphrase-file` option.

Note that `podman image sign` (which is not the recommended workflow) does not have that option yet.

**Comment by jskov-jyskebank-dk** [comment] 2022-08-24 05:22
Very nice. Thanks @mtrmac !

**Comment by enyineer** [comment] 2022-08-24 06:20
Also a big thanks from me! Very appreciated.

**Comment by rhatdan** [comment] 2022-08-25 20:06
Looks like this issue is fixed.  Closing.

**Closed by rhatdan** 2022-08-25 20:06 UTC
Labels: kind/feature
