### ISSUE TITLE
[Bug]: Cache miss on `ARG`

### ISSUE THREAD

**Issue by SohumB** [containers/podman#17039] opened 2023-01-09 14:03 UTC
### Issue Description

I have gitlab CI traces here of a cache miss on an `ARG` line that hasn't changed. You can see in the logs that all lines before the `ARG` are considered cached, but that is the one that busts it. These runs happened less than ten minutes apart.

[0.log](https://github.com/containers/podman/files/10373684/0.log)
[1.log](https://github.com/containers/podman/files/10373686/1.log)

### Steps to reproduce the issue

I've attached the Dockerfile in question. 
[Dockerfile.txt](https://github.com/containers/podman/files/10373711/Dockerfile.txt)

As you can see in the traces, the build command is:
```
podman build --build-arg RUST_TOOLCHAIN -t $TEST_IMAGE -f Dockerfile.test --cache-from $CI_REGISTRY_IMAGE/cache --cache-to $CI_REGISTRY_IMAGE/cache .
```

under the environment variable `RUST_TOOLCHAIN=nightly-bullseye-slim-2023-01-01`.

### Describe the results you received

Busted cache.

### Describe the results you expected

Unbusted cache.

### podman info output

```shell
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.5-1.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 5.16
    systemPercent: 28.2
    userPercent: 66.64
  cpus: 1
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: file
  hostname: runner-xxurkrix-project-42417448-concurrent-0
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.109+
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 2520944640
  memTotal: 3864317952
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-3.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 0h 1m 51.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.9-6.fc37.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.9
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 21969563648
  graphRootUsed: 5314850816
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178887
  BuiltTime: Fri Nov 11 15:01:27 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```
```


### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Gitlab CI shared runners running `quay.io/podman/stable`

### Additional information

_No response_

**Comment by mheon** [comment] 2023-01-09 14:22
@flouthoc PTAL

**Comment by flouthoc** [comment] 2023-01-09 15:20
Hi @SohumB , I think this must be fixed here https://github.com/containers/buildah/pull/4326 but looks like its not released here.

**Comment by SohumB** [comment] 2023-01-10 09:19
I see. I tried using `quay.io/buildah/stable` i.e. buildah v1.28, which was released after the PR linked on that issue was closed, but it still seemed to have the same issue:
```
[1/2] STEP 5/18: ENV SCCACHE_DIR=/usr/local/sccache
--> Cache pulled from remote registry.gitlab.com/climaterisk/facades/cache:988897c367dee93e6f33125237fe48feb3a901b66defadd12681c6caf3c6394a
--> Using cache 32499281d287675be0b33a3d36d5c891ecf58fdcb94ea87a72d63d56e668c6b5
--> 32499281d28
[1/2] STEP 6/18: ARG TARGET=x86_64-unknown-linux-gnu
--> Pushing cache registry.gitlab.com/climaterisk/facades/cache:e9ad1722253f17e3d346a4990a2e67c90964533d1fea7a8ae915a2b4d0621e41
--> ab0839d26b4
```

(the differences in steps are because my Dockerfile has also changed some since, but this is the second run with the same file.)

**Comment by rhatdan** [comment] 2023-02-19 18:14
@flouthoc PTAL

**Comment by Sankluj** [comment] 2023-03-01 10:15
Hi!

I started using podman (thanks for the hard work 🙇 ) recently and just stumbled upon this issue. 
I can't find any related issue/PR on the buildah repo besides https://github.com/containers/buildah/pull/4326 which has been merged end of October 2022.

Is it tracked somewhere else?

**Comment by flouthoc** [comment] 2023-03-01 11:27
Hi @Sankluj and @SohumB , Could you please share a small reproducer for this issue, is it different from the test added in https://github.com/containers/buildah/pull/4326 ?

**Comment by SohumB** [comment] 2023-03-03 10:17
I don't _imagine_ the linked reproducer would be a different issue from this one, but unfortunately I can't say for sure — I don't know if there are more complicated conditions under which `ARG` would bust the cache. That said, I've now noticed that that commit wasn't actually in v1.28 — it's in v1.29.1 — so I'll test that, and if I still get a busted cache, I'll try to find a smaller repro.

**Comment by SohumB** [comment] 2023-03-05 13:41
I can confirm that my case is solved on 1.29.1!

**Comment by flouthoc** [comment] 2023-03-07 05:27
@Sankluj Could you also please try the latest version as @SohumB, if it works for you I'll close this issue.

**Comment by flouthoc** [comment] 2023-03-09 08:10
I think similar issue was reported was reported here https://github.com/containers/buildah/issues/4621 and its fixed on`main` https://github.com/containers/buildah/issues/4621. I am closing this issue but please feel free to re-open if it this is not resolved.

**Closed by flouthoc** 2023-03-09 08:10 UTC
Labels: kind/bug
