### ISSUE TITLE
CI flake: Panic in Spec Teardown: send on closed channel

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#6518] opened 2020-06-08 16:56 UTC
cirrus-flake-xref is reporting three instances of this since May 26:
```
Panic in Spec Teardown (AfterEach) [2.677 seconds]
         Podman containers 
         /var/tmp/go/src/github.com/containers/libpod/pkg/bindings/test/containers_test.go:19
           podman wait to pause|unpause condition [AfterEach]
           /var/tmp/go/src/github.com/containers/libpod/pkg/bindings/test/containers_test.go:282
         
           Test Panicked
           send on closed channel
           /usr/lib/golang/src/runtime/panic.go:969
         
           Full Stack Trace
           panic(0x10397a0, 0x134e430)
           	/usr/lib/golang/src/runtime/panic.go:969 +0x166
           github.com/containers/libpod/pkg/bindings/test.glob..func5.20.2(0xc0000b2a38, 0xc00004dc90, 0xc000319ae8, 0xc000011180)
           	/var/tmp/go/src/github.com/containers/libpod/pkg/bindings/test/containers_test.go:308 +0xc8
           created by github.com/containers/libpod/pkg/bindings/test.glob..func5.20
           	/var/tmp/go/src/github.com/containers/libpod/pkg/bindings/test/containers_test.go:304 +0x6cc
```
Log links:
* [PR 6356](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4615038243700736/html/integration_test.log.html)
* [PR 6453](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5392977415634944/html/integration_test.log.html)
* [PR 6515](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4547364012687360/html/integration_test.log.html)

Link to [containers_test.go:308](https://github.com/containers/libpod/blob/a5facca78fed010552339a6644dd8ef1bb0fa229/pkg/bindings/test/containers_test.go#L308).

All failures have been in `fedora-32 special_testing_bindings`.

**Comment by edsantiago** [comment] 2020-06-24 22:00
Still happening, and (as far as my logs can tell) still only on f32:

Podman containers  [AfterEach] podman wait to pause|unpause condition
* fedora-32 : special_testing_bindings
  * PR #6733
    * [06-23 19:18](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4928848678617088/html/integration_test.log.html)
  * PR #6689
    * [06-19 14:00](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5458638397505536/html/integration_test.log.html)
  * PR #6655
    * [06-17 16:31](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4771629823688704/html/integration_test.log.html)
    * [06-17 15:54](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5164624129556480/html/integration_test.log.html)
  * PR #6589
    * [06-15 13:06](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6335607536353280/html/integration_test.log.html)
  * PR #6515
    * [06-08 11:12](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4547364012687360/html/integration_test.log.html)
  * PR #6453
    * [06-01 12:44](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5392977415634944/html/integration_test.log.html)
  * PR #6356
    * [05-26 13:36](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4615038243700736/html/integration_test.log.html)

**Comment by rhatdan** [comment] 2020-07-25 11:20
@edsantiago Still an issue?

**Comment by edsantiago** [comment] 2020-07-25 12:09
Yes, at least as of three days ago.

Podman containers  [AfterEach] podman wait to pause|unpause condition
* fedora-32 : special_testing_bindings
  * PR #7053
    * [07-22 14:28](https://api.cirrus-ci.com/v1/task/5938556097003520/logs/integration_test.log)
  * PR #7003
    * [07-16 14:43](https://api.cirrus-ci.com/v1/task/5886289499127808/logs/integration_test.log)
  * PR #7001
    * [07-16 10:23](https://api.cirrus-ci.com/v1/task/6551437511491584/logs/integration_test.log)
  * PR #6906
    * [07-09 11:31]()
  * PR #6848
    * [07-02 15:23](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4811138992963584/html/integration_test.log.html)
  * PR #6846
    * [07-02 13:55](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6269985637007360/html/integration_test.log.html)
    * [07-02 13:29](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4973613445021696/html/integration_test.log.html)
  * PR #6821
    * [06-30 08:29](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5355871104401408/html/integration_test.log.html)
  * PR #6817
    * [06-30 08:42](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4908059426291712/html/integration_test.log.html)
    * [06-30 08:42](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4908059426291712/html/integration_test.log.html)
    * [06-29 21:46](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5256687273639936/html/integration_test.log.html)
    * [06-29 21:46](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5256687273639936/html/integration_test.log.html)
  * PR #6794
    * [06-29 10:59](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6503571845808128/html/integration_test.log.html)
    * [06-29 10:39](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5274684411346944/html/integration_test.log.html)
  * PR #6733
    * [06-23 19:18](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4928848678617088/html/integration_test.log.html) (already noted above)

**Comment by edsantiago** [comment] 2020-07-25 19:28
And [another one just now](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4916956467822592/html/integration_test.log.html), on my own PR #7070

**Comment by edsantiago** [comment] 2020-07-28 11:48
Another one yesterday:

* fedora-32 : special_testing_bindings
  * PR #7088
    * [07-27 06:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5233642425286656/html/integration_test.log.html)

Still no sign of it on anything other than f32

**Comment by rhatdan** [comment] 2020-08-28 14:18
@edsantiago Still an issue?

**Comment by edsantiago** [comment] 2020-08-31 12:06
Uh, well, no, because it was flaking so much that I disabled the test (#7143). I haven't tried to generate a reproducer, but if today is calm I will try to do so. I've removed the stale-issue label because until the test is reenabled, we don't know.

**Comment by edsantiago** [comment] 2020-09-08 17:38
Yes, still happening, in post-merge testing on master:
```
[+0517s] •! Panic in Spec Teardown (AfterEach) [2.851 seconds]
         Podman containers 
         /var/tmp/go/src/github.com/containers/podman/pkg/bindings/test/containers_test.go:17
           podman wait to pause|unpause condition [AfterEach]
           /var/tmp/go/src/github.com/containers/podman/pkg/bindings/test/containers_test.go:272
         
           Test Panicked
           send on closed channel
           /usr/lib/golang/src/runtime/panic.go:969
         
           Full Stack Trace
           panic(0x104b380, 0x13644d0)
           	/usr/lib/golang/src/runtime/panic.go:969 +0x166
           github.com/containers/podman/v2/pkg/bindings/test.glob..func5.20.2(0xc000010200, 0xc0001d7640, 0xc000c7eba8, 0xc0010b8520)
           	/var/tmp/go/src/github.com/containers/podman/pkg/bindings/test/containers_test.go:298 +0xc8
           created by github.com/containers/podman/v2/pkg/bindings/test.glob..func5.20
           	/var/tmp/go/src/github.com/containers/podman/pkg/bindings/test/containers_test.go:294 +0x6cc
```
Links, from most- to least-specific:
* [htmlified log](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5870210613772288/html/integration_test.log.html)
* [CI run](https://cirrus-ci.com/task/5870210613772288?command=integration_test#L1161)
* [CI job](https://cirrus-ci.com/build/5552420547723264)

**Comment by edsantiago** [comment] 2020-09-23 18:09
This is still happening. Recent failures:

  * PR #7698
    * [09-21 07:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5900828428992512/html/integration_test.log.html)
  * PR #7697
    * [09-19 06:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6347992624005120/html/integration_test.log.html)
  * PR #7680
    * [09-17 14:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5477936218243072/html/integration_test.log.html)
  * PR #7561
    * [09-11 07:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4662388567834624/html/integration_test.log.html)
    * [09-11 07:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4662388567834624/html/integration_test.log.html)

**Comment by rhatdan** [comment] 2020-11-10 21:37
@edsantiago still seeing this?

**Comment by edsantiago** [comment] 2020-11-10 21:38
Sorry, I haven't had time to look (at this nor the other stale-issue that you haven't pinged me about yet). Won't have time until Thursday most likely. But I will, I promise.

**Comment by edsantiago** [comment] 2020-11-11 19:12
Yes, still happening. I'll skip the September instances, and just list October/November:

* fedora : Test Bindings
  * PR #8111
    * [10-22 13:52](https://api.cirrus-ci.com/v1/task/4765044275675136/logs/main.log)
  * PR #8075
    * [10-20 13:48](https://api.cirrus-ci.com/v1/task/4651865780518912/logs/main.log)
* gce_instance:fedora : Test Bindings
  * PR #8231
    * [11-03 10:46](https://api.cirrus-ci.com/v1/task/5981506344583168/logs/main.log)

Note to self: the search term for cirrus-flake-summarize is "unpause"

**Comment by edsantiago** [comment] 2020-12-01 16:42
Still flaking. I've filed #8536 to re-disable the offending test.

  * PR #8535
    * [12-01 10:34](https://api.cirrus-ci.com/v1/task/4981488271753216/logs/main.log)
  * PR #8487
    * [11-26 06:21](https://api.cirrus-ci.com/v1/task/5335911053393920/logs/main.log)
  * PR #8410
    * [11-20 11:26](https://api.cirrus-ci.com/v1/task/6363281021468672/logs/main.log)
  * PR #8360
    * [11-16 16:55](https://api.cirrus-ci.com/v1/task/5612961274265600/logs/main.log)

**Comment by rhatdan** [comment] 2020-12-01 18:43
@edsantiago What do you think of this patch.  I think the issue is the second errchan is setup before the first one completes.  Causing the issue you are seeing.  If we separate the channels, we should not be closing the channel before it is used.

[diff.txt](https://github.com/containers/podman/files/5624692/diff.txt)

**Comment by edsantiago** [comment] 2020-12-01 18:51
I don't see how there could be a race here -- the code looks really sequential to me. But Go has subtleties I don't understand. I'm willing and even eager to give your approach a try for a few months, if you'd like to submit that! I will close this once your PR goes through CI and merges. Thank you!

**Comment by rhatdan** [comment] 2020-12-01 19:06
I am wondering if threads would skip over the wait error channel, but you may be right.  Only way I could see this happening would be if the second err = make(chan error) could fire before the close(errChan) in the fist function happened.

**Closed** 2020-12-01 21:09 UTC
Labels: flakes, kind/bug, kind/test-flake
