### ISSUE TITLE
Why docker pull is 100x times faster on any repo then podman?

### ISSUE THREAD

**Issue by korjavin** [containers/podman#12978] opened 2022-01-22 16:46 UTC
It's just impossible to believe in such big difference.

What is wrong? Is it storage issue or what?

```
Copying blob  ...

```
lasts for tens minutes.
Even if it mines bitcoin it's still not an explanation.

What should I check first?

**Comment by giuseppe** [comment] 2022-01-22 19:55
Can you please share your results?  What images have you tried?

**Comment by korjavin** [comment] 2022-01-22 20:00
Any,

 for example apache/superset

**Comment by giuseppe** [comment] 2022-01-23 00:47
Can you share the output of `time -v $runtime pull ...` for both podman and docker?

**Comment by vrothberg** [comment] 2022-01-24 13:09
Please provide the data requested in the issue template. Without reproducer and the data of the host (i.e., `podman info --debug`) it is impossible to know what's going on.

I tested `pull docker.io/apache/superset` on my machine and the performance is identical:
* Podman: 0m38.135s
* Docker: 0m39.315s

**Comment by giuseppe** [comment] 2022-01-26 08:28
since the issue lacks data to compare how Podman behaves differently, I am closing it.

Please reopen if you have more data to share

**Closed by giuseppe** 2022-01-26 08:28 UTC

**Comment by rhatdan** [comment] 2022-01-26 20:42
If I had to guess, the podman  was using vfs with lots of layers.

**Comment by korjavin** [comment] 2022-01-27 12:04
It must be some misconfiguration on my side.

After updating podman I started to get:
```
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve

```

during the `podman pull` i'm getting LA 


```load average: 35,70, 21,16, 9,74```

my system almost frozen

**Comment by vrothberg** [comment] 2022-01-27 12:10
@rhatdan's suspicion was right.  The `vfs` storage driver has very poor performance.  You already changed it to `overlay` but the local storage/database is still using `vfs`.  In order to change that, you can use `podman system reset`. Note that'll remove all images and containers.
