### ISSUE TITLE
Podman --tty breaks pipelines while docker does not

### ISSUE THREAD

**Issue by StayPirate** [containers/podman#9718] opened 2021-03-15 16:16 UTC
### Update

This issue was initially opened with the idea I was hitting a bug in Podman, it turned out that CRLF is set by the TTY (probably from [the kernel](https://github.com/moby/moby/issues/8513#issuecomment-218044116)), and the same behavior can be experienced with Docker as well.
Moving further with some tests I found that Podman misbehaves when pipes are involved, while Docker correctly handles them.
For a quick sum up jump to https://github.com/containers/podman/issues/9718#issuecomment-799925847, avoiding all the tests which brought me there.

---

/kind bug

**Description**

Whenever I run `podman container exec/run --tty [...]` the output use CRNL (0x0d, 0x0a) instead a simple NL (0x0a) at the end of each output line on Linux.

**Steps to reproduce the issue:**

1. `podman container run -d --name test alpine:latest sleep infitely `
2. `podman container exec -t test echo a | od -c`
```
0000000   a  \r  \n
0000003
```
3. `podman container exec test echo a | od -c` (without --tty)
```
0000000   a  \n
0000002
```

same issue with `run`:

1. `podman container run --rm -t alpine:latest echo a | od -c`
```
0000000   a  \r  \n
0000003
```
#### I also test it directly via `runc`
and I doubt it's `runc` fault, as was suggested https://github.com/containers/podman/issues/3179#issuecomment-494783055:
`runc exec -t c45fa68707ef26672b545a9fc6c317f1b48b5bc5f2df2c9bec22a7eac3339604 echo a | od -c`
```
0000000   a  \n
0000002
```
`podman container exec -t c45fa68707ef26672b545a9fc6c317f1b48b5bc5f2df2c9bec22a7eac3339604 echo a | od -c`
```
0000000   a  \r  \n
0000003
```

**Describe the results you expected:**

I'm expecting to only get `\n` at the end of each output line in Linux.

**Additional information:**

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.16
Git Commit:   c640670e85c4aaaff92741691d6a854a90229d8d
Built:        Sun Feb 21 16:29:46 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.26-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 0e155c83aa739ef0a0540ec9f9d265f57f68038b'
  cpus: 8
  distribution:
    distribution: manjaro
    version: unknown
  eventLogger: journald
  hostname: wintermute
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
  kernel: 5.10.19-1-MANJARO
  linkmode: dynamic
  memFree: 8877490176
  memTotal: 33389625344
  ociRuntime:
    name: runc
    package: /usr/bin/runc is owned by runc 1.0.0rc93-1
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
      spec: 1.0.2-dev
      go: go1.15.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.9-1
    version: |-
      slirp4netns version 1.1.9
      commit: 4e37ea557562e0d7a64dc636eff156f64927335e
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 9446825984
  swapTotal: 9446825984
  uptime: 19h 46m 9.72s (Approximately 0.79 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/crazybyte/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    .mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: /usr/bin/fuse-overlayfs is owned by fuse-overlayfs 1.4.0-1
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /home/crazybyte/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 34
  runRoot: /run/user/1000/containers
  volumePath: /home/crazybyte/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613921386
  BuiltTime: Sun Feb 21 16:29:46 2021
  GitCommit: c640670e85c4aaaff92741691d6a854a90229d8d
  GoVersion: go1.16
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (`pacman -Qii podman`):**

```
Name            : podman
Version         : 3.0.1-2
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  device-mapper  iptables  libseccomp  runc  slirp4netns  libsystemd  fuse-overlayfs  libgpgme.so=11-64
Optional Deps   : podman-docker: for Docker-compatible CLI
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support
                  crun: support for unified cgroupsv2
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 75.64 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Sun 21 Feb 2021 04:29:46 PM CET
Install Date    : Mon 01 Mar 2021 09:40:58 AM CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
Backup Files    :
(none)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm using Manjaro Linux, zsh (v. 5.8) and Tmux (v. 3.1c)

`stty -a` (zsh on my host system)
```
speed 38400 baud; rows 74; columns 189; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O;
min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```
`podman container exec -t c45fa68707ef26672b545a9fc6c317f1b48b5bc5f2df2c9bec22a7eac3339604 stty -a`
```
speed 38400 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
```

**Comment by StayPirate** [comment] 2021-03-15 16:20
related issues I read, but have not helped me are: https://github.com/containers/podman/issues/7942, https://github.com/containers/podman/issues/8342, https://github.com/containers/podman/issues/3179.

**Comment by eriksjolund** [comment] 2021-03-15 19:28
In this related Docker issue:
https://github.com/moby/moby/issues/37366#issuecomment-401157643
it is stated that this is not a bug.
The carriage return is added by the TTY (not Docker). I guess the situation is the same for Podman.

**Comment by StayPirate** [comment] 2021-03-16 02:55
> In this related Docker issue:
> [moby/moby#37366 (comment)](https://github.com/moby/moby/issues/37366#issuecomment-401157643)
> it is stated that this is not a bug.
> The carriage return is added by the TTY (not Docker). I guess the situation is the same for Podman.

This is very interesting, thanks. 

Can you tell me why podman behaves slightly different than docker?
```bash
$ docker run --rm --tty busybox sh -c "echo 1; echo 2" | od -c
0000000   1  \r  \n   2  \r  \n
0000006
$ docker run --rm --tty busybox sh -c "echo 1; echo 2" | cat -A
1^M$
2^M$
```

```bash
$ podman run --rm --tty busybox sh -c "echo 1; echo 2" | od -c
0000000   1  \r  \n   2  \r  \n
0000006
$ podman run --rm --tty busybox sh -c "echo 1; echo 2" | cat -A
1^M$
    2^M$
```
This messes up any output I'm trying to handle with a pipeline. Could you please tell me if you experience the same behavior??

**Comment by StayPirate** [comment] 2021-03-16 03:16
other examples with podman:
```bash
> $0 --version | head -n 1 # bash version
GNU bash, version 5.1.0(1)-release (x86_64-pc-linux-gnu)
> echo 1
1
> podman run --rm --tty busybox sh -c "stty -onlcr; echo 1; echo 2" | cat -A
1$
  2$
    > echo 1 | cat -A
1$
> podman run --rm --tty busybox sh -c "echo 1; echo 2" | cat -A
1^M$
    2^M$
        > echo 1 | cat -A
1$
> podman run --rm --tty busybox sh -c "stty -onlcr; echo 1; echo 2" | cat -A
1$
  2$
```

with docker:
```bash
> $0 --version | head -n 1 # bash version
GNU bash, version 5.1.0(1)-release (x86_64-pc-linux-gnu)
> docker run --rm --tty busybox sh -c "stty -onlcr; echo 1; echo 2" | cat -A
1$
2$
> docker run --rm --tty busybox sh -c "echo 1; echo 2" | cat -A
1^M$
2^M$
```
same behavior with zsh:
```bash
$0 --version | head -n 1 # zsh version
zsh 5.8 (x86_64-pc-linux-gnu)
> echo 1 | cat -A
1$
> docker run --rm --tty busybox sh -c "stty -onlcr; echo 1; echo 2" | cat -A
1$
2$
> docker run --rm --tty busybox sh -c "echo 1; echo 2" | cat -A
1^M$
2^M$
> podman run --rm --tty busybox sh -c "stty -onlcr; echo 1; echo 2" | cat -A
1$
  2$
    %                                                                                                                                                                                            > podman run --rm --tty busybox sh -c "echo 1; echo 2" | cat -A
1^M$
    2^M$
        % 
```

**Comment by StayPirate** [comment] 2021-03-16 03:39
Container engine apart, this is related to the shell. It seems once set `stty -onlcr`, from a sub-shell (or a container with access to the same TTY), that setting is then kept for subsequent commands. And TBH it sounds normal to me, since the shell and any sub-shell run within the same TTY.
```bash
> sh -c "echo 1; echo 2" | cat -A
1$
2$
> sh -c "stty -onlcr; echo 1; echo 2" | cat -A
1$
  2$
    > sh -c "echo 1; echo 2" | cat -At -A
1$
  2$
    > sh -c "stty onlcr; echo 1; echo 2" | cat -At -A
1$
2$
> sh -c "echo 1; echo 2" | cat -A
1$
2$
```
## More specific question is
Why docker behaves differently? It works ok with pipes even without touching TTY options ( `-onlcr` )
```bash
> podman run --rm --tty busybox sh -c "echo 1; echo 2" | cat -A
1^M$
    2^M$
```
```bash
> docker run --rm --tty busybox sh -c "echo 1; echo 2" | cat -A
1^M$
2^M$
```

**Comment by StayPirate** [comment] 2021-03-16 03:56
Summarize the findings above:

```bash
> # Podman behaves weirdly with CR and pipelines
> podman run --rm --tty busybox echo | cat -A
^M$
   > # pressed enter here
> # Docker handles it correctly instead
> docker run --rm --tty busybox echo | cat -A
^M$
> # pressed enter here
> # The expected correct behavior is shown by reproducing
> # the same output with echo. Same as Docker 
> echo -ne "\r\n" | cat -A
> ^M$
> # pressed enter here
> 
```
Why Podman behaves this way? It brakes all my pipelines.

**Comment by rhatdan** [comment] 2021-03-16 11:27
I would figure there is some bug/issue buried in podman that is causing the difference.

**Comment by mheon** [comment] 2021-03-16 11:36
Why are you using -t with pipes? The intended use of -t is user facing
applications - if you’re piping output into another command you should
avoid it.

**Comment by StayPirate** [comment] 2021-03-16 11:55
> Why are you using -t with pipes? The intended use of -t is user facing applications - if you’re piping output into another command you should avoid it.

I'm using `podman exec` in a way similar to `toolbox`, sometimes I need to just run something not interactive like 
```
podman container exec -ti -w $(pwd) container_name echo test
```
where `-t` can be omitted, but some other times I use interactive commands like: 
```
podman container exec -ti -w $(pwd) container_name vim file
or
podman container exec -ti -w $(pwd) container_name less file
```
For the latter examples I need `--tty` option enabled. My problems arise when I do `podman container exec -ti -w $(pwd) container_name echo test | whatever`

**Comment by StayPirate** [comment] 2021-03-16 11:55
> I would figure there is some bug/issue buried in podman that is causing the difference.

Do you know how these buried issues can be addressed?

**Comment by rhatdan** [comment] 2021-03-16 12:06
Nope,  @baude @mheon Any ideas?

**Comment by eriksjolund** [comment] 2021-03-16 12:13
Maybe this is a clue to different behaviour:
`stty -a` gives different results on Podman and Docker.
```
esjolund@laptop:~$ docker --version
Docker version 20.10.5, build 55c4c88
esjolund@laptop:~$ podman --version
podman version 3.0.1
esjolund@laptop:~$ podman run --rm --tty docker.io/busybox sh -c "stty -a" > /tmp/podman
esjolund@laptop:~$ docker run --rm --tty docker.io/busybox sh -c "stty -a" > /tmp/docker
esjolund@laptop:~$ cat /tmp/podman 
speed 38400 baud; rows 53; columns 238; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho
esjolund@laptop:~$ cat /tmp/docker 
speed 38400 baud;stty: standard input
 line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho
esjolund@laptop:~$ 
```

**Comment by mheon** [comment] 2021-03-16 12:34
Can you just omit -t on output you will be piping? The flag is independent
for each exec session so there is no obligation to use it every time.

**Comment by StayPirate** [comment] 2021-03-16 12:48
> Can you just omit -t on output you will be piping? The flag is independent for each exec session so there is no obligation to use it every time.

TBH this is not really a solution for my use-case, I don't know in advance when the container will be used to run an interactive or non-interactive command. I think this kind of issue will become more common with people start using containers as `toolbox` suggests.

I'm really wondering why this doesn't happen with Docker, I love Podman and I don't really want to fallback to Docker because of that...

**Comment by StayPirate** [comment] 2021-03-16 13:04
> Maybe this is a clue to the different behaviour:
> `stty -a` gives different results on Podman and Docker.
> 
> ```
> esjolund@laptop:~$ docker --version
> Docker version 20.10.5, build 55c4c88
> esjolund@laptop:~$ podman --version
> podman version 3.0.1
> esjolund@laptop:~$ podman run --rm --tty docker.io/busybox sh -c "stty -a" > /tmp/podman
> esjolund@laptop:~$ docker run --rm --tty docker.io/busybox sh -c "stty -a" > /tmp/docker
> esjolund@laptop:~$ cat /tmp/podman 
> speed 38400 baud; rows 53; columns 238; line = 0;
> intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
> -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
> -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
> opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
> isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho
> esjolund@laptop:~$ cat /tmp/docker 
> speed 38400 baud;stty: standard input
>  line = 0;
> intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
> eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
> werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
> -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
> -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
> -iuclc -ixany -imaxbel -iutf8
> opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
> isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
> echoctl echoke -flusho
> esjolund@laptop:~$ 
> ```

Thanks @eriksjolund that's a good starting point. I tried the same and I see that Podman is printing the exact `stty -a` output as it is run from the host system 
```bash
> # Host
> stty -a
speed 38400 baud; rows 51; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
> # From Podman
> podman container run --rm -t alpine:latest sh -c "stty -a"
speed 38400 baud; rows 51; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
>
```

**Comment by StayPirate** [comment] 2021-03-16 13:08
Interesting finding: Docker acts the same way when `-i` option is added!
```bash
> sudo podman container run --rm -t alpine:latest sh -c "echo" | cat -A
^M$
   > # pressed enter here
> sudo podman container run --rm -ti alpine:latest sh -c "echo" | cat -A
^M$
   > # pressed enter here
> sudo docker container run --rm -t alpine:latest sh -c "echo" | cat -A
^M$
> # pressed enter here
> sudo docker container run --rm -ti alpine:latest sh -c "echo" | cat -A
^M$
   > # pressed enter here
>
```
Does that ring a bell for you?

**Comment by zhangguanzhang** [comment] 2021-03-17 06:05
Replace --runtime and see if there is still this problem

**Comment by StayPirate** [comment] 2021-03-17 09:00
Thanks for the suggestion, but it doesn't seem to solve the problem
```bash
> podman container run --rm -t --runtime runc alpine:latest echo | cat -A
^M$
   > # pressed enter here
> podman container run --rm -t --runtime crun alpine:latest echo | cat -A
^M$
   > # pressed enter here
>
```

**Comment by giuseppe** [comment] 2021-03-17 14:01
I think you should not use --tty when outputting to a pipe.

What we could probably do with podman is to have an extension like --tty=auto that sets the tty only when outputting to a tty, but on the other end you could easily wrap this functionality in a script (check if `tty` succeeds and then add `--tty` to the podman command line).

**Comment by StayPirate** [comment] 2021-03-17 17:34
During a very pleasant chat with @giuseppe over IRC, he helped me to implement his suggestion to my context and it works great!
Drop the solution here for the record and hoping it will help others who will struggle with the same issue in the future.
```bash
podman_run () {
    _ti=""; tty 0<&1 &>/dev/null && _ti="-ti"
    podman container run --rm $_ti alpine:latest "$@"
}

> podman_run echo | cat -A
$
> 
```
Feel free to close this issue if this workaround is considered enough, for me it is.

**Comment by rhatdan** [comment] 2021-03-18 10:14
On my machine the only difference I see with `stty -a` is podman has `rows 43; columns 198; ` and docker has `stty: standard input`.

Not sure if this is important.  I would love to understand why we are getting the extra tab.

```
sh-5.1# docker run --rm --tty docker.io/busybox echo hello | cat -A
hello^M$
sh-5.1# podman run --rm --tty docker.io/busybox echo hello | cat -A
hello^M$
        sh-5.1# 
```

**Comment by rhatdan** [comment] 2021-03-18 10:18
Since `docker run -i` causes the same behavior, it looks like podman is doing something in non interactive mode that we should not  do.
```
docker run -i --rm --tty docker.io/busybox echo hello | cat -A
hello^M$
        sh-5.1# 
```

**Comment by StayPirate** [comment] 2021-03-18 15:15
> On my machine the only difference I see with `stty -a` is podman has `rows 43; columns 198; ` and docker has `stty: standard input`.

Same thing here, but I don't think this affects this misbehavior. 

> Not sure if this is important. I would love to understand why we are getting the extra tab.

I'd like to understand the reason behind that too. In the meantime, the workaround suggested by Giuseppe is doing its job ;)

**Comment by edsantiago** [comment] 2021-03-18 16:57
That's not a tab: it's an artifact of CR without NL:
```bash
$ ./bin/podman run --rm --tty docker.io/busybox echo hello hello hello | cat -A
hello hello hello^M$
                    $ 
$
```

**Comment by giuseppe** [comment] 2021-05-20 17:32
I still think that when the user asks for --tty then we have to create one, no matter what kind of file is used

**Comment by rhatdan** [comment] 2021-05-20 17:34
So you think we should close this as notabug?

**Comment by giuseppe** [comment] 2021-05-20 18:42
Yes, I think this is not a bug since the user asked for a tty

**Comment by rhatdan** [comment] 2021-05-20 18:45
Ok I will go along with that.

**Closed by rhatdan** 2021-05-20 18:45 UTC
Labels: kind/bug
