### ISSUE TITLE
5.3.0 release shasums file is incomplete

### ISSUE THREAD

**Issue by Nemric** [containers/podman#24558] opened 2024-11-14 10:07 UTC
Hi, 
I'm used to automatically download `podman-remote-static-linux_amd64.tar.gz` and `shasums` from  `https://github.com/containers/podman/releases/latest/download` that will take me to latest release download page, and then check the hash with `sha256sum`

but `shasums` is incomplete for 5.3.0 release packages and only contains 
```
f52a93a5f53c19505e672b6416db3057cdeec43e992eff1daf97e24480b011b0  podman-installer-macos-arm64.pkg
ab07df774334138b806476d754570a99b9b3ad513fb7a1875c86d4ef0d709719  podman-installer-macos-amd64.pkg
d5d20f4d91a92a8c12690a5414d0582b04660ecbffc2923659baa5a02792837a  podman-installer-macos-universal.pkg
1fa99609621603e26cd9dce90044729967cbcdaa9f2f999660adda203721bfcb  podman-5.3.0-setup.exe
```

**Comment by Luap99** [comment] 2024-11-14 12:33
Given this is all build by github action I would assume this is a duplicate of https://github.com/containers/podman/issues/22887 for the underlying cause. Anyway I will update the file manually in the meantime

**Closed** 2024-11-14 12:39 UTC
