### ISSUE TITLE
Volume directory has wrong permissions when overriding container directory

### ISSUE THREAD

**Issue by mohd-akram** [containers/podman#12523] opened 2021-12-06 16:27 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman, unlike Docker, does not seem to match the existing permissions of a container directory when overriding it with a volume. The steps below use the `podman-docker` alias.

**Steps to reproduce the issue:**

1. `docker run --rm -v osm-test:/var/lib/postgresql/12/main --entrypoint ls overv/openstreetmap-tile-server -lha /var/lib/postgresql/12; docker volume rm osm-test`

**Describe the results you received:**

```
drwx--x--x. 19 postgres postgres 4.0K Dec  6 00:11 main
```

**Describe the results you expected:**

```
drwx------ 19 postgres postgres 4.0K Dec  6 00:11 main
```

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Sat Nov 13 00:25:37 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: kde
    version: "35"
  eventLogger: journald
  hostname: razrlab-am
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.6-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 495935488
  memTotal: 15730135040
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4179636224
  swapTotal: 16533938176
  uptime: 31h 39m 47.57s (Approximately 1.29 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/mohamed/.config/containers/storage.conf
  containerStore:
    number: 14
    paused: 0
    running: 3
    stopped: 11
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-2.fc35.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
  graphRoot: /home/mohamed/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 21
  runRoot: /run/user/1000/containers
  volumePath: /home/mohamed/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636748737
  BuiltTime: Sat Nov 13 00:25:37 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.2-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by mheon** [comment] 2021-12-06 16:31
https://github.com/containers/podman/pull/10531 looks related, but that's been in since v3.3.0 so this is still occurring despite it.

**Comment by mheon** [comment] 2021-12-06 16:31
@rhatdan Any ideas?

**Comment by flouthoc** [comment] 2021-12-07 09:48
@mohd-akram @mheon Above PR should close this , we add extra `0111` to target path's stat causing this issues.

@mohd-akram I have verified patch with your reproducer feel free to try it.

**Comment by rhatdan** [comment] 2021-12-07 11:00
No idea or memory of where this came from.  Only thing I can think of is this had something to do with user namespace. @giuseppe @nalind @vrothberg Any ideas?
If the tests pass, I am fine with it.

**Closed** 2021-12-07 11:39 UTC
Labels: kind/bug
