### ISSUE TITLE
static ip address is already allocated, but that container is already deleted

### ISSUE THREAD

**Issue by nivekuil** [containers/podman#15708] opened 2022-09-08 22:44 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I am replacing a container with a new one with the same statically assigned IP.

Starting the new container gives:
```
$ podman start 9aa                                                                    
ERRO[0000] Starting some container dependencies         
ERRO[0000] "IPAM error: requested ip address 2a07::redacted is already allocated to container ID c4bf4b75204ab3abba9e950baf52aa2de6aa169dea1d7ca000dc4ce4c57b76ef" 
Error: unable to start container "9aa4f3c7acc19e3314af787d246a03b8730b5d5d32b277747fa219bafd0e7a7e": error starting some containers: internal libpod error
```
however the old container no longer exists:
```
$ podman container rm c4bf4b75204ab3abba9e950baf52aa2de6aa169dea1d7ca000dc4ce4c57b76ef
Error: no container with name or ID "c4bf4b75204ab3abba9e950baf52aa2de6aa169dea1d7ca000dc4ce4c57b76ef" found: no such container
```

**Steps to reproduce the issue:**
Not sure, think the container restarted a lot and there's a race condition freeing the IP somewhere?

A reboot fixed it.

**Describe the results you received:**
IP address allocated of nonexistent container

**Describe the results you expected:**
new container starts without issue

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 14:42:17 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 92.72
    systemPercent: 1.04
    userPercent: 6.23
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: dro-2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.19.6-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 13559296000
  memTotal: 16773713920
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 6h 3m 51.00s (Approximately 0.25 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 18
    paused: 0
    running: 15
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 214199939072
  graphRootUsed: 25624629248
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 41
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228937
  BuiltTime: Thu Aug 11 14:42:17 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by Luap99** [comment] 2022-09-09 07:47
There is no race, everything should be looked. Most likely the container cleanup failed and thus the ip was leaked in the DB.

**Comment by nivekuil** [comment] 2022-10-02 01:43
Think you fixed this with https://github.com/containers/podman/pull/16016?

**Comment by Luap99** [comment] 2022-10-02 10:19
I don't think so. Looking at the code in https://github.com/containers/common/blob/e5d97e0eea0a35d2b1bf15239a4130e89fee5619/libnetwork/netavark/run.go#L112 we should always delete static ips from the db. Therefore something before that must have failed and never called into that network cleanup code path.

**Comment by rhatdan** [comment] 2022-11-04 15:54
Since we have heard no further action on this issue, I am going to close.  Reopen if you believe there is still more work to be done.

**Comment by nivekuil** [comment] 2023-01-09 08:14
Still seeing this on 4.3.1.

**Comment by cig0** [comment] 2023-02-23 16:31
I hit this issue using `4.4.1`:

```
- podman nginx stop
- podman rm nginx
- podman run -d --name nginx -p 8443:8443 -v $HOME/mnt/nginx:/etc/nginx:Z --network=podman --ip=10.88.0.100 nginx:1.23-alpine-slim

Error: IPAM error: requested ip address 10.88.0.100 is already allocated to container ID 1e967bae12d2cf693e9e0ed3fa3593c694db671f994444a2d8bf6d0b942cee13
```

Is there any way I can proceed to remove this IP from Podman's database manually?

**Comment by rlenferink** [comment] 2023-02-23 18:48
I am also getting this issue with podman `4.4.1`

```
Error response from daemon: IPAM error: requested ip address 172.22.1.253 is already allocated to container ID 375fc9276b68b0201da0f9ee9eb7a14c50cb2ea58f9b61b1852310e9ba5b37ef
```

**Comment by heidricha** [comment] 2023-03-02 11:03
I'm on 4.4.2 (netavark 15.0, aardvark-dns 1.5.0) and experience the same
also using docker-compose

```
Creating svi-v42_frontend_1          ... error

ERROR: for svi-v42_frontend_1  Cannot start service frontend: IPAM error: requested ip address 10.89.0.110 is already allocated to container ID aba087df711bb3fedd7499dc3cf7000cace1618c3c0d8374a001ae4c05c78df5

ERROR: for frontend  Cannot start service frontend: IPAM error: requested ip address 10.89.0.110 is already allocated to container ID aba087df711bb3fedd7499dc3cf7000cace1618c3c0d8374a001ae4c05c78df5
ERROR: Encountered errors while bringing up the project.
sagemcom@svi-testlab-hun:~/v4.2.0-RC5/docker$ podman inspect aba087df711bb3fedd7499dc3cf7000cace1618c3c0d8374a001ae4c05c78df5
[]
Error: inspecting object: no such object: "aba087df711bb3fedd7499dc3cf7000cace1618c3c0d8374a001ae4c05c78df5"
```

I use external network, the issue still remains after removing and recreating the network

**Comment by heidricha** [comment] 2023-03-02 12:10
reproducible...

- start services with `docker-compose up`, make one of the unable to start, with something  like "port already allocated"
- fix the port allocation
- try to start services again

**Comment by cevich** [comment] 2023-03-02 20:30
Re-opened by request of @nivekuil

**Comment by anibal-aguila** [comment] 2023-05-23 11:18
Here the same issue...

**Comment by justinjereza** [comment] 2023-06-12 05:36
I think I just encountered the same problem with a rootful container on EL9 using podman 4.4.1.

* Built new image.
* Stopped quadlet container.
* Edited quadlet unit file because the image was renamed.
* Ran `systemctl daemon-reload`.
* `systemctl start` fails with the error `Error: IPAM error: requested ip address 10.88.0.2 is already allocated to container ID buildah-buildah1336789766`.

I made sure I deleted every container shown by `buildah containers --all` and I still got the same error.

**Comment by bobobo1618** [comment] 2023-07-18 19:50
In my case this happened after the container with that IP encountered a bind error. It's as if the IP is mapped before the bind but not cleaned up if the bind fails?

**Comment by rhatdan** [comment] 2023-07-30 09:57
@Luap99 Can you take a fresh look at this?

**Comment by Luap99** [comment] 2023-07-31 08:41
I landed some cleanup fixes in the past months that should be in podman v4.6 so please retest.

Without a proper reproducer there is nothing I can do.

**Comment by rhatdan** [comment] 2023-07-31 20:06
Ok lets assume that this is fixed until we have a reproducer.

**Closed by rhatdan** 2023-07-31 20:06 UTC
Labels: kind/bug, network
