### ISSUE TITLE
Additional `podman stats` metrics

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#9258] opened 2021-02-07 13:34 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It would be really helpful if additional column(s) could be added to those available when specifying custom `podman stats` output to indicate:

* maximum/high-water-mark memory usage;
* Average CPU usage (since started in in a given period);
* total CPU time;
* average I/O reads/second;
* average I/O writes/second;
* etc.

... of each container.

**Comment by rhatdan** [comment] 2021-02-08 22:04
Well PRs welcome.

**Comment by mpolden** [comment] 2021-02-10 14:17
Some of these metrics can be retrieved through runc: `runc events --stats <complete-container-id>`.

**Comment by anishasthana** [comment] 2021-05-10 00:44
I'd like to work on this.

**Comment by srcshelton** [comment] 2021-05-16 14:30
(Also, could someone fix the github-actions bot so that the `stale-issue` label is removed when someone replies to an issue?!)

**Comment by rhatdan** [comment] 2021-05-16 15:46
Please open a PR to make the change.

**Comment by srcshelton** [comment] 2021-05-16 16:04
> Please open a PR to make the change.

Possibly related to https://github.com/actions/stale/issues/441?

(Although https://github.com/actions/stale/issues/346 sounds useful to have)

I just checked, and we do have `remove-stale-when-updated` set to true (any this should be supported by the included version) - so it looks as if somethings not working, rather than anything's been omitted.

I can push a PR to bump the release of `stale` used from v1 to v3, in case anything's changed in the meantime?

**Comment by rhatdan** [comment] 2021-05-17 13:38
SGTM

**Comment by rhatdan** [comment] 2021-05-17 13:40
I would tell you the stale notification, is the squeaky wheel that gets me and others to look at old issues.  We don't close them automatically, we just attempt to see if they are still active or have been fixed in the last 30 days.

**Comment by rhatdan** [comment] 2021-06-09 09:37
@cdoern Take it.

**Comment by cdoern** [comment] 2021-06-25 20:18
CPU features implemented but reopening to link more PRs and new Stat features.

**Comment by srcshelton** [comment] 2021-06-29 17:32
I've commented on the (merged) change above:

https://github.com/containers/podman/pull/10696#issuecomment-870782566

In short, it appears that the current change only averages CPU usage (I've not checked time) over the period the single `stats` invocation is running, so when run with `--no-stream` the results aren't usable.

I feel that the counters for these stats should be associated with each running container, allowing accurate figures to be retrieved at any point whilst they still run.

**Comment by cdoern** [comment] 2021-06-29 17:37
@srcshelton I took a look earlier, you are right that the no stream doesn't seem to work with these I will look into a fix. Time seems to work as intended since the timers don't reset on every `stats` call

**Comment by mheon** [comment] 2021-06-29 17:42
I don't know if we can store metrics persistently. How would we capture them, considering Podman doesn't have a daemon?

**Comment by cdoern** [comment] 2021-06-29 17:46
@mheon I was just thinking the same thing. All of our other stats are captured "in the moment". the `avg cpu` usage (besides time) is the only cumulative stat we currently have.  Time only works because it is a `cgroupStat`

**Comment by srcshelton** [comment] 2021-06-30 16:03
Is there no facility for the long-running `podman run`, `common`, or `runc`/`crun` processes to be interrogated by a one-shot `podman stats` invocation to retrieve enough data to provide this form of statistic?

If not, could `podman` gain an additional mode (`podman monitor`?) which would attach to a running container (or all running containers?) and in a lightweight fashion gathers this data to then provide it to a separate `podman stats` call on demand - an optional mini-daemon, effectively?

**Comment by rhatdan** [comment] 2021-06-30 18:27
runc/crun run once and then die.
rootless podman can launch other services like fuse-overlay, slirp4netns and conmon.
Rootfull usually just does conmon.

**Comment by rhatdan** [comment] 2021-08-01 16:31
@srcshelton @cdoern @mheon What should we do with this issue?

**Comment by cdoern** [comment] 2021-08-02 12:54
@rhatdan thanks for the poke, one idea I had was to implement the other stats as I did with avg cpu %: **reset each time you call stats but is persistent as long as the stats stream is running**. Not sure if that is what @srcshelton would like, but the way we store stats isn't conducive to any other solution I don't think

**Comment by rhatdan** [comment] 2021-08-02 15:37
Works for me.

**Comment by srcshelton** [comment] 2021-08-03 15:15
> @rhatdan thanks for the poke, one idea I had was to implement the other stats as I did with avg cpu %: **reset each time you call stats but is persistent as long as the stats stream is running**. Not sure if that is what @srcshelton would like, but the way we store stats isn't conducive to any other solution I don't think

Hypothetically with this solution, would it be possible to have a lightweight daemon service keeping the steam (many steams for numerous containers?) alive, and then persist and offer-up these stats for the lifetime of the process?

The ideal would be to somehow and at any point find out the average CPU usage of a container over its entire lifetime to date - but if another collector process is needed to provide this to one-shot tools wishing to interrogate this data, that doesn't sound so bad?

**Comment by rhatdan** [comment] 2021-08-03 17:25
I don't see this as a requirement for Podman.  There is some information available from cgroups for this, I believe.  I am thinking cgroup accounting.  @nalind @giuseppe Any ideas?

**Comment by giuseppe** [comment] 2021-08-04 07:07
> The ideal would be to somehow and at any point find out the average CPU usage of a container over its entire lifetime to date

would that just require the cpu usage and how long the container is running?

We can grab the first information from cgroups and the second one from the OCI runtime (or reading directly `starttime` from `/proc/$CONTAINER_PID/stat`)

**Comment by cdoern** [comment] 2021-08-04 13:09
@giuseppe do cgroups store all of the old cpu % as well? the issue we are running into is that the time is correct, but the percentage only holds the most recent read, leading this to be a stream only feature.

**Comment by giuseppe** [comment] 2021-08-06 07:32
the cgroup stores the total usage of the cpu.  To calculate the percentage we use two measurements

**Comment by rhatdan** [comment] 2021-09-09 21:19
@giuseppe @cdoern any progress on this?

**Comment by giuseppe** [comment] 2021-09-27 10:48
I am not working on this issue.

@cdoern any update?  Can we close this issue?

**Comment by cdoern** [comment] 2021-09-29 23:26
No update from me, we can close for now and then if there is demand I can investigate the `/proc/CONTAINER_PID/stat` approach?

**Closed** 2021-09-30 16:21 UTC
Labels: Good First Issue, kind/feature, In Progress
