### ISSUE TITLE
Cannot remove pod after force remove of container within it

### ISSUE THREAD

**Issue by faandg** [containers/podman#15847] opened 2022-09-17 16:06 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. create pod with container in it (used podman play kube if that matters)

2. force remove (running) container using podman rm -f

3. trying to remove pod fails with lock reference to container (even with force)

**Describe the results you received:**
`podman pod ls`
POD ID        NAME           STATUS      CREATED            INFRA ID      # OF CONTAINERS
f8e764f124fe  plex-pod       Error       About an hour ago  841096105af8  1
`podman pod rm f8e764f124fe` 
Error: error freeing lock for container 841096105af849c53471e81e2de84dc1e07694683412bdad4e831d2128561980: no such file or directory
`podman pod rm -f f8e764f124fe `
Error: error freeing lock for container 841096105af849c53471e81e2de84dc1e07694683412bdad4e831d2128561980: no such file or directory

**Describe the results you expected:**
Expected pod removal, especially with `-f`, even if the container in it has been forcefully removed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Not much experience using podman pods but could not find any similar bug report.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.19
Git Commit:   7fe5a419cfd2880df2028ad3d7fd9378a88a04f4-dirty
Built:        Sat Aug 13 12:26:55 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.4-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: bd1459a3ffbb13eb552cc9af213e1f56f31ba2ee'
  cpuUtilization:
    idlePercent: 89.53
    systemPercent: 2.72
    userPercent: 7.76
  cpus: 16
  distribution:
    distribution: manjaro
    version: unknown
  eventLogger: journald
  hostname: ---
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.65-1-MANJARO
  linkmode: dynamic
  logDriver: journald
  memFree: 100619157504
  memTotal: 118115364864
  networkBackend: cni
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.5-2
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 0h 5m 10.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 12
    paused: 0
    running: 6
    stopped: 6
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 2000082173952
  graphRootUsed: 1027771244544
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 67
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660386415
  BuiltTime: Sat Aug 13 12:26:55 2022
  GitCommit: 7fe5a419cfd2880df2028ad3d7fd9378a88a04f4-dirty
  GoVersion: go1.19
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
pacman -Q podman
podman 4.2.0-1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Latest stable available on my distro.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment] 2022-09-19 13:36
Dupe of https://github.com/containers/podman/issues/15526, closing

**Closed by mheon** 2022-09-19 13:36 UTC
Labels: kind/bug

**Comment by faandg** [comment] 2022-09-19 20:27
I did actually skim the dupe and the lack of version info and HTTP API label threw me off track.
Thanks a lot for putting me back on it, `podman system renumber` fixed the broken state for me as well!
