### ISSUE TITLE
RUN instruction in Containerfile triggers SIGSEGV when `podman build .` on FreeBSD

### ISSUE THREAD

**Issue by grebokra** [containers/podman#24180] opened 2024-10-06 19:40 UTC
### Issue Description

I was experimenting with podman on FreeBSD 14.1-RELEASE, trying to see if it was already possible to perform the usual tasks I need with containers and container images.

I have written a simple Containerfile with several RUN instructions in it.

Suddenly, I've stumbled upon a SIGSEGV when tried to build a container image using `podman build .`

### Steps to reproduce the issue

Steps to reproduce the issue
1. Write a simple Containerfile with a RUN instruction in it:
```
FROM ghcr.io/dfr/freebsd14.1-small:latest
RUN freebsd-version -u > /freebsd-version.txt
CMD ["cat", "/freebsd-version.txt"]
```

2. do `podman build .`

### Describe the results you received

```
root@ebisu:~/probe # podman build . -f Containerfile -t test:latest
STEP 1/3: FROM ghcr.io/dfr/freebsd14.1-small:latest
STEP 2/3: RUN freebsd-version -u > /freebsd-version.txt
error running container: did not get container start message from parent: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x221f085]

goroutine 21 [running]:
github.com/containers/buildah.(*Builder).runUsingRuntimeSubproc(_, _, {0x8700fdc80, {0x0, 0x0}, 0x0, {0x870590780, 0x7}, {0x2914180, 0x0, ...}, ...}, ...)
        /wrkdirs/usr/ports/sysutils/podman/work/podman-5.1.1/vendor/github.com/containers/buildah/run_common.go:1256 +0x12e5
github.com/containers/buildah.(*Builder).Run(_, {_, _, _}, {0x8700fdc80, {0x0, 0x0}, 0x0, {0x870590780, 0x7}, ...})
        /wrkdirs/usr/ports/sysutils/podman/work/podman-5.1.1/vendor/github.com/containers/buildah/run_freebsd.go:325 +0x20b1
github.com/containers/buildah/imagebuildah.(*StageExecutor).Run(_, {0x1, {0x8706033e0, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        /wrkdirs/usr/ports/sysutils/podman/work/podman-5.1.1/vendor/github.com/containers/buildah/imagebuildah/stage_executor.go:815 +0x1050
github.com/openshift/imagebuilder.(*Builder).Run(0x87036e900, 0x87033f900, {0x90cd98, 0x8704801e0}, 0x1)
        /wrkdirs/usr/ports/sysutils/podman/work/podman-5.1.1/vendor/github.com/openshift/imagebuilder/builder.go:481 +0x527
github.com/containers/buildah/imagebuildah.(*StageExecutor).Execute(0x8704801e0, {0x907758, 0x87021f650}, {0x8700c44e0, 0x24})
        /wrkdirs/usr/ports/sysutils/podman/work/podman-5.1.1/vendor/github.com/containers/buildah/imagebuildah/stage_executor.go:1495 +0x33d5
github.com/containers/buildah/imagebuildah.(*Executor).buildStage(0x870190680, {0x907758, 0x87021f650}, 0x1?, {0x87054d7d0, 0x1, 0x1}, 0x0)
        /wrkdirs/usr/ports/sysutils/podman/work/podman-5.1.1/vendor/github.com/containers/buildah/imagebuildah/executor.go:570 +0x5c5
github.com/containers/buildah/imagebuildah.(*Executor).Build.func3.1()
        /wrkdirs/usr/ports/sysutils/podman/work/podman-5.1.1/vendor/github.com/containers/buildah/imagebuildah/executor.go:934 +0x2b1
created by github.com/containers/buildah/imagebuildah.(*Executor).Build.func3 in goroutine 53
        /wrkdirs/usr/ports/sysutils/podman/work/podman-5.1.1/vendor/github.com/containers/buildah/imagebuildah/executor.go:905 +0x305
root@ebisu:~/probe #
```

### Describe the results you expected

The expected result is not having a SIGSEGV in this situation.

### podman info output
```
host:
  arch: amd64
  buildahVersion: 1.36.0
  cgroupControllers: null
  cgroupManager: ""
  cgroupVersion: ""
  conmon:
    package: conmon-2.1.12_2
    path: /usr/local/bin/conmon
    version: 'conmon version 2.1.12, commit: unknown'
  cpuUtilization:
    idlePercent: 99.54013329116889
    systemPercent: 0.15013568902431482
    userPercent: 0.028336539914274452
  cpus: 4
  databaseBackend: sqlite
  distribution:
    distribution: freebsd
    version: "14.1"
  eventLogger: file
  hostname: ebisu.vill.int.nyansq.ru
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 14.1-RELEASE
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 6410510336
  memTotal: 8314462208
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns: {}
  ociRuntime:
    name: ocijail
    package: ocijail-0.4.0
    path: /usr/local/bin/ocijail
    version: ocijail version 0.4.0
  os: freebsd
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: false
    path: /var/run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: ""
    rootless: false
    seccompEnabled: false
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 56h 46m 50.00s (Approximately 2.33 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /usr/local/etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: zfs
  graphOptions: {}
  graphRoot: /var/db/containers/storage
  graphRootAllocated: 965468958720
  graphRootUsed: 2338816
  graphStatus:
    Compression: zstd
    Parent Dataset: data/containers
    Parent Quota: "no"
    Space Available: "965466619904"
    Space Used By Parent: "88195072"
    Zpool: data
    Zpool Health: ONLINE
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 9
  runRoot: /var/run/containers/storage
  transientStore: false
  volumePath: /var/db/containers/storage/volumes
version:
  APIVersion: 5.1.1
  Built: 1726890422
  BuiltTime: Sat Sep 21 06:47:02 2024
  GitCommit: ""
  GoVersion: go1.21.12
  Os: freebsd
  OsArch: freebsd/amd64
  Version: 5.1.1
```
### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

I'm running podman 5.1.1 on FreeBSD 14.1-RELEASE on a baremetal x86_64 host
```
# uname -a
FreeBSD ebisu.vill.int.nyansq.ru 14.1-RELEASE FreeBSD 14.1-RELEASE releng/14.1-n267679-10e31f0946d8 GENERIC amd64

# podman --version
podman version 5.1.1
```

### Additional information

Also tried to build an image from the same Containerfile using buildah command
```
root@ebisu:~/probe # buildah build --format=docker -f Containerfile -t test:latest .
STEP 1/3: FROM ghcr.io/dfr/freebsd14.1-small:latest
STEP 2/3: RUN freebsd-version -u > /freebsd-version.txt
STEP 3/3: CMD ["cat", "/freebsd-version.txt"]
COMMIT test:latest
Getting image source signatures
Copying blob 86da702b809a skipped: already exists
Copying blob 26a88751a2f5 skipped: already exists
Copying blob 801a8c54f568 skipped: already exists
Copying blob 807e35a5450f skipped: already exists
Copying blob 71a00b45753f skipped: already exists
Copying blob 298e881e67ac done   |
Copying config 0def77e88d done   |
Writing manifest to image destination
--> 0def77e88dde
Successfully tagged localhost/test:latest
0def77e88dde02b402dceb5f1554ce082b48076a90f1e010e77aa927dadf2cc3
root@ebisu:~/probe # podman run --rm test:latest
14.1-RELEASE-p5
```

works as expected

**Comment by Luap99** [comment] 2024-10-07 08:40
Duplicate of https://github.com/containers/buildah/issues/5748

**Closed by Luap99** 2024-10-07 08:40 UTC
Labels: kind/bug
