### ISSUE TITLE
Error: dial unix /var/folders/.../T/podman/qmp_podman-machine-default.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by doberkofler** [containers/podman#18410] opened 2023-05-02 08:54 UTC
### Issue Description

Every couple of days the podman engine stops and I get the following error:
```
podman machine start
Starting machine "podman-machine-default"
Error: dial unix /var/folders/2y/kvrr5nws6xz4nx9vnwjxj17w0000gn/T/podman/qmp_podman-machine-default.sock: connect: no such file or directory
```

The only way to start podman now is to reboot the computer.

### Steps to reproduce the issue

Unfortunately it cannot be reproduced as it only happens after 24-48 hours.

podman version:
```
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.3
Git Commit:   75e3c12579d391b81d871fd1cded6cf0d043550a
Built:        Fri Apr 14 15:28:20 2023
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.4.4
API Version:  4.4.4
Go Version:   go1.20.1
Built:        Mon Apr  3 13:29:09 2023
OS/Arch:      linux/amd64
```

### Describe the results you received

podman machine start
Starting machine "podman-machine-default"
Error: dial unix /var/folders/2y/kvrr5nws6xz4nx9vnwjxj17w0000gn/T/podman/qmp_podman-machine-default.sock: connect: no such file or directory

### Describe the results you expected

podman not to stop in the first place and then to start

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 69.91
    systemPercent: 3.42
    userPercent: 26.68
  cpus: 4
  databaseBackend: ""
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.2.9-300.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1826816000
  memTotal: 8312496128
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.3-2.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 11m 1.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 30540935168
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 20
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.4
  Built: 1680521349
  BuiltTime: Mon Apr  3 13:29:09 2023
  GitCommit: ""
  GoVersion: go1.20.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.4
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by doberkofler** [comment] 2023-05-02 14:09
I already had to restart my computer and don't know if it still meaningful but this is what i see:
```
ls /var/folders/2y/kvrr5nws6xz4nx9vnwjxj17w0000gn/T/podman/
total 16
-rw-r--r--@ 1 doberkofler  staff  4 May  2 10:40 podman-machine-default_proxy.pid
srwxr-xr-x@ 1 doberkofler  staff  0 May  2 10:40 podman-machine-default_ready.sock
-rw-------@ 1 doberkofler  staff  5 May  2 10:40 podman-machine-default_vm.pid
srwxr-xr-x@ 1 doberkofler  staff  0 May  2 10:40 qmp_podman-machine-default.sock
```

**Comment by baude** [comment] 2023-05-03 13:12
if it happens again, please take a peek and see ...

**Comment by doberkofler** [comment] 2023-05-03 18:43
I'm not sure, if this is related, but after I wanted to restart the engine because of another (#18444) issue I get the following error:
```
podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: cannot create PID file: Cannot lock pid file: Resource temporarily unavailable
```

**Comment by doberkofler** [comment] 2023-05-06 16:09
This seems to be the typical error now when podman crashes. Typically first all running container stop and can no longer be started but the engine is still running. After stopping the engine and trying to restart I get this error:

```
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: cannot create PID file: Cannot lock pid file: Resource temporarily unavailable
```

**Comment by vrothberg** [comment] 2023-07-31 12:15
I think it's a duplicate of https://github.com/containers/podman/issues/16054.  We're investigating.

**Closed by vrothberg** 2023-07-31 12:15 UTC
Labels: kind/bug, remote, macos, podman machine
