### ISSUE TITLE
Need Podman 3.1.1 in Kubic repo

### ISSUE THREAD

**Issue by pascapascapascapasca** [containers/podman#10117] opened 2021-04-22 16:22 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Kubic still has the RPMs for Podman 3.0.1 (in https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/ for example). Would it be possible to update it to at least 3.1.1?

**Comment by mheon** [comment] 2021-04-22 17:28
@lsm5 Were we holding off until we got a successful build through Bodhi in Fedora?

@pascapascapascapasca FYI, we have been having some stability issues with 3.1.x, hence the quick 3.1.0 -> 3.1.1 bump, and it's unclear if they're entirely resolved yet; we might be cutting a 3.1.2 next week. I think there's a general hesitance to push builds to Kubic, where there's no real validation of the quality of the package other than it building successfully, until we have tested elsewhere and confirmed things are working.

**Comment by pascapascapascapasca** [comment] 2021-04-22 17:31
Right, makes sense to me.

**Comment by vrothberg** [comment] 2021-04-22 17:43
Note that CentOS 7 will not receive version of Podman beyond 3.0.0 (see https://podman.io/blogs/2021/03/02/podman-support-for-older-distros.html).

**Comment by afbjorklund** [comment] 2021-04-23 06:42
> Note that CentOS 7 will not receive version of Podman beyond 3.0.0

Is there any plan for the stability issues in 3.0.x, beyond "change OS" ?

**Comment by rhatdan** [comment] 2021-04-23 08:25
No, this would be up to community.  We are not supporting or providing newer versions of Podman on RHEL7 or Centos7.

Red Hat engineering will continue to provide CVE fixes for the life of RHEL7, but not on the newer versions of Podman.

**Comment by lsm5** [comment] 2021-04-23 12:52
> @lsm5 Were we holding off until we got a successful build through Bodhi in Fedora?

@mheon will get to it today.

**Comment by lsm5** [comment] 2021-04-23 13:29
@pascapascapascapasca ah I just now noticed you mentioned CentOS 7. So like the others mentioned already, there won't be any further updates to CentOS 7 from the containers team, unless community members would like to take it up.

In case anyone in the community is willing to own CentOS 7 builds, I'm open to carrying CentOS 7 patches from them in the rpm spec files if that makes maintenance easier. But I can't spend any more of my time on it. 

HTH.

/cc @alitvak69

**Comment by lsm5** [comment] 2021-04-23 13:55
v3.1.2 built for centos8 and newer, and ubuntu 20.04 and newer. Closing this, guess we can re-open it if anyone in the community is willing to own CentOS 7. Let me know..

**Closed by lsm5** 2021-04-23 13:55 UTC
Labels: Packaging

**Comment by afbjorklund** [comment] 2021-04-23 14:18
Why was the Ubuntu requirement set higher ? Or was it too much administration to build for both 18.04 and 20.04 ?

**Comment by lsm5** [comment] 2021-04-23 15:11
@afbjorklund 18.04 also has really old packages needing way too much gymnastics for podman.

**Comment by alitvak69** [comment] 2021-04-23 15:22
CentOS 7 is supported until 2024.  Given the current situation with CentOS 8 / CentOS stream, I am sure number of people will use it for a while.  @lsm5 is correct of work required to support packaging for multiple OS distros and versions.  At this point we switched to building  our own packages with static binaries distributed with git or building them using nix.  It is not ideal either but seems to be working with Xenial, Bionic, Focal, and CentOS 7.  We are not planning to use CentOS 8 on bare metal hosts and slowly drifting to Ubuntu (or perhaps Debian if something happens to Ubuntu in the long run).

**Comment by afbjorklund** [comment] 2021-04-23 15:22
> @afbjorklund 18.04 also has really old packages needing way too much gymnastics for podman.

OK, I guess they can continue to use podman 2.2.1 until they are ready to upgrade to podman 3.1...

Unfortunately those packages are missing from the available downloads, similar to the static binaries.
But they could rebuild the binaries themselves, and then install them. Or build from source, perhaps.

The majority of the users seem to be on 20.04, which will be available for another year (until 22.04).

**Comment by mheon** [comment] 2021-04-23 15:46
Static binaries missing... Oops. That would be me forgetting to upload the artifacts.

**Comment by afbjorklund** [comment] 2021-04-23 15:52
> Static binaries missing... Oops. That would be me forgetting to upload the artifacts.

I don't think there has been any nix binaries for the last couple of release ? Only podman-remote

**Comment by mheon** [comment] 2021-04-23 16:54
Correct - we've never offered non-remote artifacts, from what I can remember.

**Comment by pascapascapascapasca** [comment] 2021-04-26 15:32
Thanks for the info all. So, if I want the fix for https://github.com/containers/podman/issues/10015, the solutions would be to either build the package from source or move to CentOS 8?

**Comment by glaszig** [comment] 2022-07-10 05:58
you just removed the podman 3.0 packages from the repo and broke our entire production pipeline. we're on centos 7 and we're not planing to upgrade the entire os which has vendor support until '24 only because the packages _of one package_ disappeared. i mean, the problem is not that there are no updates... **the packages in the centos 7 folder are just gone**.

yech. what a mess. seriously.

**Comment by lsm5** [comment] 2022-07-11 12:22
@glaszig you can still find podman in the centos 7 extras repo. And, we've always told production users to use distro packages and not depend on kubic.
