### ISSUE TITLE
podman unable to build on M2 mac

### ISSUE THREAD

**Issue by zozo6015** [containers/podman#16762] opened 2022-12-06 22:53 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

When trying to build using podman on an M2 mac the build process fails with the following error:

```
zozo@Peters-MacBook-Pro ~ % podman build -t quay.io/zozo6015/openjdk:11 --rm --no-cache .
ERRO[0303] 1 error occurred:
	* archive/tar: write too long

 
Error: Post "http://d/v4.3.1/libpod/build?dockerfile=%5B%22Dockerfile%22%5D&forcerm=1&identitylabel=1&idmappingoptions=%7B%22HostUIDMapping%22%3Atrue%2C%22HostGIDMapping%22%3Atrue%2C%22UIDMap%22%3A%5B%5D%2C%22GIDMap%22%3A%5B%5D%2C%22AutoUserNs%22%3Afalse%2C%22AutoUserNsOpts%22%3A%7B%22Size%22%3A0%2C%22InitialSize%22%3A0%2C%22PasswdFile%22%3A%22%22%2C%22GroupFile%22%3A%22%22%2C%22AdditionalUIDMappings%22%3Anull%2C%22AdditionalGIDMappings%22%3Anull%7D%7D&isolation=3&jobs=1&layers=1&networkmode=0&nocache=1&nsoptions=%5B%7B%22Name%22%3A%22user%22%2C%22Host%22%3Atrue%2C%22Path%22%3A%22%22%7D%5D&omithistory=0&output=quay.io%2Fzozo6015%2Fopenjdk%3A11&outputformat=application%2Fvnd.oci.image.manifest.v1%2Bjson&platform=%2F&pullpolicy=missing&rm=1&shmsize=67108864&t=quay.io%2Fzozo6015%2Fopenjdk%3A11": io: read/write on closed pipe
```

1. Install podman using brew or package on an M2 mac. 

2. Create a Dockerfile with this content:
```
FROM	alpine:3
LABEL	description="java 11"
ENV	TZ=UTC
RUN	apk add --no-cache bash openjdk11 curl
CMD	["bash", "-c", "while true; do date; sleep 5; done"]
```
3.  Initialize the podman machine using:
```
podman machine init
```

4. run the build:
```
podman build -t [quay.io/zozo6015/openjdk:11](http://quay.io/zozo6015/openjdk:11) . -f Dockerfile
```
**Describe the results you received:**
After waiting quite some time the build process errors out with the following message:
```
ERRO[0303] 1 error occurred:
	* archive/tar: write too long

 
Error: Post "http://d/v4.3.1/libpod/build?dockerfile=%5B%22Dockerfile%22%5D&forcerm=1&identitylabel=1&idmappingoptions=%7B%22HostUIDMapping%22%3Atrue%2C%22HostGIDMapping%22%3Atrue%2C%22UIDMap%22%3A%5B%5D%2C%22GIDMap%22%3A%5B%5D%2C%22AutoUserNs%22%3Afalse%2C%22AutoUserNsOpts%22%3A%7B%22Size%22%3A0%2C%22InitialSize%22%3A0%2C%22PasswdFile%22%3A%22%22%2C%22GroupFile%22%3A%22%22%2C%22AdditionalUIDMappings%22%3Anull%2C%22AdditionalGIDMappings%22%3Anull%7D%7D&isolation=3&jobs=1&layers=1&networkmode=0&nocache=1&nsoptions=%5B%7B%22Name%22%3A%22user%22%2C%22Host%22%3Atrue%2C%22Path%22%3A%22%22%7D%5D&omithistory=0&output=quay.io%2Fzozo6015%2Fopenjdk%3A11&outputformat=application%2Fvnd.oci.image.manifest.v1%2Bjson&platform=%2F&pullpolicy=missing&rm=1&shmsize=67108864&t=quay.io%2Fzozo6015%2Fopenjdk%3A11": io: read/write on closed pipe
```

**Describe the results you expected:**
The image should be built and should be listed using `podman images`

**Additional information you deem important (e.g. issue happens only occasionally):**
if I ssh into the podman machine and run the build in there everything works as expected.

**Output of `podman version`:**

```
podman version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.8
Built:        Wed Nov  9 22:43:58 2022
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 17:00:31 2022
OS/Arch:      linux/arm64
```

**Output of `podman info`:**

```
host:
  arch: arm64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc37.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 98.79
    systemPercent: 0.78
    userPercent: 0.43
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "37"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.0.9-300.fc37.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1408610304
  memTotal: 2049859584
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7-1.fc37.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.7
      commit: 40d996ea8a827981895ce22886a9bac367f87264
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.aarch64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 28m 4.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 62911938560
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178831
  BuiltTime: Fri Nov 11 17:00:31 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/arm64
  Version: 4.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
==> podman: stable 4.3.1 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.3.1 (185 files, 47.6MB) *
  Poured from bottle on 2022-12-06 at 02:15:47
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0 and GPL-3.0-or-later
==> Dependencies
Build: go-md2man ✘, go@1.18 ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions

To restart podman after an upgrade:
  brew services restart podman
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/podman/bin/podman system service --time=0
==> Analytics
install: 28,436 (30 days), 80,258 (90 days), 240,801 (365 days)
install-on-request: 25,932 (30 days), 75,783 (90 days), 235,203 (365 days)
build-error: 13 (30 days)
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
running on an M2 macbook pro.

**Comment by mheon** [comment] 2022-12-07 18:55
@ashley-cui PTAL

**Comment by ashley-cui** [comment] 2022-12-07 19:45
I'm unable to reproduce on M1 and don't have access to an M2 machine. Just in case, could you try rm-ing and re-initing a new machine and trying the build again? Occasionally that helps.

**Comment by zozo6015** [comment] 2022-12-07 19:52
```
podman machine ls
NAME                     VM TYPE     CREATED       LAST UP       CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        43 hours ago  43 hours ago  1           2.147GB     107.4GB
```

```
podman machine rm

The following files will be deleted:

/Users/zozo/.ssh/podman-machine-default
/Users/zozo/.ssh/podman-machine-default.pub
/Users/zozo/.config/containers/podman/machine/qemu/podman-machine-default.ign
/Users/zozo/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-37.20221127.2.0-qemu.aarch64.qcow2
/Users/zozo/.local/share/containers/podman/machine/podman-machine-default/podman.sock
/Users/zozo/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd
/Users/zozo/.config/containers/podman/machine/qemu/podman-machine-default.json


Are you sure you want to continue? [y/N] y
```

```
podman machine init
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

	podman machine start

❯ podman machine start
Starting machine "podman-machine-default"
WARN[0000] podman helper is installed, but was not able to claim the global docker sock 
Waiting for VM ...
Mounting volume... /Users/zozo:/Users/zozo

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command: 

	podman machine set --rootful

API forwarding listening on: /Users/zozo/.local/share/containers/podman/machine/podman-machine-default/podman.sock

Another process was listening on the default Docker API socket address.
You can still connect Docker API clients by setting DOCKER_HOST using the
following command in your terminal session:

	export DOCKER_HOST='unix:///Users/zozo/.local/share/containers/podman/machine/podman-machine-default/podman.sock'

Machine "podman-machine-default" started successfully
```

```
podman build -t quay.io/zozo6015/openjdk:11 . -f Dockerfile
ERRO[0136] 1 error occurred:
	* archive/tar: write too long

 
Error: Post "http://d/v4.3.1/libpod/build?dockerfile=%5B%22Dockerfile%22%5D&forcerm=1&identitylabel=1&idmappingoptions=%7B%22HostUIDMapping%22%3Atrue%2C%22HostGIDMapping%22%3Atrue%2C%22UIDMap%22%3A%5B%5D%2C%22GIDMap%22%3A%5B%5D%2C%22AutoUserNs%22%3Afalse%2C%22AutoUserNsOpts%22%3A%7B%22Size%22%3A0%2C%22InitialSize%22%3A0%2C%22PasswdFile%22%3A%22%22%2C%22GroupFile%22%3A%22%22%2C%22AdditionalUIDMappings%22%3Anull%2C%22AdditionalGIDMappings%22%3Anull%7D%7D&isolation=3&jobs=1&layers=1&networkmode=0&nsoptions=%5B%7B%22Name%22%3A%22user%22%2C%22Host%22%3Atrue%2C%22Path%22%3A%22%22%7D%5D&omithistory=0&output=quay.io%2Fzozo6015%2Fopenjdk%3A11&outputformat=application%2Fvnd.oci.image.manifest.v1%2Bjson&platform=%2F&pullpolicy=missing&rm=1&shmsize=67108864&t=quay.io%2Fzozo6015%2Fopenjdk%3A11": io: read/write on closed pipe
```

**Comment by baude** [comment] 2022-12-13 20:57
any chance you have large objects or lots of little ones in the context dir?

**Comment by zozo6015** [comment] 2022-12-13 21:06
context dir contained only the Dockerfile nothing else

**Comment by rhatdan** [comment] 2023-01-18 23:55
@zozo6015 Do you still have this issue?

**Comment by zozo6015** [comment] 2023-01-19 08:14
yes

**Comment by rhatdan** [comment] 2023-02-21 20:01
@flouthoc PTAL

**Comment by zozo6015** [comment] 2023-02-22 12:56
Not sure what happened but podman was able to build the same version that before wasn't.

**Comment by rhatdan** [comment] 2023-02-22 13:51
I think this means I can close this issue, reopen if I am mistaken.

**Closed by rhatdan** 2023-02-22 13:51 UTC
Labels: kind/bug, remote, macos
