### ISSUE TITLE
Cannot run image in Mac podman

### ISSUE THREAD

**Issue by corbym** [containers/podman#11875] opened 2021-10-06 10:04 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running podman on mac fails with an error:

```
> podman run ed210e3e4a5b 
Error: error preparing container 331d3ca3ad0a32ae41285b76d898e769c4350911e104f348e871975bc1db2990 for attach: error configuring network namespace for container 331d3ca3ad0a32ae41285b76d898e769c4350911e104f348e871975bc1db2990: error adding pod determined_knuth_determined_knuth to CNI network "podman": unexpected end of JSON input

```
**Steps to reproduce the issue:**

1. build an image on macos with `podman build .`

2. try to run the image `podman run [image]`

**Describe the results you received:**
```
Error: error preparing container 331d3ca3ad0a32ae41285b76d898e769c4350911e104f348e871975bc1db2990 for attach: error configuring network namespace for container 331d3ca3ad0a32ae41285b76d898e769c4350911e104f348e871975bc1db2990: error adding pod determined_knuth_determined_knuth to CNI network "podman": unexpected end of JSON input
```

**Describe the results you expected:**
A running container.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens all the time.

**Output of `podman version`:**

```
Client:
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.17.1
Built:        Thu Sep 30 19:44:31 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Mon Aug 30 21:46:14 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-1.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    version: "35"
  eventLogger: journald
  hostname: linux
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-60.fc35.x86_64
  linkmode: dynamic
  logDriver: ""
  memFree: 1040297984
  memTotal: 2061529088
  ociRuntime:
    name: crun
    package: crun-1.0-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.0
      commit: 139dc6971e2f1d931af520188763e984d6cdfbf8
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 42h 9m 16.04s (Approximately 1.75 days)
plugins:
  log: null
  network: null
  volume: null
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 11
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1630356374
  BuiltTime: Mon Aug 30 20:46:14 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
> brew list podman 
/usr/local/Cellar/podman/3.4.0_1/bin/podman
/usr/local/Cellar/podman/3.4.0_1/bin/podman-remote
/usr/local/Cellar/podman/3.4.0_1/etc/bash_completion.d/podman
/usr/local/Cellar/podman/3.4.0_1/libexec/gvproxy
/usr/local/Cellar/podman/3.4.0_1/share/fish/vendor_completions.d/podman.fish
/usr/local/Cellar/podman/3.4.0_1/share/man/ (160 files)
/usr/local/Cellar/podman/3.4.0_1/share/zsh/site-functions/_podman

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
MacOS

**Comment by afbjorklund** [comment] 2021-10-06 11:18
See https://github.com/containers/podman/issues/11837

**Comment by Luap99** [comment] 2021-10-06 12:24
Duplicate of #11837

**Closed by Luap99** 2021-10-06 12:24 UTC
Labels: kind/bug
