### ISSUE TITLE
a rootless privileged container refuses to start if a host device layout has changed

### ISSUE THREAD

**Issue by nefigtut** [containers/podman#4900] opened 2020-01-18 02:07 UTC
/kind bug

**Description**

a rootless privileged container refuses to start if a host device layout has changed since its creation. 

**Steps to reproduce the issue:**

1. install the latest available podman:
   ```
    # dnf install podman-1.7.1-1579308829.gitce4bf33c.fc31.x86_64.rpm`
   ```

2. create regular rootless privileged container:
    ```
    $ podman create --hostname=test --name=podman-test --privileged -it fedora:31 bash
    4064af39d51912b991132022d1211c5a2e57828a8d1a8e65a5c769c3ebb03064
    ```

3. run it to verify it is fine and quit:
    ```
    $ podman start -ia podman-test
    [root@test /]# exit
   ```

4. **unplug the mouse or any other usb device**

5. try to rum the container again:
   ```
    $ podman start -ia podman-test
    Error: unable to start container 4064af39d51912b991132022d1211c5a2e57828a8d1a8e65a5c769c3ebb03064: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/dev/bus/usb/001/014\\\" to rootfs \\\"/home/vladis/.local/share/containers/storage/overlay/c74f7eeb485fa7ef272fccd713c628e293a6ef2fe9698f3d94ce3fc028c6a5ea/merged\\\" at \\\"/dev/bus/usb/001/014\\\" caused \\\"stat /dev/bus/usb/001/014: no such file or directory\\\"\"": OCI runtime command not found error
   ```

6. cry in despair and try to work it around

7. edit `~/.local/share/containers/storage/libpod/bolt_state.db` with a hex editor

8. replace with spaces all two occurrences of:
    `{"destination":"/dev/bus/usb/001/014","type":"bind","source":"/dev/bus/usb/001/014","options":["slave","nosuid","noexec","rw","rbind"]},`

9. breath out:
   ```
    $ podman start -ia podman-test
    [root@test /]# exit
   ```

**Describe the results you received:**
a rootless privileged container refuses to start if i unplug a mouse

**Describe the results you expected:**
i expect this container to start

**Additional information you deem important (e.g. issue happens only occasionally):**

reproduces with a podman package at the latest commit as of today.

yes, `man podman-create` states:

> A “privileged” container is given access to all devices.
> When the operator executes a privileged container, Podman enables access to all devices on the host

i understand that podman will mount all the devices it remembers for the privileged containers. but i would expect it is able to handle such volatile things like usb devices and other plug/unplug devices which presence is expected to change over time. at least, it would be great to have a way to work around this problem, like `--ignore-unexisting-mounts` for `podman start` or something.

**Output of `podman version`:**

```
$ podman version
Version:            1.7.1-dev
RemoteAPI Version:  1
Go Version:         go1.13.5
Git Commit:         6408303711bef45e21e2ed5f4ec90dd679aa31f8-dirty
Built:              Sat Aug  4 02:00:00 2018
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: 6408303711bef45e21e2ed5f4ec90dd679aa31f8-dirty
  go version: go1.13.5
  podman version: 1.7.1-dev
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: podman-1.7.1-1579308829.gitce4bf33c.fc31.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.7, commit: 6408303711bef45e21e2ed5f4ec90dd679aa31f8-dirty'
  Distribution:
    distribution: fedora
    version: "29"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 24305704960
  MemTotal: 33083305984
  OCIRuntime:
    name: runc
    package: runc-1.0.0-95.rc9.gitc1485a1.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 26f9c71f0ee5e621be1ae6d0aa4bfa1a8d072e4c
      spec: 1.0.1-dev
  SwapFree: 17179865088
  SwapTotal: 17179865088
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: rules
  kernel: 5.4.8-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-2.git1798179.fc29.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3
      commit: 179817925a6b37e8b80ba552f3998de5c4611703
  uptime: 12h 31m 18.08s (Approximately 0.50 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: ~/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.5-2.fc29.x86_64
      Version: |-
        fuse-overlayfs: version 0.6.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: ~/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/1000
  VolumePath: ~/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ rpm -q podman
podman-1.7.1-1579308829.gitce4bf33c.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical Lenovo P50 laptop

**Comment by mheon** [comment] 2020-01-18 02:22
I don't think we want to remove the general-case requirement that mount sources must exist in order to be mounted into the container, so I think we need a more narrowly-tailored fix here.

Can we mount the entirety of /dev from the host, instead of individual devices, and then mount over whatever we want to replace?

**Comment by rhatdan** [comment] 2020-01-19 13:09
@giuseppe Could you take a look at this?

**Comment by giuseppe** [comment] 2020-01-20 10:08
> Can we mount the entirety of /dev from the host, instead of individual devices, and then mount over whatever we want to replace?

if we give access to `/dev` and mount stuff on top of it, then a privileged container can still umount the new mounts and get access to the underlying files.  e.g. we now skip mounting `/dev/tty` from the host.  If we would mount `/dev` from the host then cover it with a new tmpfs, the user inside of the container can still umount("/dev/tty") and get access to the original files.

With root containers, where we create the devices with mknod, we have a similar problem and new devices don't appear inside of the container.

I'd prefer we keep root and rootless as close as possible.  If it is fine that a privileged container has access to the host `/dev` then we could simplify both cases with a `-v /dev:/dev`.

**Comment by mheon** [comment] 2020-02-04 14:46
Why are we closing this? I'm pretty sure it's still an issue

**Comment by rhatdan** [comment] 2020-02-04 20:44
I read @giuseppe response to say we won't change the way this works.  If I am mistaken then reopen.

**Comment by nefigtut** [comment] 2020-02-06 08:28
errr.... the issue is not resolved. i believe, binary hacking bolt_state.db to make a container run is not a solution. as mentioned, it would be great to have, at least, `--ignore-unexisting-mounts` for `podman start` or something alike.

**Comment by giuseppe** [comment] 2020-02-17 13:38
> errr.... the issue is not resolved. i believe, binary hacking bolt_state.db to make a container run is not a solution. as mentioned, it would be great to have, at least, `--ignore-unexisting-mounts` for `podman start` or something alike.

that won't be enough.  That kind of check must be done by the OCI runtime.  Otherwise there is a race condition by the time Podman checks for the existence of the source and the time the OCI runtime creates the bind mount.

That is unlikely to be adopted in the OCI runtime specs, the best we could possibly to is to add a custom extension/annotation to crun to support it.

**Comment by edsantiago** [comment] 2020-02-19 21:31
OMG. Confirmed: if I happen to create the container with my Yubikey plugged in, then start it after unplugging Yubikey, podman barfs. I consider this a serious usability bug.

**Comment by mheon** [comment] 2020-02-19 22:22
I would love to see something like this in the OCI runtime spec - that seems like the most logical place.

@giuseppe Is there an issue or PR against runtime-spec to track this?

**Comment by giuseppe** [comment] 2020-02-20 08:16
> @giuseppe Is there an issue or PR against runtime-spec to track this?

it is not tracked anywhere at the moment

**Comment by rhatdan** [comment] 2020-02-21 16:24
@vbatts PTAL

**Comment by vbatts** [comment] 2020-02-21 19:28
trying out @edsantiago reproducer with docker 19.03.2 this does not seem to be the case.
Perhaps that is something that is reconciled at 'start' of the container?

**Comment by mheon** [comment] 2020-02-21 19:31
If we want to move this into Libpod, we could. There's still the potential for a race between finalizing the spec on the Libpod side and passing it into `runc`, though. Not sure how big of a deal that is.

**Comment by giuseppe** [comment] 2020-02-24 09:04
> trying out @edsantiago reproducer with docker 19.03.2 this does not seem to be the case.

running as root doesn't have this problem as it can use `mknod`, same for Podman.

The issue only happens with rootless where `mknod` is not allowed and we need to bind mount the devices.

Even if we fix Podman to check whether the devices exist before the container runs, there is still a race condition and the device can disappear before the mount is done

**Comment by rhatdan** [comment] 2020-03-26 09:56
@mheon @giuseppe What should we do with this issue.

**Comment by giuseppe** [comment] 2020-03-26 11:37
I am not 100% sure how to proceed here.  We could use `-v /dev/:/dev/:rslave` for rootless.  It is not ideal and one difference more with root containers but it is the only thing we can do.

**Comment by rhatdan** [comment] 2020-03-26 12:20
Why don't we just tighten it up at least for rootless environments so podman fixes the environment  before launching the OCI Runtime.  Then we could also make a small change to crun to handle it and suggest this as a fix for runc.  @AkihiroSuda WDYT?

**Comment by rhatdan** [comment] 2020-03-26 12:20
This is very likely to be an issue with toolbox correct?

**Comment by mheon** [comment] 2020-03-26 13:33
What are the disadvantages of directly mounting `/dev` and then mounting over where we need to? I'm inclined to do that unless we have a good reason not to.

**Comment by giuseppe** [comment] 2020-03-26 13:41
> This is very likely to be an issue with toolbox correct?

toolbox is already forcing `-v /dev/:/dev:rslave` so this is not an issue anymore.



> What are the disadvantages of directly mounting `/dev` and then mounting over where we need to? I'm inclined to do that unless we have a good reason not to.

one disadvantage I can think of is that a rootless container gets access to `/dev/tty` from the host.  It is not so bad as anyway it doesn't gain more privileges than the unprivileged user, but I'd have preferred if it wasn't not accessible at all.

**Comment by rhatdan** [comment] 2020-03-26 14:19
Well potentially a container could hit the user with a prompt like

Password:

On the tty?  Or potentially listen to tty communications.  Not sure SELinux would do a great job of blocking this or not.

**Comment by mheon** [comment] 2020-03-26 14:21
Can we mask the path and/or mount over it with our own TTY device?

**Comment by giuseppe** [comment] 2020-03-26 14:28
> Can we mask the path and/or mount over it with our own TTY device?

masked paths are applied after all the other mounts so we cannot use here.  We still have our own `/dev/pts` but if a container has `CAP_SYS_ADMIN` (so the issue doesn't apply to most containers) then it is able to umount it.

**Comment by rhatdan** [comment] 2020-03-26 15:09
If your container has CAP_SYS_ADMIN, then we offer little protections.

**Comment by nefigtut** [comment] 2020-03-31 10:34
afaiu, the issue is not about protection, it is about an ability to start a container. coudn't we provide a switch like `--ignore-unexisting-mounts` for `podman start`, so mounts not existing at the start time are, well, ignored? or `--ignore-unexisting-mounts=usb` so missing `/dev/bus/usb` mounts are ignored.

**Comment by giuseppe** [comment] 2020-03-31 13:31
> coudn't we provide a switch like `--ignore-unexisting-mounts` for `podman start`, so mounts not existing at the start time are, well, ignored? or `--ignore-unexisting-mounts=usb` so missing `/dev/bus/usb` mounts are ignored.

that won't be enough, there would still be a race condition: https://github.com/containers/libpod/issues/4900#issuecomment-586997767

**Comment by edsantiago** [comment] 2020-03-31 14:39
>there would still be a race condition

Is that really such a problem? I believe that, at least in the USB case, a user is somewhat likely to be aware of what happens in the window between hitting ENTER and having podman emit that error. "Oops, I unplugged that mouse, I'll try again". With the current situation, the user would have to remember "oh yes, when I first created that container four months and three days ago, I had my USB backup drive plugged in". Le mieux est l'ennemi du bien and all that.

**Comment by mheon** [comment] 2020-03-31 14:51
We already have a number of mount options that are consumed within Libpod (`:z` and `:Z`) - so what if we added another one for mounts that are allowed to be missing? We can tag all device bind mounts for rootless as `:allowmissing` and, when we assemble the final spec, if the mount isn't there we don't include it. There's still a small race here between spec generation and container start, but that doesn't seem like that significant of an issue (just restart the container to fix)

**Comment by rhatdan** [comment] 2020-06-09 19:20
@giuseppe @mheon @baude Lets talk about this at the next standup.  We should think of ways to fix this.

**Comment by jmou** [comment] 2020-09-05 17:51
Hi sorry if this is already known, but I just wanted to share my experience between podman and docker. I can reproduce this issue on podman with:
```
$ podman create --name test --privileged debian true
0e7237521ea2a99348997441d7cd36e4486e5b11e6537286929ab02adba4f6a8
$ # unplug usb device (webcam)
$ podman start test
Error: unable to start container "0e7237521ea2a99348997441d7cd36e4486e5b11e6537286929ab02adba4f6a8": error stat'ing file `/dev/bus/usb/001/044`: No such file or directory: OCI runtime command not found error
```

With docker:
```
$ # plug in usb device                                                                                                
$ ls /dev/bus/usb/001/
001  002  006
$ sudo docker create --name test --privileged debian sleep +Inf
6c404d4fd3b0efe667928f5924d2763d7fd397ae50e3e3489e87edb0851d9fda
$ sudo docker start test
test
$ sudo docker exec -i test ls /dev/bus/usb/001/
001
002
006
$ # unplug usb device
$ ls /dev/bus/usb/001/
001  002
$ sudo docker exec -i test ls /dev/bus/usb/001/
001
002
006 
$ sudo docker stop test
test 
$ sudo docker start test
test 
$ sudo docker exec -i test ls /dev/bus/usb/001/
001  
002
```

When I unplug the device, the running docker container still includes the removed usb device. It is no longer present when the container is restarted. It looks like docker reconfigures /dev when the container starts.

**Comment by GitYangYang** [comment] 2020-09-27 08:39
same issue,after remove my xbox wireless adapter:
`
ERRO[0000] unable to start container "confluence": time="2020-09-27T16:28:39+08:00" level=warning msg="exit status 1"
time="2020-09-27T16:28:39+08:00" level=error msg="container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/dev/bus/usb/001/005\\\\\\\" to rootfs \\\\\\\"/home/yangyang/.local/share/containers/storage/overlay/7d34a8384bdcd143c5404aa6c835a7db315692610404fcc3de743e42d2e02cbf/merged\\\\\\\" at \\\\\\\"/dev/bus/usb/001/005\\\\\\\" caused \\\\\\\"stat /dev/bus/usb/001/005: no such file or directory\\\\\\\"\\\"\""
`

**Comment by rhatdan** [comment] 2020-11-24 14:09
@giuseppe Any movement on this?

**Comment by giuseppe** [comment] 2020-11-25 08:49
I think we have a better way to deal with the issue now, using something like `-v /dev:/dev --mount type=devpts,target=/dev/pts` so that the `/dev/pts` is mounted on top of `/dev`

**Comment by rhatdan** [comment] 2020-12-26 11:31
@nefigtut Did you try @giuseppe suggestion?  Does it work for  you?

**Comment by rhatdan** [comment] 2021-01-27 13:30
CLosing for lack of response.  Reopen if more data available.

**Comment by sshnaidm** [comment] 2021-03-23 23:03
I have same problem with podman pod, one of containers can't stop after I inserted USB dongle in a laptop. Removing it doesn't help.
```
Error: error starting container 310d424f65ab81d5bbb053aeed9e1043157179817107378ca64dc2af067988a4: error stat'ing file `/dev/bus/usb/001/012`: No such file or directory: OCI not found
```

**Comment by rhatdan** [comment] 2021-03-24 13:15
Can you give a command you used to get into this state?

**Comment by sshnaidm** [comment] 2021-03-24 13:30
`podman pod stop`, insert or change USB device, `podman pod start`
Pod is: https://paste.centos.org/view/5b77d868

**Comment by mheon** [comment] 2021-03-24 13:52
Reopening.

We either need to:
- Make Giuseppe's approach (mount in /dev with a custom devpts mount) default for all privileged containers.
- Modify Libpod to re-read devices and re-create them in the spec every time the container starts.

**Comment by rhatdan** [comment] 2021-03-24 20:41
I like the /dev, approach.

**Comment by Sanqui** [comment] 2021-07-11 15:05
Is there a recommended procedure to restore access to a container hit by this issue?  Is the best workaround still editing the binary file `bolt_state.db` by hand?

**Comment by mheon** [comment] 2021-07-12 15:20
It ought to be possible to re-create the container by grabbing its create command from `podman inspect`, committing the container to an image, and re-creating using the original command and the new image.

**Comment by vrothberg** [comment] 2021-09-23 08:51
@mheon didn't we close a similar issue this week?

**Comment by mheon** [comment] 2021-09-23 14:48
Not that I recall?

This is definitely still something we have to fix.

**Comment by edsantiago** [comment] 2021-09-23 18:11
@vrothberg were you thinking of #11425?

**Comment by vrothberg** [comment] 2021-09-24 07:09
Ah, I was thinking of https://github.com/containers/podman/issues/11239 which is still open.

**Closed** 2021-10-12 10:35 UTC
Labels: kind/bug

**Comment by mheon** [comment] 2022-01-10 14:23
Same issue. We store the host device layout from the time the container was created in privileged containers, which means any changes result in the container being unable to start.

**Comment by dzintars** [comment] 2022-05-27 15:32
Seeing this issue as well. Can't start the container after i stopped it. No changes in devices.

**Comment by rhatdan** [comment] 2022-05-28 11:25
Please open a new issue, not just add to a closed issue.  You seem to be reporting something different Since you have no changes in devices. We need podman info and a reproducer in the new issue.

**Comment by criztovyl** [comment] 2022-06-11 15:42
I second https://github.com/containers/podman/issues/4900#issuecomment-1008865710, not sure how https://github.com/containers/podman/issues/11239 is related, I think this issue should be reopened.

I wrote a script for applying the libpod-state workaround w/o using a hex editor.
https://github.com/criztovyl/fix-podman-changed-dev-layout

Unfortunately minikube then failed with a different error and I had to recreate...

**Comment by criztovyl** [comment] 2022-06-11 16:29
I'm on podman 3.0.1 (Debian 11) ([details](https://gist.github.com/criztovyl/6379c51f70de6febcf10fd1d03dd8c44)) and can reproduce with slightly simplified steps from the  initial description:

0. have an usb device you can plug out
1. have that device plugged in
2. `podman create --name usb-test --privileged busybox`
3. unplug the usb device
4. `podman start -a usb-test`
    <pre>Error: unable to start container ...: error stat'ing file `/dev/bus/usb/.../...`: No such file or directory: OCI not found</pre>

**Comment by mheon** [comment] 2022-06-11 19:15
A fix for this has merged and will be included in Podman 4.2, which I believe we expect in mid-July.

**Comment by criztovyl** [comment] 2022-06-11 19:50
ah, great! that's #14483 (#13899), yes? It's even indirectly linked above, missed that.

**Comment by nefigtut** [comment] 2022-06-12 12:25
thanks a ton, @mheon!
