### ISSUE TITLE
Using "--preserve-fds" sometimes prints "Error: error attaching to container" ... "read unixpacket @->/proc/self/fd/16/attach: read: connection reset by peer"

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman#11446] opened 2021-09-04 07:35 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When using `podman run` with the command-line option `--preserve-fds` I sometimes see this error message

```
Error: error attaching to container 74939f1723c3d69ca3632b7a859b4c89d2da663767aa1e0ed6070e712cef2a5c: read unixpacket @->/proc/self/fd/16/attach: read: connection reset by peer
```

I ran the same command twice.  Only one time the error message was shown.

**Steps to reproduce the issue:**

1. Create a new user account 
```
[root@fedora ~]# useradd -m erikdev2
[root@fedora ~]# machinectl shell erikdev2@
Connected to the local host. Press ^] three times within 1s to exit session.
[erikdev2@fedora ~]$ 
```

2. Pull the image _docker.io/library/fedora_
```
[erikdev2@fedora ~]$ podman pull docker.io/library/fedora
Trying to pull docker.io/library/fedora:latest...
Getting image source signatures
Copying blob b9705287bb9f done  
Copying config dce66322d6 done  
Writing manifest to image destination
Storing signatures
dce66322d6472e195c624cd3bd0c6c13918c00d1022c653a95341491a1597f52
[erikdev2@fedora ~]$
```

3. Run these commands

```
[erikdev2@fedora ~]$ echo hello > file.txt
[erikdev2@fedora ~]$ echo | podman run --security-opt label=disable  --rm -i --preserve-fds 1 --pull=never docker.io/library/fedora sh -c "cat <&3" 3< file.txt
hello
[erikdev2@fedora ~]$ echo | podman run --security-opt label=disable  --rm -i --preserve-fds 1 --pull=never docker.io/library/fedora sh -c "cat <&3" 3< file.txt
hello
Error: error attaching to container 74939f1723c3d69ca3632b7a859b4c89d2da663767aa1e0ed6070e712cef2a5c: read unixpacket @->/proc/self/fd/16/attach: read: connection reset by peer
[erikdev2@fedora ~]$ 
```

**Describe the results you received:**

I see the error message
```
Error: error attaching to container 74939f1723c3d69ca3632b7a859b4c89d2da663767aa1e0ed6070e712cef2a5c: read unixpacket @->/proc/self/fd/16/attach: read: connection reset by peer
```
**Describe the results you expected:**

I didn't expect to see the error message.

**Additional information you deem important (e.g. issue happens only occasionally):**

It is not deterministic. I created a new user _erikdev3_ and followed the same steps. Now the result was:
first four times with the error message, and then one time without the error message.
 

```
[erikdev3@fedora ~]$ echo | podman run --security-opt label=disable  --rm -i --preserve-fds 1 --pull=never docker.io/library/fedora sh -c "cat <&3" 3< file.txt
hello
Error: error attaching to container a7af2de9d3e1d13a65f663c10bff87dcc8413f5060719c2d53f1b72370c45bd9: read unixpacket @->/proc/self/fd/16/attach: read: connection reset by peer
[erikdev3@fedora ~]$ echo | podman run --security-opt label=disable  --rm -i --preserve-fds 1 --pull=never docker.io/library/fedora sh -c "cat <&3" 3< file.txt
hello
Error: error attaching to container 44cf91df37d32d585bdc5ea6c53097d5850b3f6da0901da29ad23265d93bd8f3: read unixpacket @->/proc/self/fd/16/attach: read: connection reset by peer
[erikdev3@fedora ~]$ echo | podman run --security-opt label=disable  --rm -i --preserve-fds 1 --pull=never docker.io/library/fedora sh -c "cat <&3" 3< file.txt
hello
Error: error attaching to container cfbf8939df37a06e70b98488ea4c8432fce2d1448a93e636b94beb1ec6a3ab47: read unixpacket @->/proc/self/fd/16/attach: read: connection reset by peer
[erikdev3@fedora ~]$ echo | podman run --security-opt label=disable  --rm -i --preserve-fds 1 --pull=never docker.io/library/fedora sh -c "cat <&3" 3< file.txt
hello
Error: error attaching to container 0627b1600dfab91ac80a554fb422628635d8886c8230ebf6b8d9eb6743a8bac1: read unixpacket @->/proc/self/fd/16/attach: read: connection reset by peer
[erikdev3@fedora ~]$ echo | podman run --security-opt label=disable  --rm -i --preserve-fds 1 --pull=never docker.io/library/fedora sh -c "cat <&3" 3< file.txt
hello
[erikdev3@fedora ~]$ 
```

**Output of `podman version`:**

```
podman version 3.3.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 16
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
  kernel: 5.13.13-200.fc34.x86_64
  linkmode: dynamic
  memFree: 5732679680
  memTotal: 7689117696
  ociRuntime:
    name: crun
    package: crun-1.0-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.0
      commit: 139dc6971e2f1d931af520188763e984d6cdfbf8
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1003/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 7688155136
  swapTotal: 7688155136
  uptime: 1h 12m 54.02s (Approximately 0.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/erikdev2/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/erikdev2/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1003/containers
  volumePath: /home/erikdev2/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1630356396
  BuiltTime: Mon Aug 30 23:46:36 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.1-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I was logged in to the computer via SSH.

**Comment by eriksjolund** [comment] 2021-09-04 20:13
I'm starting to think that this has nothing to do with `--preserve-fds`. The nondeterministic behavior  probably stems from the fact  that there are two commands involved in the pipe (`echo` and `podman`) and it's not clear which of them will finish first. 

```
$ echo | podman run --security-opt label=disable -i --rm --pull=never docker.io/library/fedora sleep 1.0e-1
$ echo | podman run --security-opt label=disable -i --rm --pull=never docker.io/library/fedora sleep 1.0e-2
$ echo | podman run --security-opt label=disable -i --rm --pull=never docker.io/library/fedora sleep 1.0e-3
Error: error attaching to container afce5f596384260f86077cb5d0ccddbb38b885de70b82d34602cf7953f5f078a: read unixpacket @->/proc/self/fd/15/attach: read: connection reset by peer
$ 
```

Maybe this is just expected behavior?

**Comment by eriksjolund** [comment] 2021-09-10 19:40
Simplifying it a bit, it could look like this
```
echo | podman run --rm -i --pull=never docker.io/library/fedora /bin/true
```

As a test I ran a for loop with 1000 iterations on my laptop (Fedora 34). I was not using SSH this time. 
The error message was shown 4 times.   

```
$ for i in $(seq 1 1000) ; do echo | podman run --rm -i  --pull=never docker.io/library/fedora /bin/true || echo $i; done
Error: error attaching to container 5673d0a74727901cd25fcdf9c859901ab89abf0894a2f38e7263e5056826338f: read unixpacket @->/proc/self/fd/15/attach: read: connection reset by peer
87
Error: error attaching to container 0538196366acb845ff4bf8ac1a1a6d98bc8148561127c63a64cb7d11d8b82085: read unixpacket @->/proc/self/fd/15/attach: read: connection reset by peer
395
Error: error attaching to container 209ed2cf95f011c34347c909b3b841b212a7c5cc298dac541f06259f5e3bc9bb: read unixpacket @->/proc/self/fd/15/attach: read: connection reset by peer
526
Error: error attaching to container 65a3ecfd5672afe087823fca4a97dbdac40004be41ba9f5a23ccc534300a664d: read unixpacket @->/proc/self/fd/15/attach: read: connection reset by peer
590
$ 
```



Previously when I logged in over SSH to the other computer it seemed to happen every time with a fast running program (e.g. `/bin/true`). I'm not sure if this was due to the properties of the other computer or  if it was due to using SSH.

**Comment by rhatdan** [comment] 2021-11-16 01:11
What would be the expected behaviour here.  Should we just not return an error?  This looks like stdin is closed before we attach it to the container.

**Comment by rhatdan** [comment] 2021-11-16 01:11
@edsantiago WDYT?

**Comment by edsantiago** [comment] 2021-11-16 18:08
I can't reproduce this on my laptop (f35), neither with `podman-3.4.1-1.fc35` nor main @ f031bd23c6f5f790dde383d542c940bfe2dfaadd. 

One consistent element of your reports is the high fd number: 15, 16. Perhaps this is a stupid question, but is there something in your environment that produces this? What does `ls -l /proc/self/fd` show when run from your shell?

**Comment by eriksjolund** [comment] 2021-11-16 18:46
@edsantiago  I can reproduce it with podman-3.4.1-1.fc35 on my Fedora 35 laptop.

```
[root@laptop ~]# useradd my
[root@laptop ~]# machinectl shell my@
Connected to the local host. Press ^] three times within 1s to exit session.
[my@laptop ~]$ ls -l /proc/self/fd
total 0
lrwx------. 1 my my 64 Nov 16 19:33 0 -> /dev/pts/21
lrwx------. 1 my my 64 Nov 16 19:33 1 -> /dev/pts/21
lrwx------. 1 my my 64 Nov 16 19:33 2 -> /dev/pts/21
lr-x------. 1 my my 64 Nov 16 19:33 3 -> /proc/61824/fd
[my@laptop ~]$ which podman
/usr/bin/podman
[my@laptop ~]$ podman --version
podman version 3.4.1
[my@laptop ~]$ rpm -qf /usr/bin/podman
podman-3.4.1-1.fc35.x86_64
[my@laptop ~]$ podman pull -q docker.io/library/fedora 
b080de8a4da3da9ec2fdbeeb6d70d94079b27df87483039fc45abd2152109c43
[my@laptop ~]$ for i in $(seq 1 1000) ; do echo | podman run --rm -i  --pull=never docker.io/library/fedora /bin/true || echo $i; done
Error: error attaching to container 3bb2ced8a28ce894971912cb9840238bf144c8ef8359efaf647cae896062c871: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
33
Error: error attaching to container edc41bd80c858e4e56ffab716ca2c242209b3dad440ec8613368807c51042f3d: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
43
Error: error attaching to container 702fbad18147dc48414c0ff5432270489cdecc7587ed069956ecd0d8bb80179f: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
84
Error: error attaching to container f4b284db6e2aaee06c322619173ecb650323ecf7d03ea83ea93f61105e8d98a1: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
250
Error: error attaching to container b1038e05bdd56015af9705775436a0327d68cdd2cd59d64c68874999a3b06cf4: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
357
Error: error attaching to container 756eb2799f3bd818aeaa8963a36557b033e1a8abd73d6ca661636593dc68f86e: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
592
[my@laptop ~]$ echo $?
0
[my@laptop ~]$ cat /proc/cpuinfo | grep "model name" | head -1
model name	: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
[my@laptop ~]$ 
```

**Comment by rhatdan** [comment] 2021-11-16 19:59
I got this to happen on my f34 box within a couple of seconds.

**Comment by snhardin** [comment] 2021-12-16 06:15
Seeing an issue similar to this on Mac OS X using Podman 3.4.2. Attempting to pass a file via STDIN to a `podman run` command using `<` operator works the first time but fails subsequent times until the virtual machine is restarted. Docker is unaffected.

```
Could not part 0: ENOENT: no such file or directory, open ''
Error: write unixpacket @->/proc/self/fd/13/attach: write: connection reset by peer
```

Using `cat FILE.json | podman run ...` is a workaround.

**Comment by mheon** [comment] 2021-12-16 14:24
Are you using `--preserve-fds`? If not, I think this merits a fresh issue, as it's a separate bug. If so, it's probably still a fresh bug deserving of a separate issue, because that flag shouldn't be available for remote (we can't forward FDs across to the VM, so it doesn't make much sense).

**Comment by eriksjolund** [comment] 2021-12-16 14:45
@mheon  My reproducer in https://github.com/containers/podman/issues/11446#issuecomment-917163965 does not make use of `--preserve-fds`.
When created this issue, I thought it was directly connected to `--preserve-fds` but now when I can reproduce the error message without `--preserve-fds` I tend to think that  `--preserve-fds` is not so important for this issue.

**Comment by mheon** [comment] 2021-12-16 14:47
OK.

**Comment by rhatdan** [comment] 2022-01-18 10:38
@eriksjolund are you still seeing this issue.  @giuseppe you were working on some issues with closing of FDs could this be an issue you were dealing with?

**Comment by eriksjolund** [comment] 2022-01-18 10:58
@rhatdan yes 
(my laptop runs fedora 35, podman 3.4.4)

**Comment by rhatdan** [comment] 2022-02-21 18:53
@eriksjolund Still seeing this with podman 4?

**Comment by eriksjolund** [comment] 2022-02-21 19:02
@rhatdan yes
```
[test@laptop ~]$ rpm -qf /usr/bin/podman
podman-4.0.0-9.fc35.x86_64
[test@laptop ~]$ podman pull -q docker.io/library/fedora 
b78af7a836928efd44317e82c8f2f9c86bb83ae915deef1b58dc6465dfa5436e
[test@laptop ~]$ for i in $(seq 1 1000) ; do echo | podman run --rm -i  --pull=never docker.io/library/fedora /bin/true || echo $i; done
Error: error attaching to container 2f5184930997d09a4ef400f969e79e2cca969a16d39dbad58449cb7c5a334c9e: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
44
Error: error attaching to container 94cab9c4faaea6889830360c0fb61f722120351d227779b57a5590cf1a9f89db: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
110
Error: error attaching to container 8248946d880fc42b2a9cee37251babae0d27ac2c1e1a9be2b1f1e79e3667c0bb: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
153
Error: error attaching to container f6fd50ac78733e43cac7c358909b9305a6644bf727fcfcfe97e99ea743818ada: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
181
[test@laptop ~]$ ^C
```
(I pressed Ctrl-C after a while)

**Comment by rhatdan** [comment] 2022-02-21 20:26
@giuseppe Thoughts?

**Comment by giuseppe** [comment] 2022-02-22 08:29
so the issue doesn't depend on `--preserve-fds`?

I've tried the reproducer above but I am not able to see it locally.  What version of conmon are you using?

**Comment by eriksjolund** [comment] 2022-02-22 08:59
I use this conmon version
```
$ rpm -q conmon
conmon-2.1.0-2.fc35.x86_64
```

**Comment by rhatdan** [comment] 2022-03-25 11:36
@eriksjolund @giuseppe any update on this?

**Comment by giuseppe** [comment] 2022-03-25 16:27
I've tried again to reproduce locally but no luck

**Comment by eriksjolund** [comment] 2022-03-25 18:19
I currently don't have access to the laptop that I used for the previous tests,
but I can reproduce the issue on another computer.

Running 
```
for i in $(seq 1 1000) ; do echo | podman run --rm -i --pull=never docker.io/library/fedora /bin/true || echo $i; done
```
in one Bash terminal didn't reproduce the issue, but running the the command in two Bash terminals at the same time reproduced the issue:

```
$ for i in $(seq 1 1000) ; do echo | podman run --rm -i --pull=never docker.io/library/fedora /bin/true || echo $i; done
Error: error attaching to container 1e293e9ce7318cc90d0e431d44ad04738f4584db1d5e8ec90a06b6ace4f4469a: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
172
```

Software versions:
```
$ rpm -q podman
podman-4.0.2-5.fc35.x86_64
$ rpm -q conmon
conmon-2.1.0-2.fc35.x86_64
$ cat /etc/fedora-release 
Fedora release 35 (Thirty Five)
$ 
```

**Comment by giuseppe** [comment] 2022-03-28 12:30
still no luck, I've tried on two different systems.  Have you changed anything in the default configuration?  In what environment are you running that command (GNOME, ssh, ...)?

**Comment by eriksjolund** [comment] 2022-03-28 13:29
#### Previous laptop HP EliteBook 850 G6
On the previous laptop that I currently don't have access to, I was logged in to a gnome-session and ran the command in gnome-terminal. At that time I had the feeling that I could trigger more failures by opening up many web browser tabs and switch between the web browser tabs rapidly. (I didn't test it enough times to validate that theory though. It could also have been my imagination). In the previous laptop, I was able to reproduce the error with high probability, maybe it was 5-10 errors per 1000 iterations. It never happened that I got no errors when running 1000 iterations.

#### Latest test on Asus PN-51
For the last test in https://github.com/containers/podman/issues/11446#issuecomment-1079284832, I logged in via SSH to a  Asus PN-51 (mini PC) that was running Fedora 35. If I remember correctly, I installed Podman like this

```
 $ sudo dnf copr enable rhcontainerbot/podman4
 $ sudo dnf install podman
```

I think the Asus PN-51 wasn't running anything else. The computer must have had little CPU load except the two for loops.

**Comment by edsantiago** [comment] 2022-03-28 17:26
It now reproduces for me, using `registry.fedoraproject.org/fedora:latest  (750037c05cfe)`. It does not reproduce with `quay.io/libpod/testimage:20210610` (which is based on alpine).
```console
$ for i in $(seq 1 1000) ; do printf "\r%04d..." $i;echo | bin/podman run --rm -i --pull=never fedora:latest /bin/truei; done
0359...Error: error attaching to container 2a3a2d7999cd802ff1ca1397295f7f5f020bf86b6c9135ebc646133a9965b6dd: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
0456...Error: error attaching to container 9391a5acfa539a5dfe0f6c4e5be308c402bb2ee475ec2e793032597085d438eb: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
1000...%
```
podman main @ b76d717bbfc41188d4e03641c33200f2814a0baf on f35

**Comment by edsantiago** [comment] 2022-03-28 18:55
Also reproduces with `registry.access.redhat.com/ubi8:latest  @ 552ac8ae4291`:
```console
$ for i in $(seq 1 1000) ; do printf "\r%04d..." $i;echo | bin/podman run --rm -i --pull=never ubi8 /bin/true; done
0479...Error: error attaching to container dbed19cd66bc38ddb3457cc49a23aafe87ad16df46bdc34b299b2b4986fade3a: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer
1000...%   
```

**Comment by giuseppe** [comment] 2022-03-30 06:56
I've attempted your reproducer twice:

```
$ for i in $(seq 1 1000) ; do printf "\r%04d..." $i;echo | bin/podman run --rm -i --pull=never fedora:latest /bin/true; done
1000...
```

What kernel version are you using?  I am on `5.16.14-200.fc35.x86_64`

**Comment by rhatdan** [comment] 2022-05-03 19:05
@giuseppe Did you ever go any further with this?

**Comment by giuseppe** [comment] 2022-05-04 13:04
opened a PR: https://github.com/containers/podman/pull/14109

**Closed** 2022-05-04 17:12 UTC
Labels: kind/bug
