### ISSUE TITLE
Podman exec fails.

### ISSUE THREAD

**Issue by MrErr** [containers/podman#8401] opened 2020-11-18 21:19 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.podman start nextcloud

2. podman ps --filter name=nextcloud
CONTAINER ID  IMAGE                         COMMAND         CREATED       STATUS                PORTS   NAMES
9b47d3d27e18  localhost/nextcloud:18.0.0-1  /usr/sbin/init  3 months ago  Up About an hour ago          nextcloud

3. podman exec -it nextcloud ls
Error: exec failed: container_linux.go:349: starting container process caused "process_linux.go:105: adding pid 3049948 to cgroups caused \"failed to write 3049948 to cgroup.procs: write /sys/fs/cgroup/machine.slice/libpod-9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2.scope/cgroup.procs: device or resource busy\"": OCI runtime error

**Describe the results you received:** I got an exec error as mentioned above.

**Describe the results you expected:** The output of ls is expected output.

**Additional information you deem important (e.g. issue happens only occasionally):** This does not happen on all containers. I think it started to happen when i changed from cgroups v1 to cgroups v2.

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Oct  7 11:21:20 2020
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: xroads
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.9.8-200.fc33.x86_64
  linkmode: dynamic
  memFree: 13861302272
  memTotal: 33420734464
  ociRuntime:
    name: crun
    package: crun-0.15.1-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15.1
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 12884893696
  swapTotal: 12884893696
  uptime: 1h 48m 22.79s (Approximately 0.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 37
    paused: 0
    running: 21
    stopped: 16
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 49
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1602087680
  BuiltTime: Wed Oct  7 11:21:20 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-12.fc33.x86_64

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical machine

**Comment by mheon** [comment] 2020-11-18 21:22
Does the problem only happen with this one container, or can you reproduce with other containers?

**Comment by MrErr** [comment] 2020-11-18 21:26
Just this container. All other containers work fine.

**Comment by rhatdan** [comment] 2020-11-18 21:47
I have a feeling you need to remove all containers created with cgroups V1 to fix this problem.

**Comment by MrErr** [comment] 2020-11-18 22:32
> I have a feeling you need to remove all containers created with cgroups V1 to fix this problem.

That is a disruptive solution. There are twenty other containers running on this server. 
Can you please explain why you feel that removing other containers would be the solution? Also why wont just recreating this container be a solution? I could consider it even though it defeats the purpose of using containers for portability.

**Comment by mheon** [comment] 2020-11-18 22:37
Can you do a `podman inspect` of that container and check the OCIRuntime - I suspect that this container is still using runc on cgroups v2, from the error message. I'm a tad surprised it started at all, given that... @rhatdan @lsm5 How new is our runc on F33?

**Comment by MrErr** [comment] 2020-11-18 22:42
podman inspect nextcloud 
[
    {
        "Id": "9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2",
        "Created": "2020-07-23T20:46:50.372018954-05:00",
        "Path": "/usr/sbin/init",
        "Args": [
            "/usr/sbin/init"
        ],
        "State": {
            "OciVersion": "1.0.2-dev",
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 480051,
            "ConmonPid": 480017,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-11-18T13:42:21.192833524-06:00",
            "FinishedAt": "2020-11-18T13:42:00.369080378-06:00",
            "Healthcheck": {
                "Status": "",
                "FailingStreak": 0,
                "Log": null
            }
        },
        "Image": "04442dc21ed6e0be2fee2580973693a3f08c9c88ad934d2d2e032003f3e77caf",
        "ImageName": "localhost/nextcloud:18.0.0-1",
        "Rootfs": "",
        "Pod": "",
        "ResolvConfPath": "/var/run/containers/storage/overlay-containers/9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2/userdata/resolv.conf",
        "HostnamePath": "/var/run/containers/storage/overlay-containers/9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2/userdata/hostname",
        "HostsPath": "/var/run/containers/storage/overlay-containers/9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2/userdata/hosts",
        "StaticDir": "/var/lib/containers/storage/overlay-containers/9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2/userdata",
        "OCIConfigPath": "/var/lib/containers/storage/overlay-containers/9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2/userdata/config.json",
        "OCIRuntime": "runc",
        "LogPath": "/var/lib/containers/storage/overlay-containers/9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2/userdata/ctr.log",
        "LogTag": "",
        "ConmonPidFile": "/var/run/containers/storage/overlay-containers/9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2/userdata/conmon.pid",
        "Name": "nextcloud",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "EffectiveCaps": [
            "CAP_AUDIT_WRITE",
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FOWNER",
            "CAP_FSETID",
            "CAP_KILL",
            "CAP_MKNOD",
            "CAP_NET_BIND_SERVICE",
            "CAP_NET_RAW",
            "CAP_SETFCAP",
            "CAP_SETGID",
            "CAP_SETPCAP",
            "CAP_SETUID",
            "CAP_SYS_CHROOT"
        ],
        "BoundingCaps": [
            "CAP_AUDIT_WRITE",
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FOWNER",
            "CAP_FSETID",
            "CAP_KILL",
            "CAP_MKNOD",
            "CAP_NET_BIND_SERVICE",
            "CAP_NET_RAW",
            "CAP_SETFCAP",
            "CAP_SETGID",
            "CAP_SETPCAP",
            "CAP_SETUID",
            "CAP_SYS_CHROOT"
        ],
        "ExecIDs": [
            "2029f04c4c636a374eeb3a7d50c8c067dd2c95880d64d5768c3efb3c4de27c1a",
            "4fe1db7653044f4bdfc2a171a6d0fa7a7481b5dec4f6b95bc5b31b0c01bf3101",
            "5b328f98f5d91a2e6e121fc70521a357045b7c2643b3c6215b228e345d8cae24"
        ],
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/var/lib/containers/storage/overlay/12a06f33b145b375cafc988fb65630c944b5fac292f353e2d1d693bf3199d134/diff",
                "MergedDir": "/var/lib/containers/storage/overlay/ba9b71c4e583c7801c665313432d715e4bf4684dcc998c2e1bad520bcaad448b/merged",
                "UpperDir": "/var/lib/containers/storage/overlay/ba9b71c4e583c7801c665313432d715e4bf4684dcc998c2e1bad520bcaad448b/diff",
                "WorkDir": "/var/lib/containers/storage/overlay/ba9b71c4e583c7801c665313432d715e4bf4684dcc998c2e1bad520bcaad448b/work"
            }
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "nextcloud-backup",
                "Source": "/var/lib/containers/storage/volumes/nextcloud-backup/_data",
                "Destination": "/var/backup",
                "Driver": "local",
                "Mode": "",
                "Options": [
                    "nosuid",
                    "nodev",
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "nextcloud-db",
                "Source": "/var/lib/containers/storage/volumes/nextcloud-db/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "",
                "Options": [
                    "nosuid",
                    "nodev",
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "nextcloud-data",
                "Source": "/var/lib/containers/storage/volumes/nextcloud-data/_data",
                "Destination": "/var/lib/nextcloud/data",
                "Driver": "local",
                "Mode": "",
                "Options": [
                    "nosuid",
                    "nodev",
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "nextcloud-www",
                "Source": "/var/lib/containers/storage/volumes/nextcloud-www/_data",
                "Destination": "/var/www/html",
                "Driver": "local",
                "Mode": "",
                "Options": [
                    "nosuid",
                    "nodev",
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Dependencies": [],
        "NetworkSettings": {
            "EndpointID": "",
            "Gateway": "10.88.0.1",
            "IPAddress": "10.88.13.7",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "MacAddress": "0a:23:c1:5e:ac:03",
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/netns/cni-7b385a19-619a-702b-657b-45f8d644d942"
        },
        "ExitCommand": [
            "/usr/bin/podman",
            "--root",
            "/var/lib/containers/storage",
            "--runroot",
            "/var/run/containers/storage",
            "--log-level",
            "error",
            "--cgroup-manager",
            "systemd",
            "--tmpdir",
            "/var/run/libpod",
            "--runtime",
            "runc",
            "--storage-driver",
            "overlay",
            "--storage-opt",
            "overlay.mountopt=nodev,metacopy=on",
            "--storage-opt",
            "overlay.mountopt=nodev,metacopy=on",
            "--events-backend",
            "file",
            "container",
            "cleanup",
            "9b47d3d27e186652d4db7589ba303129e8776d2f1d905c4c2b5d1fb41361c0a2"
        ],
        "Namespace": "",
        "IsInfra": false,
        "Config": {
            "Hostname": "nextcloud",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm",
                "container=podman",
                "DISTTAG=f32container",
                "FGC=f32",
                "HOSTNAME=nextcloud",
                "HOME=/root"
            ],
            "Cmd": [
                "/usr/sbin/init"
            ],
            "Image": "localhost/nextcloud:18.0.0-1",
            "Volumes": null,
            "WorkingDir": "/temp",
            "Entrypoint": "",
            "OnBuild": null,
            "Labels": {
                "io.buildah.version": "1.15.0",
                "license": "MIT",
                "maintainer": "Sam Irlapati <irlapati@gmail.com>",
                "name": "fedora",
                "vendor": "Fedora Project",
                "version": "32"
            },
            "Annotations": {
                "io.container.manager": "libpod",
                "io.kubernetes.cri-o.Created": "2020-07-23T20:46:50.372018954-05:00",
                "io.kubernetes.cri-o.TTY": "false",
                "io.podman.annotations.autoremove": "FALSE",
                "io.podman.annotations.init": "FALSE",
                "io.podman.annotations.privileged": "FALSE",
                "io.podman.annotations.publish-all": "FALSE",
                "org.opencontainers.image.stopSignal": "37"
            },
            "StopSignal": 37,
            "CreateCommand": [
                "podman",
                "create",
                "--name",
                "nextcloud",
                "--hostname",
                "nextcloud",
                "--ip",
                "10.88.13.7",
                "--dns=10.88.13.3",
                "--mount",
                "type=volume,src=nextcloud-db,dst=/var/lib/mysql",
                "--mount",
                "type=volume,src=nextcloud-data,dst=/var/lib/nextcloud/data",
                "--mount",
                "type=volume,src=nextcloud-www,dst=/var/www/html",
                "--mount",
                "type=volume,src=nextcloud-backup,dst=/var/backup",
                "--restart",
                "always",
                "nextcloud:18.0.0-1"
            ],
            "SystemdMode": true,
            "Umask": "0000"
        },
        "HostConfig": {
            "Binds": [
                "nextcloud-backup:/var/backup:rw,rprivate,nosuid,nodev,rbind",
                "nextcloud-db:/var/lib/mysql:rw,rprivate,nosuid,nodev,rbind",
                "nextcloud-data:/var/lib/nextcloud/data:rw,rprivate,nosuid,nodev,rbind",
                "nextcloud-www:/var/www/html:rw,rprivate,nosuid,nodev,rbind"
            ],
            "CgroupMode": "host",
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "k8s-file",
                "Config": null
            },
            "NetworkMode": "bridge",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [],
            "Dns": [
                "10.88.13.3"
            ],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": [],
            "IpcMode": "private",
            "Cgroup": "",
            "Cgroups": "default",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "private",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [],
            "Tmpfs": {},
            "UTSMode": "private",
            "UsernsMode": "",
            "ShmSize": 65536000,
            "Runtime": "oci",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": 0,
            "OomKillDisable": false,
            "PidsLimit": 2048,
            "Ulimits": [
                {
                    "Name": "RLIMIT_NOFILE",
                    "Soft": 1048576,
                    "Hard": 1048576
                },
                {
                    "Name": "RLIMIT_NPROC",
                    "Soft": 4194304,
                    "Hard": 4194304
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "CgroupConf": null
        }
    }
]

**Comment by rhatdan** [comment] 2020-11-18 23:31
@MrErr If we can keep the containers, that is fine, I am just concerned about changing the cgroups from under the container and expecting it to still work.  But @mheon might be correct about the change from runc to crun.

**Comment by mheon** [comment] 2020-11-18 23:37
That container's still on `runc`. I'm feeling like this could be a runc + cgroups v2 bug given the relative immaturity of the support there.

**Comment by MrErr** [comment] 2020-11-18 23:54
I switched back to cgroups v1 and all containers seem to be working fine.

What should be the method to switch to cgroups v2?

**Comment by mheon** [comment] 2020-11-19 01:21
We added a `--runtime` flag to `podman system migrate` to force all containers to switch to a new OCI runtime - so, with all containers stopped on a fresh boot in v2 mode, run `podman system migrate --runtime crun` and then start the containers. They should be migrated to the crun runtime and work as expected.

**Comment by rhatdan** [comment] 2020-11-24 12:08
Since we have a solution, I am closing the issue.

**Closed by rhatdan** 2020-11-24 12:08 UTC
Labels: kind/bug
