### ISSUE TITLE
-v dir fails where the parent of directory is only accessible by subuid user

### ISSUE THREAD

**Issue by ibukanov** [containers/podman#12716] opened 2021-12-30 03:41 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When running as a user bind-mounting a host directory fails when the ownership of the parent directory is `root:some_subgid` and mode is `0750`. Here `root` is the root on the host and `some_subgid` is an id from /etc/subgid range for the user.  The user `root` can be replaced by any other user that is not mapped into the container user range.

**Steps to reproduce the issue:**

1. On a system without SELinux or with SELinux disable create a test directory structure on the host (100000 should be replaced by the first gid from /etc/subgid range): 
```
sudo sh -c 'mkdir -m 0750 /tmp/foo && chgrp 100000 /tmp/foo && mkdir -m 0755 /tmp/foo/bar'
```

2. Run the container with `/tmp/foo/bar` bind-mounted into it:
```
podman run -ti --rm -v /tmp/foo/bar:/bar  ubuntu:20.04
```
**Describe the results you received:**
```
Error: statfs /tmp/foo/bar: permission denied
```

**Describe the results you expected:**
Container runs and `/bar` inside it is accessible.

Note is is possible to access `/tmp/foo` from `podman unshare` and create bind-mounts from inside that command, but only after adding the group 1 corresponding to 100000 on the host in the above example to supplementary groups:
```
> podman unshare ls -al /tmp/foo
ls: cannot open directory '/tmp/foo': Permission denied

> podman unshare setpriv --groups 1 ls -al /tmp/foo
total 0
drwxr-x---  3 nobody bin     60 Dec 30 03:30 .
drwxrwxrwt 31 nobody nobody 760 Dec 30 03:30 ..
drwxr-xr-x  2 nobody nobody  40 Dec 30 03:30 bar

> podman unshare setpriv --groups 1 sh -c 'mkdir /tmp/bar2 && mount --bind /tmp/foo/bar /tmp/bar2 && ls -al /tmp/bar2'
total 0
drwxr-xr-x  2 nobody nobody  40 Dec 30 03:30 .
drwxrwxrwt 32 nobody nobody 780 Dec 30 04:22 ..
```

Based on the above observation that adding supplementary groups fixed the unshare access I tried to pass --group-add, but that has not helped:
```
> podman run -ti --rm -v /tmp/foo/bar:/bar --group-add 1 ubuntu:20.04
Error: statfs /tmp/foo/bar: permission denied
```

Can it be that --group-add applies too late?

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 22:45:07 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "35"
  eventLogger: journald
  hostname: rhea
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 131072
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 131072
  kernel: 5.15.11-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 25347825664
  memTotal: 33361461248
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 51539603456
  swapTotal: 51539603456
  uptime: 15h 53m 41.26s (Approximately 0.62 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/igor/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/igor/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/igor/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1638999907
  BuiltTime: Wed Dec  8 22:45:07 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.4-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

I suppose Fedora 35 includes the latest podman release.

**Comment by flouthoc** [comment] 2021-12-30 07:43
Hi @ibukanov thanks for creating the issue.

I am a bit confused and could be wrong here.

```console
sudo sh -c 'mkdir -m 0750 /tmp/foo && chgrp 100000 /tmp/foo && mkdir -m 0755 /tmp/foo/bar'
```
only changes group for `/tmp/foo`

Then shouldn't you try 
```console
podman run -ti --rm -v /tmp/foo:/bar  ubuntu:20.04
```
instead of 
```console
podman run -ti --rm -v /tmp/foo/bar:/bar  ubuntu:20.04
``` 
?

`/tmp/foo/bar` still has its group as `root` as far as i can see.

**Comment by rhatdan** [comment] 2021-12-30 12:16
Does https://www.redhat.com/sysadmin/supplemental-groups-podman-containers help you understand what is going on?

**Comment by ibukanov** [comment] 2021-12-30 12:27
@flouthoc The purpose is to mount /tmp/foo/bar into /bar in the container so /bar/somefile can be accessed by any user in the container who otherwise would not be able to access /tmp/foo/bar. This way the group on /tmp/foo serves as a protection point to restrict who can read its content. Then the bind mount allows to relax that for a particular container so any user in the container can access /tmp/foo/bar.

Note that `podman run --privileged` does not help either:
 ```
> podman run --privileged -ti --rm -v /tmp/foo/bar:/foo/bar --group-add 1 ubuntu:20.04
Error: statfs /tmp/foo/bar: permission denied
```

Yet if I bind-mount /tmp/foo into the container I can then bind-mount /tmp/foo/bar from the inside:
```
> podman run --privileged -ti --rm -v /tmp/foo:/foo --group-add 1 ubuntu:20.04
root@08896391b87d:/# mkdir /bar
root@08896391b87d:/# mount --bind /foo/bar /bar
root@08896391b87d:/# ls -al /bar
total 4
drwxr-xr-x 2 nobody nogroup   40 Dec 30 11:48 .
dr-xr-xr-x 1 root   root    4096 Dec 30 11:55 ..
```

So my theory is that --group-add sort-of acts too late. I suspect it should be done before the bind-mounts.

**Comment by giuseppe** [comment] 2021-12-30 13:03
does it work if you use `--group-add keep-groups`?

**Comment by ibukanov** [comment] 2021-12-30 13:32
@giuseppe keep-groups does not work since at the time of the invocation of the command the user does not have the group 100000 in the list of supplementary groups at the moment of the command invocation.

**Comment by ibukanov** [comment] 2021-12-30 13:48
Interesting that the bug does not happen when in the above example the group root is replaced by an arbitrary gid from subgid range (12345 in the example below) and even when that gid and the original user is not mapped into the container:
```
> podman unshare sh -c 'mkdir -m 0750 /tmp/foo && chown 12345:1 /tmp/foo && echo 123 > /tmp/foo/bar'
> ls -ldn /tmp/foo
drwxr-x--- 2 112344 100000 60 Dec 30 14:41 /tmp/foo
> podman run --privileged -ti --rm -v /tmp/foo/bar:/bar --uidmap 0:1:1000 --gidmap 0:1:1000 ubuntu:20.04
root@58ac72334a8e:/# ls -al /bar
-rw-r--r-- 1 nobody nogroup 4 Dec 30 13:41 /bar
root@58ac72334a8e:/# cat /bar
123
 ```

**Comment by ibukanov** [comment] 2021-12-30 14:20
It can be a misfeature of Linux kernel when the dac_override/dac_read_search capabilities in the user namespace does not really override all permissions check. In particular, when the file owner is outside the namespace but the group is in the caller still must have the necessary supplementary group to access the file: 
```
> podman unshare sh -c 'mkdir -m 0750 /tmp/foo && chown 12345:2 /tmp/foo && echo 123 > /tmp/foo/bar'
> podman run -ti --rm -v /tmp/foo:/foo --uidmap 0:1:1000 --gidmap 0:1:1000 ubuntu:20.04
root@bb0211aa7bcf:/# cat /foo/bar
cat: /foo/bar: Permission denied
root@bb0211aa7bcf:/# ls -ldn /foo
drwxr-x--- 2 65534 1 60 Dec 30 14:16 /foo
root@bb0211aa7bcf:/# setpriv --groups 1 cat /foo/bar
123
```

**Comment by giuseppe** [comment] 2021-12-30 15:27
I think that is expected otherwise you could gain privileges with directories you don't own

**Comment by ibukanov** [comment] 2021-12-30 16:15
@giuseppe As the example #issuecomment-1003008103 demonstrates, there is no protection as the desired result can be archived with an explicit bind-mount from the container. But it will be nice if it worked without starting a privileged container and manual dropping of privileges after the bind mount.

**Comment by giuseppe** [comment] 2022-01-03 09:32
@ibukanov I took another look at the issue.  It looks like CAP_DAC_OVERRIDE still requires the uid to be mapped inside the user namespace, even if one of the groups would allow access to the directory.  And I can reproduce the same behavior here:

```
$ sudo sh -c 'mkdir -m 0750 /tmp/foo && chgrp 100000 /tmp/foo && mkdir -m 0755 /tmp/foo/bar
$ podman unshare ls -l /tmp/foo
ls: cannot open directory '/tmp/foo/': Permission denied
```

I am closing the issue since there is nothing we can do in Podman (or the OCI runtime), as the check is in the kernel, but please feel free to comment further on the issue, if you think there is anything we can do.

**Closed by giuseppe** 2022-01-03 09:32 UTC
Labels: kind/bug
