### ISSUE TITLE
[api] fire an event when renaming a container

### ISSUE THREAD

**Issue by strzinek** [containers/podman#13919] opened 2022-04-19 19:02 UTC
/kind feature

**Description**

When calling API method /libpod/container/<id>/rename, no event gets fired afterwards. There is no event type for container renaming defined.

Having "rename" event fired would help in implementing renaming functionality in client UI such as cockpit-podman. Without such event, it is hard to detect that container has been renamed.

**Steps to reproduce the issue:**

1. start consuming events, e.g. with calling API /libpod/events GET
2. rename a container, e.g. with calling API /libpod/container/<id>/rename POST

**Describe the results you received:**
There is no event triggered and client consuming podman API does not get notified about new container name, getting into inconsistent state.

**Describe the results you expected:**
There should be some event triggered when renaming a container. New event type for could be named for example "rename".

**Output of `podman version`:**

```
3.4.4
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No. There is no "rename" event documented in latest version: https://github.com/containers/podman/blob/main/docs/source/markdown/podman-events.1.md

**Additional environment details:**
does not depend on environment. Tested on Fedora 35.

**Comment by Luap99** [comment] 2022-04-19 19:49
Duplicate of https://github.com/containers/podman/issues/13670

https://github.com/containers/podman/pull/13677 should be in podman 4.1

**Closed by Luap99** 2022-04-19 19:49 UTC
Labels: kind/feature
