### ISSUE TITLE
Podman crash all containers and pods since 4.8.2

### ISSUE THREAD

**Issue by Elrondo46** [containers/podman#21028] opened 2023-12-15 06:48 UTC
### Issue Description

Describe your issue

### Steps to reproduce the issue

Upgrade to 4.8.2

### Describe the results you received

Unable to start pods and containers in two diffenrent systems

### Describe the results you expected

Starting containers and pods

### podman info output

```yaml
starting container 9dfaaa5b033d02e152e965f3362e5d265923650d468fdc1786f84927a097e1f5: container create failed (no logs from conmon): conmon bytes "": readObjectStart: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...
starting container 4504edb9a4d5791f6714af39adb72a57506b089fe3dbf567d6e93bba6a2c1a22: a dependency of container 4504edb9a4d5791f6714af39adb72a57506b089fe3dbf567d6e93bba6a2c1a22 failed to start: container state improper
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Arch Linux ARM and AMD64

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment] 2023-12-15 09:32
Duplicate of #21024

**Closed by Luap99** 2023-12-15 09:32 UTC
Labels: kind/bug
