### ISSUE TITLE
Podman 4.2.1 from homebrew unable to run commands

### ISSUE THREAD

**Issue by nictownsend** [containers/podman#15912] opened 2022-09-23 10:46 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. podman machine init

2. podman machine start

3. podman `x` (e.g `podman ps`)

**Describe the results you received:**
`Error: unable to create connection. "" is not a supported schema`

**Describe the results you expected:**
Response from podman

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Error: unable to create connection. "" is not a supported schema
```

**Output of `podman info`:**

```
Error: unable to create connection. "" is not a supported schema
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
==> podman: stable 4.2.1 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/4.2.1 (178 files, 48.5MB) *
  Poured from bottle on 2022-09-23 at 11:30:50
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

![image](https://user-images.githubusercontent.com/47386186/191944690-c7edeb51-0099-420a-8222-572910e44484.png)

**Comment by ashley-cui** [comment] 2022-09-23 13:42
What's the output of `podman system connection list`?

**Comment by nictownsend** [comment] 2022-09-23 14:31
```
$ podman machine info
Host:
  Arch: amd64
  CurrentMachine: podman-machine-default
  DefaultMachine: podman-machine-default
  EventsDir: /var/folders/15/jl6qb71n52q0w8dx6tqhh_v80000gn/T/podman-run--1/podman
  MachineConfigDir: /Users/nic/.config/containers/podman/machine/qemu
  MachineImageDir: /Users/nic/.local/share/containers/podman/machine/qemu
  MachineState: Running
  NumberOfMachines: 1
  OS: darwin
  VMType: qemu
Version:
  APIVersion: 4.2.1
  Built: 1662491762
  BuiltTime: Tue Sep  6 20:16:02 2022
  GitCommit: ""
  GoVersion: go1.18.6
  Os: darwin
  OsArch: darwin/amd64
  Version: 4.2.1
```

**Comment by nictownsend** [comment] 2022-09-23 15:03
`podman --url ssh://core@localhost:50537/run/user/501/podman/podman.sock version`

`Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:50537/run/user/501/podman/podman.sock) failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain`

**Comment by nictownsend** [comment] 2022-09-23 15:04
```podman --url tcp://localhost:50537/run/user/501/podman/podman.sock version

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.2.1/libpod/_ping": net/http: HTTP/1.x transport connection broken: malformed HTTP response "SSH-2.0-OpenSSH_8.8"
```

**Comment by nictownsend** [comment] 2022-09-23 15:17
```
podman --log-level trace --url ssh://core@localhost:50537/run/user/501/podman/podman.sock info

INFO[0000] podman filtering at log level trace
DEBU[0000] Called info.PersistentPreRunE(podman --log-level trace --url ssh://core@localhost:50537/run/user/501/podman/podman.sock info)
DEBU[0000] Found SSH_AUTH_SOCK "/var/folders/15/jl6qb71n52q0w8dx6tqhh_v80000gn/T//ssh-1fQS4N1lIgER/agent.65922", ssh-agent signer(s) enabled
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:50537/run/user/501/podman/podman.sock) failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

**Comment by ashley-cui** [comment] 2022-09-27 13:57
Hmm. Have you tried rm-ing and re-initing the machine?

**Comment by nictownsend** [comment] 2022-09-27 16:13
```
$ podman machine stop podman-machine-default
$ podman machine rm podman-machine-default
$ podman machine init
$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users/nic:/Users/nic

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

	podman machine set --rootful

API forwarding listening on: /Users/nic/.local/share/containers/podman/machine/podman-machine-default/podman.sock

Another process was listening on the default Docker API socket address.
You can still connect Docker API clients by setting DOCKER_HOST using the
following command in your terminal session:

	export DOCKER_HOST='unix:///Users/nic/.local/share/containers/podman/machine/podman-machine-default/podman.sock'

Machine "podman-machine-default" started successfully
$ podman ps
Error: unable to create connection. "" is not a supported schema
```

**Comment by nictownsend** [comment] 2022-09-27 16:15
I stopped Docker desktop, then `rm` and `init` again:

```
$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users/nic:/Users/nic

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

	podman machine set --rootful

API forwarding listening on: /var/run/docker.sock
Docker API clients default to this address. You do not need to set DOCKER_HOST.

Machine "podman-machine-default" started successfully
$ podman ps
Error: unable to create connection. "" is not a supported schema
```

**Comment by ashley-cui** [comment] 2022-09-28 19:07
Interesting, does `podman --identity /Users/nic/.ssh/podman-machine-default` work?

**Comment by nictownsend** [comment] 2022-09-29 12:30
```$ podman --identity /Users/nic/.ssh/podman-machine-default ps
Error: unable to create connection. "" is not a supported schema```

**Comment by ashley-cui** [comment] 2022-09-29 13:26
Hmm, I'm unable to reproduce at all. This looks like either an issue with ssh, or something maybe a fresh install of podman would help.

**Comment by YevheniiPokhvalii** [comment] 2022-09-29 20:31
The latest `podman` from Linuxbrew even cannot be run on my system. Homebrew just does not install the executable in the bin directory. Restarting the terminal did not help.

**Comment by ashley-cui** [comment] 2022-09-30 15:03
Closing as it looks like this is resolved, the usage of CONTAINER_HOST is documented

**Closed by ashley-cui** 2022-09-30 15:03 UTC
Labels: kind/bug
