### ISSUE TITLE
Running multiple rootless containers in parallel with keep-ns sometimes fails with "runc: runc create failed: User namespaces enabled, but no user mapping found"

### ISSUE THREAD

**Issue by MarkRx** [containers/podman#20107] opened 2023-09-22 17:28 UTC
### Issue Description

Running multiple rootless podman containers in parallel with keep-id on sometimes results in some of the containers failing with the following error:

> {"cause":"OCI runtime error","message":"runc: runc create failed: User namespaces enabled, but no user mapping found.: OCI runtime error","response":500}

### Steps to reproduce the issue

Steps to reproduce the issue
1. Setup rootless podman
2. Run the following script

```bash
#!/bin/bash -e

DOCKER_HOST="/run/user/$(id -u)/podman/podman.sock"

run() {
    IMAGE_NAME=$1
    CONTAINER_NAME=$2
    CONTAINER_CONFIG="{\"Image\":\"$IMAGE_NAME\",\"Cmd\": [],\"AttachStdin\": false,\"AttachStdout\": true,\"AttachStderr\": true,\"Tty\": false}"
    
    curl -s -H "Content-Type: application/json" --unix-socket "$DOCKER_HOST" "http://localhost/containers/create?name=$CONTAINER_NAME" --data "$CONTAINER_CONFIG"

    curl -s -X POST --unix-socket "$DOCKER_HOST" "http://localhost/containers/$CONTAINER_NAME/start"

    podman inspect "$CONTAINER_NAME"
}

echo "Pulling all images"

podman pull ubuntu:20.04 &
podman pull ubuntu:22.04 &
podman pull ubuntu:23.04 &
podman pull ubuntu:23.10

echo "Running all images"

podman rm -f test0 test1 test2 test3

run ubuntu:20.04 test0 &
run ubuntu:22.04 test1 &
run ubuntu:23.04 test2 &
run ubuntu:23.10 test3

podman stop test0 test1 test2 test3
podman rm -f test0 test1 test2 test3

```

### Describe the results you received

Some containers randomly fail with the following error:

> {"cause":"OCI runtime error","message":"runc: runc create failed: User namespaces enabled, but no user mapping found.: OCI runtime error","response":500}

### Describe the results you expected

Containers can run in parallel

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.6-1.module+el8.8.0+18098+9b44df5f.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: 8c4ab5a095127ecc96ef8a9c885e0e1b14aeb11b'
  cpuUtilization:
    idlePercent: 94.67
    systemPercent: 2.38
    userPercent: 2.94
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.8"
  eventLogger: journald
  hostname: *****
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 20
      size: 1
    - container_id: 1
      host_id: 200000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 78572
      size: 1
    - container_id: 1
      host_id: 200000
      size: 100000
  kernel: 4.18.0-477.15.1.el8_8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 4045602816
  memTotal: 12266721280
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.module+el8.8.0+18060+3f21f2cc.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.19.4
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/78572/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.8.0+18060+3f21f2cc.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 3869638656
  swapTotal: 4194299904
  uptime: 346h 5m 6.00s (Approximately 14.42 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /var/appl/jenkins/home/myuser/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/appl/jenkins/home/myuser/.local/share/containers/storage
  graphRootAllocated: 107317563392
  graphRootUsed: 26649378816
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 35
  runRoot: /run/user/78572/containers
  transientStore: false
  volumePath: /var/appl/jenkins/home/myuser/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1686839996
  BuiltTime: Thu Jun 15 10:39:56 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

> $ cat /etc/redhat-release
> Red Hat Enterprise Linux release 8.8 (Ootpa)

> $ podman version
> Client:       Podman Engine
> Version:      4.4.1
> API Version:  4.4.1
> Go Version:   go1.19.6
> Built:        Thu Jun 15 10:39:56 2023
> OS/Arch:      linux/amd64

> $ cat /etc/subuid
> myuser:200000:100000

> $ cat /etc/subgid
> myuser:200000:65536

> $ cat /usr/share/containers/containers.conf | grep userns
> userns = "keep-id"
> #userns_size = 65536

### Additional information

The user podman socket is perpetually running setup using the following commands:

```
/usr/bin/loginctl enable-linger myuser
/usr/bin/systemctl --user enable --now podman.socket
/usr/bin/systemctl --user start podman.service
```

**Comment by rhatdan** [comment] 2023-10-23 17:11
Have you been able to nail this down with a repeater?

**Comment by MarkRx** [comment] 2023-11-06 03:32
For the most part. The script above almost always yields the runc error for me for at least one of the executions but usually 3 out of 4 of them. I'm not versed in what is going on behind the scenes but I suspect the combination of keep-id + namespace remapping that I am using has problems with running in parallel and the only time I don't see 3/4 errors is when of the images terminates in time proving room for another one to start.

**Comment by MarkRx** [comment] 2023-11-06 06:32
It seems that containers created in parallel using the create API do not properly setup GID/UID mappings. Either I'm missing some parameter when calling the API or the CLI behaves differently.

This works in parallel. Each created container has IDMappings properly filled out:

> podman create --name "$CONTAINER_NAME" "$IMAGE_NAME"

This does NOT work. Some of the containers are missing mappings data in the "IDMappings" field:

> curl -s -H "Content-Type: application/json" --unix-socket "$DOCKER_HOST" "http://localhost/containers/create?name=$CONTAINER_NAME" --data "$CONTAINER_CONFIG"

Working script using podman create:

```
#!/bin/bash -e

DOCKER_HOST="/run/user/$(id -u)/podman/podman.sock"

run() {
    IMAGE_NAME=$1
    CONTAINER_NAME=$2
    
    podman create --name "$CONTAINER_NAME" "$IMAGE_NAME"

    podman inspect "$CONTAINER_NAME"
}

echo "Pulling all images"

podman pull ubuntu:20.04 &
podman pull ubuntu:22.04 &
podman pull ubuntu:23.04 &
podman pull ubuntu:23.10

echo "Running all images"

podman rm -f test0 test1 test2 test3

run ubuntu:20.04 test0 &
run ubuntu:22.04 test1 &
run ubuntu:23.04 test2 &
run ubuntu:23.10 test3

podman stop test0 test1 test2 test3
podman rm -f test0 test1 test2 test3
```

**Comment by rhatdan** [comment] 2023-11-06 14:28
@giuseppe PTAL

**Comment by giuseppe** [comment] 2023-11-08 11:33
I let the reproducer script run for over an hour, but I am not able to reproduce locally on RHEL with Podman 4.4.1.

Can you reproduce this issue with the latest upstream release?

If it happens only RHEL then I suggest filing a bug using the official channels

**Comment by Luap99** [comment] 2024-06-15 18:57
Given there was never an answer closing

**Closed by Luap99** 2024-06-15 18:57 UTC
Labels: kind/bug
