### ISSUE TITLE
/etc/hosts has wrong content

### ISSUE THREAD

**Issue by mlegenovic** [containers/podman#11057] opened 2021-07-27 11:39 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If container is started with --network=host /etc/hosts maps hostname to wrong IP address (127.0.1.1).

**Steps to reproduce the issue:**

1. `podman run -it --rm --network host registry.fedoraproject.org/fedora:34 cat /etc/hosts`

**Describe the results you received:**
```
podman run -it --rm --network host registry.fedoraproject.org/fedora:34 cat /etc/hosts
127.0.0.1       localhost localhost.localdomain localhost4 localhost4.localdomain4
::1             localhost localhost.localdomain localhost6 localhost6.localdomain6
127.0.1.1 foo.mydomain.com foo.mydomain.com optimistic_newton
```

**Describe the results you expected:**
```
podman run -it --rm --network host registry.fedoraproject.org/fedora:34 cat /etc/hosts
127.0.0.1       localhost localhost.localdomain localhost4 localhost4.localdomain4
::1             localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.1.72 foo.mydomain.com foo.mydomain.com optimistic_newton
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.16.5
Built:        Fri Jul 16 22:33:32 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: foo.mydomain.com
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.4-200.fc34.x86_64
  linkmode: dynamic
  memFree: 29542653952
  memTotal: 33589002240
  ociRuntime:
    name: crun
    package: crun-0.20.1-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 21m 22.51s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/test/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.4
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.4
        using FUSE kernel interface version 7.31
  graphRoot: /home/test/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 10
  runRoot: /run/user/1000/containers
  volumePath: /home/test/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1626467612
  BuiltTime: Fri Jul 16 22:33:32 2021
  GitCommit: ""
  GoVersion: go1.16.5
  OsArch: linux/amd64
  Version: 3.2.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

```
Version:      3.3.0-dev
API Version:  3.3.0-dev
Go Version:   go1.16.5
Git Commit:   d7b2f03f8a5d0e3789ac185ea03989463168fb76
Built:        Tue Jul 27 13:20:19 2021
OS/Arch:      linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment] 2021-07-27 13:13
Why would you need `192.168.1.72` as entry in /etc/hosts? Is this your eth0 ip address? I do not think podman can figure out the correct ip. You could have several interfaces with several ip adresses. According to the `hosts` man page:
> 127.0.1.1 is often used for the FQDN of the machine

I close this as duplicate of https://github.com/containers/podman/issues/10319.

**Closed by Luap99** 2021-07-27 13:13 UTC
Labels: kind/bug

**Comment by mlegenovic** [comment] 2021-07-27 14:05
To be honest, I was sure there is an issue on this topic, but I couldn't find it.

My description what I expect is wrong, I'm not expecting any IP address in `/etc/hosts` file if `--network=host` is passed as argument, also not `127.0.1.1`. Problem with this entry is that a service as consequence starts listening on `127.0.1.1`, and this is wrong. In docker, if you run `hostname -i` in container which is started with `--network=host` you are getting the same IP address like on host machine. Podman returns now `127.0.1.1`, but this was not the case in older version (on RHEL 7).

The problem came to light when a developer in our company complained that he could no longer connect to a service from a remote machine (after upgrade to RHEL 8). `netstat -tulpen` showed where the problem is: `127.0.1.1:7105`, so you can access the service from local machine, but not from remote.
