### ISSUE TITLE
Digest could be invalid when using multiple registries

### ISSUE THREAD

**Issue by janisz** [containers/podman#15652] opened 2022-09-06 16:32 UTC
/kind bug

**Description**

Reported RepoDigests are invalid when pulling image from more than one registry.
podman does cross product of image names and all available digests which can lead to invalid repo digests as digest is registry specific.  

Similar to: https://github.com/cri-o/cri-o/issues/6208

**Steps to reproduce the issue:**

1. Pull the same image from two registries 

2. Inspect images and their repo digests

**Describe the results you received:**

```json
          "Id": "2b7d6430f78d432f89109b29d88d4c36c868cdbf15dc31d2132ceaa02b993763",
          "Digest": "sha256:f8fe7d0e6be40a7febbdec9aaf820eed7dbe62cb2afff00f67610666f7a9bd97",
          "RepoTags": [
               "docker.io/library/nginx:1.23",
               "image-registry.openshift-image-registry.svc:5000/rox-12400/nginx:1.23"
          ],
          "RepoDigests": [
               "docker.io/library/nginx@sha256:89020cd33be2767f3f894484b8dd77bc2e5a1ccc864350b92c53262213257dfc",
               "docker.io/library/nginx@sha256:b95a99feebf7797479e0c5eb5ec0bdfa5d9f504bc94da550c2f58e839ea6914f",
               "docker.io/library/nginx@sha256:f8fe7d0e6be40a7febbdec9aaf820eed7dbe62cb2afff00f67610666f7a9bd97",
               "image-registry.openshift-image-registry.svc:5000/rox-12400/nginx@sha256:89020cd33be2767f3f894484b8dd77bc2e5a1ccc864350b92c53262213257dfc",
               "image-registry.openshift-image-registry.svc:5000/rox-12400/nginx@sha256:b95a99feebf7797479e0c5eb5ec0bdfa5d9f504bc94da550c2f58e839ea6914f",
               "image-registry.openshift-image-registry.svc:5000/rox-12400/nginx@sha256:f8fe7d0e6be40a7febbdec9aaf820eed7dbe62cb2afff00f67610666f7a9bd97"
          ],
```

**Describe the results you expected:**

Docker output

```json
        "Id": "sha256:2b7d6430f78d432f89109b29d88d4c36c868cdbf15dc31d2132ceaa02b993763",
        "RepoTags": [
            "nginx:1.23",
            "quay.io/dhaus/repro:1.23"
        ],
        "RepoDigests": [
            "nginx@sha256:89020cd33be2767f3f894484b8dd77bc2e5a1ccc864350b92c53262213257dfc",
            "nginx@sha256:b95a99feebf7797479e0c5eb5ec0bdfa5d9f504bc94da550c2f58e839ea6914f",
            "quay.io/dhaus/repro@sha256:89020cd33be2767f3f894484b8dd77bc2e5a1ccc864350b92c53262213257dfc"
        ],
```

**Comment by rhatdan** [comment] 2022-09-06 19:36
@mtrmac @vrothberg @nalind PTAL

**Comment by mtrmac** [comment] 2022-09-06 19:41
https://github.com/containers/podman/issues/3761#issuecomment-520180830

**Comment by vrothberg** [comment] 2022-09-07 08:38
@mtrmac can we close this as a duplicate?

**Comment by mtrmac** [comment] 2022-09-07 16:32
Let’s. (I don’t have a strong opinion on which one to close — keeping the full context of #3761 seems valuable, OTOH this one is a concise description of a specific problem, without the debugging session, and without other people piling on with not-exactly-the-same issues.)

**Comment by vrothberg** [comment] 2022-09-08 08:07
Closing as a duplicate of https://github.com/containers/podman/issues/3761.

**Closed by vrothberg** 2022-09-08 08:07 UTC
Labels: kind/bug
