### ISSUE TITLE
Get: "Error: open `..`: No such file or directory: OCI not found" on start

### ISSUE THREAD

**Issue by novak-services** [containers/podman#9475] opened 2021-02-22 20:39 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am working with Ubuntu 18.04 and recently I got the newest podman version 3.0.1 on my system.

I am running a docker container which contains just an own build of postgres inside.

Since the update I get the error Message "Error: open `..`: No such file or directory: OCI not found" on start and the container won't run.

I start the container with this command line:

sudo podman run --rm -i -t postgres psql -h 192.168.1.20 -p 5433 -U odoo

**Steps to reproduce the issue:**

1. Have a docker container for Postgres

2. Start container with above command line as super user (sudo)

3. Get only the error message

**Describe the results you received:**

Error message:

"Error: open `..`: No such file or directory: OCI not found"

**Describe the results you expected:**

A running container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.26, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: journald
  hostname: theorem
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.0-65-generic
  linkmode: dynamic
  memFree: 9133068288
  memTotal: 16543039488
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17.7-5502-dirty
      commit: fd582c529489c0738e7039cbc036781d1d039014
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 34000072704
  swapTotal: 34000072704
  uptime: 12h 9m 15.06s (Approximately 0.50 days)
registries:
  search:
  - kurkuma.jnos.de:5050
  - registry.gitlab.com
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 29
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 100:3.0.1-2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

No, it is a physical notebook

**Comment by mheon** [comment] 2021-02-23 06:41
Feels likely this is a dupe of https://github.com/containers/podman/issues/9450 - please test with crun 0.18.

**Comment by giuseppe** [comment] 2021-02-25 14:07
yes that is a crun issue: #9450

**Closed by giuseppe** 2021-02-25 14:07 UTC
Labels: kind/bug

**Comment by novak-services** [comment] 2021-02-25 14:49
I had no time until today, to install an update, but got an automatic update of crun today, and it works again.

Thank you very much for the fast help!
