### ISSUE TITLE
Volumes as OCI artefacts

### ISSUE THREAD

**Issue by ericcurtin** [containers/podman#23956] opened 2024-09-15 12:53 UTC
### Feature request description

This is a feature I wish podman has had for a while:

https://kubernetes.io/blog/2024/08/16/kubernetes-1-31-image-volume-source/

build a directory structure as an OCI artefact, push to to an OCI registry so someone can download and bind mount somewhere.

Basically downloadable volumes from OCI registries.

**Comment by Luap99** [comment] 2024-09-16 08:55
Duplicate of #23775

**Closed by Luap99** 2024-09-16 08:55 UTC
Labels: kind/feature
