### ISSUE TITLE
File changes from macos host aren't notified to podman container

### ISSUE THREAD

**Issue by singh-lokendra** [containers/podman#22631] opened 2024-05-07 10:51 UTC
### Issue Description

File change events (macos) aren't propagated to podman container

### Steps to reproduce the issue

1. Create a podman container with shared directory using `podman run -it --rm -v $(pwd):/shared_directory alpine:latest`
2. Install inotify tools and add listener on **hello.txt** using
```bash
#!/bin/bash

apk add bash inotify-tools
bash
file="/shared_directory/hello.txt"

inotifywait -m -e modify "$file" |
while read -r directory event filename; do
    if [ "$event" = "MODIFY" ]; then
        echo "File $file Modified"
    fi
done
```
3. Update the file from hostos (macos) using `echo Hello >> hello.txt`

<img width="1440" alt="image" src="https://github.com/containers/podman/assets/37541956/71f4cbb6-5293-4e5f-a9d6-1e51593f7ee5">

### Describe the results you received

- Files changes aren't notified on podman container.

### Describe the results you expected

- Expected following output
```bash
File /shared_directory/hello.txt Modified
File /shared_directory/hello.txt Modified
```

 Replicated the same on docker, and file changes events are visible there

- Docker steps
```bash
docker run -it --rm -v $(pwd):/shared_directory alpine:latest

#!/bin/bash

apk add bash inotify-tools
bash
file="/shared_directory/hello.txt"

inotifywait -m -e modify "$file" |
while read -r directory event filename; do
    if [ "$event" = "MODIFY" ]; then
        echo "File $file Modified"
    fi
done


```
<img width="1434" alt="image" src="https://github.com/containers/podman/assets/37541956/e8527eaa-90cd-4785-8be6-560cede691a0">

### podman info output

```yaml
- `podman -v`
`podman version 5.0.2`


- OS: Macos
`sw_vers`

ProductName:		macOS
ProductVersion:		14.4.1
BuildVersion:		23E224
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

N/A

**Comment by Luap99** [comment] 2024-05-07 11:33
Duplicate of #22343 and https://github.com/containers/podman/discussions/19430

**Closed by Luap99** 2024-05-07 11:33 UTC
Labels: kind/bug
