### ISSUE TITLE
Digest does not match error when pulling image

### ISSUE THREAD

**Issue by adambkaplan** [containers/podman#7298] opened 2020-08-11 20:16 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Pulling the Fedora 32 toolbox image fails with:

```
$ Digest did not match, expected sha256:037a20ccce44f4a50af27f659c9572bba253abf1494f7e3f843d13c5c3910d63, got sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

**Steps to reproduce the issue:**

1. podman pull registry.fedoraproject.org/f32/fedora-toolbox:32

**Describe the results you received:**

```
Trying to pull registry.fedoraproject.org/f32/fedora-toolbox:32...
Getting image source signatures
Copying blob 037a20ccce44 [--------------------------------------] 0.0b / 67.6MiB
Copying blob 03c837e31708 done  
  Digest did not match, expected sha256:037a20ccce44f4a50af27f659c9572bba253abf1494f7e3f843d13c5c3910d63, got sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Error: error pulling image "registry.fedoraproject.org/f32/fedora-toolbox:32": unable to pull registry.fedoraproject.org/f32/fedora-toolbox:32: unable to pull image: Error reading blob sha256:037a20ccce44f4a50af27f659c9572bba253abf1494f7e3f843d13c5c3910d63: Digest did not match, expected sha256:037a20ccce44f4a50af27f659c9572bba253abf1494f7e3f843d13c5c3910d63, got sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Verbose pull here: https://paste.centos.org/view/faa7dcdc

**Describe the results you expected:**

Pull succeeds

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.14.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.14.2
  podmanVersion: 1.9.3
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.18-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 6e8799f576f11f902cd8a8d8b45b2b2caf636a85'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.19-300.fc32.x86_64
  memFree: 385757184
  memTotal: 16653860864
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.1-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.1
      commit: bbf27c5acd4356edb97fa639b4e15e0cd56a39d5
      libslirp: 4.2.0
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 8376807424
  swapTotal: 8396992512
  uptime: 29h 16m 5.99s (Approximately 1.21 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /var/home/adkaplan/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.1-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/adkaplan/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  volumePath: /var/home/adkaplan/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.3-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 32 Silverblue

**Comment by mheon** [comment] 2020-08-11 20:23
@mtrmac PTAL. This reproduces on my machine. I suspect the registry is serving a malformed blob, but presumably Docker does similar validation to what we do and it succeeds.

**Comment by mheon** [comment] 2020-08-11 20:25
Pulling https://registry.fedoraproject.org/v2/f32/fedora-toolbox/blobs/sha256:03c837e31708e15035b6c6f9a7a4b78b64f6bc10e6daec01684c077655becf95 down does give me a file with a SHA256 of 03c837e31708e15035b6c6f9a7a4b78b64f6bc10e6daec01684c077655becf95 so the registry seems sane. Not sure what's going on here.

**Comment by mtrmac** [comment] 2020-08-11 20:40
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 is a sha256sum of an empty file; is it possible it was a transient error? Right now, `skopeo --override-os linux --insecure-policy copy --debug 'docker://registry.fedoraproject.org/f32/fedora-toolbox:32' dir:t` works for me.

@mheon Does Skopeo ^^^ work for you?

**Comment by mheon** [comment] 2020-08-11 20:51
@mtrmac No - fails on two separate machines, one on the RH VPN and one not.

Seems likely that this is registry trouble given what we're seeing here, though. `wget` retrieves the correct blob, but Skopeo (and anything else using c/image) does not.

**Comment by mtrmac** [comment] 2020-08-11 20:55
Or maybe a Go version difference? For me, both HEAD Skopeo with `go version go1.13.10 darwin/amd64` and a very old Skopeo build with `go version go1.10.8 linux/amd64` works.

**Comment by mheon** [comment] 2020-08-11 21:02
@mtrmac I'm talking with the Fedora admins now, and it sounds like the path we're being handed by the registry is a redirect - any chance we don't handle that properly?

**Comment by mheon** [comment] 2020-08-11 21:03
From `wget`:
```
HTTP request sent, awaiting response... 302 Found
Location: https://cdn.registry.fedoraproject.org/v2/f32/fedora-toolbox/blobs/sha256:03c837e31708e15035b6c6f9a7a4b78b64f6bc10e6daec01684c077655becf95 [following]
```

**Comment by mtrmac** [comment] 2020-08-11 21:06
There’s a known behavior difference from Docker (~by definition a bug) in handling _credentials_ when following redirects, but redirects should be followed in principle.

**Comment by mheon** [comment] 2020-08-11 21:12
@mtrmac Tracing further, it appears that the Fedora CDN may have cached bad values for certain files - likely explains the difference in the results we were seeing as we were hitting different CDN nodes. Talking with the Fedora admins to have the cache invalidated now.

**Comment by mheon** [comment] 2020-08-11 23:04
Going to close this - cache invalidation seems to have resolved matters.

**Closed by mheon** 2020-08-11 23:04 UTC
Labels: kind/bug
