### ISSUE TITLE
`podman port --all` does not print port mappings of pod

### ISSUE THREAD

**Issue by Panke** [containers/podman#10898] opened 2021-07-10 16:58 UTC
/kind bug

**Description**

`podman port --all` does not show port bindings of pod

```sh
~ podman pod create --name portissue -p3333 
c7e9f572a4d8dc0ea14b672ff5eae6ae2b679362706f80fd687e2e74bdc04df6
~ podman port --all
~ 
```

**Steps to reproduce the issue:**

1. Create a Pod with a port mapping

2. Show all mapped ports with `podman pod --all`

`podman pod --all` does not show anything, but `podman inspect` does show the mapping
```
[
    {
        "Id": "06eed290bb7707029785e3153220634bb2161db14769d1b8820053c239e04cd6",
        "Created": "2021-07-10T18:51:18.205455795+02:00",
        "Path": "/pause",
        "Args": [
            "/pause"
        ],
        "State": {
            "OciVersion": "1.0.2-dev",
            "Status": "configured",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Healthcheck": {
                "Status": "",
                "FailingStreak": 0,
                "Log": null
            }
        },
        "Image": "ed210e3e4a5bae1237f1bb44d72a05a2f1e5c6bfe7a7e73da179e2534269c459",
        "ImageName": "k8s.gcr.io/pause:3.5",
        "Rootfs": "",
        "Pod": "c7e9f572a4d8dc0ea14b672ff5eae6ae2b679362706f80fd687e2e74bdc04df6",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "StaticDir": "/home/me/.local/share/containers/storage/overlay-containers/06eed290bb7707029785e3153220634bb2161db14769d1b8820053c239e04cd6/userdata",
        "OCIRuntime": "crun",
        "ConmonPidFile": "/run/user/1000/containers/overlay-containers/06eed290bb7707029785e3153220634bb2161db14769d1b8820053c239e04cd6/userdata/conmon.pid",
        "PidFile": "/run/user/1000/containers/overlay-containers/06eed290bb7707029785e3153220634bb2161db14769d1b8820053c239e04cd6/userdata/pidfile",
        "Name": "c7e9f572a4d8-infra",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "EffectiveCaps": [
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FSETID",
            "CAP_FOWNER",
            "CAP_MKNOD",
            "CAP_NET_RAW",
            "CAP_SETGID",
            "CAP_SETUID",
            "CAP_SETFCAP",
            "CAP_SETPCAP",
            "CAP_NET_BIND_SERVICE",
            "CAP_SYS_CHROOT",
            "CAP_KILL",
            "CAP_AUDIT_WRITE"
        ],
        "BoundingCaps": [
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FSETID",
            "CAP_FOWNER",
            "CAP_MKNOD",
            "CAP_NET_RAW",
            "CAP_SETGID",
            "CAP_SETUID",
            "CAP_SETFCAP",
            "CAP_SETPCAP",
            "CAP_NET_BIND_SERVICE",
            "CAP_SYS_CHROOT",
            "CAP_KILL",
            "CAP_AUDIT_WRITE"
        ],
        "ExecIDs": [],
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/home/me/.local/share/containers/storage/overlay/dee215ffc666313e1381d3e6e4299a4455503735b8df31c3fa161d2df50860a8/diff",
                "UpperDir": "/home/me/.local/share/containers/storage/overlay/e4185dcb63b3aa14e9a0b1fe4f031b828709587065b992fc4f13bd2c79349411/diff",
                "WorkDir": "/home/me/.local/share/containers/storage/overlay/e4185dcb63b3aa14e9a0b1fe4f031b828709587065b992fc4f13bd2c79349411/work"
            }
        },
        "Mounts": [],
        "Dependencies": [],
        "NetworkSettings": {
            "EndpointID": "",
            "Gateway": "",
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "MacAddress": "",
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3333/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "41353"
                    }
                ]
            },
            "SandboxKey": ""
        },
        "ExitCommand": [
            "/usr/bin/podman",
            "--root",
            "/home/me/.local/share/containers/storage",
            "--runroot",
            "/run/user/1000/containers",
            "--log-level",
            "warning",
            "--cgroup-manager",
            "systemd",
            "--tmpdir",
            "/run/user/1000/libpod/tmp",
            "--runtime",
            "crun",
            "--storage-driver",
            "overlay",
            "--events-backend",
            "journald",
            "container",
            "cleanup",
            "06eed290bb7707029785e3153220634bb2161db14769d1b8820053c239e04cd6"
        ],
        "Namespace": "",
        "IsInfra": true,
        "Config": {
            "Hostname": "portissue",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm"
            ],
            "Cmd": null,
            "Image": "k8s.gcr.io/pause:3.5",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": "/pause",
            "OnBuild": null,
            "Labels": null,
            "Annotations": null,
            "StopSignal": 15,
            "Umask": "0000",
            "Timeout": 0,
            "StopTimeout": 10
        },
        "HostConfig": {
            "Binds": [],
            "CgroupManager": "systemd",
            "CgroupMode": "host",
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "",
                "Config": null,
                "Path": "/home/me/.local/share/containers/storage/overlay-containers/06eed290bb7707029785e3153220634bb2161db14769d1b8820053c239e04cd6/userdata/ctr.log",
                "Tag": "",
                "Size": "0B"
            },
            "NetworkMode": "slirp4netns",
            "PortBindings": {
                "3333/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "41353"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": [],
            "IpcMode": "private",
            "Cgroup": "",
            "Cgroups": "default",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "private",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": true,
            "SecurityOpt": [],
            "Tmpfs": {},
            "UTSMode": "private",
            "UsernsMode": "",
            "ShmSize": 65536000,
            "Runtime": "oci",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "user.slice/user-libpod_pod_c7e9f572a4d8dc0ea14b672ff5eae6ae2b679362706f80fd687e2e74bdc04df6.slice",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": 0,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": [
                {
                    "Name": "RLIMIT_NOFILE",
                    "Soft": 1024,
                    "Hard": 1024
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "CgroupConf": null
        }
    }
]

```

**Describe the results you received:**
No port mappings returned by `podman port`

**Describe the results you expected:**
The mapping for the port 3333 of c7e9f572a4d8-infra

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.16.5
Git Commit:   d577c44e359f9f8284b38cf984f939b3020badc3
Built:        Mon Jun 28 22:13:34 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon ist in conmon 1:2.0.29-1 enthalten
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 7e6de6678f6ed8a18661e1d5721b81ccee293b9b'
  cpus: 12
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: akela
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.12.14-arch1-1
  linkmode: dynamic
  memFree: 11616665600
  memTotal: 33678327808
  ociRuntime:
    name: crun
    package: /usr/bin/crun ist in crun 0.20.1-1 enthalten
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 38271d1c8d9641a2cdc70acfa3dcb6996d124b3d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns ist in slirp4netns 1.1.11-1 enthalten
    version: |-
      slirp4netns version 1.1.11
      commit: 368e69ccc074628d17a9bb9a35b8f4b9f74db4c6
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 9h 47m 1.87s (Approximately 0.38 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/me/config/gitconfig/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/me/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 67
  runRoot: /run/user/1000/containers
  volumePath: /home/me/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.2
  Built: 1624911214
  BuiltTime: Mon Jun 28 22:13:34 2021
  GitCommit: d577c44e359f9f8284b38cf984f939b3020badc3
  GoVersion: go1.16.5
  OsArch: linux/amd64
  Version: 3.2.2


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Current ArchLinux
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Normal linux box, non-root.

**Comment by cdoern** [comment] 2021-07-12 13:12
@mheon have a theory for this one, could be because infra is where the port assignments are, but infra is not running so `runtime.state.AllContainers` won't return it?

**Comment by mheon** [comment] 2021-07-12 13:17
This seems like NOTABUG to me? The description of `port --all` says "all running containers". There are no running containers in the pod. If there were, it would be included in the results?

**Comment by cdoern** [comment] 2021-07-12 13:21
Good point @mheon, but the port mappings of a pod are assigned to infra so should there be a way with `port` to output those as well?

**Comment by mheon** [comment] 2021-07-12 13:25
Why? `port --all` will pick up the infra container. What's more, because of the way port sharing, we will also show that every container in the pod has these ports. Example, for two containers in a port that forwards ports 8080 and 8090:
```
mheon@Marlborough code/podman (main) $ podman port --all
c4103a0819ef	80/tcp -> 0.0.0.0:8080
c4103a0819ef	8090/tcp -> 0.0.0.0:8090
d471f08def0f	80/tcp -> 0.0.0.0:8080
d471f08def0f	8090/tcp -> 0.0.0.0:8090
```

We're showing both containers in the pod as owning every port forwarded. This seems more than sufficient.

**Comment by cdoern** [comment] 2021-07-12 13:27
Ahhhh okay, I didn't see that the containers in the pod pick up the port assignments like this I just tried `--port all` before adding a container, this looks good to me as is.

**Comment by cdoern** [comment] 2021-07-12 13:29
@Panke seems like you need to add a container to the pod before `podman port --all` will display anything as infra is a non-running container. Closing this as it is not a bug, feel free to re-open with any questions about why this functions the way it does.

**Closed by cdoern** 2021-07-12 13:29 UTC
Labels: kind/bug

**Comment by mheon** [comment] 2021-07-12 13:32
You don't need to add a container - I expect that a `podman pod start` on a fresh pod would also do the job.

**Comment by Panke** [comment] 2021-07-14 18:09
> You don't need to add a container - I expect that a podman pod start on a fresh pod would also do the job.
It doesn't. `podman port --all` does not show the port mapping after `podman pod start` even though the infra container is in state `Running` and has `IsRunning` as true. 

It's not an important thing, but violates the POLA principle, IMO. I will just work around it.

**Comment by rhatdan** [comment] 2021-07-15 00:30
Does `podman port --all` show ports for non running containers?

**Comment by mheon** [comment] 2021-07-15 12:51
It does not.

**Comment by rhatdan** [comment] 2021-07-15 13:07
Then I do not see this as a POLA
