### ISSUE TITLE
Panic when trying to run or start a container

### ISSUE THREAD

**Issue by mmohaveri** [containers/podman#13989] opened 2022-04-24 10:44 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Unable to start containers (even the ones that were working previously) after upgrading from version `3.4.6` to `3.4.7`.

**Steps to reproduce the issue:**

1. In Debain Sid upgrade podman to its latest version (at the time of writing this issue version `3.4.7+ds1-2`).
2. Try to start any container, e.g: `podman run envoyproxy/envoy:v1.20.0` or `podman start <name-of-an-already-exising-but-stopped-container>`

**Describe the results you received:**

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/opencontainers/runtime-tools/generate.(*Generator).addEnv(...)
	github.com/opencontainers/runtime-tools/generate/generate.go:532
github.com/opencontainers/runtime-tools/generate.(*Generator).AddProcessEnv(0xc00056f0d8, {0x17edeb7, 0x8}, {0xc0001d5c40, 0xc})
	github.com/opencontainers/runtime-tools/generate/generate.go:508 +0x2ea
github.com/containers/podman/libpod.(*Container).generateSpec(0xc0001440b0, {0x1ad3150, 0xc000630ab0})
	github.com/containers/podman/libpod/container_internal_linux.go:648 +0x2965
github.com/containers/podman/libpod.(*Container).init(0xc0001440b0, {0x1ad3150, 0xc000630ab0}, 0x0)
	github.com/containers/podman/libpod/container_internal.go:1098 +0x8e
github.com/containers/podman/libpod.(*Container).prepareToStart(0xc0001440b0, {0x1ad3150, 0xc000630ab0}, 0xc0?)
	github.com/containers/podman/libpod/container_internal.go:875 +0x345
github.com/containers/podman/libpod.(*Container).Start(0xc0001440b0, {0x1ad3150?, 0xc000630ab0?}, 0x0?)
	github.com/containers/podman/libpod/container_api.go:91 +0xde
github.com/containers/podman/pkg/domain/infra/abi.(*ContainerEngine).ContainerStart(0xc000010038, {0x1ad3150, 0xc000630ab0}, {0xc000640a00?, 0x7?, 0xc00056fd30?}, {0xc0002a65d0, 0x0, 0x0, {0x17f5ed4, ...}, ...})
	github.com/containers/podman/pkg/domain/infra/abi/containers.go:856 +0x36b
github.com/containers/podman/cmd/podman/containers.start(0x2504e20?, {0xc000640a00, 0x2, 0x2})
	github.com/containers/podman/cmd/podman/containers/start.go:136 +0x1f4
github.com/spf13/cobra.(*Command).execute(0x2504e20, {0xc00003c0e0, 0x2, 0x2})
	github.com/spf13/cobra/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x251b3a0)
	github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra/command.go:895
main.Execute()
	github.com/containers/podman/cmd/podman/root.go:91 +0xc5
main.main()
	github.com/containers/podman/cmd/podman/main.go:39 +0x74
```

**Describe the results you expected:**

I expected for the container to start.

**Additional information you deem important (e.g. issue happens only occasionally):**

As I said earlier, I'm using Debian Sid. Issue started when I upgraded from `3.4.6+ds1-1` to `3.4.7+ds1-2`. I downgraded to `3.4.6+ds1-1` by adding Debian Testing source and the issue was fixed.

**Output of `podman version`:**

```
podman version 3.4.7
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 8
  distribution:
    distribution: debian
    version: unknown
  eventLogger: journald
  hostname: Mahdi-ThinkPad
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.17.0-1-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 1806970880
  memTotal: 16417386496
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 10228842496
  swapTotal: 10242486272
  uptime: 42h 33m 38.5s (Approximately 1.75 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/mahdi/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/mahdi/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/mahdi/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.7
  Built: 0
  BuiltTime: Thu Jan  1 03:30:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  OsArch: linux/amd64
  Version: 3.4.7
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unstable,now 3.4.7+ds1-2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment] 2022-04-24 13:14
Duplicate of #13968

**Closed** 2022-04-25 07:11 UTC
Labels: kind/bug
