### ISSUE TITLE
Podman panic err, when trying to show the podman disk usage

### ISSUE THREAD

**Issue by kumadee** [containers/podman#22438] opened 2024-04-19 10:06 UTC
### Issue Description

Podman fails with panic error when I try to view the disk usage on the VM. It fails only one a specific instance which has a lot of volumes.
```bash
$ podman volume ls | wc -l
98
```

Please note that I am still able to run containers normally on the VM.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Executed `podman system df`

### Describe the results you received

$ podman system df
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5602b906dfa2]

goroutine 1 [running]:
panic({0x5602b9cf9ae0?, 0x5602baaf88a0?})
	/usr/lib/golang/src/runtime/panic.go:1017 +0x3ac fp=0xc0012394f8 sp=0xc001239448 pc=0x5602b848f04c
runtime.panicmem(...)
	/usr/lib/golang/src/runtime/panic.go:261
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:861 +0x378 fp=0xc001239558 sp=0xc0012394f8 pc=0x5602b84a6a78
github.com/containers/common/libimage.(*Runtime).DiskUsage(0xc000a598c8?, {0x5602b9f5b508, 0xc000596390})
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/containers/common/libimage/disk_usage.go:68 +0x542 fp=0xc0012397f8 sp=0xc001239558 pc=0x5602b906dfa2
github.com/containers/podman/v4/pkg/domain/infra/abi.(*ContainerEngine).SystemDf(0xc000600018, {0x5602b9f5b508?, 0xc000596390?}, {{0x0?, 0x0?}, 0x0?})
	/builddir/build/BUILD/podman-4.9.4/pkg/domain/infra/abi/system.go:261 +0x47 fp=0xc001239b50 sp=0xc0012397f8 pc=0x5602b94d2be7
github.com/containers/podman/v4/cmd/podman/system.df(0x5602bab2fae0?, {0x5602bac308e0?, 0x0?, 0x0?})
	/builddir/build/BUILD/podman-4.9.4/cmd/podman/system/df.go:55 +0x6d fp=0xc001239ba8 sp=0xc001239b50 pc=0x5602b96c9e6d
github.com/spf13/cobra.(*Command).execute(0x5602bab2fae0, {0xc0000402f0, 0x0, 0x0})
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/spf13/cobra/command.go:983 +0xabc fp=0xc001239d48 sp=0xc001239ba8 pc=0x5602b89e921c
github.com/spf13/cobra.(*Command).ExecuteC(0x5602bab18dc0)
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff fp=0xc001239e20 sp=0xc001239d48 pc=0x5602b89e9adf
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/spf13/cobra/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/spf13/cobra/command.go:1032
main.Execute()
	/builddir/build/BUILD/podman-4.9.4/cmd/podman/root.go:115 +0xb8 fp=0xc001239ea8 sp=0xc001239e20 pc=0x5602b96e57d8
main.main()
	/builddir/build/BUILD/podman-4.9.4/cmd/podman/main.go:60 +0x467 fp=0xc001239f40 sp=0xc001239ea8 pc=0x5602b96e4f07
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:267 +0x2d2 fp=0xc001239fe0 sp=0xc001239f40 pc=0x5602b8491fb2
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc001239fe8 sp=0xc001239fe0 pc=0x5602b84c61e1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000072fa8 sp=0xc000072f88 pc=0x5602b849242e
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:404
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:322 +0xb8 fp=0xc000072fe0 sp=0xc000072fa8 pc=0x5602b8492298
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x5602b84c61e1
created by runtime.init.7 in goroutine 1
	/usr/lib/golang/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000073778 sp=0xc000073758 pc=0x5602b849242e
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/usr/lib/golang/src/runtime/mgcsweep.go:321 +0xdf fp=0xc0000737c8 sp=0xc000073778 pc=0x5602b847c7ff
runtime.gcenable.func1()
	/usr/lib/golang/src/runtime/mgc.go:200 +0x25 fp=0xc0000737e0 sp=0xc0000737c8 pc=0x5602b8471925
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000737e8 sp=0xc0000737e0 pc=0x5602b84c61e1
created by runtime.gcenable in goroutine 1
	/usr/lib/golang/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x5602babf9980?, 0x3b9aca00?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000073f70 sp=0xc000073f50 pc=0x5602b849242e
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x5602babf9980)
	/usr/lib/golang/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000073fa0 sp=0xc000073f70 pc=0x5602b847a089
runtime.bgscavenge(0x0?)
	/usr/lib/golang/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc000073fc8 sp=0xc000073fa0 pc=0x5602b847a639
runtime.gcenable.func2()
	/usr/lib/golang/src/runtime/mgc.go:201 +0x25 fp=0xc000073fe0 sp=0xc000073fc8 pc=0x5602b84718c5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x5602b84c61e1
created by runtime.gcenable in goroutine 1
	/usr/lib/golang/src/runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0x198?, 0x5602b9f2b180?, 0x1?, 0x35?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000072620 sp=0xc000072600 pc=0x5602b849242e
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:193 +0x107 fp=0xc0000727e0 sp=0xc000072620 pc=0x5602b84708c7
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000727e8 sp=0xc0000727e0 pc=0x5602b84c61e1
created by runtime.createfing in goroutine 1
	/usr/lib/golang/src/runtime/mfinal.go:163 +0x3d

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x5602bac33300?, 0x1?, 0xd6?, 0x8?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000074750 sp=0xc000074730 pc=0x5602b849242e
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000747e0 sp=0xc000074750 pc=0x5602b84734e5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x5602b84c61e1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/golang/src/runtime/mgc.go:1219 +0x1c

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x5602bac33300?, 0x1?, 0x90?, 0xd6?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc00006e750 sp=0xc00006e730 pc=0x5602b849242e
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1295 +0xe5 fp=0xc00006e7e0 sp=0xc00006e750 pc=0x5602b84734e5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006e7e8 sp=0xc00006e7e0 pc=0x5602b84c61e1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/golang/src/runtime/mgc.go:1219 +0x1c

goroutine 34 [GC worker (idle)]:
runtime.gopark(0xa5a7c04658b?, 0x3?, 0x69?, 0x4d?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000588750 sp=0xc000588730 pc=0x5602b849242e
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1295 +0xe5 fp=0xc0005887e0 sp=0xc000588750 pc=0x5602b84734e5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0005887e8 sp=0xc0005887e0 pc=0x5602b84c61e1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/golang/src/runtime/mgc.go:1219 +0x1c

goroutine 7 [GC worker (idle)]:
runtime.gopark(0xa5a7c04cf97?, 0x3?, 0x96?, 0x55?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000074f50 sp=0xc000074f30 pc=0x5602b849242e
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1295 +0xe5 fp=0xc000074fe0 sp=0xc000074f50 pc=0x5602b84734e5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000074fe8 sp=0xc000074fe0 pc=0x5602b84c61e1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/golang/src/runtime/mgc.go:1219 +0x1c

goroutine 19 [select, locked to thread]:
runtime.gopark(0xc00006f7a8?, 0x2?, 0x0?, 0x0?, 0xc00006f7a4?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc00006f638 sp=0xc00006f618 pc=0x5602b849242e
runtime.selectgo(0xc00006f7a8, 0xc00006f7a0, 0x0?, 0x0, 0x0?, 0x1)
	/usr/lib/golang/src/runtime/select.go:327 +0x725 fp=0xc00006f758 sp=0xc00006f638 pc=0x5602b84a2be5
runtime.ensureSigM.func1()
	/usr/lib/golang/src/runtime/signal_unix.go:1014 +0x1a5 fp=0xc00006f7e0 sp=0xc00006f758 pc=0x5602b84bc7e5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006f7e8 sp=0xc00006f7e0 pc=0x5602b84c61e1
created by runtime.ensureSigM in goroutine 1
	/usr/lib/golang/src/runtime/signal_unix.go:997 +0xc8

goroutine 20 [syscall]:
runtime.notetsleepg(0x0?, 0x0?)
	/usr/lib/golang/src/runtime/lock_futex.go:236 +0x29 fp=0xc00006ffa0 sp=0xc00006ff68 pc=0x5602b8463669
os/signal.signal_recv()
	/usr/lib/golang/src/runtime/sigqueue.go:152 +0x29 fp=0xc00006ffc0 sp=0xc00006ffa0 pc=0x5602b84c2689
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x13 fp=0xc00006ffe0 sp=0xc00006ffc0 pc=0x5602b859c933
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00006ffe8 sp=0xc00006ffe0 pc=0x5602b84c61e1
created by os/signal.Notify.func1.1 in goroutine 1
	/usr/lib/golang/src/os/signal/signal.go:151 +0x1f

goroutine 35 [select]:
runtime.gopark(0xc000588fb0?, 0x2?, 0x0?, 0x0?, 0xc000588eac?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc00008bd38 sp=0xc00008bd18 pc=0x5602b849242e
runtime.selectgo(0xc00008bfb0, 0xc000588ea8, 0x0?, 0x0, 0x0?, 0x1)
	/usr/lib/golang/src/runtime/select.go:327 +0x725 fp=0xc00008be58 sp=0xc00008bd38 pc=0x5602b84a2be5
github.com/containers/podman/v4/libpod/shutdown.Start.func1()
	/builddir/build/BUILD/podman-4.9.4/libpod/shutdown/handler.go:48 +0x87 fp=0xc00008bfe0 sp=0xc00008be58 pc=0x5602b92b4327
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00008bfe8 sp=0xc00008bfe0 pc=0x5602b84c61e1
created by github.com/containers/podman/v4/libpod/shutdown.Start in goroutine 1
	/builddir/build/BUILD/podman-4.9.4/libpod/shutdown/handler.go:47 +0xf1

goroutine 36 [chan receive]:
runtime.gopark(0x5602b858f305?, 0x0?, 0xa8?, 0x97?, 0x5602b858f279?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000589718 sp=0xc0005896f8 pc=0x5602b849242e
runtime.chanrecv(0xc000058420, 0x0, 0x1)
	/usr/lib/golang/src/runtime/chan.go:583 +0x3cd fp=0xc000589790 sp=0xc000589718 pc=0x5602b845df4d
runtime.chanrecv1(0xc000598000?, 0x0?)
	/usr/lib/golang/src/runtime/chan.go:442 +0x12 fp=0xc0005897b8 sp=0xc000589790 pc=0x5602b845db52
github.com/godbus/dbus/v5.newConn.func1()
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/godbus/dbus/v5/conn.go:302 +0x2c fp=0xc0005897e0 sp=0xc0005897b8 pc=0x5602b8cdca6c
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0005897e8 sp=0xc0005897e0 pc=0x5602b84c61e1
created by github.com/godbus/dbus/v5.newConn in goroutine 1
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/godbus/dbus/v5/conn.go:301 +0x4f6

goroutine 21 [IO wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000129a48 sp=0xc000129a28 pc=0x5602b849242e
runtime.netpollblock(0x0?, 0xb845b086?, 0x2?)
	/usr/lib/golang/src/runtime/netpoll.go:564 +0xf7 fp=0xc000129a80 sp=0xc000129a48 pc=0x5602b848ad17
internal/poll.runtime_pollWait(0x7fd1ee057eb0, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:343 +0x85 fp=0xc000129aa0 sp=0xc000129a80 pc=0x5602b84c0105
internal/poll.(*pollDesc).wait(0xc00058c580?, 0xc00053acd0?, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc000129ac8 sp=0xc000129aa0 pc=0x5602b853ee47
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadMsg(0xc00058c580, {0xc00053acd0, 0x10, 0x10}, {0xc0003b5320, 0x1000, 0x1000}, 0xc000078800?)
	/usr/lib/golang/src/internal/poll/fd_unix.go:301 +0x38a fp=0xc000129bb8 sp=0xc000129ac8 pc=0x5602b854134a
net.(*netFD).readMsg(0xc00058c580, {0xc00053acd0?, 0x7fd1ee203a68?, 0x10?}, {0xc0003b5320?, 0xc000550a70?, 0x0?}, 0xc000129ce8?)
	/usr/lib/golang/src/net/fd_posix.go:78 +0x31 fp=0xc000129c40 sp=0xc000129bb8 pc=0x5602b8662ef1
net.(*UnixConn).readMsg(0xc000228148, {0xc00053acd0?, 0xc000129d88?, 0xc000129dc8?}, {0xc0003b5320?, 0x5602bac308e0?, 0xc0000d20f4?})
	/usr/lib/golang/src/net/unixsock_posix.go:115 +0x45 fp=0xc000129cd0 sp=0xc000129c40 pc=0x5602b8684f45
net.(*UnixConn).ReadMsgUnix(0xc000228148, {0xc00053acd0?, 0x5602b845da76?, 0xc000129d90?}, {0xc0003b5320?, 0xc000129da8?, 0x5602b858ef26?})
	/usr/lib/golang/src/net/unixsock.go:143 +0x36 fp=0xc000129d48 sp=0xc000129cd0 pc=0x5602b8682c96
github.com/godbus/dbus/v5.(*oobReader).Read(0xc0003b5300, {0xc00053acd0?, 0xc0000a8820?, 0xc000129df8?})
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/godbus/dbus/v5/transport_unix.go:41 +0x3c fp=0xc000129dc0 sp=0xc000129d48 pc=0x5602b8cf439c
io.ReadAtLeast({0x5602b9f4e4a0, 0xc0003b5300}, {0xc00053acd0, 0x10, 0x10}, 0x10)
	/usr/lib/golang/src/io/io.go:335 +0x90 fp=0xc000129e08 sp=0xc000129dc0 pc=0x5602b84d3490
io.ReadFull(...)
	/usr/lib/golang/src/io/io.go:354
github.com/godbus/dbus/v5.(*unixTransport).ReadMessage(0xc0005182b8)
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/godbus/dbus/v5/transport_unix.go:116 +0x22a fp=0xc000129f58 sp=0xc000129e08 pc=0x5602b8cf4a8a
github.com/godbus/dbus/v5.(*Conn).inWorker(0xc000028000)
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/godbus/dbus/v5/conn.go:389 +0x43 fp=0xc000129fc8 sp=0xc000129f58 pc=0x5602b8cdcf23
github.com/godbus/dbus/v5.(*Conn).Auth.func1()
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/godbus/dbus/v5/auth.go:118 +0x25 fp=0xc000129fe0 sp=0xc000129fc8 pc=0x5602b8cda4c5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000129fe8 sp=0xc000129fe0 pc=0x5602b84c61e1
created by github.com/godbus/dbus/v5.(*Conn).Auth in goroutine 1
	/builddir/build/BUILD/podman-4.9.4/vendor/github.com/godbus/dbus/v5/auth.go:118 +0x945

goroutine 8 [select]:
runtime.gopark(0xc00008fee8?, 0x2?, 0x44?, 0x11?, 0xc00008fea4?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc00008fca8 sp=0xc00008fc88 pc=0x5602b849242e
runtime.selectgo(0xc00008fee8, 0xc00008fea0, 0x0?, 0x0, 0x0?, 0x1)
	/usr/lib/golang/src/runtime/select.go:327 +0x725 fp=0xc00008fdc8 sp=0xc00008fca8 pc=0x5602b84a2be5
github.com/containers/podman/v4/libpod.(*Runtime).libimageEvents.func2()
	/builddir/build/BUILD/podman-4.9.4/libpod/runtime.go:749 +0xdd fp=0xc00008ffe0 sp=0xc00008fdc8 pc=0x5602b93fa9fd
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00008ffe8 sp=0xc00008ffe0 pc=0x5602b84c61e1
created by github.com/containers/podman/v4/libpod.(*Runtime).libimageEvents in goroutine 1
	/builddir/build/BUILD/podman-4.9.4/libpod/runtime.go:725 +0x10b

goroutine 50 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:398 +0xce fp=0xc000586708 sp=0xc0005866e8 pc=0x5602b849242e
runtime.chanrecv(0xc000234b40, 0xc0005867c8, 0x1)
	/usr/lib/golang/src/runtime/chan.go:583 +0x3cd fp=0xc000586780 sp=0xc000586708 pc=0x5602b845df4d
runtime.chanrecv2(0x0?, 0x0?)
	/usr/lib/golang/src/runtime/chan.go:447 +0x12 fp=0xc0005867a8 sp=0xc000586780 pc=0x5602b845db72
github.com/containers/podman/v4/libpod.(*Runtime).startWorker.func1()
	/builddir/build/BUILD/podman-4.9.4/libpod/runtime_worker.go:9 +0x6c fp=0xc0005867e0 sp=0xc0005867a8 pc=0x5602b941662c
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0005867e8 sp=0xc0005867e0 pc=0x5602b84c61e1
created by github.com/containers/podman/v4/libpod.(*Runtime).startWorker in goroutine 1
	/builddir/build/BUILD/podman-4.9.4/libpod/runtime_worker.go:8 +0x8e

### Describe the results you expected

I expected to see the disk usage of running containers and volumes.

### podman info output

```yaml
$ podman system info
host:
  arch: amd64
  buildahVersion: 1.33.7
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.fc39.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 97.79
    systemPercent: 0.93
    userPercent: 1.28
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: workstation
    version: "39"
  eventLogger: journald
  freeLocks: 1945
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.8.4-200.fc39.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 20281274368
  memTotal: 33651453952
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns:
      package: podman-plugins-4.9.4-1.fc39.x86_64
      path: /usr/libexec/cni/dnsname
      version: |-
        CNI dnsname plugin
        version: 1.3.1
        commit: unknown
    package: |-
      containernetworking-plugins-1.3.0-3.fc39.x86_64
      podman-plugins-4.9.4-1.fc39.x86_64
    path: /usr/libexec/cni
  ociRuntime:
    name: crun
    package: crun-1.14.4-1.fc39.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.4
      commit: a220ca661ce078f2c37b38c92e66cf66c012d9c1
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240220.g1e6f92b-1.fc39.x86_64
    version: |
      pasta 0^20240220.g1e6f92b-1.fc39.x86_64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc39.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 3h 12m 21.00s (Approximately 0.12 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: true
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
    PullFromMirror: ""
  quay.io:
    Blocked: true
    Insecure: false
    Location: quay.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: quay.io
    PullFromMirror: ""
  registry.centos.org:
    Blocked: true
    Insecure: false
    Location: registry.centos.org
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.centos.org
    PullFromMirror: ""
  registry.fedoraproject.org:
    Blocked: true
    Insecure: false
    Location: registry.fedoraproject.org
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.fedoraproject.org
    PullFromMirror: ""
store:
  configFile: /home/kumadee/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/kumadee/.local/share/containers/storage
  graphRootAllocated: 273803116544
  graphRootUsed: 187152842752
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1835
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/kumadee/.local/share/containers/storage/volumes
version:
  APIVersion: 4.9.4
  Built: 1711445992
  BuiltTime: Tue Mar 26 10:39:52 2024
  GitCommit: ""
  GoVersion: go1.21.8
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.4
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

The VM is running within VirtualBox.

**Comment by Luap99** [comment] 2024-04-19 10:15
Duplicate of #20942
Fixed in podman 5

**Closed by Luap99** 2024-04-19 10:15 UTC
Labels: kind/bug
