### ISSUE TITLE
v5.0.0-RC3 MacOS amd installer bad CPU type

### ISSUE THREAD

**Issue by xbabalov** [containers/podman#21902] opened 2024-03-01 13:50 UTC
### Issue Description

I installed Podman through the v5.0.0-RC3 podman-installer-macos-amd64.pkg installer on my Intel Mac. Running `podman version` results in `zsh: bad CPU type in executable: podman`. Podman is also not detected by Podman Desktop.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install Podman v5.0.0 using podman-installer-macos-amd64.pkg installer
2. Run `podman version` (or any podman command)

### Describe the results you received

`zsh: bad CPU type in executable: podman`

### Describe the results you expected

`podman version 5.0.0`

### podman info output

```yaml
`zsh: bad CPU type in executable: podman`
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by Luap99** [comment] 2024-03-01 13:56
Duplicate of #21769

**Closed by Luap99** 2024-03-01 13:56 UTC
Labels: kind/bug
