### ISSUE TITLE
Can't pull public image from ghcr.io: 403

### ISSUE THREAD

**Issue by SuperFluffy** [containers/podman#18155] opened 2023-04-12 08:50 UTC
### Issue Description

When trying to pull any public image from ghcr.io I get 403 status code from the server:
```sh
❯ podman logout --all
Removed login credentials for all registries
❯ podman pull ghcr.io/tomwright/dasel:latest
Trying to pull ghcr.io/tomwright/dasel:latest...
Error: initializing source docker://ghcr.io/tomwright/dasel:latest:
Requesting bearer token: invalid status code from registry 403 (Forbidden)
```

Note that immediately after logging in using a personal access token pulling works:
```sh
❯ podman login ghcr.io
Authenticating with existing credentials for ghcr.io
Existing credentials are invalid, please enter valid username and password
Username (superfluffy): superfluffy
Password:
Login Succeeded!

❯ podman pull ghcr.io/tomwright/dasel:latest
Trying to pull ghcr.io/tomwright/dasel:latest...
Getting image source signatures
Copying blob 63ab8c9a809b done
Copying blob 3689b8de819b done
Copying config e9c1a75695 done
Writing manifest to image destination
Storing signatures
e9c1a756955ae6924e299298961b2530505bc4d2d8267427af81a8d88e0f6a3f
```

Docker has no issues pulling images:
```sh
❯ docker logout ghcr.io
Removing login credentials for ghcr.io

❯ docker pull ghcr.io/tomwright/dasel:latest
latest: Pulling from tomwright/dasel
3689b8de819b: Pull complete
63ab8c9a809b: Pull complete
Digest: sha256:670b7e2e6ebc711eb3e9ea4a69d7e5b835253bbac2ab3b8234f1f5bbb4a93a58
Status: Downloaded newer image for ghcr.io/tomwright/dasel:latest
ghcr.io/tomwright/dasel:latest
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman logout --all`
2. `podman pull ghcr.io/tomwright/dasel:latest`
3. observe error

### Describe the results you received

I received an error with a 403 error status and message `Requesting bearer token: invalid status code from registry 403 (Forbidden)`

### Describe the results you expected

I expected podman to successfully pull the public image similar to docker or when I log into my github account.

### podman info output

```yaml
❯ podman info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 60.35
    systemPercent: 13.11
    userPercent: 26.54
  cpus: 16
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: blackie
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 6.2.8-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 27468800000
  memTotal: 63104663552
  networkBackend: cni
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.8.3-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 228h 50m 54.00s (Approximately 9.50 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - docker.io
store:
  configFile: /home/janis/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/janis/.local/share/containers/storage
  graphRootAllocated: 1803195609088
  graphRootUsed: 912146685952
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/janis/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.4
  Built: 1680009696
  BuiltTime: Tue Mar 28 15:21:36 2023
  GitCommit: c8223435f49a860c8ac4281a85db39232745a7cb-dirty
  GoVersion: go1.20.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Bare metal:
```
❯ podman version
Client:       Podman Engine
Version:      4.4.4
API Version:  4.4.4
Go Version:   go1.20.2
Git Commit:   c8223435f49a860c8ac4281a85db39232745a7cb-dirty
Built:        Tue Mar 28 15:21:36 2023
OS/Arch:      linux/amd64

❯ pacman -Qi podman
Name            : podman
Version         : 4.4.4-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/podman
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : catatonit  conmon  containers-common  crun  gcc-libs  glibc  iptables
                  device-mapper  libdevmapper.so=1.02-64  gpgme  libgpgme.so=11-64
                  libseccomp  libseccomp.so=2-64  slirp4netns
Optional Deps   : apparmor: for AppArmor support
                  btrfs-progs: support btrfs backend devices [installed]
                  cni-plugins: for an alternative container-network-stack implementation
                  [installed]
                  fuse-overlayfs: for storage driver in rootless environment [installed]
                  podman-compose: for docker-compose compatibility [installed]
                  podman-docker: for Docker-compatible CLI
Required By     : podman-compose
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 79.24 MiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Tue Mar 28 15:21:36 2023
Install Date    : Fri Mar 31 22:40:27 2023
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

❯ uname -srvmpio
Linux 6.2.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000 x86_64 unknown unknown GNU/Linux
```

Archlinux builds podman from the v4.4.4 tagged ref:
https://github.com/archlinux/svntogit-community/blob/18ef17c01ae18f9e8faaf8d33ef8afe2d29ab529/trunk/PKGBUILD

**Comment by vrothberg** [comment] 2023-04-12 08:55
Thanks for reaching out, @SuperFluffy!

I cannot reproduce on my machine.  Can you rerun `podman pull` with `--log-level=debug` (after a `podman logout`) and share the output?

Cc: @mtrmac

**Comment by vrothberg** [comment] 2023-04-12 09:11
@SuperFluffy, no worries at all.  I appreciate you taking the time to reach out.

It could very well be a bug on the registry side or some maintenance window etc.  I suggest to close the issue for now but please reach out again if you see it popping up again.

**Closed by vrothberg** 2023-04-12 09:11 UTC
Labels: kind/bug

**Comment by agardnerIT** [comment] 2023-05-02 22:25
I'm getting this too on `v4.5.0`

```
% podman version
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.3
Git Commit:   75e3c12579d391b81d871fd1cded6cf0d043550a
Built:        Fri Apr 14 23:28:20 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.4.4
API Version:  4.4.4
Go Version:   go1.20.1
Built:        Mon Apr  3 21:28:56 2023
OS/Arch:      linux/arm64

% podman logout --all
Removed login credentials for all registries

% podman logout ghcr.io
Error: not logged into ghcr.io

% podman pull --log-level=debug ghcr.io/agardnerit/containerbuild:main
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called pull.PersistentPreRunE(podman pull --log-level=debug ghcr.io/agardnerit/containerbuild:main) 
DEBU[0000] SSH Ident Key "/Users/.../.ssh/podman-machine-default" SHA256:a2...O/N......k ssh-ed25519 
DEBU[0000] DoRequest Method: GET URI: http://d/v4.5.0/libpod/_ping 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0000] DoRequest Method: POST URI: http://d/v4.5.0/libpod/images/pull 
Trying to pull ghcr.io/agardnerit/containerbuild:main...
Error: initializing source docker://ghcr.io/agardnerit/containerbuild:main: unable to retrieve auth token: invalid username/password: unauthorized
DEBU[0000] Shutting down engines
```
