### ISSUE TITLE
Replacing --privileged flag with all capabilities does not seem to work

### ISSUE THREAD

**Issue by ashokponkumar** [containers/podman#8856] opened 2020-12-30 13:06 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind question

**Description**
When trying to run a fedora 33 container with podman in it inside a Kubernetes cluster with /var/lib/container mounted with emptyDir, and with privileged mode enabled, I  am able to run podman successfully. But when I replace the privileged mode with all CAP permissions, it does not seem to work. 

```
          securityContext:
            #privileged: true
            capabilities:
              add: [CHOWN,DAC_OVERRIDE,DAC_READ_SEARCH,FOWNER,FSETID,KILL,SETGID,SETUID,SETPCAP,LINUX_IMMUTABLE,NET_BIND_SERVICE,NET_BROADCAST,NET_ADMIN,NET_RAW,IPC_LOCK,IPC_OWNER,SYS_MODULE,SYS_RAWIO,SYS_CHROOT,SYS_PTRACE,SYS_PACCT,SYS_ADMIN,SYS_BOOT,SYS_NICE,SYS_RESOURCE,SYS_TIME,SYS_TTY_CONFIG,MKNOD,LEASE,AUDIT_WRITE,AUDIT_CONTROL,SETFCAP,MAC_OVERRIDE,MAC_ADMIN,SYSLOG,WAKE_ALARM,BLOCK_SUSPEND,AUDIT_READ]
 ```

I get the following error:
`Error: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver`

**Context**
I am trying to get [this pod](https://github.com/konveyor/move2kube-operator/blob/main/helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml) working with the least privileges required.

**Steps to reproduce the issue:**

1. In a pod with podman, if we give below as security context `podman version` works without issue.

```
          securityContext:
            privileged: true

```

2. If we replace the security context with the below, I get the error stated above.

```
          securityContext:
            capabilities:
              add: [CHOWN,DAC_OVERRIDE,DAC_READ_SEARCH,FOWNER,FSETID,KILL,SETGID,SETUID,SETPCAP,LINUX_IMMUTABLE,NET_BIND_SERVICE,NET_BROADCAST,NET_ADMIN,NET_RAW,IPC_LOCK,IPC_OWNER,SYS_MODULE,SYS_RAWIO,SYS_CHROOT,SYS_PTRACE,SYS_PACCT,SYS_ADMIN,SYS_BOOT,SYS_NICE,SYS_RESOURCE,SYS_TIME,SYS_TTY_CONFIG,MKNOD,LEASE,AUDIT_WRITE,AUDIT_CONTROL,SETFCAP,MAC_OVERRIDE,MAC_ADMIN,SYSLOG,WAKE_ALARM,BLOCK_SUSPEND,AUDIT_READ]
 ```

**Describe the results you received:**
All capabilities addition does not seem to be same as `privileged`. 

**Describe the results you expected:**
I would like to know what more might be required to be added to security context to make podman work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 14:37:50 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

With privileged enabled.
```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: file
  hostname: m2k-move2kubeapi-1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.15.0-118-generic
  linkmode: dynamic
  memFree: 251277312
  memTotal: 16813735936
  ociRuntime:
    name: runc
    package: runc-1.0.0-279.dev.gitdedadbf.fc33.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92+dev
      commit: c9a9ce0286785bef3f3c3c87cd1232e535a03e15
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 1673h 5m 27.58s (Approximately 69.71 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438270
  BuiltTime: Tue Dec  8 14:37:50 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes, checked with the latest version from dnf

**Additional environment details (AWS, VirtualBox, physical, etc.):**
IBM Kubernetes Cluster (IKS)

**Comment by rhatdan** [comment] 2020-12-30 14:56
You need to setup a volume to be mounted on the containers container/storage. 
If you are running within a container you can not mount an overlay on an overlay.  The kernel does not allow this.
Podman/Buildah use /var/lib/containers for its overlay mounts.  So mounting a non overlay file system on /var/lib/containers will stop the error.

Alternatively you could use fuse-overlayfs within the container to use a fuse file system instead of an overlayfs.  You can set this up by setting the mount_program inside of /etc/containers/storage.conf.

**Comment by ashokponkumar** [comment] 2020-12-30 15:05
Thanks @rhatdan for the quick response. 

I am indeed mounting a storage into the container at /var/lib/containers (https://github.com/konveyor/move2kube-operator/blob/6d2642f4570d81c568ddcb9379ce4f4ce8a37c7a/helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml#L33). Without this, even with --privileged flag it fails. Currently with mounting, it still fails without `privileged` flag.

Will checkout with the following values and get back.
```
[storage]
  driver = "overlay"
  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
```

**Comment by ashokponkumar** [comment] 2020-12-30 18:03
> You need to setup a volume to be mounted on the containers container/storage.
> If you are running within a container you can not mount an overlay on an overlay. The kernel does not allow this.
> Podman/Buildah use /var/lib/containers for its overlay mounts. So mounting a non overlay file system on /var/lib/containers will stop the error.
> 
> Alternatively you could use fuse-overlayfs within the container to use a fuse file system instead of an overlayfs. You can set this up by setting the mount_program inside of /etc/containers/storage.conf.

Even if I set mount_program, I get the below error, even if I give all CAP permissions to the container.

`Error: mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: permission denied`

**Comment by rhatdan** [comment] 2020-12-30 19:59
Could you show exactly what command you are using?  Are you running the container within docker? Podman? Kubernetes?

**Comment by ashokponkumar** [comment] 2020-12-30 20:19
> Could you show exactly what command you are using?  Are you running the container within docker? Podman? Kubernetes?

I get this error for even `podman version` command. I am running the container within kubernetes (which I assume is using containerd, and I think I got similar error with cri-o too).


After it works, the code I intend to execute (move2kube - https://github.com/konveyor/move2kube/blob/0e9d69d02c16379c6492e2404080fa295cc08a5f/internal/containerizer/cnb/containerruntimeprovider.go#L59) runs multiple podman commands like inspect, pull, run etc. 

With privileged option enabled in security context and a emptydir volume mounted in /var/lib/containers, everything above is working fine, both in Kubernetes and Openshift (with scc). I am now trying to reduce the permissions required if possible.

**Comment by rhatdan** [comment] 2021-01-04 13:49
This could be caused by SELinux, Or seccomp, which both should have been turned off via privileged flag.  Bottom line something is preventing the container from executing with privs.  Not sure if containerd works correctly. mightbe able to further diagnose with CRI-O.

**Comment by rhatdan** [comment] 2021-02-03 17:21
BTW Privileged also turns off the read/only mounts on /proc and on /sys file system as well as masking over them.

**Comment by rhatdan** [comment] 2021-02-03 17:22
@umohnani8 When the smoke clears on 3.0 you and I have to write a blog on using podman within other container runtimes. Specificall podman in podman and podman within CRI-O/Kubernetes.

**Comment by rhatdan** [comment] 2021-02-04 18:34
Since we have 3 other podman-in-container issues, I am going to close this one.  Please look for podman-in-container label and add comments there.

**Closed by rhatdan** 2021-02-04 18:34 UTC
Labels: Question, podman-in-container
