### ISSUE TITLE
--volumes-from not mounting files in volume

### ISSUE THREAD

**Issue by MattBelle** [containers/podman#23994] opened 2024-09-17 14:39 UTC
### Bug description

I cannot access files from a volume declared in another container.

### Operating system

macOS Sonoma 14.5 Apple silicon (Apple M3 Pro)

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

### Steps to reproduce

Build an image with the following Containerfile:

```
FROM ubuntu

RUN mkdir -p /opt/foo
RUN echo somedata > /opt/foo/bar.txt

VOLUME /opt/foo
```

create a container instance, and then mount the previously declared volume into a new container with `--volumes-from` podman will recreate the path of the volume,  but leave the volume's contents empty:

```
✦5 ❯ podman build --platform linux/amd64 -t test .
STEP 1/4: FROM ubuntu
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/ubuntu:latest...
Getting image source signatures
Copying blob sha256:dafa2b0c44d2cfb0be6721f079092ddf15dc8bc537fb07fe7c3264c15cb2e8e6
Copying config sha256:b1e9cef3f2977f8bdd19eb9ae04f83b315f80fe4f5c5651fedf41482c12432f7
Writing manifest to image destination
STEP 2/4: RUN mkdir -p /opt/foo
--> 49c309434912
STEP 3/4: RUN echo somedata > /opt/foo/bar.txt
--> a3dd61166e74
STEP 4/4: VOLUME /opt/foo
COMMIT test
--> 76e5299764c8
Successfully tagged localhost/test:latest
76e5299764c809617932e05fcb27f52f4dac153d35d460dfa97600564654d9d0

✦5 ❯ podman create --platform linux/amd64 test
a34d6314305ef858d84af1f2215a550252dc3affe29d49a96e99744602872545

✦5 ❯ podman run --platform linux/amd64 --volumes-from a34d6314305ef858d84af1f2215a550252dc3affe29d49a96e99744602872545 ubuntu ls /opt/foo

```

running these exact commands with docker will correctly list `bar.txt` as a child of the volume.

**Comment by benoitf** [comment] 2024-09-18 08:16
transferring to podman repository as reproducer is done without Podman Desktop, just using podman/podman CLI

**Comment by Luap99** [comment] 2024-09-18 08:31
Duplicate of https://github.com/containers/podman/issues/23643

You need to set the prepare_volume_on_create contianers.conf option if you want to copy the volume contents into the volume on create and not start time. Given you are using machine you would have to set this inside the VM not on client.

**Closed by Luap99** 2024-09-18 08:31 UTC
