### ISSUE TITLE
Rootless Podman won't work since version 3.1.0

### ISSUE THREAD

**Issue by rffontenelle** [containers/podman#9936] opened 2021-04-05 01:19 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

> This subject was initially discussed at https://bbs.archlinux.org/viewtopic.php?id=265140.

Since v3.1.0, rootless Podman is not working with the same configuration that worked in v3.0.1 for some images.

It is hanging with zero output (only when ran in rootless mode!) with `rootless_storage_path` defined with "$HOME" variable. If  `rootless_storage_path` is commented out or set to an user's home path (instead of $HOME variable), it sort of works. It is as if $HOME was being used literally, instead of as a variable.

When I say "sort of works" it is because it still gives "operation not permitted" with some Docker images, like archlinux or ubuntu. However, I tested with alpine and fedora, and it works. See error outputs below.

**Steps to reproduce the issue:**

1. enable `rootless_storage_path` setting in `/etc/containers/storage.conf` with the following value
    ```
    rootless_storage_path = "$HOME/.local/share/containers/storage"
    ```

2. run `podman pull docker.io/archlinux` as normal user

3. the CLI should be hanging, so run Ctrl+C to cancel the previous command

4. now set `rootless_storage_path` with the home directory, say "/home/foo/"
    ```
    rootless_storage_path = "/home/foo/.local/share/containers/storage"
    ```

5. run `podman pull docker.io/archlinux` as normal user again

6. layers are download, but it ends up with "operation not permitted" error message

**Describe the results you received:**

Terminal is hanging when `rootless_storage_path` is set and has "$HOME" in its path:

```
$ podman pull docker.io/archlinux

```

If "$HOME" is replaced with real valid path like "/home/foo", I get the following output:

```
$ podman pull docker.io/archlinux
Trying to pull docker.io/library/archlinux:latest...
Getting image source signatures
Copying blob 10756994dc19 skipped: already exists  
Copying blob 5bb50848eab8 done  
Copying config 3de742be92 done  
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): operation not permitted
Error: Error committing the finished image: error adding layer with blob "sha256:5bb50848eab8d3d80a48b3769ef342097f57881b1ef86826e898c43ee4dd2460": Error processing tar file(exit status 1): operation not permitted
```

But not all images:

```
$ podman pull docker.io/alpine
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob ca3cd42a7c95 done  
Copying config 49f356fa45 done  
Writing manifest to image destination
Storing signatures
49f356fa4513676c5e22e3a8404aad6c7262cc7aaed15341458265320786c58c
```

**Describe the results you expected:**

Be able to use Podman in rootless mode for all images, mainly Arch Linux

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.1.0
API Version:  3.1.0
Go Version:   go1.16.2
Git Commit:   9f09fb62cba8f44c18eda84db3e72aab3ae76046-dirty
Built:        Wed Mar 31 11:46:48 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon pertence a conmon 1:2.0.27-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: 65fad4bfcb250df0435ea668017e643e7f462155'
  cpus: 4
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: arch
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65537
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65537
  kernel: 5.11.11-arch1-1
  linkmode: dynamic
  memFree: 1937080320
  memTotal: 8222564352
  ociRuntime:
    name: runc
    package: /usr/bin/runc pertence a runc 1.0.0rc93-2
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
      spec: 1.0.2-dev
      go: go1.16.2
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns pertence a slirp4netns 1.1.9-1
    version: |-
      slirp4netns version 1.1.9
      commit: 4e37ea557562e0d7a64dc636eff156f64927335e
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 12884897792
  swapTotal: 12884897792
  uptime: 52m 57.03s
registries:
  search:
  - docker.io
store:
  configFile: /home/rafael/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/rafael/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/rafael/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.0
  Built: 1617202008
  BuiltTime: Wed Mar 31 11:46:48 2021
  GitCommit: 9f09fb62cba8f44c18eda84db3e72aab3ae76046-dirty
  GoVersion: go1.16.2
  OsArch: linux/amd64
  Version: 3.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ pacman -Qi podman
Name            : podman
Version         : 3.1.0-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  device-mapper
                  iptables  libseccomp  runc  slirp4netns  libsystemd
                  fuse-overlayfs  libgpgme.so=11-64
Optional Deps   : podman-docker: for Docker-compatible CLI
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support
                  crun: support for unified cgroupsv2
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 72.86 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Wed Mar 31 11:46:48 2021
Install Date    : Sun Apr 4 20:38:40 2021
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes (the commit tested was 72eb0005f) and yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Its a physical machine, running Arch Linux 64-bit, with containers-common installed.

Here is my rootless mode settings (See [Podman in ArchWiki](https://wiki.archlinux.org/index.php/Podman#Rootless_Podman) for the guide followed):
- `kernel.unprivileged_userns_clone=1` already set by the stock Linux kernel in Arch Linux
- cgroups v2 already set since Systemd v248, and which is the version currently installed.
- subuid and subgid: both set with ```rafael:100000:65536``` (my username and group)

**Comment by calebstewart** [comment] 2021-04-05 02:36
I'm also experiencing this issue, and just thought I'd note that I can't find any pattern when looking at various image manifests. `archlinux` and `ubuntu` both fail for me, while `alpine` works fine.

**archlinux manifest**
```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 1801,
    "digest": "sha256:3de742be9254c8423b72d08dde70cc049d9897ea8de1a981aa77b9071e41ad53"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 134275179,
      "digest": "sha256:10756994dc1943314a638a8a9f7808b269aff96c2890521a68699803a98f792f"
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 6660,
      "digest": "sha256:5bb50848eab8d3d80a48b3769ef342097f57881b1ef86826e898c43ee4dd2460"
    }
  ]
}
```

**ubuntu manifest**
```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 3316,
    "digest": "sha256:26b77e58432b01665d7e876248c9056fa58bf4a7ab82576a024f5cf3dac146d6"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 28569016,
      "digest": "sha256:a70d879fa5984474288d52009479054b8bb2993de2a1859f43b5480600cecb24"
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 848,
      "digest": "sha256:c4394a92d1f8760cf7d17fee0bcee732c94c5b858dd8d19c7ff02beecf3b4e83"
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 187,
      "digest": "sha256:10e6159c56c084c858f5de2416454ac0a49ddda47b764e4379c5d5a147c9bf5f"
    }
  ]
}
```

**alpine manifest**
```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 1472,
    "digest": "sha256:49f356fa4513676c5e22e3a8404aad6c7262cc7aaed15341458265320786c58c"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 2811947,
      "digest": "sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15"
    }
  ]
}
```

**Comment by bitstrings** [comment] 2021-04-05 03:32
I got the same issue, same behaviours as OP.

```
podman pull ubuntu

Trying to pull docker.io/library/ubuntu:latest...
Getting image source signatures
Copying blob a70d879fa598 skipped: already exists  
Copying blob c4394a92d1f8 skipped: already exists  
Copying blob 10e6159c56c0 done  
Copying config 26b77e5843 done  
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): operation not permitted
Error: Error committing the finished image: error adding layer with blob "sha256:10e6159c56c084c858f5de2416454ac0a49ddda47b764e4379c5d5a147c9bf5f": Error processing tar file(exit status 1): operation not permitted
```

**Comment by mheon** [comment] 2021-04-05 04:15
@rhatdan PTAL

**Comment by SahilChaudhary25** [comment] 2021-04-05 05:28
i am getting this error

Getting image source signatures
Copying blob 0a5e725150a2 done
Copying blob 9ab4bf1101f3 done
Copying blob 751620502a7a done
Copying blob 101c41d0463b done
Copying blob e4c3d3e4f7b0 done
Copying blob 8275efcd805f done
Copying blob 9ba108bf0aed done
Copying blob 67fa621f5716 done
Copying blob eac75d8e87c4 done
Copying blob 39fbc9d321cc done
Copying blob b0738a49740d done
Copying blob cfeec63032ba done
Copying blob 1a1413bab799 done
Copying blob 1fc24897a7b3 done
Copying blob 61e0e6cbf188 done
Copying blob efafcd88086a done
Copying blob 3787a9910beb done
Copying blob 93de00f6392a done
Copying blob e4d33e48646b done
Copying blob cf6cbd30cfec done
Copying blob 969c8ca772c4 done
Copying blob 3d59c3ad3f7a done
Copying blob 2b11e1322dbb done
Copying blob e0c40ad85d99 done
Copying blob fd20bda8a407 done
Copying blob 480010707a10 done
Copying config 35a9517e93 done
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): remount /, flags: 0x44000: permission denied
Error: Error committing the finished image: error adding layer with blob "sha256:e4c3d3e4f7b024979a1c12daa4073f6353b2ba92d96418bc90451994927c9bff": Error processing tar file(exit status 1): remount /, flags: 0x44000: permission denied

**Comment by Fenrikur** [comment] 2021-04-05 10:12
There seems to be potentially related issue with consistent environment variable expansion in `storage.conf`'s setting `rootless_storage_path`, as setting it to a directory with well-known permissions like
`[storage]
rootless_storage_path = "/tmp/$USER/.local/share/containers/storage"`
will yield the following structure after running `podman system info` from a rootless-enabled user:

```
/tmp/$USER
/tmp/$USER/.local
/tmp/$USER/.local/share
/tmp/$USER/.local/share/containers
/tmp/$USER/.local/share/containers/storage
/tmp/$USER/.local/share/containers/storage/overlay
/tmp/fen
/tmp/fen/.local
/tmp/fen/.local/share
/tmp/fen/.local/share/containers
/tmp/fen/.local/share/containers/storage
/tmp/fen/.local/share/containers/storage/overlay-layers
/tmp/fen/.local/share/containers/storage/overlay-layers/layers.lock
/tmp/fen/.local/share/containers/storage/overlay-containers
/tmp/fen/.local/share/containers/storage/overlay-containers/containers.lock
/tmp/fen/.local/share/containers/storage/overlay-images
/tmp/fen/.local/share/containers/storage/overlay-images/images.lock
/tmp/fen/.local/share/containers/storage/userns.lock
/tmp/fen/.local/share/containers/storage/storage.lock
/tmp/fen/.local/share/containers/storage/overlay
/tmp/fen/.local/share/containers/storage/overlay/l
/tmp/fen/.local/share/containers/storage/tmp
/tmp/fen/.local/share/containers/storage/mounts
/tmp/fen/.local/share/containers/storage/libpod
/tmp/fen/.local/share/containers/storage/libpod/bolt_state.db
```

When running additional commands like e.g. `podman pull docker.io/alpine:latest`, files will consistently only be written to the directory with the expanded environment variable (in this case `/tmp/fen/.local/share/containers/storage`).

**Comment by rhatdan** [comment] 2021-04-05 13:47
@giuseppe Ideas?

Are you seeing issues with SELinux or seccomp?

**Comment by rhatdan** [comment] 2021-04-05 13:49
Could you make sure you have the latest fuse-overlayfs installed.

**Comment by rhatdan** [comment] 2021-04-05 13:50
@giuseppe could this be these platforms attempting to use native overlay?

**Comment by bitstrings** [comment] 2021-04-05 15:15
@rhatdan `fuse-overlayfs:1.5.0`.

I don't use SELinux.

**Comment by SahilChaudhary25** [comment] 2021-04-05 16:51
I tried this $HOME variables expanded correctly, but indeed podman CLI is hanging even on info command

**Comment by rhatdan** [comment] 2021-04-05 16:52
Find, what I don't know is if these are all the same issues.

Is everyone running on arch, has everyone modified the storage.conf?

**Comment by calebstewart** [comment] 2021-04-05 17:12
> I tried this $HOME variables expanded correctly, but indeed podman CLI is hanging even on info command

Regarding the `$HOME` expansion, it seemed to not be expanding based on my `strace` of `podman` when it hangs. I can see it trying to call `newfstatat` with an unexpanded `$HOME` componenent. Afterwards, during "hanging", it is repeatedly calling the last line in the below output forever (consuming non-trivial CPU). It appears that it doesn't expand `$HOME` and then attempts to traverse the tree looking for the nearest existing directory, but gets stuck on `.` forever.

```
[pid 232536] newfstatat(AT_FDCWD, "$HOME/.local/share/containers/storage/overlay/.has-mount-program", 0xc00001c928, 0) = -1 ENOENT (No such file or directory)
[pid 232536] newfstatat(AT_FDCWD, "$HOME/.local/share/containers/storage/overlay", 0xc00001c9f8, 0) = -1 ENOENT (No such file or directory)
[pid 232536] newfstatat(AT_FDCWD, "$HOME/.local/share/containers/storage/overlay", 0xc00001cac8, 0) = -1 ENOENT (No such file or directory)
[pid 232536] newfstatat(AT_FDCWD, "$HOME/.local/share/containers/storage", 0xc00001cb98, 0) = -1 ENOENT (No such file or directory)
[pid 232536] newfstatat(AT_FDCWD, "$HOME/.local/share/containers", 0xc00001cc68, 0) = -1 ENOENT (No such file or directory)
[pid 232536] newfstatat(AT_FDCWD, "$HOME/.local/share", 0xc00001cd38, 0) = -1 ENOENT (No such file or directory)
[pid 232536] newfstatat(AT_FDCWD, "$HOME/.local", 0xc00001ce08, 0) = -1 ENOENT (No such file or directory)
[pid 232536] newfstatat(AT_FDCWD, "$HOME", 0xc00001ced8, 0) = -1 ENOENT (No such file or directory)
[pid 232536] newfstatat(AT_FDCWD, ".", {st_mode=S_IFDIR|0711, st_size=4096, ...}, 0) = 0
```

> Is everyone running on arch, has everyone modified the storage.conf?

I am running Arch. I have modified `storage.conf` in the same way, however leaving `rootless_storage_path` unset also appears to correctly resolve the default location (`$HOME/.local/share/containers/storage`). In either case, once getting past the hanging, I still get an "operation not permitted" error. 

I agree that this seems like two separate problems:
1. Something weird happening with `rootless_storage_path` and environment expansion.
2. `Operation not Permitted` error while pulling *some* images.

**Comment by rffontenelle** [comment] 2021-04-05 17:29
> Could you make sure you have the latest fuse-overlayfs installed.

@rhatdan OP here. Yes, using [fuse-overlayfs 1.5 0](https://archlinux.org/packages/community/x86_64/fuse-overlayfs/).

**Comment by bitstrings** [comment] 2021-04-05 18:09
@rhatdan No config files modified from vanilla.

`storage.conf` is untouched in my case. I got the same issues with `rootless_storage_path`.

`vfs` works.

**Comment by rhatdan** [comment] 2021-04-05 19:18
What does podman info show for storage?

**Comment by bitstrings** [comment] 2021-04-05 23:45
@rhatdan 

```
store:
  configFile: /home/p/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/p/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1001/containers
  volumePath: /home/p/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.0
  Built: 1617202008
  BuiltTime: Wed Mar 31 10:46:48 2021
  GitCommit: 9f09fb62cba8f44c18eda84db3e72aab3ae76046-dirty
  GoVersion: go1.16.2
  OsArch: linux/amd64
  Version: 3.1.0
```

**Comment by pendulm** [comment] 2021-04-06 09:38
I think this commit ec1651fbf11c4d3d1c792e7f46139ebd96f7ffb2 broken something.  `graphOptions` not get filled in rootless podman.

**Comment by giuseppe** [comment] 2021-04-06 10:45
> @giuseppe could this be these platforms attempting to use native overlay?

the error I am seeing "Error processing tar file(exit status 1): operation not permitted" happens at pull time.

It turns to be another issue in containers/storage with native rootless overlay: https://github.com/containers/storage/pull/872

**Comment by giuseppe** [comment] 2021-04-06 12:50
another issue is fixed with: https://github.com/containers/storage/pull/867

**Comment by Foxboron** [comment] 2021-04-07 13:05
Yo, `podman` packager for Arch. Wasn't aware of the issue until now and I'm happy to test patches and backport anything that fixes the issue.

**Comment by mheon** [comment] 2021-04-07 13:19
https://github.com/containers/storage/pull/872 should be ready to merge, but https://github.com/containers/storage/pull/867 does not look like it's ready yet. Once both are, we can cut a fresh release of c/storage and get it vendored into Podman for a 3.1.1. In the meantime, anyone who can manually apply the two and do a scratch-build to verify this actually resolves the issue would be greatly appreciated - I can't reproduce this myself so I can't verify the fix.

**Comment by Foxboron** [comment] 2021-04-07 22:05
I can confirm containers/storage#872 fixes this issue on Arch.  I'm a tiny bit unsure how to properly test containers/storage#867 so haven't done that.

<pre>
λ libpod master» ./bin/podman info                 
host:
  arch: amd64
  buildahVersion: 1.20.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.27-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: 65fad4bfcb250df0435ea668017e643e7f462155'
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: anathema
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.11-arch1-1
  linkmode: dynamic
  memFree: 1332187136
  memTotal: 16536141824
  ociRuntime:
    name: runc
    package: /usr/bin/runc is owned by runc 1.0.0rc93-2
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
      spec: 1.0.2-dev
      go: go1.16.2
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.9-1
    version: |-
      slirp4netns version 1.1.9
      commit: 4e37ea557562e0d7a64dc636eff156f64927335e
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 26h 27m 38.96s (Approximately 1.08 days)
registries: {}
store:
  configFile: /home/fox/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/fox/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/fox/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.0-dev
  Built: 1617832824
  BuiltTime: Thu Apr  8 00:00:24 2021
  GitCommit: 0e67053b9a26f20e5ccbffdcc5e7a84254ca16b8-dirty
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.2.0-dev
</pre>

Tiny bit manual patching to build.
<pre>
λ libpod master» git diff Makefile go.mod
diff --git a/Makefile b/Makefile
index a70e07991..a0fd2611d 100644
--- a/Makefile
+++ b/Makefile
@@ -41,7 +41,7 @@ PRE_COMMIT = $(shell command -v bin/venv/bin/pre-commit ~/.local/bin/pre-commit
 # our target (bin/podman{,-remote}), a rebuild is triggered.
 SOURCES = $(shell find . -path './.*' -prune -o \( -name '*.go' -a ! -name '*_test.go' \) -print)
 
-BUILDFLAGS := -mod=vendor $(BUILDFLAGS)
+BUILDFLAGS := $(BUILDFLAGS)
 
 BUILDTAGS_CROSS ?= containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper exclude_graphdriver_overlay
 CONTAINER_RUNTIME := $(shell command -v podman 2> /dev/null || echo docker)
diff --git a/go.mod b/go.mod
index 52d632b46..699cb99dd 100644
--- a/go.mod
+++ b/go.mod
@@ -71,3 +71,5 @@ require (
        k8s.io/api v0.20.5
        k8s.io/apimachinery v0.20.5
 )
+
+replace github.com/containers/storage => ../storage
</pre>

**Closed** 2021-04-08 09:10 UTC
Labels: kind/bug

**Comment by SahilChaudhary25** [comment] 2021-04-08 10:48
When we can expect podman 3.1.1 release into alpine community ?

**Comment by mheon** [comment] 2021-04-08 14:40
I would expect sometime next week. We need a fresh c/storage release cut and vendored into Podman, then we can cut a fresh release.
