### ISSUE TITLE
build copy-from: Unmounting, invalid argument, no stage or image found with that name

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14350] opened 2022-05-24 18:35 UTC
It's a one-off, but I don't like one-offs:
```
[+0818s] not ok 150 build with copy-from referencing the base image
...
         # # podman build --no-cache --jobs 4 -t derived-mt -f /tmp/podman_bats.1Efpk4/build-test/Containerfile2 /tmp/podman_bats.1Efpk4/build-test
         # [2/2] STEP 1/2: FROM quay.io/libpod/alpine AS final
         # [1/2] STEP 1/2: FROM quay.io/libpod/testimage:20210610 AS test
         # [1/2] STEP 2/2: RUN rm -f /etc/alpine-release
         # [2/2] STEP 2/2: COPY --from=quay.io/libpod/testimage:20210610 /etc/alpine-release /test/
         # time="2022-05-24T03:04:07-05:00" level=error msg="Unmounting /var/lib/containers/storage/overlay/a4ef9fae76fa79493269d65e523335cf55e36ac67e31c5f6f17e3599e2af7302/merged: invalid argument"
         # Error: COPY --from=quay.io/libpod/testimage:20210610: no stage or image found with that name
         # [ rc=125 (** EXPECTED 0 **) ]
```
### [sys] 150 build with copy-from referencing the base image
* fedora-35 : sys podman fedora-35 root host
  * PR #14319
    * [05-24 04:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6522966241443840/html/sys-podman-fedora-35-root-host.log.html#t--00150)

**Comment by vrothberg** [comment] 2022-05-25 12:51
@flouthoc this looks like a cool nut to track .

**Comment by rhatdan** [comment] 2022-07-28 13:24
@flouthoc do you have time to look at this?

**Comment by flouthoc** [comment] 2022-07-28 13:25
@rhatdan Sure. I'll take a look at this thanks.

**Comment by flouthoc** [comment] 2022-08-23 06:40
I am unable to reproduce this race no matter how many times i invoke this build. I can imaging a scenario where this happens when `quay.io/libpod/testimage:20210610` is removed forcefully from storage while the build is in progress but I am not sure if that can happen in CI.

My reproducer attempt ( from which i am not able to reproduce )
```Dockerfile
FROM quay.io/libpod/testimage:20210610 AS test
RUN rm -f /etc/alpine-release
FROM quay.io/libpod/alpine AS final
COPY --from=quay.io/libpod/testimage:20210610 /etc/alpine-release /test/
```
```console
podman build --no-cache --jobs 4 -t test .
```

Since I am unable to reproduce this on `main` and it had only occurred once with no history, I am closing this issue but @edsantiago please reopen the issue if this is a constant issue or there are more occurrence of this but as of now I can't reproduce this from `main`.

**Closed by flouthoc** 2022-08-23 06:40 UTC
Labels: flakes
