### ISSUE TITLE
Port forwarding large number of ports fails as the port is already in use

### ISSUE THREAD

**Issue by rcmadhankumar** [containers/podman#23964] opened 2024-09-16 11:22 UTC
### Issue Description

Trying to forward 1000 ports on an nginx container fails as podman assigns a port which is already in use.

```
podman run -d -p 80/tcp -p 443/tcp -p 500/tcp -p 501/tcp -p 502/tcp ............ -p 999/tcp  -p 200/udp -p 201/udp ...... -p 699/udp -it <nginx_base_image> 


Failed to bind port 41283 (Address already in use) for option '-u 41283-41283:539-539'

```

### Steps to reproduce the issue

Steps to reproduce the issue
1.Full command
```
podman run -d -p 80/tcp -p 443/tcp -p 500/tcp -p 501/tcp -p 502/tcp -p 503/tcp -p 504/tcp -p 505/tcp -p 506/tcp -p 507/tcp -p 508/tcp -p 509/tcp -p 510/tcp -p 511/tcp -p 512/tcp -p 513/tcp -p 514/tcp -p 515/tcp -p 516/tcp -p 517/tcp -p 518/tcp -p 519/tcp -p 520/tcp -p 521/tcp -p 522/tcp -p 523/tcp -p 524/tcp -p 525/tcp -p 526/tcp -p 527/tcp -p 528/tcp -p 529/tcp -p 530/tcp -p 531/tcp -p 532/tcp -p 533/tcp -p 534/tcp -p 535/tcp -p 536/tcp -p 537/tcp -p 538/tcp -p 539/tcp -p 540/tcp -p 541/tcp -p 542/tcp -p 543/tcp -p 544/tcp -p 545/tcp -p 546/tcp -p 547/tcp -p 548/tcp -p 549/tcp -p 550/tcp -p 551/tcp -p 552/tcp -p 553/tcp -p 554/tcp -p 555/tcp -p 556/tcp -p 557/tcp -p 558/tcp -p 559/tcp -p 560/tcp -p 561/tcp -p 562/tcp -p 563/tcp -p 564/tcp -p 565/tcp -p 566/tcp -p 567/tcp -p 568/tcp -p 569/tcp -p 570/tcp -p 571/tcp -p 572/tcp -p 573/tcp -p 574/tcp -p 575/tcp -p 576/tcp -p 577/tcp -p 578/tcp -p 579/tcp -p 580/tcp -p 581/tcp -p 582/tcp -p 583/tcp -p 584/tcp -p 585/tcp -p 586/tcp -p 587/tcp -p 588/tcp -p 589/tcp -p 590/tcp -p 591/tcp -p 592/tcp -p 593/tcp -p 594/tcp -p 595/tcp -p 596/tcp -p 597/tcp -p 598/tcp -p 599/tcp -p 600/tcp -p 601/tcp -p 602/tcp -p 603/tcp -p 604/tcp -p 605/tcp -p 606/tcp -p 607/tcp -p 608/tcp -p 609/tcp -p 610/tcp -p 611/tcp -p 612/tcp -p 613/tcp -p 614/tcp -p 615/tcp -p 616/tcp -p 617/tcp -p 618/tcp -p 619/tcp -p 620/tcp -p 621/tcp -p 622/tcp -p 623/tcp -p 624/tcp -p 625/tcp -p 626/tcp -p 627/tcp -p 628/tcp -p 629/tcp -p 630/tcp -p 631/tcp -p 632/tcp -p 633/tcp -p 634/tcp -p 635/tcp -p 636/tcp -p 637/tcp -p 638/tcp -p 639/tcp -p 640/tcp -p 641/tcp -p 642/tcp -p 643/tcp -p 644/tcp -p 645/tcp -p 646/tcp -p 647/tcp -p 648/tcp -p 649/tcp -p 650/tcp -p 651/tcp -p 652/tcp -p 653/tcp -p 654/tcp -p 655/tcp -p 656/tcp -p 657/tcp -p 658/tcp -p 659/tcp -p 660/tcp -p 661/tcp -p 662/tcp -p 663/tcp -p 664/tcp -p 665/tcp -p 666/tcp -p 667/tcp -p 668/tcp -p 669/tcp -p 670/tcp -p 671/tcp -p 672/tcp -p 673/tcp -p 674/tcp -p 675/tcp -p 676/tcp -p 677/tcp -p 678/tcp -p 679/tcp -p 680/tcp -p 681/tcp -p 682/tcp -p 683/tcp -p 684/tcp -p 685/tcp -p 686/tcp -p 687/tcp -p 688/tcp -p 689/tcp -p 690/tcp -p 691/tcp -p 692/tcp -p 693/tcp -p 694/tcp -p 695/tcp -p 696/tcp -p 697/tcp -p 698/tcp -p 699/tcp -p 700/tcp -p 701/tcp -p 702/tcp -p 703/tcp -p 704/tcp -p 705/tcp -p 706/tcp -p 707/tcp -p 708/tcp -p 709/tcp -p 710/tcp -p 711/tcp -p 712/tcp -p 713/tcp -p 714/tcp -p 715/tcp -p 716/tcp -p 717/tcp -p 718/tcp -p 719/tcp -p 720/tcp -p 721/tcp -p 722/tcp -p 723/tcp -p 724/tcp -p 725/tcp -p 726/tcp -p 727/tcp -p 728/tcp -p 729/tcp -p 730/tcp -p 731/tcp -p 732/tcp -p 733/tcp -p 734/tcp -p 735/tcp -p 736/tcp -p 737/tcp -p 738/tcp -p 739/tcp -p 740/tcp -p 741/tcp -p 742/tcp -p 743/tcp -p 744/tcp -p 745/tcp -p 746/tcp -p 747/tcp -p 748/tcp -p 749/tcp -p 750/tcp -p 751/tcp -p 752/tcp -p 753/tcp -p 754/tcp -p 755/tcp -p 756/tcp -p 757/tcp -p 758/tcp -p 759/tcp -p 760/tcp -p 761/tcp -p 762/tcp -p 763/tcp -p 764/tcp -p 765/tcp -p 766/tcp -p 767/tcp -p 768/tcp -p 769/tcp -p 770/tcp -p 771/tcp -p 772/tcp -p 773/tcp -p 774/tcp -p 775/tcp -p 776/tcp -p 777/tcp -p 778/tcp -p 779/tcp -p 780/tcp -p 781/tcp -p 782/tcp -p 783/tcp -p 784/tcp -p 785/tcp -p 786/tcp -p 787/tcp -p 788/tcp -p 789/tcp -p 790/tcp -p 791/tcp -p 792/tcp -p 793/tcp -p 794/tcp -p 795/tcp -p 796/tcp -p 797/tcp -p 798/tcp -p 799/tcp -p 800/tcp -p 801/tcp -p 802/tcp -p 803/tcp -p 804/tcp -p 805/tcp -p 806/tcp -p 807/tcp -p 808/tcp -p 809/tcp -p 810/tcp -p 811/tcp -p 812/tcp -p 813/tcp -p 814/tcp -p 815/tcp -p 816/tcp -p 817/tcp -p 818/tcp -p 819/tcp -p 820/tcp -p 821/tcp -p 822/tcp -p 823/tcp -p 824/tcp -p 825/tcp -p 826/tcp -p 827/tcp -p 828/tcp -p 829/tcp -p 830/tcp -p 831/tcp -p 832/tcp -p 833/tcp -p 834/tcp -p 835/tcp -p 836/tcp -p 837/tcp -p 838/tcp -p 839/tcp -p 840/tcp -p 841/tcp -p 842/tcp -p 843/tcp -p 844/tcp -p 845/tcp -p 846/tcp -p 847/tcp -p 848/tcp -p 849/tcp -p 850/tcp -p 851/tcp -p 852/tcp -p 853/tcp -p 854/tcp -p 855/tcp -p 856/tcp -p 857/tcp -p 858/tcp -p 859/tcp -p 860/tcp -p 861/tcp -p 862/tcp -p 863/tcp -p 864/tcp -p 865/tcp -p 866/tcp -p 867/tcp -p 868/tcp -p 869/tcp -p 870/tcp -p 871/tcp -p 872/tcp -p 873/tcp -p 874/tcp -p 875/tcp -p 876/tcp -p 877/tcp -p 878/tcp -p 879/tcp -p 880/tcp -p 881/tcp -p 882/tcp -p 883/tcp -p 884/tcp -p 885/tcp -p 886/tcp -p 887/tcp -p 888/tcp -p 889/tcp -p 890/tcp -p 891/tcp -p 892/tcp -p 893/tcp -p 894/tcp -p 895/tcp -p 896/tcp -p 897/tcp -p 898/tcp -p 899/tcp -p 900/tcp -p 901/tcp -p 902/tcp -p 903/tcp -p 904/tcp -p 905/tcp -p 906/tcp -p 907/tcp -p 908/tcp -p 909/tcp -p 910/tcp -p 911/tcp -p 912/tcp -p 913/tcp -p 914/tcp -p 915/tcp -p 916/tcp -p 917/tcp -p 918/tcp -p 919/tcp -p 920/tcp -p 921/tcp -p 922/tcp -p 923/tcp -p 924/tcp -p 925/tcp -p 926/tcp -p 927/tcp -p 928/tcp -p 929/tcp -p 930/tcp -p 931/tcp -p 932/tcp -p 933/tcp -p 934/tcp -p 935/tcp -p 936/tcp -p 937/tcp -p 938/tcp -p 939/tcp -p 940/tcp -p 941/tcp -p 942/tcp -p 943/tcp -p 944/tcp -p 945/tcp -p 946/tcp -p 947/tcp -p 948/tcp -p 949/tcp -p 950/tcp -p 951/tcp -p 952/tcp -p 953/tcp -p 954/tcp -p 955/tcp -p 956/tcp -p 957/tcp -p 958/tcp -p 959/tcp -p 960/tcp -p 961/tcp -p 962/tcp -p 963/tcp -p 964/tcp -p 965/tcp -p 966/tcp -p 967/tcp -p 968/tcp -p 969/tcp -p 970/tcp -p 971/tcp -p 972/tcp -p 973/tcp -p 974/tcp -p 975/tcp -p 976/tcp -p 977/tcp -p 978/tcp -p 979/tcp -p 980/tcp -p 981/tcp -p 982/tcp -p 983/tcp -p 984/tcp -p 985/tcp -p 986/tcp -p 987/tcp -p 988/tcp -p 989/tcp -p 990/tcp -p 991/tcp -p 992/tcp -p 993/tcp -p 994/tcp -p 995/tcp -p 996/tcp -p 997/tcp -p 998/tcp -p 999/tcp -p 200/udp -p 201/udp -p 202/udp -p 203/udp -p 204/udp -p 205/udp -p 206/udp -p 207/udp -p 208/udp -p 209/udp -p 210/udp -p 211/udp -p 212/udp -p 213/udp -p 214/udp -p 215/udp -p 216/udp -p 217/udp -p 218/udp -p 219/udp -p 220/udp -p 221/udp -p 222/udp -p 223/udp -p 224/udp -p 225/udp -p 226/udp -p 227/udp -p 228/udp -p 229/udp -p 230/udp -p 231/udp -p 232/udp -p 233/udp -p 234/udp -p 235/udp -p 236/udp -p 237/udp -p 238/udp -p 239/udp -p 240/udp -p 241/udp -p 242/udp -p 243/udp -p 244/udp -p 245/udp -p 246/udp -p 247/udp -p 248/udp -p 249/udp -p 250/udp -p 251/udp -p 252/udp -p 253/udp -p 254/udp -p 255/udp -p 256/udp -p 257/udp -p 258/udp -p 259/udp -p 260/udp -p 261/udp -p 262/udp -p 263/udp -p 264/udp -p 265/udp -p 266/udp -p 267/udp -p 268/udp -p 269/udp -p 270/udp -p 271/udp -p 272/udp -p 273/udp -p 274/udp -p 275/udp -p 276/udp -p 277/udp -p 278/udp -p 279/udp -p 280/udp -p 281/udp -p 282/udp -p 283/udp -p 284/udp -p 285/udp -p 286/udp -p 287/udp -p 288/udp -p 289/udp -p 290/udp -p 291/udp -p 292/udp -p 293/udp -p 294/udp -p 295/udp -p 296/udp -p 297/udp -p 298/udp -p 299/udp -p 300/udp -p 301/udp -p 302/udp -p 303/udp -p 304/udp -p 305/udp -p 306/udp -p 307/udp -p 308/udp -p 309/udp -p 310/udp -p 311/udp -p 312/udp -p 313/udp -p 314/udp -p 315/udp -p 316/udp -p 317/udp -p 318/udp -p 319/udp -p 320/udp -p 321/udp -p 322/udp -p 323/udp -p 324/udp -p 325/udp -p 326/udp -p 327/udp -p 328/udp -p 329/udp -p 330/udp -p 331/udp -p 332/udp -p 333/udp -p 334/udp -p 335/udp -p 336/udp -p 337/udp -p 338/udp -p 339/udp -p 340/udp -p 341/udp -p 342/udp -p 343/udp -p 344/udp -p 345/udp -p 346/udp -p 347/udp -p 348/udp -p 349/udp -p 350/udp -p 351/udp -p 352/udp -p 353/udp -p 354/udp -p 355/udp -p 356/udp -p 357/udp -p 358/udp -p 359/udp -p 360/udp -p 361/udp -p 362/udp -p 363/udp -p 364/udp -p 365/udp -p 366/udp -p 367/udp -p 368/udp -p 369/udp -p 370/udp -p 371/udp -p 372/udp -p 373/udp -p 374/udp -p 375/udp -p 376/udp -p 377/udp -p 378/udp -p 379/udp -p 380/udp -p 381/udp -p 382/udp -p 383/udp -p 384/udp -p 385/udp -p 386/udp -p 387/udp -p 388/udp -p 389/udp -p 390/udp -p 391/udp -p 392/udp -p 393/udp -p 394/udp -p 395/udp -p 396/udp -p 397/udp -p 398/udp -p 399/udp -p 400/udp -p 401/udp -p 402/udp -p 403/udp -p 404/udp -p 405/udp -p 406/udp -p 407/udp -p 408/udp -p 409/udp -p 410/udp -p 411/udp -p 412/udp -p 413/udp -p 414/udp -p 415/udp -p 416/udp -p 417/udp -p 418/udp -p 419/udp -p 420/udp -p 421/udp -p 422/udp -p 423/udp -p 424/udp -p 425/udp -p 426/udp -p 427/udp -p 428/udp -p 429/udp -p 430/udp -p 431/udp -p 432/udp -p 433/udp -p 434/udp -p 435/udp -p 436/udp -p 437/udp -p 438/udp -p 439/udp -p 440/udp -p 441/udp -p 442/udp -p 443/udp -p 444/udp -p 445/udp -p 446/udp -p 447/udp -p 448/udp -p 449/udp -p 450/udp -p 451/udp -p 452/udp -p 453/udp -p 454/udp -p 455/udp -p 456/udp -p 457/udp -p 458/udp -p 459/udp -p 460/udp -p 461/udp -p 462/udp -p 463/udp -p 464/udp -p 465/udp -p 466/udp -p 467/udp -p 468/udp -p 469/udp -p 470/udp -p 471/udp -p 472/udp -p 473/udp -p 474/udp -p 475/udp -p 476/udp -p 477/udp -p 478/udp -p 479/udp -p 480/udp -p 481/udp -p 482/udp -p 483/udp -p 484/udp -p 485/udp -p 486/udp -p 487/udp -p 488/udp -p 489/udp -p 490/udp -p 491/udp -p 492/udp -p 493/udp -p 494/udp -p 495/udp -p 496/udp -p 497/udp -p 498/udp -p 499/udp -p 500/udp -p 501/udp -p 502/udp -p 503/udp -p 504/udp -p 505/udp -p 506/udp -p 507/udp -p 508/udp -p 509/udp -p 510/udp -p 511/udp -p 512/udp -p 513/udp -p 514/udp -p 515/udp -p 516/udp -p 517/udp -p 518/udp -p 519/udp -p 520/udp -p 521/udp -p 522/udp -p 523/udp -p 524/udp -p 525/udp -p 526/udp -p 527/udp -p 528/udp -p 529/udp -p 530/udp -p 531/udp -p 532/udp -p 533/udp -p 534/udp -p 535/udp -p 536/udp -p 537/udp -p 538/udp -p 539/udp -p 540/udp -p 541/udp -p 542/udp -p 543/udp -p 544/udp -p 545/udp -p 546/udp -p 547/udp -p 548/udp -p 549/udp -p 550/udp -p 551/udp -p 552/udp -p 553/udp -p 554/udp -p 555/udp -p 556/udp -p 557/udp -p 558/udp -p 559/udp -p 560/udp -p 561/udp -p 562/udp -p 563/udp -p 564/udp -p 565/udp -p 566/udp -p 567/udp -p 568/udp -p 569/udp -p 570/udp -p 571/udp -p 572/udp -p 573/udp -p 574/udp -p 575/udp -p 576/udp -p 577/udp -p 578/udp -p 579/udp -p 580/udp -p 581/udp -p 582/udp -p 583/udp -p 584/udp -p 585/udp -p 586/udp -p 587/udp -p 588/udp -p 589/udp -p 590/udp -p 591/udp -p 592/udp -p 593/udp -p 594/udp -p 595/udp -p 596/udp -p 597/udp -p 598/udp -p 599/udp -p 600/udp -p 601/udp -p 602/udp -p 603/udp -p 604/udp -p 605/udp -p 606/udp -p 607/udp -p 608/udp -p 609/udp -p 610/udp -p 611/udp -p 612/udp -p 613/udp -p 614/udp -p 615/udp -p 616/udp -p 617/udp -p 618/udp -p 619/udp -p 620/udp -p 621/udp -p 622/udp -p 623/udp -p 624/udp -p 625/udp -p 626/udp -p 627/udp -p 628/udp -p 629/udp -p 630/udp -p 631/udp -p 632/udp -p 633/udp -p 634/udp -p 635/udp -p 636/udp -p 637/udp -p 638/udp -p 639/udp -p 640/udp -p 641/udp -p 642/udp -p 643/udp -p 644/udp -p 645/udp -p 646/udp -p 647/udp -p 648/udp -p 649/udp -p 650/udp -p 651/udp -p 652/udp -p 653/udp -p 654/udp -p 655/udp -p 656/udp -p 657/udp -p 658/udp -p 659/udp -p 660/udp -p 661/udp -p 662/udp -p 663/udp -p 664/udp -p 665/udp -p 666/udp -p 667/udp -p 668/udp -p 669/udp -p 670/udp -p 671/udp -p 672/udp -p 673/udp -p 674/udp -p 675/udp -p 676/udp -p 677/udp -p 678/udp -p 679/udp -p 680/udp -p 681/udp -p 682/udp -p 683/udp -p 684/udp -p 685/udp -p 686/udp -p 687/udp -p 688/udp -p 689/udp -p 690/udp -p 691/udp -p 692/udp -p 693/udp -p 694/udp -p 695/udp -p 696/udp -p 697/udp -p 698/udp -p 699/udp -it <nginix image>
```
2. Need to stop the container and run this command multiple times if the issue is not seen

### Describe the results you received

Run container fails as the port was already in use and podman assigned a used port to the container port.

### Describe the results you expected

Container should be running without any issues.

### podman info output

```yaml
> podman info
host:
  arch: amd64
  buildahVersion: 1.37.2
  cgroupControllers:
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-150500.9.9.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: unknown'
  cpuUtilization:
    idlePercent: 98.59
    systemPercent: 0.32
    userPercent: 1.09
  cpus: 24
  databaseBackend: sqlite
  distribution:
    distribution: opensuse-leap
    version: "15.6"
  eventLogger: file
  freeLocks: 2018
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.4.0-150600.23.14-default
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 35368890368
  memTotal: 67075629056
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.11.0-150500.3.6.1.x86_64
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.11.0
    package: netavark-1.11.0-150500.3.6.1.x86_64
    path: /usr/lib/podman/netavark
    version: netavark 1.11.0
  ociRuntime:
    name: crun
    package: crun-1.15-1.1.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.15
      commit: e6eacaf4034e84185fd8780ac9262bbf57082278
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-20240821.1d6142f-1.1.x86_64
    version: |
      pasta 20240821.1d6142f-1.1
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-150600.1.5.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.3
  swapFree: 2147811328
  swapTotal: 2147811328
  uptime: 116h 16m 45.00s (Approximately 4.83 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.opensuse.org
  - registry.suse.com
  - docker.io
store:
  configFile: /home/madhankumar/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/madhankumar/.local/share/containers/storage
  graphRootAllocated: 1021788028928
  graphRootUsed: 164027035648
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 230
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/madhankumar/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.2
  Built: 1724314016
  BuiltTime: Thu Aug 22 13:36:56 2024
  GitCommit: ""
  GoVersion: go1.22.6
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

> cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.6"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.6"
PRETTY_NAME="openSUSE Leap 15.6"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.6"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment] 2024-09-16 13:05
I ran this in a type loop 100 times and was not able to trigger it. I do notice I have a slightly newer pasta however.

```
baude@fedora podman (main) $ rpm -qf /usr/bin/pasta
passt-0^20240906.g6b38f07-1.fc40.x86_64
baude@fedora podman (main) $ pasta --version
pasta 0^20240906.g6b38f07-1.fc40.x86_64
```

**Comment by Luap99** [comment] 2024-09-16 13:15
This is basically a duplicate of https://github.com/containers/podman/issues/10205 (just different symptom to trigger it), see https://github.com/containers/podman/issues/10205#issuecomment-1010055023
The main issue is that we assign random ports on create time and then when the processes actually binds it might already be used. As pointed out there fixing this is non trivial as it must work with all our different port forwarders which is a lot of work.

**Closed by Luap99** 2024-09-16 13:15 UTC
Labels: kind/bug
