### ISSUE TITLE
"layer not known" transient error after interrupting a pull

### ISSUE THREAD

**Issue by martinetd** [containers/podman#9588] opened 2021-03-03 04:49 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Follow-up on #8148 : with today's master, the error is now transient, but it's still scary to unaware users so simple ^C should probably not cause this.
As said there it's more of an UX issue than an actual problem

**Steps to reproduce the issue:**

1. alternate between podman pull smth, interrupting it, and rmi the freshly fetched image. Full reproducer in https://github.com/containers/podman/issues/8148#issuecomment-788467263

**Describe the results you received:**
Sometimes get this error (only once, state fixes itself after running it)
```
$ ./bin/podman --root /tmp/podmanroot rmi localhost:5000/a:2
WARN[0000] Top layer ca84fd7b90547cb7f2b5adf21c4d5270becc15b855548277feccb31732917e8f of image e1b17d5af16529f22664f6c8f7328cad67bf10e3cabe9f7e13d75f14b992d7a2 not found in layer tree. The storage may be corrupted, consider running `podman system reset`. 
WARN[0000] Layer ca84fd7b90547cb7f2b5adf21c4d5270becc15b855548277feccb31732917e8f not found in layer. The storage may be corrupted, consider running `podman system reset`. 
WARN[0000] Top layer ca84fd7b90547cb7f2b5adf21c4d5270becc15b855548277feccb31732917e8f of image e1b17d5af16529f22664f6c8f7328cad67bf10e3cabe9f7e13d75f14b992d7a2 not found in layer tree. The storage may be corrupted, consider running `podman system reset`. 
WARN[0000] Layer ca84fd7b90547cb7f2b5adf21c4d5270becc15b855548277feccb31732917e8f not found in layer. The storage may be corrupted, consider running `podman system reset`. 
Error: 1 error occurred:
	* layer not known
```

**Describe the results you expected:**

pull should not be able to leave the directory in that state? I don't know.

**Comment by rhatdan** [comment] 2021-03-03 20:42
@umohnani8 Just fixed this in container storage, I believe.  Urvashi can you confirm?

**Comment by umohnani8** [comment] 2021-03-03 20:54
This looks different, I fixed the symlinks not found issue. This actually may be fixed by the pull improvements that @vrothberg is working on?

**Comment by vrothberg** [comment] 2021-03-04 10:19
The pull improvement won't help in this case.  The problem is that `rmi` needs to (still) be made more robust against a corrupted storage.

**Comment by vrothberg** [comment] 2021-03-04 13:03
https://github.com/containers/podman/pull/9617 is (hopefully) the last missing piece.  We already ignored unknown-image errors so it seems logical to extend it to ignore unknown-layer errors as well - those may be caused by an incomplete pull/commit.

**Comment by martinetd** [comment] 2021-03-04 13:10
Thanks! I'll test tomorrow

**Closed** 2021-03-04 15:16 UTC
Labels: kind/bug

**Comment by martinetd** [comment] 2021-03-08 01:00
tomorrow got a bit late, here's what it looks like now:
```
$ ./bin/podman --root /tmp/podmanroot pull localhost:5000/a:2
Trying to pull localhost:5000/a:2...
Getting image source signatures
Copying blob fc87b077f4bb skipped: already exists  
Copying blob 353a677e0e56 done  
Copying config e1b17d5af1 done  
Writing manifest to image destination
Storing signatures
^C
$ ./bin/podman --root /tmp/podmanroot rmi localhost:5000/a:2
WARN[0000] Top layer ca84fd7b90547cb7f2b5adf21c4d5270becc15b855548277feccb31732917e8f of image e1b17d5af16529f22664f6c8f7328cad67bf10e3cabe9f7e13d75f14b992d7a2 not found in layer tree. The storage may be corrupted, consider running `podman system reset`. 
WARN[0000] Layer ca84fd7b90547cb7f2b5adf21c4d5270becc15b855548277feccb31732917e8f not found in layer. The storage may be corrupted, consider running `podman system reset`. 
WARN[0000] Top layer ca84fd7b90547cb7f2b5adf21c4d5270becc15b855548277feccb31732917e8f of image e1b17d5af16529f22664f6c8f7328cad67bf10e3cabe9f7e13d75f14b992d7a2 not found in layer tree. The storage may be corrupted, consider running `podman system reset`. 
WARN[0000] Layer ca84fd7b90547cb7f2b5adf21c4d5270becc15b855548277feccb31732917e8f not found in layer. The storage may be corrupted, consider running `podman system reset`. 
Untagged: e1b17d5af16529f22664f6c8f7328cad67bf10e3cabe9f7e13d75f14b992d7a2
Deleted: e1b17d5af16529f22664f6c8f7328cad67bf10e3cabe9f7e13d75f14b992d7a2

$ echo $?
0
```

So the hard error is gone; I guess it's fair to keep showing the warnings. Thanks!

**Comment by vrothberg** [comment] 2021-03-08 08:15
@martinetd, thanks a lot for sharing and for your patience.  I appreciate your feedback and interactions!
