### ISSUE TITLE
 Bug: Errors when using rootless containers

### ISSUE THREAD

**Issue by daniel-wtd** [containers/podman#6090] opened 2020-05-05 14:43 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hi,

when running rootless containers, I am getting some errors:

```
podman run -dt -p 8080:80 docker.io/library/httpd:2.4
ERRO[0000] unable to write pod event: "open : no such file or directory" 
ERRO[0000] unable to write pod event: "open : no such file or directory" 
ERRO[0000] unable to write pod event: "open : no such file or directory"
```

These kind of errors occur for several subcommands like: run, stop, start, restart
Other subcommands like "ps" seem not to be affected.
Disabling SELinux does not help to prevent the errors.

## information

OS: Fedora 32 Silverblue
Podman: 1.9.1

If you need any additional information, please feel free to reach out to me.

**Comment by mheon** [comment] 2020-05-05 15:50
@rhatdan Looks like containers.conf again.

@daniel-wtd Can you provide your `~/.config/containers/libpod.conf`

**Comment by daniel-wtd** [comment] 2020-05-05 16:02
@mheon sure:

```
volume_path = "/var/home/dschier/.local/share/containers/storage/volumes"
image_default_transport = "docker://"
runtime = "crun"
runtime_supports_json = ["crun", "runc"]
runtime_supports_nocgroups = ["crun"]
conmon_path = ["/usr/libexec/podman/conmon", "/usr/local/libexec/podman/conmon", "/usr/local/lib/podman/conmon", "/usr/bin/conmon", "/usr/sbin/conmon", "/usr/local/bin/conmon", "/usr/local/sbin/conmon", "/run/current-system/sw/bin/conmon"]
conmon_env_vars = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]
cgroup_manager = "systemd"
init_path = ""
static_dir = "/var/home/dschier/.local/share/containers/storage/libpod"
tmp_dir = "/run/user/1000/libpod/tmp"
max_log_size = -1
no_pivot_root = false
cni_config_dir = "/etc/cni/net.d/"
cni_plugin_dir = ["/usr/libexec/cni", "/usr/lib/cni", "/usr/local/lib/cni", "/opt/cni/bin"]
infra_image = "k8s.gcr.io/pause:3.1"
infra_command = "/pause"
enable_port_reservation = true
label = true
network_cmd_path = ""
num_locks = 2048
lock_type = "shm"
events_logger = "journald"
events_logfile_path = ""
detach_keys = "ctrl-p,ctrl-q"
SDNotify = false
cgroup_check = true

[runtimes]
  crun = ["/usr/bin/crun", "/usr/local/bin/crun"]
  runc = ["/usr/bin/runc", "/usr/sbin/runc", "/usr/local/bin/runc", "/usr/local/sbin/runc", "/sbin/runc", "/bin/runc", "/usr/lib/cri-o-runc/sbin/runc", "/run/current-system/sw/bin/runc"]
```

**Comment by mheon** [comment] 2020-05-05 16:52
I know we're now ignoring `events_logger` which is probably why we're forcing file...

@daniel-wtd Can you remove the `events_logfile_path = ""` line and see if the errors go away? I suspect we're going to have to ignore that setting as well if it's explicitly set to `""`

**Comment by daniel-wtd** [comment] 2020-05-05 16:55
@mheon I can confirm commenting or removing the lines does the trick.

**Comment by rhatdan** [comment] 2020-05-06 01:40
If you did not modify libpod.conf, it is probably best to remove the file.

**Comment by HarryMichal** [comment] 2020-05-07 20:56
I also experience the same issue. I successfully started a few containers and then the issue appeared. I did not edit libpod.conf. Removing the file fixed it.

System: Fedora Silverblue 32
Versions: 1.9.1

**Comment by junjieyuan** [comment] 2020-05-09 14:02
And podman will create an empty ".lock" file in $PWD.

**Comment by bkircher** [comment] 2020-05-15 18:48
Can confirm. .lock file is created in $PWD and just removing $HOME/.config/containers/libpod.conf does the trick.

**Comment by mheon** [comment] 2020-06-02 16:12
I think we need this fixed for v2.0, to make sure that upgrades from older Podmans do not blow up.

**Comment by rhatdan** [comment] 2020-07-06 14:33
@bkircher @mheon Was this fixed in 2.0?  Can I close this?

**Comment by mheon** [comment] 2020-07-06 14:36
This is not fixed.

**Comment by vrothberg** [comment] 2020-09-10 12:07
@mheon, did we fix it? Is the crux of the matter the libpod.conf?

**Comment by mheon** [comment] 2020-09-10 12:18
I do not recall anyone fixing this, but at the same time I have not heard any reports of it for two months.

**Comment by daniel-wtd** [comment] 2020-09-10 12:21
At least, I cannot reproduce it in 2.0+

**Comment by vrothberg** [comment] 2020-09-10 12:26
I couldn't reproduce either. I'll close but please drop a comment or reopen if it pops up.

**Closed by vrothberg** 2020-09-10 12:26 UTC
Labels: Needed for V2, kind/bug, rootless
