### ISSUE TITLE
Create a amd64 qemu machine on Macbook M1

### ISSUE THREAD

**Issue by sanyer** [containers/podman#14101] opened 2022-05-03 18:30 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Since it is possible to create amd64 qemu vm on Macbook M1, how about teaching podman machine to do it?
Sometimes needed image doesn't have a aarch64 version, so having a amd64 podman machine would be a really beneficial.

I tried it a bit myself by modifying existing podman machine `/.config/containers/podman/machine/qemu/podman-machine-default.json` file and was able to get machine started, but not connected to podman. But I'm sure it should be possible to do.

**Comment by Luap99** [comment] 2022-05-04 11:53
Duplicate of #11458

**Closed by Luap99** 2022-05-04 11:53 UTC
Labels: kind/feature
