### ISSUE TITLE
container status not refresh

### ISSUE THREAD

**Issue by Taymindis** [containers/podman#15849] opened 2022-09-18 04:42 UTC
Linux or Mac version

**Steps to reproduce the issue:**

1. podman run --name abc -d busybox

2. podman rm -f abc

3. podman run --name abc -d busybox

Version:      4.2.0

```
676d75793101  docker.io/library/busybox:latest           sh                    35 minutes ago  Exited (0) 34 minutes ago                                                                                              abc
```

It always showing the first podman machine started time.

**Comment by giuseppe** [comment] 2022-09-19 07:16
I cannot reproduce here:

```
$ podman run --name abc -d busybox
d429b540b90b784fce38d8cd7721e404cda3f03503fdcf6eac2351a84d9ad75f
$ podman rm -f abc
d429b540b90b784fce38d8cd7721e404cda3f03503fdcf6eac2351a84d9ad75f
$ podman run --name abc -d busybox
6ad60bbcf51a467de6a46a797682fa980c68ff0a7a63713a304fde5302f839c5
$ podman ps -a
CONTAINER ID  IMAGE                             COMMAND     CREATED        STATUS                    PORTS       NAMES
6ad60bbcf51a  docker.io/library/busybox:latest  sh          2 seconds ago  Exited (0) 3 seconds ago              abc
```

Can you show the output for that same commands?

**Comment by Taymindis** [comment] 2022-09-19 07:51
<img width="715" alt="image" src="https://user-images.githubusercontent.com/14217761/190972388-39c28e0b-c073-4c83-b430-1f56981d3837.png">

**Comment by mheon** [comment] 2022-09-19 13:31
Are we sure it isn't the time on the machine that's incorrect, here? Podman just sends the timestamps for when the container was started across the network, not the actual "41 minutes ago" text, so if the server's clock is 41 minutes slow, this result makes sense, and we have known issues with clock drift on `podman machine` VMs

**Comment by mheon** [comment] 2022-09-21 12:32
Can you check if the time on the `podman machine` VM is correct? `podman machine ssh` should let you run the `date` command in the VM and verify.

**Comment by Taymindis** [comment] 2022-09-22 03:30
Seemed like issue cannot reproduce when I'am using development office network. So the problem is come to my server network time zone? What can I do

![image](https://user-images.githubusercontent.com/14217761/191651636-893e88b0-68ff-4b00-9ab0-3a191467a565.png)

![image](https://user-images.githubusercontent.com/14217761/191651803-61c74811-fec8-4f24-901b-dc17491d64d1.png)

**Comment by Taymindis** [comment] 2022-09-22 07:52
![image](https://user-images.githubusercontent.com/14217761/191686992-884c004f-412b-413e-9a3d-16929cc9be9c.png)



Machine time out of sync

**Comment by rhatdan** [comment] 2022-09-22 10:16
This is a known problem.  Lots of people are discussing how to fix it. Basically when laptop goes to sleep, qemu VM does not know about a time shift when machine wakes up.

**Comment by rhatdan** [comment] 2023-07-30 09:53
@ashley-cui @vrothberg @baude @Luap99 Any update on this problem?

**Comment by Luap99** [comment] 2023-07-31 08:44
VM time-drift was fixed in https://github.com/containers/podman/commit/9ac0d4f1a69e74f25ef41c88a1c1378fa333c19e AFAIK, so it should not happen if you create a new machine.

**Closed by Luap99** 2023-07-31 08:44 UTC
Labels: podman machine
