### ISSUE TITLE
podman is not requesting the right scope for the catalog during search

### ISSUE THREAD

**Issue by anderbubble** [containers/podman#15704] opened 2022-09-08 19:22 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When attempting to use `podman search` to list the containers in a Keycloak-authenticated registry, podman fails with an error.

**Steps to reproduce the issue:**

1. Stand up a kubernetes container registry using Keycloak for authentication.

2. Log into the registry.

3. Push a container to the registry.

4. Attempt to see the container with a search.

**Describe the results you received:**

```console
$ podman login --tls-verify=false https://registry.[redacted].nip.io
Username: [redacted]
Password: 
Login Succeeded!
$ podman search --tls-verify=false registry.[redacted].nip.io/[redacted]
ERRO[0003] error getting search results from v2 endpoint "registry.[redacted].nip.io": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required 
Error: 1 error occurred:
	* couldn't search registry "registry.[redacted].nip.io": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

**Describe the results you expected:**

A list of the available containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens consistently on both EL8.6 and Fedora 37 versions.

```console
$ podman search --tls-verify=false registry.[redacted].nip.io:80/ --log-level=debug
...
DEBU[0000] Found credentials for registry.[redacted].nip.io:80 in credential helper containers-auth.json in file /run/user/1000/containers/auth.json 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/registry.[redacted].nip.io:80 
DEBU[0000] trying to talk to v2 search endpoint         
DEBU[0000] GET https://registry.[redacted].nip.io:80/v2/ 
DEBU[0000] Ping https://registry.[redacted].nip.io:80/v2/ err Get "https://registry.[redacted].nip.io:80/v2/": http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://registry.[redacted].nip.io:80/v2/", Err:(*errors.errorString)(0xc0008aea60)}) 
DEBU[0000] GET http://registry.[redacted].nip.io:80/v2/ 
DEBU[0000] Ping http://registry.[redacted].nip.io:80/v2/ status 401 
DEBU[0000] GET https://auth.[redacted].nip.io/auth/realms/[redacted]/protocol/docker-v2/auth?account=[redacted]-admin&service=DockerRegistry 
DEBU[0000] GET http://registry.[redacted].nip.io:80/v2/_catalog 
ERRO[0000] error getting search results from v2 endpoint "registry.[redacted].nip.io:80": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required 
Error: 1 error occurred:
	* couldn't search registry "registry.[redacted].nip.io:80": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

As tcpdump show (this is the packets for the ping line above Ping http://registry.[redacted].nip.io:80/v2/ status 401 ): 

```
GET /v2/ HTTP/1.1
Host: registry.[redacted].nip.io:80
User-Agent: containers/5.21.1 (github.com/containers/image)
Docker-Distribution-Api-Version: registry/2.0
Accept-Encoding: gzip
Connection: close
13:18:32.097069 IP 10.240.0.100.http > 10.240.0.36.35710: Flags [.], ack 211, win 235, options [nop,nop,TS val 1996761404 ecr 3863276933], length 0
13:18:32.098923 IP 10.240.0.100.http > 10.240.0.36.35710: Flags [P.], seq 1:525, ack 211, win 235, options [nop,nop,TS val 1996761406 ecr 3863276933], length 524: HTTP: HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Content-Length: 87
Connection: close
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.[redacted].nip.io/auth/realms/[redacted]/protocol/docker-v2/auth",service="DockerRegistry"
X-Content-Type-Options: nosniff
Date: Mon, 05 Sep 2022 13:18:32 GMT
X-Kong-Upstream-Latency: 2
X-Kong-Proxy-Latency: 0
Via: kong/2.8.1
```

At this time podman is requesting a token to https://auth.[redacted].nip.io/auth/realms/[redacted]/protocol/docker-v2/auth", note that there is no scope, the issue is that podman is keeping the token for the request to /v2/_catalog like tcpdump log shown in these packets : 

```
GET /v2/_catalog HTTP/1.1
Host: registry.[redacted].nip.io:80
User-Agent: containers/5.21.1 (github.com/containers/image)
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3RDVVOjVRUzI6WUNDQjpaT1I2Ok5JN086VkU2TDpJQlNCOlRJNlk6QVNIMzpNTkxVOkJTSFY6SkRNSCJ9.eyJleHAiOjE2NjI0NzAzMTIsIm5iZiI6MTY2MjM4MzkxMiwiaWF0IjoxNjYyMzgzOTEyLCJqdGkiOiJhZjY2YjI3YS1iMGY0LTQwNmMtOTk1Yi1jNTk3ODhkM2ZlOGIiLCJpc3MiOiJodHRwczovL2F1dGguMTAuMjQwLjAuMTAwLm5pcC5pby9hdXRoL3JlYWxtcy9DdHJsSVEiLCJhdWQiOiJEb2NrZXJSZWdpc3RyeSIsInN1YiI6ImZ1enpiYWxsLWFkbWluIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiRG9ja2VyUmVnaXN0cnkiLCJhY2Nlc3MiOltdfQ.Azmt5qJiESD2kJ4MFEgXdlUgRTgxZBRWzlh9_D1TWwpPc45e33bNSX28XTIMNqyYHK1acUNW15HUUbGFbNR5dluFK7PE6YZcsQKM-34OzNusTAOzZWEdRzU-8NzXyEQciBxM-8z3QortYbFhyInzs86GBKknWxLt86PojeYViufG_IGSrTL2_8ekhsao69i9AfKQj1Tju-7Mj5-Ti0-XAa4pbuEZdBjcx1CGUPu_w03CV2JEmyj_0ZdTQDdLBR-Q6akdJ1FYfJNbo8kp9cHL2Gak2wpG-o09NxxpTW4q84Ys6Eeci-9QiIBEFA9FwM1XIngAIgOOAsFdoE5z_bHFMA
Docker-Distribution-Api-Version: registry/2.0
Accept-Encoding: gzip
Connection: close
13:18:32.126589 IP 10.240.0.100.http > 10.240.0.36.35714: Flags [.], ack 1057, win 243, options [nop,nop,TS val 1478732270 ecr 3863276963], length 0
13:18:32.128169 IP 10.240.0.100.http > 10.240.0.36.35714: Flags [P.], seq 1:638, ack 1057, win 243, options [nop,nop,TS val 1478732272 ecr 3863276963], length 637: HTTP: HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Content-Length: 145
Connection: close
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.[redacted].nip.io/auth/realms/[redacted]/protocol/docker-v2/auth",service="DockerRegistry",scope="registry:catalog:*",error="insufficient_scope"
X-Content-Type-Options: nosniff
Date: Mon, 05 Sep 2022 13:18:32 GMT
X-Kong-Upstream-Latency: 1
X-Kong-Proxy-Latency: 0
Via: kong/2.8.1

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
```

Finally the registry send as part of the 401 response the right scope (scope="registry:catalog:*") that podman should ask with the token, but instead podman consider the credentials as not valid and abort without asking the new token with the right scope as expected.

**Output of `podman version`:**

```console
$ podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.12
Built:        Tue Aug  2 07:53:14 2022
OS/Arch:      linux/amd64
```

```console
$ podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 15 08:33:05 2022
OS/Arch:      linux/arm64
```

**Output of `podman info`:**

```console
$ podman info
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.2-2.module+el8.6.0+997+05c9d812.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: 98e028a5804809ccb49bc099c0d53adc43ef8cc4'
  cpuUtilization:
    idlePercent: 99.12
    systemPercent: 0.21
    userPercent: 0.67
  cpus: 1
  distribution:
    distribution: '"rocky"'
    version: "8.6"
  eventLogger: file
  hostname: [redacted]
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-372.19.1.el8_6.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 438095872
  memTotal: 2068545536
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.3-2.module+el8.6.0+997+05c9d812.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.3
      spec: 1.0.2-dev
      go: go1.17.12
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.6.0+997+05c9d812.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 6182666240
  swapTotal: 6291451904
  uptime: 42h 59m 55.53s (Approximately 1.75 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/iqube/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/iqube/.local/share/containers/storage
  graphRootAllocated: 64385212416
  graphRootUsed: 18741260288
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/iqube/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1659426794
  BuiltTime: Tue Aug  2 07:53:14 2022
  GitCommit: ""
  GoVersion: go1.17.12
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```console
$ rpm -q podman
podman-4.1.1-2.module+el8.6.0+997+05c9d812.x86_64
```

```console
$ rpm -q podman
podman-4.1.1-1.fc36.aarch64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

I'm working on replicating with 4.2 from Fedora rawhide, currently building.

I don't see anything pertinent in the Troubleshooting Guide.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Both clients in a KVM environment; one was x86_64, the other aarch64.

**Comment by anderbubble** [comment] 2022-09-08 21:43
I just discovered that podman 4.2 is in fc36 now, so I went ahead and replicated the results with that. So I think this confirms the issue persists.

```
[janderson@fedora ~]$ podman version
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 08:43:11 2022
OS/Arch:      linux/arm64

[janderson@fedora ~]$ rpm -q podman
podman-4.2.0-2.fc36.aarch64
```

**Comment by vrothberg** [comment] 2022-09-09 07:43
Thanks for reaching out, @anderbubble!

@mtrmac PTAL

**Comment by mtrmac** [comment] 2022-09-09 13:39
This is very likely a duplicate of #13369, recently fixed in c/image https://github.com/containers/image/pull/1640 .

**Comment by rhatdan** [comment] 2022-09-09 14:12
So this should be fixed in podman 4.3 which is about to be cut for RC1.

**Comment by anderbubble** [comment] 2022-09-09 16:40
Great! As soon as that RC is released I'll try it out and report back.

**Comment by vrothberg** [comment] 2022-09-14 11:37
Closing as https://github.com/containers/image/pull/1640 has been merged into Podman.

**Closed by vrothberg** 2022-09-14 11:37 UTC
Labels: kind/bug

**Comment by anderbubble** [comment] 2022-09-23 15:28
@rhatdan where can I get the 4.3 RC1 to test this fix?

**Comment by rhatdan** [comment] 2022-09-23 15:34
Not being cut until Monday/Tuesday next week.

**Comment by HansVenema** [comment] 2023-01-12 07:26
Hi, is there any update on this? I also have this issue when using Harbor as registry. My podman version:
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.7
Built:        Wed Oct 26 21:23:47 2022
OS/Arch:      linux/amd64

**Comment by vrothberg** [comment] 2023-01-12 12:06
@HansVenema, you need to update to Podman v4.3 and above.

**Comment by HansVenema** [comment] 2023-01-12 12:36
Okay, thanks! I will ask my infrastructure department when the update is applied and test it again.
