### ISSUE TITLE
Podman info shows cgroup manager cgroupfs

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#9259] opened 2021-02-07 17:58 UTC
It's possible to configure different cgroup managers, systemd and cgroupfs for the root and rootless users. Is it really possible? /kind bug

1. Configure cgroup manager = systemd as by default
2. Ligin as root user
3. execute podman info - group manager is shown as systemd
4. Login as non-root user, i.e.pavel
5. exec podman info

**Describe the results you received:**

[pavel@MSI-wsl ~]$ podman info
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: cgroupfs
  cgroupVersion: v1

**Describe the results you expected:**

cgroupManager: systemd of course 

**Additional information you deem important (e.g. issue happens only occasionally):**
In the documentation cgroup manager is described as a global parameter. Hopefully it is true. What rootless user sees in the Podman info?

**Output of `podman version`:**

```
Version:      3.0.0-rc1
API Version:  3.0.0
Go Version:   go1.15.6
Built:        Mon Jan 18 18:07:50 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
rpm -q podman
podman-3.0.0-0.1.rc1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: MSI-wsl
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.91-microsoft-standard-WSL2

**Comment by gbraad** [comment] 2021-02-08 12:06
You are running WSL, so can you share the config you are using `/etc/containers/containers.conf` as the change to use `cgroupfs` is needed as WSL does not use systemd (but a simple init replacement when bash is started). If you are systemd how was this configured? or are you using podman-remote? Some information here is missing or confusing

**Comment by giuseppe** [comment] 2021-02-08 13:10
rootless on cgroupv1 cannot really use cgroups, it is not safe to delegate cgroup v1 to unprivileged users.

If you want to use cgroups as rootless user you need cgroup v2.

I am going to close the issue but feel free to add more comments

**Closed by giuseppe** 2021-02-08 13:10 UTC

**Comment by PavelSosin-320** [comment] 2021-02-08 15:08
@giuseppe The issue for me is that I use WSL Fedora33 distro tricked to use systemd. This required to start distro differently once in the "boot" mode using genie -s and then in the "login" mode via WT using genie -l . The cgroup manager is configured globally as systemd. But podman info shows different values for the root and non-root users. Everything else works as expected in the root and rootless mode but I would like to be sure that in both cases systemd is used as cgroup manager.

**Comment by giuseppe** [comment] 2021-02-09 08:19
how does "ls /sys/fs/cgroup"?  If the system is using cgroup v1 then rootless cannot use it (neither systemd or cgroupfs) and it just fallbacks to cgroupfs

**Comment by PavelSosin-320** [comment] 2021-02-09 17:19
It looks not bad:
[pavel@MSI-wsl ~]$ whoami
pavel
[pavel@MSI-wsl ~]$ ls -al /sys/fs/cgroup/
total 0
drwxr-xr-x 19 root root 380 Feb  8 09:53 .
drwxr-xr-x 10 root root   0 Feb  8 09:53 ..
dr-xr-xr-x  2 root root   0 Feb  8 09:53 blkio
dr-xr-xr-x  2 root root   0 Feb  8 09:53 cpu
drwxr-xr-x  2 root root  40 Feb  8 09:53 cpu,cpuacct
dr-xr-xr-x  2 root root   0 Feb  8 09:53 cpuacct
dr-xr-xr-x  2 root root   0 Feb  8 09:53 cpuset
dr-xr-xr-x  5 root root   0 Feb  8 09:53 devices
dr-xr-xr-x  2 root root   0 Feb  8 09:53 freezer
dr-xr-xr-x  2 root root   0 Feb  8 09:53 hugetlb
dr-xr-xr-x  6 root root   0 Feb  8 09:53 memory
dr-xr-xr-x  2 root root   0 Feb  8 09:53 net_cls
drwxr-xr-x  2 root root  40 Feb  8 09:53 net_cls,net_prio
dr-xr-xr-x  2 root root   0 Feb  8 09:53 net_prio
dr-xr-xr-x  2 root root   0 Feb  8 09:53 perf_event
dr-xr-xr-x  5 root root   0 Feb  8 09:53 pids
dr-xr-xr-x  2 root root   0 Feb  8 09:53 rdma
dr-xr-xr-x  6 root root   0 Feb  8 09:53 systemd
dr-xr-xr-x  6 root root   0 Feb  8 09:53 unified
[pavel@MSI-wsl ~]$
and 
[pavel@MSI-wsl ~]$ ls -al /sys/fs/cgroup/systemd/
total 0
dr-xr-xr-x  6 root root   0 Feb  8 09:53 .
drwxr-xr-x 19 root root 380 Feb  8 09:53 ..
-rw-r--r--  1 root root   0 Feb  9 19:14 cgroup.clone_children
-rw-r--r--  1 root root   0 Feb  9 19:14 cgroup.procs
-r--r--r--  1 root root   0 Feb  9 19:14 cgroup.sane_behavior
drwxr-xr-x  2 root root   0 Feb  8 09:53 init.scope
drwxr-xr-x  2 root root   0 Feb  9 19:14 machine.slice
-rw-r--r--  1 root root   0 Feb  9 19:14 notify_on_release
-rw-r--r--  1 root root   0 Feb  9 19:14 release_agent
drwxr-xr-x 20 root root   0 Feb  8 09:53 system.slice
-rw-r--r--  1 root root   0 Feb  9 19:14 tasks
drwxr-xr-x  4 root root   0 Feb  8 09:53 user.slice
Logind creates "systemd session". I use wsl .... genie -l  for rootless login. Otherwise, it doesn't work

**Comment by giuseppe** [comment] 2021-02-11 13:20
Thanks for confirming it, so the system is using cgroup v1.

> Does it mean that group manager configuration is silently ignored and Podman info shows the wrong value in both cases without warning?

it is just not used because it cannot use cgroup v1 with rootless.

**Comment by PavelSosin-320** [comment] 2021-02-11 15:15
I found that the following check confirms that cgroup v2 is supported:
grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
Dan Wallsh said that non-root users can use cgroup v2 starting from Fedora 32 about a year ago.
The real root causes may be:
1. I  [Fedora33 WSL distro from](https://fedoramagazine.org/wsl-fedora-33/)
2. Microsoft Kernel is 4 releases behind the Current stable 5.8. uname -a
Linux MSI-wsl 5.4.91-microsoft-standard-WSL2
I hope, that the 1st cause can be eliminated easily. But The 2nd can take a long time as usual.
I would like to discuss what can be done.

**Comment by giuseppe** [comment] 2021-02-12 15:16
I am not familiar with WSL, but you need to boot the system with cgroup v2 only, you may need to tweak the kernel command line for that.

The end result should be like:

```
$ stat -c '%T' -f /sys/fs/cgroup/
cgroup2fs
```

**Comment by gbraad** [comment] 2021-02-14 03:54
Without a clear description of how this was enabled on WSL, it would be hard to reproduce.
Especially as https://github.com/arkane-systems/genie/issues/98 does not provide a working setup from a base F33 import, adding groupinstall "Basic Desktop" to get systemd, etc. but this results in issues with policykit and dbus.

**Comment by PavelSosin-320** [comment] 2021-02-14 06:57
WSL (Windows Subsystem for Linux)  is the lightweight VM that allows running Linux distros inside Windows OS and can be enabled today even in OEM Windows Home edition. Microsoft resists enabling systemd  in WSL and insists that it doesn't work, can't work, and is not needed for Microsoft users. So it will be never implemented by Microsoft. In spite of this statement, systemd can be easily enabled cross-distro via the usage of [Arkane-system genie](https://github.com/arkane-systems/genie), a small package with the only dependency - Dotnet 5.0. Although it is dedicated to Debian its support is easily extendable to other Linux distros. 
To start Fedora distro with systemd I created Windows desktop shortcut wsl -d Fedora33 -u user root -s. It starts Fedora distro using systemd and opens the root user session in the command. To login as a rootless user I created the WT profile using WT settings:
{
        "guid": "{76ce0607-0119-4bc0-831c-6a367e162f43}",
        "hidden": false,
        "name": "Fedora33Usersession",
        "commandline": "wsl -d Fedora33 genie -l"
      } It initiates the regular Linux ligin with username and password.
In the Podman configuration, I changed group managed and eventlogger to systemd.
Upon installation of Podman 3.0 RC1 in my Fedora distro I tested various scenario and meanwhile this is the only critical issue I found.
The differences between Fedora33 with Podman 3 and Docker-for-Win are
1. Total Linux footprint < 150Mb vs ~4Gb
2. Startup time of the Fedora Distro with Podman and ~ 50 containers < 1sec vs Dcker-for-win startup 3-4 min.

**Comment by gbraad** [comment] 2021-02-14 07:25
I m not unfamiliar to WSL2. I used to work on the build for the Fedora project before the legal issues (indemnification) would prevent publication

I got the install for the WLS systemd working as described here: https://github.com/arkane-systems/genie/issues/98#issuecomment-778641443

**Comment by gbraad** [comment] 2021-02-14 07:31
Note:

> rootless
> `"wsl -d Fedora33 genie -l`

Shouldn't this be `wsl -d Fedora33 genie -s` and have a default user enabled be sufficient? The logon prompt seems like an unnecessary step.

**Comment by gbraad** [comment] 2021-02-14 07:57
> I am not familiar with WSL, but you need to boot the system with cgroup v2 only, you may need to tweak the kernel command line for that.

and that might be part of the issue. AFAIK you can only specify a custom kernel from the `.wslconfig` [ref](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig)

```
[wsl2]
kernel=C:\\temp\\myCustomKernel
```

and not arguments like `--args="systemd.unified_cgroup_hierarchy=1"` if not mistaken.

**Comment by gbraad** [comment] 2021-02-15 15:26
> Have to try kernelCommandLine and see if that works

had some time besides the 'mandatory family visits' (CNY), but setting the `kernelCommandline="systemd.unified_cgroup_hierarchy=1"` didn't do it.

**Comment by PavelSosin-320** [comment] 2021-02-16 18:44
@gbraad After some hustles with .wslconfig I succeeded to run Fedora with 
[wsl2]
memory=12GB
processors=4
kernelCommandLine=systemd.unified_cgroup_hierarchy=1

and this parameter reaches the destination:
cat /proc/cmdline
initrd=\initrd.img panic=-1 nr_cpus=4 swiotlb=force pty.legacy_count=0 systemd.unified_cgroup_hierarchy=1_

Now, according   to  [ RunC documentation](https://github.com/opencontainers/runc/blob/master/docs/cgroup-v2.md#cgroup-v2
) not CRun, used by Podman 3
nothing prevents  using systemd as cgroups manager if
1. CRun gets all necessary parameters_
     _--cgroup-manager=MANAGER   cgroup manager
      --debug                produce verbose output
      --log=FILE
      --log-format=FORMAT
      --root=DIR
      --rootless=VALUE
      --systemd-cgroup       use systemd cgroups_
      --cgroup-manager=MANAGER   cgroup manager
      --rootless=VALUE
      --systemd-cgroup       use systemd cgroups
2.  **Microsoft Kernel 5.4 really implements cgroups v2 api**

**Comment by gbraad** [comment] 2021-02-16 21:44
But, what does `podman info` show?

**Comment by PavelSosin-320** [comment] 2021-02-17 06:43
@jbraad. I see different things:
[root@MSI-wsl ~]# ps -ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 systemd
     21 ?        Ss     0:00 /usr/lib/systemd/systemd-journald
     27 ?        Ss     0:00 /usr/lib/systemd/systemd-resolved
     29 ?        Ss     0:00 /usr/lib/systemd/systemd-homed
     30 ?        Ss     0:00 /usr/lib/systemd/systemd-logind
     32 tty1     Ss+    0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 xterm-256color
     33 ?        Ss     0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux
     34 ?        Ss     0:00 /usr/bin/dbus-broker-launch --scope system --audit
     35 ?        Ss     0:00 /usr/lib/systemd/systemd-userdbd
     36 ?        S      0:00 dbus-broker --log 4 --controller 9 --machine-id c53a30ca9b1942819377b54eb6553043 --max-byte
     42 ?        Ss     0:00 /usr/lib/systemd/systemd-machined
     43 ?        Ss     0:00 /usr/lib/systemd/systemd --user
     44 pts/1    Ss     0:00 /bin/bash -l
     45 ?        S      0:00 (sd-pam)
     51 ?        Ss     0:00 /usr/lib/systemd/systemd --user
     52 ?        S      0:00 (sd-pam)
     61 pts/1    S      0:00 (sd-pam)
     82 ?        Ss     0:00 login -- pavel
     83 pts/3    Ss+    0:00 -bash
    136 ?        S      0:00 systemd-userwork
    137 ?        S      0:00 systemd-userwork
    138 ?        S      0:00 systemd-userwork
    139 pts/1    R+     0:00 ps -ax
[root@MSI-wsl ~]#

I use a shortcut with wsl -d Fedora33 -u root genie -s to start Fedora with systemd. Then I use the special WT profile to login with systemd-logind. Indeed, WSL is useless without systemd, i.e. systemd-genie. But with genie it is very useful. Arkane-system, the genie developers have enough knowledge to solve this issue and they are open for cooperation.
Why I need "some adjustments" to get junk Linux without networking and D-Bus with junk Podman at the end if I can have the normal Linux and normal Podman?

**Comment by gbraad** [comment] 2021-02-17 07:30
> Arkane-system, the genie developers have enough knowledge to solve this issue and they are open for cooperation.

I am already talking to Alistair, but that is not part of this issue. Please, prevent the noise.


What I meant was that you can not disable cgroupv1 as this stops systemd from starting with `genie -[i/l/s]`. Anyway...

```
$ ls /sys/fs/cgroup/unified
cgroup.controllers  cgroup.max.depth  cgroup.max.descendants  cgroup.procs  cgroup.stat  cgroup.subtree_control  cgroup.threads  init.scope  machine.slice  system.slice  user.slice
```

exists as expected. But I am sure when you do a `mount`, you will ALSO see the v1 mounts besides the v2 unified mount.

```
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
...
```

When a regular Fedora VM is used, you will NOT see any v1 mounts...
```
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate)
```
and there is NO nesting to use `unified`. Perhaps podman uses this to make decision of what to do ? @giuseppe

**Comment by PavelSosin-320** [comment] 2021-02-17 08:45
Maybe, [Known and solved libvirt issue](https://listman.redhat.com/archives/libvir-list/2020-November/msg01037.html)
Device management in WSL is a separate topic, like GPU. If Podman will work without devices it will be OK for 90% of WSL users.
Advertized by MS solution for GPU doesn't work too because either cause green screens or 65% memory usage if GPU software is not maintained carefully.

**Comment by PavelSosin-320** [comment] 2021-03-07 06:54
@gbraad Maybe, I see the root cause. According to the [Systemd explanation of groups version setup ](https://systemd.io/CGROUP_DELEGATION/) My new Fedora34 VM must have only /sys/fs/cgroup/unified mount point but actually has both /sys/fs/cgroup/unified/ and /sys/fs/cgroup/systemd/. It happens although I'm passing the parameter "cgroup unified = 1 as a kernel startup option. I suppose ,it has a negative effect  not only on Podman but also on Kernel startup:
![image](https://user-images.githubusercontent.com/54495912/110231655-ba3adc00-7f21-11eb-91cb-30d0ea7eb934.png)

I know how to enable cgroup V2 API but I don't know how to disable legacy and combined setups as systemd.io recommends. Could you give a hint? It may mislead Podman to use V1 API in the cases when V2 API is presented. I think that V1 should be disabled in the development environment as systemd.io recommends.

**Comment by gbraad** [comment] 2021-03-07 07:01
This is what I also suspected. Not sure how podman handles this.

I am busy with rebuilding the kernel for this. Trying to find out what is needed so a Fedora-like kernel can be used. At the moment a stock kernel wont boot. Filed issues for this and taking to solve of the engineers at MS. Though, don't have much time to work on this. Have priorities around CRC (+podman) on HyperV that go first.

**Comment by PavelSosin-320** [comment] 2021-03-07 07:34
@gbraad If you are working on WSL / Hyper-V Kernels and trying to use MS Fedora images it is time wasting.  They are broken. You need upgrade to MS Kernel to 5.4.9 and use 
Operating System: Fedora 34 (Container Image Prerelease)
     CPE OS Name: cpe:/o:fedoraproject:fedora:34
          Kernel: Linux 5.4.91-microsoft-standard-WSL2
    Architecture: x86-64
Also genie 1.36 is required to have systemd and make networking stable because MS methods to generate hosts and resolv.conf files can't work in the normal modern LAN setups with multiple network infrastructures available.

**Comment by gbraad** [comment] 2021-03-07 07:43
I work on the debugging with the engineers.

**Comment by PavelSosin-320** [comment] 2021-03-07 08:46
@graab Indeed. I opened the issue on the genie. Hopeflly, it will help. Unfortunatelly, neither WSL nor genie writes something useful into WSL_Console.log or Journal. Only those people that wrote that code can solve the issue.
As soon I will get correction for this issue I will test, report and close the Podman issue finally.
Bottom line: genie version 1.35 for Fedora has issues.

**Comment by gbraad** [comment] 2021-03-07 10:29
@PavelSosin-320 Is it so difficult to write my name?!?

> Bottom line: genie version 1.35 for Fedora has issues.

If there are issues, please report them here: https://github.com/arkane-systems/genie/issues/new/choose

> As soon I will get correction for this issue I will test, report and close the Podman issue finally.

This issue is already closed.

**Comment by giuseppe** [comment] 2021-03-08 08:31
> @gbraad Maybe, I see the root cause. According to the [Systemd explanation of groups version setup ](https://systemd.io/CGROUP_DELEGATION/) My new Fedora34 VM must have only /sys/fs/cgroup/unified mount point but actually has both /sys/fs/cgroup/unified/ and /sys/fs/cgroup/systemd/. It happens although I'm passing the parameter "cgroup unified = 1 as a kernel startup option. I suppose ,it has a negative effect not only on Podman but also on Kernel startup:
> ![image](https://user-images.githubusercontent.com/54495912/110231655-ba3adc00-7f21-11eb-91cb-30d0ea7eb934.png)
> 
> I know how to enable cgroup V2 API but I don't know how to disable legacy and combined setups as systemd.io recommends. Could you give a hint? It may mislead Podman to use V1 API in the cases when V2 API is presented. I think that V1 should be disabled in the development environment as systemd.io recommends.

that is known as hybrid mode, where both cgroup v1 and cgroup v2 are mounted.  That is not supported by Podman (or by crun/runc), and only the cgroup v1 mounted controllers are going to be used.

If you want to use cgroup v2 you need the unified hierarchy, please try adding `systemd.unified_cgroup_hierarchy=1` to the kernel command line.

**Comment by gbraad** [comment] 2021-03-08 08:41
In that case, this is a WSL issue. They do not pick up the kernel arguments correctly. They enable the v2, but it ends up being a hybrid mode with this setting.

Not a podman issue

**Comment by PavelSosin-320** [comment] 2021-03-08 16:08
@gbraad FYI #https://github.com/systemd/systemd/issues/18912 In the article [Fedora31-control-cgroup-v2](https://www.redhat.com/sysadmin/fedora-31-control-group-v2)  Dan Walsh said that the problem is Solved in Fedora 31, i.e. a long time ago. But it is not solved completely. The systemd still issues the message about systemd-compat invocation, fails due to access violation, ignores the failure, and does nothing from the Podman point of view. Now systemd.io closes the issue and insists that it is impossible to do.
![image](https://user-images.githubusercontent.com/54495912/110346591-60790580-8038-11eb-8c90-4315eadc2bd0.png)

_n In systemd 248 (v248~rc2-1.fc34) default-hierarchy=unified
the _ as promised but conversion doesn't exist or doesn't work. The mixed setup is not recommended but allowed. So I can't blame genie or WSL.

**Comment by PavelSosin-320** [comment] 2021-03-09 11:11
@gbraad We are not alone: #https://github.com/systemd/systemd/issues/18047 The issue hopefully will be corrected in the systemd ver 248.
The failure in the Cgroup conversion from V1 to V2 in the systemd 247 causes this issue.

**Comment by gbraad** [comment] 2021-03-09 12:22
As said; not a podman issue.
This is closed. If further problems, please open a new issue
