### ISSUE TITLE
Podman machine init try to download non existing next-devel build of fedora coreos

### ISSUE THREAD

**Issue by michael-bang** [containers/podman#14213] opened 2022-05-12 08:36 UTC
/kind bug

**Description**

Running 'podman machine init' on a Podman 4.1.0 using brew on mac result in the following error:
Error: downloading VM image https://fedorapeople.org/groups/podman/next-devel/builds/36.20220511.dev.0/x86_64/fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz: 404 Not Found  

**Steps to reproduce the issue:**

1. brew install podman

2. podman machine init

**Describe the results you received:**
Not able to create a new VM for podman to run in because podman is trying to download a non existing image.
Error: downloading VM image https://fedorapeople.org/groups/podman/next-devel/builds/36.20220511.dev.0/x86_64/fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz: 404 Not Found  

**Describe the results you expected:**
I expected that a VM image would be downloaded, unpacked and ready to be used.
I'm also a bit surprised that the image is a next-devel and not a stable build !

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.1.0
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.1.0/libpod/_ping": dial unix ///var/folders/9j/k49krtsj5s7_j4tqn7xcjw5m0000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
installed with brew so not available
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes and there are no info about podman machine ...

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Mac intel based.

**Comment by Luap99** [comment] 2022-05-12 08:43
Duplicate of #14210

**Closed by Luap99** 2022-05-12 08:43 UTC
Labels: kind/bug

**Comment by baude** [comment] 2022-05-12 14:34
fwiw, this is also fixed now
