### ISSUE TITLE
Getting an WARN[0000] Error validating CNI config file /etc/cni/net.d/myproject_default.conflist: [plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"] 

### ISSUE THREAD

**Issue by epicwhale** [containers/podman#21511] opened 2024-02-05 00:16 UTC
### Issue Description

When I docker-compose up, I always get this `WARN[0000] Error validating CNI config file /etc/cni/net.d/myproject_default.conflist: [plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"] `

### Steps to reproduce the issue

Steps to reproduce the issue
I installed podman on a fresh Ubuntu server via `sudo apt install -y podman`

I created a very basic compose file
```
version: "3.8"

services:
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
```

```
(/root/code/myproject/.conda) (.conda) (base) root@ubuntu-8gb-nbg1-1:~/code/myproject# podman-compose up redis
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 3.4.4
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=myproject', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
['podman', 'network', 'exists', 'myproject_default']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=myproject', '--label', 'com.docker.compose.project=myproject', 'myproject_default']
['podman', 'network', 'exists', 'myproject_default']
WARN[0000] Error validating CNI config file /etc/cni/net.d/myproject_default.conflist: [plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"] 
podman create --name=myproject_redis_1 --label io.podman.compose.config-hash=9c7ddc5bb2e7251a8f81f8b906c9d0e62ad78014aa13c3d3b60319ee6ec8d6c9 --label io.podman.compose.project=myproject --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@myproject.service --label com.docker.compose.project=myproject --label com.docker.compose.project.working_dir=/root/code/myproject --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=redis --net myproject_default --network-alias redis -p 6379:6379 redis:7.2.4-alpine
WARN[0000] Error validating CNI config file /etc/cni/net.d/myproject_default.conflist: [plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"] 
Error: short-name "redis:7.2.4-alpine" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
podman start -a myproject_redis_1
WARN[0000] Error validating CNI config file /etc/cni/net.d/myproject_default.conflist: [plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"] 
Error: no container with name or ID "myproject_redis_1" found: no such container
exit code: 125
```

I googled around and someone suggested installing `containernetworking-plugins`, but I can confirm it is is already the newest version (0.9.1+ds1-1) on this Ubuntu.

What am I missing?

### podman info output

```yaml
WARN[0000] Error validating CNI config file /etc/cni/net.d/myproject_default.conflist: [plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"] 
host:
  arch: arm64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 4
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: ubuntu-8gb-nbg1-1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-91-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 1095819264
  memTotal: 8113692672
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 745h 24m 47.02s (Approximately 31.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  OsArch: linux/arm64
  Version: 3.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

arm64 architecture

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment] 2024-02-05 10:05
Duplicate of #20213

**Closed by Luap99** 2024-02-05 10:05 UTC
Labels: kind/bug
