### ISSUE TITLE
podman play kube support for secrets

### ISSUE THREAD

**Issue by ydayagi** [containers/podman#12446] opened 2021-11-30 07:43 UTC
/kind feature

**Description**

support secrets in podman play kube. We know that podman already supports some form of secrets. Our goal is to use podman play kube for creating the secrets and the pods (with references to the secrets) just as we do in k8s. Will podman support that? Can my team add this support?

**Comment by rhatdan** [comment] 2021-11-30 11:24
We have looked into this in the past, and have a hard time translating the two concepts, but I would be very interested in revisiting this.  @vrothberg @ashley-cui WDYT?

**Comment by vrothberg** [comment] 2021-11-30 12:39
Closing this issue as it's a duplicate of https://github.com/containers/podman/issues/10105#issuecomment-958936019, let's continue over there.

**Closed by vrothberg** 2021-11-30 12:39 UTC
Labels: kind/feature
