### ISSUE TITLE
[Bug]: podman containers cannot be accessed from external network

### ISSUE THREAD

**Issue by harshasukeerthi** [containers/podman#17030] opened 2023-01-08 18:01 UTC
### Issue Description

I have Windows 10 host system with WSL2, hosting a Linux VM (Fedora CoreOS instantiated by podman as podman machine), and podman client running on Windows 10 host.  Created a sample container using command:

podman run -dp 9800:80/tcp --name webserver quay.io/libpod/banner:latest

From web browser, I can access localhost:9800, but times out when I try to access ip:9800, port 9800 is allowed in Windows defender firewall for inbound access for Domain, private and public networks.

When I view open ports in the system, I see port opened in 127.0.0.1:9800 by wslhost.exe, but no open ports in either 0.0.0.0 or <ip>.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman machine init
2. podman machine start
3. podman run -dp 9800:80/tcp --name webserver quay.io/libpod/banner:latest

podman ps -a
CONTAINER ID  IMAGE                         COMMAND               CREATED        STATUS            PORTS                 NAMES
f6ad583b00c1  quay.io/libpod/banner:latest  nginx -g daemon o...  6 seconds ago  Up 6 seconds ago  0.0.0.0:9800->80/tcp  webserver

4. Access localhost:9800 from browser

![image](https://user-images.githubusercontent.com/122226346/211211385-a46b6f00-0698-4f82-80af-163599d0117c.png)

5. Access ip:9800 from browser

![image](https://user-images.githubusercontent.com/122226346/211211404-f68b2ea8-6c5d-42a0-91aa-d2b909620b19.png)

6. Output from netstat:

![image](https://user-images.githubusercontent.com/122226346/211211431-89da6748-1018-48b5-8f96-7bf42b7809e2.png)

![image](https://user-images.githubusercontent.com/122226346/211211455-ea85ceb5-705b-4c8e-a0b8-62db0c3910e9.png)

### Describe the results you received

Not able to access container network from external network, timeout error is seen.  Changing port number does not resolve the issue.

### Describe the results you expected

Container network is accessed from external network after port mapping.

### podman info output

```shell
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.5-1.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 99.85
    systemPercent: 0.06
    userPercent: 0.09
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: IE4LLT23ZQ5S2
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.16.3-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 5291147264
  memTotal: 6533144576
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 2h 20m 38.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 1189007360
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668180253
  BuiltTime: Fri Nov 11 20:54:13 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by harshasukeerthi** [comment] 2023-01-08 18:05
IP configuration in the host system:

![image](https://user-images.githubusercontent.com/122226346/211211755-bb743ae0-2725-4e05-a558-aad09b6c15b0.png)

**Comment by baude** [comment] 2023-01-09 14:56
@n1hility is this expected behavior?  I would not think so but I know there are some caveats to port mapping, wsl, etc.

**Comment by harshasukeerthi** [comment] 2023-01-10 04:25
After reading https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md again, I noticed below in port forwarding:

![image](https://user-images.githubusercontent.com/122226346/211461426-a1e34319-3b14-4ebf-a497-62e904f53480.png)

Where it mentions ports are bound against local host (specifically), is this really the case?

**Comment by harshasukeerthi** [comment] 2023-01-10 16:52
@Luap99:

podman machine ssh ss -tulpn
Warning: Permanently added '[localhost]:63058' (ECDSA) to the list of known hosts.
Netid State  Recv-Q Send-Q Local Address:Port  Peer Address:PortProcess
tcp   LISTEN 0      4096         0.0.0.0:9800       0.0.0.0:*    users:(("rootlessport",pid=112,fd=11))
tcp   LISTEN 0      128          0.0.0.0:63058      0.0.0.0:*
tcp   LISTEN 0      4096            [::]:9800          [::]:*    users:(("rootlessport",pid=112,fd=12))
tcp   LISTEN 0      128             [::]:63058         [::]:*

C:\WINDOWS\system32>netstat -aonp tcp | findstr :9800
  TCP    127.0.0.1:9800         0.0.0.0:0              LISTENING       24708

C:\WINDOWS\system32>netstat -aonp tcp | findstr :63058
  TCP    127.0.0.1:63058        0.0.0.0:0              LISTENING       24708

**Comment by Luap99** [comment] 2023-01-10 17:13
OK so we are binded correctly to `0.0.0.0` and `::` in linux, this means it is something in the wsl layer that does not bind the correcr addresses on the windows side. cc @n1hility

**Comment by n1hility** [comment] 2023-01-10 17:26
Sorry for the delay replying. This is expected behavior for WSL since WSL traffic is isolated to a separate network interface from Windows applications (this is the vWSL interface). You can reach it via localhost (preferred) which is traffic forwarded, or the ip address assigned to the WSL distro (e.g. podman machine ssh ifconfig or wsl -d podman-machine-default ifconfig), although this one is temporary and changes. 

If you need the port to be remotely accessible to other systems on the lan you need to add an ip forward (see bottom section of https://learn.microsoft.com/en-us/windows/wsl/networking)

**Closed** 2023-01-10 17:59 UTC
Labels: kind/bug, remote, windows
