### ISSUE TITLE
Unable to pull Docker registry image on Fedora Rawhide (Error processing tar file(exit status 1): operation not supported)

### ISSUE THREAD

**Issue by HarryMichal** [containers/podman#10693] opened 2021-06-16 15:21 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

While trying to pull an image through `podman run` the command fails with:
```
Error: Error committing the finished image: error adding layer with blob "sha256:6eda6749503f60eb69077e148cba1015ec5808b0c1c2e6f027f7d1b960f6a3a9": Error processing tar file(exit status 1): operation not supported
```

The affected command is:
```
# Create a Docker registry without authentication
run $PODMAN --root "$BATS_RUN_TMPDIR"/reg run -d \
    --rm \
    --name docker-registry-noauth \
    --privileged \
    -v "$BATS_RUN_TMPDIR"/certs:/certs \
    -e REGISTRY_HTTP_ADDR=0.0.0.0:443 \
    -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
    -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
    -p 50000:443 \
    docker.io/library/registry:2
```

The command is ran as part of system tests ran using [bats-core](https://github.com/bats-core/bats-core). In the `certs` dir are certificates needed for HTTPS. That part can be left out.

The tests are executed on hosts with Fedora 33, Fedora 34 and Fedora Rawhide. I encountered https://github.com/containers/podman/issues/10038 (there are more reports for the same issue) along the way.

I could not reproduce the issue locally (Fedora Silverblue Rawhide with the same version of Podman).

Whole output of the affected command:
```
Trying to pull docker.io/library/registry:2...
Getting image source signatures
Copying blob sha256:ddad3d7c1e96adf9153f8921a7c9790f880a390163df453be1566e9ef0d546e0
Copying blob sha256:5b94580856e6fd27a74d55ab33fc3b53fd6f599f7147f38845a2482cc003cc19
Copying blob sha256:12008541203a024dab3a30542c87421e5a27dbb601b9c6f029b3827af138ccb3
Copying blob sha256:363ab70c2143bc121f037ba432cede225b7053200abba2a7a4ca24c2915a3998
Copying blob sha256:6eda6749503f60eb69077e148cba1015ec5808b0c1c2e6f027f7d1b960f6a3a9
Copying config sha256:1fd8e1b0bb7ef6cc63e0094e2fb5a35259bdce7041ef5e7e4c99694ded1041d7
Writing manifest to image destination
Storing signatures
Error: Error committing the finished image: error adding layer with blob "sha256:6eda6749503f60eb69077e148cba1015ec5808b0c1c2e6f027f7d1b960f6a3a9": Error processing tar file(exit status 1): operation not supported
```

**Steps to reproduce the issue:**

1. `podman run --rm --privileged docker.io/library/registry:2`

**Describe the results you received:**

Error when trying to run Docker registry in a container. The root directory with overlays and such cannot be removed by user.

**Describe the results you expected:**

Successfully launched Docker registry in a container.

**Additional information you deem important (e.g. issue happens only occasionally):**

I applied the following [fix](https://github.com/containers/podman/issues/10038#issuecomment-820185033) that has been used successfully. It helped with jobs running on Fedora 33 and Fedora 34 hosts but not here. The two environments have both older versions of Podman and fuse-overlayfs.

**Output of `podman version`:**

```
Version:      3.3.0-dev
API Version:  3.3.0-dev
Go Version:   go1.16.4
Built:        Fri Jun 11 04:17:43 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.1
  cgroupControllers: []https://softwarefactory-project.io/zuul/t/local/status
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.28-0.2.dev.git551605f.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.28-dev, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    version: "35"
  eventLogger: journald
  hostname: host-38-129-56-200
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.0-0.rc6.45.fc35.x86_64
  linkmode: dynamic
  memFree: 2415087616
  memTotal: 4104429568
  ociRuntime:
    name: crun
    package: crun-0.20.1.3-0.14.git9dec366.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1.3-9dec
      commit: 9dec366ed15c0cee945b3f1c95ffbd54a292a6aa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.11-2.dev.git0a9773c.fc35.x86_64
    version: |-
      slirp4netns version 1.1.11+dev
      commit: 0a9773c2d35c1d53c05d2ec4dbf4bc1adec89f57
      libslirp: 4.6.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 3m 21.08s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/zuul-worker/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.6-3.dev.git91a020f.fc35.x86_64
      Version: |-
        fusermount3 version: 3.10.4
        fuse-overlayfs: version 1.6-dev
        FUSE library version 3.10.4
        using FUSE kernel interface version 7.31
  graphRoot: /home/zuul-worker/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/zuul-worker/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.0-dev
  Built: 1623385063
  BuiltTime: Fri Jun 11 04:17:43 2021
  GitCommit: ""
  GoVersion: go1.16.4
  OsArch: linux/amd64
  Version: 3.3.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
golang-1.16.4-2.fc35.x86_64
podman-3.3.0-0.5.dev.gited983c9.fc35.x86_64
crun-0.20.1.3-0.14.git9dec366.fc35.x86_64
conmon-2.0.28-0.2.dev.git551605f.fc35.x86_64
fuse-overlayfs-1.6-3.dev.git91a020f.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Zuul CI hosted on [SoftwareFactory](https://softwarefactory-project.io/zuul); Fedora Cloud Rawhide image

Link to affected CI job: https://softwarefactory-project.io/zuul/t/local/build/e0f0e7624d1943659f42232de67f40d0 (switch to tab `Console` for more practical and informal view).

**Comment by mheon** [comment] 2021-06-16 17:35
Do we have any more details on the CI environment - is Podman running in a VM or a container? Are there any security constraints on the CI environment, e.g. a seccomp profile that could block a syscall we want to use?

**Comment by HarryMichal** [comment] 2021-06-16 18:06
Podman runs in a VM. The CI is used for testing Toolbox and that can not be done inside of a container.

I'm not aware of any abnormalities in the setup but my knowledge of the CI environment is very limited.

**Comment by HarryMichal** [comment] 2021-06-16 18:49
@TristanCacqueray might know a bit more about some possible limitations in the CI environment.

**Comment by rhatdan** [comment] 2021-06-16 19:50
This is rootless Podman correct?

**Comment by HarryMichal** [comment] 2021-06-16 19:56
> This is rootless Podman correct?

Indeed.

**Comment by rhatdan** [comment] 2021-06-16 20:13
This smells like the linger issues that people often have.   But the Operation not supported, does not match the usually issue.

@giuseppe Any thoughts?  One difference in Rawhide, is that it uses native overlayfs rather then fuse-overlayfs.

**Comment by TristanCacqueray** [comment] 2021-06-16 20:15
This is happening with an OpenStack instance started with the fedora cloud image. I don't think there is any special security constraints.

**Comment by HarryMichal** [comment] 2021-06-16 20:21
> One difference in Rawhide, is that it uses native overlayfs rather then fuse-overlayfs.

I believe I forced the use of `fuse-overlayfs` by applying https://github.com/containers/podman/issues/10038#issuecomment-820185033.

**Comment by HarryMichal** [comment] 2021-06-16 21:58
Without applying the workaround the job still fails with the same error. Output of `podman info --debug`:

```
host:
  arch: amd64
  buildahVersion: 1.21.1
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.28-0.2.dev.git551605f.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.28-dev, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    version: "35"
  eventLogger: journald
  hostname: host-38-102-83-166
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.0-0.rc6.45.fc35.x86_64
  linkmode: dynamic
  memFree: 2416377856
  memTotal: 4104421376
  ociRuntime:
    name: crun
    package: crun-0.20.1.3-0.14.git9dec366.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1.3-9dec
      commit: 9dec366ed15c0cee945b3f1c95ffbd54a292a6aa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.11-2.dev.git0a9773c.fc35.x86_64
    version: |-
      slirp4netns version 1.1.11+dev
      commit: 0a9773c2d35c1d53c05d2ec4dbf4bc1adec89f57
      libslirp: 4.6.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 2m 58.74s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/zuul-worker/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/zuul-worker/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/zuul-worker/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.0-dev
  Built: 1623385063
  BuiltTime: Fri Jun 11 04:17:43 2021
  GitCommit: ""
  GoVersion: go1.16.4
  OsArch: linux/amd64
  Version: 3.3.0-dev
```

**Comment by mheon** [comment] 2021-06-16 23:38
So we fail both with, and without, mount program set, with the same error?

**Comment by giuseppe** [comment] 2021-06-17 07:39
I guess "$BATS_RUN_TMPDIR" is pointing to `/tmp` or another tmpfs that doesn't support extended attributes.

The error above happens when setting an extended attribute, to reproduce it:

```
$ touch /tmp/foo
$ setfattr -n user.foo -v bar /tmp/foo
setfattr: /tmp/foo: Operation not supported
```

Please use another file system for the storage root.

I am closing the issue but please keep commenting and re-open it if I am wrong and that is not the reason.

**Closed by giuseppe** 2021-06-17 07:39 UTC
Labels: kind/bug

**Comment by HarryMichal** [comment] 2021-06-17 09:05
That sounds like the cause of the problem. Thanks for the insight, @giuseppe!

I wonder though why this issue happens only on Rawhide and not the stable versions of Fedora.

Anyway, I'll try to use a different location for the root.

**Comment by giuseppe** [comment] 2021-06-17 11:21
> I wonder though why this issue happens only on Rawhide and not the stable versions of Fedora.
> 
> Anyway, I'll try to use a different location for the root.

that happens because Fedora Rawhide has support for native overlay also for rootless.  In this case whiteout files are created using extended attributes, while on the older Fedora version we were using a different format for whiteout files (`.wh.FILE`) that is used by fuse-overlayfs

**Comment by HarryMichal** [comment] 2021-06-18 10:19
Thank you for the explanation!
