### ISSUE TITLE
Provide at least two different Podman major versions in the repositories

### ISSUE THREAD

**Issue by edigaryev** [containers/podman#9358] opened 2021-02-14 01:52 UTC
Recently Podman 3.0.0 was released and it seems to introduced some breaking changes (e.g. https://github.com/containers/podman/issues/9354, https://github.com/containers/podman/issues/9352 or https://github.com/containers/podman/issues/9351).

Currently in the [Ubuntu 20.04 repository](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/) there's only binary and source package of version 3.0.0 are available.

It would be nice if the users could choose to keep using the previous major release until the bugs are resolved and consumers are adapted to the new API versions.

**Comment by afbjorklund** [comment] 2021-02-14 08:16
It has happened before (with 1.9 to 2.0 transition), the workaround is to rebuild the old packages from source...

**Comment by Kiritow** [comment] 2021-02-17 02:55
Strongly agree with this. After upgrading to Podman 3.0.0, `sudo podman build` keeps failing and there's no easy way back. (It says either `container_linux.go:349: starting container process caused "error adding seccomp rule for syscall socket: requested action matches default action of filter"` or `exec: "runc": executable file not found in $PATH`, and I can't change it to use `crun` by default even after editing both `/usr/share/containers/containers.conf` and `/etc/containers/containers.conf` )

**Comment by mheon** [comment] 2021-02-17 05:59
The amount of packaging resources we have access to is strictly limited - @lsm5 is swamped with his current workload. If the community is willing to step up and maintain this, we'd be glad to advertise it, but we don't have the resources to maintain parallel packaging for different major versions right now.

**Comment by afbjorklund** [comment] 2021-02-17 06:55
I don't really want to be rebuilding the packages (bintray) or building the binaries (static), so I think I will leave this to the distributions (like RHEL and Debian) to come up with a supported way of installing podman for the maintenance tracks.

**Comment by alitvak69** [comment] 2021-02-17 22:34
I was thinking that whoever undertakes this have to handle packaging and rebuilding all dependencies.  Or at least storing the older versions somewhere.  I noticed this in repositories recently.   https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/old_podman/

Why cannot it be at least a temporary  solution for debs as well.  Pushing old files there would be a stop gap measure.

**Comment by rhatdan** [comment] 2021-03-23 10:00
Does not look like community has made any progress on this.

**Comment by jdockter** [comment] 2021-03-23 21:29
With 3.1.0 release looming what is the recommended way we can at least test out on Ubuntu 18 so we don't get hit with issues and have to scramble?  Is there any regression podman tests that specifically run on Ubuntu 18?  We use enterprise Travis CI and currently stuck at Ubuntu 18 so want a warm fuzzy we are okay.  BTW...anyway this next release can be on a Monday :) @mheon

**Comment by afbjorklund** [comment] 2021-04-09 16:24
@jdockter : I don't think there will be any packages for Ubuntu 18.04 LTS or Ubuntu 20.04 LTS, only for Ubuntu 20.10

https://podman.io/blogs/2021/03/02/podman-support-for-older-distros.html

https://podman.io/community/meeting/notes/2021-03-02/#podman-packages-on-kubic

There are no static binaries for 3.1.0 either, so you would have to build from source... Or just stay with podman 3.0.1 ?

**Comment by rhatdan** [comment] 2021-04-27 15:43
Closed since this is a duplicate of #3924

**Closed by rhatdan** 2021-04-27 15:43 UTC
