### ISSUE TITLE
Container restart fails with "address already in use"

### ISSUE THREAD

**Issue by apollo13** [containers/podman#9447] opened 2021-02-20 10:47 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Restarting a podman rootless container results in `address already in use` errors for me. It does not happen always (and maybe the way the image works might somehow cause that, but imo podman should handle that)

**Steps to reproduce the issue:**

```
➜  ~ podman run -d -p 8000:8000 --name wiki crazymax/dokuwiki:edge
ba5b7ab5b59d3c84c05dcc795a3cb81247956aa7d31067538501daa5339d0cd9
➜  ~ podman restart wiki
Error: rootlessport listen tcp 0.0.0.0:8000: bind: address already in use
➜  ~ podman restart wiki
ba5b7ab5b59d3c84c05dcc795a3cb81247956aa7d31067538501daa5339d0cd9
➜  ~ podman restart wiki
ba5b7ab5b59d3c84c05dcc795a3cb81247956aa7d31067538501daa5339d0cd9
➜  ~ podman restart wiki
Error: rootlessport listen tcp 0.0.0.0:8000: bind: address already in use
```

**Describe the results you expected:**

Proper restarts all the time.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 15:37:50 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.26-1.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 777074ecdb5e883b9bec233f3630c5e7fa37d521'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: apollo13
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.15-200.fc33.x86_64
  linkmode: dynamic
  memFree: 8343269376
  memTotal: 16419074048
  ociRuntime:
    name: crun
    package: crun-0.17-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.fc33.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 38654697472
  swapTotal: 38654697472
  uptime: 19m 6.72s
registries:
  search:
  - docker.io
store:
  configFile: /home/florian/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/florian/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 19
  runRoot: /run/user/1000/containers
  volumePath: /home/florian/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438270
  BuiltTime: Tue Dec  8 15:37:50 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No, can retest as soon as podman 3 hits fedora 33

**Comment by mheon** [comment] 2021-02-20 20:18
Stringly suspect this is the same issue as https://github.com/containers/podman/issues/9083

**Comment by rei-ber** [comment] 2021-03-08 12:58
same here with containers running in a pod and podman version: 
```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.14
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Comment by mheon** [comment] 2021-03-08 19:46
Any chance you can retest with Conmon 2.0.27 (just released)? It fixed a similar issue for root Podman, so I think it might also fix this

**Comment by apollo13** [comment] 2021-03-08 20:19
Will fedora 33 get an update to conmon .27? Can you link me to the relevant conmon commit that should fix this issue?

**Comment by apollo13** [comment] 2021-03-08 20:25
Ok, if that is early enough as a test for you, I'll happily report back then.

**Comment by haircommander** [comment] 2021-03-08 21:01
it is going through the pipeline now https://bodhi.fedoraproject.org/updates/FEDORA-2021-a5f4e3fb1a , probably a couple of days to get to stable

**Comment by sjpb** [comment] 2021-03-16 16:38
Is there a workaround for this at all?

**Comment by sdhoward** [comment] 2021-03-16 19:29
workarounds that kind of work but I'm sure have significant drawbacks:

* rolling back to conmon 2.0.22, or
* running `pkill containers-rootlessport`

**Comment by mheon** [comment] 2021-03-17 01:28
Had anyone confirmed the new Conmon does resolve the issue? It should be
ready for testing now.

**Comment by techsolo** [comment] 2021-03-17 06:24
@mheon Maybe not related but even after patching to the latest podman and conmon on CentOS7 I keep hitting:

`Failed to set up listener: SocketException: Address already in use`

https://github.com/minhhungit/mongodb-cluster-docker-compose for example doesn't seem to run on Podman.

Packages installed:

podman-3.0.1-2.el7.3.1.x86_64
podman-docker-3.0.1-2.el7.3.1.noarch
podman-plugins-3.0.1-2.el7.3.1.x86_64
conmon-2.0.27-1.el7.1.1.x86_64
buildah-1.19.6-3.el7.4.1.x86_64

And I'm running everything rootless.

**Comment by apollo13** [comment] 2021-03-17 06:55
> Had anyone confirmed the new Conmon does resolve the issue? It should be ready for testing now.

Thanks for the heads up, I pulled in `conmon-2:2.0.27-1.fc34.x86_64` and it seems fine for now.

**Comment by sdhoward** [comment] 2021-03-17 22:39
I'm not on red hat but I upgraded from conmon 2.0.26 to 2.0.27 and it fixed the issue for me as well -- I no longer have the `bind: address already in use` error.

**Comment by rhatdan** [comment] 2021-03-18 18:34
Closing since this seems to be fixed in the main branches.

**Closed by rhatdan** 2021-03-18 18:34 UTC
Labels: kind/bug

**Comment by heidemn** [comment] 2023-02-25 15:11
Hi there,
Is this expected to be fixed in Podman 3.4.4 (which is the version from the Ubuntu 22.04 repo)?
This issue was closed on Mar 18 2021, and v3.4.4 was released on Dec 8 2021.

It doesn't work for me (but works when using `sudo`).
I'm using WSL2 with Systemd.

Thanks for looking into it :-) 

```
$ sudo apt  install podman-docker
...

$ podman run --rm -p 80:80 httpd:alpine
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.0.2.100. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.0.2.100. Set the 'ServerName' directive globally to suppress this message
[Sat Feb 25 15:03:07.649551 2023] [mpm_event:notice] [pid 1:tid 140082517875528] AH00489: Apache/2.4.55 (Unix) configured -- resuming normal operations
[Sat Feb 25 15:03:07.649936 2023] [core:notice] [pid 1:tid 140082517875528] AH00094: Command line: 'httpd -D FOREGROUND'
^C[Sat Feb 25 15:03:09.907730 2023] [mpm_event:notice] [pid 1:tid 140082517875528] AH00491: caught SIGTERM, shutting down

$ podman run --rm -p 80:80 httpd:alpine
Error: rootlessport listen tcp 0.0.0.0:80: bind: address already in use

$ podman --version
podman version 3.4.4

$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
...

$ uname -a
Linux HOSTNAME 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cristianrgreco** [comment] 2023-03-12 22:00
Same issue as @heidemn. Using latest Podman (4.2.2) on Ubuntu 22.04. After restarting a container encountering the following error: `rootlessport listen tcp 0.0.0.0:42193: bind: address already in use`

**Comment by mheon** [comment] 2023-03-13 01:56
Please open a new issue, this one is two years old

**Comment by cristianrgreco** [comment] 2023-03-13 08:53
Apologies @mheon. FYI I've just checked and I wasn't using the latest podman, it was using 3.4.x. I've just tested the latest ("Debian Testing/Bookworm") version and these issues are resolved. How are we meant to get these fixes in production without using such unstable channels?

**Comment by heidemn** [comment] 2023-04-22 12:44
For others stumbling into this - after I followed these instructions: https://github.com/containers/podman/issues/12983
* `$ sudo apt install dbus-user-session`
* `> wsl --shutdown`

...I could no longer reproduce the issue `bind: address already in use`.

**Comment by emreds** [comment] 2023-04-25 13:39
> 

Thanks for the tip. This worked for me.

**Comment by emreds** [comment] 2023-04-25 13:39
> For others stumbling into this - after I followed these instructions: #12983
> 
>     * `$ sudo apt install dbus-user-session`
> 
>     * `> wsl --shutdown`
> 
> 
> ...I could no longer reproduce the issue `bind: address already in use`.

Thanks for the tip. This worked for me on WSL2.
