### ISSUE TITLE
I was not able to remove podman on Mac M1 MacOs 12.4 

### ISSUE THREAD

**Issue by jinglichen66** [containers/podman#15296] opened 2022-08-12 00:46 UTC
I was able to see the podman-machine-default but I am not able to remove the podman-machine-default on my macBook Pro M1, MacOS12.4. Can someone please help?

Here are commands i ran in order:

jli$ **podman machine list**
NAME                     VM TYPE     CREATED      LAST UP      CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        2 weeks ago  2 weeks ago  4           2.147GB     107.4GB

jli$ **podman machine rm podman-machine-default**
ERRO[0000] unable to find connection named "podman-machine-default" 
ERRO[0000] unable to find connection named "podman-machine-default-root" 

The following files will be deleted:

/Users/jli/.ssh/podman-machine-default
/Users/jli/.ssh/podman-machine-default.pub
/Users/jli/.config/containers/podman/machine/qemu/podman-machine-default.ign
/Users/jli/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-36.20220703.3.1-qemu.aarch64.qcow2
/Users/jli/.local/share/containers/podman/machine/podman-machine-default/podman.sock
/Users/jli/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd
/Users/jli/.config/containers/podman/machine/qemu/podman-machine-default.json

Are you sure you want to continue? [y/N] y
macos-WDFXKGYXRK:web-service-integration jli$ **podman machine list**
NAME                     VM TYPE     CREATED      LAST UP      CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        2 weeks ago  2 weeks ago  4           2.147GB     107.4GB
macos-WDFXKGYXRK:web-service-integration jli$

**Comment by jinglichen66** [comment] 2022-08-12 00:48
Here are my podman info
 jli$ podman --version
podman version 4.1.1
 jli$ qemu-system-aarch64 --version
QEMU emulator version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

**Comment by jinglichen66** [comment] 2022-08-12 01:06
jli$ qemu-system-aarch64 --version
QEMU emulator version 6.2.0

**Comment by mheon** [comment] 2022-08-15 14:09
@ashley-cui @baude PTAL

**Comment by ashley-cui** [comment] 2022-08-25 21:35
I'm unable to reproduce, try removing the files listed manually. Closing for now, re-open if issue persists

**Closed by ashley-cui** 2022-08-25 21:35 UTC
Labels: kind/bug, remote, macos
