### ISSUE TITLE
Error: short-name resolution enforced but cannot prompt without a TTY

### ISSUE THREAD

**Issue by T0MASD** [containers/podman#11530] opened 2021-09-11 08:02 UTC
**BUG REPORT**

/kind bug

**Description**

When installing rootless kind, using:
```
KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster --name test
```

getting an error:
```
command "podman pull kindest/node@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6" failed with error: exit status 125
Command Output: Error: short-name resolution enforced but cannot prompt without a TTY
```

**Steps to reproduce the issue:**

1. go get sigs.k8s.io/kind@v0.11.1 

2. KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster --name test

**Describe the results you received:**

Error: short-name resolution enforced but cannot prompt without a TTY

**Describe the results you expected:**

No errors

**Additional information you deem important (e.g. issue happens only occasionally):**

```
[tomas@uola ~]$ KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster --name test
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Cgroup controller detection is not implemented for Podman. If you see cgroup-related errors, you might need to set systemd property "Delegate=yes", see https://kind.sigs.k8s.io/docs/user/rootless/
Creating cluster "test" ...
 ✗ Ensuring node image (kindest/node:v1.21.1) 🖼 
ERROR: failed to create cluster: failed to pull image "kindest/node@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6": command "podman pull kindest/node@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6" failed with error: exit status 125
Command Output: Error: short-name resolution enforced but cannot prompt without a TTY

```

**Output of `podman version`:**

```
Version:      3.3.0
API Version:  3.3.0
Go Version:   go1.16.6
Built:        Sat Aug 21 05:36:14 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: uola
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.12-200.fc34.x86_64
  linkmode: dynamic
  memFree: 173449216
  memTotal: 12348919808
  ociRuntime:
    name: crun
    package: crun-0.21-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.21
      commit: c4c3cdf2ce408ed44a9e027c618473e6485c635b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 14172282880
  swapTotal: 17179860992
  uptime: 9h 9m 47.97s (Approximately 0.38 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/tomas/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/tomas/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 12
  runRoot: /run/user/1000
  volumePath: /home/tomas/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.0
  Built: 1629488174
  BuiltTime: Sat Aug 21 05:36:14 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.0-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by T0MASD** [comment] 2021-09-11 08:11
Manually ran podman pull:
```
[tomas@uola ~]$ podman pull kindest/node@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
✔ docker.io/kindest/node@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
Trying to pull docker.io/kindest/node@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6...
Getting image source signatures
Copying blob 92397077056a done  
Copying blob 2c8dd3a52776 done  
Copying blob 9178282edeae done  
Copying blob b8ff34c1005f done  
Copying blob 6415519001ad done  
Copying blob 259d51f13710 done  
Copying blob 6d2c2164c4af done  
Copying blob 5e79b1e14903 done  
Copying blob da636a2fd1fa done  
Copying blob d69368c3d04e done  
Copying blob 41e3227605a3 done  
Copying blob b68a62b92963 done  
Copying config 32b8b755de done  
Writing manifest to image destination
Storing signatures
32b8b755dee8d5fc6dbafef80898e7f2e450655f45f4b59cca3f7f57e9278c3b
```
After which kind create cluster went ok
```
[tomas@uola ~]$ KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster --name test
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Cgroup controller detection is not implemented for Podman. If you see cgroup-related errors, you might need to set systemd property "Delegate=yes", see https://kind.sigs.k8s.io/docs/user/rootless/
Creating cluster "test" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-test"
You can now use your cluster with:

kubectl cluster-info --context kind-test

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
```

**Comment by afbjorklund** [comment] 2021-09-11 08:42
They would eventually have to start using long names: 

https://www.redhat.com/sysadmin/container-image-short-names

Docker does this too, but is a bit more secretive about it.

```
Status: Image is up to date for kindest/node@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
docker.io/kindest/node@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
```


Did you file a bug with [kind](https://github.com/kubernetes-sigs/kind) already ? 

The workaround is disabling strict mode...

**Comment by afbjorklund** [comment] 2021-09-11 08:44
Seems at least related to https://github.com/kubernetes-sigs/kind/issues/2186

**Comment by mheon** [comment] 2021-09-12 06:12
This does look like intended behavior. The default mode for shortname handling in F34 is enforcing, and if we can't prompt (typically, if we're being invoked by a script, like kind), we hard-fail. This is necessary for security reasons - details can be found [here](https://www.redhat.com/sysadmin/container-image-short-names).

I concur with @afbjorklund that this is related to the linked kind issue, and is fixed there. Recommend you update to a more recent kind; if that fails, please raise an issue upstream with them. Closing as such.

**Closed by mheon** 2021-09-12 06:12 UTC
Labels: kind/bug

**Comment by ikem-krueger** [comment] 2022-10-31 11:01
I had a similar problem on the windows command prompt.

When I run this, I get the same error message as you:

`podman run -e 'MESSAGE_WELCOME=Hello, world DIT' test/hello-world`

When I run this instead, I get no error message and all works as intended::

`podman run -e "MESSAGE_WELCOME=Hello, world DIT" test/hello-world`

(Take a close look at the quotes around `MESSAGE_WELCOME`.)

I hope that helps somehow.

**Comment by koppor** [comment] 2022-11-05 11:52
On `cmd.exe` on Windows, I have the same issue independent of the quotes.

Installed Podman 4.3.0 using `podman-desktop`.

**Comment by SimplyGed** [comment] 2022-11-12 08:24
> On `cmd.exe` on Windows, I have the same issue independent of the quotes.
> 
> Installed Podman 4.3.0 using `podman-desktop`.

What image are you trying to run?
I had the same problem running `datalust/seq`. If I prefixed the container image with the registry name, it worked

e.g. 

`podman run docker.io/datalust/seq`

Hope that helps :-)

**Comment by n49o7** [comment] 2022-12-02 12:25
Specify the full name:

`podman pull docker.io/postgrest/postgrest`

**Comment by Type1J** [comment] 2023-01-02 22:44
Is there a way to disable short name resolution enforcement? Also, for podman, is there another file to change what server will be used with a short name?

**Comment by vrothberg** [comment] 2023-01-03 09:23
> Is there a way to disable short name resolution enforcement? Also, for podman, is there another file to change what server will be used with a short name?

The [containers-registries.conf man page ](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#short-name-aliasing-modes)goes into the details.
