### ISSUE TITLE
DNS lookup slow for public names

### ISSUE THREAD

**Issue by Nilos** [containers/podman#13926] opened 2022-04-20 09:02 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

DNS resolution is slow from inside a container that uses a container network. The local DNS takes ~5s to fail and then the DNS falls back to using the backup DNS configured in resolv.conf

**Steps to reproduce the issue:**

1. `podman network create testnetwork`

2. `podman run -it --name testcontainer alpine sh`

3. `podman network connect testnetwork testcontainer`

4. `time nslookup google.com`

**Describe the results you received:**

nslookup takes 5s to receive the dns entry

```
# time nslookup -debug google.com
Server:         8.8.8.8
Address:        8.8.8.8:53

Query #0 completed in 192ms:
Non-authoritative answer:
Name:   google.com
Address: 142.251.33.206

Query #1 completed in 193ms:
Non-authoritative answer:
Name:   google.com
Address: 2607:f8b0:4004:837::200e

real    0m 5.25s
user    0m 0.00s
sys     0m 0.02s
```

**Describe the results you expected:**

nslookup finishes in <1s

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is persistent for me in my buildroot/embedded setup. I did not try to reproduce it yet on another OS though.
The issue happens in a debian based container too.

**Output of `podman version`:**

```
# podman version
Client:       Podman Engine
Version:      4.0.3
API Version:  4.0.3
Go Version:   go1.17.8
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/arm
```

**Output of `podman info --debug`:**

```
# podman info --debug
host:
  arch: arm
  buildahVersion: 1.24.3
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 1
  distribution:
    distribution: buildroot
    version: 2021.02.2
  eventLogger: none
  hostname: zubrOS
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.72
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 25686016
  memTotal: 508403712
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: HEAD
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 24m 15.65s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 7
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /mnt/data/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 7
  runRoot: /run/containers/storage
  volumePath: /mnt/data/containers/storage/volumes
version:
  APIVersion: 4.0.3
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.8
  OsArch: linux/arm
  Version: 4.0.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Build from source for armv7 (via buildroot)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS is running on buildroot/busybox.

**Comment by Nilos** [comment] 2022-04-20 09:06
If this is just some configuration mistake from my side, I'm sorry about that.
Thanks for any help in advance!

I really enjoy podman, thanks for all the great work!

**Comment by flouthoc** [comment] 2022-04-20 09:37
Hi @Nilos Thanks for creating the issue. I'm unable to reproduce this on both rootless and rootfull on my host. Could you make sure your host resolver does not contains any bad resolver cause fallback dns will try all resolvers in order.

```console
$ sudo podman run -it --rm --name testcontainer --network testnetwork alpine sh
WARN[0000] Ignoring global metacopy option, not supported with booted kernel 
/ # time nslookup google.com
Server:		10.89.2.1
Address:	10.89.2.1:53

Non-authoritative answer:
Name:	google.com
Address: 142.250.195.142

Non-authoritative answer:
Name:	google.com
Address: 2404:6800:4007:820::200e

real	0m 0.01s
user	0m 0.00s
sys	0m 0.00s

```

**Comment by Nilos** [comment] 2022-04-20 12:57
Thanks for the quick replies! 🙌

Host `/etc/resolv.conf` points to google dns:
```
# cat /etc/resolv.conf
nameserver 8.8.8.8 8.8.4.4
```

Container `/etc/resolv.conf` looks like this:
```
# cat /etc/resolv.conf
nameserver 10.89.1.1
nameserver 8.8.8.8
nameserver 8.8.4.4
```

aardvark is running:
```
# ps aux | grep aardvark
  744 root     /usr/libexec/podman/aardvark-dns --config /run/containers/networks/aardvark-dns -p 53 run
22353 root     grep aardvark
```

**Comment by Nilos** [comment] 2022-04-20 13:02
That was very helpful, I think I found the issue now:

```
/ # time nslookup -debug google.com
Server:         10.89.1.1
Address:        10.89.1.1:53

Query #0 completed in 215ms:
Non-authoritative answer:
Name:   google.com
Address: 142.250.81.206

Query #1 completed in 229ms:
Non-authoritative answer:
Name:   google.com
Address: 2607:f8b0:4004:82f::200e

real    0m 0.25s
user    0m 0.00s
sys     0m 0.01s
```

The problem is the host `/etc/resolv.conf`. If I split the nameserver line into two lines, it works as expected. It did require a restart of aardvark-dns though to become effective.

**Comment by flouthoc** [comment] 2022-04-20 13:08
Thanks closing this issue.

**Closed by flouthoc** 2022-04-20 13:08 UTC
Labels: kind/bug

**Comment by Nilos** [comment] 2022-04-20 13:09
Thanks so much for all the help!

**Comment by Luap99** [comment] 2022-04-20 13:12
Having to nameservers on the same line is not valid syntax according to resolv.conf(5) man page.

We might want to look into the parsing code in aardvark, I don't understand why it hangs more than 5s. If there are no valid entries we should just return and not hang.

**Comment by mheon** [comment] 2022-04-20 13:15
Concur, this seems like an Aardvark bug - we should at least throw a warning that the host resolv.conf is not using valid syntax?
