### ISSUE TITLE
podman network create/rm: please ignore ENOENT

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10926] opened 2021-07-13 20:23 UTC
There's a race condition between the time podman reads its CNI directory and the time it tries to read conflist files. Trivial reproducer (requires two shells):
```console
! window 1
$ while :;do bin/podman network create aaa;bin/podman network rm -f aaa;done

! window 2
$ while :;do bin/podman network create bbb;bin/podman network rm -f bbb;done
```
Within less than ten seconds, one or the other will spit out:
```
ERRO[0000] Error loading CNI config list file /home/esm/.config/cni/net.d/xxx.conflist: error reading /home/esm/.config/cni/net.d/xxx.conflist: open /home/esm/.config/cni/net.d/xxx.conflist: no such file or directory
```
...where `xxx` is the name of the other window (e.g. you will see "bbb" in the aaa window and vice-versa).

(Note: even though it says ERRO, it's not an error and does not cause a nonzero exit status).

This is really annoying to me when looking at integration-test logs, because they all show up in bright scary orange that makes me think there's an error (and, in some cases, hides real errors because of the cry-wolf thing).

To normal-people users, this is probably kind of alarming, and would presumably cause them to waste an indeterminate amount of time looking into it.

Easy/obvious solution is to just ignore ENOENT, ¿que no?

**Comment by edsantiago** [comment] 2021-07-13 20:26
Oops, forgot to xref #9041

**Comment by Luap99** [comment] 2021-07-14 09:20
The only place where this error is shown is in ocicni and I already fixed it to make it ignore enoent, at least I thought it was fixed with https://github.com/cri-o/ocicni/pull/85.
https://github.com/cri-o/ocicni/blob/5ce5cee5666d097f0a18341868b87eb8c016480d/pkg/ocicni/ocicni.go#L290-L296
Maybe `!os.IsNotExist(err)` does not work correctly in this case.

**Comment by edsantiago** [comment] 2021-07-14 11:15
@Luap99 maybe my setup doesn't have that vendored in? Can you reproduce on your system?

**Comment by Luap99** [comment] 2021-07-14 11:28
It is vendored in. I just checked the code. CNI does not return a warped error. It uses `fmt.Errorf("error reading %s: %s", filename, err)`. Therefore we cannot check the root cause of this error correctly. I think we have to use string comparison to catch this.

**Comment by rhatdan** [comment] 2021-07-14 23:35
Yes this output looks like it is a logrus.Error.

**Comment by Luap99** [comment] 2021-07-21 16:14
Upstream PR https://github.com/containernetworking/cni/pull/850 to fix this is merged. When they release CNI v1.0.0 we can vendor this in (hopefully soon).

**Comment by edsantiago** [comment] 2021-08-10 19:51
Just a quick comment to reset the nagbot. This is still happening often:

### Podman network [It] podman network prune
* fedora-33 : int podman fedora-33 root container
  * PR #11176
    * [08-10 05:54](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5085474504048640/html/int-podman-fedora-33-root-container.log.html#t--podman-network-prune--1)
* fedora-33 : int podman fedora-33 root host
  * PR #11176
    * [08-10 05:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5314172922626048/html/int-podman-fedora-33-root-host.log.html#t--podman-network-prune--1)
* fedora-33 : int podman fedora-33 rootless host
  * PR #11176
    * [08-10 06:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4803999527337984/html/int-podman-fedora-33-rootless-host.log.html#t--podman-network-prune--1)
* fedora-34 : int podman fedora-34 root container
  * PR #11176
    * [08-10 05:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5648424457469952/html/int-podman-fedora-34-root-container.log.html#t--podman-network-prune--1)
* fedora-34 : int podman fedora-34 root host
  * PR #11176
    * [08-10 05:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5877122876047360/html/int-podman-fedora-34-root-host.log.html#t--podman-network-prune--1)
  * PR #11074
    * [08-05 10:12](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6717075688259584/html/int-podman-fedora-34-root-host.log.html#t--podman-network-prune--1)

**Comment by edsantiago** [comment] 2021-09-09 14:24
### Podman network [It] podman network prune
* fedora-33 : int podman fedora-33 root container
  * PR #11463
    * [09-06 16:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5652691230654464/html/int-podman-fedora-33-root-container.log.html#t--podman-network-prune--1)
  * PR #11337
    * [08-27 05:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4997205510586368/html/int-podman-fedora-33-root-container.log.html#t--podman-network-prune--1)
  * PR #11308
    * [08-23 11:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5554515903512576/html/int-podman-fedora-33-root-container.log.html#t--podman-network-prune--1)
  * PR #11307
    * [08-26 05:28](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5980134571245568/html/int-podman-fedora-33-root-container.log.html#t--podman-network-prune--1)
  * PR #11298
    * [08-26 10:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5245793184514048/html/int-podman-fedora-33-root-container.log.html#t--podman-network-prune--1)
    * [08-25 18:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4610537951592448/html/int-podman-fedora-33-root-container.log.html#t--podman-network-prune--1)
* fedora-34 : int remote fedora-34 root host [remote]
  * PR #11485
    * [09-09 05:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181162843799552/html/int-remote-fedora-34-root-host.log.html#t--podman-network-prune--1)
* ubuntu-2010 : int podman ubuntu-2010 rootless host
  * PR #11451
    * [09-05 13:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5305984961740800/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-network-prune--1)
  * PR #11376
    * [08-31 14:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4640376129585152/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-network-prune--1)
  * PR #11333
    * [08-27 07:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5372310774349824/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-network-prune--1)
  * PR #11327
    * [08-30 07:59](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6633371649441792/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-network-prune--1)
* ubuntu-2104 : int podman ubuntu-2104 root host
  * PR #11402
    * [09-07 05:10](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5734243096592384/html/int-podman-ubuntu-2104-root-host.log.html#t--podman-network-prune--1)
  * PR #11314
    * [08-24 10:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6222408777465856/html/int-podman-ubuntu-2104-root-host.log.html#t--podman-network-prune--1)

**Comment by Luap99** [comment] 2021-09-09 14:26
CNI version 1.0.0 is available, I can start updating when https://github.com/containers/podman/pull/11322 is merged.

**Closed** 2021-09-22 15:37 UTC
Labels: flakes, kind/bug, In Progress, 4.0
