### ISSUE TITLE
File ownership inside container differs for users using additionalimagestores

### ISSUE THREAD

**Issue by kdickerson** [containers/podman#20178] opened 2023-09-27 21:23 UTC
### Issue Description

I'm working on an image that will be shared by several users using `additionalimagestores`.  I've been successfully following @rhatdan's guide here: https://www.redhat.com/sysadmin/image-stores-podman.

When I run my container as the user who originally put it into the shared store the file ownership is what I expect to see, but when I run it as another user all the files are owned by `nobody` (uid=65534).

This is an issue because I have a startup script in the container which allows the user starting it to pick which nginx configuration to use (which it does by creating a symlink in `/etc/nginx/conf.d` to the desired config).  For the original user this works fine, but for other users it fails with permission denied.

I'm building off the `nginx-unprivileged` image so inside the container we're operating as the `nginx` user instead of `root`.

### Steps to reproduce the issue

A boiled down example:

**nginx-example.containerfile**
```dockerfile
# syntax=docker/dockerfile:1

FROM registry.hub.docker.com/nginxinc/nginx-unprivileged:1.24.0

USER root

RUN rm /etc/nginx/conf.d/default.conf &&\
    mkdir -p /etc/nginx/available-sites /var/www &&\
    echo 'server {listen 8080; server_name _; location / {root /var/www;}}' > /etc/nginx/available-sites/example.conf &&\
    echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Hello</title></head><body>Hello World</body></html>' > /var/www/index.html &&\
    ln -s /etc/nginx/available-sites/example.conf /etc/nginx/conf.d/example.conf

EXPOSE 8080
USER nginx
CMD ["nginx", "-g", "daemon off;"]
```

Note that I'm excluding the custom startup script for simplicity since the root issue is the file-ownership differences which can be shown without it.

1. Build the Image: `podman build -t nginx-example -f "images/nginx-example.containerfile"`
2. Save the image: `podman save --output nginx-example.tar nginx-example:latest`
3. Transfer to target machine
Now following Dan's guide (on target machine)
4. User1: Load the image into shared location: `podman --root /var/shared_podman_images load --input nginx-example.tar`
5. User1: Configure `additionalimagestores` in `~/.config/containers/storage.conf` per Dan's guide:
    ```
    [storage]
    driver = "overlay"

    [storage.options]
    additionalimagestores = [ "/var/shared_podman_images",]

    [storage.options.overlay]
    mount_program = "/usr/bin/fuse-overlayfs"
    ```
6. User1: Run a shell in a container for the image to inspect filesystem:
    ```
    [user1@localhost ~]$ podman container run --interactive --tty --entrypoint=/bin/bash nginx-example
    nginx@56f91d7cc418:/$ whoami
    nginx
    nginx@56f91d7cc418:/$ id -u
    101
    nginx@56f91d7cc418:/$ ls -la /etc/nginx/conf.d
    total 0
    drwxrwxr-x. 2 nginx nogroup 46 Sep 27 19:51 .
    drwxrwxr-x. 4 nginx nogroup 43 Sep 27 19:51 ..
    lrwxrwxrwx. 1 root  nogroup 39 Sep 27 19:51 example.conf -> /etc/nginx/available-sites/example.conf
    nginx@56f91d7cc418:/$ ls -lan /etc/nginx/conf.d
    total 0
    drwxrwxr-x. 2 101 65534 46 Sep 27 19:51 .
    drwxrwxr-x. 4 101 65534 43 Sep 27 19:51 ..
    lrwxrwxrwx. 1   0 65534 39 Sep 27 19:51 example.conf -> /etc/nginx/available-sites/example.conf
    nginx@56f91d7cc418:/$ touch /etc/nginx/conf.d/new.conf
    nginx@56f91d7cc418:/$ ls -lan /etc/nginx/conf.d
    total 0
    drwxrwxr-x. 2 101 65534 22 Sep 27 20:49 .
    drwxrwxr-x. 4 101 65534 43 Sep 27 19:51 ..
    lrwxrwxrwx. 1   0 65534 39 Sep 27 19:51 example.conf -> /etc/nginx/available-sites/example.conf
    -rw-r--r--. 1 101   101  0 Sep 27 20:49 new.conf
    ```
7. User1: Change permissions on shared location: `sudo chmod -R g+rX /var/shared_podman_images`
8. User2: Configure `additionalimagestores` in `~/.config/containers/storage.conf` same as above.
9. User2: Run a shell in a container for the image to inspect filesystem:
    ```
    [user2@localhost ~]$ podman container run --interactive --tty --entrypoint=/bin/bash nginx-example
    nginx@2b28a98c56d9:/$ whoami
    nginx
    nginx@2b28a98c56d9:/$ id -u
    101
    nginx@2b28a98c56d9:/$ ls -la /etc/nginx/conf.d
    total 0
    drwxrwxr-x. 2 nobody nogroup 46 Sep 27 19:51 .
    drwxrwxr-x. 4 nobody nogroup 43 Sep 27 19:51 ..
    lrwxrwxrwx. 1 nobody nogroup 39 Sep 27 19:51 example.conf -> /etc/nginx/available-sites/example.conf
    nginx@2b28a98c56d9:/$ ls -lan /etc/nginx/conf.d
    total 0
    drwxrwxr-x. 2 65534 65534 46 Sep 27 19:51 .
    drwxrwxr-x. 4 65534 65534 43 Sep 27 19:51 ..
    lrwxrwxrwx. 1 65534 65534 39 Sep 27 19:51 example.conf -> /etc/nginx/available-sites/example.conf
    nginx@2b28a98c56d9:/$ touch /etc/nginx/conf.d/new.conf
    touch: cannot touch '/etc/nginx/conf.d/new.conf': Permission denied
    ```

### Describe the results you received

For User1 all the files are owned by either `root`, or `nginx`.  But for User2 they're all owned by `nobody`. and User2 cannot modify the configuration directory (which in my real use case is done by a custom entrypoint script based on passed configuration during container startup).

### Describe the results you expected

Expected file ownership inside the container to be the same regardless of which user runs the container.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.6-1.module+el8.8.0+1265+fa25dd7a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: a88a21e8953a6243d5f369f61a342bcaf0630aa1'
  cpuUtilization:
    idlePercent: 96.53
    systemPercent: 1.01
    userPercent: 2.46
  cpus: 2
  distribution:
    distribution: '"rocky"'
    version: "8.8"
  eventLogger: file
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 4.18.0-477.27.1.el8_8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 2913218560
  memTotal: 5881090048
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.module+el8.8.0+1265+fa25dd7a.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.19.4
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_SYS_CHROOT,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.8.0+1265+fa25dd7a.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 1h 10m 23.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/user2/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/shared_podman_images
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.11-1.module+el8.8.0+1265+fa25dd7a.x86_64
      Version: |-
        fusermount3 version: 3.3.0
        fuse-overlayfs: version 1.11
        FUSE library version 3.3.0
        using FUSE kernel interface version 7.26
  graphRoot: /home/user2/.local/share/containers/storage
  graphRootAllocated: 37558423552
  graphRootUsed: 8998699008
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /tmp/containers-user-1001/containers
  transientStore: false
  volumePath: /home/user2/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1695425060
  BuiltTime: Fri Sep 22 16:24:20 2023
  GitCommit: ""
  GoVersion: go1.19.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Container host is a Rocky 8 VM in VirtualBox on a Windows 10 host.

### Additional information

Spun off another VM to build podman from source to test the latest version with the same results.  Had some issues getting it to compile, but got around it eventually.  It reports `podman version 4.8.0-dev`.  Kept the `podman info` output on this ticket from the latest version officially available in Rocky 8 since I may have done something incorrect while compiling the newer version.

**Comment by flouthoc** [comment] 2023-09-28 05:28
Checking this.

**Comment by giuseppe** [comment] 2023-09-28 09:39
have you used `force_mask = "shared"` when pulling the images in the additional store?

**Comment by giuseppe** [comment] 2023-09-28 09:40
that will force the containers/storage library to store the "real" ownership of the files inside an extended attribute, that later fuse-overlayfs will read and use instead of the original owner and mode for the inode

**Comment by kdickerson** [comment] 2023-09-28 16:53
That didn't seem to change anything, but perhaps I did something incorrectly.

1. User1: Get a clean state `podman system reset && sudo rm -rf /var/shared_podman_images/*`
3. User1: Modify `~/.config/containers/storage.conf` and add `force_mask = "shared"` under `[storage.options.overlay]`
4. User1: Load the image (as above): `podman --root /var/shared_podman_images load --input nginx-example.tar`
5. User1: Update permissions (I left out the chgrp in my original description, both users are in the group): `sudo chmod -R g+rX /var/shared_podman_images && sudo chgrp -R podman-images /var/shared_podman_images`
6. User1: Runs image, still sees files owned by `nginx`/`root`.
7. User2: Get a clean state `podman system reset`
8. User2: Runs image, still sees files owned by `nobody`.

This was on my VM with the self-compiled podman `4.8.0-dev`.

I wasn't sure if User2 needed `force_mask` configured as well (the description suggests to me it only affects pulling/loading the image).  Doing so didn't change anything.

I also tried using `pull` on the original `nginx-unprivileged` image in case there was an issue using `load`, but no change there either.

**Comment by giuseppe** [comment] 2023-09-29 10:49
can you check if the files under `/var/shared_podman_images` have the correct xattr set?

e.g. you can read the xattrs for a file with:

```
# getfattr  -d -m'.*' /var/lib/containers/storage/overlay/5eb2e729c16708697e84f3cf2648d1ff3f2ce56f2f1eceb0289b226bc96b061a/diff/usr/bin/ls 
getfattr: Removing leading '/' from absolute path names
# file: var/lib/containers/storage/overlay/5eb2e729c16708697e84f3cf2648d1ff3f2ce56f2f1eceb0289b226bc96b061a/diff/usr/bin/ls
security.selinux="unconfined_u:object_r:container_ro_file_t:s0"
```

just make sure to use a file that is part of the image and it is under your store.

Then we will understand if it is failing at writing these xattrs or they are not honored by user 2.

Also make sure user2 is using fuse-overlayfs.

**Comment by kdickerson** [comment] 2023-09-29 16:24
I have no experience working with extended attributes, so I don't know what I'm looking for.  I identified the appropriate overlay directory to look at by looking at the output of `podman inspect` and finding the `GraphDriver.Data.UpperDir` value.  Here's the output for the nginx config directory I care about in particular (but I checked several arbitrarily chosen files and they all had the same output):

```
[user1@localhost ~]$ getfattr -d -m'.*' /var/shared_podman_images/overlay/c6df3a9eb27557d924dbea6dbd2421cba5b55690d25a7cbfe1c5ec9985d9769b/diff/etc/nginx/conf.d
getfattr: Removing leading '/' from absolute path names
# file: var/shared_podman_images/overlay/c6df3a9eb27557d924dbea6dbd2421cba5b55690d25a7cbfe1c5ec9985d9769b/diff/etc/nginx/conf.d
security.selinux="unconfined_u:object_r:var_t:s0"
```

User2 is using the `storage.conf` shown in the original post--using fuse-overlayfs.

**Comment by rhatdan** [comment] 2023-09-29 16:54
From an SELinux point of view, it looks like these files are mislabled.   

Did you do the 
```
# semange fcontext -a -e /var/lib/containers/storage /var/shared_podman_images
# restorecon -R -v /var/shared_podman_images
```

**Comment by kdickerson** [comment] 2023-09-29 17:51
Is that something that should be in the "Exploring additional image stores in Podman" article?  I haven't run across it before now.

I ran those commands. No change to the file ownership when running the image.  I reset both users to a clean state and did it all again with no change either.

```
[user1@localhost ~]$ getfattr -d -m'.*' /var/shared_podman_images/overlay/c6df3a9eb27557d924dbea6dbd2421cba5b55690d25a7cbfe1c5ec9985d9769b/diff/etc/nginx/conf.d
getfattr: Removing leading '/' from absolute path names
# file: var/shared_podman_images/overlay/c6df3a9eb27557d924dbea6dbd2421cba5b55690d25a7cbfe1c5ec9985d9769b/diff/etc/nginx/conf.d
security.selinux="unconfined_u:object_r:container_ro_file_t:s0"
```

**Comment by rhatdan** [comment] 2023-10-11 13:05
Have you verified that this is an SELinux issue versus a permissions issue?

Check for AVC messages, and see if setting `setenfore 0` works?

**Comment by kdickerson** [comment] 2023-10-11 16:19
I have very little experience with SELinux (I'm a software developer that only dabbles in sysadmin-ing), but I was unable to find any denial messages in the audit log. (`# grep -i prevent /var/log/audit/audit.log` and `# grep -i denied /var/log/audit/audit.log`).  If I should be looking for something else, please let me know.  I scanned the log entries over the time frame when I loaded and then ran the image, but didn't see anything that stood out to me.

I put my 2 users back into a clean state and then put SELinux into permissive mode and ran through it all again with no change in result.

**Comment by rhatdan** [comment] 2023-10-11 17:24
grep -i avc /var/log/audit/audit.log

**Comment by rhatdan** [comment] 2023-10-11 17:24
Since setenforce 0, did not fix the problem, the problem is with User Namespace.

**Comment by giuseppe** [comment] 2023-10-12 08:32
> I have no experience working with extended attributes, so I don't know what I'm looking for. I identified the appropriate overlay directory to look at by looking at the output of `podman inspect` and finding the `GraphDriver.Data.UpperDir` value. Here's the output for the nginx config directory I care about in particular (but I checked several arbitrarily chosen files and they all had the same output):
> 
> ```
> [user1@localhost ~]$ getfattr -d -m'.*' /var/shared_podman_images/overlay/c6df3a9eb27557d924dbea6dbd2421cba5b55690d25a7cbfe1c5ec9985d9769b/diff/etc/nginx/conf.d
> getfattr: Removing leading '/' from absolute path names
> # file: var/shared_podman_images/overlay/c6df3a9eb27557d924dbea6dbd2421cba5b55690d25a7cbfe1c5ec9985d9769b/diff/etc/nginx/conf.d
> security.selinux="unconfined_u:object_r:var_t:s0"
> ```
> 
> User2 is using the `storage.conf` shown in the original post--using fuse-overlayfs.

from the output above, it seems the files in the additional storage do not have the correct xattr set.  Please make sure you set up a mount program as well as `force_mask="shared"`.

```
[storage]
driver = "overlay"

[storage.options]
additionalimagestores = [ "/var/shared_podman_images",]

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
force_mask = "shared"
```

Could you try with the configuration above (you need to remove and re-pull your image in the additional storage)?

**Comment by kdickerson** [comment] 2023-10-12 15:39
That is the configuration I've been using.

**Comment by rhatdan** [comment] 2023-11-12 17:25
@kdickerson still having this issue?

**Comment by kdickerson** [comment] 2023-11-12 17:53
> @kdickerson still having this issue?

Correct, this has not yet been resolved.

**Comment by martinfg2** [comment] 2023-11-16 01:01
I'm also experiencing this issue.  Just like the original poster, I had my storage.conf configured per Giuseppe's Oct 12 post for User1 and User2, then User1 did a "podman --root=<sharedstore> pull ..." of a custom container image.  User 1 runs a container from that image, things look nominal.  User2 runs a container from it, almost every file appears to be owned by "nobody:nobody".

In addition, if any files in this container image are not owned by root, then their uid/gid are not mapped properly for User2.  If the container image is configured to utilize non-root users, this is a problem, especially if using a containerized application that insists on a restrictive permission mask like 0400.

**Comment by rhatdan** [comment] 2023-12-17 11:45
@martinfg2 Could you give @giuseppe the output he asked for?

**Comment by kasualkeef** [comment] 2024-02-13 12:16
FWIW, I had this issue when using the root user to pull images into the image store. If I use another rootless user, the in-container permissions seem to work properly.

**Comment by giuseppe** [comment] 2024-02-13 12:44
you need to force fuse-overlayfs also with the root user

**Comment by giuseppe** [comment] 2024-02-13 12:45
I am closing the issue since there was no feedback

**Closed by giuseppe** 2024-02-13 12:45 UTC
Labels: kind/bug

**Comment by kdickerson** [comment] 2024-02-16 17:05
I believe I provided all feedback and additional information that was asked of me.  It is still unresolved.
