### ISSUE TITLE
idmap only works one way

### ISSUE THREAD

**Issue by namazso** [containers/podman#18717] opened 2023-05-28 16:54 UTC
### Issue Description

Idmapped mounts seem to be working only one way, when touching things from the container they become nobody:nobody. I can't really describe it better, see the next point.

### Steps to reproduce the issue

podman command:

```
/usr/bin/podman run -d --name transmission --userns=host --user=977:973 --mount=type=bind,source=/mnt/data/Downloads,destination=/mnt/data/Downloads,idmap=uids=979-977-1;gids=975-973-1 --security-opt label=disable fedora:37
```

The issue:

```
[root@server2 Downloads]# touch test.txt
[root@server2 Downloads]# ls -lna test.txt
-rw-r--r--. 1 0 0 0 May 28 18:43 test.txt
[root@server2 Downloads]# chown -R 979:975 test.txt
[root@server2 Downloads]# ls -lna test.txt
-rw-r--r--. 1 979 975 0 May 28 18:43 test.txt
[root@server2 Downloads]# podman exec -it transmission /bin/ls -lna /mnt/data/Downloads/test.txt
-rw-r--r--. 1 977 973 0 May 28 16:43 /mnt/data/Downloads/test.txt
[root@server2 Downloads]# podman exec -it transmission /bin/id -u
977
[root@server2 Downloads]# podman exec -it transmission /bin/id -g
973
[root@server2 Downloads]# rm test.txt
[root@server2 Downloads]# podman exec -it transmission /bin/touch /mnt/data/Downloads/test.txt
/bin/touch: setting times of '/mnt/data/Downloads/test.txt': Permission denied
[root@server2 Downloads]# ls -lna test.txt
-rw-r--r--. 1 977 973 0 May 28 18:45 test.txt
[root@server2 Downloads]# podman exec -it transmission /bin/ls -lna /mnt/data/Downloads/test.txt
-rw-r--r--. 1 65534 65534 0 May 28 16:45 /mnt/data/Downloads/test.txt
```

### Describe the results you received

Describe the results you received

### Describe the results you expected

This used to work as you'd expect

### podman info output

```yaml
[root@server2 Downloads]# podman info
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 96.36
    systemPercent: 0.94
    userPercent: 2.71
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: iot
    version: "38"
  eventLogger: journald
  hostname: server2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.2.15-300.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 342323200
  memTotal: 8222838784
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 7644901376
  swapTotal: 8221880320
  uptime: 31h 43m 12.00s (Approximately 1.29 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 8
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 73391005696
  graphRootUsed: 14339117056
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 17
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681486942
  BuiltTime: Fri Apr 14 17:42:22 2023
  GitCommit: ""
  GoVersion: go1.20.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```
```


### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by namazso** [comment] 2023-05-28 17:17
interestingly, rolling back to 4.4.4 didn't fix the issue

**Comment by giuseppe** [comment] 2023-05-29 14:39
it works well for me using your same reproducer.

What is the file ownership for the `/mnt/data/Downloads/test.txt` file on the host?  What is the underlying file system for `/mnt/data/Downloads`?

**Comment by namazso** [comment] 2023-05-29 14:42
> it works well for me using your same reproducer.

Odd. It used to work for me too until about the 17th of this month, not sure what changed

> What is the file ownership for the /mnt/data/Downloads/test.txt file on the host?

see `ls -lna` in the original post ran on both the internally and externally created file

>  What is the underlying file system for /mnt/data/Downloads?

`/dev/sda1 on /var/mnt/data type ntfs3 (rw,noatime,uid=0,gid=0,iocharset=utf8,sparse,prealloc)`

**Comment by namazso** [comment] 2023-05-29 14:54
I can confirm the reproducer does work as expected (and not as reported) on an ext4 filesystem

**Comment by giuseppe** [comment] 2023-05-29 14:54
I am not familiar with `ntfs3` but that would be the first thing I'd investigate.

Can you try with a different file system?

**Comment by giuseppe** [comment] 2023-05-29 15:13
I am closing the issue since this is a kernel bug

**Closed by giuseppe** 2023-05-29 15:13 UTC
Labels: kind/bug
