### ISSUE TITLE
Podman v5.0.0-RC4 Machine init command results in error cannot find policy.json

### ISSUE THREAD

**Issue by odockal** [containers/podman#21964] opened 2024-03-06 22:01 UTC
### Issue Description

`podman machine init` command with podman v5.0.0-rc4 bits on windows with hyperv throws an error:
```
Error: failed to pull quay.io/baude/stage-podman-machine-image@sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228: obtaining signature policy: open C:\Program Files\RedHat\Podman\podman.exe\policy.json: The system cannot find the path specified.
```

Related issue: https://github.com/containers/podman/issues/21855

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install Podman (v5.0.0-rc4) from the setup.exe installer
2. Set `CONTAINERS_MACHINE_PROVIDER` to `hyperv`
3. `podman machine init`

### Describe the results you received

```
Error: failed to pull quay.io/baude/stage-podman-machine-image@sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228: obtaining signature policy: open C:\Program Files\RedHat\Podman\podman.exe\policy.json: The system cannot find the path specified.
```

### Describe the results you expected

Podman machine created

### podman info output

```yaml
podman info
OS: windows/amd64
provider: hyperv
version: 5.0.0-rc4

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v5.0.0/libpod/_ping": dial unix /run/podman/podman.sock: connect: A socket operation encountered a dead network.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Windows 10 Professional
CONTAINERS_MACHINE_PROVIDER=hyperv

### Additional information

Whole command run with debugging on:
```
podman machine init --log-level=debug
time="2024-03-06T22:48:42+01:00" level=info msg="C:\\Program Files\\RedHat\\Podman\\podman.exe filtering at log level debug"
time="2024-03-06T22:48:42+01:00" level=debug msg="Using Podman machine with `hyperv` virtualization provider"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.config\\containers\\podman\\machine\\hyperv is 56"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv is 61"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\cache is 67"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\AppData\\Local\\Temp\\podman is 41"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.config\\containers\\podman\\machine\\hyperv is 56"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv is 61"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\cache is 67"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\AppData\\Local\\Temp\\podman is 41"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.config\\containers\\podman\\machine\\hyperv\\podman-machine-default.json is 84"
time="2024-03-06T22:48:42+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\podman-machine-default-amd64.vhdx is 95"
time="2024-03-06T22:48:42+01:00" level=debug msg="Using registries.d directory /etc/containers/registries.d"
time="2024-03-06T22:48:42+01:00" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
time="2024-03-06T22:48:42+01:00" level=debug msg="Trying to access \"quay.io/baude/stage-podman-machine-image:5.0\""
time="2024-03-06T22:48:42+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\Ondrej\\.config\\containers\\auth.json"
time="2024-03-06T22:48:42+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\Ondrej\\.config\\containers\\auth.json"
time="2024-03-06T22:48:42+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\Ondrej\\.docker\\config.json"
time="2024-03-06T22:48:42+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\Ondrej\\.dockercfg"
time="2024-03-06T22:48:42+01:00" level=debug msg="No credentials for quay.io/baude/stage-podman-machine-image found"
time="2024-03-06T22:48:42+01:00" level=debug msg=" No signature storage configuration found for quay.io/baude/stage-podman-machine-image:5.0, using built-in default file://C:%5CUsers%5COndrej%5C.local%5Cshare%5Ccontainers%5Csigstore"
time="2024-03-06T22:48:42+01:00" level=debug msg="Looking for TLS certificates and private keys in \\etc\\docker\\certs.d\\quay.io"
time="2024-03-06T22:48:42+01:00" level=debug msg="GET https://quay.io/v2/"
time="2024-03-06T22:48:42+01:00" level=debug msg="Ping https://quay.io/v2/ status 401"
time="2024-03-06T22:48:42+01:00" level=debug msg="GET https://quay.io/v2/auth?scope=repository%3Abaude%2Fstage-podman-machine-image%3Apull&service=quay.io"
time="2024-03-06T22:48:43+01:00" level=debug msg="Increasing token expiration to: 60 seconds"
time="2024-03-06T22:48:43+01:00" level=debug msg="GET https://quay.io/v2/baude/stage-podman-machine-image/manifests/5.0"
time="2024-03-06T22:48:43+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.oci.image.index.v1+json\""
time="2024-03-06T22:48:43+01:00" level=debug msg="found image in digest: \"sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228\""
time="2024-03-06T22:48:43+01:00" level=debug msg="GET https://quay.io/v2/baude/stage-podman-machine-image/manifests/sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228"
time="2024-03-06T22:48:43+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.oci.image.manifest.v1+json\""
time="2024-03-06T22:48:43+01:00" level=debug msg="original artifact file name: podman-machine-daily.x86_64.hyperv.vhdx.zst"
time="2024-03-06T22:48:43+01:00" level=debug msg="GET https://quay.io/v2/baude/stage-podman-machine-image/manifests/sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228"
time="2024-03-06T22:48:43+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.oci.image.manifest.v1+json\""
time="2024-03-06T22:48:43+01:00" level=debug msg="original artifact file name: podman-machine-daily.x86_64.hyperv.vhdx.zst"
time="2024-03-06T22:48:43+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\cache\\6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228.vhdx.zst is 141"
time="2024-03-06T22:48:43+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\cache\\6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228 is 132"
Error: failed to pull quay.io/baude/stage-podman-machine-image@sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228: obtaining signature policy: open C:\Program Files\RedHat\Podman\podman.exe\policy.json: The system cannot find the path specified.
time="2024-03-06T22:48:43+01:00" level=debug msg="Shutting down engines"
```

**Comment by baude** [comment] 2024-03-07 01:12
you can get the policy.json from several locations; but https://github.com/containers/podman/blob/main/pkg/machine/ocipull/policy.json is one

**Comment by baude** [comment] 2024-03-07 01:13
fwiw, rc5's installer should have the policy.json in it right @n1hility @ashley-cui ?

**Comment by n1hility** [comment] 2024-03-07 01:41
not yet, will get to it soon though

**Comment by odockal** [comment] 2024-03-08 14:07
@baude @Luap99 Thanks for looking into it. 
I have tried today with rc5 bits.
I am getting into another error:
```
podman machine init --log-level=debug
time="2024-03-08T15:04:48+01:00" level=info msg="C:\\Program Files\\RedHat\\Podman\\podman.exe filtering at log level debug"
time="2024-03-08T15:04:48+01:00" level=debug msg="Using Podman machine with `hyperv` virtualization provider"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.config\\containers\\podman\\machine\\hyperv is 56"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv is 61"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\cache is 67"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\AppData\\Local\\Temp\\podman is 41"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.config\\containers\\podman\\machine\\hyperv is 56"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv is 61"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\cache is 67"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\AppData\\Local\\Temp\\podman is 41"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.config\\containers\\podman\\machine\\hyperv\\podman-machine-default.json is 84"
time="2024-03-08T15:04:48+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\podman-machine-default-amd64.vhdx is 95"
Looking up Podman Machine image at quay.io/baude/stage-podman-machine-image:5.0 to create VM
time="2024-03-08T15:04:48+01:00" level=debug msg="Using registries.d directory /etc/containers/registries.d"
time="2024-03-08T15:04:48+01:00" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
time="2024-03-08T15:04:48+01:00" level=debug msg="Trying to access \"quay.io/baude/stage-podman-machine-image:5.0\""
time="2024-03-08T15:04:48+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\Ondrej\\.config\\containers\\auth.json"
time="2024-03-08T15:04:48+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\Ondrej\\.config\\containers\\auth.json"
time="2024-03-08T15:04:48+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\Ondrej\\.docker\\config.json"
time="2024-03-08T15:04:48+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\Ondrej\\.dockercfg"
time="2024-03-08T15:04:48+01:00" level=debug msg="No credentials for quay.io/baude/stage-podman-machine-image found"
time="2024-03-08T15:04:48+01:00" level=debug msg=" No signature storage configuration found for quay.io/baude/stage-podman-machine-image:5.0, using built-in default file://C:%5CUsers%5COndrej%5C.local%5Cshare%5Ccontainers%5Csigstore"
time="2024-03-08T15:04:48+01:00" level=debug msg="Looking for TLS certificates and private keys in \\etc\\docker\\certs.d\\quay.io"
time="2024-03-08T15:04:48+01:00" level=debug msg="GET https://quay.io/v2/"
time="2024-03-08T15:04:48+01:00" level=debug msg="Ping https://quay.io/v2/ status 401"
time="2024-03-08T15:04:48+01:00" level=debug msg="GET https://quay.io/v2/auth?scope=repository%3Abaude%2Fstage-podman-machine-image%3Apull&service=quay.io"
time="2024-03-08T15:04:49+01:00" level=debug msg="Increasing token expiration to: 60 seconds"
time="2024-03-08T15:04:49+01:00" level=debug msg="GET https://quay.io/v2/baude/stage-podman-machine-image/manifests/5.0"
time="2024-03-08T15:04:49+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.oci.image.index.v1+json\""
time="2024-03-08T15:04:49+01:00" level=debug msg="found image in digest: \"sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228\""
time="2024-03-08T15:04:49+01:00" level=debug msg="GET https://quay.io/v2/baude/stage-podman-machine-image/manifests/sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228"
time="2024-03-08T15:04:50+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.oci.image.manifest.v1+json\""
time="2024-03-08T15:04:50+01:00" level=debug msg="original artifact file name: podman-machine-daily.x86_64.hyperv.vhdx.zst"
time="2024-03-08T15:04:50+01:00" level=debug msg="GET https://quay.io/v2/baude/stage-podman-machine-image/manifests/sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228"
time="2024-03-08T15:04:50+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.oci.image.manifest.v1+json\""
time="2024-03-08T15:04:50+01:00" level=debug msg="original artifact file name: podman-machine-daily.x86_64.hyperv.vhdx.zst"
time="2024-03-08T15:04:50+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\cache\\6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228.vhdx.zst is 141"
time="2024-03-08T15:04:50+01:00" level=debug msg="cached image exists and is latest: C:\\Users\\Ondrej\\.local\\share\\containers\\podman\\machine\\hyperv\\cache\\6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228.vhdx.zst"
time="2024-03-08T15:04:50+01:00" level=debug msg="Detected compression format zstd"
Extracting compressed file: podman-machine-default-amd64.vhdx: done
time="2024-03-08T15:04:52+01:00" level=debug msg="--> imagePath is \"C:\\\\Users\\\\Ondrej\\\\.local\\\\share\\\\containers\\\\podman\\\\machine\\\\hyperv\\\\podman-machine-default-amd64.vhdx\""
time="2024-03-08T15:04:52+01:00" level=debug msg="socket length for C:\\Users\\Ondrej\\.config\\containers\\podman\\machine\\hyperv\\podman-machine-default.ign is 83"
time="2024-03-08T15:04:52+01:00" level=error msg="The handle is invalid."
Error: Access is denied.
time="2024-03-08T15:04:52+01:00" level=debug msg="Shutting down engines"
```
Should I continue in this issue or create new one?

**Comment by Luap99** [comment] 2024-03-08 14:36
Sounds like a different issue, seems like you over the policy.json error so I consider this fixed.
But yes please file a new one for the new issue. The error unfortunately is not really helpful...

**Comment by odockal** [comment] 2024-03-08 14:43
@Luap99 Ok, also colleague was able to reproduce the issue I first saw with rc5 but could not reproduce after manually copying `policy.json` into podman installation folder in `Program Files`
Error after fresh install of rc5 bits:
```
PS C:\Users\rosta> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
PS C:\Users\rosta> podman machine init --log-level=debug
time="2024-03-08T15:39:36+01:00" level=info msg="C:\\Program Files\\RedHat\\Podman\\podman.exe filtering at log level debug"
time="2024-03-08T15:39:36+01:00" level=debug msg="Using Podman machine with `hyperv` virtualization provider"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.config\\containers\\podman\\machine\\hyperv is 55"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.local\\share\\containers\\podman\\machine\\hyperv is 60"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.local\\share\\containers\\podman\\machine\\hyperv\\cache is 66"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\AppData\\Local\\Temp\\podman is 40"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.config\\containers\\podman\\machine\\hyperv is 55"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.local\\share\\containers\\podman\\machine\\hyperv is 60"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.local\\share\\containers\\podman\\machine\\hyperv\\cache is 66"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\AppData\\Local\\Temp\\podman is 40"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.config\\containers\\podman\\machine\\hyperv\\podman-machine-default.json is 83"
time="2024-03-08T15:39:36+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.local\\share\\containers\\podman\\machine\\hyperv\\podman-machine-default-amd64.vhdx is 94"
Looking up Podman Machine image at quay.io/baude/stage-podman-machine-image:5.0 to create VM
time="2024-03-08T15:39:36+01:00" level=debug msg="Using registries.d directory /etc/containers/registries.d"
time="2024-03-08T15:39:36+01:00" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
time="2024-03-08T15:39:36+01:00" level=debug msg="Trying to access \"quay.io/baude/stage-podman-machine-image:5.0\""
time="2024-03-08T15:39:36+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\rosta\\.config\\containers\\auth.json"
time="2024-03-08T15:39:36+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\rosta\\.config\\containers\\auth.json"
time="2024-03-08T15:39:36+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\rosta\\.docker\\config.json"
time="2024-03-08T15:39:36+01:00" level=debug msg="No credentials matching quay.io/baude/stage-podman-machine-image found in C:\\Users\\rosta\\.dockercfg"
time="2024-03-08T15:39:36+01:00" level=debug msg="No credentials for quay.io/baude/stage-podman-machine-image found"
time="2024-03-08T15:39:36+01:00" level=debug msg=" No signature storage configuration found for quay.io/baude/stage-podman-machine-image:5.0, using built-in default [file://C](file:///):%5CUsers%5Crosta%5C.local%5Cshare%5Ccontainers%5Csigstore"
time="2024-03-08T15:39:36+01:00" level=debug msg="Looking for TLS certificates and private keys in \\etc\\docker\\certs.d\\quay.io"
time="2024-03-08T15:39:36+01:00" level=debug msg="GET https://quay.io/v2/"
time="2024-03-08T15:39:37+01:00" level=debug msg="GET https://quay.io/v2/auth?scope=repository%3Abaude%2Fstage-podman-machine-image%3Apull&service=quay.io"
time="2024-03-08T15:39:37+01:00" level=debug msg="Increasing token expiration to: 60 seconds"
time="2024-03-08T15:39:37+01:00" level=debug msg="GET https://quay.io/v2/baude/stage-podman-machine-image/manifests/5.0"
time="2024-03-08T15:39:38+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.oci.image.index.v1+json\""
time="2024-03-08T15:39:38+01:00" level=debug msg="found image in digest: \"sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228\""
time="2024-03-08T15:39:38+01:00" level=debug msg="GET https://quay.io/v2/baude/stage-podman-machine-image/manifests/sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228"
time="2024-03-08T15:39:38+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.oci.image.manifest.v1+json\""
time="2024-03-08T15:39:38+01:00" level=debug msg="original artifact file name: podman-machine-daily.x86_64.hyperv.vhdx.zst"
time="2024-03-08T15:39:38+01:00" level=debug msg="GET https://quay.io/v2/baude/stage-podman-machine-image/manifests/sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228"
time="2024-03-08T15:39:38+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.oci.image.manifest.v1+json\""
time="2024-03-08T15:39:38+01:00" level=debug msg="original artifact file name: podman-machine-daily.x86_64.hyperv.vhdx.zst"
time="2024-03-08T15:39:38+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.local\\share\\containers\\podman\\machine\\hyperv\\cache\\6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228.vhdx.zst is 140"
time="2024-03-08T15:39:38+01:00" level=debug msg="socket length for C:\\Users\\rosta\\.local\\share\\containers\\podman\\machine\\hyperv\\cache\\6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228 is 131"
Error: failed to pull quay.io/baude/stage-podman-machine-image@sha256:6a47d33056736e2d9c68845a10fe7f5a6120d6fc0445288afcfbd0fbdbea2228: no DefaultPolicyJSONPath defined and no local overwrites found: ["CreateFile C:\\Users\\rosta\\AppData\\Roaming\\containers\\policy.json: The system cannot find the file specified."]
time="2024-03-08T15:39:38+01:00" level=debug msg="Shutting down engines"
```

**Comment by Luap99** [comment] 2024-03-08 14:48
> no DefaultPolicyJSONPath defined and no local overwrites found

Sound like https://github.com/containers/podman/pull/21985 didn't work then as it no longer set's the build option for some reason. 

Can you at least verify if policy.json was put into`C:\Program Files\RedHat\Podman` dir by the installer?

**Comment by odockal** [comment] 2024-03-08 14:49
> Can you at least verify if policy.json was put into`C:\Program Files\RedHat\Podman` dir by the installer?

Yes the `policy.json` is present in podman installation folder.

**Comment by n1hility** [comment] 2024-03-08 19:19
I can confirm the release binaries were somehow created with MACHINE_POLICY* set, looking into why

**Comment by n1hility** [comment] 2024-03-09 08:42
Just a follow up the issue appears to be specific to the environment the podman binary was built on (the go linker failed to interpret all specified X ldflags, including other values we set on build like the git sha

Will update the issue later with next steps.

**Comment by Luap99** [comment] 2024-03-11 10:27
How are the zip files for the releases build, @ashley-cui @lsm5 @mheon?

**Comment by ashley-cui** [comment] 2024-03-11 12:43
`make release-artifacts`

This problem seems to only be present on my machine, as @n1hility was unable to reproduce. I'm looking into my environment today and seeing if I can fix it. No idea why it's broken.

**Comment by baude** [comment] 2024-03-12 15:00
@ashley-cui was this fixed in the rc from yesterday ?

**Comment by ashley-cui** [comment] 2024-03-12 15:01
Yep, should be.

**Closed** 2024-03-12 15:01 UTC
Labels: kind/bug, machine, windows
