### ISSUE TITLE
failed to mmp when use bind mount

### ISSUE THREAD

**Issue by monotone** [containers/podman#20055] opened 2023-09-20 08:37 UTC
### Issue Description

i just run this commannd in my mac m2, and it issue like:
```bash
$ podman run --rm -it -p 9090:9090 -v $(pwd):/prometheus --user 0:0 prom/prometheus:v2.46.0                            130 ↵ 
ts=2023-09-20T08:30:35.316Z caller=main.go:541 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2023-09-20T08:30:35.317Z caller=main.go:585 level=info msg="Starting Prometheus Server" mode=server version="(version=2.46.0, branch=HEAD, revision=cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0)"
ts=2023-09-20T08:30:35.317Z caller=main.go:590 level=info build_context="(go=go1.20.6, platform=linux/arm64, user=root@42454fc0f41e, date=20230725-12:37:33, tags=netgo,builtinassets,stringlabels)"
ts=2023-09-20T08:30:35.317Z caller=main.go:591 level=info host_details="(Linux 6.4.15-200.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:51:10 UTC 2023 aarch64 40df65556270 (none))"
ts=2023-09-20T08:30:35.318Z caller=main.go:592 level=info fd_limits="(soft=524288, hard=524288)"
ts=2023-09-20T08:30:35.318Z caller=main.go:593 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-09-20T08:30:35.332Z caller=query_logger.go:105 level=error component=activeQueryTracker msg="Failed to mmap" file=/prometheus/queries.active Attemptedsize=20001 err="invalid argument"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0xffffc5171ee6, 0xb}, 0x14, {0x374a840, 0x400004d1d0})
        /app/promql/query_logger.go:123 +0x2fc
main.main()
        /app/cmd/prometheus/main.go:647 +0x6710
```

I have tried this in orbstack docker, it`s ok event i not set the user to root.

### Steps to reproduce the issue

just run ` podman run --rm -it -p 9090:9090 -v $(pwd):/prometheus --user 0:0 prom/prometheus:v2.46.0` in termianl.

### Describe the results you received

got error like "failed to mmap"

### Describe the results you expected

it should be ok like orbstack docker:
```bash
$ docker run --rm -it -p 9090:9090 -v $(pwd):/prometheus --user 0:0 prom/prometheus:v2.46.0                                                                                      130 ↵
ts=2023-09-20T08:35:37.309Z caller=main.go:541 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2023-09-20T08:35:37.309Z caller=main.go:585 level=info msg="Starting Prometheus Server" mode=server version="(version=2.46.0, branch=HEAD, revision=cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0)"
ts=2023-09-20T08:35:37.309Z caller=main.go:590 level=info build_context="(go=go1.20.6, platform=linux/arm64, user=root@42454fc0f41e, date=20230725-12:37:33, tags=netgo,builtinassets,stringlabels)"
ts=2023-09-20T08:35:37.309Z caller=main.go:591 level=info host_details="(Linux 6.4.16-orbstack-00103-g02b40eb69695 #1 SMP Wed Sep 13 10:13:30 UTC 2023 aarch64 bee8a30acd51 (none))"
ts=2023-09-20T08:35:37.309Z caller=main.go:592 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2023-09-20T08:35:37.309Z caller=main.go:593 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-09-20T08:35:37.311Z caller=web.go:563 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2023-09-20T08:35:37.311Z caller=main.go:1026 level=info msg="Starting TSDB ..."
ts=2023-09-20T08:35:37.313Z caller=tls_config.go:274 level=info component=web msg="Listening on" address=[::]:9090
ts=2023-09-20T08:35:37.313Z caller=tls_config.go:277 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
ts=2023-09-20T08:35:37.318Z caller=head.go:595 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2023-09-20T08:35:37.318Z caller=head.go:676 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=1.792µs
ts=2023-09-20T08:35:37.318Z caller=head.go:684 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2023-09-20T08:35:37.319Z caller=head.go:755 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-09-20T08:35:37.319Z caller=head.go:792 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=423.206µs wal_replay_duration=410.164µs wbl_replay_duration=0s total_replay_duration=864.62µs
ts=2023-09-20T08:35:37.321Z caller=main.go:1047 level=info fs_type=65735546
ts=2023-09-20T08:35:37.321Z caller=main.go:1050 level=info msg="TSDB started"
ts=2023-09-20T08:35:37.321Z caller=main.go:1231 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
ts=2023-09-20T08:35:37.322Z caller=main.go:1268 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=431.206µs db_storage=667ns remote_storage=708ns web_handler=375ns query_engine=541ns scrape=185.707µs scrape_sd=24.791µs notify=23.209µs notify_sd=23.749µs rules=1.125µs tracing=15.625µs
ts=2023-09-20T08:35:37.322Z caller=main.go:1011 level=info msg="Server is ready to receive web requests."
ts=2023-09-20T08:35:37.322Z caller=manager.go:1009 level=info component="rule manager" msg="Starting rule manager..."
```

### podman info output

```yaml
$ podman info
host:
  arch: arm64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 98.93
    systemPercent: 0.52
    userPercent: 0.55
  cpus: 1
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  freeLocks: 2048
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.4.15-200.fc38.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1361387520
  memTotal: 2048544768
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.fc38.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-1.fc38.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.8.7-1.fc38.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.7
      commit: 53a9996ce82d1ee818349bdcc64797a1fa0433c4
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230823.ga7e4bfb-1.fc38.aarch64
    version: |
      pasta 0^20230823.ga7e4bfb-1.fc38.aarch64
      Copyright Red Hat
      GNU Affero GPL version 3 or later <https://www.gnu.org/licenses/agpl-3.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.fc38.aarch64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 32m 19.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 2797142016
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 1693251554
  BuiltTime: Tue Aug 29 03:39:14 2023
  GitCommit: ""
  GoVersion: go1.20.7
  Os: linux
  OsArch: linux/arm64
  Version: 4.6.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by giuseppe** [comment] 2023-09-20 11:20
does the file `/prometheus/queries.active` exist?  If so, what is its size?

**Comment by giuseppe** [comment] 2023-09-20 11:25
thinking more about it, it might fail because the volume is on a network file system

**Comment by Luap99** [comment] 2023-09-20 11:33
Looks like the same as https://github.com/containers/podman/issues/19639

**Comment by monotone** [comment] 2023-09-21 01:13
> Looks like the same as #19639

I already read #19639 before make this issue.  if I do't use `--user 0:0` option,  the error like this, notice  the `permission denied`。 

```bash
$ podman run --rm -it -p 9090:9090 -v $(pwd):/prometheus prom/prometheus:v2.47.0                                                                                                   2 ↵
ts=2023-09-21T01:12:15.445Z caller=main.go:539 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2023-09-21T01:12:15.446Z caller=main.go:583 level=info msg="Starting Prometheus Server" mode=server version="(version=2.47.0, branch=HEAD, revision=efa34a5840661c29c2e362efa76bc3a70dccb335)"
ts=2023-09-21T01:12:15.446Z caller=main.go:588 level=info build_context="(go=go1.21.0, platform=linux/arm64, user=root@409eb5e6b30c, date=20230906-10:27:30, tags=netgo,builtinassets,stringlabels)"
ts=2023-09-21T01:12:15.446Z caller=main.go:589 level=info host_details="(Linux 6.4.15-200.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:51:10 UTC 2023 aarch64 db1c57af6fb7 (none))"
ts=2023-09-21T01:12:15.447Z caller=main.go:590 level=info fd_limits="(soft=524288, hard=524288)"
ts=2023-09-21T01:12:15.447Z caller=main.go:591 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-09-21T01:12:15.448Z caller=query_logger.go:93 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0xffffd9286ee6, 0xb}, 0x14, {0x382c2c0, 0x400017b0e0})
	/app/promql/query_logger.go:123 +0x2f8
main.main()
	/app/cmd/prometheus/main.go:645 +0x6830
```

**Comment by monotone** [comment] 2023-09-21 01:22
> thinking more about it, it might fail because the volume is on a network file system
> does the file `/prometheus/queries.active` exist? If so, what is its size?

no, it is just directory on my Mac m2.  I will show this:
```bash
~/test
$ pwd
/Users/billow/test

~/test
$ ls -al
total 0
drwxr-xr-x    4 billow  staff   128 Sep 15 16:47 .
drwxr-x---+ 112 billow  staff  3584 Sep 21 09:15 ..
drwxr-xr-x    2 billow  staff    64 Sep 15 16:47 a
drwxr-xr-x    2 billow  staff    64 Sep 15 16:47 b

~/test
$ podman run --rm -it -p 9090:9090 -v $(pwd):/prometheus --user 0:0 --entrypoint sh prom/prometheus:v2.47.0
/prometheus # ls -a
.   ..  a   b
/prometheus # prometheus --config.file /etc/prometheus/prometheus.yml
ts=2023-09-21T01:17:41.580Z caller=main.go:539 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2023-09-21T01:17:41.581Z caller=main.go:583 level=info msg="Starting Prometheus Server" mode=server version="(version=2.47.0, branch=HEAD, revision=efa34a5840661c29c2e362efa76bc3a70dccb335)"
ts=2023-09-21T01:17:41.582Z caller=main.go:588 level=info build_context="(go=go1.21.0, platform=linux/arm64, user=root@409eb5e6b30c, date=20230906-10:27:30, tags=netgo,builtinassets,stringlabels)"
ts=2023-09-21T01:17:41.582Z caller=main.go:589 level=info host_details="(Linux 6.4.15-200.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:51:10 UTC 2023 aarch64 785515a09295 (none))"
ts=2023-09-21T01:17:41.582Z caller=main.go:590 level=info fd_limits="(soft=524288, hard=524288)"
ts=2023-09-21T01:17:41.583Z caller=main.go:591 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-09-21T01:17:41.596Z caller=query_logger.go:105 level=error component=activeQueryTracker msg="Failed to mmap" file=data/queries.active Attemptedsize=20001 err="invalid argument"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x2f2e09f, 0x5}, 0x14, {0x382c2c0, 0x40007cc870})
	/app/promql/query_logger.go:123 +0x2f8
main.main()
	/app/cmd/prometheus/main.go:645 +0x6830
/prometheus # ls -al ./data/queries.active
-rw-r--r--    1 root     nobody       20001 Sep 21 01:17 ./data/queries.active
```

**Comment by giuseppe** [comment] 2023-09-28 09:41
I think this can be closed since it is a duplicate of https://github.com/containers/podman/issues/19639 as @Luap99 pointed out.

**Closed by giuseppe** 2023-09-28 09:41 UTC
Labels: kind/bug, remote, podman machine
