### ISSUE TITLE
Cannot set up namespace using /usr/bin/newuidmap - Rocky 9.2 Kernel 5.14 Podman 4.4.1

### ISSUE THREAD

**Issue by GCHQDeveloper211** [containers/podman#19334] opened 2023-07-24 14:07 UTC
### Issue Description

Describe your issue

When running any podman command (aiming for rootless podman), we get:
`ERRO[0000] running /usr/bin/newuidmap <pid> 0 83060 1 1 608752 65536`
`Error: cannot set up namespace using "/usr/bin/newuidmap": exit status 1`

I've been getting this issue for a couple of weeks now, since updating my server to Rocky 9.2.
We have another server that is configured by someone else that is also running Rocky 9.2, this one seems to be working. But the error we are seeing is reproducible on a rebuild of the server.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Execute any podman command. Including podman system migrate

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

Expected podman commands to run, e.g podman ps, would list running containers

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

We cannot run podman info as a user, but as root, we get:

host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-1.el9_2.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: e6cdc9a4d6319e039efa13e532c1e58b713c904d'
  cpuUtilization:
    idlePercent: 99.76
    systemPercent: 0.07
    userPercent: 0.18
  cpus: 32
  distribution:
    distribution: '"rocky"'
    version: "9.2"
  eventLogger: journald
  hostname: <not needed>
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-284.11.1.el9_2.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 400244948992
  memTotal: 403770892288
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.4-1.el9_2.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.0-3.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 0h 39m 45.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.com
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 211281186816
  graphRootUsed: 1769046016
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1683632637
  BuiltTime: Tue May  9 11:43:57 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: limux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

Running on a Rocky 9.2 box
Kernel 5.14
Podman 4.4.1

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by GCHQDeveloper211** [comment] 2023-07-24 14:24
/etc/subuid and /etc/subgid look like:
`user1:150000:65536`
`user2:215536:65536`
etc etc

And an `ls -lahZ` on the files shows:
`-rw-r--r-- 1 root root ? 166 Jul 24 14:20 /etc/subgid`
`-rw-r--r-- 1 root root ? 166 Jul 24 14:20 /etc/subuid`

**Comment by rhatdan** [comment] 2023-07-24 15:58
@giuseppe PTAL

**Comment by giuseppe** [comment] 2023-07-25 09:04
I see you have used a different range when trying it out manually:

```
 $ unshare -U sleep 100 &
$ newuidmap $! 0 608572 65536
$ newgidmap $! 0 608572 65536
```

compared to what is used by Podman:

```
ERRO[0000] running `/usr/bin/newuidmap 5602 0 83715 1 1 281072 65536`
Error: cannot set up namespace using "/usr/bin/newuidmap": exit status 1
```

What do you get if you try the same values with the same user?

```
 $ unshare -U sleep 100 &
$ newuidmap $! 0 83715 1 1 281072 65536
```

How was the session created?  Is the `USER` environment variable correct?

**Comment by GCHQDeveloper211** [comment] 2023-07-25 12:43
The USER environment variable is correct. And I get the same output (successful) result for executing the correct neuidmap command (I had swapped users when attempting it before to see if I got the same results across multiple users)

**Comment by giuseppe** [comment] 2023-07-25 14:14
don't see why it is any different than podman executing it.

Is there any useful information in the journal?

Could you try the latest upstream version?

**Comment by GCHQDeveloper211** [comment] 2023-07-25 15:42
Installed latest podman 4.6.0-rc2, and still getting the same errors

**Comment by GCHQDeveloper211** [comment] 2023-07-31 12:47
Upon further investigation into debugging, I should iterate that the server we are running this on has home directories NFS mounted.

We have a libpod.conf file in ~/.config/containers/ set as:
```
volume_path = "/data/podman-store/<user-id>/volumes"
image_default_transport = "docker://"
runtime = "runc"
conmon_path = ["/usr/libexec/podman/conmon", "/usr/local/lib/podman/conmon", "/usr/bin/conmon", "/usr/sbin/conmon", "/usr/local/bin/conmon", "/usr/local/sbin/conmon"]
conmon_env_vars = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]
cgroup_manager = "cgroupfs"
init_path = "/usr/libexec/podman/catatonit"
static_dir = "/data/podman-store/<user-id>/libpod"
tmp_dir = "/tmp/run-<uid>/libpod/tmp"
max_log_size = -1
no_pivot_root = false
cni_config_dir = "/etc/cni/net.d/"
cni_plugin_dir = ["/usr/libexec/cni", "/usr/lib/cni", "/usr/local/lib/cni", "/opt/cni/bin"]
infra_image = "k8s.gcr.io/pause:3.1"
infra_command = "/pause"
enable_port_reservation = true
label = true
network_cmd_path = ""
num_locks = 2048
events_logger = "journald"
EventsLogFilePath = ""
detach_keys = "ctrl-p,ctrl-q"

[runtime]
  runc = ["/usr/bin/runc", "/usr/sbin/runc", "/usr/local/bin/runc", "/usr/local/sbin/runc", "/sbin/runc", "/bin/runc", "/usr/lib/cri-o-runc/sbin/runc"]
```

We also have a storage.conf located in the same space:

```
[storage]
  driver = "overlay"
  runroot = "/run/user/<uid>
  graphroot = "/data/podman-store/<user-id>/storage"
  rootless_storage_path = "/data/podman-store/<user-id>/storage"
  [storage.options]
    [storage.options.overlay]
      mount_program = "/usr/bin/fuse-overlayfs"
```

Hopefully this information can assist in further debugging

**Comment by GCHQDeveloper211** [comment] 2023-08-08 07:58
I have tried this on a Rocky 9.2 build with no nfs mounted home directory, and this still breaks.
After attempting this on a Rocky 8.7 build running podman 4.2.0, everything works.

**Comment by giuseppe** [comment] 2023-08-08 09:53
I am still not able to reproduce it locally.

Since you are able to reproduce it so easily, could you try to bisect v4.2 and v.4.4.0 and see what commit is causing the issue for you?

**Comment by GCHQDeveloper211** [comment] 2023-08-08 10:40
Apologies to burst the bubble, but it seems that upon running Rocky 9.1 (where podman 4.2.0 is available) we still see the same issue. So it seems it may not be podman itself, but rather podmans compatibility with Rocky 9.X. At least with our config outlined in the previous comments

**Comment by giuseppe** [comment] 2023-08-08 11:04
would it be possible for you to try reproducing it with CentOS Stream and the same configuration?

**Comment by GCHQDeveloper211** [comment] 2023-08-16 13:39
Hello,

Thanks for all the assistance, we have managed to find the issue/solution. It seems some interaction of a podman dependancy or podman itself between RHEL 7/8 and RHEL 9 requires that /etc/login.defs be world readable (0644) which is the standard behaviour of that file, but some security polices, ensure that the file is just readable to user and group (0640).
Changing this to 0644 fixes the issues we were seeing.

Hopefully this can help either insert a better debug, or find a work around, or just leave it as is.

Otherwise, the ticket can be closed. And thanks again.

**Comment by rhatdan** [comment] 2023-08-16 18:31
I have a feeling this is something to do with newuidmap.

**Comment by giuseppe** [comment] 2023-08-17 09:33
thanks for letting us know.  I am closing the issue now

**Closed by giuseppe** 2023-08-17 09:33 UTC
Labels: kind/bug
