### ISSUE TITLE
"No route to host" while trying to curl to the container connected to multiple networks using netavark

### ISSUE THREAD

**Issue by yklin2022** [containers/podman#13871] opened 2022-04-14 02:11 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When a container is publishing ports with <host_ip>:port, and is connected to multiple (non-internal) bridge network, using the network backend netavark, trying to curl the container with <host_ip>:port failed with "No route to host"

**Steps to reproduce the issue:**

1. Create two bridge networks
podman network create --driver=bridge --subnet=192.168.230.0/24 network_main
podman network create --driver=bridge --subnet=192.168.228.0/24 network_sub

2. Create two containers
podman run -d  --network=network_main -p 10.85.41.219:9000:8080 --name nginx docker.io/bitnami/nginx:latest
podman run -d  --network=network_main -p 10.85.41.219:9090:8080 --name nginx123 docker.io/bitnami/nginx:latest

After running these commands, from the host
curl 10.85.41.219:9000
curl 10.85.41.219:9090
both are working.

3. Connect network_sub to container nginx
podman network connect network_sub nginx

**Describe the results you received:**
After running the above commands, while firing curl command from host:
curl 10.85.41.219:9000 shows "No route to host", which is container nginx, connected to network_main and network_sub
curl 10.85.41.219:9090 still works, which is container nginx123, only connects to network_main

**Describe the results you expected:**
curl 10.85.41.219:9000 should work as well

**Additional information you deem important (e.g. issue happens only occasionally):**
Firewalld is disabled on the host

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.0
API Version:  4.0.0
Go Version:   go1.17.7

Built:      Mon Feb 21 13:35:55 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+el8.4.0+11822+6cc1e7d7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: ae467a0c8001179d4d0adf4ada381108a893d7ec'
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: xyz
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.40.2.el8_4.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 58189189120
  memTotal: 66800742400
  networkBackend: netavark
  ociRuntime:
    name: runc
    package: runc-1.0.0-74.rc95.module+el8.4.0+11822+6cc1e7d7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.4.0+11822+6cc1e7d7.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 68719472640
  swapTotal: 68719472640
  uptime: 15m 48.44s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 9
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.0
  Built: 1645479355
  BuiltTime: Mon Feb 21 13:35:55 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.0

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.0-3.module+el8.6.0+14305+6b14f34e.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, we also tried the Podman 4.0.2, the behavior is the same

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment] 2022-04-14 12:09
You run as root, correct?

**Comment by yklin2022** [comment] 2022-04-14 17:06
Yes, I'm running as root

**Comment by Luap99** [comment] 2022-04-20 10:58
I cannot reproduce with the latest version, what is your netavark version. `/usr/libexec/podman/netavark version` should show it.

Can you also provide the `iptables -nvL -t nat` output?

**Comment by yklin2022** [comment] 2022-04-20 23:33
netavark version:
```
{
  "version": "1.0.0",
  "commit": "78e556ee22452bf70b1a0daffb0a98cd124e8354",
  "build_time": "2022-02-23T21:10:35.218058613+00:00",
  "target": "x86_64-unknown-linux-gnu"
}
```

Output from ```iptables -nvL -t nat```
```
Chain PREROUTING (policy ACCEPT 82 packets, 12788 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 NETAVARK-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 55 packets, 9677 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 12 packets, 846 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   13   900 NETAVARK-HOSTPORT-MASQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    1    54 NETAVARK-B0056C8D26F12  all  --  *      *       192.168.230.0/24     0.0.0.0/0           
    0     0 NETAVARK-7BBEAEAFF2139  all  --  *      *       192.168.228.0/24     0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 10 packets, 720 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    4   234 NETAVARK-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain NETAVARK-B0056C8D26F12 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    1    54 ACCEPT     all  --  *      *       0.0.0.0/0            192.168.230.0/24    
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4         

Chain NETAVARK-HOSTPORT-SETMARK (4 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x2000

Chain NETAVARK-HOSTPORT-MASQ (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* netavark portfw masq mark */ mark match 0x2000/0x2000

Chain NETAVARK-DN-B0056C8D26F12 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 NETAVARK-HOSTPORT-SETMARK  tcp  --  *      *       192.168.230.0/24     10.85.41.219         tcp dpt:9000
    0     0 NETAVARK-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            10.85.41.219         tcp dpt:9000
    3   180 DNAT       tcp  --  *      *       0.0.0.0/0            10.85.41.219         tcp dpt:9000 to:192.168.230.2:8080

Chain NETAVARK-HOSTPORT-DNAT (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    3   180 NETAVARK-DN-B0056C8D26F12  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:9000 /* dnat name: network_main id: 533884d9460dd2728b1165901e3fbb6da708c535f7446fdd7138111c679944c8 */
    0     0 NETAVARK-DN-7BBEAEAFF2139  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:9000 /* dnat name: network_sub id: 533884d9460dd2728b1165901e3fbb6da708c535f7446fdd7138111c679944c8 */

Chain NETAVARK-7BBEAEAFF2139 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            192.168.228.0/24    
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4         

Chain NETAVARK-DN-7BBEAEAFF2139 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 NETAVARK-HOSTPORT-SETMARK  tcp  --  *      *       192.168.228.0/24     10.85.41.219         tcp dpt:9000
    0     0 NETAVARK-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            10.85.41.219         tcp dpt:9000
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.85.41.219         tcp dpt:9000 to:192.168.228.2:8080

```

**Comment by rhatdan** [comment] 2022-05-23 20:40
@Luap99 Anything further on this?

**Comment by Luap99** [comment] 2022-05-24 16:04
This seems to be a RHEL only issue closing this in favour of https://bugzilla.redhat.com/show_bug.cgi?id=2075373

**Closed by Luap99** 2022-05-24 16:04 UTC
Labels: kind/bug, network

**Comment by micheljung** [comment] 2022-09-26 06:40
@Luap99 do you remember what this bug was about? 

> You are not authorized to access bug #2075373. To see this bug, you must first [log in to an account](https://bugzilla.redhat.com/show_bug.cgi?id=2075373&GoAheadAndLogIn=1) with the appropriate permissions.
