### ISSUE TITLE
Can't init machine of windows 11

### ISSUE THREAD

**Issue by Evan7o** [containers/podman#14954] opened 2022-07-17 12:52 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.download 4.1.1 podman .msi file and installed

2.run ```podman machine init```, auto install wsl on my 🖥, and get error:
```Error: head request failed: http://github.com/fedora-cloud/docker-brew-fedora/raw/35/x86_64/fedora-35-x86_64.tar.xz: Head "https://raw.githubusercontent.com/fedora-cloud/docker-brew-fedora/35/x86_64/fedora-35-x86_64.tar.xz": dial tcp: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.```
3.downloaded fedora 35 images to local, and i try run ```podman machine init --image-path D:Downloads/fedora-35-x86_64.tar.xz```
get error:``` Error: open C:\Users\EvanYou\.local\share\containers\podman\machine\wsl: is a directory ```
**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman.exe version 4.1.1
(paste your output here)
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Laptop computer（Windows11Pro 21H2 22000.795）

**Comment by Luap99** [comment] 2022-07-18 14:19
I think this is a duplicate of #14495
@n1hility PTAL

**Comment by n1hility** [comment] 2022-07-18 14:49
Agree looks like the same issue. Reopen if you determine thats not the case. If DNS does not work it's usually a firewall/Windows Defender issue, or a VPN which is dropping packets between the WSL VMs network and the Windows host network. In 4.2 (already in RC) we are switching to a prebuilt image, and that will make workarounds simpler. If you want to resolve the underlying I have a note in that issue https://github.com/containers/podman/issues/14495#issuecomment-1159240529

**Closed by n1hility** 2022-07-18 14:49 UTC
Labels: kind/bug, podman machine, windows
