### ISSUE TITLE
request for a bcachefs storage driver

### ISSUE THREAD

**Issue by holmanb** [containers/podman#21357] opened 2024-01-24 23:36 UTC
### Feature request description

Bcachefs was merged into the upstream linux kernel in 6.7, and contains support for snapshots with an API similar to btrfs. Bcachefs claims to have better snapshot scalability (and scalability in general) than btrfs.

### Suggest potential solution

Is a storage driver for bcachefs a feature that the podman team would be willing to develop? 

### Have you considered any alternatives?

Would a storage driver for bcachefs be a contribution that the podman team would be willing to review and consider merging?

**Comment by Luap99** [comment] 2024-01-25 10:32
Duplicate of https://github.com/containers/storage/issues/1744

**Closed by Luap99** 2024-01-25 10:32 UTC
Labels: kind/feature
