### ISSUE TITLE
podman image scp should allow specifying image by hash name with remote connection

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/podman#14313] opened 2022-05-21 22:22 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

`podman image scp` should allow specifying image by hash name, even with remove connections.

**Steps to reproduce the issue:**

1. Setup two remote connections, in my case `aarch64` and `x86_64`.

2. Try to `podman image save` and `podman image load` from one connection to another using only an image hash, it works:

```
[root@e988f777948b /]# podman -c aarch64 image save 73440715a548019127335111c8b8c94b443f7a6024bcfd0a3a07835e5e5d2659 | podman -c x86_64 image load
Loaded image(s): sha256:73440715a548019127335111c8b8c94b443f7a6024bcfd0a3a07835e5e5d2659
```

3. Try a similar thing with podman scp, it fails:

```
[root@e988f777948b /]# podman image scp aarch64::73440715a548019127335111c8b8c94b443f7a6024bcfd0a3a07835e5e5d2659 x86_64::
Error: invalid repository name (73440715a548019127335111c8b8c94b443f7a6024bcfd0a3a07835e5e5d2659), cannot specify 64-byte hexadecimal strings
```

**Describe the results you received:**

Error: invalid repository name (73440715a548019127335111c8b8c94b443f7a6024bcfd0a3a07835e5e5d2659), cannot specify 64-byte hexadecimal strings

**Describe the results you expected:**

It should work with no error when specifying an image by hash.

**Output of `podman version`:**

```
[root@e988f777948b /]# podman version
Client:       Podman Engine
Version:      4.2.0-dev
API Version:  4.2.0-dev
Go Version:   go1.16.15
Git Commit:   68e45555b3dfc9662ce71b6ff548b43c9ea8d50c
Built:        Mon May  9 18:23:55 2022
OS/Arch:      linux/amd64```

**Comment by cdoern** [comment] 2022-05-24 13:33
yeah, this is definitely doable and should be implemented, I will tackle this.

**Comment by cdoern** [comment] 2022-06-01 17:54
labeling as a bug since this is expected behavior

**Comment by rhatdan** [comment] 2022-07-02 10:52
@cdoern what is going on with this issue?

**Comment by cdoern** [comment] 2022-07-02 15:51
@rhatdan I have a branch ready for a PR I just needed the remote SCP PR to merge. Now that it has I will make one asap for this.

**Comment by Romain-Geissler-1A** [comment] 2022-08-02 19:47
Hi @cdoern,

Do you still have the pull request ready for this ? I tried the latest podman, and now the error we get is this one (extracted from a real jenkins job right now):

```
[2022-08-02T19:41:58.105Z] + podman image scp aarch64::sha256:c22f18f37c05bdc5999fb654f8801dc465e2b2a52fb5de887907ea89a27bee09 x86_64::
[2022-08-02T19:41:58.105Z] Error: failed to connect: dial tcp: missing address
```

Cheers,
Romain

**Comment by cdoern** [comment] 2022-08-02 20:07
sorry Romain, this one totally slipped through the cracks. Will make a PR today

**Comment by Romain-Geissler-1A** [comment] 2022-08-02 20:09
Ah, it's because I used the "sha256:" prefix that we get as an output of `podman image build --iidfile`:

```
Error: invalid repository name (2ecb6df959942dd2fdeb65606ca2e42a54f8c06af10eeb594fdfc3e2656c53d1), cannot specify 64-byte hexadecimal strings
[root@ead76803be83 /]# podman image scp aarch64::sha256:2ecb6df959942dd2fdeb65606ca2e42a54f8c06af10eeb594fdfc3e2656c53d1 x86_64::
Error: failed to connect: dial tcp: missing address
```

In the end, will you support both syntaxes ?

**Comment by cdoern** [comment] 2022-08-02 20:16
actually... I am going to fold this into #15094 so I do not need to unnecessarily rebase against code that is about to fully change. this will be in 4.3 for sure, and will be in main in a few days fingers crossed @Romain-Geissler-1A

**Comment by Romain-Geissler-1A** [comment] 2022-08-02 20:23
Ah I will finally be able to use all my ssh host alias + configuration I have in `~/.ssh/config` using the new flag `--ssh=native` ? That's cool, I wished I had this since quite some time actually, instead of copying the same config in my containers.conf file !

On my side I can test these the podman scp changes as soon as it's merged and integrated into a `quay.io/podman/upstream` nightly image.

**Comment by cdoern** [comment] 2022-09-02 15:45
this is completed

**Closed by cdoern** 2022-09-02 15:45 UTC
Labels: kind/bug

**Comment by Romain-Geissler-1A** [comment] 2022-09-06 18:42
Hi @cdoern,

I just tried the latest image `quay.io/podman/upstream`, and here is the error I have (`aarch64` and `x86_64` are names of two distinct remote connections):

```
20:40:11  + podman image scp aarch64::sha256:633feaece5c2c503aeb79f6d8283934871f610cfe71119169768ccb2a25b4b1c x86_64::
20:40:11  Error: strconv.Atoi: parsing "": invalid syntax
```

Cheers,
Romain
