### ISSUE TITLE
crun:    chdir: Not a directory : exit status 1

### ISSUE THREAD

**Issue by kallisti5** [containers/podman#10877] opened 2021-07-07 21:42 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman no longer working again

**Steps to reproduce the issue:**

1. ArchLinux
2. Build a container

**Describe the results you received:**
```
$ make
docker build --no-cache --tag docker.io/haiku/trac:1.4.0 .
STEP 1: FROM docker.io/python:2.7-alpine
STEP 2: WORKDIR /app
--> cf5a0438572
STEP 3: ADD requirements.txt /app
--> 5548b46fde8
STEP 4: RUN apk update &&     apk add --virtual build-deps gcc python-dev musl-dev &&     apk add git postgresql-dev curl
error running container: error from /usr/bin/crun creating container for [/bin/sh -c apk update &&     apk add --virtual build-deps gcc python-dev musl-dev &&     apk add git postgresql-dev curl]: chdir: Not a directory
: exit status 1
Error: error building at STEP "RUN apk update &&     apk add --virtual build-deps gcc python-dev musl-dev &&     apk add git postgresql-dev curl": error while running runtime: exit status 1
make: *** [Makefile:2: default] Error 125
```

**Describe the results you expected:**

Not to error :-)

**Output of `podman version`:**

```
$ podman version
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.16.5
Git Commit:   d577c44e359f9f8284b38cf984f939b3020badc3
Built:        Mon Jun 28 15:13:34 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.29-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 7e6de6678f6ed8a18661e1d5721b81ccee293b9b'
  cpus: 16
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: eris.discord.local
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 985
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
  kernel: 5.12.14-arch1-1
  linkmode: dynamic
  memFree: 35175088128
  memTotal: 67394387968
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 0.20.1-1
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 38271d1c8d9641a2cdc70acfa3dcb6996d124b3d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.11-1
    version: |-
      slirp4netns version 1.1.11
      commit: 368e69ccc074628d17a9bb9a35b8f4b9f74db4c6
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 16835670016
  swapTotal: 17179865088
  uptime: 8h 53m 43.59s (Approximately 0.33 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/kallisti5/.config/containers/storage.conf
  containerStore:
    number: 51
    paused: 0
    running: 0
    stopped: 51
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: /usr/bin/fuse-overlayfs is owned by fuse-overlayfs 1.6-1
      Version: |-
        fusermount3 version: 3.10.4
        fuse-overlayfs: version 1.6
        FUSE library version 3.10.4
        using FUSE kernel interface version 7.31
  graphRoot: /home/kallisti5/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 678
  runRoot: /run/user/1000/containers
  volumePath: /home/kallisti5/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.2
  Built: 1624911214
  BuiltTime: Mon Jun 28 15:13:34 2021
  GitCommit: d577c44e359f9f8284b38cf984f939b3020badc3
  GoVersion: go1.16.5
  OsArch: linux/amd64
  Version: 3.2.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ sudo pacman -Ss podman | grep installed
community/podman 3.2.2-1 [installed]
community/podman-compose 0.1.5-2 [installed]
community/podman-docker 3.2.2-1 [installed]
```

**Comment by mheon** [comment] 2021-07-07 22:13
Looks like a Buildah issue - @nalind @TomSweeneyRedHat PTAL

**Comment by Luap99** [comment] 2021-07-08 07:31
Duplicate of https://github.com/containers/podman/issues/10671, check this issue for a workaround.

**Closed by Luap99** 2021-07-08 07:31 UTC
Labels: Buildah, kind/bug
