### ISSUE TITLE
Debian / Ubuntu envs in upstream CI

### ISSUE THREAD

**Issue by lsm5** [containers/podman#11070] opened 2021-07-28 18:49 UTC
Our upstream CI currently tests 2 current ubuntus (typically 1 LTS + 1 latest release). This tends to be a problem every time an Ubuntu release goes EOL and we have to prepare for a new Ubuntu release (An EOL occurs every 6-9 months IIUC).

We would like to have Debian and/or Ubuntu versions in our upstream CI so that we have:
- low maintenance
- early indicators of failures/problems
- reasonable certainty that CI experience would match user experience :)

Hopefully, limit to 2 environments in total.

With that in mind, I think replacing 2 current Ubuntus with `Latest Ubuntu LTS + Debian Sid` could be a good combo of stable + bleeding edge + account for most users (or maybe that's just my imagination)

@siretart @cevich and others, WDYT ?

**Comment by cevich** [comment] 2021-07-28 18:54
Adding another OS into the mix sounds scary as it would potentially bring in a whole new set of challenges.  So my preference would be something more like: Drop Ubuntu entirely and only test Debian Sid (bleeding edge).  This would more closely mirror what we do with Fedora (except they have two bleeding edges) - i.e. we're not testing CentOS or RHEL in upstream.

**Comment by vrothberg** [comment] 2021-07-29 07:30
IMHO it's important to test on the latest Ubuntu to catch potential regressions early.  Ubuntu is a very popular distro among developers.

I think that Ubuntu is too different from Debian to have a high confidence level.

**Comment by siretart** [comment] 2021-07-29 14:13
If you want to minimize the number of platforms to build for, I'd suggest to limit to

1. most recent debian/stable release (next release scheduled for **8/14/2021**)
2. most recent ubuntu LTS

For users that prefer a newer version of debian, I'd recommend using the packages from debian/experimental. They will work just fine on every debian/testing installation. The documentation  could point to https://wiki.debian.org/AptConfiguration?action=show&redirect=AptPinning for suggestion how to enable auto-updates for these users

For users that prefer a newer version of ubuntu, the packages for the most recent LTS *have* to work for newer versions of ubuntu as well. (if that wasn't the case, we'd have found a broken upgrade path that needs to be fixed anyways). The "apt pinning" trick I pointed out above would work here equally well.

**Comment by lsm5** [comment] 2021-07-29 14:19
@siretart sorry about any phrasing issues in my original post, this was mainly RE: testing of every upstream PR on ubuntu/debian environments on Cirrus CI. It doesn't involve actually building/shipping packages to end users. 

But I guess your suggestion about recent ubuntu LTS + recent debian release would also apply to simple PR testing ?

**Comment by siretart** [comment] 2021-07-29 15:18
Yes, I think that still holds.

Do you have control over the kernel being used in CI? -- Presumably Cirrus CI is running in containers and thus is using a more recent kernel than the distro provides, so we should be fine from that front.

I'd argue that you provide maximum value in form of confidence of platform coverage by being conservative in the choices of platforms at the expense of developer convenience and having to deal with "old" dependencies.

**Comment by cevich** [comment] 2021-08-03 18:33
> Do you have control over the kernel being used in CI?

Yes

> I'd argue that you provide maximum value

Remember, we're talking _just_ about upstream developer-centric ("shift-left") testing. This doesn't affect downstream, they're free to run on whatever platform(s) are relevant.  So developer-convenience really is the name of the game, up to a point of balance vs 100% downstream testing.

---

Since I'm largely the one maintaining the VM and container images we use for testing, I can say that maintaining two versions of two platforms, across all our big projects is quite heavy.  Adding a third platform (Debian) would be an additional burden, not less.  If we go with Debian, it would need to entirely replace either Ubuntu or Fedora.  In other words, a third platform would represent a whole new/separate set of scripts and build instructions.

Given the misalignment of release and support schedules, it seems like only testing the latest Ubuntu + two Fedoras (one for runc) might be the best compromise.  Though that means potentially still supported downstream releases discover bugs, where upstream fixes are more costly (vs finding them earlier w/ CI testing).

**Comment by rhatdan** [comment] 2021-09-07 17:11
@lsm5 @cevich what is happening with this issue?

**Comment by cevich** [comment] 2021-09-07 20:26
IMHO we can close this and continue on as-is, or drop the "previous-ubuntu" VMs to save a medium-small amount of headache.  I don't have the bandwidth to add/maintain a third distro in our CI.  I also don't think wholly dropping Ubuntu for Debian would be a good move.  Of course if somebody else wants to do the Debian work, I'll certainly consult on that effort as I'm able :smiley:

**Closed** 2021-09-07 20:34 UTC

**Comment by cevich** [comment] 2021-09-09 15:29
Followup: Talked this over with the team, and decided to drop "previous-ubuntu" across container-CI.  We're using such a customized set of CI-only packages (maintained by Lokesh) the disparity between "as-tested" and "user experience" will always be larger for that release.  OTOH, the "latest" Ubuntu will remain much closer compared to these custom packages used in upstream testing.
