### ISSUE TITLE
[packaging] podman-docker: kubic package for ubuntu creates weird /usr/bin/docker

### ISSUE THREAD

**Issue by Timost** [containers/podman#18611] opened 2023-05-17 16:08 UTC
### Issue Description

Thank for podman ❤️ 

I'm using podman installed directly within an WSL2 ubuntu 22.04 instance.
The package is installed from the unstable kubic repository.

When installing `podman-docker` the resulting `/usr/bin/docker` looks weird (see below)
```
#!/bin/sh
[ -e /home/abuild/debbuild/BUILDROOT/podman-4.5.0-0ubuntu22.04+obs74.12.amd64/etc/containers/nodocker ] || \
echo "Emulate Docker CLI using podman. Create /home/abuild/debbuild/BUILDROOT/podman-4.5.0-0ubuntu22.04+obs74.12.amd64/etc/containers/nodocker to quiet msg." >&2
exec /home/abuild/debbuild/BUILDROOT/podman-4.5.0-0ubuntu22.04+obs74.12.amd64/usr/bin/podman "$@"
```
There is nothing at `/home/abuild/debbuild/BUILDROOT/podman-4.5.0-0ubuntu22.04+obs74.12.amd64/usr/bin/podman` and I have to patch that file manually to point to `/usr/bin/podman`

I know that the kubic repos are made on a "best effort" basis though.

### Steps to reproduce the issue

Steps to reproduce the issue
1. On an ubuntu 22.04 WSL instance
2. set up kubic repos as described here https://podman.io/docs/installation#ubuntu
3. `apt install podman`
4. `apt install podman-docker`
5. `cat  /usr/bin/docker`

### Describe the results you received

```
#!/bin/sh
[ -e /home/abuild/debbuild/BUILDROOT/podman-4.5.0-0ubuntu22.04+obs74.12.amd64/etc/containers/nodocker ] || \
echo "Emulate Docker CLI using podman. Create /home/abuild/debbuild/BUILDROOT/podman-4.5.0-0ubuntu22.04+obs74.12.amd64/etc/containers/nodocker to quiet msg." >&2
exec /home/abuild/debbuild/BUILDROOT/podman-4.5.0-0ubuntu22.04+obs74.12.amd64/usr/bin/podman "$@"
```
There is nothing at `/home/abuild/debbuild/BUILDROOT/podman-4.5.0-0ubuntu22.04+obs74.12.amd64/usr/bin/podman` and I have to patch that file manually to point to `/usr/bin/podman`

### Describe the results you expected

Working `/usr/bin/docker` alias

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon_2:2.1.7-0ubuntu22.04+obs15.26_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 98.34
    systemPercent: 0.43
    userPercent: 1.23
  cpus: 16
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: LA-23-055
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 6742016000
  memTotal: 16475512832
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_101:1.8.4-0ubuntu22.04+obs55.12_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-0ubuntu22.04+obs10.65_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 28h 17m 4.00s (Approximately 1.17 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/timost/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/timost/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 27414286336
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/timost/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

podman installed directly inside a WSL2 instance with systemd enabled

**Comment by lsm5** [comment] 2023-05-17 17:33
ya, that one was caused by the new envsubst thing in the Makefile. I'll see what I can do.

**Comment by Timost** [comment] 2023-05-22 08:31
For the record, I just tested on a pure ubuntu system and the issue is the same (no surprise there), I'm removing the WSL2 in the title

**Comment by lsm5** [comment] 2023-05-22 14:24
latest build should fix it. Check it out.

**Comment by lsm5** [comment] 2023-05-22 20:25
Closing.. please reopen if issue persists.

**Closed by lsm5** 2023-05-22 20:25 UTC
Labels: kind/bug, Packaging

**Comment by Timost** [comment] 2023-05-24 09:51
Retried today, it's working ! 👍

Thanks a lot for fixing the issue ! 🙏🙏🙏
