### ISSUE TITLE
unmounting/EINVAL flake

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18831] opened 2023-06-08 20:27 UTC
Two new flakes seen in #13808 (buildah treadmill):
```
<+009ms> # # podman-remote --url unix:/tmp/podman_tmp_9HtW pod rm c3cc31049b088d86ef22ad5b279ce5c1d01b88887116bc9f6486b9b0a28f2080
<+104ms> # Error: 2 errors occurred:
         # 	* removing container 0c7966924a988d4e00f2585da31627a0db0621e6fbd6531cea4d02779e3bcfe2 from pod c3cc31049b088d86ef22ad5b279ce5c1d01b88887116bc9f6486b9b0a28f2080: cleaning up storage: removing container 0c7966924a988d4e00f2585da31627a0db0621e6fbd6531cea4d02779e3bcfe2 root filesystem: unmounting "/var/lib/containers/storage/overlay/4e8aaf7a108d0bf91f873379b4558162620f9e4ffaca942d06ef4d40778456bc/merged": invalid argument
         # 	* removing container 55ade4c16aa0fffb758fc893be4d24c8fdaabcde14eec89df7885b42c4b03881 from pod c3cc31049b088d86ef22ad5b279ce5c1d01b88887116bc9f6486b9b0a28f2080: cleaning up storage: removing container 55ade4c16aa0fffb758fc893be4d24c8fdaabcde14eec89df7885b42c4b03881 root filesystem: unmounting "/var/lib/containers/storage/overlay/1ef8c38e52bd1d345801a0a4a7b2e0631b85965881be472dcb6db0afd6c3a65b/merged": invalid argument
```
Once they happen, everything is hosed: all subsequent tests fail.

This is sooooooo close to #17216 (unlinkat/EBUSY) that I'm 99.99% convinced it's the same bug, just a different manifestation (presumably because of new containers/whatever). If that turns out to be the case, I'll close this issue and merge these flakes there.

* debian-12 : sys remote debian-12 root host boltdb [remote]
    * [06-08 15:08](https://api.cirrus-ci.com/v1/artifact/task/4726381167247360/html/sys-remote-debian-12-root-host-boltdb.log.html#t--00550) in [sys] podman play
* fedora-38-aarch64 : sys remote fedora-38-aarch64 root host boltdb [remote]
    * [06-08 15:08](https://api.cirrus-ci.com/v1/artifact/task/5852281074089984/html/sys-remote-fedora-38-aarch64-root-host-boltdb.log.html#t--00319) in [sys] pod exit policies

**Comment by rhatdan** [comment] 2023-06-10 10:57
As I recall making the storage private was because of leaked mounts when we were using Devicemapper.  Not sure if this still applies, but that was a huge problem back in the early Docker days.

**Comment by mtrmac** [comment] 2023-06-12 20:30
> it looks like the default c/storage behaviour is to make the container store use private by default.

(Just to be explicit, that should be possible turn off with `skip_mount_home=true`.)

**Comment by edsantiago** [comment] 2023-06-12 21:37
This is now triggering in main. [debian root](https://api.cirrus-ci.com/v1/artifact/task/4847177860644864/html/sys-remote-debian-12-root-host-sqlite.log.html#t--00553)

**Comment by Luap99** [comment] 2023-06-13 08:26
> > it looks like the default c/storage behaviour is to make the container store use private by default.
> 
> (Just to be explicit, that should be possible turn off with `skip_mount_home=true`.)

Yes I found that option, https://github.com/containers/podman/commit/68183b07d634622bce28a06e068e0e6f595b3d36

**Comment by edsantiago** [comment] 2023-06-13 16:42
Is anyone working on fixing this? 

* debian-12 : sys remote debian-12 root host sqlite [remote]
    * [06-13 11:03](https://api.cirrus-ci.com/v1/artifact/task/4697452750569472/html/sys-remote-debian-12-root-host-sqlite.log.html#t--00435) in [sys] podman run with slirp4ns adds correct dns address to resolv.conf
    * [06-12 15:26](https://api.cirrus-ci.com/v1/artifact/task/4847177860644864/html/sys-remote-debian-12-root-host-sqlite.log.html#t--00553) in [sys] podman kube play read-only
* fedora-37 : sys remote fedora-37 root host sqlite [remote]
    * [06-12 18:13](https://api.cirrus-ci.com/v1/artifact/task/5174689283178496/html/sys-remote-fedora-37-root-host-sqlite.log.html#t--00295) in [sys] podman --group-add keep-groups plus added groups

**Comment by edsantiago** [comment] 2023-07-31 13:04
This is still hitting us hard.

* debian-12 : sys remote debian-12 root host boltdb [remote]
  * PR #19302
    * [07-25 11:12](https://api.cirrus-ci.com/v1/artifact/task/6705447202193408/html/sys-remote-debian-12-root-host-boltdb.log.html#t--00561) in [sys] podman play
  * PR #19189
    * [07-10 17:26](https://api.cirrus-ci.com/v1/artifact/task/4744967151681536/html/sys-remote-debian-12-root-host-boltdb.log.html#t--00566) in [sys] podman kube play - default log driver
  * PR #19180
    * [07-10 11:14](https://api.cirrus-ci.com/v1/artifact/task/6332036437245952/html/sys-remote-debian-12-root-host-boltdb.log.html#t--00558) in [sys] podman kube --network
* fedora-37 : sys remote fedora-37 root host boltdb [remote]
  * PR #19261
    * [07-18 10:20](https://api.cirrus-ci.com/v1/artifact/task/4801040986406912/html/sys-remote-fedora-37-root-host-boltdb.log.html#t--00563) in [sys] podman kube play read-only
  * PR #19211
    * [07-14 10:24](https://api.cirrus-ci.com/v1/artifact/task/5614434777825280/html/sys-remote-fedora-37-root-host-boltdb.log.html#t--00559) in [sys] podman play
* fedora-38 : sys remote fedora-38 root host boltdb [remote]
  * PR #19180
    * [07-10 11:11](https://api.cirrus-ci.com/v1/artifact/task/6683880158134272/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00317) in [sys] podman pod create --share
* fedora-38 : sys remote fedora-38 rootless host boltdb [remote]
  * PR #19367
    * [07-27 07:32](https://api.cirrus-ci.com/v1/artifact/task/6486330503331840/html/sys-remote-fedora-38-rootless-host-boltdb.log.html#t--00573) in [sys] podman kube play - default log driver
* rawhide : sys remote rawhide root host sqlite [remote]
  * PR #19196
    * [07-11 11:27](https://api.cirrus-ci.com/v1/artifact/task/4614252053397504/html/sys-remote-rawhide-root-host-sqlite.log.html#t--00318) in [sys] podman pod create --pod new: --hostname
  * PR #17831
    * [07-10 18:19](https://api.cirrus-ci.com/v1/artifact/task/5922916508893184/html/sys-remote-rawhide-root-host-sqlite.log.html#t--00321) in [sys] pod exit policies

**Comment by edsantiago** [comment] 2023-08-02 01:32
WOW! Every single `integration rootless` test in a [buildah bump-VM PR](https://cirrus-ci.com/build/5006486368157696) failed! So this has gone from a root-flake to a hard (rootless) failure. This is probably the best chance we have right now to track this down: someone with `get-ci-vm` privs, maybe get one of these new VMs and see what buildah is doing?

**Comment by edsantiago** [comment] 2023-08-07 15:01
I just got this on my laptop, rootless non-remote, after ^C'ing from a test loop:
```
d6ca8864235b6329facf2cdbb48eef7cffe4c4c1669c7e7932cf95e6d88abeed
^C%                                                                                                                                                             
$ bin/podman rm -f -a -t0
ERRO[0000] cleaning up storage: removing container 4d1b2909ce4444604c3616e268b1be978cf58d091df4130cffbb84c1a81e4532 root filesystem: unmounting "/home/esm/.local/share/containers/storage/overlay/a7660b4fa10f5ec903b8025957747358a532a1e304fffb98dbc0347fef6fba60/merged": invalid argument 
138263879a6f1ae5b80d71ad7362d0928dbf2b45c7bc7050e80a5b357f87d579
Error: cleaning up container 4d1b2909ce4444604c3616e268b1be978cf58d091df4130cffbb84c1a81e4532: unmounting container 4d1b2909ce4444604c3616e268b1be978cf58d091df4130cffbb84c1a81e4532 storage: cleaning up container 4d1b2909ce4444604c3616e268b1be978cf58d091df4130cffbb84c1a81e4532 storage: unmounting container 4d1b2909ce4444604c3616e268b1be978cf58d091df4130cffbb84c1a81e4532 root filesystem: unmounting "/home/esm/.local/share/containers/storage/overlay/a7660b4fa10f5ec903b8025957747358a532a1e304fffb98dbc0347fef6fba60/merged": invalid argument
```
Unlike this issue, a subsequent `!!` returned no output, no errors, and all is well. My system is not dead-hosed forever. Everything is back to normal. I don't know why it's ok here but hosed-forever when it happens in CI.

**Comment by edsantiago** [comment] 2023-08-28 12:10
Haven't seen this one in the last 4-5 days, but now all of a sudden:
```
# setup(): removing stray external container 8d8e6fe55654 (a669ae9cac29-infra)
         # [setup] # podman rm -f 8d8e6fe55654
         # Error: removing storage for container "8d8e6fe55654": removing mount point "/var/lib/containers/storage/overlay/b14478b250486fcac32b2a4591d781a1aadb4903753c0d8023dee6339778f936/merged": device or resource busy
         # setup(): removing stray external container d0890420d690 (test_pod-test)
         # [setup] # podman rm -f d0890420d690
         # Error: removing storage for container "d0890420d690": removing mount point "/var/lib/containers/storage/overlay/b6747d4b2f72ce2a1df040c116b76fe5b0690bfa6d120e2b62b5d838765813d9/merged": device or resource busy
         # setup(): removing stray image localhost/podman-pause:4.7.0-dev-1693138408
         # setup(): removing stray image 5b53252ec597
[+1191s] not ok 591 podman kube play - default log driver
         # (from function `die' in file test/system/[helpers.bash, line 722](https://github.com/containers/podman/blob/59f66714eee24ac05e1445c5b75d8800c59316b0/test/system/helpers.bash#L722),
         #  from function `run_podman' in file test/system/[helpers.bash, line 381](https://github.com/containers/podman/blob/59f66714eee24ac05e1445c5b75d8800c59316b0/test/system/helpers.bash#L381),
         #  in test file test/system/[700-play.bats, line 468](https://github.com/containers/podman/blob/59f66714eee24ac05e1445c5b75d8800c59316b0/test/system/700-play.bats#L468))
         #   `run_podman kube play $PODMAN_TMPDIR/test.yaml' failed
<+     > # # podman-remote --url unix:/tmp/podman_tmp_GA3f rm -t 0 --all --force --ignore
<+048ms> # # podman-remote --url unix:/tmp/podman_tmp_GA3f ps --all --external --format {{.ID}} {{.Names}}
<+046ms> # 8d8e6fe55654 a669ae9cac29-infra
         # d0890420d690 test_pod-test
<+011ms> # # podman-remote --url unix:/tmp/podman_tmp_GA3f rm -f 8d8e6fe55654
<+046ms> # Error: removing storage for container "8d8e6fe55654": removing mount point "/var/lib/containers/storage/overlay/b14478b250486fcac32b2a4591d781a1aadb4903753c0d8023dee6339778f936/merged": device or resource busy
<+006ms> # [ rc=125 ]
```
(in [f38 remote root](https://api.cirrus-ci.com/v1/artifact/task/6739981541048320/html/sys-remote-fedora-38-root-host-sqlite.log.html#t--00591)).

To recap:
* first it was **unlinkat/EBUSY**
* then **unmounting/EINVAL**
* now it's **removing storage/EBUSY**???!?!?!?

Still remote-only AFAICT.

**Comment by mtrmac** [comment] 2023-08-28 14:22
I think the original variant is pre-https://github.com/containers/storage/pull/1607 : `Driver.Put` silently ignored errors _both_ unmounting and deleting, and `unlinkat` failed in some higher layer.

The second is after https://github.com/containers/storage/pull/1607 : unmount failure is reported.

The third is after https://github.com/containers/storage/pull/1687 : unmount failure is ignored again, but deleting is now a hard failure in `Driver.Put`.

AFAICT none of this tinkering has substantially improved our understanding of the actual cause.

**Comment by edsantiago** [comment] 2023-08-30 14:27
Seen just now in [int f38 rootless non-remote](https://api.cirrus-ci.com/v1/artifact/task/4992740727980032/html/int-podman-fedora-38-rootless-host-sqlite.log.html#t---DeferCleanup--Suite----1):
```
[FAILED] DeferCleanup callback returned error: unlinkat /tmp/ginkgo892567680/root/vfs/dir/..../bin: permission denied
```
Not quite the same -- this is `int` tests, not sys; and `podman`, not remote; and `unlinkat`, not "removing storage"; and obviously it does not destroy all future test runs because `int` tests each happen with a different root. Maybe related, maybe not, am posting anyway.

**Comment by edsantiago** [comment] 2023-09-14 12:35
Hi, I know everyone's busy and that this is a hard one, but please don't forget about it.

* fedora-37 : sys remote fedora-37 root host boltdb [remote]
  * PR #19955
    * [09-13 15:26](https://api.cirrus-ci.com/v1/artifact/task/6002841370755072/html/sys-remote-fedora-37-root-host-boltdb.log.html#t--00598) in [sys] podman kube play - hostport
* fedora-38 : int podman fedora-38 rootless host sqlite
  * PR #19794
    * [08-29 11:13](https://api.cirrus-ci.com/v1/artifact/task/4992740727980032/html/int-podman-fedora-38-rootless-host-sqlite.log.html#t---DeferCleanup--Suite----1) in [DeferCleanup (Suite)]
* fedora-38 : sys remote fedora-38 root host sqlite [remote]
  * PR #19696
    * [08-24 11:18](https://api.cirrus-ci.com/v1/artifact/task/5657330277154816/html/sys-remote-fedora-38-root-host-sqlite.log.html#t--00322) in [sys] podman pod - communicating via /dev/shm
  * PR #19596
    * [08-15-2023 09:36](https://api.cirrus-ci.com/v1/artifact/task/4744027828912128/html/sys-remote-fedora-38-root-host-sqlite.log.html#t--00311) in [sys] podman --ipc=host
  * PR #17831
    * [08-27 08:50](https://api.cirrus-ci.com/v1/artifact/task/6739981541048320/html/sys-remote-fedora-38-root-host-sqlite.log.html#t--00591) in [sys] podman kube play - default log driver
    * [08-23 17:20](https://api.cirrus-ci.com/v1/artifact/task/5238176902545408/html/sys-remote-fedora-38-root-host-sqlite.log.html#t--00326) in [sys] podman pod create --pod new: --hostname
* fedora-38-aarch64 : sys remote fedora-38-aarch64 root host boltdb [remote]
  * PR #19861
    * [09-05 14:24](https://api.cirrus-ci.com/v1/artifact/task/6590764109529088/html/sys-remote-fedora-38-aarch64-root-host-boltdb.log.html#t--00599) in [sys] podman kube play --wait - wait for pod to exit
  * PR #19754
    * [08-28 11:43](https://api.cirrus-ci.com/v1/artifact/task/6119679647809536/html/sys-remote-fedora-38-aarch64-root-host-boltdb.log.html#t--00581) in [sys] podman kube --network
* rawhide : sys remote rawhide root host sqlite [remote]
  * PR #19970
    * [09-13 15:31](https://api.cirrus-ci.com/v1/artifact/task/5149582531756032/html/sys-remote-rawhide-root-host-sqlite.log.html#t--00601) in [sys] podman kube play --wait with siginterrupt
  * PR #19959
    * [09-13 10:27](https://api.cirrus-ci.com/v1/artifact/task/4677218236891136/html/sys-remote-rawhide-root-host-sqlite.log.html#t--00583) in [sys] podman play
  * PR #19929
    * [09-11 14:47](https://api.cirrus-ci.com/v1/artifact/task/6712279270424576/html/sys-remote-rawhide-root-host-sqlite.log.html#t--00594) in [sys] podman play Yaml --no-trunc with annotation > Max

Seen in: int/sys podman/remote fedora-37/fedora-38/fedora-38-aarch64/rawhide root/rootless host boltdb/sqlite

**Comment by edsantiago** [comment] 2023-09-19 14:23
Here's a variant that I don't recognize ([f37 remote root](https://api.cirrus-ci.com/v1/artifact/task/5881317955469312/html/sys-remote-fedora-37-root-host-boltdb.log.html#t--00330)):
```
<+027ms> # podman run --rm --pod new:xjbur0qugi --hostname foobar quay.io/libpod/testimage:20221018 hostname
<+374ms> Error: failed to make pod: building local pause image: deleting build container "e40fcfa654072d9434bebfed49e6b3724c1f04f569adc601e91bf39e83b3e8c0": removing mount point "/var/lib/containers/storage/overlay/d8935b35f51d27896f81816f58dd60efb8f6860f795dd5a6fddf0e3ab48c6daf/merged": device or resource busy
```
Curiously, this does not hose all subsequent tests. The error persists forevermore, but only in a place where it doesn't really matter. Subsequent tests actually pass.

**Comment by edsantiago** [comment] 2023-09-26 17:08
Just seen in [debian 13](https://api.cirrus-ci.com/v1/artifact/task/5039167478956032/html/sys-remote-debian-13-root-host-sqlite.log.html#t--00591) but  with yet another surprise symptom:
```
starting container <SHA>: runc: runc create failed: unable to start container process: exec: "touch": executable file not found in $PATH: OCI runtime attempted to invoke a command that was not found
```
That looks suspiciously like #17042 ("catatonit et al not found", another hard-to-track-down flake). And, blam, everything after that is hosed.

**Comment by edsantiago** [comment] 2023-09-27 22:10
Sigh..... [no such luck](https://api.cirrus-ci.com/v1/artifact/task/5974786577268736/html/sys-remote-fedora-39-root-host-sqlite.log.html#t--00597).

**Comment by giuseppe** [comment] 2023-09-27 23:26
Was the change already vendored?  I will take another look, maybe it is a different instance of the same problem and needs a similar fix

**Comment by edsantiago** [comment] 2023-09-27 23:30
Yes, this is #17831 my pet PR on which I churn CI. I believe I correctly [vendored c/storage](https://github.com/containers/podman/pull/17831/commits/869760024856f6f8ddde2c8938ae526006d6743c) but it's always possible I did something wrong.

PS isn't it really, really late where you are??

**Comment by vrothberg** [comment] 2023-09-28 07:48
> Yes, this is #17831 my pet PR on which I churn CI. I believe I correctly [vendored c/storage](https://github.com/containers/podman/pull/17831/commits/869760024856f6f8ddde2c8938ae526006d6743c) but it's always possible I did something wrong.

I double checked and think you vendored it correctly.  But I am sure @giuseppe has picked up the right sent - there may be more such cases scattered in c/storage (or libpod?).

**Comment by giuseppe** [comment] 2023-09-28 07:51
the good news is that the occurrence I looked at yesterday doesn't appear in the log, and that was an easy one since I've managed to reproduce it all the time in a VM.  I am looking at the new error message right now.

**Comment by giuseppe** [comment] 2023-09-28 09:47
I think the issue could be fixed with something like:

```diff
diff --git a/drivers/overlay/overlay.go b/drivers/overlay/overlay.go
index 0f6d74021..f6f0932e0 100644
--- a/drivers/overlay/overlay.go
+++ b/drivers/overlay/overlay.go
@@ -1891,12 +1891,7 @@ func (d *Driver) Put(id string) error {
                }
        }
 
-       if err := unix.Rmdir(mountpoint); err != nil && !os.IsNotExist(err) {
-               logrus.Debugf("Failed to remove mountpoint %s overlay: %s - %v", id, mountpoint, err)
-               return fmt.Errorf("removing mount point %q: %w", mountpoint, err)
-       }
-
-       return nil
+       return system.EnsureRemoveAll(mountpoint)
 }
```

but before I open a PR, I'd like to understand how we even get in that situation.

@edsantiago do you think we could collect some more information with:

```
diff --git a/test/system/helpers.bash b/test/system/helpers.bash
index 3fcd69a60..f7dad187e 100644
--- a/test/system/helpers.bash
+++ b/test/system/helpers.bash
@@ -150,10 +150,13 @@ function basic_setup() {
         echo "# setup(): removing stray external container $1 ($2)" >&3
         run_podman '?' rm -f $1
         if [[ $status -ne 0 ]]; then
+            run_podman --log-level debug '?' rm -f $1
             echo "# [setup] $_LOG_PROMPT podman rm -f $1" >&3
             for errline in "${lines[@]}"; do
                 echo "# $errline" >&3
             done
+            echo "# MOUNTINFO"
+            cat /proc/self/mountinfo | while read i; do echo "# $i"; done
             # FIXME FIXME FIXME: temporary hack for #18831. If we see the
             # unmount/EINVAL flake, nothing will ever work again.
             if [[ $output =~ unmounting.*invalid ]]; then
```

I've opened a test PR based on yours: https://github.com/containers/podman/pull/20183, I'll let it run for a while and see if I am lucky to hit it

**Closed** 2023-10-05 11:26 UTC
Labels: flakes, remote
