### ISSUE TITLE
Use a new catatonit per namespace set

### ISSUE THREAD

**Issue by mathstuf** [containers/podman#21876] opened 2024-02-29 14:08 UTC
### Issue Description

With multiple namespaces, the persistent `catatonit` persists the selection that it was started with. When there is a namespace mismatch, a new `catatonit` process should be used.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Start a new namespace (e.g., networking)
2. `podman run` in one namespace
3. `podman run` in the other inherits the other's namespace and cannot use networking properly.

### Describe the results you received

Container cannot contact the network when running `podman` from a new network namespace.

### Describe the results you expected

The namespace selection of `podman` itself should be used for containers (except those that `podman` creates for its own operations).

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.33.5
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.8-2.fc38.x86_64
    path: /usr/libexec/crio/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 94.97
    systemPercent: 0.94
    userPercent: 4.09
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    version: "38"
  eventLogger: journald
  freeLocks: 2014
  hostname: farprobe
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.6.13-100.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 2676744192
  memTotal: 33351647232
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns:
      package: podman-plugins-4.9.3-2.fc38.x86_64
      path: /usr/libexec/cni/dnsname
      version: |-
        CNI dnsname plugin
        version: 1.3.1
        commit: unknown
    package: |-
      containernetworking-plugins-1.3.0-2.fc38.x86_64
      podman-plugins-4.9.3-2.fc38.x86_64
    path: /usr/libexec/cni
  ociRuntime:
    name: /usr/bin/crun
    package: crun-1.14.3-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.3
      commit: 1961d211ba98f532ea52d2e80f4c20359f241a98
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: false
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc38.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 16948912128
  swapTotal: 17179860992
  uptime: 792h 12m 52.00s (Approximately 33.00 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/boeckb/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.12-1.fc38.x86_64
      Version: |-
        fusermount3 version: 3.14.1
        fuse-overlayfs: version 1.12
        FUSE library version 3.14.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/boeckb/.local/share/containers/storage
  graphRootAllocated: 631649308672
  graphRootUsed: 512254971904
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 110
  runRoot: /run/user/1000
  transientStore: false
  volumePath: /home/boeckb/.local/share/containers/storage/volumes
version:
  APIVersion: 4.9.3
  Built: 1708357383
  BuiltTime: Mon Feb 19 10:43:03 2024
  GitCommit: ""
  GoVersion: go1.20.13
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.3
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment] 2024-02-29 14:32
It is not clear what you are asking for, can please provide a full reproducer.

Generally speaking spawning podman from more than one namespace will cause major consistency issues and a lot weird corner cases so the answer should likely be no that is not something that we ever can support.

**Comment by mathstuf** [comment] 2024-02-29 19:59
I have a wireguard VPN setup. I push it into a namespace. However, if I want to access VPN-only resources via a container, the `catatonit -P` ends up using the original namespace and cannot access the resources. It works if I kill `catatonit -P` and launch `podman` from within the namespace. I'm not sure how to provide a full reproducer as it involves setting up a Wireguard network. See [this page](https://www.wireguard.com/netns/) for instructions. Once you have it set up:

```sh
# Start a `tmux` in each network namespace
ip netns exec physical tmux -L physical start-server
ip netns exec wireguard tmux -L wireguard start-server

# Launch a container in the physical namespace
tmux -L physical -N
echo "in tmux" && podman exec --rm curlimages/curl curl ddg.gg
tmux detach-session

# Run in the wireguard namespace
tmux -L wireguard -N
# This fails because the container ends up in the `physical` namespace due to the leftover `catatonit -P` process
echo "in tmux" && podman exec --rm curlimages/curl curl some-wg-only-resource
```

**Comment by Luap99** [comment] 2024-03-01 10:18
Well at the very least show us how you create the container.

catatonit is only used to hold the user + mnt namespace, it is not used to switch the netns and we cannot switch the netns to another netns not created within the podman user namespace because we would have no perms to switch to either physical or wireguard so we just run from the current one.

If I run a container first to create the userns in the normal host namspaces and then run something like
```
sudo unshare -n su - $USER -c "podman run --rm quay.io/libpod/testimage:20240123 ping -c 1 google.com"
```
it correctly fails as the slirp4netns process for this container would be spawned in the new netns which does not have any connectivity.

This may have a different behaviour if you use `--network bridge` as this only ever uses one slirp4netns process so it would use the first container that was started.

**Comment by mathstuf** [comment] 2024-03-01 12:12
> Well at the very least show us how you create the container.

That I did show; they're normal images with plain `podman run`…though I see I did `exec` here :facepalm: . Edited.

> catatonit is only used to hold the user + mnt namespace

Ah! This might be the core of the issue here. It looks like `ip netns` sets up *mount* namespaces for `/sys`. But it doesn't set up the *child* mounts (I've had to fix `/sys/fs/cgroup` in the namespaces before). So it gets put into the network namespace, but the `/sys` tree is mismatched.

**Comment by giuseppe** [comment] 2024-03-04 08:54
I don't think this is something we can support.

If you want to run podman from different network namespaces, you need to use a different `--root` for each, so they don't step on each other.

**Comment by Luap99** [comment] 2024-03-04 10:13
> If you want to run podman from different network namespaces, you need to use a different --root for each, so they don't step on each other.

I doubt that this makes any difference we still only ever use one pause process regardless of --root.

**Comment by mathstuf** [comment] 2024-03-04 10:48
A `--fresh-pause` flag (though rename as needed) would be sufficient for my needs. At least I'm fine with a "I know I need this" rather than magic heuristics. Making it take an argument like `yes` and `no` could allow some level of `=auto` in the future if it ever comes to it.

**Comment by giuseppe** [comment] 2024-03-04 10:57
> > If you want to run podman from different network namespaces, you need to use a different --root for each, so they don't step on each other.
> 
> I doubt that this makes any difference we still only ever use one pause process regardless of --root.

the network namespaces can be owned by the same user namespace, so they can share the same pause process.

If it is not enough, then it needs a different `--runroot` as well, so it uses a different pause process.

**Comment by mathstuf** [comment] 2024-03-04 10:57
FWIW, my current "workaround" is to kill the `catatonit -P` process and then run from the network namespace. What dragons am I poking with a stick by doing that?

**Comment by giuseppe** [comment] 2024-03-04 11:00
> A `--fresh-pause` flag (though rename as needed) would be sufficient for my needs. At least I'm fine with a "I know I need this" rather than magic heuristics. Making it take an argument like `yes` and `no` could allow some level of `=auto` in the future if it ever comes to it.

that defeats having a pause process at all.  We must make sure all processes are owned by the same user namespace, a different pause process will be owned by a different user namespace unless you make sure to use `podman unshare` first.
  
The `podman unshare` command, and the pause process, is the equivalent of running as root, once there you do all your manual tweaks.

**Comment by Luap99** [comment] 2024-03-04 11:04
You can no longer properly manage any containers started in the previous userns.
All the unmounts, etc.. will fail and cause a lot of errrors. Also note that just killing the pause pid is not enough if there are still running container we try to join the userns back via the conmon pid if possible.

If you never have any running containers when you do this you should be mostly be fine, but again this is not something we will support.

**Comment by Luap99** [comment] 2024-03-04 11:05
Also would it make more sense for you to use `nsenter -n` instead because this will not change the mountns.

**Comment by mathstuf** [comment] 2024-03-04 14:32
> Also would it make more sense for you to use nsenter -n instead because this will not change the mountns.

Thanks; I'll try this out.

**Comment by mathstuf** [comment] 2024-03-04 14:37
It seems that some mount namespace is needed to interpose `/etc/resolv.conf` to use the DNS settings for the wireguard tunnel. I'll see about getting `ip netns exec` to mount sub-`/sys` mounts in its mount namespace again at least (then `podman` can run containers even if networking is busted).

**Comment by giuseppe** [comment] 2024-03-05 09:13
I am closing this issue for now, since it is not something we want to support in Podman.  Feel free to comment further and keep the conversion going if you've more questions

**Closed by giuseppe** 2024-03-05 09:13 UTC
Labels: kind/bug

**Comment by mathstuf** [comment] 2024-03-06 05:42
> If it is not enough, then it needs a different --runroot as well, so it uses a different pause process.

I tried with `--root=… --runroot=` and it still seems to have reused the existing `catatonit` process.

**Comment by Luap99** [comment] 2024-03-06 09:49
Yes we only ever use one pause process regardless of --root/--runroot

**Comment by giuseppe** [comment] 2024-03-06 10:33
can you try overriding XDG_RUNTIME_DIR?

**Comment by mathstuf** [comment] 2024-03-06 12:15
Ok, that managed to make it use another pause process. So it looks like the steps to make this work are:

- make the network namespace
- remount `cgroup2` in it at `/sys/fs/cgroup`
- make `podman` use a separate storage and run root
- - use `CONTAINERS_STORAGE_CONF` and `CONTAINERS_CONF` to relocate configuration files
