### ISSUE TITLE
macos: podman 2.0.6 remote support is broken

### ISSUE THREAD

**Issue by ssbarnea** [containers/podman#7602] opened 2020-09-11 11:03 UTC
While recent versions of podman improved the remoting  support they also introduced some critical bugs, like

```bash
export CONTAINER_HOST=ssh://root@example.com/run/podman/podman.sock
podman build .
# returns success (0), no output, but it failed to do anything
```

Trying to increase verbosity has not effects.

Both client (macos) and remote (fedora-32) are using same version of podman 2.0.6

**Comment by vrothberg** [comment] 2020-09-11 11:08
@ashley-cui PTAL

**Comment by ashley-cui** [comment] 2020-09-11 13:22
@ssbarnea is this a duplicate of https://github.com/containers/podman/issues/7498 ?

**Comment by ssbarnea** [comment] 2020-09-11 13:41
It seems like but there are two different issues: lack of logging and lack of returning the result code from the command. I would treat them differently, later one being critical.

**Comment by afbjorklund** [comment] 2020-09-11 13:45
Same situation on Linux. It was working in 2.0.0-2.0.4, but broken in 2.0.5-2.0.6

Since older versions are no longer available, it is not possible to downgrade either.

**Comment by ashley-cui** [comment] 2020-09-11 13:47
@ssbarnea got it, thanks
@afbjorklund thanks for the info, that'll definitely be helpful. I'll take a look at this soon

**Comment by afbjorklund** [comment] 2020-09-11 14:17
Hopefully some regression tests can be added for podman 2.1, for a better release ?

As it is now, we will probably will stay on podman 1.9.3 for the rest of the year or so.

**Comment by rhatdan** [comment] 2020-09-11 17:26
We are going to start release candidates on Monday for podman 2.1 so @ashley-cui Could you try each one out.

**Comment by rhatdan** [comment] 2020-09-11 17:31
@ssbarnea We added a new method to handle connections in podman 2.0
podman system connect
```
# podman system connect --help
Manage podman

Description:
  Manage podman

Usage:
  podman system [command]

Available Commands:
  connection  Manage remote ssh destinations
  df          Show podman disk usage
  info        Display podman system information
  migrate     Migrate containers
  prune       Remove unused data
  renumber    Migrate lock numbers
  reset       Reset podman storage
  service     Run API service
```

**Comment by ashley-cui** [comment] 2020-09-11 18:50
@rhatdan yep, looks like this is a real regression. i'll see if i can get this done.

**Comment by ashley-cui** [comment] 2020-09-11 19:28
huh, i was able to reproduce once for the linux podman-remote and then later it worked.. odd
```
$ podman-remote build ~/tst
Getting image source signatures
Copying blob sha256:50644c29ef5a27c9a40c393a73ece2479de78325cae7d762ef3cdc19bf42dd0a
Copying blob sha256:4ca545ee6d5db5c1170386eeb39b2ffe3bd46e5d4a73a9acbebc805f19607eb3
Copying config sha256:f69e15d34b6bdf5d326269510a1863eda431a4c6b0965a1918d6ec68a4934799
Writing manifest to image destination
Storing signatures
--> f69e15d34b6
f69e15d34b6bdf5d326269510a1863eda431a4c6b0965a1918d6ec68a4934799

FROM alpine
CMD echo "hello world"
COMMIT
Successfully built f69e15d34b6bdf5d326269510a1863eda431a4c6b0965a1918d6ec68a4934799
```

**Comment by afbjorklund** [comment] 2020-09-12 07:30
> We added a new method to handle connections in podman 2.0

I will take a look to see if this new `podman system connection` command can replace the variables.

I don't fully understand how it would work with **two** machines/shells, but I see that it has "names".

```
Usage:
  podman system connection add [flags] NAME DESTINATION
```

However, there doesn't seem to be a variable for which connection to use - or am I missing something ?

So each command would have to use `podman --remote --connection name`, if not using the default name.

No $PODMAN_CONNECTION ?

The user can have several VMs...


It seems like by default, they would both use the `~/.config/containers/containers.conf` configuration file.

So if I use `podman system connection default NAME` in one shell, it would also affect the _other_ shell.

See https://minikube.sigs.k8s.io/docs/commands/podman-env/

https://minikube.sigs.k8s.io/docs/handbook/pushing/#3-pushing-directly-to-in-cluster-cri-o-podman-env

**Closed** 2020-09-15 10:17 UTC
Labels: kind/bug, macos, remote

**Comment by rhatdan** [comment] 2020-09-15 14:20
I suppose we could add a connection name environment variable to override the default, if this is something you would want.
