### ISSUE TITLE
Error: listing vms: invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by liketoeatcheese** [containers/podman#16788] opened 2022-12-08 21:23 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman machine automatically not working. 

**Steps to reproduce the issue:**

Can't produce it because it randomly showed up. Restart machine, or reinstall podman didn't work

**Describe the results you received:**

podman machine ls
`Error: listing vms: invalid character '\x00' looking for beginning of value`

I have a machine named `podman-fed`

I attempted to stop it:
podman machine stop podman-fed
`Error: invalid character '\x00' looking for beginning of value`

**Describe the results you expected:**

Should list out machines or be able to remove them

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue happened before and occasionally, I fixed it last time by reinstall podman, but it didn't work this time for some reason.

**Output of `podman version`:**
```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.3.0/libpod/_ping": dial unix ///run/podman/podman.sock: connect: An invalid argument was supplied.
```
I installed v4.3.1 in my system

So I ran `podman system connection list`, and I got:
```
Name                         URI                                                          Identity                                    Default
podman-fed                   ssh://user@localhost:51113/run/user/1000/podman/podman.sock  C:\Users\wpham\.ssh\podman-fed              false
podman-fed-root              ssh://root@localhost:51113/run/podman/podman.sock            C:\Users\wpham\.ssh\podman-fed              false
podman-machine-default       ssh://user@localhost:50966/run/user/1000/podman/podman.sock  C:\Users\wpham\.ssh\podman-machine-default  false
podman-machine-default-root  ssh://root@localhost:50966/run/podman/podman.sock            C:\Users\wpham\.ssh\podman-machine-default  false
```

I suspected it to be a block of network within my work network. So, I tried to connect to my phone hotspot and tried again, but it didn't seem to work so we can eliminate that reason.

**Output of `podman info`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.3.0/libpod/_ping": dial unix ///run/podman/podman.sock: connect: An invalid argument was supplied.
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows

**Comment by Luap99** [comment] 2022-12-09 13:51
Duplicate of #16550

This will be fixed in the next release

**Closed by Luap99** 2022-12-09 13:51 UTC
Labels: kind/bug, windows
