### ISSUE TITLE
binfmt_misc mountpoint missing in privileged containers

### ISSUE THREAD

**Issue by michaeladler** [containers/podman#4725] opened 2019-12-18 12:23 UTC
/kind bug

**Description**

In order to be compatible with Docker, a privileged container should provide the binfmt_misc mountpoint.

**Steps to reproduce the issue:**

1. `sudo podman run --rm -it --privileged debian:buster-slim /bin/bash`

2. `mount | grep binfmt_misc`

**Describe the results you received:**

Empty output

**Describe the results you expected:**

```
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0-rc1
host:
  BuildahVersion: 1.11.6
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /nix/store/8xlzm0w62cd8qdpva0xg3ybnsm5ppkrp-conmon-2.0.8/bin/conmon
    version: 'conmon version 2.0.8, commit: unknown'
  Distribution:
    distribution: nixos
    version: 20.03.git.1bfdbc8
  MemFree: 9552855040
  MemTotal: 16640389120
  OCIRuntime:
    name: crun
    package: Unknown
    path: /run/current-system/sw/bin/crun
    version: |-
      crun version UNKNOWN
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: demogorgon
  kernel: 5.4.3
  os: linux
  rootless: false
  uptime: 24m 20.43s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 56
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

NixOS

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by rhatdan** [comment] 2019-12-18 12:43
Does Docker mount the /proc/sys from the host into the container?

**Comment by michaeladler** [comment] 2019-12-18 12:48
Yes. Unfortunately, binfmt_misc is not yet namespace aware, although there are some [recent efforts](https://lkml.org/lkml/2019/11/7/577) to remedy this...

**Comment by rhatdan** [comment] 2020-01-19 12:49
@giuseppe Could you look into this one?

**Comment by giuseppe** [comment] 2020-01-20 09:46
I've tried Docker 1.13 and I don't see binfmt mounted.  What version have you tried?

If it is not namespaces, I don't think we should add it by default.  Changes done there are visible to the host and it could be used to register malicious handlers.

**Comment by rhatdan** [comment] 2020-01-20 11:05
I thought the problem was whether we do with --privileged flag?

**Comment by giuseppe** [comment] 2020-01-20 12:19
> I thought the problem was whether we do with --privileged flag?

yes but I think it could still be a problem to add it by default since it is not namespaced.  Changes done to to the binfmt files will be propagated to the host and to every other container.  Do we want to do it by default?

**Comment by rhatdan** [comment] 2020-01-20 12:48
No.  Does Docker do it by default?  Or only when used with --privileged?

**Comment by michaeladler** [comment] 2020-01-20 13:14
Interestingly, I just realized that manually mounting binfmt_misc works using podman (in privileged mode, of course). So the problem seems to be with the container itself, as can be seen from these two commands:

```sh
$ sudo docker run --rm -it --privileged kasproject/kas-isar:1.1 mount | grep binfmt_misc
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
```

```sh
$ sudo podman run --rm -it --privileged kasproject/kas-isar:1.1 mount | grep binfmt_misc

```

While I tend to agree that setting up (or mounting) binfmt_misc from inside a container is not very clean, I still would expect the same behavior from docker and podman. (The mountpoint is required for cross-architecture builds.)

**Comment by giuseppe** [comment] 2020-01-22 09:31
> No. Does Docker do it by default? Or only when used with --privileged?

with Docker 1.13, I don't see it mounted in both cases

**Comment by vrothberg** [comment] 2020-01-31 11:01
> > No. Does Docker do it by default? Or only when used with --privileged?
> 
> with Docker 1.13, I don't see it mounted in both cases

Maybe you should try a version of Docker from after the war :^)

@michaeladler, which version of Docker are you running?

**Comment by michaeladler** [comment] 2020-02-03 08:13
Docker version 19.03.5, build 633a0ea838f10e000b7c6d6eed1623e6e988b5bc

However, please take notice of my last comment: https://github.com/containers/libpod/issues/4725#issuecomment-576268919 
It seems to be an issue with the way the specific container is built. Still, since the slogan of podman is `alias docker=podman`, I would expect this to work :)

**Comment by rhatdan** [comment] 2020-02-18 15:06
@michaeladler What other mount points under /proc do you see?  My machine is currently running cgroups V2 so docker will not work.

**Comment by mheon** [comment] 2020-02-18 15:08
I tried with Docker 18.06, which does not have the mount, but that's still 2 years old. I couldn't find direct mention in the release notes, so I'm not sure exactly when it landed.

An OCI spec from a privileged Docker container with the mount added would help a fair bit, so we know exactly what it's doing.

**Comment by michaeladler** [comment] 2020-02-26 11:37
Docker version 19.03.5, build 633a0ea838f10e000b7c6d6eed1623e6e988b5bc:

```sh
$ sudo docker run --rm -it --privileged kasproject/kas-isar:2.0 /bin/bash
builder@7003438ef59e:~$ mount
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/2YBR5HOLI7P7OGMAEE2TGXPM3V:/var/lib/docker/overlay2/l/DOPD5OQRZZ4AWWQDCB3E6CKTBL:/var/lib/docker/overlay2/l/5AXXMGXPAGFXARCIKVY3WCHICM:/var/lib/docker/overlay2/l/R66QC25T2WIHBHVDMCE4WGDVUZ:/var/lib/docker/overlay2/l/2RBMMPUIUGC75TY2ZKYET2CC6T:/var/lib/docker/overlay2/l/GLQ37LHUL6SILAQ7SVEZZ637LQ:/var/lib/docker/overlay2/l/IBOJ3Q3E7WCECP25W2EDHPNV7L:/var/lib/docker/overlay2/l/TMCVQFJN4QGLIBEE6M4HU5ZFJK:/var/lib/docker/overlay2/l/NXER34KHIPL7ZCIXQTKCCXTHRN:/var/lib/docker/overlay2/l/KJU73JATESCQTYCKSGFNV6CURU:/var/lib/docker/overlay2/l/RPBEFSFYJRPXP7LE22VEUFEQIW:/var/lib/docker/overlay2/l/Q5GJ65EJVZZAOLSHYSUNEDQ7FK,upperdir=/var/lib/docker/overlay2/4890d55619079321f5e96767324767f1eaae833a8c8d8fcf93175c185a400f5c/diff,workdir=/var/lib/docker/overlay2/4890d55619079321f5e96767324767f1eaae833a8c8d8fcf93175c185a400f5c/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
/dev/disk/by-uuid/b5008ea7-5342-470f-aeb1-d84a04f8f000 on /etc/resolv.conf type ext4 (rw,noatime,nodiratime,discard,errors=remount-ro,commit=90)
/dev/disk/by-uuid/b5008ea7-5342-470f-aeb1-d84a04f8f000 on /etc/hostname type ext4 (rw,noatime,nodiratime,discard,errors=remount-ro,commit=90)
/dev/disk/by-uuid/b5008ea7-5342-470f-aeb1-d84a04f8f000 on /etc/hosts type ext4 (rw,noatime,nodiratime,discard,errors=remount-ro,commit=90)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
```
**Notice: the last line says binfmt_misc**

podman version 1.8.0:

```
$ sudo /run/current-system/sw/bin/podman run --rm -it --privileged kasproject/kas-isar:2.0 /bin/bash                                                                                                         12:34
builder@47dd10eadebe:~$ mount
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/containers/storage/overlay/l/4JQXB6MIFTYSRWAEFY34I3TVVG:/var/lib/containers/storage/overlay/l/VPLXZNLAX3V4CH24FJYF5AM46Z:/var/lib/containers/storage/overlay/l/2TSIEXDXLEWZ4MZKOF73N2Z7JF:/var/lib/containers/storage/overlay/l/B33S3KWZNGBQ2ZR4GVHIQZ32YC:/var/lib/containers/storage/overlay/l/W7DTFTJI4MNEPNXNJ2FG2H75FF:/var/lib/containers/storage/overlay/l/KC6VVUPLM4CQQJCEN5S4J2QTSE:/var/lib/containers/storage/overlay/l/T7NPBSEITVFRNPBK7IZ36HZTIB:/var/lib/containers/storage/overlay/l/6CFIO4GLKDL4AUSY7TVKXZZG2L:/var/lib/containers/storage/overlay/l/2AJHIHER4NC6YNZ4ECQFPUSZYB:/var/lib/containers/storage/overlay/l/FIAYHXYBUIPCUYYRB7N6RZ7MTT:/var/lib/containers/storage/overlay/l/WHP6NHAS5W36JAHGYQAZ4QNDJ3,upperdir=/var/lib/containers/storage/overlay/f08105c7d72093db98e84b8ee5b7acc98a85d5d709863c3a7765eec5a32e37e1/diff,workdir=/var/lib/containers/storage/overlay/f08105c7d72093db98e84b8ee5b7acc98a85d5d709863c3a7765eec5a32e37e1/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
tmpfs on /etc/hostname type tmpfs (rw,nosuid,nodev,size=4062584k,mode=755)
tmpfs on /run/.containerenv type tmpfs (rw,nosuid,nodev,size=4062584k,mode=755)
tmpfs on /etc/resolv.conf type tmpfs (rw,nosuid,nodev,size=4062584k,mode=755)
tmpfs on /etc/hosts type tmpfs (rw,nosuid,nodev,size=4062584k,mode=755)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=64000k)
cgroup on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1024k)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
```

If I run `sudo mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc` inside the container, the mountpoint is there (as expected).

**Comment by michaeladler** [comment] 2020-03-06 09:28
Ok, so I think I have nailed down this problem a little further:

1. Run debian:buster-slim in a privileged container, e.g. `docker run --privileged debian:buster-slim /bin/bash` (or podman instead of docker)
2. `apt-get update && apt-get install -y qemu-user-static`
3. `mount | grep binfmt`

If the container was created using docker, you will see the line `binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)`. In the case of podman, it is missing.

This can also be reproduced in an already running container:

1. `umount /proc/sys/fs/binfmt_misc`
2. `dpkg-reconfigure --force qemu-user-static`
3. `mount | grep binfmt`

In the case of docker, you will see `/proc/sys/fs/binfmt_misc mounted` again. In the case of podman, it is missing. **However, if I run `update-binfmts --enable` directly, it works in both docker and podman**. So the actual question is why does the package installation behave differently in Docker and podman.

**Comment by rhatdan** [comment] 2020-03-06 16:15
Ok the difference seems to be your image is running the entrypoint of  --entrypoint=/kas/docker-entrypoint which is mounting or causing to mount the binfmt_misc mountpoint.

For some reason podman is not executing this or it is failing to mount.

**Comment by rhatdan** [comment] 2020-03-06 16:17
@giuseppe I checked this against runc and crun and podman does them the same either way.

**Comment by fbezdeka** [comment] 2020-07-08 16:52
@rhatdan I have the same problem using the kas container.

docker:
```
ls -al /proc/sys/fs/binfmt_misc
total 0
drwxr-xr-x 2 root root 0 Jul  7 18:43 .
dr-xr-xr-x 1 root root 0 Jul  3 17:58 ..
-rw-r--r-- 1 root root 0 Jul  7 18:43 qemu-aarch64
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-alpha
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-arm
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-armeb
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-cris
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-hppa
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-m68k
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-microblaze
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-mips
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-mips64
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-mips64el
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-mipsel
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-ppc
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-ppc64
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-ppc64abi32
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-ppc64le
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-riscv32
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-riscv64
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-s390x
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-sh4
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-sh4eb
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-sparc
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-sparc32plus
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-sparc64
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-xtensa
-rw-r--r-- 1 root root 0 Jul  8 18:05 qemu-xtensaeb
--w------- 1 root root 0 Jul  8 18:05 register
-rw-r--r-- 1 root root 0 Jul  8 18:05 status
```

podman:
```
$ ls -al /proc/sys/fs/binfmt_misc/
total 0
dr-xr-xr-x 2 root root 0 Jul  8 16:51 .
dr-xr-xr-x 1 root root 0 Jul  8 16:51 ..
```

There is a "mount" call in the entry point, but that seems to be executed by docker as well as podman.
Any ideas?

**Comment by rhatdan** [comment] 2020-07-08 17:53
@fbezdeka What podman command are you executing?  What podman --version?

**Comment by fbezdeka** [comment] 2020-07-08 19:33
```
$ podman --version
podman version 2.0.1
```

```
sudo podman run --privileged -it docker.io/library/debian:buster-slim bash
root@25c18f19cdbe:/# 
root@25c18f19cdbe:/# ls -al /proc/sys/fs/binfmt_misc/
total 0
dr-xr-xr-x. 2 root root 0 Jul  8 19:31 .
dr-xr-xr-x. 1 root root 0 Jul  8 19:31 ..
root@25c18f19cdbe:/# 
root@25c18f19cdbe:/# 
root@25c18f19cdbe:/# mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc 
root@25c18f19cdbe:/# 
root@25c18f19cdbe:/# ls -al /proc/sys/fs/binfmt_misc/
total 0
drwxr-xr-x. 2 root root 0 Jul  8 18:36 .
dr-xr-xr-x. 1 root root 0 Jul  8 19:31 ..
-rw-r--r--. 1 root root 0 Jul  8 18:36 jexec
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-aarch64
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-aarch64_be
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-alpha
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-arm
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-armeb
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-hppa
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-m68k
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-microblaze
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-microblazeel
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-mips
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-mips64
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-mips64el
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-mipsel
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-mipsn32
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-mipsn32el
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-or1k
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-ppc
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-ppc64
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-ppc64le
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-riscv32
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-riscv64
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-s390x
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-sh4
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-sh4eb
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-sparc
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-sparc32plus
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-sparc64
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-xtensa
-rw-r--r--. 1 root root 0 Jul  8 18:36 qemu-xtensaeb
--w-------. 1 root root 0 Jul  8 18:36 register
-rw-r--r--. 1 root root 0 Jul  8 18:36 status
```

**Comment by rhatdan** [comment] 2020-07-08 20:24
@fbezdeka You need to do the install, I belive.

The buster-slim image does not do `mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc ` automatically.

**Comment by fbezdeka** [comment] 2020-07-08 20:42
I will retest, but when running on docker it is getting mounted.

So we have different behaviour between docker and podman here.

**Comment by rhatdan** [comment] 2020-07-08 20:55
If that is true, then Docker is mounting binfmt_misc by default when running --privileged, if that is true then that would be a significant difference that we should fix, however I don't believe it does.

**Comment by fbezdeka** [comment] 2020-07-08 21:08
Host: 
package `qemu-user-static` is installed, so `/proc/sys/fs/binfmt_misc` is "filled".

Both (docker and podman)
When starting the container `/proc/sys/fs/binfmt_misc` is empty.

Within container running on docker:
```
$ apt-get install qemu-user-static
...
$ ls /proc/sys/fs/binfmt_misc
(filled)
```

Within container running on podman:
```
$ apt-get install qemu-user-static
...
$ ls /proc/sys/fs/binfmt_misc
(stays empty)
```

**Comment by fbezdeka** [comment] 2020-07-08 21:25
When running on docker a kernel module named `binfmt_misc` gets loaded into the host kernel.

When running on podman this seems to fail (silently).

**Comment by rhatdan** [comment] 2020-07-08 21:27
It is blocked by SELinux and might be blocked by non root user doing it.
Does it work if you disable SELinux for the container?
Does it work if you install it as rootfull podman.

**Comment by fbezdeka** [comment] 2020-07-09 09:29
SELinux:
It's not a SELinux problem. Even when running with a global "setenforce 0" the audit log keeps empty.

rootfull podman:
What exactly do you mean? I'm starting with sudo and the --privileged flag. Does that fully cover "rootfull podman"?

I just noticed that the mentioned `binfmt_misc` kernel module is already loaded during boot on the podman host.
So the installation of `qemu-user-static` fills `/proc/sys/fs/binfmt_misc` when running on docker, but it does not when running on podman.

As a workaround I can install `qemu-user-static` on the host and mount `/proc/sys/fs/binfmt_misc` manually inside the container. But I would like to avoid that.

**Comment by rhatdan** [comment] 2020-07-09 17:36
I have no idea what in Podman would be blocking this mount.
I am trying to duplicate your error, and I see.
sudo podman run --privileged -it docker.io/library/debian:buster-slim bash
root@09b37fba3c34:/# apt-get install qemu-user-static
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qemu-user-static

**Comment by rhatdan** [comment] 2020-07-09 17:37
apt-get update 
fixes that issue.

**Comment by rhatdan** [comment] 2020-07-09 17:40
Ok I don't see a problem in the install, but when it is done, the mount point does not exist.

**Comment by rhatdan** [comment] 2020-07-09 17:42
Do you know what the post install script of qemu-user-static looks like?

**Comment by rhatdan** [comment] 2020-07-09 17:48
It seems to work if I do --pid=host. 

So this looks like something different in the way we setup the /proc file system when running in Podman then in Docker.

Inside of Podman I see:

# mount | grep proc
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)

Also could you make sure Docker uses PIDNS in privileged mode.

sudo podman run --privileged -it docker.io/library/debian:buster-slim ls -l /proc/self/ns/pid; ls -l /proc/self/ns/pid
lrwxrwxrwx. 1 root root 0 Jul  9 17:48 /proc/self/ns/pid -> 'pid:[4026534044]'
lrwxrwxrwx. 1 root root 0 Jul  9 13:48 /proc/self/ns/pid -> 'pid:[4026531836]'

**Comment by fbezdeka** [comment] 2020-07-09 18:22
PIDs on docker:
```
sudo docker run --privileged -it docker.io/library/debian:buster-slim ls -l /proc/self/ns/pid; ls -l /proc/self/ns/pid
lrwxrwxrwx 1 root root 0 Jul  9 18:18 /proc/self/ns/pid -> 'pid:[4026532267]'
lrwxrwxrwx 1 flo flo 0 Jul  9 20:18 /proc/self/ns/pid -> 'pid:[4026531836]'
```
The owner of the last one is different when comparing to podman, don't know if that matters.

I can confirm that --pid=host works. Thanks for the hint!

**Comment by rhatdan** [comment] 2020-07-10 10:24
@giuseppe Any ideas what is going on here?

**Comment by michaeladler** [comment] 2020-07-14 07:54
`--pid=host` does the trick for me as well. Thanks! @rhatdan Consider re-opening the bug?

**Comment by rhatdan** [comment] 2020-09-10 20:10
@giuseppe Still no idea on this one?

**Comment by vrothberg** [comment] 2020-09-15 09:39
Note that @giuseppe is on PTO

**Comment by rhatdan** [comment] 2020-12-24 12:53
@giuseppe Could you take a look at this one?

**Comment by rhatdan** [comment] 2021-01-27 13:43
@giuseppe PTAL,  I looked at this last summer, and the only thing I came up with is potentially docker and podman setting up pidns different?

**Comment by giuseppe** [comment] 2021-01-28 10:01
this is not something we can fix I think.

The issue is in:

```
# head /var/lib/dpkg/info/qemu-user-static.postinst
#!/bin/sh
set -e
# check if we're running inside an (lxc) container
# (we may copy or move this to the postinst script too, to skip installing it)
grep -zqs ^container= /proc/1/environ && exit 0                              <= THIS IS THE ISSUE
```

so the `container=podman` environment variable blocks the postinst script to actually do the mount.

If I try:
```
# podman run --rm -it --privileged debian:buster-slim /bin/bash
# unset container
# exec bash
# apt-get update && apt-get install -y qemu-user-static
# mount | grep binfmt_misc
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
```
I get the mount.

This should be reported to Debian, although it seems to be on purpose and the issue is with Docker

**Closed by giuseppe** 2021-01-28 10:01 UTC
Labels: kind/bug

**Comment by rhatdan** [comment] 2021-01-29 16:34
Nice find @giuseppe

**Comment by fbezdeka** [comment] 2021-01-29 17:27
Could someone explain why `--pid=host` is fixing this problem then? I would be surprised if that touches the environment somehow...

**Comment by fbezdeka** [comment] 2021-01-30 14:55
That's not what I expected (and kind of weired), but `--pid=host` influences `/proc/1/environ`

Without `--pid=host` => container=podman
```
$ podman run --rm -it --privileged debian:buster-slim /bin/bash           
root@6fb226385718:/# grep -zs ^container= /proc/1/environ
container=podman
```

With `--pid=host` => container is unset
```
$ podman run --pid=host --rm -it --privileged debian:buster-slim /bin/bash 
root@b2616e2782ec:/# grep -zs ^container= /proc/1/environ
root@b2616e2782ec:/#
```

Anyway, I will try to open a bug for the Debian qemu-user-static package.
