### ISSUE TITLE
[Question] How to start adb (android debug bridge) from inside a podman container?

### ISSUE THREAD

**Issue by jeet-parekh** [containers/podman#8610] opened 2020-12-05 11:42 UTC
**Description**

I have been exploring podman since the last couple of days. I tried to run adb from inside a podman container. And it just fails to start the adb server.
Please note, it works if I add the `--privileged` flag. But I have been trying to avoid using that flag unless there's no choice.
Apologies if this is the wrong place for this question.

**Steps to reproduce the issue:**

These steps work for docker. I am able to see my attached android device.

```
sudo docker run --rm -it --device=/dev/bus -v /dev/serial:/dev/serial:ro --cap-add SYS_PTRACE ubuntu:20.04
apt update && apt install -y android-tools-adb android-tools-fastboot
adb devices
```

Output:
```
List of devices attached
* daemon not running; starting now at tcp:5037
* daemon started successfully
<my_device_id>	device
```

But when I do the same with podman

```
podman run --rm -it --device=/dev/bus -v /dev/serial:/dev/serial:ro --cap-add SYS_PTRACE ubuntu:20.04
apt update && apt install -y android-tools-adb android-tools-fastboot
adb devices
```

Output:
```
List of devices attached
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.0.log
Server had pid: 1184
--- adb starting (pid 1184) ---
adb I 12-05 17:05:45  1184  1184 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 12-05 17:05:45  1184  1184 main.cpp:57] Version 1:8.1.0+r23-5ubuntu2
adb I 12-05 17:05:45  1184  1184 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 12-05 17:05:45  1184  1184 main.cpp:57] 
adb I 12-05 17:05:45  1184  1184 adb_auth_host.cpp:416] adb_auth_init...
adb I 12-05 17:05:45  1184  1184 adb_auth_host.cpp:262] User key '/root/.android/adbkey' does not exist...
adb I 12-05 17:05:45  1184  1184 adb_auth_host.cpp:109] generate_key(/root/.android/adbkey)...
adb I 12-05 17:05:45  1184  1184 adb_auth_host.cpp:77] write_public_keyfile...
adb I 12-05 17:05:45  1184  1184 adb_auth_host.cpp:56] get_user_info...
adb I 12-05 17:05:45  1184  1184 adb_auth_host.cpp:174] read_key_file '/root/.android/adbkey'...
adb I 12-05 17:05:45  1184  1184 adb_auth_host.cpp:391] adb_auth_inotify_init...

* failed to start daemon
error: cannot connect to daemon
```

**Output of `podman version`:**

```
Version:      2.2.0
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 05:30:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 8
  distribution:
    distribution: pop
    version: "20.04"
  eventLogger: journald
  hostname: jeet
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.0-7630-generic
  linkmode: dynamic
  memFree: 23486369792
  memTotal: 33564786688
  ociRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  swapFree: 4294434816
  swapTotal: 4294434816
  uptime: 8h 15m 13.17s (Approximately 0.33 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/jeet/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/jeet/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/jeet/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 05:30:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
apt list podman:

Listing... Done
podman/unknown,now 2.2.0~2 amd64 [installed]
podman/unknown 2.2.0~2 arm64
podman/unknown 2.2.0~2 armhf
podman/unknown 2.2.0~2 s390x

apt info podman:

Package: podman
Version: 2.2.0~2
Priority: optional
Section: devel
Maintainer: Lokesh Mandvekar <lsm5@fedoraproject.org>
Installed-Size: 69.4 MB
Depends: libseccomp2, libdevmapper1.02.1, libgpgme11, catatonit, conmon (>= 2.0.18~1), containers-common (>= 1.2.0~3), containernetworking-plugins (>= 0.8.6~1), runc | cri-o-runc, iptables, podman-plugins (>= 1.1.1~1)
Recommends: crun, slirp4netns, uidmap, varlink
Conflicts: podman-rootless
Homepage: https://github.com/containers/podman.git
Download-Size: 16.9 MB
APT-Manual-Installed: yes
APT-Sources: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Packages
Description: Manage pods, containers and container images.
```

**Comment by afbjorklund** [comment] 2020-12-06 09:37
Does it work with the regular `sudo podman`, instead of podman rootless ?

**Comment by jeet-parekh** [comment] 2020-12-06 09:54
No, it doesn't work with `sudo podman` either.

**Comment by jeet-parekh** [comment] 2020-12-06 09:57
Some more info, running `adb nodaemon server` inside podman (both sudo and rootless) shows a segmentation fault. But it works fine with docker.

```
# adb nodaemon server
adb I 12-06 09:55:47    12    12 auth.cpp:437] adb_auth_init...
adb I 12-06 09:55:47    12    12 auth.cpp:262] User key '/root/.android/adbkey' does not exist...
adb I 12-06 09:55:47    12    12 auth.cpp:97] generate_key(/root/.android/adbkey)...
Segmentation fault (core dumped)
```

**Comment by mheon** [comment] 2020-12-06 14:47
Can you try adding the '--privileged' flag? Some of our security defaults
are tougher than Docker, so if it works with them disabled that is most
likely the cause.

**Comment by jeet-parekh** [comment] 2020-12-06 16:39
Adding the `--privileged` flag works. But it does not detect attached devices in rootless mode. You have to use `--privileged` + `sudo` to have adb detect the attached devices. I mentioned this in the issue description. I was exploring and trying to figure out how to avoid using `--privileged`.

That could definitely be the cause. I'm curious what's exactly happening here. And is there a way to make it work without `--privileged`...? Like it works with docker.

**Comment by mheon** [comment] 2020-12-06 17:20
Hm. So it works as rootless with the `--privileged` flag, and you'd like to turn it off?

Security-wise, `--privileged` has three effects: it enables all capabilities (`--cap-add ALL`), disabled Seccomp filtering (`--security-opt seccomp=unconfined`), and (on Apparmor distros) disables Apparmor (`--security-opt apparmor=unconfined`). Can you try each of those options individually without `--privileged` and see if any of them do the trick? We can drill down further once we know exactly what is doing the blocking.

**Comment by jeet-parekh** [comment] 2020-12-06 17:33
> So it works as rootless with the `--privileged` flag, and you'd like to turn it off?

adb works, but it doesn't detect the devices. So, it's kinda useless. You have to use sudo + privileged to have adb work as well as detect the devices.

Ideally, it would be good to have it work without sudo or privileged. But again, I am just exploring to see if it's possible.

Before testing those three options, I'll note the current behaviour of two commands.

1. adb server doesn't start. A [segmentation fault](https://github.com/containers/podman/issues/8610#issuecomment-739480213) happens.
```
podman run --rm -it --device=/dev/bus -v /dev/serial:/dev/serial:ro --cap-add SYS_PTRACE ubuntu:20.04
```

2. adb server starts, but cannot detect the attached android device.
```
podman run --rm -it --device=/dev/bus -v /dev/serial:/dev/serial:ro --privileged ubuntu:20.04
```

3. For all of these three commands, just like (1), adb doesn't start. And a segmentation fault happens. I tried these three commands both rootless, and with sudo.
```
podman run --rm -it --device=/dev/bus -v /dev/serial:/dev/serial:ro --cap-add ALL ubuntu:20.04
podman run --rm -it --device=/dev/bus -v /dev/serial:/dev/serial:ro --security-opt seccomp=unconfined ubuntu:20.04
podman run --rm -it --device=/dev/bus -v /dev/serial:/dev/serial:ro --security-opt apparmor=unconfined ubuntu:20.04
```

**Comment by mheon** [comment] 2020-12-06 17:45
Running without `sudo` may be impossible, given permissions issues. I presume you were running `docker` as root (perhaps with your user added to the `docker` group so you could access it without `sudo`, but the daemon was running as root) - so full permissions were available. Rootless Podman is not SUID, and has no elevated privileges - so my first impression would be that we don't have permission to access the devices you're mounting into the container.

**Comment by jeet-parekh** [comment] 2020-12-06 17:57
> I presume you were running docker as root (perhaps with your user added to the docker group so you could access it without sudo, but the daemon was running as root) - so full permissions were available.

Right. I am running docker as root. Not by adding the user to the docker group. Explicitly with sudo.

> so my first impression would be that we don't have permission to access the devices you're mounting into the container

Makes sense. I just tried a plain rootless `podman run --rm -it ubuntu:20.04` without any device or volume mount. And the adb server was able to start without a segmentation fault.

Do you think it's possible to make it work with root, but without privileged?

**Comment by mheon** [comment] 2020-12-06 19:32
I can't see a reason why sudo, but no `--privileged`, could not be made to work. It is very interesting that it doesn't seem to be security, though. Potentially could be a device not being mounted in from the host, I suppose. @giuseppe @rhatdan Any thoughts here?

**Comment by rhatdan** [comment] 2020-12-07 12:31
As a rootless user can you access these devices?  If not, then it will not be able to be done in rootless mode.  The devices probably need to be readable and perhaps writeable by the user.  If they are protected by root, then it probably impossible to use rootless.

--privileged also unmasks all of /proc and /sys, which might be why you cannot use these devices without being root.
In the main branch of podman we just added a new feature, which allows you to disable the masking

podman run --security-opt unmask=all ...

Which should remove the masks.

**Comment by jeet-parekh** [comment] 2020-12-07 13:11
> As a rootless user can you access these devices?

Yes. If I run `adb devices` directly on my laptop withouth `sudo`, then it works just fine. It lists my devices.
My user does have root privileges though. But it works fine without `sudo`. Not sure if that matters.

> In the main branch of podman we just added a new feature, which allows you to disable the masking.

I guess I could try building podman from the main branch and try adb again. I wasn't able to find any build steps though.

**Comment by afbjorklund** [comment] 2020-12-07 14:25
For me, it is the usb claim that fails:

```
[pid  1274] ioctl(11, USBDEVFS_CLAIMINTERFACE, 0x7fa4791efa6c) = 0
[pid  1274] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x4} ---
```

When running on the host, it succeeds.

**Comment by rhatdan** [comment] 2020-12-07 14:34
Look like the cgrouppermissions is definitely  a bug,   Not sure about mounting all of the devices.

**Comment by rhatdan** [comment] 2020-12-07 14:35
@giuseppe WDYT?

**Comment by zhangguanzhang** [comment] 2020-12-09 13:31
I use the dlv to debug this, I think the problem should be in the part of listening to the container creation event and creating the container
```
(dlv) p ctr.config.Spec.Linux.Resources.Devices
[]github.com/opencontainers/runtime-spec/specs-go.LinuxDeviceCgroup len: 2, cap: 2, [
	{Allow: true, Type: "c", Major: *189, Minor: *0, Access: "rwm"},
	{Allow: true, Type: "c", Major: *189, Minor: *1, Access: "rwm"},
]
(dlv) ls
> github.com/containers/podman/v2/libpod.(*BoltState).AddContainer() libpod/boltdb_state.go:688 (PC: 0x1a51991)
   683:	
   684:		if ctr.config.Pod != "" {
   685:			return errors.Wrapf(define.ErrInvalidArg, "cannot add a container that belongs to a pod with AddContainer - use AddContainerToPod")
   686:		}
   687:	
=> 688:		return s.addContainer(ctr, nil)
   689:	}
   690:	
   691:	// RemoveContainer removes a container from the state
   692:	// Only removes containers not in pods - for containers that are a member of a
   693:	// pod, use RemoveContainerFromPod
(dlv) p ctr.config.Spec.Linux.Devices
[]github.com/opencontainers/runtime-spec/specs-go.LinuxDevice len: 2, cap: 2, [
	{
		Path: "/dev/bus/usb/001/001",
		Type: "c",
		Major: 189,
		Minor: 0,
		FileMode: *8628,
		UID: *0,
		GID: *0,},
	{
		Path: "/dev/bus/usb/001/002",
		Type: "c",
		Major: 189,
		Minor: 1,
		FileMode: *8628,
		UID: *0,
		GID: *0,},
]
(dlv) 

```

**Comment by zhangguanzhang** [comment] 2020-12-09 14:33
```
[root@Centos8 /sys/fs/cgroup/devices/machine.slice/libpod-d993bbcab954e98d233f59867ae25226b1fa46c1359a42fa23b9a3d422a8f94b.scope]# podman inspect t1 | grep -i pid
            "Pid": 328791,
            "ConmonPid": 328780,
        "ConmonPidFile": "/var/run/containers/storage/overlay-containers/d993bbcab954e98d233f59867ae25226b1fa46c1359a42fa23b9a3d422a8f94b/userdata/conmon.pid",
            "PidMode": "private",
            "PidsLimit": 2048,
[root@Centos8 /sys/fs/cgroup/devices/machine.slice/libpod-d993bbcab954e98d233f59867ae25226b1fa46c1359a42fa23b9a3d422a8f94b.scope]# cat notify_on_release 
0
[root@Centos8 /sys/fs/cgroup/devices/machine.slice/libpod-d993bbcab954e98d233f59867ae25226b1fa46c1359a42fa23b9a3d422a8f94b.scope]# cat cgroup.procs 
328791
[root@Centos8 /sys/fs/cgroup/devices/machine.slice/libpod-d993bbcab954e98d233f59867ae25226b1fa46c1359a42fa23b9a3d422a8f94b.scope]# cat cgroup.clone_children 
0
[root@Centos8 /sys/fs/cgroup/devices/machine.slice/libpod-d993bbcab954e98d233f59867ae25226b1fa46c1359a42fa23b9a3d422a8f94b.scope]# cat devices.list 
c 189:1 rwm
c 189:0 rwm
c 136:* rwm
c 5:2 rwm
c 5:0 rwm
c 1:9 rwm
c 1:8 rwm
c 1:7 rwm
c 1:5 rwm
c 1:3 rwm
b *:* m
c *:* m
c 10:200 rwm
```
look like correct 
```
c 189:1 rwm
c 189:0 rwm

```

**Comment by giuseppe** [comment] 2020-12-10 14:04
as rootless could you try with `-v /dev:/dev --mount type=devpts,destination=/dev/pts`?

The cgroup settings don't affect rootless as anyway a rootless user cannot configure the devices controller both on cgroup v1 and cgroup v2.

**Comment by jeet-parekh** [comment] 2020-12-10 14:33
This fails.

```
podman run --rm -it -v /dev:/dev --mount type=devpts,destination=/dev/pts ubuntu:20.04

Error: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: open /dev/console: permission denied: OCI permission denied
```

This works fine. But trying to run adb still causes a segmentation fault.

```
podman run --rm -it -v /dev/bus:/dev/bus --mount type=devpts,destination=/dev/pts ubuntu:20.04
```

**Comment by rhatdan** [comment] 2021-01-10 13:03
Any further update on this issue?

**Comment by jeet-parekh** [comment] 2021-01-13 19:35
For visibility, maybe change the label from question to bug?

**Comment by jeet-parekh** [comment] 2021-02-25 19:19
I see the label has been changed to question again. Perhaps change the title to something describing the bug uncovered in this discussion, and re-label it as bug...?

**Comment by rhatdan** [comment] 2021-03-29 13:25
I am not sure what bug has been descoved in this discussion, Could someone clarify what they think needs to happen to close this issue?

**Comment by giuseppe** [comment] 2021-03-29 14:02
please try: `podman run --rm -it -v /dev:/dev --mount type=devpts,destination=/dev/pts ...` with crun instead of runc

**Comment by jeet-parekh** [comment] 2021-03-30 04:30
I believe this got fixed in the last four months. adb inside a podman container can now detect my android device.

@rhatdan, https://github.com/containers/podman/issues/8610#issuecomment-739956160
> Look like the cgrouppermissions is definitely a bug, Not sure about mounting all of the devices.

@giuseppe, both of these work now. Segmentation fault does not happen. And I can access the android device via adb.

```bash
podman --runtime=/usr/bin/crun run --rm -it -v /dev/bus/usb/:/dev/bus/usb ubuntu:20.04
podman --runtime=/usr/bin/runc run --rm -it -v /dev/bus/usb/:/dev/bus/usb ubuntu:20.04
```

**Comment by giuseppe** [comment] 2021-03-30 09:09
thanks, so are you fine if we close this issue?

**Closed** 2021-03-30 18:47 UTC
Labels: Question
