### ISSUE TITLE
Podman should detach from non-interactive mode containers

### ISSUE THREAD

**Issue by Keith-Nowosielski-SJSU** [containers/podman#6990] opened 2020-07-15 19:52 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

 

Unable to detach from a container using the default keys ctrl-p,ctrl-q or by setting different keys in the /etc/containers/container.conf file.  

**Steps to reproduce the issue:**

1. Attach to a container "podman attach containername" 

2. press detach key sequence "ctrl-p, ctrl-q" 
 

**Describe the results you received:**
Nothing happens, the cursor indicates its still in the container with a blank output or whatever is expected of that container. The terminal has to be exited to continue working as no escape keys will exit the container

**Describe the results you expected:**
The terminal should exit the pod and return to the local system bash prompt.

**Additional information you deem important (e.g. issue happens only occasionally):**
n/a
**Output of `podman version`:**

```
podman version 2.0.2

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.18, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: keith-Latitude-E7270
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.3.0-62-generic
  linkmode: dynamic
  memFree: 475717632
  memTotal: 8000921600
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: unknown
  swapFree: 458551296
  swapTotal: 2147479552
  uptime: 91h 22m 34.45s (Approximately 3.79 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/keith/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/keith/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/keith/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.14.4
  OsArch: linux/amd64
  Version: 2.0.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.0.2~2 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical, I'm also running this on a Centos 8 machine which is a vm in vsphere 6.5 with the same issue.

**Comment by rhatdan** [comment] 2020-07-15 21:51
@QiWang19 PTAL

**Comment by QiWang19** [comment] 2020-07-24 20:22
@Keith-Nowosielski-SJSU  I failed to reproduce this detach key issue with 2.0.2 or the current upstream branch. ctrl-p, ctrl-q will only work when you have started your container with interactive mode (-it). Maybe you have changed the `detach_keys` in containers.conf to other keys?

**Comment by Keith-Nowosielski-SJSU** [comment] 2020-07-24 20:25
Qi, Yes I did discover they work with interactive mode. Is there just no
way to detach in non-interactive mode?

Thanks,

Keith

**Comment by QiWang19** [comment] 2020-07-24 20:33
Do you mean this, run with -d,  `-d, --detach                                   Run container in background and print container ID`?

**Comment by mheon** [comment] 2020-07-24 20:35
With `--sig-proxy=false` set, you could control-c Podman and kill just it, not the container - I don't think we can do that by default, though, even for non-interactive containers.

I suppose we could also add a client-side loop for non-interactive Podman that listens for the detach keys and stops Podman if they're received?

**Comment by Keith-Nowosielski-SJSU** [comment] 2020-07-24 20:40
podman attach container_name <- this is what I use, it gives the output
from the pod if there is any similar to a telnet session into a network
device. The podman documentation reads like the detach keys should work to
exit this mode and return to the local system. Otherwise all I can do is
close the terminal and start a new one.


Keith

**Comment by rhatdan** [comment] 2020-07-25 11:08
Yes this should allow you to detach.

**Comment by rhatdan** [comment] 2020-08-25 18:09
@QiWang19 Have you been able to look into @mheon suggestion?

**Comment by rhatdan** [comment] 2020-09-10 21:18
@QiWang19 I think we need to raise the importance of this issue.

**Comment by rhatdan** [comment] 2020-12-24 12:32
@Keith-Nowosielski-SJSU @mheon Do we still have this issue?

**Comment by mheon** [comment] 2020-12-24 17:06
This has not been fixed.

**Comment by Keith-Nowosielski-SJSU** [comment] 2020-12-24 18:57
Wish I could give you an answer. My podman installation is currently giving me [this issue](https://github.com/containers/podman/issues/7396) for all commands so far as I can see.

**Comment by Keith-Nowosielski-SJSU** [comment] 2021-01-04 21:03
Just confirmed this is still an issue in podman 2.1.1

**Comment by rhatdan** [comment] 2021-03-08 19:13
@mheon could you spend some time on this one?

**Comment by mheon** [comment] 2021-03-08 19:14
I'll see what I can do this week

**Comment by mheon** [comment] 2021-03-09 21:29
Looking more into this today - I'm starting to lean towards this not being possible. We can detect the normal detech keys (Ctrl-p, Ctrl-Q) because the terminal is placed in raw mode as part of `-t` and we get raw bytes off the terminal. Without `-t` we are not in raw mode (and I don't believe we can be - the point of running Podman without `-t` is to ensure that output is plaintext and can be easily used with pipes, shell redirection, etc and raw mode would prevent that) and as such I can't tell if the control key is depressed - it's being handled at a higher level and we have no idea about it. I tested with the latest Docker, and `docker run -i` also displays this behavior - detach keys are ignored.

I'm going to close this as a WONTFIX - we can't do this without breaking the main intent of Podman without `-t`.

**Closed by mheon** 2021-03-09 21:29 UTC
Labels: kind/bug

**Comment by Keith-Nowosielski-SJSU** [comment] 2021-03-10 18:51
Can the documentation then be updated to reflect this? I was still
relatively new to podman when I happened across this and it was really
frustrating because the documentation spells this out as the proper
functionality. The first thing I would do is run a plain jane attach and
hit this problem.

http://docs.podman.io/en/latest/markdown/podman-attach.1.html

Thanks,

Keith Nowosielski

Information Technology Systems Specialist

Computing Services Department

San Jose State University

**Comment by rhatdan** [comment] 2021-03-11 15:29
Interested in opening a PR with documentation that would have helped you?

**Comment by chaseadam** [comment] 2021-08-28 02:56
> Without `-t` we are not in raw mode (and I don't believe we can be - the point of running Podman without `-t` is to ensure that output is plaintext and can be easily used with pipes, shell redirection, etc and raw mode would prevent that) and as such I can't tell if the control key is depressed - it's being handled at a higher level and we have no idea about it.

In text mode (non -t) how is "Ctrl-C" handled (in that it can terminate a process)?
It seems to be passed to the process but because we are not in '-t' raw mode, podman doesn't have access to "capture" those characters?
Can we not capture them at all or can we just not do the "wait to see if the sequence matches detatch, and if not, send them" to the process?

I ran into this several times in the past and recently as well. I agree the documentation could be better. The best description I have seen so far is https://stackoverflow.com/a/41099052

**Comment by mheon** [comment] 2021-08-28 19:15
In normal mode, I believe it's the shell that's handling all of that - so the shell gets a Ctrl-C, and subsequently sends the foregrounded process a signal to terminate. We have absolutely no indication that the control key is being pressed, we're just getting a stream of unicode characters that are the final result of whatever keys are being pressed. Some key cominations don't actually produce output, but rather side effects. It's similar to how Ctrl-D isn't actually sending an EOF character, but instead is closing the STDIN stream.

**Comment by mheon** [comment] 2021-09-02 13:40
A `kill -9` on the Podman process performing the attach is guaranteed to get rid of it, but not the container. Other signals unfortunately won't work (we default to using `--sig-proxy`, which proxies (almost) all signals that can be caught into the container; we need a signal that cannot be caught to successfully terminate Podman itself, hence SIGKILL).
