### ISSUE TITLE
Error: unable to convert image EXPOSE: invalid port number: strconv.Atoi: parsing "8080,": invalid syntax

### ISSUE THREAD

**Issue by blame2020** [containers/podman#15217] opened 2022-08-05 15:47 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

when run docker.io/gerritcodereview/gerrit, I got:

```
Error: unable to convert image EXPOSE: invalid port number: strconv.Atoi: parsing "8080,": invalid syntax
```

**Steps to reproduce the issue:**

1. Run `podman run -it --rm docker.io/gerritcodereview/gerrit:latest`

**Describe the results you received:**

```
podman run -it --rm docker.io/gerritcodereview/gerrit:latest
Error: unable to convert image EXPOSE: invalid port number: strconv.Atoi: parsing "8080,": invalid syntax
```

**Describe the results you expected:**

This container is valid for docker, so should be valid for podman.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.4
Built:        Sat Jul 23 04:05:59 2022
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-3.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No, but latest package in Fedora.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by vrothberg** [comment] 2022-08-08 07:50
Thanks for the report, @blame2020!

I cannot reproduce with podman-4.1.1-3.fc36.x86_64.  Also the image config looks OK as shown below:
```
~ $ skopeo inspect --config docker://docker.io/gerritcodereview/gerrit | jq .config.ExposedPorts
{                                                                                               
  "29418/tcp": {},                                                                              
  "8080/tcp": {}                                                                                
}
```

I suspect that the `latest` image had a temporary bug.  I am going to close the issue but please let me know in case you still see the issue today.

**Closed by vrothberg** 2022-08-08 07:50 UTC
Labels: Good First Issue, kind/bug

**Comment by blame2020** [comment] 2022-08-08 08:15
Thank you for your response.

umm..
I have not been able to resolve this issue in my environment yet.
And i just noticed that the error message is different for each run.
```
$ skopeo inspect --config docker://docker.io/gerritcodereview/gerrit | jq .config.ExposedPorts
{
  "29418/tcp": {},
  "8080/tcp": {}
}
$ podman run -ti  docker.io/gerritcodereview/gerrit:latest
Error: unable to convert image EXPOSE: invalid port number: strconv.Atoi: parsing "29148]": invalid syntax
$ podman run -ti  docker.io/gerritcodereview/gerrit:latest
Error: unable to convert image EXPOSE: invalid port number: strconv.Atoi: parsing "[8080,": invalid syntax
$ podman --version
podman version 4.1.1
$ podman run -ti  hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by vrothberg** [comment] 2022-08-08 08:22
Very curious!  Can you share the digest of your local image as shown below?  I think you need to repull the image.  `podman run` will only pull if the image isn't already in the local storage.

```
~ $ podman image inspect --format "{{.Digest}}" gerrit
sha256:e3908c5c8300d78c78116ab609b10b7d7c6607a7b1e1eab56d9246e2d5e07ad5
```

**Comment by vrothberg** [comment] 2022-08-08 08:58
Glad we could resolve your image!  Thanks for reaching out.
