### ISSUE TITLE
Unable to use Podman from Pycharm due to API version string

### ISSUE THREAD

**Issue by bkhl** [containers/podman#7327] opened 2020-08-15 11:37 UTC
**Description**

Tried using the Podman REST API to enable using it as an execution backend for Pycharm.

1. Run podman API on a TCP port with `podman system service --time=0 tcp:localhost:2375 --log-level debug`
2. Configure Pycharm to connect to Docker by TCP with Engine API URL: `http://localhost:2375`

**Describe the results you received:**

This error is shown in Pycharm

```
Cannot connect: java.lang.IllegalArgumentException: 1.0.0 can not be parsed
```
With the log level set to `debug`, I can see that it requested the `version` endpoint, which reports:

```
"APIVersion": "1.0.0"
```

It appears that this is a parsing error due to Docker API versions normally being formatted as `1.40`.

Not sure if Pycharm would accept `1.00`, but at least the parsing of the version would work, I guess.

**Describe the results you expected:**

Podman to be sufficiently compatible with the Docker API so that I can use it as a build backend for Pycharm.

One idea to allow hacking around clients with restrictions on API version (there may be many more of these besides Pycharm) might be to allow using a different TCP base URL to get it to report whatever version your clients needs. So if I e.g. put in `http://localhost:2375/v1.40` as your API base URL, that's the API version that would be reported by Podman.

**Output of `podman version`:**

```
Version:      2.0.4
API Version:  1
Go Version:   go1.14.6
Built:        Thu Jan  1 07:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: foxglove
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.7.14-200.fc32.x86_64
  linkmode: dynamic
  memFree: 4180303872
  memTotal: 16430170112
  ociRuntime:
    name: crun
    package: crun-0.14.1-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 8321495040
  swapTotal: 8321495040
  uptime: 5h 9m 2.02s (Approximately 0.21 days)
registries:
  artifactoryaut.vizrt.internal:
    Blocked: false
    Insecure: true
    Location: artifactoryaut.vizrt.internal
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: artifactoryaut.vizrt.internal
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  configFile: /var/home/bkhl/.config/containers/storage.conf
  containerStore:
    number: 19
    paused: 0
    running: 1
    stopped: 18
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/bkhl/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 77
  runRoot: /run/user/1000/containers
  volumePath: /var/home/bkhl/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 07:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.6
  OsArch: linux/amd64
  Version: 2.0.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Pycharm version: `2020.2`

**Comment by bkhl** [comment] 2020-08-15 11:40
Also reported this to Jetbrains here: https://youtrack.jetbrains.com/issue/IDEA-226650#focus=Comments-27-4345415.0-0 , since this could potentially be fixed there as well.

However, I suspect this can cause issues with other clients, so might be good to address it in Podman regardless.

**Comment by TomSweeneyRedHat** [comment] 2020-08-15 14:04
@jwhonce thoughts?

**Comment by mheon** [comment] 2020-08-15 14:08
Likely issue is that one of our unversioned endpoints is reporting Libpod
API version instead of the Docker compatible API version.

**Comment by bkhl** [comment] 2020-08-15 15:15
> Likely issue is that one of our unversioned endpoints is reporting Libpod API version instead of the Docker compatible API version.

It appears to affect versioned endpoints also. If I put in `http://localhost:2375/v1.40` I can see from the debug output that Pycharm requests `http://localhost:2375/v1.40/version`, which still says `"APIVersion":"1.0.0"`.

**Comment by vrothberg** [comment] 2020-09-08 14:31
@jwhonce can you have a look at it? I believe you already have some battle scars in that big version matrix.

**Comment by mheon** [comment] 2020-09-08 14:43
From the look of things, we're going to need a separate version endpoint for Compat that reports the Docker API version, not the Libpod one.

**Comment by mlegenovic** [comment] 2020-09-12 14:56
Problem with Jetbrain's Docker plugin is that version string is not parsed as semver string (what Podman returns). Docker API also does not strictly define that ApiVersion must be semver string.

I have patched Podman's `/version` endpoint (which BTW is already in compat package) to return Docker API version just to test if everything else works. Result is:
- Jetbrain's Docker plugin can now connect, and list all images
- Running container instances (started via CLI) are listed, but you cannot interact with them from UI
- New container instances cannot be started successfully from UI

I do not know what the problem is, but Podman debug output shows that only two endpoints are used:
`/containers/json?all=true`
`/images/json`

It is maybe out of scope, but Eclipse Docker plugin also does not work. Version endpoint is here not the problem, but /images/json. Podman returns here a json which does not comply with the Docker API specification. Docker API defines for example ParentId, SharedSize, VirtualSize, Labels and Containers attributes as mandatory, but Podman does not provide them. RepoDigests is called Digests in Podman's result. Because of that, json deserialisation in Eclipse Docker plugin fails.

Fixing `/version` endpoint is for sure a good thing, but still has no huge value because both popular IDEs will still not work.
If possible, fix also `/images/json` compat endpoint, that will help Eclipse plugin. Jetbrain's Docker plugin is not open-source, so you cannot do anything for it as long as it is not clear what the problem is.

**Comment by rhatdan** [comment] 2020-09-15 14:37
@baude PTAL

**Comment by jwhonce** [comment] 2020-09-15 17:24
@baude I've got this.

**Comment by jwhonce** [comment] 2020-09-15 18:53
@mlegenovic Can we move the discussion around omitted fields to another issue? To save on bandwidth when encoding JSON we have routinely omitted zero-value fields.  If this is causing decoding issues, we can revisit this design decision.

**Closed** 2020-09-16 02:06 UTC
Labels: kind/bug

**Comment by mlegenovic** [comment] 2020-09-30 20:31
@jwhonce Agree. [https://github.com/containers/podman/issues/7857](https://github.com/containers/podman/issues/7857)
