### ISSUE TITLE
upper fs does not support xattr, with --userns keepid, rhel 8.5 podman 3.3.1

### ISSUE THREAD

**Issue by michael-d-fmtech** [containers/podman#12350] opened 2021-11-18 16:37 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On a fresh rhel 8.5 installation, when trying to launch containers using native overlayfs, with userns mapping  and user ID mapping (--userns keepid --user ${userid}), 

I receive the following error in the kernel logs,

` overlayfs: upper fs does not support xattr, falling back to index=off and metacopy=off.`

The container eventually starts after 10's of minutes. 
 
After the container starts from a fresh image. The container will start relatively quickly if the container is stopped and removed (--rm). However, using new images or running after a 'podman system reset'  will cause the issue again.

* Can workaround this issue by creating a local storage.conf and using fuse-overlayfs (restores previous behavior)
* I have not tested if the container fully operates as expected after it eventually launches with overlayfs

**Steps to reproduce the issue:**

1. podman system reset

2. Start a container with --userns keepid --user ${userid} // Where userid is a non-root user

3. Inspect /var/log/messages via `dmesg` or tail while starting a container

**Describe the results you received:**

kernel: overlayfs: upper fs does not support xattr, falling back to index=off and metacopy=off.

**Describe the results you expected:**

Container to start as normal

**Additional information you deem important (e.g. issue happens only occasionally):**

Reproduceable

**Output of `podman version`:**

```
podman version 3.3.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 0f5bee61b18d4581668e5bf18b910cda3cff5081'
  cpus: 16
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: <SECRET>
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 626
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-348.2.1.el8_5.x86_64
  linkmode: dynamic
  memFree: 31355015168
  memTotal: 33394434048
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/626/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 16869486592
  swapTotal: 16869486592
  uptime: 19h 13m 16.19s (Approximately 0.79 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/<USERID>/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/<USERID>/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/626/containers
  volumePath: /home/<USERID>/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1632213702
  BuiltTime: Tue Sep 21 01:41:42 2021
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.3.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.1-9.module+el8.5.0+12697+018f24d7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine with newly installed rhel 8.5 kernel

**Comment by giuseppe** [comment] 2021-11-18 19:10
the container starts slowly because native overlay doesn't support idmapping of IDs, so the image must be cloned (and it takes time).
The error you are seeing is a test podman does to verify what features overlay support, and it should not affect your container.

What image are you using?

Does it happen even with small images (e.g., ubi, busybox)?

**Comment by mheon** [comment] 2021-11-18 19:12
Also, please provide the full output of a `podman run` command that fails with the `--log-level=debug` flag added

**Comment by michael-d-fmtech** [comment] 2021-11-18 19:42
@giuseppe   - Ok this make sense

I've tried a couple of container images
1) rhel minimal install + some packages ~2-3 GB
2) rhel minimal install + large application ~ 10GB

The smaller image has a 'faster' startup time ; Although extremely slow compared to fuse-overlay, clearly attributable to the clone

Are there any suggestions about improving this startup time?  Or are you aware if any kernel updates in the future will support idmapping? 

Hopefully there is a plan for enabing native fuse-overlay to perform better, but until then I am currently inclined to continue using fuse-overlay (unless you have some suggestions to minimize the impact).

**Comment by giuseppe** [comment] 2021-11-18 19:57
sadly not yet.

We are waiting for idmapped mounts in the kernel to support overlay, which is not the case at the moment.

The issue is tracked here: https://github.com/containers/podman/issues/10374

I am closing this issue, since there is nothing we can do in Podman to address it.

The only alternative at the moment is to use fuse-overlayfs

**Closed by giuseppe** 2021-11-18 19:57 UTC
Labels: kind/bug

**Comment by michael-d-fmtech** [comment] 2021-11-18 20:03
Agree,
Thanks
