### ISSUE TITLE
Failure to set up network for podman-compose

### ISSUE THREAD

**Issue by DistantThunder** [containers/podman#19502] opened 2023-08-03 19:04 UTC
### Issue Description

# SPECS

> podman version                                                                                                                                                                                                    
Client:       Podman Engine
Version:      4.6.0
API Version:  4.6.0
Go Version:   go1.20.6
Git Commit:   38e6fab9664c6e59b66e73523b307a56130316ae-dirty
Built:        Fri Jul 21 14:38:28 2023
OS/Arch:      linux/amd64

> podman-compose version                                                                                                                                                                                                    
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.6.0
podman-compose version 1.0.6
podman --version 
podman version 4.6.0
exit code: 0

----

# Issue

When trying to run a Compose stack, I get an error

The source is here: https://github.com/elkninja/elastic-stack-docker-part-one/

### Steps to reproduce the issue

Steps to reproduce the issue
1. Clone the mentioned repo
2. Try to `podman-compose -f $file up`
3. 

### Describe the results you received

```
podman start -a elastic-stack-docker-part-one_setup_1
WARN[0000] Failed to load cached network config: network elastic not found in CNI cache, falling back to loading network elastic from disk 
Error: unable to start container 734119a77696e1612f95f1cd14558c9f1daa56aee434e86e0a99a2ae5f839b8c: plugin type="tuning" failed (add): cni plugin tuning failed: open /etc/cni/tuning/allowlist.conf: permission denied
exit code: 125
podman start -a elastic-stack-docker-part-one_es01_1
WARN[0000] Failed to load cached network config: network elastic not found in CNI cache, falling back to loading network elastic from disk 
ERRO[0000] Starting some container dependencies         
ERRO[0000] "plugin type=\"tuning\" failed (add): cni plugin tuning failed: open /etc/cni/tuning/allowlist.conf: permission denied" 
Error: unable to start container 9d574840632f8a5cf7ed49781ac7003e0ec355bd72cd080e3b04fa9ece65c535: starting some containers: internal libpod error
exit code: 125
podman start -a elastic-stack-docker-part-one_kibana_1
WARN[0000] Failed to load cached network config: network elastic not found in CNI cache, falling back to loading network elastic from disk 
ERRO[0000] Starting some container dependencies         
ERRO[0000] "plugin type=\"tuning\" failed (add): cni plugin tuning failed: open /etc/cni/tuning/allowlist.conf: permission denied" 
ERRO[0000] "a dependency of container 9d574840632f8a5cf7ed49781ac7003e0ec355bd72cd080e3b04fa9ece65c535 failed to start: container state improper" 
Error: unable to start container 050a6942c0e0b7fe72e347dd12e72ac1369bf2a1b920ffd3ed314c0d12518d57: starting some containers: internal libpod error
exit code: 125
podman start -a elastic-stack-docker-part-one_filebeat01_1
Error: no container with name or ID "elastic-stack-docker-part-one_filebeat01_1" found: no such container
exit code: 125
podman start -a elastic-stack-docker-part-one_metricbeat01_1
WARN[0000] Failed to load cached network config: network elastic not found in CNI cache, falling back to loading network elastic from disk 
ERRO[0000] Starting some container dependencies         
ERRO[0000] "plugin type=\"tuning\" failed (add): cni plugin tuning failed: open /etc/cni/tuning/allowlist.conf: permission denied" 
ERRO[0000] "a dependency of container 050a6942c0e0b7fe72e347dd12e72ac1369bf2a1b920ffd3ed314c0d12518d57 failed to start: container state improper" 
ERRO[0000] "a dependency of container 9d574840632f8a5cf7ed49781ac7003e0ec355bd72cd080e3b04fa9ece65c535 failed to start: container state improper" 
Error: unable to start container b57b8f464724b86e04cca3de45659c0b8686b60303db7b319323c42820b4b6e0: starting some containers: internal libpod error
exit code: 125
podman start -a elastic-stack-docker-part-one_logstash01_1
WARN[0000] Failed to load cached network config: network elastic not found in CNI cache, falling back to loading network elastic from disk 
ERRO[0000] Starting some container dependencies         
ERRO[0000] "a dependency of container 050a6942c0e0b7fe72e347dd12e72ac1369bf2a1b920ffd3ed314c0d12518d57 failed to start: container state improper" 
ERRO[0000] "a dependency of container 9d574840632f8a5cf7ed49781ac7003e0ec355bd72cd080e3b04fa9ece65c535 failed to start: container state improper" 
ERRO[0000] "plugin type=\"tuning\" failed (add): cni plugin tuning failed: open /etc/cni/tuning/allowlist.conf: permission denied" 
Error: unable to start container 6f9f41540071fc18a2921a368061c8940a7669112cad5ece97ad30a010df2abd: starting some containers: internal libpod error
exit code: 125

```

### Describe the results you expected

The storage works.

### podman info output

```yaml
> podman info 
>host:
> arch: amd64
> buildahVersion: 1.31.0
> cgroupControllers:
>  - memory
>  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon appartient à conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 63.74
    systemPercent: 9.5
    userPercent: 26.76
  cpus: 16
  databaseBackend: boltdb
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  freeLocks: 2032
  hostname: XXX
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.3.9-zen1-1-zen
  linkmode: dynamic
  logDriver: journald
  memFree: 15864713216
  memTotal: 67345371136
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns:
      package: /usr/lib/cni/dnsname appartient à podman-dnsname 1.3.1-2
      path: /usr/lib/cni/dnsname
      version: |-
        CNI dnsname plugin
        version: 1.3.1
        commit: 18822f9a4fb35d1349eb256f4cd2bfd372474d84
    package: |-
      /usr/lib/cni/ appartient à cni-plugins 1.3.0-1
      /usr/lib/cni/ appartient à podman-dnsname 1.3.1-2
    path: /usr/lib/cni
  ociRuntime:
    name: crun
    package: /usr/bin/crun appartient à crun 1.8.5-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: /usr/bin/slirp4netns appartient à slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 268h 20m 43.00s (Approximately 11.17 days)
plugins:
  authorization: null
  log:
>  - k8s-file
>  - none
>  - passthrough
>  - journald
>  network:
>  - bridge
>  - macvlan
>  - ipvlan
>  volume:
>  - local
>registries:
>  search:
>  - docker.io
>  - registry.fedoraproject.org
>  - quay.io
>  - registry.access.redhat.com
>  - registry.centos.org
>store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 0
    stopped: 7
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 16797093888
  graphRootUsed: 8102682624
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 24
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.0
  Built: 1689943108
  BuiltTime: Fri Jul 21 14:38:28 2023
  GitCommit: 38e6fab9664c6e59b66e73523b307a56130316ae-dirty
  GoVersion: go1.20.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment] 2023-08-04 07:14
Thanks for reaching out, @DistantThunder.

> WARN[0000] Failed to load cached network config: network elastic not found in CNI cache, falling back to loading network elastic from disk 
Error: unable to start container 734119a77696e1612f95f1cd14558c9f1daa56aee434e86e0a99a2ae5f839b8c: plugin type="tuning" failed (add): cni plugin tuning failed: open /etc/cni/tuning/allowlist.conf: permission denied
exit code: 125

Did you investigate this error?

Is there are a specific reason why you're using the CNI backend?  There's a new network since Podman 4.0 (see https://www.redhat.com/sysadmin/podman-new-network-stack).

FWIW, I don't think this compose file will properly work with Podman as it does things like mounting `/var/lib/docker/containers`.  This requires a) to run as root (so rootless Podman won't work) and b) expects Docker to be executing the workload.

**Comment by Luap99** [comment] 2023-08-04 09:50
As @vrothberg mentioned we are recommending netavark, it will work with that.
The easiest way to switch is to make sure `netavark` and `aardvark-dns` are installed then run `podman system reset`. You can confirm the backend with `podman info --format {{.Host.NetworkBackend}}`.

---
As for the actual error it looks like the plugins added a new file which rootless users have no access to: https://github.com/containernetworking/plugins/pull/693

This is pretty bad for us as this will make CNI plugins >= v1.2 incompatible with rootless podman. 
There might be ways for us to work around that but I really don't think it is worth out time as out focus is on netavark and CNI is deprecated anyway.

As for an actual workaround you should be able to create the `/etc/cni/tuning` directory and make it and the parent readable for all users.

**Comment by DistantThunder** [comment] 2023-08-04 13:17
Hello, @vrothberg  @Luap99 , thank you for your quick answers here.

I had no idea I was using a specific "cni" network plugin that wasn't the recommended default. I usually run my containers rootless so no idea this could be an issue.

> Did you investigate this error?

Is there are a specific reason why you're using the CNI backend? There's a new network since Podman 4.0 (see https://www.redhat.com/sysadmin/podman-new-network-stack).

I could see it's a permission + potentially missing dir issue but I had no interest in pursuing that since the goal is to run rootless and I have been able to do that until now.




> The easiest way to switch is to make sure netavark and aardvark-dns are installed then run podman system reset. You can confirm the backend with podman info --format {{.Host.NetworkBackend}}.


I went with this and it appears I'm using "netavark" now. I have also removed the docker dir mounting.

Now I encountered various other problems, namely this section:

> 108     ulimits:
109       memlock:
110         soft: -1
111         hard: -1

Figuring out what may be the best option here.

**Comment by hawkdavis** [comment] 2023-08-05 04:30
i've run into the same issue with the ports not working after upgrading podman-compose, nothing seems to fix it.

**Comment by DistantThunder** [comment] 2023-08-06 01:07
So I could make this work by:

* Wiping my environment with the full reset command: `podman system reset`.
* And then I simply removed the ulimits block. As these cannot exceed the system's and will need to be necessarily lower or perhaps matching. I had a satisfying value system-wide so I was wine just removing the block.
* Lastly ofc, also remove the docker resources mounting

After doing these three steps, I was able to get the stack up.

**Comment by Luap99** [comment] 2023-08-07 09:03
> i've run into the same issue with the ports not working after upgrading podman-compose, nothing seems to fix it.

I don't see how this is related. If you have reproducer and checked with the latest version please fill a new issue with all requested information.

---

As far as this CNI problem is concerned I will close this issue as wontfix given there is a workaround. We strongly recommend users to migrate to netavark, CNI is deprecated and will be removed in the future.

**Closed by Luap99** 2023-08-07 09:04 UTC
Labels: kind/bug, CNI, network
