### ISSUE TITLE
/_ping output differs from Docker API

### ISSUE THREAD

**Issue by andrin55** [containers/podman#8097] opened 2020-10-21 14:25 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman API includes newline char whereas Docker API does not. This can cause issues with software which does an exact comparison (str == "OK")

**Steps to reproduce the issue:**

1. curl -s --unix-socket /var/run/docker.sock http://d/v1.28.0/_ping -vv

**Describe the results you received:**
Podman (Content-Length: 3):
```
*   Trying /var/run/docker.sock...
* Connected to d (/run/podman/podman.sock) port 80 (#0)
> GET /v1.28.0/_ping HTTP/1.1
> Host: d
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Api-Version: 1.40
< Buildkit-Version:
< Cache-Control: no-cache
< Docker-Experimental: true
< Libpod-Api-Version: 2.0.0
< Libpod-Buildha-Version: 1.16.1
< Pragma: no-cache
< Server: Libpod/2.0.0 (linux)
< Date: Wed, 21 Oct 2020 14:15:44 GMT
< Content-Length: 3
< Content-Type: text/plain; charset=utf-8
<
OK
* Connection #0 to host d left intact
```

**Describe the results you expected:**
Docker (Content-Length: 2):
```
* About to connect() to d port 80 (#0)
*   Trying /var/run/docker.sock...
* Failed to set TCP_KEEPIDLE on fd 3
* Failed to set TCP_KEEPINTVL on fd 3
* Connected to d (/var/run/docker.sock) port 80 (#0)
> GET /v1.28.0/_ping HTTP/1.1
> User-Agent: curl/7.29.0
> Host: d
> Accept: */*
>
< HTTP/1.1 200 OK
< Api-Version: 1.26
< Docker-Experimental: false
< Server: Docker/1.13.1 (linux)
< Date: Wed, 21 Oct 2020 14:21:20 GMT
< Content-Length: 2
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host d left intact
OK[root@hostname ~]#
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.13.15
Built:        Fri Oct  2 16:30:39 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-1.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: fa5f92225c4c95759d10846106c1ebd325966f91-dirty'
  cpus: 2
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: hostname
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-193.19.1.el8_2.x86_64
  linkmode: dynamic
  memFree: 1684803584
  memTotal: 3956207616
  ociRuntime:
    name: runc
    package: runc-1.0.0-145.rc91.git24a3cf8.el8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4261408768
  swapTotal: 4261408768
  uptime: 6h 5m 6.05s (Approximately 0.25 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 10
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 8
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601649039
  BuiltTime: Fri Oct  2 16:30:39 2020
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-4.el8.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment] 2020-10-21 17:01
@jwhonce PTAL

**Comment by jwhonce** [comment] 2020-10-21 17:16
@mheon yup self assigned, talking with @baude about impact on endpoint handlers now

**Comment by jwhonce** [comment] 2020-12-07 16:57
@andrin55 Thanks for reporting the issue. I cannot reproduce on master which will be the next major release. You can see `< Content-Length: 2` below.

```
$ curl -s --unix-socket /run/user/1000/podman/podman.sock http://d/v1.28.0/_ping -vv
* Uses proxy env variable no_proxy == 'localhost,127.0.0.0/8,.local,192.168.250.53/24'
*   Trying /run/user/1000/podman/podman.sock:0...
* Connected to d (/run/user/1000/podman/podman.sock) port 80 (#0)
> GET /v1.28.0/_ping HTTP/1.1
> Host: d
> User-Agent: curl/7.71.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Api-Version: 1.40
< Builder-Version: 
< Buildkit-Version: 
< Cache-Control: no-cache
< Docker-Experimental: true
< Libpod-Api-Version: 2.0.0
< Libpod-Buildah-Version: 1.19.0-dev
< Pragma: no-cache
< Server: Libpod/2.0.0 (linux)
< Date: Mon, 07 Dec 2020 16:25:44 GMT
< Content-Length: 2
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host d left intact
OK>
```

```
$ curl --version
curl 7.71.1 (x86_64-redhat-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1h-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
$ cat /etc/os-release 
NAME=Fedora
VERSION="33 (Workstation Edition)"
$ git log
commit ef6748dc87126765cc97b6901d0f5adf297914d4 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Merge: aac03d4a3 bd2cfe0a9
```

**Comment by zhangguanzhang** [comment] 2020-12-08 01:54
I think this had bee fix by https://github.com/containers/podman/pull/8486
,so I will close this issue
/close

**Closed by zhangguanzhang** 2020-12-08 01:54 UTC
Labels: 3.0 Features, kind/bug
