### ISSUE TITLE
podman prints unclear "binary not found" warning with netavark backend

### ISSUE THREAD

**Issue by alanorth** [containers/podman#13412] opened 2022-03-03 09:27 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Unclear "binary not found" warning when using the netavark backend in podman 4.0.1. It's not clear what binary is missing. Podman commands seem to succeed despite this warning.

**Steps to reproduce the issue:**

1. Set `network_backend = "netavark"` in `/etc/containers/containers.conf`

2. Run any podman command

3. Command succeeds, but podman prints "WARN[0000]  binary not found, container dns will not be enabled" to stderr

**Describe the results you received:**
With the old CNI backend I get no message printed to stderr:

```console
$ podman info --format {{.Host.NetworkBackend}}
cni
```
But after setting the network backend to netavark I get:

```console
$ podman info --format {{.Host.NetworkBackend}}
WARN[0000]  binary not found, container dns will not be enabled 
netavark
```

**Describe the results you expected:**
No warning.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.1
API Version:  4.0.1
Go Version:   go1.17.7
Git Commit:   c8b9a2e3ec3630e9172499e15205c11b823c8107
Built:        Thu Feb 24 14:12:50 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.0-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: bdb4f6e56cd193d40b75ffc9725d4b74a18cb33c'
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: balozi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.16.11-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 1187782656
  memTotal: 16490004480
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.4.2-1
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.12-1
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8587571200
  swapTotal: 8589930496
  uptime: 75h 17m 51.98s (Approximately 3.12 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/aorth/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 2
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/aorth/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/aorth/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.1
  Built: 1645701170
  BuiltTime: Thu Feb 24 14:12:50 2022
  GitCommit: c8b9a2e3ec3630e9172499e15205c11b823c8107
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ pacman -Qi podman
Name            : podman
Version         : 4.0.1-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/podman
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : conmon  containers-common  crun  fuse-overlayfs  iptables  libdevmapper.so=1.02-64  libgpgme.so=11-64
                  libseccomp.so=2-64  slirp4netns
Optional Deps   : apparmor: for AppArmor support
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support
                  netavark: for a new container-network-stack implementation [installed]
                  podman-compose: for docker-compose compatibility
                  podman-docker: for Docker-compatible CLI
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 79.65 MiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Thu 24 Feb 2022 02:12:50 PM EAT
Install Date    : Thu 03 Mar 2022 09:48:15 AM EAT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

netavark version:

```
Name            : netavark
Version         : 1.0.1-1
Description     : Container network stack
Architecture    : x86_64
URL             : https://github.com/containers/netavark
Licenses        : Apache
Groups          : None
Provides        : container-network-stack
Depends On      : gcc-libs  glibc
Optional Deps   : aardvark-dns: for authorative DNS server
Required By     : containers-common
Optional For    : podman
Conflicts With  : None
Replaces        : None
Installed Size  : 6.13 MiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Fri 25 Feb 2022 02:20:53 AM EAT
Install Date    : Thu 03 Mar 2022 09:51:05 AM EAT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

The netavark pacakge on Arch contains:

```
netavark /usr/
netavark /usr/lib/
netavark /usr/lib/podman/
netavark /usr/lib/podman/netavark
netavark /usr/share/
netavark /usr/share/doc/
netavark /usr/share/doc/netavark/
netavark /usr/share/doc/netavark/README.md
netavark /usr/share/man/
netavark /usr/share/man/man1/
netavark /usr/share/man/man1/netavark.1.gz
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Arch Linux on a physical machine.

**Comment by MarkusSchoelzel** [comment] 2022-03-03 15:05
it's probably https://github.com/containers/aardvark-dns which is not found or missing

**Comment by flouthoc** [comment] 2022-03-03 15:37
@cloudlena @alanorth This is correct. Following message is just a warning notifying users that `dns` will not work if `aardvark-dns` is not installed. Did you manually build and install on `Arch` ? I'm closing this issue since its already resolved but lets continue discussion below.

**Comment by cloudlena** [comment] 2022-03-03 15:40
The problem is that `aardvark-dns` is only an optional dependency (instead of a normal "strict" dependency) of `netavark` so it doesn't get installed automatically by Arch Linux.

**Comment by rhatdan** [comment] 2022-03-03 15:51
@flouthoc could you fix the error message to make it clear which binary is missing.

**Comment by flouthoc** [comment] 2022-03-03 15:55
@rhatdan Sure.

**Comment by flouthoc** [comment] 2022-03-03 16:02
@cloudlena @rhatdan Above PR fixes the error message.

**Comment by alanorth** [comment] 2022-03-03 17:33
Thank you. I completely missed that there was an optional package `aardvark-dns` in Arch Linux. Now I know, though improving the warning message will help users in the future!

**Closed** 2022-03-06 13:30 UTC
Labels: kind/bug

**Comment by tobiashochguertel** [comment] 2022-06-12 01:20
I have this error with Fedora Server 36.

````
Linux fedora 5.17.13-300.fc36.x86_64 #1 SMP PREEMPT Mon Jun 6 14:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

`dnf` doesn't find any package with the name `aardvark-dns`. How can I fix this issue?
