### ISSUE TITLE
Use native WSL systemd support

### ISSUE THREAD

**Issue by Karsten7** [containers/podman#18985] opened 2023-06-23 18:05 UTC
WSL can run systemd natively ([Systemd support is now available in WSL!](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/)). 

One can opt-in to enable systemd by adding 
```
[boot]
systemd=true
```
to `/etc/wsl.conf`.

Currently, systemd is enabled by using a nested process namespace. This was a typical workaround, that should no longer be necessary. 

Using the native systemd support should make podman-wsl-fedora behave more similar to other WSL distributions and Fedora Linux systems. (E.g., issues like https://github.com/containers/podman-wsl-fedora/issues/9 would be avoided.)

**Comment by Karsten7** [comment] 2023-06-23 18:16
The bootstrap script at https://github.com/containers/podman/blob/main/pkg/machine/wsl/machine.go#L73 creates the nested process namespace for systemd. This file contains a lot more special handling of systemd for WSL that should no longer be necessary once the native systemd support is used instead.

**Comment by vrothberg** [comment] 2023-06-26 06:04
Thanks for reaching out, @Karsten7 !

@n1hility, what do you think?

**Comment by Luap99** [comment] 2023-06-26 09:15
Duplicate of #15967

**Closed by Luap99** 2023-06-26 09:15 UTC
Labels: kind/feature, windows
